//! Package-backed mirror of the compiled `rules_tables` module `ultimate_equipment::equipment_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[cfg_attr(test, derive(schemars::JsonSchema))]
#[cfg_attr(test, schemars(rename = "ultimate_equipment__equipment_tables__EquipmentCategory"))]
pub enum EquipmentCategory {
    General,
    ArmsArmor,
    MagicItems,
    Equipmods,
}
impl EquipmentCategory {
    pub const ALL: &'static [EquipmentCategory] = &[
        EquipmentCategory::General,
        EquipmentCategory::ArmsArmor,
        EquipmentCategory::MagicItems,
        EquipmentCategory::Equipmods,
    ];
}
#[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
#[cfg_attr(test, derive(schemars::JsonSchema))]
#[cfg_attr(test, schemars(rename = "ultimate_equipment__equipment_tables__EquipmentTableEntry"))]
pub struct EquipmentTableEntry {
    pub key: &'static str,
    pub category: EquipmentCategory,
    pub name: &'static str,
    /// Cost in gold pieces from the corpus `COST:` token. `None` when the
    /// token is absent or a non-numeric PCGen formula this table does not
    /// evaluate.
    pub cost_gp: Option<f64>,
    /// Weight in pounds from the corpus `WT:` token. `None` when the
    /// corpus record carries no `WT:` token (true for every
    /// `ue_equipmods` record -- equipment *modifiers* carry no
    /// independent weight, matching every other book's own established
    /// finding).
    pub weight_lbs: Option<f64>,
    /// Descriptive text: the corpus `DESC:` token, the `SPROP:` token, or
    /// both joined with a space when a record carries both. `None` only
    /// when the corpus record has neither.
    pub description: Option<&'static str>,
}
pub fn equipment_tables() -> &'static [EquipmentTableEntry] {
    crate::rules_core::rules_catalog::rows::<EquipmentTableEntry>(
        "ultimate_equipment/equipment_tables/equipment_tables",
    )
}
pub fn equipmod_tables() -> &'static [EquipmentTableEntry] {
    crate::rules_core::rules_catalog::rows::<EquipmentTableEntry>(
        "ultimate_equipment/equipment_tables/equipmod_tables",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_has_1369_equipment_records() {
        assert_eq!(equipment_tables().len(), 1369);
    }

    #[test]
    fn catalog_has_180_equipmod_records() {
        assert_eq!(equipmod_tables().len(), 180);
    }

    #[test]
    fn every_record_carries_a_real_key_and_name() {
        for e in equipment_tables().iter().chain(equipmod_tables()) {
            assert!(!e.key.is_empty());
            assert!(!e.name.is_empty());
        }
    }

    #[test]
    fn keys_are_unique_within_each_table() {
        let eq_keys: std::collections::BTreeSet<&str> = equipment_tables().iter().map(|e| e.key).collect();
        assert_eq!(eq_keys.len(), equipment_tables().len());
        let mod_keys: std::collections::BTreeSet<&str> = equipmod_tables().iter().map(|e| e.key).collect();
        assert_eq!(mod_keys.len(), equipmod_tables().len());
    }

    // `SD31-W3-INTEGRATE-001` — adversarial-review CONFIRMED finding:
    // `ue_equip_magic_items:714` is a corpus row TWO items long, glued
    // together by a missing newline (the second item's name is even
    // embedded mid-token inside the first item's `BONUS:SITUATION` value:
    // `...TYPE=CompetenceMitre of the Hierophant`). PCGen's own last-
    // token-wins parse would read `COST:18000`/`WT:2` for a key first
    // matched on `Miser's Mask`, but the real Miser's Mask (p.246) is
    // COST 3000 / WT 1 — the 18000/2 pair belongs to the row's SECOND,
    // unshipped item, "Mitre of the Hierophant" (p.247). Verified against
    // the raw row directly: `sed -n '714p'
    // $PCGEN_CORPUS_ROOT/pathfinder/paizo/roleplaying_game/ultimate_equipment/ue_equip_magic_items
    // | tr '\t' '\n'` shows `COST:3000`/`WT:1`/`SOURCEPAGE:p.246` BEFORE
    // the embedded "Mitre of the Hierophant" name, and `COST:18000`/`WT:2`/
    // `SOURCEPAGE:p.247` after it. Fixed here (the table this record's
    // `cost_gp`/`weight_lbs` actually render from, per
    // `apps/desktop/src-tauri/src/equipment_catalog.rs`); a full second
    // "Mitre of the Hierophant" table entry is a separate follow-on
    // (`OPEN-ISSUES.md` row 40) — the shared malformed line has no clean
    // column boundary for a citation resolver to key a second record off
    // of without a raw-line-splitting change this fix does not make.
    #[test]
    fn misers_mask_ships_its_own_item_s_cost_and_weight_not_the_glued_second_item_s() {
        let e = equipment_tables()
            .iter()
            .find(|e| e.key == "Miser's Mask")
            .expect("Miser's Mask must still be in the catalog");
        assert_eq!(e.cost_gp, Some(3000.0), "Miser's Mask is 3,000 gp per p.246, not 18,000 gp");
        assert_eq!(e.weight_lbs, Some(1.0), "Miser's Mask is 1 lb per p.246, not 2 lb");
    }
}
