//! Package-backed mirror of the compiled `rules_tables` module `ultimate_equipment::equipment_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::ultimate_equipment::equipment_tables::EquipmentCategory;
pub use rt::ultimate_equipment::equipment_tables::EquipmentTableEntry;
pub fn equipment_tables() -> &'static [EquipmentTableEntry] {
    crate::rules_core::rules_catalog::rows::<EquipmentTableEntry>(
        "ultimate_equipment/equipment_tables/equipment_tables",
    )
}
pub fn equipmod_tables() -> &'static [EquipmentTableEntry] {
    crate::rules_core::rules_catalog::rows::<EquipmentTableEntry>(
        "ultimate_equipment/equipment_tables/equipmod_tables",
    )
}
