#!/usr/bin/env python3
"""Bootstrap generator for src/rules_core/rules_catalog/** (SD-37 E4a.2).

Mirrors the module tree of src/rules_core/rules_tables/ as a package-backed view:
  - row/id types and pure functions are re-exported from where they are defined;
  - every registered table (rules_data_package::TABLE_IDS) becomes a loader-backed Table / fn;
  - every view (rules_data_package::VIEWS) and every function that reads a table is copied and
    reads the package-backed tables instead.
Run from the repo root:  python3 <this file> <scratchpad-with-rtparse/analyze>
"""
import sys,os,re,collections,shutil
HERE=os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0,HERE)
import analyze as A
from overrides import OVERRIDES, ROOT_EXTRA, EXCLUDE_MODS

OUT='src/rules_core/rules_catalog'
RT='rt'
CAT='crate::rules_core::rules_catalog'

st,bu,vi=A.registry()
stp=A.ids_to_pairs(st);bup=A.ids_to_pairs(bu);vip=A.ids_to_pairs(vi)
sid={}   # (chain,name)->id
for i in st+bu+vi:
    parts=i.split('/'); sid[(tuple(parts[:-1]),parts[-1])]=i
reg,reads=A.flagged_reads()
tok=re.compile(r'[A-Za-z_][A-Za-z0-9_]*')
STATIC_NAMES={n for (c,n) in stp if A.items(c) and any(it['name']==n and it['kw'] in('const','static') for it in A.items(c))}
STATIC_NAMES|={n for (c,n) in bup if any(it['name']==n and it['kw'] in('const','static') for it in A.items(c))}

def vis_of(it): return it['vis']
def is_test(it): return 'cfg(test)' in re.sub(r'\s','',it['attrs'])

def elem_type(ty):
    ty=ty.strip()
    m=re.match(r"&\s*(?:'static\s+)?",ty)
    if m: ty=ty[m.end():].strip()
    if ty.startswith('['):
        d=0;j=0
        for j,ch in enumerate(ty):
            if ch=='[': d+=1
            elif ch==']':
                d-=1
                if d==0: break
        inner=ty[1:j]
        # split top-level ';'
        d=0;cut=None
        for k,ch in enumerate(inner):
            if ch in '([<': d+=1
            elif ch in ')]>': d-=1
            elif ch==';' and d==0: cut=k;break
        return (inner if cut is None else inner[:cut]).strip()
    return None

def static_decl_type(it):
    t=it['code']
    m=re.match(r'(?:pub(?:\([^)]*\))?\s+)?(?:const|static)\s+(?:mut\s+)?[A-Za-z_0-9]+\s*:\s*',t)
    if not m: return None
    rest=t[m.end():]
    d=0
    for k,ch in enumerate(rest):
        if ch in '([<': d+=1
        elif ch in ')]>': 
            if not (ch=='>' and rest[k-1]=='-'): d-=1
        elif ch=='=' and d==0:
            return rest[:k].strip()
    return None

def fn_ret(it):
    t=it['code']
    i=t.index('fn ')
    # find matching ')' of params
    j=t.index('(',i); d=0
    for k in range(j,len(t)):
        if t[k]=='(': d+=1
        elif t[k]==')':
            d-=1
            if d==0: break
    rest=t[k+1:]
    m=re.match(r'\s*->\s*',rest)
    if not m: return None
    rest=rest[m.end():]
    cut=rest.index('{')
    return rest[:cut].strip()

def rewrite(text,wrapnames=True):
    text=text.replace('crate::rules_core::rules_tables::','crate::rules_core::rules_catalog::')
    text=re.sub(r'\brules_tables::','rules_catalog::',text)
    text=re.sub(r'\bconst\s+fn\b','fn',text)
    # registered static names used as values become (&*NAME)
    def wrap(m):
        nxt=text[m.end():].lstrip()[:1]
        return m.group(0) if nxt in ('.','[') else ('&*'+m.group(0))
    pat=re.compile(r'(?<![A-Za-z0-9_])(?:(?:[A-Za-z_][A-Za-z0-9_]*::)+)?(?:'+'|'.join(sorted(STATIC_NAMES,key=len,reverse=True))+r')(?![A-Za-z0-9_])')
    out=[];last=0
    protect=[(m.start(),m.end()) for m in re.finditer(r'\buse\s+[^;]*;',text)]
    def prot(s): return any(a<=s<b for a,b in protect)
    for m in (pat.finditer(text) if wrapnames else []):
        if prot(m.start()): continue
        s=m.start()
        prev=text[max(0,s-3):s]
        if prev.endswith('&*') or prev.endswith('(&*'): continue
        out.append(text[last:s]); out.append(wrap(m)); last=m.end()
    out.append(text[last:])
    return ''.join(out)

report=collections.defaultdict(list)
KIND_COUNT=collections.Counter()
EQUIV=[]
REPLACED=[]
DEBUG_IDS=set(open(HERE+'/debug_ids.txt').read().split()) if os.path.exists(HERE+'/debug_ids.txt') else set()
SKIP_IDS=set(open(HERE+'/skip_ids.txt').read().split()) if os.path.exists(HERE+'/skip_ids.txt') else set()
files_out={}

def emit_module(chain):
    its=A.items(chain)
    lines=[]
    modname='::'.join(chain) or '(root)'
    lines.append(f"//! Package-backed mirror of the compiled `rules_tables` module `{modname}` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).")
    lines.append("#![allow(dead_code, unused_imports, unused_variables, clippy::explicit_auto_deref, clippy::needless_borrow, clippy::type_complexity)]")
    lines.append("use crate::rules_core::rules_tables as rt;")
    lines.append("")
    by_name=collections.defaultdict(list)
    for it in its:
        if it['name']: by_name[it['name']].append(it)
    emitted=[]   # (kind,text,it)
    copied_code=[]
    pending_private=set()
    for it in its:
        if is_test(it): continue
        kw=it['kw'];name=it['name'];vis=vis_of(it)
        key=(chain,name)
        pubby = vis in('pub','pub(crate)')
        if (chain+(name,)) in OVERRIDES and kw!='use':
            pass
        if kw=='mod':
            if name in EXCLUDE_MODS: continue
            if '{' in it['code'].split(';')[0] and not it['code'].rstrip().endswith(';'):
                data=set(tok.findall(it['code']))&({n for _,n in reg if not A.is_type_name(n)}|{n for _,n in reads})
                if data:
                    report['inline-mod-copied'].append(modname+'::'+str(name)+' '+str(sorted(data)[:3]))
                    emitted.append(('copy',rewrite(it['text']),it)); copied_code.append(it['code']); continue
                emitted.append(('reexport',f"{vis} use {RT}::{'::'.join(chain)+'::' if chain else ''}{name};",it)); continue
            emitted.append(('mod',f"{vis+' ' if vis else ''}mod {name};",it)); continue
        if kw=='use':
            emitted.append(('use',rewrite(it['text'],False),it)); continue
        if kw=='macro_rules!':
            emitted.append(('macro',it['text'],it)); copied_code.append(it['code']); continue
        if kw=='impl':
            continue
        if kw in('struct','enum','union','type','trait'):
            if kw=='enum' and key in bup or key in stp and False: pass
            if pubby:
                emitted.append(('reexport',f"{vis} use {RT}::{'::'.join(chain)+'::' if chain else ''}{name};",it))
            else:
                pending_private.add(name)
            continue
        ov=OVERRIDES.get(chain+(name,))
        if ov is not None and kw in('fn','const fn','const','static'):
            REPLACED.append('/'.join(chain+(name,)))
            emitted.append(('override',ov,it)); copied_code.append(ov); continue
        if kw in('const','static') and key in stp|bup:
            ty=static_decl_type(it); ty=rewrite(ty,False) if ty else ty; e=elem_type(ty) if ty else None
            if not e:
                report['static-type-unknown'].append(f"{modname}::{name}: {ty}"); continue
            v=vis if vis in('pub','pub(crate)') else 'pub(crate)'
            REPLACED.append('/'.join(chain+(name,)))
            EQUIV.append(('table',chain,name,sid[key]))
            emitted.append(('table',f"{v} static {name}: {CAT}::Table<{e}> = {CAT}::Table::new(\"{sid[key]}\");",it)); continue
        if kw in('fn','const fn') and key in bup:
            ret=fn_ret(it)
            ret=rewrite(ret,False) if ret else ret
            if ret is None: report['built-no-ret'].append(f"{modname}::{name}"); continue
            m=re.match(r'Vec<(.*)>$',ret,re.S)
            v=vis if vis in('pub','pub(crate)') else 'pub(crate)'
            if m:
                body=f'{CAT}::rows_vec::<{m.group(1).strip()}>("{sid[key]}")'
            else:
                e=elem_type(ret)
                if not e: report['built-ret-unknown'].append(f"{modname}::{name}: {ret}"); continue
                body=f'{CAT}::rows::<{e}>("{sid[key]}")'
            REPLACED.append('/'.join(chain+(name,)))
            EQUIV.append(('call',chain,name,sid[key]))
            emitted.append(('built',f"{v} fn {name}() -> {ret} {{ {body} }}",it)); continue
        if kw in('fn','const fn') and (key in vip or key in reads):
            if key in vip and vis in ('pub','pub(crate)'): EQUIV.append(('call',chain,name,sid[key]))
            REPLACED.append('/'.join(chain+(name,)))
            txt=rewrite(it['text'])
            emitted.append(('copy',(re.sub(r'\s*#\[[^\]]*\]\s*','',it['attrs']) if False else '')+txt,it)); copied_code.append(it['code']); continue
        if kw in('const','static') and (key in vip):
            report['view-const'].append(f"{modname}::{name}"); continue
        # pure items
        if pubby:
            emitted.append(('reexport',f"{vis} use {RT}::{'::'.join(chain)+'::' if chain else ''}{name};",it))
        else:
            pending_private.add(name)
    # private dependencies of copied code
    need=set(tok.findall('\n'.join(copied_code)))
    done=set()
    changed=True
    while changed:
        changed=False
        for name in sorted(pending_private):
            if name in need and name not in done:
                done.add(name)
                for it in by_name[name]:
                    if is_test(it): continue
                    if it['kw'] in('fn','const fn','const','static'):
                        if (chain,name) in stp|bup|vip: continue
                        emitted.append(('copy',rewrite(it['text']),it)); need|=set(tok.findall(it['code'])); changed=True
                    elif it['kw'] in('struct','enum','type','trait','union'):
                        report['private-type-needed'].append(f"{modname}::{name}")
    for kind,_,_ in emitted: KIND_COUNT[kind]+=1
    # order: uses, mods, rest
    order={'use':0,'mod':1}
    body=[]
    for kind,text,it in sorted(emitted,key=lambda e:order.get(e[0],2)):
        body.append(text if text.endswith((';','}')) else text+';')
    return "\n".join(lines+body)+"\n"

def write_equivalence():
    out=['//! Generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`: every package-backed table and view equals the compiled source it replaces.',
         '#![allow(clippy::all)]','','use crate::rules_core::rules_tables as rt;','use std::fmt::Debug;','',
         'fn same<A: serde::Serialize + ?Sized, B: serde::Serialize + ?Sized>(id: &str, catalog: &A, compiled: &B) {',
         '    let catalog = serde_json::to_string(catalog).expect("serialise catalog rows");',
         '    let compiled = serde_json::to_string(compiled).expect("serialise compiled rows");',
         '    assert!(catalog == compiled, "{id}: package-backed rows differ from the compiled table");',
         '}','',
         'fn same_debug<A: Debug + ?Sized, B: Debug + ?Sized>(id: &str, catalog: &A, compiled: &B) {',
         '    assert!(format!("{catalog:?}") == format!("{compiled:?}"), "{id}: package-backed rows differ from the compiled table");',
         '}','']
    tables=[e for e in EQUIV if e[0]=='table']; calls=[e for e in EQUIV if e[0]=='call']
    def pth(root,chain,name): return root+'::'+'::'.join(chain+(name,)) if True else ''
    out.append('pub(super) const TABLES: usize = %d;'%len(tables))
    out.append('pub(super) const CALLS: usize = %d;'%len(calls))
    out.append('')
    out.append('#[test]')
    out.append('fn every_package_table_equals_its_compiled_table() {')
    for k,chain,name,i in tables:
        f='same_debug' if i in DEBUG_IDS else 'same'
        if i in SKIP_IDS: continue
        out.append(f'    {f}("{i}", &*{CAT}::{"::".join(chain+(name,))}, &{RT}::{"::".join(chain+(name,))});')
    out.append('}')
    out.append('')
    out.append('#[test]')
    out.append('fn every_package_view_equals_its_compiled_function() {')
    for k,chain,name,i in calls:
        f='same_debug' if i in DEBUG_IDS else 'same'
        if i in SKIP_IDS: continue
        out.append(f'    {f}("{i}", &{CAT}::{"::".join(chain+(name,))}(), &{RT}::{"::".join(chain+(name,))}());')
    out.append('}')
    open(OUT+'/equivalence_tests.rs','w').write('\n'.join(out)+'\n')

def path_for(chain):
    if not chain: return OUT+'/mod.rs'
    a=A.FILES[chain]
    rel=os.path.relpath(a,A.R)
    return OUT+'/'+rel

WIDEN=[('crb/class_tables.rs','GoodSaves'),('crb/class_tables.rs','ClassMeta'),('simple_kind_tables.rs','SimpleKindTable')]

def widen_fields(rel,struct):
    f=A.R+'/'+rel
    s=open(f).read()
    m=re.search(r'(?:pub(?:\([a-z]+\))? )?struct '+struct+r'\b[^{]*\{(.*?)\n\}',s,re.S)
    body=m.group(1)
    def fix(mm): return mm.group(1)+'pub(crate) '+mm.group(2)
    body2=re.sub(r'^(    )((?!pub)[a-z_][a-z_0-9]*\s*:)',fix,body,flags=re.M)
    if body2!=body:
        open(f,'w').write(s[:m.start(1)]+body2+s[m.end(1):])
        print('widened',rel,struct)

def main():
    for rel,struct in WIDEN: widen_fields(rel,struct)
    shutil.rmtree(OUT+'_gen',ignore_errors=True)
    n=0
    for chain in sorted(A.FILES):
        if any(p in EXCLUDE_MODS for p in chain): continue
        if not chain: continue
        txt=emit_module(chain)
        p=path_for(chain)
        files_out[p]=txt
    # root module list from rt mod.rs
    for p,txt in files_out.items():
        os.makedirs(os.path.dirname(p),exist_ok=True)
        open(p,'w').write(txt); n+=1
    write_equivalence()
    tmpl=open(HERE+'/control_tests_template.rs.tmpl').read()
    open(OUT+'/control_tests.rs','w').write(tmpl+'const REPLACED: &[&str] = &[\n'+''.join(f'    "{r}",\n' for r in sorted(set(REPLACED)))+'];\n')
    shutil.copy(HERE+'/override_tests.rs.tmpl',OUT+'/override_tests.rs')
    root=emit_module(())  # root: rt/mod.rs
    hdr=open(HERE+'/root_header.rs.tmpl').read()
    body='\n'.join(root.split('\n')[4:])
    open(OUT+'/mod.rs','w').write(hdr+body)
    n+=1
    import subprocess
    subprocess.run(['rustfmt','--edition','2024']+sorted(files_out)+[OUT+'/mod.rs',OUT+'/equivalence_tests.rs',OUT+'/control_tests.rs',OUT+'/override_tests.rs'],check=False)
    print('wrote',n,'files')
    print('emitted items by kind:',dict(sorted(KIND_COUNT.items())))
    for k,v in report.items():
        print(k,len(v)); 
        for x in v[:40]: print('   ',x)
    return root
if __name__=='__main__':
    root=main()
