//! bestiary_6 companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py bestiary_6`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `b6_races_companion.lst` -- 14 companion creature rows
//!   * `b6_abilities_companion.lst` -- 12 companion ability rows

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, NaturalAttackDamageBonus, SkillAbilityDiffBonus, Speed, StatAdjustment};

/// Every bestiary_6 companion creature (14 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Companion (Amargasaurus)",
        name: "Companion (Amargasaurus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }, NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(3),
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Amargasaurus"],
        external_ability_refs: &["Scent"],
        source_file: "b6_races_companion.lst",
        source_line: 4,
    },
    CompanionRecord {
        key: "Companion (Brontotherium)",
        name: "Companion (Brontotherium)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: Some("1d10") }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Slam", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 6 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(8),
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Brontotherium"],
        external_ability_refs: &["Scent"],
        source_file: "b6_races_companion.lst",
        source_line: 5,
    },
    CompanionRecord {
        key: "Companion (Deinotherium)",
        name: "Companion (Deinotherium)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }, NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(4),
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Deinotherium"],
        external_ability_refs: &["Scent"],
        source_file: "b6_races_companion.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Companion (Devil Monkey)",
        name: "Companion (Devil Monkey)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionPrimate"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }],
        natural_armor: Some(3),
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Devil Monkey"],
        external_ability_refs: &[],
        source_file: "b6_races_companion.lst",
        source_line: 7,
    },
    CompanionRecord {
        key: "Companion (Dunkleosteus)",
        name: "Companion (Dunkleosteus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Swim", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(4),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Dunkleosteus"],
        external_ability_refs: &[],
        source_file: "b6_races_companion.lst",
        source_line: 8,
    },
    CompanionRecord {
        key: "Companion (Elasmotherium)",
        name: "Companion (Elasmotherium)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Gore", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 6 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(4),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Elasmotherium"],
        external_ability_refs: &["Scent"],
        source_file: "b6_races_companion.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Companion (Giganotosaurus)",
        name: "Companion (Giganotosaurus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }],
        natural_armor: Some(4),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Giganotosaurus"],
        external_ability_refs: &["Scent"],
        source_file: "b6_races_companion.lst",
        source_line: 10,
    },
    CompanionRecord {
        key: "Companion (Kentrosaurus)",
        name: "Companion (Kentrosaurus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Tail", damage_dice: Some("1d8") }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Tail", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(2),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Kentrosaurus"],
        external_ability_refs: &["Kentrosaurus ~ Impaling Strike"],
        source_file: "b6_races_companion.lst",
        source_line: 11,
    },
    CompanionRecord {
        key: "Companion (Mokele-Mbembe)",
        name: "Companion (Mokele-Mbembe)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }],
        natural_armor: Some(5),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Mokele-Mbembe"],
        external_ability_refs: &["Scent"],
        source_file: "b6_races_companion.lst",
        source_line: 12,
    },
    CompanionRecord {
        key: "Companion (Quetzalcoatlus)",
        name: "Companion (Quetzalcoatlus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))|PREVARLT:CompanionAdvancement,1" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 10 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: Some(2),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Quetzalcoatlus"],
        external_ability_refs: &["Scent"],
        source_file: "b6_races_companion.lst",
        source_line: 13,
    },
    CompanionRecord {
        key: "Companion (Raven (Giant))",
        name: "Companion (Raven (Giant))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Raven (Giant)"],
        external_ability_refs: &["Giant Raven ~ Scavenger"],
        source_file: "b6_races_companion.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Companion (Titanoboa)",
        name: "Companion (Titanoboa)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 6 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(4),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Titanoboa"],
        external_ability_refs: &["Scent"],
        source_file: "b6_races_companion.lst",
        source_line: 15,
    },
    CompanionRecord {
        key: "Familiar (Coral Capuchin)",
        name: "Familiar (Coral Capuchin)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }, Speed { mode: "Fly", feet: 40 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Magical Beast"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Magical Beast:2"),
        type_segments: &["Companion", "Familiar", "Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.66"),
        ability_keys: &[],
        external_ability_refs: &["Amphibious"],
        source_file: "b6_races_companion.lst",
        source_line: 18,
    },
    CompanionRecord {
        key: "Familiar (Mockingfey)",
        name: "Familiar (Mockingfey)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Fey"),
        race_subtype: None,
        monster_class: Some("Fey:3"),
        type_segments: &["Companion", "Familiar", "Fey"],
        natural_attacks: &[NaturalAttack { name: "Talons", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.189"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b6_races_companion.lst",
        source_line: 19,
    },
];

/// Every bestiary_6 companion ability record (12 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Amargasaurus",
        name: "Companion Advancement (Amargasaurus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Amargasaurus)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 4,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Brontotherium",
        name: "Companion Advancement (Brontotherium)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Brontotherium)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 5,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Deinotherium",
        name: "Companion Advancement (Deinotherium)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Deinotherium)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 6,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Devil Monkey",
        name: "Companion Advancement (Devil Monkey)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Devil Monkey)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 7,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dunkleosteus",
        name: "Companion Advancement (Dunkleosteus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dunkleosteus)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 8,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Elasmotherium",
        name: "Companion Advancement (Elasmotherium)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Elasmotherium)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 9,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Giganotosaurus",
        name: "Companion Advancement (Giganotosaurus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Giganotosaurus)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 10,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Kentrosaurus",
        name: "Companion Advancement (Kentrosaurus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Kentrosaurus)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 11,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Mokele-Mbembe",
        name: "Companion Advancement (Mokele-Mbembe)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Mokele-Mbembe)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 12,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Quetzalcoatlus",
        name: "Companion Advancement (Quetzalcoatlus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Quetzalcoatlus)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 13,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Raven (Giant)",
        name: "Companion Advancement (Raven (Giant))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Raven (Giant))"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 14,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Titanoboa",
        name: "Companion Advancement (Titanoboa)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Titanoboa)"],
        cross_book_owners: &[],
        source_file: "b6_abilities_companion.lst",
        source_line: 15,
    },
];
