//! The verbatim ingest tails the shipped feat catalogs used to carry, kept on
//! the converter side as the round-trip oracle for the typed live form.
//!
//! SD-35 `AT-35-E6-003-SWEEP` cycle 7 (`decisions.md` §11 — no PCGen in live
//! code; `epic-breakdown.md` `### AT-35-E6-003`). Before this cycle every
//! `FeatEffectBonus` row stored its corpus `BONUS:` token whole, tail included,
//! so a `TYPE=<label>` stacking label and every `PRE<FAMILY>:` guard sat in
//! `src/rules_core/`. The live tables now carry `bonus_type` and `conditions`
//! in our own schema instead.
//!
//! This table is the proof that the conversion lost nothing: one row per
//! converted bonus, holding the **verbatim** tail the ingest record wrote, and
//! a test that rebuilds that string from the live typed form and compares it
//! character for character. It is converter-side data — nothing under a live
//! root reads it — and it is kept, not deleted, because Starfinder ingests the
//! same format (`decisions.md` §11, what is kept).
//!
//! Generated by
//! `docs/release/SD-35-corpus-sheet-completion/artifacts/epic-6-pcgen-exit/AT-35-E6-003-SWEEP_cycle7_type_feat_effect_tails.py`.
//! Do not hand-edit; re-run the generator.

/// One converted bonus's verbatim ingest tail.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FeatEffectTail {
    /// Which shipped feat catalog the bonus lives in: `crb`, `apg`, `acg`, `arg`.
    pub catalog: &'static str,
    /// The feat record's `key`.
    pub feat_key: &'static str,
    /// 0-based index of the bonus within that feat's `effect` slice.
    pub index: usize,
    /// The tail exactly as the ingest record wrote it, pipe-joined.
    pub tail: &'static str,
}

/// Every converted tail, in catalog source order.
pub const FEAT_EFFECT_TAILS: &[FeatEffectTail] = &[
    FeatEffectTail { catalog: "acg", feat_key: "Steadfast Personality", index: 1, tail: "PREVARLT:WIS,0" },
    FeatEffectTail { catalog: "arg", feat_key: "Tail Terror", index: 0, tail: "PREEQUIP:1,TYPE=KoboldTailAttachment" },
    FeatEffectTail { catalog: "arg", feat_key: "Angel Wings", index: 1, tail: "PREVARLT:ENCUMBERANCE,1,var(\\\"COUNT[EQTYPE.ARMOR.EQUIPPED.IS.MEDIUM]\\\"),1,var(\\\"COUNT[EQTYPE.ARMOR.EQUIPPED.IS.HEAVY]\\\"),1" },
    FeatEffectTail { catalog: "arg", feat_key: "Armor of the Pit", index: 0, tail: "TYPE=Base|!PREABILITY:1,CATEGORY=Special Ability,Scaled Skin C ~ Tiefling,Scaled Skin E ~ Tiefling,Scaled Skin F ~ Tiefling" },
    FeatEffectTail { catalog: "arg", feat_key: "Armor of the Pit", index: 1, tail: "TYPE=Resistance" },
    FeatEffectTail { catalog: "arg", feat_key: "Draconic Aspect", index: 0, tail: "TYPE=Base|PREABILITY:1,CATEGORY=Special Ability,Kobold ~ Dragon-Scaled" },
    FeatEffectTail { catalog: "arg", feat_key: "Draconic Breath", index: 0, tail: "!PREABILITY:1,CATEGORY=Special Ability,Kobold Sorcerer Bloodline,Draconic Bloodline" },
    FeatEffectTail { catalog: "arg", feat_key: "Draconic Breath", index: 1, tail: "PREABILITY:1,CATEGORY=Special Ability,Kobold Sorcerer Bloodline,Draconic Bloodline" },
    FeatEffectTail { catalog: "arg", feat_key: "Drow Nobility", index: 0, tail: "TYPE=Boolean" },
    FeatEffectTail { catalog: "arg", feat_key: "Expanded Fiendish Resistance (Acid)", index: 0, tail: "TYPE=Resistance" },
    FeatEffectTail { catalog: "arg", feat_key: "Expanded Fiendish Resistance (Cold)", index: 0, tail: "TYPE=Resistance" },
    FeatEffectTail { catalog: "arg", feat_key: "Expanded Fiendish Resistance (Electricity)", index: 0, tail: "TYPE=Resistance" },
    FeatEffectTail { catalog: "arg", feat_key: "Expanded Fiendish Resistance (Fire)", index: 0, tail: "TYPE=Resistance" },
    FeatEffectTail { catalog: "arg", feat_key: "Flame Heart", index: 1, tail: "TYPE=Resistance" },
    FeatEffectTail { catalog: "arg", feat_key: "Greater Drow Nobility", index: 0, tail: "TYPE=Boolean" },
    FeatEffectTail { catalog: "arg", feat_key: "Greater Drow Nobility", index: 1, tail: "TYPE=Boolean" },
    FeatEffectTail { catalog: "arg", feat_key: "Human Spirit", index: 0, tail: "PRELEVELMAX:4" },
    FeatEffectTail { catalog: "arg", feat_key: "Improved Drow Nobility", index: 0, tail: "TYPE=Boolean" },
    FeatEffectTail { catalog: "arg", feat_key: "Improved Drow Nobility", index: 1, tail: "TYPE=Base" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 0, tail: "!PRESKILL:1,Acrobatics=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 1, tail: "!PRESKILL:1,Appraise=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 2, tail: "!PRESKILL:1,Bluff=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 3, tail: "!PRESKILL:1,Climb=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 4, tail: "!PRESKILL:1,TYPE.Craft=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 5, tail: "!PRESKILL:1,Diplomacy=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 6, tail: "!PRESKILL:1,Disguise=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 7, tail: "!PRESKILL:1,Disable Device=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 8, tail: "!PRESKILL:1,Escape Artist=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 9, tail: "!PRESKILL:1,Fly=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 10, tail: "!PRESKILL:1,Handle Animal=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 11, tail: "!PRESKILL:1,Heal=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 12, tail: "!PRESKILL:1,Intimidate=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 13, tail: "!PRESKILL:1,Linguistics=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 14, tail: "!PRESKILL:1,TYPE.Knowledge=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 15, tail: "!PRESKILL:1,Perception=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 16, tail: "!PRESKILL:1,TYPE.Perform=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 17, tail: "!PRESKILL:1,TYPE.Profession=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 18, tail: "!PRESKILL:1,Ride=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 19, tail: "!PRESKILL:1,Sense Motive=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 20, tail: "!PRESKILL:1,Sleight of Hand=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 21, tail: "!PRESKILL:1,Spellcraft=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 22, tail: "!PRESKILL:1,Stealth=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 23, tail: "!PRESKILL:1,Survival=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 24, tail: "!PRESKILL:1,Swim=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Improvisation", index: 25, tail: "!PRESKILL:1,Use Magic Device=1" },
    FeatEffectTail { catalog: "arg", feat_key: "Sure and Fleet", index: 0, tail: "TYPE=Racial" },
    FeatEffectTail { catalog: "arg", feat_key: "Wings of Air", index: 0, tail: "PREVAREQ:ENCUMBERANCE,0" },
    FeatEffectTail { catalog: "apg", feat_key: "Elemental Fist", index: 3, tail: "PREMULT:1,[PREVAREQ:ElementalFistGranted,1],[PREMULT:3,[PRETOTALAB:8],[PREABILITY:1,CATEGORY=FEAT,Improved Unarmed Strike],[PRESTAT:2,CON=13,WIS=13]]" },
    FeatEffectTail { catalog: "apg", feat_key: "Breadth of Experience", index: 1, tail: "TYPE=Boolean" },
    FeatEffectTail { catalog: "apg", feat_key: "Ironhide", index: 0, tail: "TYPE=Base.STACK" },
    FeatEffectTail { catalog: "apg", feat_key: "Steel Soul", index: 0, tail: "TYPE=Racial" },
    FeatEffectTail { catalog: "apg", feat_key: "Steel Soul", index: 1, tail: "TYPE=Boolean" },
    FeatEffectTail { catalog: "crb", feat_key: "Agile Maneuvers", index: 0, tail: "PRESIZEGT:T" },
    FeatEffectTail { catalog: "crb", feat_key: "Combat Expertise", index: 0, tail: "TYPE=Base" },
    FeatEffectTail { catalog: "crb", feat_key: "Combat Expertise", index: 1, tail: "TYPE=Base" },
    FeatEffectTail { catalog: "crb", feat_key: "Combat Expertise", index: 2, tail: "TYPE=Base" },
    FeatEffectTail { catalog: "crb", feat_key: "Dodge", index: 0, tail: "TYPE=Dodge" },
    FeatEffectTail { catalog: "crb", feat_key: "Far Shot", index: 0, tail: "TYPE=Base" },
    FeatEffectTail { catalog: "crb", feat_key: "Greater Shield Focus", index: 0, tail: "TYPE=Shield.STACK|PREEQUIP:1,TYPE=Shield" },
    FeatEffectTail { catalog: "crb", feat_key: "Improved Critical", index: 0, tail: "TYPE=NonStackingCrit" },
    FeatEffectTail { catalog: "crb", feat_key: "Improved Unarmed Strike", index: 0, tail: "TYPE=Boolean" },
    FeatEffectTail { catalog: "crb", feat_key: "Shield Focus", index: 0, tail: "TYPE=Shield.STACK|PREEQUIP:1,TYPE=Shield" },
    FeatEffectTail { catalog: "crb", feat_key: "Shield Master", index: 0, tail: "TYPE=Enhancement" },
    FeatEffectTail { catalog: "crb", feat_key: "Shield Master", index: 1, tail: "TYPE=Enhancement" },
    FeatEffectTail { catalog: "crb", feat_key: "Shield Master", index: 2, tail: "TYPE=Enhancement" },
    FeatEffectTail { catalog: "crb", feat_key: "Stunning Fist", index: 0, tail: "PREABILITY:1,CATEGORY=FEAT,Ability Focus (Stunning Fist)" },
    FeatEffectTail { catalog: "crb", feat_key: "Stunning Fist", index: 2, tail: "TYPE=NoStack" },
    FeatEffectTail { catalog: "crb", feat_key: "Two-Weapon Defense", index: 0, tail: "TYPE=Shield|PREMULT:1,[PREEQUIP:1,TYPE=Double],[PREMULT:2,[PREEQUIPPRIMARY:1,TYPE=Melee],[PREEQUIPSECONDARY:1,TYPE=Melee]]" },
    FeatEffectTail { catalog: "crb", feat_key: "Weapon Finesse", index: 0, tail: "TYPE=NotRanged" },
    FeatEffectTail { catalog: "crb", feat_key: "Endurance", index: 0, tail: "TYPE=Base" },
    FeatEffectTail { catalog: "crb", feat_key: "Fleet", index: 0, tail: "PREVARLT:ENCUMBERANCE,1,var(\\\"COUNT[EQTYPE.ARMOR.EQUIPPED.IS.MEDIUM]\\\"),1,var(\\\"COUNT[EQTYPE.ARMOR.EQUIPPED.IS.HEAVY]\\\"),1" },
    FeatEffectTail { catalog: "crb", feat_key: "Greater Spell Focus", index: 0, tail: "TYPE=SpellFocus" },
    FeatEffectTail { catalog: "crb", feat_key: "Skill Focus", index: 0, tail: "TYPE=SkillFocus" },
    FeatEffectTail { catalog: "crb", feat_key: "Spell Focus", index: 0, tail: "TYPE=SpellFocus" },
    FeatEffectTail { catalog: "crb", feat_key: "Toughness", index: 0, tail: "PRERULE:1,DAMAGE_HP" },
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules_core::rules_tables::advanced_race_guide::feats as arg_feats;
    use crate::rules_core::rules_tables::crb::feats::{ConditionItem, EffectCondition};
    use crate::rules_core::rules_tables::{acg, apg, crb};

    /// Rebuilds one guard's verbatim ingest token from the typed live form.
    fn rebuild(condition: &EffectCondition) -> String {
        let mut parts: Vec<String> = Vec::new();
        for ConditionItem { facet, value } in condition.items {
            match facet {
                None => parts.push((*value).to_string()),
                Some(f) => parts.push(format!("{f}={value}")),
            }
        }
        for alternative in condition.alternatives {
            parts.push(format!("[{}]", rebuild(alternative)));
        }
        format!(
            "{}PRE{}:{}",
            if condition.negated { "!" } else { "" },
            condition.family,
            parts.join(",")
        )
    }

    fn tail_of(bonus_type: Option<&'static str>, conditions: &'static [EffectCondition]) -> String {
        let mut parts: Vec<String> = Vec::new();
        if let Some(label) = bonus_type {
            parts.push(format!("TYPE={label}"));
        }
        parts.extend(conditions.iter().map(rebuild));
        parts.join("|")
    }

    /// Every live bonus that carries a tail, as `(catalog, feat key, index, rebuilt tail)`,
    /// walked straight out of the four shipped catalogs.
    fn live_tails() -> Vec<(String, String, usize, String)> {
        let mut out: Vec<(String, String, usize, String)> = Vec::new();
        for (catalog, entries) in [
            ("crb", crb::feats::feat_tables()),
            ("apg", apg::feats::feat_tables()),
            ("acg", acg::feats::feat_tables()),
        ] {
            for entry in entries {
                let Some(bonuses) = entry.effect else { continue };
                for (index, bonus) in bonuses.iter().enumerate() {
                    let tail = tail_of(bonus.bonus_type, bonus.conditions);
                    if !tail.is_empty() {
                        out.push((catalog.to_string(), entry.key.to_string(), index, tail));
                    }
                }
            }
        }
        for entry in arg_feats::feat_tables() {
            let Some(bonuses) = entry.effect else { continue };
            for (index, bonus) in bonuses.iter().enumerate() {
                let tail = tail_of(bonus.bonus_type, bonus.conditions);
                if !tail.is_empty() {
                    out.push(("arg".to_string(), entry.key.to_string(), index, tail));
                }
            }
        }
        out
    }

    /// The live typed form reproduces every converted ingest tail exactly.
    ///
    /// This is the whole proof of the cycle-7 conversion: if a facet, a guard,
    /// a negation or a nested alternative had been dropped or re-spelled on the
    /// way into `src/rules_core/`, the rebuilt string would differ here.
    #[test]
    fn every_converted_tail_round_trips_from_the_live_typed_form() {
        assert!(
            !FEAT_EFFECT_TAILS.is_empty(),
            "the round-trip table must not be empty -- an empty table proves nothing"
        );
        let live = live_tails();
        for row in FEAT_EFFECT_TAILS {
            let found = live
                .iter()
                .find(|(c, k, i, _)| c == row.catalog && k == row.feat_key && *i == row.index)
                .unwrap_or_else(|| {
                    panic!("no live bonus with a tail at {}/{}#{}", row.catalog, row.feat_key, row.index)
                });
            assert_eq!(
                found.3, row.tail,
                "{}/{}#{} tail did not round-trip",
                row.catalog, row.feat_key, row.index
            );
        }
    }

    /// Every live bonus that carries a tail is addressed by this table, and no
    /// row addresses a bonus that has none. Without this the round-trip test
    /// could pass while silently ignoring a converted row.
    #[test]
    fn the_table_addresses_exactly_the_live_bonuses_that_carry_a_tail() {
        let mut live: Vec<(String, String, usize)> = live_tails()
            .into_iter()
            .map(|(c, k, i, _)| (c, k, i))
            .collect();
        let mut listed: Vec<(String, String, usize)> = FEAT_EFFECT_TAILS
            .iter()
            .map(|r| (r.catalog.to_string(), r.feat_key.to_string(), r.index))
            .collect();
        live.sort();
        listed.sort();
        assert_eq!(listed, live);
    }
}
