//! The `PRE`-family prerequisite tokens the corpus **feat gap rows** carry,
//! relocated off the live side — SD-35 `AT-35-E6-003-SWEEP` cycle 3,
//! enforcing `decisions.md` §11. See
//! [`crate::pcgen_import::feat_prereq_tokens`] for why these moved, how a row
//! is addressed, and every lookup and gate over them.
//!
//! **Generated — do not hand-edit.** `cargo run --bin gen_feat_gap_tables`
//! writes this file and `rules_tables::feat_gap_tables.rs` together, off the
//! same pass over the live corpus, so the two can never drift apart.

use crate::pcgen_import::feat_prereq_tokens::FeatPrereqRow;
use crate::rules_core::rules_tables::RuleSetId;

/// The tokens the corpus gap rows carried, addressed by each record's index
         /// in `feat_gap_tables::feat_gap_rows_for(rule_set)`.
///
         /// 601 row(s) across 18 book(s).
         pub static FEAT_GAP_PREREQ_TOKENS: &[FeatPrereqRow] = &[
    // core_essentials — 15 of 15 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Ce, 0, "Ability Focus", &["PREABILITY:1,CATEGORY=Ability Focus,TYPE.Ability Focus"]),
    (RuleSetId::Ce, 1, "Awesome Blow", &["PREABILITY:2,CATEGORY=FEAT,Power Attack,Improved Bull Rush", "PRESIZEGTEQ:L", "PRESTAT:1,STR=25"]),
    (RuleSetId::Ce, 2, "Craft Construct", &["PREABILITY:2,CATEGORY=FEAT,Craft Magic Arms and Armor,Craft Wondrous Item", "PREMULT:1,[PRECLASS:1,SPELLCASTER=5],[PREVARGTEQ:CasterLevel_Highest,5]"]),
    (RuleSetId::Ce, 3, "Empower Spell-Like Ability ~ Ability", &["PRETEXT:Spell-like ability at caster level 6th or higher."]),
    (RuleSetId::Ce, 4, "Empower Spell-Like Ability ~ Spell", &["PRETEXT:Spell-like ability at caster level 6th or higher."]),
    (RuleSetId::Ce, 5, "Flyby Attack", &["PREMOVE:1,Fly=1"]),
    (RuleSetId::Ce, 6, "Hover", &["PREMOVE:1,Fly=1"]),
    (RuleSetId::Ce, 7, "Improved Natural Armor", &["PRESTAT:1,CON=13", "PREVARGTEQ:BONUS.COMBAT.AC.NaturalArmor,1"]),
    (RuleSetId::Ce, 8, "Improved Natural Attack", &["PRETOTALAB:4", "PREWEAPONPROF:1,TYPE.Natural"]),
    (RuleSetId::Ce, 9, "Multiattack", &["PREWEAPONPROF:3,TYPE.Natural"]),
    (RuleSetId::Ce, 10, "Multiweapon Fighting", &["PREHANDSGTEQ:3", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,13],[PREVARGTEQ:FeatDexRequirement,13]"]),
    (RuleSetId::Ce, 11, "Quicken Spell-Like Ability ~ Ability", &["PRETEXT:Spell-like ability at caster level 10th or higher."]),
    (RuleSetId::Ce, 12, "Quicken Spell-Like Ability ~ Spell", &["PRETEXT:Spell-like ability at caster level 10th or higher."]),
    (RuleSetId::Ce, 13, "Snatch", &["PRESIZEGTEQ:H"]),
    (RuleSetId::Ce, 14, "Wingover", &["PREMOVE:1,Fly=1"]),
    // advanced_race_guide — 35 of 48 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Arg, 5, "Angelic Flesh ~ Brazen", &["PREABILITY:1,CATEGORY=FEAT,Angelic Blood", "PREFACT:1,TEMPLATES,IsAasimar=true"]),
    (RuleSetId::Arg, 6, "Angelic Flesh ~ Golden", &["PREABILITY:1,CATEGORY=FEAT,Angelic Blood", "PREFACT:1,TEMPLATES,IsAasimar=true"]),
    (RuleSetId::Arg, 7, "Angelic Flesh ~ Silver", &["PREABILITY:1,CATEGORY=FEAT,Angelic Blood", "PREFACT:1,TEMPLATES,IsAasimar=true"]),
    (RuleSetId::Arg, 8, "Angelic Flesh ~ Steel", &["PREABILITY:1,CATEGORY=FEAT,Angelic Blood", "PREFACT:1,TEMPLATES,IsAasimar=true"]),
    (RuleSetId::Arg, 9, "Heavenly Radiance ~ Flare  Burst", &["PREABILITY:1,CATEGORY=FEAT,Heavenly Radiance", "PRELEVEL:MIN=1"]),
    (RuleSetId::Arg, 10, "Heavenly Radiance ~ Wake of Light", &["PREABILITY:1,CATEGORY=FEAT,Heavenly Radiance", "PRELEVEL:MIN=3"]),
    (RuleSetId::Arg, 11, "Heavenly Radiance ~ Searing Light", &["PREABILITY:1,CATEGORY=FEAT,Heavenly Radiance", "PRELEVEL:MIN=5"]),
    (RuleSetId::Arg, 12, "Heavenly Radiance ~ Wandering Star Motes", &["PREABILITY:1,CATEGORY=FEAT,Heavenly Radiance", "PRELEVEL:MIN=7"]),
    (RuleSetId::Arg, 13, "Heavenly Radiance ~ Sunbeam", &["PREABILITY:1,CATEGORY=FEAT,Heavenly Radiance", "PRELEVEL:MIN=9"]),
    (RuleSetId::Arg, 14, "Catfolk Exemplar ~ Enhanced Senses", &["PREFACT:1,TEMPLATES,IsCatfolk=true"]),
    (RuleSetId::Arg, 15, "Catfolk Exemplar ~ Fast Sprinter", &["PREFACT:1,TEMPLATES,IsCatfolk=true"]),
    (RuleSetId::Arg, 16, "Catfolk Exemplar ~ Sharp Claws", &["PREFACT:1,TEMPLATES,IsCatfolk=true"]),
    (RuleSetId::Arg, 17, "Blood Drinker Humanoid (Aquatic)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 18, "Blood Drinker Humanoid (Dwarf)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 19, "Blood Drinker Humanoid (Elf)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 20, "Blood Drinker Humanoid (Giant)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 21, "Blood Drinker Humanoid (Gnoll)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 22, "Blood Drinker Humanoid (Gnome)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 23, "Blood Drinker Humanoid (Goblinoid)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 24, "Blood Drinker Humanoid (Halfling)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 25, "Blood Drinker Humanoid (Human)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 26, "Blood Drinker Humanoid (Orc)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 27, "Blood Drinker Humanoid (Reptilian)", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 28, "Blood Drinker Monstrous Humanoid", &["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]),
    (RuleSetId::Arg, 32, "Black", &["PREMULT:1,[PREABILITY:1,CATEGORY=Kobold Scale Color,Black],[!PREABILITY:1,CATEGORY=Kobold Scale Color,TYPE.Kobold Scale Color]"]),
    (RuleSetId::Arg, 33, "Blue", &["PREMULT:1,[PREABILITY:1,CATEGORY=Kobold Scale Color,Blue],[!PREABILITY:1,CATEGORY=Kobold Scale Color,TYPE.Kobold Scale Color]"]),
    (RuleSetId::Arg, 34, "Green", &["PREMULT:1,[PREABILITY:1,CATEGORY=Kobold Scale Color,Green],[!PREABILITY:1,CATEGORY=Kobold Scale Color,TYPE.Kobold Scale Color]"]),
    (RuleSetId::Arg, 35, "Red", &["PREMULT:1,[PREABILITY:1,CATEGORY=Kobold Scale Color,Red],[!PREABILITY:1,CATEGORY=Kobold Scale Color,TYPE.Kobold Scale Color]"]),
    (RuleSetId::Arg, 36, "White", &["PREMULT:1,[PREABILITY:1,CATEGORY=Kobold Scale Color,White],[!PREABILITY:1,CATEGORY=Kobold Scale Color,TYPE.Kobold Scale Color]"]),
    (RuleSetId::Arg, 42, "Orc Weapon Expertise ~ Bully", &["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]),
    (RuleSetId::Arg, 43, "Orc Weapon Expertise ~ Defender", &["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]),
    (RuleSetId::Arg, 44, "Orc Weapon Expertise ~ Disrupter", &["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]),
    (RuleSetId::Arg, 45, "Orc Weapon Expertise ~ Killer", &["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]),
    (RuleSetId::Arg, 46, "Orc Weapon Expertise ~ Thug", &["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]),
    (RuleSetId::Arg, 47, "Orc Weapon Expertise ~ Trickster", &["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]),
    // ultimate_combat — 2 of 2 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Uc, 0, "Gundarme Bonus Feat", &["PREABILITY:1,CATEGORY=Archetype,Cavalier Archetype ~ Gundarme", "PREABILITY:7,CATEGORY=FEAT,Improved Bull Rush,Mounted Combat,Power Attack,Ride-By Attack,Spirited Charge,Spring Attack,Unseat"]),
    (RuleSetId::Uc, 1, "Deathless Master (Vigor/Wounds)", &["PREABILITY:4,CATEGORY=FEAT,Deathless Initiate (Vigor/Wound),Diehard (Vigor/Wound),Endurance,Ironhide", "PREFACT:1,TEMPLATES,IsOrc=true,IsHalfOrc=true", "PRERULE:1,DAMAGE_VW", "PRESTAT:2,STR=13,CON=15", "PRETOTALAB:9"]),
    // ultimate_intrigue — 3 of 3 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Ui, 0, "Gaze Reflection", &["PREABILITY:2,CATEGORY=Special Ability,Mesmerist ~ Mesmerist Tricks,Mesmerist ~ Bold Stare", "PRESKILL:1,Spellcraft=10", "PRETEXT:Spellcraft 10 ranks, bold stare and mesmerist tricks class features."]),
    (RuleSetId::Ui, 1, "Improved Legendary Influence", &["PREABILITY:1,CATEGORY=FEAT,Legendary Influence", "PREABILITY:2,CATEGORY=Special Ability,Medium ~ Propitiation,Medium ~ Spirit", "PRETEXT:Legendary Influence, lesser spirit power and propitiation class features."]),
    (RuleSetId::Ui, 2, "Legendary Influence", &["PREABILITY:1,CATEGORY=Special Ability,Medium ~ Spirit", "PRETEXT:Lesser spirit power class feature."]),
    // ultimate_magic — 6 of 12 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Um, 4, "Skill Focus Knowledge Arcana", &["PREABILITY:1,CATEGORY=Internal,Dragon Shaman Bonus Feats"]),
    (RuleSetId::Um, 5, "Skill Focus Intimidate", &["PREABILITY:1,CATEGORY=Internal,Saurian Shaman Bonus Feats"]),
    (RuleSetId::Um, 6, "Skill Focus Swim", &["PREABILITY:1,CATEGORY=Internal,Shark Shaman Bonus Feats"]),
    (RuleSetId::Um, 7, "Experimental Spellcaster", &["PRESPELLTYPE:1,ANY=0"]),
    (RuleSetId::Um, 10, "Extra Word", &["PREMULT:1,[PRECLASS:1,SPELLCASTER=1],[PREVARGTEQ:CasterLevel_Highest,1]", "PREMULT:1,[PREABILITY:1,CATEGORY=Archetype,TYPE.WordsOfPower],[PREABILITY:1,CATEGORY=FEAT,Experimental Spellcaster]"]),
    (RuleSetId::Um, 11, "Meta Word Mastery", &["PREMULT:1,[PREABILITY:1,CATEGORY=Archetype,TYPE.WordsOfPower],[PREABILITY:1,CATEGORY=FEAT,Experimental Spellcaster]"]),
    // ultimate_psionics — 1 of 1 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Upsi, 0, "Feral Combat Training", &["PREABILITY:2,CATEGORY=FEAT,Improved Unarmed Strike,Weapon Focus (TYPE=Natural)"]),
    // ultimate_wilderness — 1 of 1 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Uw, 0, "Extended Animal Focus", &["PREABILITY:1,CATEGORY=Special Ability,Hunter ~ Animal Focus"]),
    // horror_adventures — 60 of 61 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Ha, 0, "Absorb Spirit", &["PREVARGTEQ:PreStatScore_CON,13", "PRETEXT:Must have died at least once or been possessed by an undead creature."]),
    (RuleSetId::Ha, 1, "Aura Flare", &["PREVARGTEQ:PreStatScore_CHA,13", "PRETEXT:Aura, aura of good, or aura of evil class feature; channel energy 4d6; strong or overwhelming good or evil aura."]),
    (RuleSetId::Ha, 2, "Blood Feast", &["PREABILITY:1,CATEGORY=Internal,Bite"]),
    (RuleSetId::Ha, 3, "Blood Spurt", &["PRETOTALAB:2", "PRETEXT:Susceptibility to bleed damage."]),
    (RuleSetId::Ha, 4, "Bouncing Spell-Like Ability", &["PRETEXT:Spell-like ability at caster level 4th or higher."]),
    (RuleSetId::Ha, 5, "Brutal Coup de Grace", &["PREABILITY:2,CATEGORY=FEAT,Dazzling Display,Weapon Focus", "PRETOTALAB:5", "PRETEXT:Proficiency with the selected weapon."]),
    (RuleSetId::Ha, 6, "Brute Assault", &["PREABILITY:2,CATEGORY=FEAT,Brute Stomp,Brute Style", "PRETOTALAB:10", "PREVARGTEQ:PreStatScore_STR,23,PreStatScore_INT,13"]),
    (RuleSetId::Ha, 7, "Brute Stomp", &["PREABILITY:1,CATEGORY=FEAT,Brute Style", "PRETOTALAB:8", "PREVARGTEQ:PreStatScore_STR,19,PreStatScore_INT,13"]),
    (RuleSetId::Ha, 8, "Brute Style", &["PREABILITY:5,CATEGORY=FEAT,Combat Reflexes,Improved Overrun,Improved Trip,Improved Unarmed Strike,Vicious Stomp", "PRETOTALAB:6", "PREVARGTEQ:PreStatScore_STR,15,PreStatScore_INT,13"]),
    (RuleSetId::Ha, 9, "Bully Breed", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.Animal Companion,TYPE.Special Mount,TYPE.Mount", "PRESKILL:2,Handle Animal=4,Intimidate=4"]),
    (RuleSetId::Ha, 10, "Clarity of Pain", &["PREABILITY:2,CATEGORY=FEAT,Improved Iron Will,Iron Will", "PREVARGTEQ:PreStatScore_CON,13"]),
    (RuleSetId::Ha, 11, "Consume Essence", &["PREABILITY:1,CATEGORY=Special Ability,Swallow Whole", "PRETOTALAB:6", "PREALIGN:LE,NE,CE", "PRERACE:2,RACETYPE=Magical Beast,RACESUBTYPE=Outsider,RACESUBTYPE=Undead"]),
    (RuleSetId::Ha, 13, "Deadhand Initiate", &["PREABILITY:1,CATEGORY=FEAT,Deadhand Style", "PRESKILL:1,Knowledge (religion)=6", "PREVARGTEQ:PreStatScore_WIS,19"]),
    (RuleSetId::Ha, 14, "Deadhand Master", &["PREABILITY:1,CATEGORY=FEAT,Deadhand Initiate", "PRESKILL:1,Knowledge (religion)=14", "PREVARGTEQ:PreStatScore_WIS,23"]),
    (RuleSetId::Ha, 15, "Deadhand Style", &["PREABILITY:1,CATEGORY=FEAT,Improved Unarmed Strike", "PREABILITY:1,CATEGORY=Special Ability,TYPE.Ki Pool", "PREALIGN:LE,NE,CE,LN,TN,CN", "PRESKILL:1,Knowledge (religion)=4", "PREVARGTEQ:PreStatScore_WIS,15"]),
    (RuleSetId::Ha, 16, "Disconcerting Knowledge", &["PREMULT:1,[PREABILITY:1,CATEGORY=Special Ability,TYPE.Bardic Knowledge],[PREVARGTEQ:DomainKnowledgeLVL,1]", "PRESKILL:2,TYPE.Knowledge=3,TYPE.Knowledge=3"]),
    (RuleSetId::Ha, 17, "Disrupting Fist", &["PREABILITY:2,CATEGORY=FEAT,Channel Smite,Improved Unarmed Strike", "PRETOTALAB:9", "PRETEXT:Channel positive energy 4d6."]),
    (RuleSetId::Ha, 18, "Disruptive Spell-Like Ability", &["PRETEXT:Spell-like ability at caster level 4th or higher."]),
    (RuleSetId::Ha, 19, "Engulf Horror", &["PREABILITY:1,CATEGORY=FEAT,Engulf Revulsion", "PREABILITY:1,CATEGORY=Special Ability,Engulf,Smother"]),
    (RuleSetId::Ha, 20, "Engulf Revulsion", &["PREABILITY:1,CATEGORY=Special Ability,Engulf,Smother"]),
    (RuleSetId::Ha, 21, "Exorcising Mutilation", &["PREABILITY:1,CATEGORY=FEAT,Clarity of Pain", "PREVARGTEQ:PreStatScore_CON,15"]),
    (RuleSetId::Ha, 22, "Exsanguinate", &["PREABILITY:2,CATEGORY=Special Ability,TYPE.Grab,Blood Drain"]),
    (RuleSetId::Ha, 23, "Fear Eater", &["PREABILITY:1,CATEGORY=FEAT,Iron Will", "PREVARGTEQ:PreStatScore_CHA,13", "PRETEXT:Have no immunity to fear effects."]),
    (RuleSetId::Ha, 24, "Fearsome Spell-Like Ability", &["PRETEXT:Spell-like ability at caster level 6th or higher."]),
    (RuleSetId::Ha, 25, "Fleshwarper", &["PREALIGN:LE,NE,CE", "PRESKILL:2,Craft (alchemy)=5,Heal=5"]),
    (RuleSetId::Ha, 26, "Gruesome Shapechanger", &["PRERACE:1,RACESUBTYPE=Shapechanger"]),
    (RuleSetId::Ha, 27, "Horrific Gorging", &["PREABILITY:1,CATEGORY=Special Ability,Swallow Whole", "PREABILITY:1,CATEGORY=Internal,Bite", "PRESIZEGTEQ:L"]),
    (RuleSetId::Ha, 28, "Incorporeal Intuition", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRESPELLCAST:TYPE=Psychic]", "PREABILITY:1,CATEGORY=FEAT,Spirit Sense"]),
    (RuleSetId::Ha, 29, "Intensified Spell-Like Ability", &["PRETEXT:Spell-like ability at caster level 4th or higher."]),
    (RuleSetId::Ha, 30, "Kyton Cut", &["PREABILITY:1,CATEGORY=FEAT,Kyton Shield", "PREMULT:1,[PRECLASS:1,Monk=6],[PRETOTALAB:8]", "PREVARGTEQ:PreStatScore_WIS,17"]),
    (RuleSetId::Ha, 31, "Kyton Shield", &["PREABILITY:1,CATEGORY=FEAT,Kyton Style", "PRETOTALAB:5", "PREVARGTEQ:PreStatScore_WIS,15"]),
    (RuleSetId::Ha, 32, "Kyton Style", &["PREABILITY:1,CATEGORY=FEAT,Exotic Weapon Proficiency (Chain (Spiked))", "PREABILITY:1,CATEGORY=Special Ability,TYPE.Ki Pool", "PRESKILL:1,Knowledge (planes)=3", "PREVARGTEQ:PreStatScore_WIS,13"]),
    (RuleSetId::Ha, 33, "Latching Horror", &["PRETEXT:Attach universal monster ability."]),
    (RuleSetId::Ha, 34, "Lifeless Gaze", &["PREABILITY:1,CATEGORY=FEAT,Iron Will", "PRESKILL:1,Bluff=5"]),
    (RuleSetId::Ha, 35, "Lingering Spell-Like Ability", &["PRETEXT:Spell-like ability at caster level 4th or higher."]),
    (RuleSetId::Ha, 36, "Maddening Obliteration", &["PREABILITY:1,CATEGORY=FEAT,Maddening Strike", "PRESKILL:1,Knowledge (arcana)=10", "PREVARGTEQ:PreStatScore_WIS,19,PreStatScore_CHA,15"]),
    (RuleSetId::Ha, 37, "Maddening Strike", &["PREABILITY:1,CATEGORY=FEAT,Maddening Style", "PRESKILL:1,Knowledge (arcana)=8", "PREVARGTEQ:PreStatScore_WIS,17,PreStatScore_CHA,13"]),
    (RuleSetId::Ha, 38, "Maddening Style", &["PREABILITY:2,CATEGORY=FEAT,Improved Unarmed Strike,Stunning Fist", "PREABILITY:1,CATEGORY=Special Ability,TYPE.Ki Pool", "PREALIGN:LE,NE,CE,LN,TN,CN", "PRESKILL:1,Knowledge (arcana)=4", "PREVARGTEQ:PreStatScore_WIS,15,PreStatScore_CHA,11"]),
    (RuleSetId::Ha, 39, "Mutilating Ritualist", &["PRESKILL:3,Knowledge (arcana)=4,Knowledge (religion)=4,Spellcraft=4"]),
    (RuleSetId::Ha, 40, "Profane Studies", &["PRESKILL:1,Knowledge (planes)=4", "PREVARGTEQ:PreStatScore_INT,13", "PRETEXT:Ability to cast a summon monster spell."]),
    (RuleSetId::Ha, 41, "Purging Emesis", &["PREABILITY:1,CATEGORY=FEAT,Great Fortitude"]),
    (RuleSetId::Ha, 42, "Putrid Summons", &["PREABILITY:1,CATEGORY=FEAT,Spell Focus (conjuration)", "PRETEXT:Ability to cast summon monster or summon nature's ally."]),
    (RuleSetId::Ha, 43, "Reach Spell-Like Ability", &["PRETEXT:Spell-like ability at caster level 4th or higher."]),
    (RuleSetId::Ha, 44, "Sacrificial Adept", &["PRESPELLTYPE:1,Arcane=3,Divine=3,Psionic=3", "PREALIGN:LE,NE,CE", "PRESKILL:4,Knowledge (arcana)=4,Knowledge (planes)=4,Knowledge (religion)=4,Spellcraft=4"]),
    (RuleSetId::Ha, 45, "Sacrificial Ritualist", &["PREABILITY:1,CATEGORY=FEAT,Mutilating Ritualist"]),
    (RuleSetId::Ha, 46, "Scarring Spell-Like Ability", &["PRETEXT:Spell-like ability at caster level 4th or higher."]),
    (RuleSetId::Ha, 47, "Shatter Control", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.Channel Positive Energy", "PRETEXT:Channel positive energy 4d6."]),
    (RuleSetId::Ha, 48, "Sickening Spell-Like Ability", &["PRETEXT:Spell-like ability at caster level 6th or higher."]),
    (RuleSetId::Ha, 49, "Skin Suit", &["PREVARGTEQ:PreStatScore_INT,7", "PRETEXT:Undead creature that was originally humanoid."]),
    (RuleSetId::Ha, 50, "Spawnlink", &["PREVARGTEQ:PreStatScore_INT,13", "PRETEXT:Create spawn monster ability."]),
    (RuleSetId::Ha, 51, "Spirit Speaker", &["PREABILITY:1,CATEGORY=FEAT,Absorb Spirit", "PRESKILL:1,Diplomacy=5", "PREVARGTEQ:PreStatScore_CON,13,PreStatScore_CHA,13", "PRETEXT:Must have died at least once or been possessed by an undead creature."]),
    (RuleSetId::Ha, 52, "Stubborn Curse", &["PRETEXT:Ability to cast a spell or spell-like ability with the curse descriptor, or a special ability with a curse effect."]),
    (RuleSetId::Ha, 53, "Touch of Evil", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.Channel Negative Energy", "PREALIGN:LE,NE,CE", "PRETEXT:Channel negative energy 6d6"]),
    (RuleSetId::Ha, 54, "Traumatic Spell-Like Ability", &["PRETEXT:Spell-like ability at caster level 6th or higher."]),
    (RuleSetId::Ha, 55, "Unyielding Ferocity", &["PREABILITY:1,CATEGORY=Special Ability,Half-Orc ~ Orc Ferocity,Ferocity,Orc ~ Ferocity,Builder Racial Trait ~ Ferocity,Builder Racial Trait ~ Orc Ferocity", "PREVARGTEQ:PreStatScore_CON,19"]),
    (RuleSetId::Ha, 56, "Zealous Mind", &["PREABILITY:2,CATEGORY=FEAT,Iron Will,Unimpeachable Honor", "PREALIGN:LG,LN,LE"]),
    (RuleSetId::Ha, 57, "Enemy Cult", &["PRETEXT:You must have encountered a cult whose general alignment is opposite to yours on at least one axis or who threatened your beliefs or way of life, or you must have the Angelic Encounter, the False Witness, The Omen, or the Terrible Secret background (all of which are found in Ultimate Campaign)."]),
    (RuleSetId::Ha, 58, "Ghost Guide", &["PRETEXT:You have encountered a ghost or haunt, or have the Bones, the Died, the Raised Among the Dead, or The Dead One background (all of which are found in Ultimate Campaign)."]),
    (RuleSetId::Ha, 59, "Protector of the People", &["PRETEXT:Your community has come under persecution and requires considerable defense, or you have the Raiders, the Righting a Wrong, The War, or The Way Things Work background (all of which are found in Ultimate Campaign)."]),
    (RuleSetId::Ha, 60, "Twisted Love", &["PRETEXT:You resemble a lost loved one of an evil creature who would otherwise be a challenging foe. The likeness is close enough for you to be mistaken as the former loved one's reincarnation, or you might be that loved one reborn in a new life. Alternately, the creature might be a former lover who has become evil and wishes to resume the relationship. This unwanted relationship must be contrary to your alignment or long-term goals. Thematically appropriate backgrounds include Born out of Time, Current Lover, Reincarnated, The Lover, and Troubled First Love (all of which are found in Ultimate Campaign)."]),
    // inner_sea_races — 49 of 50 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Isr, 0, "Alien Mindpaths", &["PREFACT:1,TEMPLATES,IsAndroid=true,IsKasatha=true,IsLashunta=true,IsTriaxian=true", "PRETEXT:Android, kasatha, lashunta, or Triaxian."]),
    (RuleSetId::Isr, 1, "Ambush Squad", &["PREFACT:1,TEMPLATES,IsKobold=true", "PRETEXT:Base attack bonus +1, kobold.", "PRETOTALAB:1"]),
    (RuleSetId::Isr, 2, "Amplified Radiance", &["PREABILITY:1,CATEGORY=Special Ability,Aasimar ~ Spell-Like Ability", "PREFACT:1,TEMPLATES,IsAasimar=true", "PRETEXT:Aasimar, daylight racial spell-like ability."]),
    (RuleSetId::Isr, 3, "Ancestral Weapon Mastery", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.RacialWeaponFamiliarity", "PRETEXT:Base attack bonus +1, weapon familiarity racial trait.", "PRETOTALAB:1"]),
    (RuleSetId::Isr, 4, "Artillery Team", &["PREMULT:1,[PRESIZEEQ:S],[PRESIZEEQ:M]", "PRETEXT:Proficiency with light crossbow, heavy crossbow, or musket; size Small or Medium.", "PREWEAPONPROF:1,Crossbow (Light),Crossbow (Heavy),Musket"]),
    (RuleSetId::Isr, 5, "Barrage of Styles", &["PREFACT:1,TEMPLATES,IsHuman=true", "PRETEXT:Base attack bonus +1, human.", "PRETOTALAB:1"]),
    (RuleSetId::Isr, 6, "Blades Above and Below", &["PRETEXT:Base attack bonus +6.", "PRETOTALAB:6"]),
    (RuleSetId::Isr, 7, "Burn It Down!", &["PREFACT:1,TEMPLATES,IsGoblin=true", "PRETEXT:Base attack bonus +1, goblin.", "PRETOTALAB:1"]),
    (RuleSetId::Isr, 8, "Child of Two Fates", &["PREFACT:1,TEMPLATES,IsHalfElf=true", "PRESKILL:1,Knowledge (Local)=5", "PRETEXT:Knowledge (local) 5 ranks, half-elf."]),
    (RuleSetId::Isr, 10, "Concentrated Fire", &["PREABILITY:1,CATEGORY=Special Ability,Elf ~ Weapon Familiarity", "PREABILITY:1,CATEGORY=FEAT,Point-Blank Shot", "PREFACT:1,TEMPLATES,IsElf=true", "PRETEXT:Point-Blank Shot, elf, weapon familiarity racial trait."]),
    (RuleSetId::Isr, 11, "Cooperative Counterspelling", &["PRESKILL:1,Spellcraft=5", "PRETEXT:Spellcraft 5 ranks, racial spell-like ability replicating a spell of 1st level or higher."]),
    (RuleSetId::Isr, 12, "Coordinated Blast", &["PRESKILL:1,Spellcraft=5", "PRETEXT:Spellcraft 5 ranks, any racial spell-like ability."]),
    (RuleSetId::Isr, 13, "Crowd of Bullies", &["PREFACT:1,TEMPLATES,IsHalfOrc=true", "PRETEXT:Half-orc."]),
    (RuleSetId::Isr, 14, "Deadly Troupe", &["PREABILITY:[redacted PI]", "PRESKILL:1,Perform (Act)=3,Perform (Dance)=3", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isr, 15, "Death Roll", &["PREABILITY:1,CATEGORY=Internal,Bite", "PRERACE:1,RACESUBTYPE=Reptilian", "PRETEXT:Bite attack, reptilian subtype."]),
    (RuleSetId::Isr, 16, "Diplomatic Ruse", &["PREABILITY:1,CATEGORY=Background,Keleshite", "PRESKILL:1,Diplomacy=3", "PRETEXT:Diplomacy 3 ranks, human (Keleshite)."]),
    (RuleSetId::Isr, 17, "Echoes of the First World", &["PREFACT:1,TEMPLATES,IsGnome=true", "PRESKILL:1,Knowledge (Nature)=3", "PRETEXT:Knowledge (nature) 2 ranks, gnome subtype."]),
    (RuleSetId::Isr, 18, "Eclipse Strike", &["PREABILITY:1,CATEGORY=Special Ability,Tiefling ~ Spell-Like Ability", "PREFACT:1,TEMPLATES,IsTiefling=true", "PRETEXT:Tiefling, darkness racial spell-like ability."]),
    (RuleSetId::Isr, 19, "Elemental Strike", &["PREFACT:1,TEMPLATES,IsIfrit=true,IsOread=true,IsSylph=true,IsUndine=true", "PRETEXT:Ifrit, oread, sylph, or undine."]),
    (RuleSetId::Isr, 20, "Eternal Enmity", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.RacialHatred", "PRESKILL:1,TYPE.Knowledge=3", "PRETEXT:Knowledge 3 ranks (see special), hatred racial trait."]),
    (RuleSetId::Isr, 21, "Extraplanar Conjunction", &["PRERACE:1,RACETYPE=Outsider", "PRETEXT:Any racial spell-like ability, outsider."]),
    (RuleSetId::Isr, 22, "Eyes of the Twilight", &["PREABILITY:1,CATEGORY=FEAT,Sharp Senses", "PREABILITY:1,CATEGORY=Special Ability,TYPE.KeenSenses", "PREABILITY:1,CATEGORY=Special Ability,Low-Light Vision", "PRESKILL:1,Perception=7", "PRETEXT:Sharp Senses, Perception 7 ranks, keen senses racial trait, low-light vision."]),
    (RuleSetId::Isr, 23, "Ferocious Horde", &["PREABILITY:1,CATEGORY=Special Ability,Orc ~ Ferocity", "PREFACT:1,TEMPLATES,IsOrc=true", "PRETEXT:Orc, ferocity racial trait."]),
    (RuleSetId::Isr, 24, "Flow of Elements", &["PRECLASS:1,SPELLCASTER.Arcane=1,Divine=1,Psychic=1", "PREFACT:1,TEMPLATES,IsIfrit=true,IsOread=true,IsSylph=true,IsUndine=true", "PRETEXT:Ability to cast spells; ifrit, oread, sylph, or undine."]),
    (RuleSetId::Isr, 25, "Friendly Rivalry", &["PREABILITY:1,CATEGORY=Background,Taldan", "PRETEXT:Human (Taldan)."]),
    (RuleSetId::Isr, 26, "Giantslaying Team", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.RacialDefensiveTraining", "PREABILITY:2,CATEGORY=FEAT,Dodge,Mobility", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,13],[PREVARGTEQ:FeatDexRequirement,13]", "PRETEXT:Dex 13, Dodge, Mobility, base attack bonus +4, defensive training racial trait.", "PRETOTALAB:4"]),
    (RuleSetId::Isr, 27, "High Magic Focus", &["PREABILITY:[redacted PI]", "PREABILITY:1,Category=Feat,TYPE.Metamagic", "PRECLASS:1,SPELLCASTER.Arcane=2,Divine=2,Psychic=2", "PRESKILL:1,Spellcraft=7", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isr, 28, "Inspiring Talent", &["PREABILITY:1,CATEGORY=Special Ability,Half-Elf ~ Adaptability,Half-Elf ~ Ancestral Arms", "PREFACT:1,TEMPLATES,IsHalfElf=true", "PRETEXT:Half-elf, adaptability or ancestral arms racial trait."]),
    (RuleSetId::Isr, 29, "Juju Way", &["PREABILITY:[redacted PI]", "PRESKILL:1,Knowledge (Religion)=3", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isr, 30, "Kinslayer", &["PREALIGN:LE,NE,CE", "PRESKILL:1,TYPE.Knowledge=3", "PRETEXT:Knowledge 3 ranks (see special), evil alignment."]),
    (RuleSetId::Isr, 31, "Living Fortress", &["PREABILITY:1,CATEGORY=Special Ability,Dwarf ~ Hardy", "PREFACT:1,TEMPLATES,IsDwarf=true", "PRETEXT:Dwarf, hardy racial trait."]),
    (RuleSetId::Isr, 32, "Loyal to the Death", &["PREABILITY:1,CATEGORY=Background,Tian", "PRETEXT:Human (Tian)."]),
    (RuleSetId::Isr, 33, "Mirror Kin", &["PREABILITY:1,CATEGORY=Special Ability,Gnome ~ Gnome Magic", "PREFACT:1,TEMPLATES,IsGnome=true", "PRESKILL:1,Bluff=8", "PRETEXT:Bluff 8 ranks, gnome, gnome magic racial trait."]),
    (RuleSetId::Isr, 34, "One Mind", &["PREABILITY:1,CATEGORY=FEAT,Alertness", "PREABILITY:[redacted PI]", "PRESKILL:1,Sense Motive=3", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isr, 35, "Pack Intimidation", &["PREABILITY:1,CATEGORY=Special Ability,Half-Orc ~ Intimidating", "PREFACT:1,TEMPLATES,IsHalfOrc=true", "PRETEXT:Half-orc, intimidating racial trait."]),
    (RuleSetId::Isr, 36, "Pursuit of Glory", &["PREABILITY:1,CATEGORY=Background,Ulfen", "PRETEXT:Human (Ulfen)."]),
    (RuleSetId::Isr, 37, "Quah Bond", &["PREABILITY:1,CATEGORY=Background,Shoanti", "PREABILITY:1,CATEGORY=FEAT,Totem Spirit", "PRETEXT:Totem Spirit (ISWG p.289), human (Shoanti)."]),
    (RuleSetId::Isr, 38, "Relentless Cheer", &["PREABILITY:2,CATEGORY=Special Ability,Halfling ~ Fearless,Halfling ~ Halfling Luck", "PREFACT:1,TEMPLATES,IsHalfling=true", "PRETEXT:Halfling, fearless and halfling luck racial traits."]),
    (RuleSetId::Isr, 39, "Returning Throw", &["PREABILITY:1,CATEGORY=FEAT,Point-Blank Shot,Precise Shot", "PRERACE:1,RACESUBTYPE=Goblinoid", "PRESKILL:1,Slight of Hand=3", "PRETEXT:Point-Blank Shot, Precise Shot, Sleight of Hand 3 ranks, goblinoid subtype."]),
    (RuleSetId::Isr, 40, "Ruthless Opportunist", &["PREABILITY:1,CATEGORY=Background,Chelaxian", "PRETEXT:Human (Chelaxian)."]),
    (RuleSetId::Isr, 41, "Scion of the Lost Empire", &["PREABILITY:1,CATEGORY=Background,Chelaxian,Taldan", "PRETEXT:Human (Chelaxian or Taldan)."]),
    (RuleSetId::Isr, 42, "Seeping Darkness", &["PREABILITY:1,CATEGORY=Special Ability,Drow ~ Spell-Like Abilities", "PREFACT:1,TEMPLATES,IsDrow=true", "PRETEXT:Drow, darkness racial spell-like ability."]),
    (RuleSetId::Isr, 43, "Shared Ownership", &["PREABILITY:1,CATEGORY=FEAT,Well-Prepared", "PREFACT:1,TEMPLATES,IsHalfling=true", "PRESKILL:1,Slight of Hand=1", "PRETEXT:Well-Prepared, Sleight of Hand 1 rank, halfling."]),
    (RuleSetId::Isr, 44, "Shared Remembrance", &["PREFACT:1,TEMPLATES,IsElf=true", "PRESKILL:1,TYPE.Knowledge=1", "PRETEXT:Knowledge (any) 1 rank, elf."]),
    (RuleSetId::Isr, 45, "Shrouded in Mystery", &["PREFACT:1,TEMPLATES,IsKitsune=true,IsNagaji=true,IsSamsaran=true,IsTengu=true,IsWayang=true", "PRESKILL:2,Bluff=1,Disguise=1", "PRETEXT:Bluff 1 rank; Disguise 1 rank; kitsune, nagaji, samsaran, tengu, or wayang."]),
    (RuleSetId::Isr, 46, "Suppressive Fire", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.KeenSenses", "PREABILITY:3,CATEGORY=FEAT,Far Shot,Point-Blank Shot,Precise Shot", "PRETEXT:Far Shot, Point-Blank Shot, Precise Shot, keen senses racial trait."]),
    (RuleSetId::Isr, 47, "Triangulate", &["PREABILITY:3,CATEGORY=FEAT,Blind-Fight,Greater Blind-Fight,Improved Blind-Fight", "PREABILITY:1,CATEGORY=Background,Kellid", "PRESKILL:1,Perception=15", "PRETEXT:Blind-Fight, Greater Blind-Fight, Improved Blind-Fight, Perception 15 ranks, human (Kellid)."]),
    (RuleSetId::Isr, 48, "True Breed", &["PREFACT:1,TEMPLATES,IsHalfOrc=true,IsHalfElf=true", "PRETEXT:Two subtypes, elf blood or orc blood racial trait."]),
    (RuleSetId::Isr, 49, "Umbral Shift", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.RacialDarkness", "PRETEXT:Darkness racial spell-like ability."]),
    // occult_adventures — 60 of 68 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Oa, 0, "Alter Binary Mindscape", &["PRESPELL:1,Instigate Psychic Duel", "PRESTAT:1,INT=13"]),
    (RuleSetId::Oa, 1, "Bleeding Stare", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Painful Stare", "PRECLASS:1,Mesmerist=5"]),
    (RuleSetId::Oa, 2, "Chakra Adept", &["PREABILITY:1,CATEGORY=FEAT,Chakra Initiate", "PREPCLEVEL:MIN=8", "PRETEXT:Ability to awaken the heart chakra."]),
    (RuleSetId::Oa, 3, "Chakra Initiate", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.Ki Pool", "PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRECLASS:1,TYPE.Psychic=1]", "PREPCLEVEL:MIN=2", "PRETEXT:Ability to awaken the root chakra."]),
    (RuleSetId::Oa, 4, "Chakra Master", &["PREABILITY:2,CATEGORY=FEAT,Chakra Adept,Chakra Initiate", "PREPCLEVEL:MIN=14", "PRETEXT:Ability to awaken the crown chakra."]),
    (RuleSetId::Oa, 5, "Compounded Pain", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Painful Stare", "PRECLASS:1,Mesmerist=13"]),
    (RuleSetId::Oa, 6, "Delay Blast", &["PREABILITY:1,CATEGORY=Special Ability,Kineticist ~ Kinetic Blast", "PRETOTALAB:3"]),
    (RuleSetId::Oa, 7, "Demoralizing Stare", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Painful Stare", "PRECLASS:1,Mesmerist=9"]),
    (RuleSetId::Oa, 8, "Disciplinary Devotee", &["PREABILITY:1,CATEGORY=Special Ability,Psychic ~ Psychic Discipline"]),
    (RuleSetId::Oa, 9, "Distant Delivery", &["PREABILITY:1,CATEGORY=Special Ability,Spiritualist ~ Phantom", "PRETEXT:Phantom with the deliver touch spells ability.", "PREVARGTEQ:PhantomMasterLVL,3"]),
    (RuleSetId::Oa, 10, "Efficient Focus Shift", &["PRECLASS:1,Occultist=7"]),
    (RuleSetId::Oa, 12, "Emotional Conduit", &["PREABILITY:1,CATEGORY=Special Ability,Spiritualist ~ Shared Consciousness"]),
    (RuleSetId::Oa, 13, "Empath", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRESPELLCAST:TYPE=Psychic]", "PRESKILL:1,Perception=1,Sense Motive=1"]),
    (RuleSetId::Oa, 14, "Excoriating Stare", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Painful Stare", "PRECLASS:1,Mesmerist=11"]),
    (RuleSetId::Oa, 15, "Expanded Phrenic Pool", &["PREABILITY:1,CATEGORY=Special Ability,Psychic ~ Phrenic Pool"]),
    (RuleSetId::Oa, 16, "Extend Resonant Power", &["PREABILITY:1,CATEGORY=Special Ability,Occultist ~ Mental Focus", "PREMULT:1,[PRECLASS:1,SPELLCASTER=7],[PREVARGTEQ:CasterLevel_Highest,7]"]),
    (RuleSetId::Oa, 17, "Extended Stare", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Hypnotic Stare"]),
    (RuleSetId::Oa, 18, "Extra Amplification", &["PREABILITY:1,CATEGORY=Special Ability,Psychic ~ Phrenic Amplifications"]),
    (RuleSetId::Oa, 19, "Extra Focus Power", &["PREABILITY:1,CATEGORY=Special Ability,Occultist ~ Focus Powers"]),
    (RuleSetId::Oa, 20, "Extra Mental Focus", &["PREABILITY:1,CATEGORY=Special Ability,Occultist ~ Mental Focus"]),
    (RuleSetId::Oa, 21, "Extra Mesmerist Tricks", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Mesmerist Tricks"]),
    (RuleSetId::Oa, 22, "Extra Touch Treatment", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Touch Treatment"]),
    (RuleSetId::Oa, 23, "Extra Wild Talent", &["PRECLASS:1,Kineticist=6"]),
    (RuleSetId::Oa, 24, "Fatiguing Stare", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Painful Stare", "PRECLASS:1,Mesmerist=7"]),
    (RuleSetId::Oa, 26, "Focused Phantom", &["PREABILITY:1,CATEGORY=Special Ability,Spiritualist ~ Spiritual Interference"]),
    (RuleSetId::Oa, 28, "Greater Mesmerizing Feint", &["PREABILITY:1,CATEGORY=FEAT,Mesmerizing Feint", "PREABILITY:2,CATEGORY=Special Ability,Mesmerist ~ Hypnotic Stare,Bold Stare ~ Psychic Inception", "PRESKILL:1,Bluff=10"]),
    (RuleSetId::Oa, 29, "Hidden Presence", &["PRESPELL:1,Possession,Possession (Greater)", "PRESTAT:1,INT=17,CHA=17"]),
    (RuleSetId::Oa, 30, "Implement Focus", &["PRECLASS:1,Occultist=3"]),
    (RuleSetId::Oa, 31, "Intense Pain", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Painful Stare", "PRECLASS:1,Mesmerist=7"]),
    (RuleSetId::Oa, 32, "Interweave Composite Blast", &["PREABILITY:1,CATEGORY=Special Ability,Kineticist ~ Kinetic Blast"]),
    (RuleSetId::Oa, 33, "Intimidating Glance", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Hypnotic Stare"]),
    (RuleSetId::Oa, 34, "Intrusive Presence", &["PREABILITY:2,CATEGORY=FEAT,Hidden Presence,Manipulative Presence", "PRESPELL:1,Possession,Possession (Greater)", "PRESTAT:1,INT=21,CHA=21"]),
    (RuleSetId::Oa, 36, "Kinetic Counter", &["PREABILITY:1,CATEGORY=Special Ability,Kineticist ~ Kinetic Blast", "PREABILITY:1,CATEGORY=Special Ability,Wild Talent ~ Cold Blast,Wild Talent ~ Fire Blast,Wild Talent ~ Water Blast"]),
    (RuleSetId::Oa, 37, "Kinetic Leap", &["PREABILITY:1,CATEGORY=Special Ability,Kineticist ~ Kinetic Blast", "PRESKILL:1,Acrobatics=3"]),
    (RuleSetId::Oa, 39, "Lucid Dreamer", &["PRESKILL:1,Knowledge (Planes)=3", "PRESTAT:1,CHA=13"]),
    (RuleSetId::Oa, 40, "Manipulative Presence", &["PREABILITY:1,CATEGORY=FEAT,Hidden Presence", "PRESPELL:1,Possession,Possession (Greater)", "PRESTAT:1,INT=19,CHA=19"]),
    (RuleSetId::Oa, 41, "Mesmerizing Feint", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Hypnotic Stare"]),
    (RuleSetId::Oa, 42, "Parting Blast", &["PREABILITY:1,CATEGORY=Special Ability,Kineticist ~ Kinetic Blast"]),
    (RuleSetId::Oa, 43, "Phantom Fighter", &["PREABILITY:1,CATEGORY=Special Ability,Spiritualist ~ Phantom", "PRETEXT:Phantom with the magic attacks ability.", "PREVARGTEQ:PhantomMasterLVL,4"]),
    (RuleSetId::Oa, 44, "Phantom Fortification", &["PREABILITY:1,CATEGORY=Special Ability,Spiritualist ~ Phantom", "PRETEXT:Phantom with the incorporeal flight ability.", "PREVARGTEQ:PhantomMasterLVL,9"]),
    (RuleSetId::Oa, 45, "Psychic Adept", &["PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity", "PRESTAT:1,INT=11"]),
    (RuleSetId::Oa, 46, "Psychic Combatant", &["PREMULT:1,[PRESTAT:1,INT=13],[PREVARGTEQ:CombatFeatIntRequirement,13]", "PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRECLASS:1,TYPE.Psychic=1]", "PREPCLEVEL:MIN=3"]),
    (RuleSetId::Oa, 47, "Psychic Defender", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRECLASS:1,TYPE.Psychic=1]", "PREPCLEVEL:MIN=3", "PRESTAT:1,INT=13"]),
    (RuleSetId::Oa, 48, "Psychic Disciple", &["PREABILITY:2,CATEGORY=FEAT,Psychic Adept,Psychic Sensitivity", "PRESTAT:1,INT=13"]),
    (RuleSetId::Oa, 49, "Psychic Healing", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRESPELLCAST:TYPE=Psychic]", "PRESKILL:1,Heal=3", "PRESTAT:1,CHA=11"]),
    (RuleSetId::Oa, 50, "Psychic Maestro", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRESPELLCAST:TYPE=Psychic]"]),
    (RuleSetId::Oa, 52, "Psychic Virtuoso", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRESPELLCAST:TYPE=Psychic]"]),
    (RuleSetId::Oa, 53, "Rapid Focus Shift", &["PREABILITY:1,CATEGORY=Special Ability,Occultist ~ Mental Focus", "PREMULT:1,[PRECLASS:1,SPELLCASTER=5],[PREVARGTEQ:CasterLevel_Highest,5]"]),
    (RuleSetId::Oa, 54, "Ready for Battle", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Mesmerist Tricks"]),
    (RuleSetId::Oa, 55, "Ready for Pain", &["PREABILITY:1,CATEGORY=Special Ability,Mesmerist ~ Mesmerist Tricks"]),
    (RuleSetId::Oa, 57, "Shared Soul", &["PREABILITY:1,CATEGORY=Special Ability,Spiritualist ~ Shared Consciousness"]),
    (RuleSetId::Oa, 58, "Shatter Mental Mask", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRECLASS:1,TYPE.Psychic=1]", "PREPCLEVEL:MIN=2"]),
    (RuleSetId::Oa, 59, "Spirit Focus", &["PREABILITY:1,CATEGORY=Special Ability,Medium ~ Spirit"]),
    (RuleSetId::Oa, 60, "Spirit Sense", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRESPELLCAST:TYPE=Psychic]"]),
    (RuleSetId::Oa, 61, "Spiritual Balance", &["PREABILITY:2,CATEGORY=Special Ability,TYPE.Ki Pool,TYPE.Still Mind"]),
    (RuleSetId::Oa, 62, "Spiritualist's Call", &["PREABILITY:1,CATEGORY=Special Ability,Spiritualist ~ Phantom"]),
    (RuleSetId::Oa, 63, "Strong Implement Link", &["PREABILITY:1,CATEGORY=Special Ability,Occultist ~ Implements"]),
    (RuleSetId::Oa, 64, "Third Eye", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Psychic Sensitivity],[PRESPELLCAST:TYPE=Psychic]"]),
    (RuleSetId::Oa, 66, "Vigilant Phantom", &["PREABILITY:1,CATEGORY=Special Ability,Spiritualist ~ Phantom"]),
    (RuleSetId::Oa, 67, "Xenoglossy", &["PRESKILL:1,Linguistics=3", "PRESTAT:1,INT=13"]),
    // inner_sea_world_guide — 26 of 31 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Iswg, 0, "Altitude Affinity", &["PREABILITY:1,CATEGORY=FEAT,Endurance"]),
    (RuleSetId::Iswg, 1, "Arcane Vendetta", &["PRESKILL:1,Spellcraft=1"]),
    (RuleSetId::Iswg, 2, "Careful Speaker", &["PRESTAT:1,WIS=13"]),
    (RuleSetId::Iswg, 3, "Cypher Magic", &["PREABILITY:1,CATEGORY=FEAT,Scribe Scroll", "PRESTAT:1,INT=15"]),
    (RuleSetId::Iswg, 4, "Cypher Script", &["PRESKILL:3,Knowledge (Arcana)=1,Linguistics=1,Spellcraft=1"]),
    (RuleSetId::Iswg, 5, "Demon Hunter", &["PRESKILL:1,Knowledge (Planes)=6"]),
    (RuleSetId::Iswg, 6, "Dervish Dance", &["PREVAREQ:HasWeaponFinesseFeat,1", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,13],[PREVARGTEQ:FeatDexRequirement,13]", "PRESKILL:1,Perform (Dance)=2", "PREWEAPONPROF:1,Scimitar"]),
    (RuleSetId::Iswg, 7, "Desert Dweller", &["PRESKILL:1,Survival=1", "PRESTAT:1,CON=13"]),
    (RuleSetId::Iswg, 9, "Eye of the Arclord", &["PRESKILL:1,Knowledge (Arcana)=4", "PRESPELLCAST:TYPE=Arcane"]),
    (RuleSetId::Iswg, 10, "Fey Foundling", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Fey Foundling],[PRELEVELMAX:1]"]),
    (RuleSetId::Iswg, 11, "Flagbearer", &["PRESTAT:1,CHA=15"]),
    (RuleSetId::Iswg, 13, "Fortune Teller", &["PRESPELLSCHOOL:1,Divination=0"]),
    (RuleSetId::Iswg, 14, "Free Spirit", &["PREALIGN:CG,CN,CE", "PRESTAT:1,CHA=13"]),
    (RuleSetId::Iswg, 15, "Godless Healing", &["PREDEITY:1,N"]),
    (RuleSetId::Iswg, 16, "Green Faith Acolyte", &["PRETEXT:Follower of the Green Faith"]),
    (RuleSetId::Iswg, 17, "Hamatulatsu", &["PREABILITY:2,CATEGORY=FEAT,Improved Unarmed Strike,Weapon Focus (Unarmed Strike)"]),
    (RuleSetId::Iswg, 18, "Harmonic Spell", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.Bardic Performance"]),
    (RuleSetId::Iswg, 20, "Necromantic Affinity", &["PRESTAT:1,CON=15"]),
    (RuleSetId::Iswg, 21, "Noble Scion", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Noble Scion],[PRELEVELMAX:1]", "PRESTAT:1,CHA=13"]),
    (RuleSetId::Iswg, 22, "Rugged Northerner", &["PRESKILL:1,Survival=1", "PRESTAT:1,CON=13"]),
    (RuleSetId::Iswg, 24, "Secret Signs", &["PRESTAT:1,INT=13"]),
    (RuleSetId::Iswg, 25, "Shrewd Tactician", &["PREABILITY:2,CATEGORY=FEAT,Alertness,Combat Reflexes"]),
    (RuleSetId::Iswg, 26, "Stoic", &["PREABILITY:1,CATEGORY=FEAT,Iron Will"]),
    (RuleSetId::Iswg, 28, "Survivor", &["PREABILITY:2,CATEGORY=FEAT,Diehard,Endurance", "PRESTAT:1,CON=13"]),
    (RuleSetId::Iswg, 29, "Totem Spirit", &["PRETEXT:Member of a Shoanti tribe"]),
    (RuleSetId::Iswg, 30, "Wand Dancer", &["PREABILITY:2,CATEGORY=FEAT,Dodge,Mobility", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,13],[PREVARGTEQ:FeatDexRequirement,13]", "PRESKILL:1,Perform (Dance)=5"]),
    // monster_codex — 28 of 32 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::MonsterCodex, 0, "Angelbane Strike", &["PREABILITY:1,CATEGORY=FEAT,Channel Smite", "PREABILITY:1,CATEGORY=Special Ability,Channel Negative Energy", "PRECLASS:1,SPELLCASTER.Divine=5", "PRETEXT:Demon lord patron deity."]),
    (RuleSetId::MonsterCodex, 1, "Aquatic Adaption", &["PRETEXT:Hold Breath."]),
    (RuleSetId::MonsterCodex, 2, "Aquatic Advantage", &["PREABILITY:1,CATEGORY=FEAT,Combat Reflexes", "PREMOVE:1,Swim=1"]),
    (RuleSetId::MonsterCodex, 3, "Awesome Charge", &["PREABILITY:3,CATEGORY=FEAT,Awesome Blow,Improved Bull Rush,Power Attack", "PREVARGTEQ:PreStatScore_STR,25"]),
    (RuleSetId::MonsterCodex, 4, "Bushwhack", &["PREABILITY:2,CATEGORY=FEAT,Improved Grapple,Improved Unarmed Strike", "PREVARGTEQ:PreStatScore_DEX,13"]),
    (RuleSetId::MonsterCodex, 5, "Chain Challenge", &["PREABILITY:1,CATEGORY=Special Ability,Cavalier ~ Challenge,Samurai ~ Challenge", "PRELEVEL:MIN=7"]),
    (RuleSetId::MonsterCodex, 6, "Cleaving Sweep", &["PREABILITY:3,CATEGORY=FEAT,Cleave,Improved Trip,Weapon Focus (greataxe)", "PRETOTALAB:11", "PREVARGTEQ:PreStatScore_STR,15"]),
    (RuleSetId::MonsterCodex, 7, "Coordinated Reposition", &["PREABILITY:1,CATEGORY=FEAT,Step Up"]),
    (RuleSetId::MonsterCodex, 8, "Disarm Partner", &["PRETOTALAB:1"]),
    (RuleSetId::MonsterCodex, 9, "Draconic Magic", &["PREABILITY:1,CATEGORY=FEAT,Draconic Aspect", "PREFACT:1,TEMPLATES,IsKobold=true"]),
    (RuleSetId::MonsterCodex, 10, "Gnawer", &["PREABILITY:1,CATEGORY=FEAT,Sharptooth", "PREFACT:1,TEMPLATES,IsRatfolk=true"]),
    (RuleSetId::MonsterCodex, 11, "Horn Rider", &["PRETOTALAB:1"]),
    (RuleSetId::MonsterCodex, 12, "Horn Riders Charge", &["PREABILITY:1,CATEGORY=FEAT,Horn Rider", "PRETOTALAB:1"]),
    (RuleSetId::MonsterCodex, 13, "Hurtful", &["PREABILITY:1,CATEGORY=FEAT,Power Attack", "PREVARGTEQ:PreStatScore_STR,13"]),
    (RuleSetId::MonsterCodex, 14, "Improved Disarm Partner", &["PREABILITY:1,CATEGORY=FEAT,Disarm Partner", "PRETOTALAB:5"]),
    (RuleSetId::MonsterCodex, 17, "Pack Rat", &["PREFACT:1,TEMPLATES,IsRatfolk=true"]),
    (RuleSetId::MonsterCodex, 18, "Pile On", &["PREABILITY:2,CATEGORY=FEAT,Hurtful,Power Attack", "PREVARGTEQ:PreStatScore_STR,13"]),
    (RuleSetId::MonsterCodex, 20, "Shadow Shroud", &["PREABILITY:1,CATEGORY=FEAT,Combat Reflexes", "PREABILITY:1,CATEGORY=Spell-Like Ability,Racial SLA ~ Darkness"]),
    (RuleSetId::MonsterCodex, 21, "Shared Stash", &["PREABILITY:1,CATEGORY=FEAT,Quick Draw", "PREABILITY:1,CATEGORY=Special Ability,Ratfolk ~ Swarming,Builder Racial Trait ~ Swarming", "PRESKILL:1,Sleight of Hand=1", "PRETOTALAB:1"]),
    (RuleSetId::MonsterCodex, 22, "Sharptooth", &["PREFACT:1,TEMPLATES,IsRatfolk=true"]),
    (RuleSetId::MonsterCodex, 23, "Shocking Bellow", &["PREABILITY:1,CATEGORY=FEAT,Intimidating Prowess"]),
    (RuleSetId::MonsterCodex, 24, "Slurk Rider", &["PREFACT:1,TEMPLATES,IsKobold=true"]),
    (RuleSetId::MonsterCodex, 25, "Snapping Flank", &["PRETOTALAB:9", "PREWEAPONPROF:1,Bite"]),
    (RuleSetId::MonsterCodex, 26, "Snipers Lantern", &["PREABILITY:1,CATEGORY=FEAT,Point-Blank Shot", "PREABILITY:1,CATEGORY=Spell-Like Ability,Racial SLA ~ Dancing Lights"]),
    (RuleSetId::MonsterCodex, 28, "Staggering Blow", &["PREABILITY:2,CATEGORY=FEAT,Power Attack,Vital Strike", "PRETOTALAB:8", "PREVARGTEQ:PreStatScore_STR,13"]),
    (RuleSetId::MonsterCodex, 29, "Strangler", &["PREABILITY:2,CATEGORY=FEAT,Exotic Weapon Proficiency (lasso), Weapon Focus (lasso)"]),
    (RuleSetId::MonsterCodex, 30, "Vampiric Companion", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.Animal Companion,TYPE.Familiar", "PREALIGN:LN,TN,CN,LE,NE,CE", "PRECLASS:1,SPELLCASTER=10", "PREFACT:1,TEMPLATES,IsDhampir=true"]),
    (RuleSetId::MonsterCodex, 31, "Visceral Threat", &["PREABILITY:1,CATEGORY=FEAT,Intimidating Prowess"]),
    // mythic_adventures — 195 of 199 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Mythic, 1, "Marked for Glory", &["PREABILITY:1,CATEGORY=FEAT,Great Fortitude,Iron Will,Lightning Reflexes"]),
    (RuleSetId::Mythic, 2, "Mythic Companion", &["PREVARLTEQ:MythicTierLevel,0"]),
    (RuleSetId::Mythic, 4, "Drink Is Life", &["PRESTAT:1,CON=19", "PREVARGTEQ:MythicTierLevel,3"]),
    (RuleSetId::Mythic, 5, "Dual Path", &["PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 6, "Extra Mythic Power", &["PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 7, "Extra Path Ability", &["PREVARGTEQ:MythicTierLevel,3"]),
    (RuleSetId::Mythic, 8, "Fabulous Figments", &["PREABILITY:1,CATEGORY=FEAT,Spell Focus (Illusion)", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 9, "Legendary Teamwork", &["PREABILITY:2,CATEGORY=FEAT,TYPE=Teamwork", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 10, "Lucky Surge", &["PREABILITY:1,CATEGORY=Mythic Feat,Potent Surge", "PREVARGTEQ:MythicTierLevel,3"]),
    (RuleSetId::Mythic, 11, "Maximize Surge", &["PREVARGTEQ:MythicTierLevel,6"]),
    (RuleSetId::Mythic, 12, "Mythic Paragon", &["PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 13, "Mythic Spell Lore", &["PRESPELLCAST:TYPE=Arcane,TYPE=Divine", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 14, "Potent Surge", &["PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 15, "Titan Strike", &["PREABILITY:1,CATEGORY=Mythic Feat,Improved Unarmed Strike", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 16, "Two-Fisted Drinker", &["PREABILITY:1,CATEGORY=FEAT,Quick Draw", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 17, "Valiant Vault", &["PREABILITY:2,CATEGORY=FEAT,Mounted Combat,Ride-By Attack", "PRESKILL:1,Ride=5", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 18, "Accursed Hex", &["PREABILITY:1,CATEGORY=FEAT,Accursed Hex", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 19, "Acrobatic", &["PREABILITY:1,CATEGORY=FEAT,Acrobatic", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 20, "Alertness", &["PREABILITY:1,CATEGORY=FEAT,Alertness", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 21, "Alignment Channel", &["PREABILITY:1,CATEGORY=FEAT,Alignment Channel", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 22, "Animal Affinity", &["PREABILITY:1,CATEGORY=FEAT,Animal Affinity", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 23, "Arcane Armor Training", &["PREABILITY:1,CATEGORY=FEAT,Arcane Armor Training", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 24, "Arcane Blast", &["PREABILITY:1,CATEGORY=FEAT,Arcane Blast", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 25, "Arcane Shield", &["PREABILITY:1,CATEGORY=FEAT,Arcane Shield", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 26, "Arcane Strike", &["PREABILITY:1,CATEGORY=FEAT,Arcane Strike", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 27, "Aspect of the Beast", &["PREABILITY:1,CATEGORY=FEAT,Aspect of the Beast", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 28, "Athletic", &["PREABILITY:1,CATEGORY=FEAT,Athletic", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 29, "Augment Summoning", &["PREABILITY:1,CATEGORY=FEAT,Augment Summoning", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 30, "Bleeding Critical", &["PREABILITY:1,CATEGORY=FEAT,Bleeding Critical", "PREABILITY:1,CATEGORY=Mythic Feat,Critical Focus", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 31, "Blind Fight", &["PREABILITY:1,CATEGORY=FEAT,Blind Fight", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 32, "Catch Off-Guard", &["PREABILITY:1,CATEGORY=FEAT,Catch Off-Guard", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 33, "Channel Smite", &["PREABILITY:1,CATEGORY=FEAT,Channel Smite", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 34, "Charge Through", &["PREABILITY:1,CATEGORY=FEAT,Charge Through", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 35, "Cleave", &["PREABILITY:1,CATEGORY=FEAT,Cleave", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 36, "Combat Expertise", &["PREABILITY:1,CATEGORY=FEAT,Combat Expertise", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 37, "Combat Reflexes", &["PREABILITY:1,CATEGORY=FEAT,Combat Reflexes", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 38, "Command Undead", &["PREABILITY:1,CATEGORY=FEAT,Command Undead", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 39, "Critical Focus", &["PREABILITY:1,CATEGORY=FEAT,Critical Focus", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 40, "Critical Mastery", &["PREABILITY:1,CATEGORY=FEAT,Critical Mastery", "PREABILITY:1,CATEGORY=Mythic Feat,Critical Focus", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 41, "Dastardly Finish", &["PREABILITY:1,CATEGORY=FEAT,Dastardly Finish", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 42, "Dazzling Display", &["PREABILITY:1,CATEGORY=FEAT,Dazzling Display", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 43, "Deadly Aim", &["PREABILITY:1,CATEGORY=FEAT,Deadly Aim", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 44, "Deadly Stroke", &["PREABILITY:1,CATEGORY=FEAT,Deadly Stroke", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 45, "Death from Above", &["PREABILITY:1,CATEGORY=FEAT,Death from Above", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 46, "Deceitful", &["PREABILITY:1,CATEGORY=FEAT,Deceitful", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 47, "Deepsight", &["PREABILITY:1,CATEGORY=FEAT,Deepsight", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 48, "Defensive Combat Training", &["PREABILITY:1,CATEGORY=FEAT,Defensive Combat Training", "PREVARGTEQ:MythicTierLevel,4"]),
    (RuleSetId::Mythic, 49, "Deflect Arrows", &["PREABILITY:1,CATEGORY=FEAT,Deflect Arrows", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 50, "Deft Hand", &["PREABILITY:1,CATEGORY=FEAT,Deft Hand", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 51, "Detect Expertise", &["PREABILITY:1,CATEGORY=FEAT,Detect Expertise", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 52, "Disruptive", &["PREABILITY:1,CATEGORY=FEAT,Disruptive", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 53, "Distance Thrower", &["PREABILITY:1,CATEGORY=FEAT,Distance Thrower", "PRESTAT:1,STR=17", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 54, "Divine Interference", &["PREABILITY:1,CATEGORY=FEAT,Divine Interference", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 55, "Dodge", &["PREABILITY:1,CATEGORY=FEAT,Dodge", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 56, "Dreadful Carnage", &["PREABILITY:1,CATEGORY=FEAT,Dreadful Carnage", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 57, "Eagle Eyes", &["PREABILITY:1,CATEGORY=FEAT,Eagle Eyes", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 58, "Eldritch Heritage", &["PREABILITY:1,CATEGORY=FEAT,Eldritch Heritage", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 59, "Elemental Channel", &["PREABILITY:1,CATEGORY=FEAT,Elemental Channel", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 60, "Elemental Fist", &["PREABILITY:1,CATEGORY=FEAT,Elemental Fist", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 61, "Elemental Focus", &["PREABILITY:1,CATEGORY=FEAT,Elemental Focus", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 62, "Elven Accuracy", &["PREABILITY:1,CATEGORY=FEAT,Elven Accuracy", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 63, "Endurance", &["PREABILITY:1,CATEGORY=FEAT,Endurance", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 64, "Eschew Materials", &["PREABILITY:1,CATEGORY=FEAT,Eschew Materials", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 65, "Far Shot", &["PREABILITY:1,CATEGORY=FEAT,Far Shot", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 66, "Fast Empathy", &["PREABILITY:1,CATEGORY=FEAT,Fast Empathy", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 67, "Fire Music", &["PREABILITY:1,CATEGORY=FEAT,Fire Music", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 68, "Fleet", &["PREABILITY:1,CATEGORY=FEAT,Fleet", "PREVARGTEQ:MythicTierLevel,1", "PREVARLT:count(\"ABILITIES\",\"CATEGORY=Mythic Feat\",\"KEY=Fleet\"),count(\"ABILITIES\",\"CATEGORY=FEAT\",\"KEY=Fleet\")"]),
    (RuleSetId::Mythic, 69, "Furious Focus", &["PREABILITY:1,CATEGORY=FEAT,Furious Focus", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 70, "Gnome Trickster", &["PREABILITY:1,CATEGORY=FEAT,Gnome Trickster", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 71, "Gorgon's Fist", &["PREABILITY:1,CATEGORY=FEAT,Gorgon's Fist", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 72, "Great Fortitude", &["PREABILITY:1,CATEGORY=FEAT,Great Fortitude", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 73, "Guided Hand", &["PREABILITY:1,CATEGORY=FEAT,Guided Hand", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 74, "Heroic Defiance", &["PREABILITY:1,CATEGORY=FEAT,Heroic Defiance", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 75, "Heroic Recovery", &["PREABILITY:1,CATEGORY=FEAT,Heroic Recovery", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 76, "Improved Bull Rush", &["PREABILITY:1,CATEGORY=FEAT,Improved Bull Rush", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 77, "Improved Channel", &["PREABILITY:1,CATEGORY=FEAT,Improved Channel", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 78, "Improved Counterspell", &["PREABILITY:1,CATEGORY=FEAT,Improved Counterspell", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 79, "Improved Critical", &["PREABILITY:1,CATEGORY=FEAT,Improved Critical", "PRETOTALAB:8", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 80, "Improved Dirty Trick", &["PREABILITY:1,CATEGORY=FEAT,Improved Dirty Trick", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 81, "Improved Disarm", &["PREABILITY:1,CATEGORY=FEAT,Improved Disarm", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 82, "Improved Drag", &["PREABILITY:1,CATEGORY=FEAT,Improved Drag", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 83, "Improved Familiar", &["PREABILITY:1,CATEGORY=FEAT,Improved Familiar", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 84, "Improved Grapple", &["PREABILITY:1,CATEGORY=FEAT,Improved Grapple", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 85, "Improved Initiative", &["PREABILITY:1,CATEGORY=FEAT,Improved Initiative", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 86, "Improved Overrun", &["PREABILITY:1,CATEGORY=FEAT,Improved Overrun", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 87, "Improved Reposition", &["PREABILITY:1,CATEGORY=FEAT,Improved Reposition", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 88, "Improved Steal", &["PREABILITY:1,CATEGORY=FEAT,Improved Steal", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 89, "Improved Stonecunning", &["PREABILITY:1,CATEGORY=FEAT,Improved Stonecunning", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 90, "Improved Sunder", &["PREABILITY:1,CATEGORY=FEAT,Improved Sunder", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 91, "Improved Trip", &["PREABILITY:1,CATEGORY=FEAT,Improved Trip", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 92, "Improved Unarmed Strike", &["PREABILITY:1,CATEGORY=FEAT,Improved Unarmed Strike", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 93, "Intimidating Prowess", &["PREABILITY:1,CATEGORY=FEAT,Intimidating Prowess", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 94, "Iron Will", &["PREABILITY:1,CATEGORY=FEAT,Iron Will", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 95, "Knockout Artist", &["PREABILITY:1,CATEGORY=FEAT,Knockout Artist", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 96, "Lightning Reflexes", &["PREABILITY:1,CATEGORY=FEAT,Lightning Reflexes", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 97, "Lucky Halfling", &["PREABILITY:1,CATEGORY=FEAT,Lucky Halfling", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 98, "Lunge", &["PREABILITY:1,CATEGORY=FEAT,Lunge", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 99, "Magical Aptitude", &["PREABILITY:1,CATEGORY=FEAT,Magical Aptitude", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 100, "Manyshot", &["PREABILITY:1,CATEGORY=FEAT,Manyshot", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 101, "Medusa's Wrath", &["PREABILITY:1,CATEGORY=FEAT,Medusa's Wrath", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 102, "Missile Shield", &["PREABILITY:1,CATEGORY=FEAT,Missile Shield", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 103, "Mobility", &["PREABILITY:1,CATEGORY=FEAT,Mobility", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 104, "Monastic Legacy", &["PREABILITY:1,CATEGORY=FEAT,Monastic Legacy", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 105, "Mounted Archery", &["PREABILITY:1,CATEGORY=FEAT,Mounted Archery", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 106, "Mounted Combat", &["PREABILITY:1,CATEGORY=FEAT,Mounted Combat", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 107, "Mythic Crafter", &["PREABILITY:1,CATEGORY=FEAT,TYPE=ItemCreation", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 108, "Natural Spell", &["PREABILITY:1,CATEGORY=FEAT,Natural Spell", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 109, "Nimble Moves", &["PREABILITY:1,CATEGORY=FEAT,Nimble Moves", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 110, "Penetrating Strike", &["PREABILITY:1,CATEGORY=FEAT,Penetrating Strike", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 111, "Persuasive", &["PREABILITY:1,CATEGORY=FEAT,Persuasive", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 112, "Pinpoint Targeting", &["PREABILITY:1,CATEGORY=FEAT,Pinpoint Targeting", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 113, "Point-Blank Shot", &["PREABILITY:1,CATEGORY=FEAT,Point-Blank Shot", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 114, "Power Attack", &["PREABILITY:1,CATEGORY=FEAT,Power Attack", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 115, "Powerful Shape", &["PREABILITY:1,CATEGORY=FEAT,Powerful Shape", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 116, "Prophetic Visionary", &["PREABILITY:1,CATEGORY=FEAT,Prophetic Visionary", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 117, "Quick Draw", &["PREABILITY:1,CATEGORY=FEAT,Quick Draw", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 118, "Racial Heritage", &["PREABILITY:1,CATEGORY=FEAT,Racial Heritage", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 119, "Rapid Reload", &["PREABILITY:1,CATEGORY=FEAT,Rapid Reload", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 120, "Rapid Shot", &["PREABILITY:1,CATEGORY=FEAT,Rapid Shot", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 121, "Rhetorical Flourish", &["PREABILITY:1,CATEGORY=FEAT,Rhetorical Flourish", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 122, "Ride-By Attack", &["PREABILITY:1,CATEGORY=FEAT,Ride-By Attack", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 123, "Run", &["PREABILITY:1,CATEGORY=FEAT,Run", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 124, "Saving Shield", &["PREABILITY:1,CATEGORY=FEAT,Saving Shield", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 125, "Scorpion Style", &["PREABILITY:1,CATEGORY=FEAT,Scorpion Style", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 126, "Selective Channeling", &["PREABILITY:1,CATEGORY=FEAT,Selective Channeling", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 127, "Self-Sufficient", &["PREABILITY:1,CATEGORY=FEAT,Self-Sufficient", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 128, "Shatter Defenses", &["PREABILITY:1,CATEGORY=FEAT,Shatter Defenses", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 129, "Shield Focus", &["PREABILITY:1,CATEGORY=FEAT,Shield Focus", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 130, "Shield Slam", &["PREABILITY:1,CATEGORY=FEAT,Shield Slam", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 131, "Shot on the Run", &["PREABILITY:1,CATEGORY=FEAT,Shot on the Run", "PRETOTALAB:6", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 132, "Skill Focus", &["PREABILITY:1,CATEGORY=FEAT,Skill Focus", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 133, "Snatch Arrows", &["PREABILITY:1,CATEGORY=FEAT,Snatch Arrows", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 134, "Sociable", &["PREABILITY:1,CATEGORY=FEAT,Sociable", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 135, "Spell Focus", &["PREABILITY:1,CATEGORY=FEAT,Spell Focus", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 136, "Spell Mastery", &["PREABILITY:1,CATEGORY=FEAT,Spell Mastery", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 137, "Spell Penetration", &["PREABILITY:1,CATEGORY=FEAT,Spell Penetration", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 138, "Spellbreaker", &["PREABILITY:1,CATEGORY=FEAT,Spellbreaker", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 139, "Spirited Charge", &["PREABILITY:1,CATEGORY=FEAT,Spirited Charge", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 140, "Spontaneous Metafocus", &["PREABILITY:1,CATEGORY=FEAT,Spontaneous Metafocus", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 141, "Spring Attack", &["PREABILITY:1,CATEGORY=FEAT,Spring Attack", "PRETOTALAB:6", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 142, "Stealthy", &["PREABILITY:1,CATEGORY=FEAT,Stealthy", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 143, "Strike Back", &["PREABILITY:1,CATEGORY=FEAT,Strike Back", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 144, "Strong Comeback", &["PREABILITY:1,CATEGORY=FEAT,Strong Comeback", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 145, "Stunning Fist", &["PREABILITY:1,CATEGORY=FEAT,Stunning Fist", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 146, "Throw Anything", &["PREABILITY:1,CATEGORY=FEAT,Throw Anything", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 147, "Toughness", &["PREABILITY:1,CATEGORY=FEAT,Toughness", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 148, "Trample", &["PREABILITY:1,CATEGORY=FEAT,Trample", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 149, "Tripping Staff", &["PREABILITY:1,CATEGORY=FEAT,Tripping Staff", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 150, "Turn Undead", &["PREABILITY:1,CATEGORY=FEAT,Turn Undead", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 151, "Two-Weapon Defense", &["PREABILITY:1,CATEGORY=FEAT,Two-Weapon Defense", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 152, "Two-Weapon Fighting", &["PREABILITY:1,CATEGORY=FEAT,Two-Weapon Fighting", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 153, "Two-Weapon Rend", &["PREABILITY:1,CATEGORY=FEAT,Two-Weapon Rend", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 154, "Undead Master", &["PREABILITY:1,CATEGORY=FEAT,Undead Master", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 155, "Unseat", &["PREABILITY:1,CATEGORY=FEAT,Unseat", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 156, "Vital Strike", &["PREABILITY:1,CATEGORY=FEAT,Vital Strike", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 157, "Voice of the Sibyl", &["PREABILITY:1,CATEGORY=FEAT,Voice of the Sibyl", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 158, "Warrior Priest", &["PREABILITY:1,CATEGORY=FEAT,Warrior Priest", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 159, "Weapon Finesse", &["PREABILITY:1,CATEGORY=FEAT,Weapon Finesse", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 160, "Weapon Focus", &["PREABILITY:1,CATEGORY=FEAT,Weapon Focus", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 161, "Weapon Specialization", &["PREABILITY:1,CATEGORY=FEAT,Weapon Specialization", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 162, "Witch Knife", &["PREABILITY:1,CATEGORY=FEAT,Witch Knife", "PREVARGTEQ:MythicTierLevel,1"]),
    (RuleSetId::Mythic, 165, "Android", &["PRETEMPLATE:1,Racial Heritage ~ Android"]),
    (RuleSetId::Mythic, 166, "Aquatic Elf", &["PRETEMPLATE:1,Racial Heritage ~ Aquatic Elf"]),
    (RuleSetId::Mythic, 167, "Catfolk", &["PRETEMPLATE:1,Racial Heritage ~ Catfolk"]),
    (RuleSetId::Mythic, 168, "Changeling", &["PRETEMPLATE:1,Racial Heritage ~ Changeling"]),
    (RuleSetId::Mythic, 169, "Dhampir", &["PRETEMPLATE:1,Racial Heritage ~ Dhampir"]),
    (RuleSetId::Mythic, 170, "Drow", &["PRETEMPLATE:1,Racial Heritage ~ Drow"]),
    (RuleSetId::Mythic, 171, "Duergar", &["PRETEMPLATE:1,Racial Heritage ~ Duergar"]),
    (RuleSetId::Mythic, 172, "Dwarf", &["PRETEMPLATE:1,Racial Heritage ~ Dwarf"]),
    (RuleSetId::Mythic, 173, "Elf", &["PRETEMPLATE:1,Racial Heritage ~ Elf"]),
    (RuleSetId::Mythic, 174, "Gillman", &["PRETEMPLATE:1,Racial Heritage ~ Gillman"]),
    (RuleSetId::Mythic, 175, "Gnome", &["PRETEMPLATE:1,Racial Heritage ~ Gnome"]),
    (RuleSetId::Mythic, 176, "Goblin", &["PRETEMPLATE:1,Racial Heritage ~ Goblin"]),
    (RuleSetId::Mythic, 177, "Grippli", &["PRETEMPLATE:1,Racial Heritage ~ Grippli"]),
    (RuleSetId::Mythic, 178, "Halfling", &["PRETEMPLATE:1,Racial Heritage ~ Halfling"]),
    (RuleSetId::Mythic, 179, "Hobgoblin", &["PRETEMPLATE:1,Racial Heritage ~ Hobgoblin"]),
    (RuleSetId::Mythic, 180, "Kasatha", &["PRETEMPLATE:1,Racial Heritage ~ Kasatha"]),
    (RuleSetId::Mythic, 181, "Kitsune", &["PRETEMPLATE:1,Racial Heritage ~ Kitsune"]),
    (RuleSetId::Mythic, 182, "Kobold", &["PRETEMPLATE:1,Racial Heritage ~ Kobold"]),
    (RuleSetId::Mythic, 183, "Lashunta", &["PRETEMPLATE:1,Racial Heritage ~ Lashunta"]),
    (RuleSetId::Mythic, 184, "Merfolk", &["PRETEMPLATE:1,Racial Heritage ~ Merfolk"]),
    (RuleSetId::Mythic, 185, "Monkey Goblin", &["PRETEMPLATE:1,Racial Heritage ~ Monkey Goblin"]),
    (RuleSetId::Mythic, 186, "Nagaji", &["PRETEMPLATE:1,Racial Heritage ~ Nagaji"]),
    (RuleSetId::Mythic, 187, "Orc", &["PRETEMPLATE:1,Racial Heritage ~ Orc"]),
    (RuleSetId::Mythic, 188, "Ratfolk", &["PRETEMPLATE:1,Racial Heritage ~ Ratfolk"]),
    (RuleSetId::Mythic, 189, "Rougarou", &["PRETEMPLATE:1,Racial Heritage ~ Rougarou"]),
    (RuleSetId::Mythic, 190, "Samsaran", &["PRETEMPLATE:1,Racial Heritage ~ Samsaran"]),
    (RuleSetId::Mythic, 191, "Skinwalker", &["PRETEMPLATE:1,Racial Heritage ~ Skinwalker"]),
    (RuleSetId::Mythic, 192, "Strix", &["PRETEMPLATE:1,Racial Heritage ~ Strix"]),
    (RuleSetId::Mythic, 193, "Svirfneblin", &["PRETEMPLATE:1,Racial Heritage ~ Svirfneblin"]),
    (RuleSetId::Mythic, 194, "Syrinx", &["PRETEMPLATE:1,Racial Heritage ~ Syrinx"]),
    (RuleSetId::Mythic, 195, "Tengu", &["PRETEMPLATE:1,Racial Heritage ~ Tengu"]),
    (RuleSetId::Mythic, 196, "Triaxian", &["PRETEMPLATE:1,Racial Heritage ~ Triaxian"]),
    (RuleSetId::Mythic, 197, "Vanara", &["PRETEMPLATE:1,Racial Heritage ~ Vanara"]),
    (RuleSetId::Mythic, 198, "Wayang", &["PRETEMPLATE:1,Racial Heritage ~ Wayang"]),
    // inner_sea_intrigue — 6 of 6 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Isi, 0, "Convincing Persona", &["PREMULT:1,[PRESKILL:2,Bluff=5,Perform (act)=5],[PREABILITY:1,CATEGORY=Special Ability,Vigilante ~ Dual Identity]", "PRETEXT:Bluff 5 ranks, Perform (act) 5 ranks, or dual identity class feature."]),
    (RuleSetId::Isi, 1, "Greater Stylized Spell", &["PREABILITY:1,CATEGORY=FEAT,Stylized Spell", "PRESKILL:2,Bluff=10,Spellcraft=10", "PRETEXT:Stylized Spell, Bluff 10 ranks, Spellcraft 10 ranks."]),
    (RuleSetId::Isi, 2, "Masked Renown", &["PRESKILL:1,Disguise=2", "PRETEXT:Cha 13, Disguise 2 ranks.", "PREVARGTEQ:PreStatScore_CHA,13"]),
    (RuleSetId::Isi, 3, "Masked Symbol", &["PREMULT:1,[PRESKILL:1,Disguise=1],[PREABILITY:1,CATEGORY=Special Ability,Vigilante ~ Dual Identity]", "PRETEXT:Disguise 1 rank or dual identity class feature."]),
    (RuleSetId::Isi, 4, "Stylized Spell Mastery", &["PREABILITY:2,CATEGORY=FEAT,Spell Mastery,Stylized Spell", "PRESKILL:2,Bluff=5,Spellcraft=5", "PRETEXT:Spell Mastery, Stylized Spell, Bluff 5 ranks, Spellcraft 5 ranks."]),
    (RuleSetId::Isi, 5, "Stylized Spontaneity", &["PRESKILL:2,Bluff=5,Spellcraft=5", "PRETEXT:Bluff 5 ranks, Spellcraft 5 ranks."]),
    // book_of_the_damned_volume_2 — 1 of 1 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Botd2, 0, "Demonic Obedience", &["PREDEITY:1,PANTHEON.Demon Lords", "PRESKILL:1,Knowledge (Planes)=3"]),
    // inner_sea_taverns — 5 of 9 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::InnerSeaTaverns, 1, "Drunken God's Blessings", &["PREDEITY:[redacted PI]"]),
    (RuleSetId::InnerSeaTaverns, 2, "Drunken Sing-Along", &["PRESKILL:2,Diplomacy=1,Perform (Sing)=1"]),
    (RuleSetId::InnerSeaTaverns, 4, "Hardy Liver", &["PREABILITY:1,CATEGORY=FEAT,Great Fortitude"]),
    (RuleSetId::InnerSeaTaverns, 7, "Read the Room", &["PREABILITY:1,CATEGORY=FEAT,Drunken Sing-Along", "PRESKILL:3,Diplomacy=1,Perform (Sing)=1,Sense Motive=1"]),
    (RuleSetId::InnerSeaTaverns, 8, "Tavern Regular", &["PREVARGTEQ:PreStatScore_CHA,14"]),
    // inner_sea_combat — 23 of 23 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Isc, 0, "Duelist of the Roaring Falls", &["PREABILITY:[redacted PI]", "PRETEXT:[redacted PI]", "PRETOTALAB:5"]),
    (RuleSetId::Isc, 1, "Duelist of the Shrouded Lake", &["PREABILITY:[redacted PI]", "PRETEXT:[redacted PI]", "PRETOTALAB:5"]),
    (RuleSetId::Isc, 2, "Falling Water Gambit", &["PREABILITY:[redacted PI]", "PRETEXT:[redacted PI]", "PRETOTALAB:8"]),
    (RuleSetId::Isc, 3, "Awe-Inspiring Smash", &["PREABILITY:1,CATEGORY=FEAT,Power Attack", "PRESTAT:1,STR=15", "PRETEXT:Prerequisites: Str 15, Power Attack, base attack bonus +3.", "PRETOTALAB:3"]),
    (RuleSetId::Isc, 4, "Black Powder Spectacle", &["PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Amateur Gunslinger],[PREABILITY:1,CATEGORY=Special Ability,TYPE.Grit,Gunslinger ~ Grit]", "PRETEXT:Prerequisites: Amateur Gunslinger or the grit class feature, base attack bonus +4.", "PRETOTALAB:5"]),
    (RuleSetId::Isc, 5, "Masterful Flourish", &["PREABILITY:1,CATEGORY=Special Ability,Fighter ~ Weapon Training,TYPE.Weapon Training", "PRETEXT:Prerequisite: Weapon training class feature."]),
    (RuleSetId::Isc, 6, "Ostentatious Weakness", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.Favored Enemy", "PRETEXT:Prerequisites: Base attack bonus +5, favored enemy class feature.", "PRETOTALAB:5"]),
    (RuleSetId::Isc, 7, "Savage Surge", &["PREABILITY:1,CATEGORY=FEAT,Intimidating Prowess", "PREABILITY:1,CATEGORY=Special Ability,TYPE.Rage", "PRETEXT:Prerequisites: Intimidating Prowess, rage class feature."]),
    (RuleSetId::Isc, 8, "Spectacular Exit", &["PREABILITY:1,CATEGORY=FEAT,Dodge", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,15],[PREVARGTEQ:FeatDexRequirement,15]", "PRESKILL:1,Acrobatics=7", "PRETEXT:Prerequisites: Dex 15, Dodge, Acrobatics 7 ranks."]),
    (RuleSetId::Isc, 9, "Thrilling Vengeance", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.Rage", "PRETEXT:Prerequisites: Base attack bonus +3, rage class feature.", "PRETOTALAB:3"]),
    (RuleSetId::Isc, 10, "Perfect Style", &["PREMULT:1,[PRETOTALAB:5],[PREVARGTEQ:MonkLVL,5]", "PRESTAT:1,WIS=13", "PRETEXT:Prerequisites: Wis 13, base attack bonus +5 or monk level 5th."]),
    (RuleSetId::Isc, 11, "Unblinking Flame Feint", &["PREABILITY:2,CATEGORY=FEAT,Perfect Style,Combat Expertise", "PREMULT:1,[PRETOTALAB:9],[PREVARGTEQ:MonkLVL,9]", "PREMULT:1,[PRESTAT:1,INT=13],[PREVARGTEQ:CombatFeatIntRequirement,13]", "PRESTAT:1,WIS=13", "PRETEXT:Prerequisites: Int 13, Wis 13, Combat Expertise, Perfect Style, base attack bonus +9 or monk level 9th."]),
    (RuleSetId::Isc, 12, "Unblinking Flame Fist", &["PREABILITY:4,CATEGORY=FEAT,Perfect Style,Combat Expertise,Stunning Fist,Unblinking Flame Feint", "PREMULT:1,[PRETOTALAB:13],[PREVARGTEQ:MonkLVL,13]", "PREMULT:1,[PRESTAT:1,INT=13],[PREVARGTEQ:CombatFeatIntRequirement,13]", "PRESTAT:1,WIS=13", "PRETEXT:Prerequisites: Int 13, Wis 13, Combat Expertise, Perfect Style, Stunning Fist, Unblinking Flame Feint, base attack bonus +13 or monk level 13th."]),
    (RuleSetId::Isc, 13, "Unfolding Wind Rush", &["PREABILITY:4,CATEGORY=FEAT,Perfect Style,Quick Draw,Unfolding Wind Strike,Mobility", "PREMULT:1,[PRETOTALAB:13],[PREVARGTEQ:MonkLVL,13]", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,13],[PREVARGTEQ:FeatDexRequirement,13]", "PRESTAT:1,WIS=13", "PRETEXT:Prerequisites: Dex 13, Wis 13, Mobility, Perfect Style, Quick Draw, Unfolding Wind Strike, base attack bonus + 13 or monk level 13th."]),
    (RuleSetId::Isc, 14, "Unfolding Wind Strike", &["PREABILITY:1,CATEGORY=FEAT,Perfect Style,Quick Draw", "PREMULT:1,[PRETOTALAB:9],[PREVARGTEQ:MonkLVL,9]", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,13],[PREVARGTEQ:FeatDexRequirement,13]", "PRESTAT:1,WIS=13", "PRETEXT:Prerequisites: Dex 13, Wis 13, Perfect Style, Quick Draw, base attack bonus +9 or monk level 9th."]),
    (RuleSetId::Isc, 15, "Untwisting Iron Skin", &["PREABILITY:3,CATEGORY=FEAT,Perfect Style,Untwisting Iron Strength,Toughness", "PREMULT:1,[PRETOTALAB:13],[PREVARGTEQ:MonkLVL,13]", "PRESTAT:2,STR=15,WIS=13", "PRETEXT:Prerequisites: Str 15, Wis 13, Perfect Style, Toughness, Untwisting Iron Strength, base attack bonus +13 or monk level 13th."]),
    (RuleSetId::Isc, 16, "Untwisting Iron Strength", &["PREABILITY:1,CATEGORY=FEAT,Perfect Style", "PREMULT:1,[PRETOTALAB:9],[PREVARGTEQ:MonkLVL,9]", "PRESTAT:2,STR=15,WIS=13", "PRETEXT:Prerequisites: Str 15, Wis 13, Perfect Style, base attack bonus +9 or monk level 9th."]),
    (RuleSetId::Isc, 17, "Monstrous Mount", &["PREMULT:1,[PREVARGTEQ:Hunters_Bond_Animal_Companion,1,AnimalCompanionLVL,4],[PREVARGTEQ:Divine_Bond_Mount,1,SpecialMountLVL,4],[PREMULT:2,[PREABILITY:1,CATEGORY=Special Ability,TYPE.Mount],[PREVARGTEQ:CavalierMountLVL,4]],[PREMULT:2,[PREABILITY:1,CATEGORY=Special Ability,TYPE.Animal Companion],[PREVARGTEQ:SamuraiMountLVL,4]]", "PRESKILL:2,Handle Animal=4,Ride=4", "PRETEXT:Prerequisites: Handle Animal 4 ranks; Ride 4 ranks; divine bond (mount), hunter's bond (animal companion), or mount class feature with an effective druid level of 4."]),
    (RuleSetId::Isc, 18, "Monstrous Mount Mastery", &["PREABILITY:1,CATEGORY=FEAT,Monstrous Mount", "PRETEXT:Prerequisites: Monstrous Mount, character level equal to or higher than that listed in your mount's Mastery entry."]),
    (RuleSetId::Isc, 19, "Cannon Master", &["PREABILITY:2,CATEGORY=FEAT,Siege Engineer", "PRESKILL:1,Knowledge (engineering)=7,Profession (siege engineer)=7", "PRETEXT:Prerequisites: Siege Engineer, Knowledge (engineering) or Profession (siege engineer) 7 ranks, proficiency with at least one firearm siege engine."]),
    (RuleSetId::Isc, 20, "Casterbane Shot", &["PREABILITY:2,CATEGORY=FEAT,Point-Blank Shot,Precise Shot", "PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Amateur Gunslinger],[PREABILITY:1,CATEGORY=Special Ability,TYPE.Grit,Gunslinger ~ Grit]", "PRETEXT:Prerequisites: Amateur Gunslingeruc or the grit class feature, Point-Blank Shot, Precise Shot, base attack bonus +4.", "PRETOTALAB:4"]),
    (RuleSetId::Isc, 21, "Grand Duchy Familiarity", &["PRETEXT:Prerequisites: Base attack bonus +3, proficiency with at least one firearm.", "PRETOTALAB:3"]),
    (RuleSetId::Isc, 22, "Redirected Shot", &["PREABILITY:3,CATEGORY=FEAT,Deadly Aim,Point-Blank Shot,Precise Shot", "PREMULT:1,[PREABILITY:1,CATEGORY=FEAT,Amateur Gunslinger],[PREABILITY:1,CATEGORY=Special Ability,TYPE.Grit,Gunslinger ~ Grit]", "PRETEXT:Prerequisites: Amateur Gunslinger or the grit class feature, Deadly Aim, Point-Blank Shot, Precise Shot."]),
    // inner_sea_gods — 85 of 86 gap row(s) carry at least one `PRE`-family token.
    (RuleSetId::Isg, 0, "Arcane Insight", &["PREABILITY:1,CATEGORY=FEAT,Arcane Shield", "PREDEITY:[redacted PI]", "PRESPELLTYPE:1,Arcane=1", "PRETEXT:[redacted PI]", "PREVARGTEQ:Caster_Level_Highest__Arcane,10"]),
    (RuleSetId::Isg, 1, "Aura Of Succumbing", &["PREDEITY:1,PANTHEON.Four Horsemen", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,1],[PREVARGTEQ:ClericChannelNegativeEnergyDice,1],[PREVARGTEQ:OracleChannelDice,1]", "PRETEXT:Prerequisites: Channel energy class feature, worshiper of one of the Four Horsemen."]),
    (RuleSetId::Isg, 2, "Beacon Of Hope", &["PREDEITY:1,Milani", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,3],[PREVARGTEQ:ClericChannelNegativeEnergyDice,3],[PREVARGTEQ:OracleChannelDice,3]", "PRETEXT:Prerequisites: Channel energy 3d6, worshiper of Milani."]),
    (RuleSetId::Isg, 3, "Believable Veils", &["PRECLASS:1,SPELLCASTER=3", "PREDEITY:1,Sivanah", "PRETEXT:Prerequisites: Caster level 3rd, ability to cast at least one glamer or figment, worshiper of Sivanah."]),
    (RuleSetId::Isg, 4, "Bestow Hope", &["PREABILITY:1,CATEGORY=FEAT,Improved Channel", "PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,1],[PREVARGTEQ:ClericChannelNegativeEnergyDice,1],[PREVARGTEQ:OracleChannelDice,1]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 5, "Blessed Hammer", &["PREDEITY:[redacted PI]", "PRESPELLTYPE:1,Divine=3", "PRETEXT:[redacted PI]", "PREWEAPONPROF:1,Warhammer"]),
    (RuleSetId::Isg, 6, "Bloodletting", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 7, "Bloody Sabres", &["PREABILITY:2,CATEGORY=FEAT,Exotic Weapon Proficiency (sawtooth sabre),Two-Weapon Fighting", "PREDEITY:1,Achaekek", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,15],[PREVARGTEQ:FeatDexRequirement,15]", "PRETEXT:Prerequisites: Dex 15, Exotic Weapon Proficiency (sawtooth sabre), Two-Weapon Fighting, worshiper of Achaekek."]),
    (RuleSetId::Isg, 8, "Bloody Vengeance", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]", "PRETOTALAB:1"]),
    (RuleSetId::Isg, 9, "Bolster Undead", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,6],[PREVARGTEQ:ClericChannelNegativeEnergyDice,6],[PREVARGTEQ:OracleChannelDice,6]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 10, "Breaker Of Barriers", &["PREDEITY:[redacted PI]", "PRESTAT:1,STR=17", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 11, "Bullseye Shot", &["PREABILITY:2,CATEGORY=FEAT,Point-Blank Shot,Precise Shot", "PRETEXT:Prerequisites: Point-Blank Shot, Precise Shot, base attack bonus +5.", "PRETOTALAB:5"]),
    (RuleSetId::Isg, 12, "Butterfly's Sting", &["PREABILITY:1,CATEGORY=FEAT,Combat Expertise", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 13, "Channel Discord", &["PREDEITY:1,PANTHEON.Demon Lord", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,8],[PREVARGTEQ:ClericChannelNegativeEnergyDice,8],[PREVARGTEQ:OracleChannelDice,8]", "PRETEXT:Prerequisites: Channel energy 8d6, worshiper of a demon lord."]),
    (RuleSetId::Isg, 14, "Channel Endurance", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,3],[PREVARGTEQ:ClericChannelNegativeEnergyDice,3],[PREVARGTEQ:OracleChannelDice,3]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 15, "Channel Hate", &["PREDEITY:1,Gyronna", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,6],[PREVARGTEQ:ClericChannelNegativeEnergyDice,6],[PREVARGTEQ:OracleChannelDice,6]", "PRETEXT:Prerequisites: Channel energy 6d6, worshiper of Gyronna."]),
    (RuleSetId::Isg, 16, "Channel Viciousness", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,4],[PREVARGTEQ:ClericChannelNegativeEnergyDice,4],[PREVARGTEQ:OracleChannelDice,4]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 17, "Charge Of The Righteous", &["PREALIGN:LG,CG,NG", "PRETEXT:Prerequisites: Base attack bonus +1, any good alignment.", "PRETOTALAB:1"]),
    (RuleSetId::Isg, 18, "Clarifying Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,1],[PREVARGTEQ:ClericChannelNegativeEnergyDice,1],[PREVARGTEQ:OracleChannelDice,1]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 19, "Conversion Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,7],[PREVARGTEQ:ClericChannelNegativeEnergyDice,7],[PREVARGTEQ:OracleChannelDice,7]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 20, "Courage In A Bottle", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.Bravery", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 21, "Cruelty", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 22, "Curse Of Vengeance", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 23, "Deific Obedience", &["PREDEITY:1,Y", "PRESKILL:1,Knowledge (religion)=3", "PRETEXT:Prerequisites: Knowledge (religion) 3 ranks, must worship a deity."]),
    (RuleSetId::Isg, 24, "Destroy Identity", &["PREABILITY:1,CATEGORY=FEAT,Critical Focus", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]", "PRETOTALAB:11"]),
    (RuleSetId::Isg, 25, "Devilish Pride", &["PREABILITY:1,CATEGORY=FEAT,Iron Will", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 26, "Diabolical Negotiator", &["PREABILITY:1,CATEGORY=FEAT,Skill Focus (Diplomacy)", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 27, "Disciple Of The Sword", &["PREABILITY:1,CATEGORY=FEAT,Weapon Focus (longsword)", "PRECLASS:1,Cleric=4,Inquisitor=4", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 28, "Divination Guide", &["PREDEITY:1,Y", "PRETEXT:Prerequisites: Caster level 3rd, ability to cast augury or divination, must worship a deity.", "PREVARGTEQ:Caster_Level_Highest,3"]),
    (RuleSetId::Isg, 29, "Divine Barrier", &["PREDEITY:1,Apsu", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,1],[PREVARGTEQ:ClericChannelNegativeEnergyDice,1],[PREVARGTEQ:OracleChannelDice,1]", "PRETEXT:Prerequisites: Channel energy class feature, worshiper of Apsu."]),
    (RuleSetId::Isg, 30, "Divine Dignity", &["PREABILITY:1,CATEGORY=FEAT,Combat Casting", "PREDEITY:[redacted PI]", "PRESPELLTYPE:1,Divine=1", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 31, "Divine Expression", &["PRECLASS:1,Bard=1", "PRECLASS:1,Cleric=1,Oracle=1", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 32, "Dreamed Secrets", &["PREDEITY:1,PANTHEON.Great Old One,PANTHEON.Outer God", "PRESPELLTYPE:1,Divine=1", "PRETEXT:Prerequisites: Ability to cast divine spells, caster level 7th, worshiper of a Great Old One or Outer God.", "PREVARGTEQ:Caster_Level_Highest,7"]),
    (RuleSetId::Isg, 33, "Drunken Brawler", &["PREABILITY:1,CATEGORY=FEAT,Endurance", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 34, "Eerie Sense", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 35, "Elemental Vigor", &["PREDEITY:1,PANTHEON.Elemental Lord", "PRETEXT:Prerequisite: Worshiper of an elemental lord."]),
    (RuleSetId::Isg, 36, "Fateful Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,3],[PREVARGTEQ:ClericChannelNegativeEnergyDice,3],[PREVARGTEQ:OracleChannelDice,3]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 37, "Fearsome Finish", &["PREABILITY:1,CATEGORY=FEAT,Intimidating Prowess", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 38, "Fey Friend", &["PREDEITY:1,PANTHEON.Eldest", "PRETEXT:Prerequisite: Worshiper of one of the Eldest."]),
    (RuleSetId::Isg, 39, "Flagellant", &["PREABILITY:1,CATEGORY=FEAT,Endurance", "PREDEITY:[redacted PI]", "PREPCLEVEL:MIN=7", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 40, "Forceful Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,7],[PREVARGTEQ:ClericChannelNegativeEnergyDice,7],[PREVARGTEQ:OracleChannelDice,7]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 41, "Glorious Heat", &["PREDEITY:[redacted PI]", "PRESPELLTYPE:1,Divine=1", "PRETEXT:[redacted PI]", "PREVARGTEQ:Caster_Level_Highest,5"]),
    (RuleSetId::Isg, 42, "Hands Of Valor", &["PREABILITY:1,CATEGORY=Special Ability,TYPE.Lay on hands", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 43, "Hellish Shackles", &["PREDEITY:1,PANTHEON.Archdevil,PANTHEON.Infernal Duke,Malbranche,Whore Queen", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,5],[PREVARGTEQ:ClericChannelNegativeEnergyDice,5],[PREVARGTEQ:OracleChannelDice,5]", "PRETEXT:Prerequisites: Channel energy 5d6; worshiper of an archdevil, infernal duke, malbranche, or whore queen."]),
    (RuleSetId::Isg, 44, "Heroic Interposition", &["PREABILITY:3,CATEGORY=FEAT,Dodge,Improved Initiative,Mobility", "PREDEITY:1,PANTHEON.Empyreal Lord", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,13],[PREVARGTEQ:FeatDexRequirement,13]", "PRETEXT:Prerequisites: Dex 13, Dodge, Improved Initiative, Mobility, worshiper ofan empyreal lord."]),
    (RuleSetId::Isg, 45, "Hunter Of Dahak", &["PREDEITY:1,Dahak", "PRETEXT:Prerequisites: Favored enemy (dragon), worshiper of Dahak."]),
    (RuleSetId::Isg, 46, "Intrepid Rescuer", &["PREABILITY:1,CATEGORY=FEAT,Combat Reflexes", "PREDEITY:1,Kurgess", "PRETEXT:Prerequisites: Combat Reflexes, worshiper of Kurgess."]),
    (RuleSetId::Isg, 47, "Ironbound Master", &["PRECLASS:1,Cleric=7", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 48, "Ki Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,1],[PREVARGTEQ:ClericChannelNegativeEnergyDice,1],[PREVARGTEQ:OracleChannelDice,1]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 49, "Liberation Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,7],[PREVARGTEQ:ClericChannelNegativeEnergyDice,7],[PREVARGTEQ:OracleChannelDice,7]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 50, "Magical Epiphany", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 51, "Master Of Knowledge", &["PREABILITY:1,CATEGORY=FEAT,Skill Focus (Knowledge%", "PREDEITY:[redacted PI]", "PRESTAT:1,INT=17", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 52, "Measured Response", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]", "PRETOTALAB:1"]),
    (RuleSetId::Isg, 53, "Merciless Rush", &["PREABILITY:1,CATEGORY=FEAT,Improved Bull Rush", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 54, "Messenger Of Fate", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 55, "Nightmare Scars", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 56, "Nimble Natural Summons", &["PREABILITY:2,CATEGORY=FEAT,Augmented Summoning,Spell Focus (conjuration)", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]", "PREVARGTEQ:Caster_Level_Highest,6"]),
    (RuleSetId::Isg, 57, "Oath Of The Unbound", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 58, "Ordered Mind", &["PREALIGN:LN,LE,LG", "PRETEXT:Prerequisites: Caster level 7th, any lawful alignment.", "PREVARGTEQ:Caster_Level_Highest,7"]),
    (RuleSetId::Isg, 59, "Perfect Casting", &["PREABILITY:2,CATEGORY=FEAT,Combat Casting,Divine Dignity", "PREDEITY:[redacted PI]", "PRESPELLTYPE:1,Divine=1", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 60, "Persuasive Performer", &["PREABILITY:2,CATEGORY=Special Ability,TYPE.Versatile Performance", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 61, "Poisoner's Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,3],[PREVARGTEQ:ClericChannelNegativeEnergyDice,3],[PREVARGTEQ:OracleChannelDice,3]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 62, "Potion Glutton", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 63, "Protective Channel", &["PREDEITY:1,lomedae", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,7],[PREVARGTEQ:ClericChannelNegativeEnergyDice,7],[PREVARGTEQ:OracleChannelDice,7]", "PRETEXT:Prerequisites: Channel energy 7d6, worshiper of lomedae."]),
    (RuleSetId::Isg, 64, "Protector's Strike", &["PREABILITY:2,CATEGORY=Special Ability,Smite Evil", "PRETEXT:Prerequisites: Base attack bonus +5, smite evil class feature.", "PRETOTALAB:5"]),
    (RuleSetId::Isg, 65, "Reject Poison", &["PREABILITY:2,CATEGORY=Special Ability,TYPE.Poison Use", "PREDEITY:[redacted PI]", "PRESTAT:1,CON=13", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 66, "Riptide Attack", &["PREABILITY:2,CATEGORY=FEAT,Improved Drag,Improved Trip", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 67, "Savior's Arrow", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]", "PREWEAPONPROF:1,Longbow"]),
    (RuleSetId::Isg, 68, "Seductive Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,1],[PREVARGTEQ:ClericChannelNegativeEnergyDice,1],[PREVARGTEQ:OracleChannelDice,1]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 69, "Shadow Dodge", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,13],[PREVARGTEQ:FeatDexRequirement,13]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 70, "Shatter Resolve", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,1],[PREVARGTEQ:ClericChannelNegativeEnergyDice,1],[PREVARGTEQ:OracleChannelDice,1]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 71, "Siphon Channel", &["PREDEITY:1,Ghlaunder", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,3],[PREVARGTEQ:ClericChannelNegativeEnergyDice,3],[PREVARGTEQ:OracleChannelDice,3]", "PRETEXT:Prerequisites: Channel energy 3d6, worshiper of Ghlaunder."]),
    (RuleSetId::Isg, 72, "Spear Dancer", &["PREABILITY:1,CATEGORY=FEAT,Weapon Focus", "PRESKILL:1,Perform (Dance)=4", "PRETEXT:Prerequisites: Weapon Focus (any two-handed reach weapon), Perform (dance) 4 ranks."]),
    (RuleSetId::Isg, 73, "Spiked Destroyer", &["PRETEXT:Prerequisite: Proficient with armor spikes."]),
    (RuleSetId::Isg, 74, "Squash Flat", &["PREABILITY:2,CATEGORY=FEAT,Improved Bull Rush,Merciless Rush", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 75, "Steady Engagement", &["PREABILITY:2,CATEGORY=FEAT,Combat Reflexes,Stand Still", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 76, "Steelskin Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,7],[PREVARGTEQ:ClericChannelNegativeEnergyDice,7],[PREVARGTEQ:OracleChannelDice,7]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 77, "Stone Read", &["PRESKILL:1,Knowledge (dungeoneering)=4", "PRETEXT:Prerequisite: Knowledge (dungeoneering) 4 ranks."]),
    (RuleSetId::Isg, 78, "Stone Strider", &["PREABILITY:1,CATEGORY=Special Ability,Dwarf ~ Stonecunning", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 79, "Sun Striker", &["PREABILITY:2,CATEGORY=FEAT,Critical Focus,Weapon Focus (scimitar)", "PREDEITY:[redacted PI]", "PREPCLEVEL:MIN=7", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 80, "Thicket Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,7],[PREVARGTEQ:ClericChannelNegativeEnergyDice,7],[PREVARGTEQ:OracleChannelDice,7]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 81, "To The Last", &["PREABILITY:2,CATEGORY=FEAT,Diehard,Endurance", "PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 83, "Trailblazing Channel", &["PREDEITY:[redacted PI]", "PREMULT:1,[PREVARGTEQ:ClericChannelPositiveEnergyDice,3],[PREVARGTEQ:ClericChannelNegativeEnergyDice,3],[PREVARGTEQ:OracleChannelDice,3]", "PRETEXT:[redacted PI]"]),
    (RuleSetId::Isg, 84, "Undermining Exploit", &["PRESKILL:1,Knowledge (dungeoneering)=4", "PRETEXT:Prerequisite: Knowledge (dungeoneering) 4 ranks."]),
    (RuleSetId::Isg, 85, "Wave Master", &["PREDEITY:[redacted PI]", "PRETEXT:[redacted PI]"]),
];
