//! The verbatim ingest qualifier chains the shipped feat catalogs used to
//! carry a selection marker in, kept converter-side as the round-trip
//! oracle for the typed live form.
//!
//! SD-35 `AT-35-E6-003-SWEEP` cycle 12 (`decisions.md` §11 -- no PCGen in live
//! code; `epic-breakdown.md` `### AT-35-E6-003`). Before this cycle ten
//! `FeatEffectBonus` rows across four shipped tables stored the ingest
//! format's marker for "whatever the player picked" -- `WEAPONPROF=%LIST`
//! in the category slot, `%LIST` / `SCHOOL.%LIST` in the target slot,
//! `var("SKILLRANK=%LIST")` and `count("ABILITIES","TYPE=FavoredClassBonus")`
//! in the value slot. Twelve of `scripts/pcgen_residue_gate.py`'s code hits,
//! in `crb/feat_data/{combat,general}.rs`, `acg/feat_data/combat.rs` and
//! `advanced_race_guide/feat_data/general.rs`.
//!
//! The live tables now carry
//! [`EffectSelection`](crate::rules_core::rules_tables::crb::feats::EffectSelection)
//! instead, and the marker slot is gone from `qualifiers`.
//!
//! This table is the proof that the conversion lost nothing: one row per
//! converted bonus, holding the **verbatim** pre-conversion chain and the slot
//! the marker sat in, and a test that rebuilds that chain from the live
//! typed form and compares it element for element. It is converter-side data
//! -- nothing under a live root reads it -- and it is kept, not deleted,
//! because Starfinder ingests the same format (`decisions.md` §11, what is
//! kept).
//!
//! Generated by
//! `docs/release/SD-35-corpus-sheet-completion/artifacts/epic-6-pcgen-exit/AT-35-E6-003-SWEEP_cycle12_selection_typing.py`.
//! Do not hand-edit; re-run the generator.

use crate::rules_core::rules_tables::crb::feats::EffectSelection;

/// One converted bonus's verbatim pre-conversion qualifier chain.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FeatEffectSelectionRow {
    /// Which shipped feat catalog the bonus lives in: `crb`, `apg`, `acg`, `arg`.
    pub catalog: &'static str,
    /// The feat record's `key`.
    pub feat_key: &'static str,
    /// 0-based index of the bonus within that feat's `effect` slice.
    pub index: usize,
    /// The typed form the live side now carries.
    pub selection: EffectSelection,
    /// 0-based qualifier slot the ingest marker occupied.
    pub slot: usize,
    /// The marker exactly as the ingest record wrote it.
    pub marker: &'static str,
    /// The whole pre-conversion chain, pipe-joined, verbatim.
    pub chain: &'static str,
}

/// The ingest spelling each typed selection was converted from, and the
/// qualifier slot it occupied. This is the inverse of the conversion, and the
/// only place in the repository that still knows it.
pub const fn ingest_marker(selection: EffectSelection) -> (&'static str, usize) {
    match selection {
        EffectSelection::ChosenWeapon => ("WEAPONPROF=%LIST", 0),
        EffectSelection::ChosenSkill => ("%LIST", 1),
        EffectSelection::ChosenSpellSchool => ("SCHOOL.%LIST", 1),
        EffectSelection::ChosenSkillRanks => ("var(\\\"SKILLRANK=%LIST\\\")", 2),
        EffectSelection::FavoredClassBonusCount => {
            ("count(\\\"ABILITIES\\\",\\\"TYPE=FavoredClassBonus\\\")", 2)
        }
    }
}

/// Every converted chain, in catalog source order.
pub const FEAT_EFFECT_SELECTIONS: &[FeatEffectSelectionRow] = &[
    FeatEffectSelectionRow { catalog: "crb", feat_key: "Greater Spell Focus", index: 0, selection: EffectSelection::ChosenSpellSchool, slot: 1, marker: "SCHOOL.%LIST", chain: "DC|SCHOOL.%LIST|2" },
    FeatEffectSelectionRow { catalog: "crb", feat_key: "Greater Weapon Focus", index: 0, selection: EffectSelection::ChosenWeapon, slot: 0, marker: "WEAPONPROF=%LIST", chain: "WEAPONPROF=%LIST|TOHIT|GreaterWeaponFocusToHit" },
    FeatEffectSelectionRow { catalog: "crb", feat_key: "Greater Weapon Specialization", index: 0, selection: EffectSelection::ChosenWeapon, slot: 0, marker: "WEAPONPROF=%LIST", chain: "WEAPONPROF=%LIST|DAMAGE|2" },
    FeatEffectSelectionRow { catalog: "crb", feat_key: "Improved Critical", index: 0, selection: EffectSelection::ChosenWeapon, slot: 0, marker: "WEAPONPROF=%LIST", chain: "WEAPONPROF=%LIST|CRITRANGEDOUBLE|1" },
    FeatEffectSelectionRow { catalog: "crb", feat_key: "Master Craftsman", index: 1, selection: EffectSelection::ChosenSkillRanks, slot: 2, marker: "var(\\\"SKILLRANK=%LIST\\\")", chain: "VAR|MasterCraftsmanRanks|var(\\\"SKILLRANK=%LIST\\\")" },
    FeatEffectSelectionRow { catalog: "crb", feat_key: "Skill Focus", index: 0, selection: EffectSelection::ChosenSkill, slot: 1, marker: "%LIST", chain: "SKILL|%LIST|3" },
    FeatEffectSelectionRow { catalog: "crb", feat_key: "Spell Focus", index: 0, selection: EffectSelection::ChosenSpellSchool, slot: 1, marker: "SCHOOL.%LIST", chain: "DC|SCHOOL.%LIST|1" },
    FeatEffectSelectionRow { catalog: "crb", feat_key: "Weapon Focus", index: 0, selection: EffectSelection::ChosenWeapon, slot: 0, marker: "WEAPONPROF=%LIST", chain: "WEAPONPROF=%LIST|TOHIT|WeaponFocusToHit" },
    FeatEffectSelectionRow { catalog: "crb", feat_key: "Weapon Specialization", index: 0, selection: EffectSelection::ChosenWeapon, slot: 0, marker: "WEAPONPROF=%LIST", chain: "WEAPONPROF=%LIST|DAMAGE|2" },
    FeatEffectSelectionRow { catalog: "acg", feat_key: "Slashing Grace", index: 0, selection: EffectSelection::ChosenWeapon, slot: 0, marker: "WEAPONPROF=%LIST", chain: "WEAPONPROF=%LIST|DAMAGE|DEX" },
    FeatEffectSelectionRow { catalog: "acg", feat_key: "Slashing Grace", index: 1, selection: EffectSelection::ChosenWeapon, slot: 0, marker: "WEAPONPROF=%LIST", chain: "WEAPONPROF=%LIST|DAMAGE|-STR" },
    FeatEffectSelectionRow { catalog: "arg", feat_key: "Multitalented Mastery", index: 1, selection: EffectSelection::FavoredClassBonusCount, slot: 2, marker: "count(\\\"ABILITIES\\\",\\\"TYPE=FavoredClassBonus\\\")", chain: "VAR|FavoredClassLevels|count(\\\"ABILITIES\\\",\\\"TYPE=FavoredClassBonus\\\")" },
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules_core::rules_tables::advanced_race_guide::feats as arg_feats;
    use crate::rules_core::rules_tables::{acg, apg, crb};

    /// Rebuild one live bonus's pre-conversion chain: re-insert the ingest
    /// marker at the slot it came out of.
    fn rebuilt_chain(qualifiers: &[&str], selection: EffectSelection) -> String {
        let (marker, slot) = ingest_marker(selection);
        let mut parts: Vec<String> = qualifiers.iter().map(|q| (*q).to_string()).collect();
        parts.insert(slot, marker.to_string());
        parts.join("|")
    }

    /// Every live bonus carrying a selection, as
    /// `(catalog, feat key, index, selection, rebuilt chain)`.
    fn live_selections() -> Vec<(String, String, usize, EffectSelection, String)> {
        let mut out = Vec::new();
        for (catalog, entries) in [
            ("crb", crb::feats::feat_tables()),
            ("apg", apg::feats::feat_tables()),
            ("acg", acg::feats::feat_tables()),
        ] {
            for entry in entries {
                let Some(bonuses) = entry.effect else { continue };
                for (index, bonus) in bonuses.iter().enumerate() {
                    if let Some(selection) = bonus.selection {
                        out.push((
                            catalog.to_string(),
                            entry.key.to_string(),
                            index,
                            selection,
                            rebuilt_chain(bonus.qualifiers, selection),
                        ));
                    }
                }
            }
        }
        for entry in arg_feats::feat_tables() {
            let Some(bonuses) = entry.effect else { continue };
            for (index, bonus) in bonuses.iter().enumerate() {
                if let Some(selection) = bonus.selection {
                    out.push((
                        "arg".to_string(),
                        entry.key.to_string(),
                        index,
                        selection,
                        rebuilt_chain(bonus.qualifiers, selection),
                    ));
                }
            }
        }
        out
    }

    /// The live typed form reproduces every converted ingest chain exactly.
    ///
    /// This is the whole proof of the cycle-12 conversion: if a slot had been
    /// dropped, re-ordered or re-spelled on the way into `src/rules_core/`,
    /// the rebuilt chain would differ here.
    #[test]
    fn every_converted_chain_round_trips_from_the_live_typed_form() {
        assert!(
            !FEAT_EFFECT_SELECTIONS.is_empty(),
            "the round-trip table must not be empty -- an empty table proves nothing"
        );
        let live = live_selections();
        for row in FEAT_EFFECT_SELECTIONS {
            let found = live
                .iter()
                .find(|(c, k, i, _, _)| c == row.catalog && k == row.feat_key && *i == row.index)
                .unwrap_or_else(|| {
                    panic!(
                        "no live bonus with a selection at {}/{}#{}",
                        row.catalog, row.feat_key, row.index
                    )
                });
            assert_eq!(found.3, row.selection, "{}/{}#{} selection changed", row.catalog, row.feat_key, row.index);
            assert_eq!(
                found.4, row.chain,
                "{}/{}#{} chain did not round-trip",
                row.catalog, row.feat_key, row.index
            );
        }
    }

    /// Every live bonus that carries a selection is addressed by this table,
    /// and no row addresses a bonus that has none. Without this the round-trip
    /// test could pass while silently ignoring a converted row.
    #[test]
    fn the_table_addresses_exactly_the_live_bonuses_that_carry_a_selection() {
        let mut live: Vec<(String, String, usize)> = live_selections()
            .into_iter()
            .map(|(c, k, i, _, _)| (c, k, i))
            .collect();
        let mut listed: Vec<(String, String, usize)> = FEAT_EFFECT_SELECTIONS
            .iter()
            .map(|r| (r.catalog.to_string(), r.feat_key.to_string(), r.index))
            .collect();
        live.sort();
        listed.sort();
        assert_eq!(listed, live);
    }

    /// Each recorded row's `marker`/`slot` pair is the one
    /// `ingest_marker` returns for its variant -- so the table and the
    /// inverse function can never drift apart.
    #[test]
    fn the_recorded_marker_matches_the_inverse_function() {
        for row in FEAT_EFFECT_SELECTIONS {
            let (marker, slot) = ingest_marker(row.selection);
            assert_eq!(row.marker, marker, "{}/{}", row.catalog, row.feat_key);
            assert_eq!(row.slot, slot, "{}/{}", row.catalog, row.feat_key);
        }
    }
}
