//! The ingest tails five shipped prose strings used to carry, relocated off the
//! live side -- SD-35 `AT-35-E6-003-SWEEP` cycle 9, enforcing `decisions.md`
//! §11 and the sheet rule (`decisions.md` §1).
//!
//! # Why these moved, and why they were not deleted
//!
//! Five `description:` / `benefit:` strings in `rules_tables` ended with an
//! ingest tail glued to the sentence a player reads on a printed character
//! sheet -- a `%N` argument's variable name, a `PRE<FAMILY>:` guard, or both:
//!
//! ```text
//! "...rip magical defenses from your enemy.  PREABILITY:1,CATEGORY=FEAT,Improved Unarmed Strike"
//! "...a +%1 enhancement bonus to her base speed.|BeastmorphSpeed|PREVAREQ:BeastmorphProgression,1"
//! ```
//!
//! The sheet prints the rule's words; `PREVAREQ:BeastmorphProgression,1` is not
//! words. The live strings now hold the prose and only the prose.
//!
//! This is a **move, not a removal**, on cycle 2's own precedent
//! (`archetype_swap_prereq_tokens`): the tails are the provenance of each
//! converted gate (`AGENTS.md` rule 9) and they are KEPT for Starfinder
//! (`decisions.md` §11, what is kept). Keyed by (table, record key), so a
//! consumer that ever needs one is a lookup away.
//!
//! Generated by
//! `docs/release/SD-35-corpus-sheet-completion/artifacts/epic-6-pcgen-exit/AT-35-E6-003-SWEEP_cycle9_prose_tail_relocate.py`.
//! Do not hand-edit; re-run the generator.

/// One relocated ingest tail.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProseIngestTail {
    /// The shipped table the prose lives in, as a repo-relative path.
    pub table: &'static str,
    /// The record's own corpus key.
    pub record_key: &'static str,
    /// Which prose field carried it: `description` or `benefit`.
    pub field: &'static str,
    /// The prose the live table kept, character for character.
    pub prose: &'static str,
    /// The tail the live table no longer carries, verbatim and pipe-joined.
    pub tail: &'static str,
}

/// Every relocated tail.
pub const PROSE_INGEST_TAILS: &[ProseIngestTail] = &[
    ProseIngestTail { table: "src/rules_core/rules_tables/ultimate_combat/feat_tables.rs", record_key: "Skilled Driver", field: "benefit", prose: "You gain a +4 bonus on driving checks with your chosen vehicle.", tail: "%LIST" },
    ProseIngestTail { table: "src/rules_core/rules_tables/ultimate_combat/feat_tables.rs", record_key: "Dispelling Fist", field: "description", prose: "By focusing on your knowledge of magic and spells that negate its powers, you use your bare hands to rip magical defenses from your enemy.", tail: "PREABILITY:1,CATEGORY=FEAT,Improved Unarmed Strike" },
    ProseIngestTail { table: "src/rules_core/rules_tables/ultimate_magic/feat_tables.rs", record_key: "Versatile Channeler", field: "benefit", prose: "You may choose to channel positive energy as if your effective cleric level were 2 levels lower than normal.", tail: "PREABILITY:1,CATEGORY=Special Ability,Versatile Channeler ~ Positive Energy" },
    ProseIngestTail { table: "src/rules_core/rules_tables/acg/archetype_tables.rs", record_key: "Mutagenic Mauler Brawler ~ Beastmorph", field: "description", prose: "A mutagenic mauler gains additional abilities when using her mutagen. She gains low-light vision and a +%1 enhancement bonus to her base speed.", tail: "BeastmorphSpeed|PREVAREQ:BeastmorphProgression,1" },
    ProseIngestTail { table: "src/rules_core/rules_tables/ultimate_magic/archetype_tables.rs", record_key: "Internal Alchemist ~ Disease Resistance", field: "description", prose: "You gain a +%1 bonus on all saving throws against disease.", tail: "AlchemistPoisonResistanceBonus|!PREABILITY:1,CATEGORY=Special Ability,Poison Immunity ~ Alchemist" },
    ProseIngestTail { table: "src/rules_core/rules_tables/ultimate_psionics/archetype_tables.rs", record_key: "Thoughtsinger ~ Collective", field: "description", prose: "Join %1 minds, plus your own, within %2 feet; can manifest some powers through collective.", tail: "ThoughtsingerCollectiveMinds|ThoughtsingerCollectiveRange|!PREABILITY:1,CATEGORY=Internal,Thoughtsinger ~ Collective Range Unlimited" },
];

#[cfg(test)]
mod tests {
    use super::*;

    /// Every recorded tail is a real ingest tail, and every recorded prose half
    /// is what the live table now ships.
    ///
    /// The prose halves are compared against the shipped tables by the
    /// generator's own `--check` mode rather than at run time: a `rules_tables`
    /// read from here would be a live-side module reading converter-side data,
    /// which is the direction this whole epic exists to prevent.
    #[test]
    fn every_row_carries_prose_on_one_side_and_ingest_vocabulary_on_the_other() {
        assert!(!PROSE_INGEST_TAILS.is_empty());
        for row in PROSE_INGEST_TAILS {
            assert!(
                row.tail.contains("PRE") || row.tail.contains("%LIST"),
                "{}: recorded tail is neither a guard nor a selection slot: {:?}",
                row.record_key,
                row.tail
            );
            assert!(
                !row.prose.contains("PRE")
                    && !row.prose.contains('|')
                    && !row.prose.contains("%LIST"),
                "{}: the kept prose still carries ingest vocabulary: {:?}",
                row.record_key,
                row.prose
            );
            assert!(
                row.field == "description" || row.field == "benefit",
                "{}: unexpected field {:?}",
                row.record_key,
                row.field
            );
        }
    }

    #[test]
    fn the_tails_are_addressed_uniquely() {
        let mut seen = std::collections::HashSet::new();
        for row in PROSE_INGEST_TAILS {
            assert!(
                seen.insert((row.table, row.record_key, row.field)),
                "{}/{} {} recorded twice",
                row.table,
                row.record_key,
                row.field
            );
        }
    }
}
