//! Generated from the real PCGen corpus file `cr_feats.lst` (`TYPE:` facet
//! containing `Combat`). 110 records, transcribed verbatim
//! (`KEY:`/name, `TYPE:`, `DESC:`, `BONUS:`) from the corpus's `###Block:
//! General Feats` section -- see `feats.rs`'s own doc comment for why
//! category is derived from the `TYPE:` facet rather than the corpus's
//! `###Block:` markers, and for the generation method. Not hand-authored --
//! do not hand-edit; regenerate if the corpus changes.

use crate::rules_core::rules_tables::crb::feats::{ConditionItem, EffectCondition, EffectSelection, FeatCategory, FeatEffectBonus, FeatTableEntry};

pub const COMBAT_TABLE: &[FeatTableEntry] = &[
    FeatTableEntry { key: "Agile Maneuvers", category: FeatCategory::Combat, name: "Agile Maneuvers", description: Some("You learned to use your quickness in place of brute force when performing combat maneuvers."), effect: Some(&[FeatEffectBonus {
        qualifiers: &["VAR", "CMB_STAT", "DEX-STR"],
        bonus_type: None,
        conditions: &[
            EffectCondition {
                negated: false,
                family: "SIZEGT",
                items: &[
                    ConditionItem { facet: None, value: "T" },
                ],
                alternatives: &[],
            },
        ],
        selection: None,
    }])},
    FeatTableEntry { key: "Arcane Armor Mastery", category: FeatCategory::Combat, name: "Arcane Armor Mastery", description: Some("You have mastered the ability to cast spells while wearing armor."), effect: None},
    FeatTableEntry { key: "Arcane Armor Training", category: FeatCategory::Combat, name: "Arcane Armor Training", description: Some("You have learned how to cast spells while wearing armor."), effect: None},
    FeatTableEntry { key: "Arcane Strike", category: FeatCategory::Combat, name: "Arcane Strike", description: Some("As a swift action, you can imbue your weapons with a fraction of your power. For 1 round, you gain a +%1 damage bonus and your weapons are treated as magic for the purpose of overcoming damage reduction.|ArcaneStrikeDamageBonus"), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "ArcaneStrikeDamageBonus", "min(1+ArcaneStrikeLVL/5,5)"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Armor Proficiency (Heavy)", category: FeatCategory::Combat, name: "Armor Proficiency (Heavy)", description: Some("You are skilled at wearing heavy armor."), effect: None},
    FeatTableEntry { key: "Armor Proficiency (Light)", category: FeatCategory::Combat, name: "Armor Proficiency (Light)", description: Some("You are skilled at wearing light armor."), effect: None},
    FeatTableEntry { key: "Armor Proficiency (Medium)", category: FeatCategory::Combat, name: "Armor Proficiency (Medium)", description: Some("You are skilled at wearing medium armor."), effect: None},
    FeatTableEntry { key: "Bleeding Critical", category: FeatCategory::Combat, name: "Bleeding Critical", description: Some("Your critical hits cause opponents to bleed profusely."), effect: None},
    FeatTableEntry { key: "Blind-Fight", category: FeatCategory::Combat, name: "Blind-Fight", description: Some("You are skillled at attacking opponents that you cannot clearly perceive."), effect: None},
    FeatTableEntry { key: "Blinding Critical", category: FeatCategory::Combat, name: "Blinding Critical", description: Some("Your critical hits blind your opponents."), effect: None},
    FeatTableEntry { key: "Catch Off-Guard", category: FeatCategory::Combat, name: "Catch Off-Guard", description: Some("Foes are surprised by your skilled use of unorthodox and improvised weapons."), effect: None},
    FeatTableEntry { key: "Channel Smite", category: FeatCategory::Combat, name: "Channel Smite", description: Some("You can channel your divine energy through your weapon."), effect: None},
    FeatTableEntry { key: "Cleave", category: FeatCategory::Combat, name: "Cleave", description: Some("You can strike two adjacent foes with a single swing."), effect: None},
    FeatTableEntry { key: "Combat Expertise", category: FeatCategory::Combat, name: "Combat Expertise", description: Some("You can increase your defense at the expense of your accuracy."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CombatExpertiseModifier", "((BAB+(FlurryLVL-MonkBAB))/4)+1"], bonus_type: Some("Base"), conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["VAR", "CombatExpertiseModifierAttack", "-CombatExpertiseModifier"], bonus_type: Some("Base"), conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["VAR", "CombatExpertiseModifierAC", "CombatExpertiseModifier"], bonus_type: Some("Base"), conditions: &[], selection: None }])},
    FeatTableEntry { key: "Combat Expertise", category: FeatCategory::Combat, name: "Combat Expertise", description: Some("You can increase your defense at the expense of your accuracy."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CombatExpertiseModifier", "floor(BAB/4)+1"], bonus_type: None, conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["VAR", "CombatExpertiseModifierAttack", "-CombatExpertiseModifier"], bonus_type: None, conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["VAR", "CombatExpertiseModifierAC", "CombatExpertiseModifier"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Combat Reflexes", category: FeatCategory::Combat, name: "Combat Reflexes", description: Some("You can make additional attacks of opportunity."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CombatReflexesAttacks", "DEX"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Critical Focus", category: FeatCategory::Combat, name: "Critical Focus", description: Some("You are trained in the arts of causing pain."), effect: None},
    FeatTableEntry { key: "Critical Mastery", category: FeatCategory::Combat, name: "Critical Mastery", description: Some("Your critical hits cause two additional effects."), effect: None},
    FeatTableEntry { key: "Dazzling Display", category: FeatCategory::Combat, name: "Dazzling Display", description: Some("Your skill with your favored weapon can frighten enemies."), effect: None},
    FeatTableEntry { key: "Deadly Aim", category: FeatCategory::Combat, name: "Deadly Aim", description: Some("You can make exceptionally deadly ranged attacks by pinpointing a foe's weak spot, at the expense of making the attack less likely to succeed."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "DeadlyAimModifier", "floor(BAB/4)+1"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Deadly Stroke", category: FeatCategory::Combat, name: "Deadly Stroke", description: Some("With a well-placed strike, you can bring a swift and painful end to most foes."), effect: None},
    FeatTableEntry { key: "Deafening Critical", category: FeatCategory::Combat, name: "Deafening Critical", description: Some("Your critical hits cause enemies to lose their hearing."), effect: None},
    FeatTableEntry { key: "Defensive Combat Training", category: FeatCategory::Combat, name: "Defensive Combat Training", description: Some("You excel at defending yourself from all manner of combat maneuvers."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMD_BAB", "TL-BAB"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Deflect Arrows", category: FeatCategory::Combat, name: "Deflect Arrows", description: Some("You can know arrows and other projectiles off course, preventing them from hitting you."), effect: None},
    FeatTableEntry { key: "Disruptive", category: FeatCategory::Combat, name: "Disruptive", description: Some("Your training makes it difficult for enemy spellcasters to safely cast spells near you."), effect: None},
    FeatTableEntry { key: "Dodge", category: FeatCategory::Combat, name: "Dodge", description: Some("Your training and reflexes allow you to react swiftly to avoid an opponent's attack."), effect: Some(&[FeatEffectBonus { qualifiers: &["COMBAT", "AC", "1"], bonus_type: Some("Dodge"), conditions: &[], selection: None }])},
    FeatTableEntry { key: "Double Slice", category: FeatCategory::Combat, name: "Double Slice", description: Some("Your off-hand weapon while dual-wielding strikes with greater power."), effect: Some(&[FeatEffectBonus { qualifiers: &["COMBAT", "DAMAGEMULT:0", "1"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Exhausting Critical", category: FeatCategory::Combat, name: "Exhausting Critical", description: Some("Your critical hits cause opponents to become exhausted."), effect: None},
    FeatTableEntry { key: "Exotic Weapon Proficiency", category: FeatCategory::Combat, name: "Exotic Weapon Proficiency", description: Some("You understand how to use your chosen exotic weapon in combat, and can utilize any special tricks or qualities that exotic weapon might allow."), effect: None},
    FeatTableEntry { key: "Far Shot", category: FeatCategory::Combat, name: "Far Shot", description: Some("You are more accurate at longer ranges."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "RangePenaltyValue", "1"], bonus_type: Some("Base"), conditions: &[], selection: None }])},
    FeatTableEntry { key: "Gorgon's Fist", category: FeatCategory::Combat, name: "Gorgon's Fist", description: Some("With one well-placed blow, you leave your target reeling."), effect: None},
    FeatTableEntry { key: "Great Cleave", category: FeatCategory::Combat, name: "Great Cleave", description: Some("You can strike many adjacent foes with a single blow."), effect: None},
    FeatTableEntry { key: "Greater Bull Rush", category: FeatCategory::Combat, name: "Greater Bull Rush", description: Some("Your bull rush attacks throw enemies off balance."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_BullRush", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Greater Disarm", category: FeatCategory::Combat, name: "Greater Disarm", description: Some("You can knock weapons far from an enemy's grasp."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Disarm", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Greater Feint", category: FeatCategory::Combat, name: "Greater Feint", description: Some("You are skilled at making foes overreact to your attacks."), effect: None},
    FeatTableEntry { key: "Greater Grapple", category: FeatCategory::Combat, name: "Greater Grapple", description: Some("Maintaining a grapple is second nature to you."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Grapple", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Greater Overrun", category: FeatCategory::Combat, name: "Greater Overrun", description: Some("Enemies must dive to avoid your dangerous move."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Overrun", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Greater Penetrating Strike", category: FeatCategory::Combat, name: "Greater Penetrating Strike", description: Some("Your attacks with your chosen weapon penetrate the defenses of most creatures."), effect: None},
    FeatTableEntry { key: "Greater Shield Focus", category: FeatCategory::Combat, name: "Greater Shield Focus", description: Some("You are skilled at deflecting blows with your shield."), effect: Some(&[FeatEffectBonus {
        qualifiers: &["COMBAT", "AC", "1"],
        bonus_type: Some("Shield.STACK"),
        conditions: &[
            EffectCondition {
                negated: false,
                family: "EQUIP",
                items: &[
                    ConditionItem { facet: None, value: "1" },
                    ConditionItem { facet: Some("TYPE"), value: "Shield" },
                ],
                alternatives: &[],
            },
        ],
        selection: None,
    }])},
    FeatTableEntry { key: "Greater Sunder", category: FeatCategory::Combat, name: "Greater Sunder", description: Some("Your devastating strikes cleave through weapons and into their wielders, damaging both item and wielder alike in a single terrific strike."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Sunder", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Greater Trip", category: FeatCategory::Combat, name: "Greater Trip", description: Some("You can make free attacks on foes that you knock down."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Trip", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Greater Two-Weapon Fighting", category: FeatCategory::Combat, name: "Greater Two-Weapon Fighting", description: Some("You are incredibly skilled at fighting with two weapons at the same time."), effect: Some(&[FeatEffectBonus { qualifiers: &["COMBAT", "SECONDARYATTACKS", "1"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Greater Vital Strike", category: FeatCategory::Combat, name: "Greater Vital Strike", description: Some("You can make a single attack that deals a tremendous amount of damage."), effect: None},
    FeatTableEntry { key: "Greater Weapon Focus", category: FeatCategory::Combat, name: "Greater Weapon Focus", description: Some("You are a master at your chosen weapon."), effect: Some(&[FeatEffectBonus { qualifiers: &["TOHIT", "GreaterWeaponFocusToHit"], bonus_type: None, conditions: &[], selection: Some(EffectSelection::ChosenWeapon) }])},
    FeatTableEntry { key: "Greater Weapon Specialization", category: FeatCategory::Combat, name: "Greater Weapon Specialization", description: Some("You deal extra damage when using your chosen weapon."), effect: Some(&[FeatEffectBonus { qualifiers: &["DAMAGE", "2"], bonus_type: None, conditions: &[], selection: Some(EffectSelection::ChosenWeapon) }])},
    FeatTableEntry { key: "Improved Bull Rush", category: FeatCategory::Combat, name: "Improved Bull Rush", description: Some("You are skilled at pushing your foes around."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_BullRush,CMD_BullRush", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Improved Critical", category: FeatCategory::Combat, name: "Improved Critical", description: Some("Attacks made with your chosen weapon are quite deadly."), effect: Some(&[FeatEffectBonus { qualifiers: &["CRITRANGEDOUBLE", "1"], bonus_type: Some("NonStackingCrit"), conditions: &[], selection: Some(EffectSelection::ChosenWeapon) }])},
    FeatTableEntry { key: "Improved Disarm", category: FeatCategory::Combat, name: "Improved Disarm", description: Some("You are skilled at knocking weapons from a foe's grasp."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Disarm,CMD_Disarm", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Improved Feint", category: FeatCategory::Combat, name: "Improved Feint", description: Some("You are skilled at fooling your opponents in combat."), effect: None},
    FeatTableEntry { key: "Improved Grapple", category: FeatCategory::Combat, name: "Improved Grapple", description: Some("You are skilled at grappling opponents."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Grapple,CMD_Grapple", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Improved Initiative", category: FeatCategory::Combat, name: "Improved Initiative", description: Some("Your quick reflexes allow you to react quickly to danger."), effect: Some(&[FeatEffectBonus { qualifiers: &["COMBAT", "INITIATIVE", "4"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Improved Overrun", category: FeatCategory::Combat, name: "Improved Overrun", description: Some("You are skilled at running down your foes."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Overrun,CMD_Overrun", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Improved Precise Shot", category: FeatCategory::Combat, name: "Improved Precise Shot", description: Some("Your ranged attacks ignore anything but total concealment and cover."), effect: None},
    FeatTableEntry { key: "Improved Shield Bash", category: FeatCategory::Combat, name: "Improved Shield Bash", description: Some("You can protect yourself with your shield, even if you use it to attack."), effect: None},
    FeatTableEntry { key: "Improved Sunder", category: FeatCategory::Combat, name: "Improved Sunder", description: Some("You are skilled at damaging your foes' weapons and armor."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Sunder,CMD_Sunder", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Improved Trip", category: FeatCategory::Combat, name: "Improved Trip", description: Some("You are skilled at sending your opponents to the ground."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Trip,CMD_Trip", "2"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Improved Two-Weapon Fighting", category: FeatCategory::Combat, name: "Improved Two-Weapon Fighting", description: Some("You are skilled at fighting with two weapons."), effect: Some(&[FeatEffectBonus { qualifiers: &["COMBAT", "SECONDARYATTACKS", "1"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Improved Unarmed Strike", category: FeatCategory::Combat, name: "Improved Unarmed Strike", description: Some("You are skilled while fighting unarmed."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "UnarmedLethal", "1"], bonus_type: Some("Boolean"), conditions: &[], selection: None }])},
    FeatTableEntry { key: "Improved Vital Strike", category: FeatCategory::Combat, name: "Improved Vital Strike", description: Some("You can make a single attack that deals a large amount of damage."), effect: None},
    FeatTableEntry { key: "Improvised Weapon Mastery", category: FeatCategory::Combat, name: "Improvised Weapon Mastery", description: Some("You can turn nearly any object into a deadly weapon, from a razor sharp chair leg to a sack of flour."), effect: None},
    FeatTableEntry { key: "Intimidating Prowess", category: FeatCategory::Combat, name: "Intimidating Prowess", description: Some("Your physical might is intimidating to others."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Intimidate", "STR"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Lightning Stance", category: FeatCategory::Combat, name: "Lightning Stance", description: Some("The speed at which you move makes it nearly impossible for opponents to strike you."), effect: None},
    FeatTableEntry { key: "Lunge", category: FeatCategory::Combat, name: "Lunge", description: Some("You can strike foes that would normally be out of reach."), effect: None},
    FeatTableEntry { key: "Manyshot", category: FeatCategory::Combat, name: "Manyshot", description: Some("You can fire multiple arrows at a single target."), effect: None},
    FeatTableEntry { key: "Martial Weapon Proficiency", category: FeatCategory::Combat, name: "Martial Weapon Proficiency", description: Some("You understand how to use your chosen martial weapon in combat."), effect: None},
    FeatTableEntry { key: "Medusa's Wrath", category: FeatCategory::Combat, name: "Medusa's Wrath", description: Some("You can take advantage of your opponent's confusion, delivering multiple blows."), effect: None},
    FeatTableEntry { key: "Mobility", category: FeatCategory::Combat, name: "Mobility", description: Some("You can easily move through a dangerous melee."), effect: None},
    FeatTableEntry { key: "Mounted Archery", category: FeatCategory::Combat, name: "Mounted Archery", description: Some("You are skilled at making ranged attacks while mounted."), effect: None},
    FeatTableEntry { key: "Mounted Combat", category: FeatCategory::Combat, name: "Mounted Combat", description: Some("You are adept at guiding your mount through combat."), effect: None},
    FeatTableEntry { key: "Penetrating Strike", category: FeatCategory::Combat, name: "Penetrating Strike", description: Some("Your attacks with your chosen weapon are capable of penetrating the defenses of some creatures."), effect: None},
    FeatTableEntry { key: "Pinpoint Targeting", category: FeatCategory::Combat, name: "Pinpoint Targeting", description: Some("You can target the weak points in your opponent's armor."), effect: None},
    FeatTableEntry { key: "Point-Blank Shot", category: FeatCategory::Combat, name: "Point-Blank Shot", description: Some("You are especially accurate when making ranged attacks against close target."), effect: Some(&[FeatEffectBonus { qualifiers: &["COMBAT", "TOHIT-SHORTRANGE,DAMAGE-SHORTRANGE", "1"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Power Attack", category: FeatCategory::Combat, name: "Power Attack", description: Some("You can make exceptionally deadly melee attacks by sacrificing accuracy for strength."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "PowerAttackModifier", "(BAB/4)+1"], bonus_type: None, conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["VAR", "PowerAttackDamageBase", "2"], bonus_type: None, conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["VAR", "PowerAttackDamageModifier", "PowerAttackDamageBase*floor(PowerAttackModifier)"], bonus_type: None, conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["VAR", "MonkFlurryPowerAttackModifier", "BAB+(FlurryLVL-MonkBAB)"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Precise Shot", category: FeatCategory::Combat, name: "Precise Shot", description: Some("You are adept at firing ranged attacks into melee."), effect: None},
    FeatTableEntry { key: "Quick Draw", category: FeatCategory::Combat, name: "Quick Draw", description: Some("You can draw weapons faster than most."), effect: None},
    FeatTableEntry { key: "Rapid Reload", category: FeatCategory::Combat, name: "Rapid Reload", description: Some("Choose a type of crossbow (hand, light, or heavy). You can reload such weapons quickly."), effect: None},
    FeatTableEntry { key: "Rapid Shot", category: FeatCategory::Combat, name: "Rapid Shot", description: Some("You can make an additional ranged attack."), effect: None},
    FeatTableEntry { key: "Ride-By Attack", category: FeatCategory::Combat, name: "Ride-By Attack", description: Some("While mounted, you can move, strike at a foe, and then continue moving."), effect: None},
    FeatTableEntry { key: "Scorpion Style", category: FeatCategory::Combat, name: "Scorpion Style", description: Some("You can perform an unarmed strike that greatly hampers your target's movement."), effect: None},
    FeatTableEntry { key: "Shatter Defenses", category: FeatCategory::Combat, name: "Shatter Defenses", description: Some("Your skill with your chosen weapon leaves opponents unable to defend themselves if you strike them when their defenses are already compromised."), effect: None},
    FeatTableEntry { key: "Shield Focus", category: FeatCategory::Combat, name: "Shield Focus", description: Some("You are skilled at deflecting blows with your shield."), effect: Some(&[FeatEffectBonus {
        qualifiers: &["COMBAT", "AC", "1"],
        bonus_type: Some("Shield.STACK"),
        conditions: &[
            EffectCondition {
                negated: false,
                family: "EQUIP",
                items: &[
                    ConditionItem { facet: None, value: "1" },
                    ConditionItem { facet: Some("TYPE"), value: "Shield" },
                ],
                alternatives: &[],
            },
        ],
        selection: None,
    }])},
    FeatTableEntry { key: "Shield Master", category: FeatCategory::Combat, name: "Shield Master", description: Some("Your mastery of the shield allows you to fight with it without hindrance."), effect: Some(&[FeatEffectBonus { qualifiers: &["COMBAT", "TOHIT.ShieldBash", "var(\\\"ARMOR.SHIELD.EQUIPPED.0.ACBONUS\\\")-var(\\\"ARMOR.SHIELD.EQUIPPED.0.BASEAC\\\")"], bonus_type: Some("Enhancement"), conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["COMBAT", "DAMAGE.ShieldBash", "var(\\\"ARMOR.SHIELD.EQUIPPED.0.ACBONUS\\\")-var(\\\"ARMOR.SHIELD.EQUIPPED.0.BASEAC\\\")"], bonus_type: Some("Enhancement"), conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["VAR", "ShieldBashAttackBonus,ShieldBashDamageBonus", "var(\\\"ARMOR.SHIELD.EQUIPPED.0.ACBONUS\\\")-var(\\\"ARMOR.SHIELD.EQUIPPED.0.BASEAC\\\")"], bonus_type: Some("Enhancement"), conditions: &[], selection: None }])},
    FeatTableEntry { key: "Shield Proficiency", category: FeatCategory::Combat, name: "Shield Proficiency", description: Some("You are trained in how to properly use a shield."), effect: None},
    FeatTableEntry { key: "Shield Slam", category: FeatCategory::Combat, name: "Shield Slam", description: Some("In the right position, your shield can be used to send opponents flying."), effect: None},
    FeatTableEntry { key: "Shot on the Run", category: FeatCategory::Combat, name: "Shot on the Run", description: Some("You can move, fire a ranged weapon, and move again before your foes can react."), effect: None},
    FeatTableEntry { key: "Sickening Critical", category: FeatCategory::Combat, name: "Sickening Critical", description: Some("Your critical hits cause opponents to become sickened."), effect: None},
    FeatTableEntry { key: "Snatch Arrows", category: FeatCategory::Combat, name: "Snatch Arrows", description: Some("Instead of knocking an arrow or ranged attack aside, you can catch it in mid-flight."), effect: None},
    FeatTableEntry { key: "Spellbreaker", category: FeatCategory::Combat, name: "Spellbreaker", description: Some("You can strike at enemy spellcasters who fail to cast defensively when you threaten them."), effect: None},
    FeatTableEntry { key: "Spirited Charge", category: FeatCategory::Combat, name: "Spirited Charge", description: Some("Your mounted charge deals a tremendous amount of damage."), effect: None},
    FeatTableEntry { key: "Spring Attack", category: FeatCategory::Combat, name: "Spring Attack", description: Some("You can deftly move up to a foe, strike, and withdraw before he can react."), effect: None},
    FeatTableEntry { key: "Staggering Critical", category: FeatCategory::Combat, name: "Staggering Critical", description: Some("Your critical hits cause opponents to slow down."), effect: None},
    FeatTableEntry { key: "Stand Still", category: FeatCategory::Combat, name: "Stand Still", description: Some("You can stop foes that try to move past you."), effect: None},
    FeatTableEntry { key: "Step Up", category: FeatCategory::Combat, name: "Step Up", description: Some("You can close the distance when a foe tries to move away."), effect: None},
    FeatTableEntry { key: "Strike Back", category: FeatCategory::Combat, name: "Strike Back", description: Some("You can strike at foes that attack you using their superior reach, by targeting their limbs or weapons as they come at you."), effect: None},
    FeatTableEntry { key: "Stunning Critical", category: FeatCategory::Combat, name: "Stunning Critical", description: Some("Your critical hits cause opponents to become stunned."), effect: None},
    FeatTableEntry { key: "Stunning Fist", category: FeatCategory::Combat, name: "Stunning Fist", description: Some("You know just where to strike to temporarily stun a foe. %1/day (DC %2)|StunningFistAttack|StunningFistDC"), effect: Some(&[FeatEffectBonus {
        qualifiers: &["VAR", "StunningFistDC", "2"],
        bonus_type: None,
        conditions: &[
            EffectCondition {
                negated: false,
                family: "ABILITY",
                items: &[
                    ConditionItem { facet: None, value: "1" },
                    ConditionItem { facet: Some("CATEGORY"), value: "FEAT" },
                    ConditionItem { facet: None, value: "Ability Focus (Stunning Fist)" },
                ],
                alternatives: &[],
            },
        ],
        selection: None,
    }, FeatEffectBonus { qualifiers: &["VAR", "StunningFistDC", "10+(TL/2)+WIS"], bonus_type: None, conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["VAR", "StunningFistAttack", "MonkLVL+floor((TL-MonkLVL)/4)"], bonus_type: Some("NoStack"), conditions: &[], selection: None }])},
    FeatTableEntry { key: "Throw Anything", category: FeatCategory::Combat, name: "Throw Anything", description: Some("You are used to throwing things you have on hand."), effect: Some(&[FeatEffectBonus { qualifiers: &["WEAPONPROF=TYPE.Splash", "TOHIT", "1"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Tiring Critical", category: FeatCategory::Combat, name: "Tiring Critical", description: Some("Your critical hits cause opponents to become fatigued."), effect: None},
    FeatTableEntry { key: "Tower Shield Proficiency", category: FeatCategory::Combat, name: "Tower Shield Proficiency", description: Some("You are trained in how to properly use a tower shield."), effect: None},
    FeatTableEntry { key: "Trample", category: FeatCategory::Combat, name: "Trample", description: Some("While mounted, you can ride down opponents and thrample them under your mount."), effect: None},
    FeatTableEntry { key: "Two-Weapon Defense", category: FeatCategory::Combat, name: "Two-Weapon Defense", description: Some("You are skilled at defending yourself while fighting with two weapons."), effect: Some(&[FeatEffectBonus {
        qualifiers: &["COMBAT", "AC", "TwoWeaponShield"],
        bonus_type: Some("Shield"),
        conditions: &[
            EffectCondition {
                negated: false,
                family: "MULT",
                items: &[
                    ConditionItem { facet: None, value: "1" },
                ],
                alternatives: &[
                    EffectCondition {
                        negated: false,
                        family: "EQUIP",
                        items: &[
                            ConditionItem { facet: None, value: "1" },
                            ConditionItem { facet: Some("TYPE"), value: "Double" },
                        ],
                        alternatives: &[],
                    },
                    EffectCondition {
                        negated: false,
                        family: "MULT",
                        items: &[
                            ConditionItem { facet: None, value: "2" },
                        ],
                        alternatives: &[
                            EffectCondition {
                                negated: false,
                                family: "EQUIPPRIMARY",
                                items: &[
                                    ConditionItem { facet: None, value: "1" },
                                    ConditionItem { facet: Some("TYPE"), value: "Melee" },
                                ],
                                alternatives: &[],
                            },
                            EffectCondition {
                                negated: false,
                                family: "EQUIPSECONDARY",
                                items: &[
                                    ConditionItem { facet: None, value: "1" },
                                    ConditionItem { facet: Some("TYPE"), value: "Melee" },
                                ],
                                alternatives: &[],
                            },
                        ],
                    },
                ],
            },
        ],
        selection: None,
    }, FeatEffectBonus { qualifiers: &["VAR", "TwoWeaponShield", "1"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Two-Weapon Fighting", category: FeatCategory::Combat, name: "Two-Weapon Fighting", description: Some("You can fight with a weapon in each of your hands. You can make one extra attack each round with the secondary weapon."), effect: Some(&[FeatEffectBonus { qualifiers: &["COMBAT", "TOHIT-PRIMARY", "2"], bonus_type: None, conditions: &[], selection: None }, FeatEffectBonus { qualifiers: &["COMBAT", "TOHIT-SECONDARY", "6"], bonus_type: None, conditions: &[], selection: None }])},
    FeatTableEntry { key: "Two-Weapon Rend", category: FeatCategory::Combat, name: "Two-Weapon Rend", description: Some("Striking with both your weapons simultanoeusly, you can use them to deliver devastating wounds."), effect: None},
    FeatTableEntry { key: "Unseat", category: FeatCategory::Combat, name: "Unseat", description: Some("You are skilled at unseating your mounted opponent."), effect: None},
    FeatTableEntry { key: "Vital Strike", category: FeatCategory::Combat, name: "Vital Strike", description: Some("You make a single attack that deals significantly more damage than normal."), effect: None},
    FeatTableEntry { key: "Weapon Finesse", category: FeatCategory::Combat, name: "Weapon Finesse", description: Some("You are trained in using your agility in melee combat, as opposed to brute strength."), effect: Some(&[FeatEffectBonus { qualifiers: &["COMBAT", "TOHIT.Finesseable", "((max(STR,DEX)-STR)+SHIELDACCHECK)"], bonus_type: Some("NotRanged"), conditions: &[], selection: None }])},
    FeatTableEntry { key: "Weapon Focus", category: FeatCategory::Combat, name: "Weapon Focus", description: Some("You are especially good at using your chosen weapon."), effect: Some(&[FeatEffectBonus { qualifiers: &["TOHIT", "WeaponFocusToHit"], bonus_type: None, conditions: &[], selection: Some(EffectSelection::ChosenWeapon) }])},
    FeatTableEntry { key: "Weapon Specialization", category: FeatCategory::Combat, name: "Weapon Specialization", description: Some("You deal extra damage when using your chosen weapon."), effect: Some(&[FeatEffectBonus { qualifiers: &["DAMAGE", "2"], bonus_type: None, conditions: &[], selection: Some(EffectSelection::ChosenWeapon) }])},
    FeatTableEntry { key: "Whirlwind Attack", category: FeatCategory::Combat, name: "Whirlwind Attack", description: Some("You can strike out at every foe within reach."), effect: None},
    FeatTableEntry { key: "Wind Stance", category: FeatCategory::Combat, name: "Wind Stance", description: Some("Your erratic movements make it difficult for enemies to pinpoint your location."), effect: None},
];

