//! Generated from the real PCGen corpus file `cr_feats.lst` (`TYPE:` facet
//! containing `General`). 50 records, transcribed verbatim
//! (`KEY:`/name, `TYPE:`, `DESC:`, `BONUS:`) from the corpus's `###Block:
//! General Feats` section -- see `feats.rs`'s own doc comment for why
//! category is derived from the `TYPE:` facet rather than the corpus's
//! `###Block:` markers, and for the generation method. Not hand-authored --
//! do not hand-edit; regenerate if the corpus changes.

use crate::rules_core::rules_tables::crb::feats::{FeatCategory, FeatEffectBonus, FeatTableEntry};

pub const GENERAL_TABLE: &[FeatTableEntry] = &[
    FeatTableEntry { key: "Acrobatic", category: FeatCategory::General, name: "Acrobatic", description: Some("You are skilled at leaping, jumping, and flying."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Acrobatics", "if(skillinfo(\"TOTALRANK\",\"Acrobatics\")>=10,4,2)"] }, FeatEffectBonus { qualifiers: &["SKILL", "Fly", "if(skillinfo(\"TOTALRANK\",\"Fly\")>=10,4,2)"] }]), prerequisites: None },
    FeatTableEntry { key: "Acrobatic Steps", category: FeatCategory::General, name: "Acrobatic Steps", description: Some("You can easily move over and through obstacles."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "Feat_NimbleMoves_Squares", "15"] }]), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Nimble Moves", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,15],[PREVARGTEQ:FeatDexRequirement,15]"]) },
    FeatTableEntry { key: "Alertness", category: FeatCategory::General, name: "Alertness", description: Some("You often notice things that others might miss."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Perception", "if(skillinfo(\"TOTALRANK\",\"Perception\")>=10,4,2)"] }, FeatEffectBonus { qualifiers: &["SKILL", "Sense Motive", "if(skillinfo(\"TOTALRANK\",\"Sense Motive\")>=10,4,2)"] }]), prerequisites: None },
    FeatTableEntry { key: "Alignment Channel", category: FeatCategory::General, name: "Alignment Channel", description: Some("You can channel your divine energy to harm or heal outsiders that possess your chosen alignment subtype."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Channel Energy"]) },
    FeatTableEntry { key: "Animal Affinity", category: FeatCategory::General, name: "Animal Affinity", description: Some("You are skilled at working with animals and mounts."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Handle Animal", "if(skillinfo(\"TOTALRANK\",\"Handle Animal\")>=10,4,2)"] }, FeatEffectBonus { qualifiers: &["SKILL", "Ride", "if(skillinfo(\"TOTALRANK\",\"Ride\")>=10,4,2)"] }]), prerequisites: None },
    FeatTableEntry { key: "Athletic", category: FeatCategory::General, name: "Athletic", description: Some("You possess inherent physical prowess."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Climb", "if(skillinfo(\"TOTALRANK\",\"Climb\")>=10,4,2)"] }, FeatEffectBonus { qualifiers: &["SKILL", "Swim", "if(skillinfo(\"TOTALRANK\",\"Swim\")>=10,4,2)"] }]), prerequisites: None },
    FeatTableEntry { key: "Augment Summoning", category: FeatCategory::General, name: "Augment Summoning", description: Some("Your summoned creatures are more powerful and robust than most."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Spell Focus (Conjuration)"]) },
    FeatTableEntry { key: "Combat Casting", category: FeatCategory::General, name: "Combat Casting", description: Some("You are adept at spellcasting when threatened or distracted."), effect: None, prerequisites: None },
    FeatTableEntry { key: "Command Undead", category: FeatCategory::General, name: "Command Undead", description: Some("Using foul powers of necromancy, you can command undead creatures, making them into your servants."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Channel Negative Energy"]) },
    FeatTableEntry { key: "Deceitful", category: FeatCategory::General, name: "Deceitful", description: Some("You are skilled at deceiving others, both with the spoken word ans with physical disguises."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Bluff", "if(skillinfo(\"TOTALRANK\",\"Bluff\")>=10,4,2)"] }, FeatEffectBonus { qualifiers: &["SKILL", "Disguise", "if(skillinfo(\"TOTALRANK\",\"Disguise\")>=10,4,2)"] }]), prerequisites: None },
    FeatTableEntry { key: "Deft Hands", category: FeatCategory::General, name: "Deft Hands", description: Some("You have exceptional manual dexterity."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Disable Device", "if(skillinfo(\"TOTALRANK\",\"Disable Device\")>=10,4,2)"] }, FeatEffectBonus { qualifiers: &["SKILL", "Sleight of Hand", "if(skillinfo(\"TOTALRANK\",\"Sleight of Hand\")>=10,4,2)"] }]), prerequisites: None },
    FeatTableEntry { key: "Diehard", category: FeatCategory::General, name: "Diehard", description: Some("You are especially hard to kill. Not only do your wounds automatically stabilize when grievously injured, but you can remain conscious and continue to act even at death's door."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Endurance"]) },
    FeatTableEntry { key: "Elemental Channel", category: FeatCategory::General, name: "Elemental Channel", description: Some("You can channel your divine energy to harm or heal outsiders that possess your chosen elemental subtype."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Channel Energy"]) },
    FeatTableEntry { key: "Endurance", category: FeatCategory::General, name: "Endurance", description: Some("Harsh conditions or long exertions do not easily tire you."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "Feat_Endurance_SaveBonus", "4", "TYPE=Base"] }]), prerequisites: None },
    FeatTableEntry { key: "Eschew Materials", category: FeatCategory::General, name: "Eschew Materials", description: Some("You can cast many spells without needing to utilize minor material components."), effect: None, prerequisites: None },
    FeatTableEntry { key: "Extra Channel", category: FeatCategory::General, name: "Extra Channel", description: Some("You can channel divine energy more often."), effect: Some(&[FeatEffectBonus { qualifiers: &["ABILITYPOOL", "Extra Channel", "1"] }]), prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Channel Positive Energy,TYPE.Channel Negative Energy"]) },
    FeatTableEntry { key: "Extra Ki", category: FeatCategory::General, name: "Extra Ki", description: Some("You can use your ki pool more times per day than most."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "KiPoints", "2"] }]), prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Ki Pool"]) },
    FeatTableEntry { key: "Extra Lay On Hands", category: FeatCategory::General, name: "Extra Lay On Hands", description: Some("You can use your lay on hands ability more often."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "LayOnHandsTimes", "2"] }]), prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Lay on Hands"]) },
    FeatTableEntry { key: "Extra Mercy", category: FeatCategory::General, name: "Extra Mercy", description: Some("Your lay on hands ability adds an additional mercy."), effect: Some(&[FeatEffectBonus { qualifiers: &["ABILITYPOOL", "Mercy", "1"] }]), prerequisites: Some(&["PREABILITY:2,CATEGORY=Special Ability,TYPE.Lay on Hands,TYPE.Mercy"]) },
    FeatTableEntry { key: "Extra Performance", category: FeatCategory::General, name: "Extra Performance", description: Some("You can use your bardic performance ability more often than normal"), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "BardicPerformanceDuration", "6"] }]), prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Bardic Performance"]) },
    FeatTableEntry { key: "Extra Rage", category: FeatCategory::General, name: "Extra Rage", description: Some("You can use your rage ability more than narmal."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "RageDuration", "6"] }]), prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Rage"]) },
    FeatTableEntry { key: "Fleet", category: FeatCategory::General, name: "Fleet", description: Some("You are faster than most."), effect: Some(&[FeatEffectBonus { qualifiers: &["MOVEADD", "TYPE.Walk", "5", "PREVARLT:ENCUMBERANCE,1,var(\"COUNT[EQTYPE.ARMOR.EQUIPPED.IS.MEDIUM]\"),1,var(\"COUNT[EQTYPE.ARMOR.EQUIPPED.IS.HEAVY]\"),1"] }]), prerequisites: None },
    FeatTableEntry { key: "Great Fortitude", category: FeatCategory::General, name: "Great Fortitude", description: Some("You are resistant to poisons, diseases, and other deadly maladies."), effect: Some(&[FeatEffectBonus { qualifiers: &["SAVE", "Fortitude", "2"] }]), prerequisites: None },
    FeatTableEntry { key: "Greater Spell Focus", category: FeatCategory::General, name: "Greater Spell Focus", description: Some("Any spells you cast from your chosen school of magic are very hard to resist."), effect: Some(&[FeatEffectBonus { qualifiers: &["DC", "SCHOOL.%LIST", "2", "TYPE=SpellFocus"] }]), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Spell Focus"]) },
    FeatTableEntry { key: "Greater Spell Penetration", category: FeatCategory::General, name: "Greater Spell Penetration", description: Some("Your spells break through spell resistance much more easily than most."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Spell Penetration"]) },
    FeatTableEntry { key: "Improved Channel", category: FeatCategory::General, name: "Improved Channel", description: Some("Your channeled energy is harder to resist."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "ClericChannelPositiveEnergyDC", "2"] }, FeatEffectBonus { qualifiers: &["VAR", "PaladinChannelPositiveEnergyDC", "2"] }, FeatEffectBonus { qualifiers: &["VAR", "ClericChannelNegativeEnergyDC", "2"] }, FeatEffectBonus { qualifiers: &["VAR", "PowerOverUndeadCommandDC", "2"] }, FeatEffectBonus { qualifiers: &["VAR", "PowerOverUndeadTurnDC", "2"] }]), prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Channel Positive Energy,TYPE.Channel Negative Energy"]) },
    FeatTableEntry { key: "Improved Counterspell", category: FeatCategory::General, name: "Improved Counterspell", description: Some("You are skilled at countering the spells of others using similar spells."), effect: None, prerequisites: None },
    FeatTableEntry { key: "Improved Familiar", category: FeatCategory::General, name: "Improved Familiar", description: Some("This feat allows you to acquire a powerful familiar, but only when they could normally acquire a new familiar."), effect: None, prerequisites: None },
    FeatTableEntry { key: "Improved Great Fortitude", category: FeatCategory::General, name: "Improved Great Fortitude", description: Some("You can draw upon an inner reserve to resist diseases, poisons, and other grievous harm."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Great Fortitude"]) },
    FeatTableEntry { key: "Improved Iron Will", category: FeatCategory::General, name: "Improved Iron Will", description: Some("Your clarity of thought allows you to resist mental attacks."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Iron Will"]) },
    FeatTableEntry { key: "Improved Lightning Reflexes", category: FeatCategory::General, name: "Improved Lightning Reflexes", description: Some("You have a knack for avoiding danger all around you."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Lightning Reflexes"]) },
    FeatTableEntry { key: "Iron Will", category: FeatCategory::General, name: "Iron Will", description: Some("You are more resistant to mental effects."), effect: Some(&[FeatEffectBonus { qualifiers: &["SAVE", "Will", "2"] }]), prerequisites: None },
    FeatTableEntry { key: "Leadership", category: FeatCategory::General, name: "Leadership", description: Some("You attract followers to your cause and a companion to join you on your adventure."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "LeadershipMaxCohortLvl", "min((TL-2),(((LeadershipScore+6)*7)/10)-4)"] }, FeatEffectBonus { qualifiers: &["VAR", "LeadershipScore", "(TL+LeadershipAbilityScoreMod)"] }, FeatEffectBonus { qualifiers: &["VAR", "LeadershipAbilityScoreMod", "CHA"] }]), prerequisites: Some(&["PRELEVEL:MIN=7"]) },
    FeatTableEntry { key: "Lightning Reflexes", category: FeatCategory::General, name: "Lightning Reflexes", description: Some("You have faster reflexes than normal."), effect: Some(&[FeatEffectBonus { qualifiers: &["SAVE", "Reflex", "2"] }]), prerequisites: None },
    FeatTableEntry { key: "Magical Aptitude", category: FeatCategory::General, name: "Magical Aptitude", description: Some("You are skilled at spellcasting and using magic items."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Spellcraft", "if(skillinfo(\"TOTALRANK\",\"Spellcraft\")>=10,4,2)"] }, FeatEffectBonus { qualifiers: &["SKILL", "Use Magic Device", "if(skillinfo(\"TOTALRANK\",\"Use Magic Device\")>=10,4,2)"] }]), prerequisites: None },
    FeatTableEntry { key: "Master Craftsman", category: FeatCategory::General, name: "Master Craftsman", description: Some("Your superior crafting skills allow you to create simple magic items."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "LIST", "2"] }, FeatEffectBonus { qualifiers: &["VAR", "MasterCraftsmanRanks", "var(\"SKILLRANK=%LIST\")"] }]), prerequisites: Some(&["PRESKILL:1,TYPE.Craft=5,TYPE.Profession=5"]) },
    FeatTableEntry { key: "Natural Spell", category: FeatCategory::General, name: "Natural Spell", description: Some("You can cast spells even while in a form that cannot normally cast spells."), effect: None, prerequisites: Some(&["PREMULT:1,[PREVARGTEQ:WildShapeProgression,1],[PREVARGTEQ:ShamanWildShapeProgression,1]", "PREVARGTEQ:PreStatScore_WIS,13"]) },
    FeatTableEntry { key: "Nimble Moves", category: FeatCategory::General, name: "Nimble Moves", description: Some("You can move across a single obstacle with ease."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "Feat_NimbleMoves_Squares", "5"] }]), prerequisites: Some(&["PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,13],[PREVARGTEQ:FeatDexRequirement,13]"]) },
    FeatTableEntry { key: "Persuasive", category: FeatCategory::General, name: "Persuasive", description: Some("You are skilled at swaying attitudes and intimidating others into your way of thinking."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Diplomacy", "if(skillinfo(\"TOTALRANK\",\"Diplomacy\")>=10,4,2)"] }, FeatEffectBonus { qualifiers: &["SKILL", "Intimidate", "if(skillinfo(\"TOTALRANK\",\"Intimidate\")>=10,4,2)"] }]), prerequisites: None },
    FeatTableEntry { key: "Run", category: FeatCategory::General, name: "Run", description: Some("You are swift of foot."), effect: None, prerequisites: None },
    FeatTableEntry { key: "Selective Channeling", category: FeatCategory::General, name: "Selective Channeling", description: Some("You can choose whom to affect when you channel energy."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Channel Positive Energy,TYPE.Channel Negative Energy", "PREVARGTEQ:PreStatScore_CHA,13"]) },
    FeatTableEntry { key: "Self-Sufficient", category: FeatCategory::General, name: "Self-Sufficient", description: Some("You know how to get along in the wild and how to effectively treat wounds.:"), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Heal", "if(skillinfo(\"TOTALRANK\",\"Heal\")>=10,4,2)"] }, FeatEffectBonus { qualifiers: &["SKILL", "Survival", "if(skillinfo(\"TOTALRANK\",\"Survival\")>=10,4,2)"] }]), prerequisites: None },
    FeatTableEntry { key: "Simple Weapon Proficiency", category: FeatCategory::General, name: "Simple Weapon Proficiency", description: Some("You are trained in the use of basic weapons."), effect: None, prerequisites: None },
    FeatTableEntry { key: "Skill Focus", category: FeatCategory::General, name: "Skill Focus", description: Some("You are particularly adept at your chosen skill."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "%LIST", "3", "TYPE=SkillFocus"] }]), prerequisites: None },
    FeatTableEntry { key: "Spell Focus", category: FeatCategory::General, name: "Spell Focus", description: Some("Any spells you cast of your chosen school of magic are more difficult to resist."), effect: Some(&[FeatEffectBonus { qualifiers: &["DC", "SCHOOL.%LIST", "1", "TYPE=SpellFocus"] }]), prerequisites: None },
    FeatTableEntry { key: "Spell Mastery", category: FeatCategory::General, name: "Spell Mastery", description: Some("You have mastered a small handfull of spells, and can prepare these spells without referencing your spellbooks at all."), effect: None, prerequisites: Some(&["PREVARGTEQ:SpellMasteryQualify,1"]) },
    FeatTableEntry { key: "Spell Penetration", category: FeatCategory::General, name: "Spell Penetration", description: Some("Your spells break through spell resistance more easily than most."), effect: None, prerequisites: None },
    FeatTableEntry { key: "Stealthy", category: FeatCategory::General, name: "Stealthy", description: Some("You are good at avoiding attention and slipping out of bonds."), effect: Some(&[FeatEffectBonus { qualifiers: &["SKILL", "Escape Artist", "if(skillinfo(\"TOTALRANK\",\"Escape Artist\")>=10,4,2)"] }, FeatEffectBonus { qualifiers: &["SKILL", "Stealth", "if(skillinfo(\"TOTALRANK\",\"Stealth\")>=10,4,2)"] }]), prerequisites: None },
    FeatTableEntry { key: "Toughness", category: FeatCategory::General, name: "Toughness", description: Some("You have enhanced physical stamina."), effect: Some(&[FeatEffectBonus { qualifiers: &["HP", "CURRENTMAX", "max(3,TL)", "PRERULE:1,DAMAGE_HP"] }]), prerequisites: None },
    FeatTableEntry { key: "Turn Undead", category: FeatCategory::General, name: "Turn Undead", description: Some("Calling upon higher powers, you cause undead to flee from the might of your unleashed divine energy."), effect: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,TYPE.Channel Positive Energy"]) },
];

