//! Package-backed mirror of the compiled `rules_tables` module `acg::bloodrager_spell_list` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

pub static BLOODRAGER_SPELL_LIST: crate::rules_core::rules_catalog::Table<(&str, u8)> =
    crate::rules_core::rules_catalog::Table::new("acg/bloodrager_spell_list/BLOODRAGER_SPELL_LIST");
pub fn bloodrager_spell_level(spell_key: &str) -> Option<u8> {
    BLOODRAGER_SPELL_LIST
        .iter()
        .find(|(key, _)| *key == spell_key)
        .map(|(_, level)| *level)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_list_matches_the_verified_corpus_extraction() {
        assert_eq!(BLOODRAGER_SPELL_LIST.len(), 200, "200 real Bloodrager spell records");
        for level in 1..=4u8 {
            let count = BLOODRAGER_SPELL_LIST.iter().filter(|(_, l)| *l == level).count();
            let expected = match level {
                1 => 55,
                2 => 49,
                3 => 54,
                _ => 42,
            };
            assert_eq!(count, expected, "spell level {level} count");
        }
    }

    #[test]
    fn no_spell_exceeds_bloodragers_fourth_level_ceiling() {
        for (name, level) in &*BLOODRAGER_SPELL_LIST {
            assert!(
                (1..=4).contains(level),
                "{name} at level {level}: Bloodrager tops out at 4th-level spells"
            );
        }
    }

    #[test]
    fn the_list_has_no_duplicate_entries() {
        let mut names: Vec<&str> = BLOODRAGER_SPELL_LIST.iter().map(|(n, _)| *n).collect();
        names.sort_unstable();
        let before = names.len();
        names.dedup();
        assert_eq!(names.len(), before, "no spell may appear twice");
    }

    #[test]
    fn lookup_resolves_a_real_entry_and_rejects_an_off_list_one() {
        assert_eq!(bloodrager_spell_level("Shield"), Some(1));
        assert_eq!(bloodrager_spell_level("Wish"), None, "9th-level spells are off this list");
        assert_eq!(bloodrager_spell_level(""), None);
    }
}
