//! Package-backed mirror of the compiled `rules_tables` module `acg::equipment_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

use crate::rules_core::rules_catalog::RuleSetId;
use crate::rules_core::rules_catalog::acg::equipment_data;
pub use rt::acg::equipment_tables::EquipmentCategory;
pub use rt::acg::equipment_tables::EquipmentFieldCoverage;
pub use rt::acg::equipment_tables::EquipmentTableEntry;
pub fn field_coverage_report() -> EquipmentFieldCoverage {
    let table = equipment_tables();
    EquipmentFieldCoverage {
        total_records: table.len() as u32,
        records_expected: 221 + 48,
        has_cost: table.iter().filter(|entry| entry.cost_gp.is_some()).count() as u32,
        has_weight: table
            .iter()
            .filter(|entry| entry.weight_lbs.is_some())
            .count() as u32,
        has_description: table
            .iter()
            .filter(|entry| entry.description.is_some())
            .count() as u32,
    }
}
pub fn equipment_tables() -> &'static [EquipmentTableEntry] {
    static TABLES: std::sync::OnceLock<Vec<EquipmentTableEntry>> = std::sync::OnceLock::new();
    TABLES.get_or_init(|| {
        let mut all = Vec::with_capacity(
            equipment_data::general::GENERAL_TABLE.len()
                + equipment_data::arms_armor::ARMS_ARMOR_TABLE.len()
                + equipment_data::magic_items::MAGIC_ITEMS_TABLE.len()
                + equipment_data::equipmods::EQUIPMODS_TABLE.len(),
        );
        all.extend_from_slice(&*equipment_data::general::GENERAL_TABLE);
        all.extend_from_slice(&*equipment_data::arms_armor::ARMS_ARMOR_TABLE);
        all.extend_from_slice(&*equipment_data::magic_items::MAGIC_ITEMS_TABLE);
        all.extend_from_slice(&*equipment_data::equipmods::EQUIPMODS_TABLE);
        all
    })
}
pub fn equipment_resolve(key: &str, rule_set: RuleSetId) -> Option<&'static EquipmentTableEntry> {
    if rule_set != RuleSetId::Acg {
        return None;
    }
    equipment_tables().iter().find(|entry| entry.key == key)
}
