//! Package-backed mirror of the compiled `rules_tables` module `acg::feats` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

use super::super::crb::feats::FeatTableEntry;
pub fn feat_tables() -> &'static [FeatTableEntry] {
    static TABLES: std::sync::OnceLock<Vec<FeatTableEntry>> = std::sync::OnceLock::new();
    TABLES.get_or_init(|| {
        let mut all = Vec::with_capacity(
            super::feat_data::general::GENERAL_TABLE.len()
                + super::feat_data::combat::COMBAT_TABLE.len()
                + super::feat_data::teamwork::TEAMWORK_TABLE.len()
                + super::feat_data::panache::PANACHE_TABLE.len(),
        );
        all.extend_from_slice(&*super::feat_data::general::GENERAL_TABLE);
        all.extend_from_slice(&*super::feat_data::combat::COMBAT_TABLE);
        all.extend_from_slice(&*super::feat_data::teamwork::TEAMWORK_TABLE);
        all.extend_from_slice(&*super::feat_data::panache::PANACHE_TABLE);
        all
    })
}
