//! monster_codex companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py monster_codex`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `mc_races_companion.lst` -- 8 companion creature rows
//!   * `mc_abilities_companion.lst` -- 7 companion ability rows

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, NaturalAttackDamageBonus, SkillAbilityDiffBonus, Speed, StatAdjustment};

/// Every monster_codex companion creature (8 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Companion (Cave Salamander)",
        name: "Companion (Cave Salamander)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(2),
        source_page: Some("p.128"),
        ability_keys: &["Companion Advancement ~ Cave Salamander"],
        external_ability_refs: &[],
        source_file: "mc_races_companion.lst",
        source_line: 5,
    },
    CompanionRecord {
        key: "Companion (Gorthek)",
        name: "Companion (Gorthek)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Gore", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(4),
        source_page: Some("p.172"),
        ability_keys: &["Companion Advancement ~ Gorthek"],
        external_ability_refs: &[],
        source_file: "mc_races_companion.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Companion (Python (Riding))",
        name: "Companion (Python (Riding))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.128"),
        ability_keys: &["Companion Advancement ~ Python (Riding)"],
        external_ability_refs: &["Can't Be Tripped"],
        source_file: "mc_races_companion.lst",
        source_line: 7,
    },
    CompanionRecord {
        key: "Companion (Rat (Riding))",
        name: "Companion (Rat (Riding))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.117"),
        ability_keys: &["Companion Advancement ~ Rat (Riding)"],
        external_ability_refs: &["Scent"],
        source_file: "mc_races_companion.lst",
        source_line: 8,
    },
    CompanionRecord {
        key: "Companion (Yzobu)",
        name: "Companion (Yzobu)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Gore", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.124"),
        ability_keys: &["Companion Advancement ~ Yzobu", "Yzobu ~ Stampede"],
        external_ability_refs: &["Scent"],
        source_file: "mc_races_companion.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Familiar (Seru)",
        name: "Familiar (Seru)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Magical Beast"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Magical Beast:1"),
        type_segments: &["Companion", "Familiar", "Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }, NaturalAttack { name: "Venom", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.208"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "mc_races_companion.lst",
        source_line: 11,
    },
    CompanionRecord {
        key: "Familiar (Sootwing Bat)",
        name: "Familiar (Sootwing Bat)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Undead"),
        race_subtype: Some("Familiar|Augmented Undead|FamiliarBase"),
        monster_class: Some("Undead:1"),
        type_segments: &["Companion", "Familiar", "Undead"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -6 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(1),
        source_page: Some("p.88"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "mc_races_companion.lst",
        source_line: 12,
    },
    CompanionRecord {
        key: "Companion (Giant Vulture)",
        name: "Companion (Giant Vulture)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(2),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Giant Vulture"],
        external_ability_refs: &[],
        source_file: "mc_races_companion.lst",
        source_line: 15,
    },
];

/// Every monster_codex companion ability record (7 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Cave Salamander",
        name: "Companion Advancement (Cave Salamander)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Cave Salamander)"],
        cross_book_owners: &[],
        source_file: "mc_abilities_companion.lst",
        source_line: 5,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Gorthek",
        name: "Companion Advancement (Gorthek)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Gorthek)"],
        cross_book_owners: &[],
        source_file: "mc_abilities_companion.lst",
        source_line: 6,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Python (Riding)",
        name: "Companion Advancement (Python (Riding))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Python (Riding))"],
        cross_book_owners: &[],
        source_file: "mc_abilities_companion.lst",
        source_line: 7,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Yzobu",
        name: "Companion Advancement (Yzobu)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Yzobu)"],
        cross_book_owners: &[],
        source_file: "mc_abilities_companion.lst",
        source_line: 8,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Rat (Riding)",
        name: "Companion Advancement (Rat (Riding))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }],
        source_page: None,
        owners: &["Companion (Rat (Riding))"],
        cross_book_owners: &[],
        source_file: "mc_abilities_companion.lst",
        source_line: 9,
    },
    CompanionAbilityRecord {
        key: "Yzobu ~ Stampede",
        name: "Stampede",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("A stampede occurs if three or more creatures with stampede make a trample attack while remaining adjacent to each other. While stampeding, the creatures can trample foes of their size or smaller, and the trample's save DC increases by +2."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Yzobu)"],
        cross_book_owners: &[],
        source_file: "mc_abilities_companion.lst",
        source_line: 11,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Giant Vulture",
        name: "7th-Level Advancement ~ Companion (Giant Vulture)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Giant Vulture)"],
        cross_book_owners: &[],
        source_file: "mc_abilities_companion.lst",
        source_line: 14,
    },
];
