//! Package-backed mirror of the compiled `rules_tables` module `ultimate_wilderness::archetype_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

use super::super::archetype_swap::{ArchetypeGrant, ArchetypeSwapEntry};
pub fn archetype_swap_tables() -> &'static [ArchetypeSwapEntry] {
    crate::rules_core::rules_catalog::rows::<ArchetypeSwapEntry>(
        "ultimate_wilderness/archetype_tables/archetype_swap_tables",
    )
}
