//! inner_sea_gods monster + monster-ability tables, transcribed verbatim
//! from the book's own PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_monster_tables.py inner_sea_gods`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst` (which counts `.MOD`/`.COPY` overlays the
//! inventory correctly excludes).
//!
//! Sources, with the line each record was read from carried per row:
//!   * `isg_races.lst` -- 36 monster rows
//!   * `isg_races_b4.lst` -- 3 monster rows
//!   * `isg_abilities_races.lst` -- 77 monster-ability rows
//!
//! 0 monster row(s) and 5 ability row(s) of this
//! book are Product Identity and are NOT transcribed -- either because the corpus
//! row DECLARES it (`NAMEISPI:YES`, PCGen's own per-record marker) or because an
//! emitted value carries a `pi_screening::PI_BLACKLIST_TERMS` term. Both land in
//! the name or key, which is the one field redaction cannot touch. Reclassifying
//! is `docs/governance/ogl-pi-blacklist.md` §3's per-book override, an operator
//! decision, not a transcriber's:
//!   * `isg_abilities_races.lst:43` (ability row, 1 PI_BLACKLIST_TERMS hit(s) in emitted values)
//!   * `isg_abilities_races.lst:44` (ability row, 1 PI_BLACKLIST_TERMS hit(s) in emitted values)
//!   * `isg_abilities_races.lst:45` (ability row, 1 PI_BLACKLIST_TERMS hit(s) in emitted values)
//!   * `isg_abilities_races.lst:146` (ability row, 1 PI_BLACKLIST_TERMS hit(s) in emitted values)
//!   * `isg_abilities_races.lst:155` (ability row, 1 PI_BLACKLIST_TERMS hit(s) in emitted values)
//!
//! 79 further ability row(s) in this book are ORPHANS -- no monster
//! row here claims them, so they are deliberately NOT transcribed (a record
//! with no owner loads and is never shown). `not-ingested` is their honest status
//! in the work inventory, and the round's receipt records them by key:
//!   * `isg_abilities_races_b4.lst:14`
//!   * `isg_abilities_races_b4.lst:15`
//!   * `isg_abilities_races_b4.lst:16`
//!   * `isg_abilities_races_b4.lst:17`
//!   * `isg_abilities_races_b4.lst:19`
//!   * `isg_abilities_races_b4.lst:20`
//!   * `isg_abilities_races_b4.lst:21`
//!   * `isg_abilities_races_b4.lst:24`
//!   * `isg_abilities_races_b4.lst:25`
//!   * `isg_abilities_races_b4.lst:26`
//!   * `isg_abilities_races_b4.lst:27`
//!   * `isg_abilities_races_b4.lst:28`
//!   * `isg_abilities_races_b4.lst:29`
//!   * `isg_abilities_races_b4.lst:32`
//!   * `isg_abilities_races_b4.lst:33`
//!   * `isg_abilities_races_b4.lst:34`
//!   * `isg_abilities_races.lst:38`
//!   * `isg_abilities_races.lst:39`
//!   * `isg_abilities_races.lst:103`
//!   * `isg_abilities_races.lst:104`
//!   * `isg_abilities_races.lst:105`
//!   * `isg_abilities_races.lst:108`
//!   * `isg_abilities_races.lst:109`
//!   * `isg_abilities_races.lst:110`
//!   * `isg_abilities_races.lst:111`
//!   * `isg_abilities_races.lst:112`
//!   * `isg_abilities_races.lst:144`
//!   * `isg_abilities_races.lst:145`
//!   * `isg_abilities_races.lst:147`
//!   * `isg_abilities_races.lst:148`
//!   * `isg_abilities_races.lst:149`
//!   * `isg_abilities_races.lst:150`
//!   * `isg_abilities_races.lst:154`
//!   * `isg_abilities_races.lst:156`
//!   * `isg_abilities_races.lst:157`
//!   * `isg_abilities_races.lst:158`
//!   * `isg_abilities_races.lst:159`
//!   * `isg_abilities_races.lst:160`
//!   * `isg_abilities_races.lst:161`
//!   * `isg_abilities_races.lst:165`
//!   * `isg_abilities_races.lst:186`
//!   * `isg_abilities_races.lst:187`
//!   * `isg_abilities_races.lst:188`
//!   * `isg_abilities_races.lst:206`
//!   * `isg_abilities_races.lst:207`
//!   * `isg_abilities_races.lst:208`
//!   * `isg_abilities_races.lst:221`
//!   * `isg_abilities_races.lst:222`
//!   * `isg_abilities_races.lst:223`
//!   * `isg_abilities_races.lst:224`
//!   * `isg_abilities_races.lst:225`
//!   * `isg_abilities_races.lst:235`
//!   * `isg_abilities_races.lst:236`
//!   * `isg_abilities_races.lst:237`
//!   * `isg_abilities_races.lst:240`
//!   * `isg_abilities_races.lst:241`
//!   * `isg_abilities_races.lst:242`
//!   * `isg_abilities_races.lst:243`
//!   * `isg_abilities_races.lst:244`
//!   * `isg_abilities_races.lst:252`
//!   * `isg_abilities_races.lst:253`
//!   * `isg_abilities_races.lst:254`
//!   * `isg_abilities_races.lst:255`
//!   * `isg_abilities_races.lst:256`
//!   * `isg_abilities_races.lst:257`
//!   * `isg_abilities_races.lst:258`
//!   * `isg_abilities_races.lst:268`
//!   * `isg_abilities_races.lst:269`
//!   * `isg_abilities_races.lst:270`
//!   * `isg_abilities_races.lst:271`
//!   * `isg_abilities_races.lst:293`
//!   * `isg_abilities_races.lst:294`
//!   * `isg_abilities_races.lst:295`
//!   * `isg_abilities_races.lst:296`
//!   * `isg_abilities_races.lst:297`
//!   * `isg_abilities_races.lst:300`
//!   * `isg_abilities_races.lst:301`
//!   * `isg_abilities_races.lst:302`
//!   * `isg_abilities_races.lst:303`

use crate::rules_core::rules_tables::monster_chassis::{MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterStatBlock, NaturalAttack, Speed};

/// Every inner_sea_gods monster stat block (39 rows).
pub(super) static MONSTERS: &[MonsterStatBlock] = &[
    MonsterStatBlock {
        key: "Lawgiver",
        name: "Lawgiver",
        size: Some("G"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Fly", feet: 60 }],
        race_type: Some("Construct"),
        race_subtype: Some("Extraplanar|Herald|Lawful"),
        challenge_rating: Some("15"),
        monster_class: Some("Construct:18"),
        source_page: Some("p.276"),
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: Some("2d6") }],
        ability_keys: &["Lawgiver ~ Immunity to Rust", "Lawgiver ~ Freeze", "Lawgiver ~ Change Shape"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 6,
    },
    MonsterStatBlock {
        key: "The First Blade",
        name: "The First Blade",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Extraplanar|Herald"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Ref):18"),
        source_page: Some("p.288"),
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: Some("2d10") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races_b4.lst",
        source_line: 6,
    },
    MonsterStatBlock {
        key: "Orsheval",
        name: "Orsheval",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Lawful"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):5"),
        source_page: Some("p.277"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }, NaturalAttack { name: "Hoof", damage_dice: Some("1d4") }],
        ability_keys: &["Orsheval ~ Electric Hooves", "Orsheval ~ Glittering Radiance"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 7,
    },
    MonsterStatBlock {
        key: "Basileus",
        name: "Basileus",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 60 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Devil|Evil|Extraplanar|Herald|Lawful"),
        challenge_rating: Some("16"),
        monster_class: Some("Outsider (Ref/Will):16"),
        source_page: Some("p.278"),
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: Some("1d8") }, NaturalAttack { name: "Touch", damage_dice: Some("1d8") }],
        ability_keys: &["Basileus ~ Gaze", "Basileus ~ Terror Shape", "Basileus ~ Veil of Forms"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 10,
    },
    MonsterStatBlock {
        key: "Steward of the Skein",
        name: "Steward of the Skein",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }, Speed { mode: "Fly", feet: 150 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Herald|Psychopomp|Shapechanger"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Ref/Will):19"),
        source_page: Some("p.302"),
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: Some("2d10") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races_b4.lst",
        source_line: 10,
    },
    MonsterStatBlock {
        key: "Devil (Accomplice)",
        name: "Devil (Accomplice)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 20 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Devil|Evil|Extraplanar|Lawful|Shapechanger"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):6"),
        source_page: Some("p.279"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 11,
    },
    MonsterStatBlock {
        key: "Psychopomp (Ahmuuth)",
        name: "Psychopomp (Ahmuuth)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Psychopomp"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):6"),
        source_page: Some("p.303"),
        natural_attacks: &[],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races_b4.lst",
        source_line: 11,
    },
    MonsterStatBlock {
        key: "The Menotherian",
        name: "The Menotherian",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 50 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Extraplanar|Herald|Shapechanger"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Ref):15"),
        source_page: Some("p.280"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d8") }, NaturalAttack { name: "Claw", damage_dice: Some("1d6") }, NaturalAttack { name: "Sting", damage_dice: Some("2d8") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 14,
    },
    MonsterStatBlock {
        key: "Vendenopterix",
        name: "Vendenopterix",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 50 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Extraplanar|Shapechanger"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Ref/Will):6"),
        source_page: Some("p.281"),
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: Some("1d6") }],
        ability_keys: &["Vendenopterix ~ Ability Drain", "Vendenopterix ~ Poison", "Vendenopterix ~ Swift Tracker", "Vendenopterix ~ Change Shape", "Vendenopterix ~ Enchantment Resistance"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 15,
    },
    MonsterStatBlock {
        key: "Thais",
        name: "Thais",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 50 }, Speed { mode: "Fly", feet: 80 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Extraplanar|Good|Herald|Shapechanger"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Ref):17"),
        source_page: Some("p.282"),
        natural_attacks: &[],
        ability_keys: &["Thais ~ Armor of Valor", "Thais ~ Aura of Bravery", "Thais ~ Luck Domain", "Thais ~ Penetrating Gaze", "Thais ~ Change Shape"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 18,
    },
    MonsterStatBlock {
        key: "Ataxian",
        name: "Ataxian",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 40 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Extraplanar|Good"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):4"),
        source_page: Some("p.283"),
        natural_attacks: &[NaturalAttack { name: "Ray", damage_dice: Some("1d6") }, NaturalAttack { name: "Slam", damage_dice: Some("1d2") }],
        ability_keys: &["Ataxian ~ Possession", "Ataxian ~ Staggered", "Ataxian ~ Staggering Drunk", "Ataxian ~ Ray"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 19,
    },
    MonsterStatBlock {
        key: "Night Monarch",
        name: "Night Monarch",
        size: Some("H"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 120 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Extraplanar|Good|Herald"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Will):18"),
        source_page: Some("p.284"),
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: Some("2d6") }, NaturalAttack { name: "Wing", damage_dice: Some("2d6") }],
        ability_keys: &["Night Monarch ~ No Breath", "Night Monarch ~ Immunity to Cold", "Night Monarch ~ Breath Weapon", "Night Monarch ~ Poison Flesh", "Night Monarch ~ Dream Dust", "Night Monarch ~ Languages"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 22,
    },
    MonsterStatBlock {
        key: "Azata (Thyrlien)",
        name: "Azata (Thyrlien)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 40 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Azata|Chaotic|Extraplanar|Good|Shapechanger"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Ref/Will):6"),
        source_page: Some("p.285"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }, NaturalAttack { name: "Wing", damage_dice: Some("1d4") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 23,
    },
    MonsterStatBlock {
        key: "The Grim White Stag",
        name: "The Grim White Stag",
        size: Some("C"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Good|Lawful"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Ref):18"),
        source_page: Some("p.286"),
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("4d6") }, NaturalAttack { name: "Hoof", damage_dice: Some("2d8") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 27,
    },
    MonsterStatBlock {
        key: "Archon (Stag)",
        name: "Archon (Stag)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Archon|Extraplanar|Good|Lawful|Shapechanger"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):6"),
        source_page: Some("p.287"),
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("1d6") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 28,
    },
    MonsterStatBlock {
        key: "Zentragt",
        name: "Zentragt",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Extraplanar"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):6"),
        source_page: Some("p.289"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }, NaturalAttack { name: "Claw", damage_dice: Some("1d6") }],
        ability_keys: &["Zentragt ~ Adamantine Attacks", "Zentragt ~ Eat Metal"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 32,
    },
    MonsterStatBlock {
        key: "Personification of Fury",
        name: "Personification of Fury",
        size: Some("H"),
        speeds: &[Speed { mode: "Fly", feet: 100 }, Speed { mode: "Swim", feet: 90 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Air|Elemental|Extraplanar|Herald|Water"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Ref):17"),
        source_page: Some("p.290"),
        natural_attacks: &[NaturalAttack { name: "Ray", damage_dice: Some("2d6") }, NaturalAttack { name: "Slam", damage_dice: Some("2d10") }],
        ability_keys: &["Personification of Fury ~ Water Mastery", "Personification of Fury ~ Change Shape", "Personification of Fury ~ Energy Ray"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 35,
    },
    MonsterStatBlock {
        key: "Xocothian",
        name: "Xocothian",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 90 }, Speed { mode: "Swim", feet: 90 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Air|Extraplanar|Water"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):6"),
        source_page: Some("p.291"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d8") }, NaturalAttack { name: "Wing", damage_dice: Some("1d6") }],
        ability_keys: &["Xocothian ~ Form of Sea and Sky", "Xocothian ~ Speak with Animals"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 36,
    },
    MonsterStatBlock {
        key: "Hand of the Inheritor",
        name: "Hand of the Inheritor",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 50 }, Speed { mode: "Fly", feet: 150 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Angel|Extraplanar|Good|Herald|Lawful"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Ref):18"),
        source_page: Some("p.292"),
        natural_attacks: &[],
        ability_keys: &["Hand of the Inheritor ~ Lay on Hands", "Hand of the Inheritor ~ Divine Trigger"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 39,
    },
    MonsterStatBlock {
        key: "Angel (Iophanite)",
        name: "Angel (Iophanite)",
        size: Some("M"),
        speeds: &[Speed { mode: "Fly", feet: 40 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Angel|Extraplanar|Fire|Good|Lawful"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Ref):5"),
        source_page: Some("p.293"),
        natural_attacks: &[NaturalAttack { name: "Blade", damage_dice: Some("1d8") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 40,
    },
    MonsterStatBlock {
        key: "The Old Man",
        name: "The Old Man",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }, Speed { mode: "Swim", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Herald|Lawful"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Ref/Will):17"),
        source_page: Some("p.294"),
        natural_attacks: &[],
        ability_keys: &["The Old Man ~ Regeneration", "The Old Man ~ Monk Abilities"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 43,
    },
    MonsterStatBlock {
        key: "Pavbagha",
        name: "Pavbagha",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Lawful"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):5"),
        source_page: Some("p.295"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d8") }, NaturalAttack { name: "Claw", damage_dice: Some("1d6") }],
        ability_keys: &["Pavbagha ~ Stunning Claw", "Pavbagha ~ Fade"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 45,
    },
    MonsterStatBlock {
        key: "Yethazmari",
        name: "Yethazmari",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 50 }, Speed { mode: "Fly", feet: 100 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Evil|Extraplanar|Herald"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Will):18"),
        source_page: Some("p.296"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("6d6") }],
        ability_keys: &["Yethazmari ~ Breath Weapon", "Yethazmari ~ Bay", "Yethazmari ~ Poison Gout", "Yethazmari ~ Soul Scream", "Yethazmari ~ Poison"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 49,
    },
    MonsterStatBlock {
        key: "Demon (Swaithe)",
        name: "Demon (Swaithe)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Demon|Evil|Extraplanar"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Ref/Will):5"),
        source_page: Some("p.297"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d4") }, NaturalAttack { name: "Claw", damage_dice: Some("1d3") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 50,
    },
    MonsterStatBlock {
        key: "Arcanotheign",
        name: "Arcanotheign",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Fly", feet: 60 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Herald|Incorporeal"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Will):17"),
        source_page: Some("p.298"),
        natural_attacks: &[NaturalAttack { name: "Incorporeal touch", damage_dice: Some("4d6") }, NaturalAttack { name: "Eldritch blast", damage_dice: Some("4d6") }],
        ability_keys: &["Arcanotheign ~ Resistance to Divine Power", "Arcanotheign ~ Change Shape", "Arcanotheign ~ Eldritch Blast", "Arcanotheign ~ Energy Channel Aura", "Arcanotheign ~ Constant Spells"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 53,
    },
    MonsterStatBlock {
        key: "Burleev",
        name: "Burleev",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):5"),
        source_page: Some("p.299"),
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: Some("1d6") }],
        ability_keys: &["Burleev ~ Frostfire Spirit"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 54,
    },
    MonsterStatBlock {
        key: "The Stabbing Beast",
        name: "The Stabbing Beast",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Evil|Extraplanar|Herald|Shapechanger"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Will):17"),
        source_page: Some("p.300"),
        natural_attacks: &[NaturalAttack { name: "Sting", damage_dice: Some("1d6") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 57,
    },
    MonsterStatBlock {
        key: "Karumzek",
        name: "Karumzek",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Climb", feet: 20 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Evil|Extraplanar|Shapechanger"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Ref):5"),
        source_page: Some("p.301"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d8") }],
        ability_keys: &["Karumzek ~ Change Shape", "Karumzek ~ Deft Limbs", "Karumzek ~ Poison", "Karumzek ~ Sense Poison", "Karumzek ~ Negate Aroma"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 58,
    },
    MonsterStatBlock {
        key: "Qlippoth (Thognorok)",
        name: "Qlippoth (Thognorok)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Acquatic|Chaotic|Evil|Extraplanar|Qlippoth"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):5"),
        source_page: Some("p.305"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 65,
    },
    MonsterStatBlock {
        key: "Sunlord Thalachos",
        name: "Sunlord Thalachos",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 50 }, Speed { mode: "Fly", feet: 100 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Angel|Extraplanar|Good|Herald|Shapechanger"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Ref):15"),
        source_page: Some("p.306"),
        natural_attacks: &[],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 68,
    },
    MonsterStatBlock {
        key: "Yhohm",
        name: "Yhohm",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 60 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Fire|Good"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):5"),
        source_page: Some("p.307"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }, NaturalAttack { name: "Talon", damage_dice: Some("1d2") }],
        ability_keys: &["Yhohm ~ Holy Fire", "Yhohm ~ Self-Resurrection", "Yhohm ~ Shroud of Flame"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 69,
    },
    MonsterStatBlock {
        key: "The Spirit of Adoration",
        name: "The Spirit of Adoration",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Fly", feet: 60 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Good|Herald|Shapechanger"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Ref/Will):16"),
        source_page: Some("p.308"),
        natural_attacks: &[],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 72,
    },
    MonsterStatBlock {
        key: "Dapsara",
        name: "Dapsara",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Angel|Extraplanar|Good"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Ref/Will):5"),
        source_page: Some("p.309"),
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: Some("1d4") }],
        ability_keys: &["Dapsara ~ Bardic Performance", "Dapsara ~ Ghostly Arms", "Dapsara ~ Versatile Performance", "Dapsara ~ Weapon Proficiencies", "Dapsara ~ Change Shape"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 73,
    },
    MonsterStatBlock {
        key: "The Grand Defender",
        name: "The Grand Defender",
        size: Some("H"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Construct"),
        race_subtype: Some("Extraplanar|Herald"),
        challenge_rating: Some("15"),
        monster_class: Some("Construct:18"),
        source_page: Some("p.310"),
        natural_attacks: &[],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 76,
    },
    MonsterStatBlock {
        key: "Chalkost",
        name: "Chalkost",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Good|Lawful|Shapechanger"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):5"),
        source_page: Some("p.311"),
        natural_attacks: &[],
        ability_keys: &["Chalkost ~ Breath Weapon", "Chalkost ~ Change Shape", "Chalkost ~ Dwarf Blood", "Chalkost ~ Shock Cestus"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 77,
    },
    MonsterStatBlock {
        key: "Mother's Maw",
        name: "Mother's Maw",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 40 }],
        race_type: Some("Undead"),
        race_subtype: Some("Evil|Extraplanar|Herald"),
        challenge_rating: Some("15"),
        monster_class: Some("Undead:18"),
        source_page: Some("p.312"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("5d6") }],
        ability_keys: &["Mother's Maw ~ Spell Deflection", "Mother's Maw ~ Devour Soul", "Mother's Maw ~ Deathless", "Mother's Maw ~ Breath Weapon", "Mother's Maw ~ Channel Negative Energy", "Mother's Maw ~ Swallow Whole"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 80,
    },
    MonsterStatBlock {
        key: "Sarcovalt",
        name: "Sarcovalt",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Fly", feet: 60 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Evil|Extraplanar"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Ref/Will):4"),
        source_page: Some("p.313"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d8") }],
        ability_keys: &["Sarcovalt ~ Detach Head", "Sarcovalt ~ Disease Swarm"],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 81,
    },
    MonsterStatBlock {
        key: "The Prince in Chains",
        name: "The Prince in Chains",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Fly", feet: 50 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Evil|Extraplanar|Kyton|Lawful"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Ref):15"),
        source_page: Some("p.314"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("6d6") }, NaturalAttack { name: "Tentacle", damage_dice: Some("3d6") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 85,
    },
    MonsterStatBlock {
        key: "Kyton (Lampadarius)",
        name: "Kyton (Lampadarius)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Evil|Extraplanar|Kyton|Lawful"),
        challenge_rating: Some("4"),
        monster_class: Some("Outsider (Fort/Will):5"),
        source_page: Some("p.315"),
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: Some("1d6") }, NaturalAttack { name: "Incorporeal Touch", damage_dice: Some("1d6") }],
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "isg_races.lst",
        source_line: 86,
    },
];

/// Every inner_sea_gods monster-ability record (77 rows).
pub(super) static MONSTER_ABILITIES: &[MonsterAbilityRecord] = &[
    MonsterAbilityRecord {
        key: "Lawgiver ~ Immunity to Rust",
        name: "Immunity to Rust",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["Immunity"],
        description: Some("Though made of metal, the Lawgiver is immune to rust and rusting effects."),
        description_variables: &[],
        source_page: None,
        owners: &["Lawgiver"],
        source_file: "isg_abilities_races.lst",
        source_line: 88,
    },
    MonsterAbilityRecord {
        key: "Lawgiver ~ Freeze",
        name: "Freeze",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The Lawgiver can hold itself so still it appears to be a statue. When using freeze it can take 20 on its Stealth check to hide in plain sight as a metal statue."),
        description_variables: &[],
        source_page: None,
        owners: &["Lawgiver"],
        source_file: "isg_abilities_races.lst",
        source_line: 89,
    },
    MonsterAbilityRecord {
        key: "Lawgiver ~ Change Shape",
        name: "Change Shape",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A giant eagle (per Beastiary) or two-headed golden eagle (same stats as an eagle, but with two bite attacks) as Beast Shape IV."),
        description_variables: &[],
        source_page: None,
        owners: &["Lawgiver"],
        source_file: "isg_abilities_races.lst",
        source_line: 90,
    },
    MonsterAbilityRecord {
        key: "Orsheval ~ Electric Hooves",
        name: "Electric Hooves",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("An orsheval's hoof does an additional 1d4 electricity damage on a successful strike."),
        description_variables: &[],
        source_page: None,
        owners: &["Orsheval"],
        source_file: "isg_abilities_races.lst",
        source_line: 93,
    },
    MonsterAbilityRecord {
        key: "Orsheval ~ Glittering Radiance",
        name: "Glittering Radiance",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("An orsheval usually glows with a golden light equivalent to that of a candle. In battle, its glow increases, filling the area within 5 feet of it with shining motes. These motes cling to all creatures in the affected area, outlining them as glitterdust for 6 rounds. Opponents in the area must succeed at a DC %1 Will save or be blinded; a blinded creature may attempt a new saving throw each round at the end of its turn to end the blindness. The motes persist for 1 round after the orsheval moves from a square, leaving a trailing cloud that can affect creatures that move into the affected area. The orsheval can suppress or reactivate the glow or motes as a free action."),
        description_variables: &["OrshevalGlitterDC"],
        source_page: None,
        owners: &["Orsheval"],
        source_file: "isg_abilities_races.lst",
        source_line: 94,
    },
    MonsterAbilityRecord {
        key: "Basileus ~ Gaze",
        name: "Gaze",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Death (if 6 HD or less) or 6d6 damage and panicked for 2d4 rounds (7 HD or more), range 30 feet, Will DC %1 negates the death or panicked effect. This gaze is a mind-affecting fear effect that causes its targets to perceive Basileus as the most terrifying thing that it can imagine."),
        description_variables: &["BaslieusGazeDC"],
        source_page: None,
        owners: &["Basileus"],
        source_file: "isg_abilities_races.lst",
        source_line: 98,
    },
    MonsterAbilityRecord {
        key: "Basileus ~ Terror Shape",
        name: "Terror Shape",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("While using his gaze ability, Basileus manifests one to five monstrous limbs that can make slam attacks."),
        description_variables: &[],
        source_page: None,
        owners: &["Basileus"],
        source_file: "isg_abilities_races.lst",
        source_line: 99,
    },
    MonsterAbilityRecord {
        key: "Basileus ~ Veil of Forms",
        name: "Veil of Forms",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("All creatures see Basileus as a powerful and attractive member of thier own race. While using this ability, Basileus's gaze ability is suppressed. He can activate or suppress this ability as a free action."),
        description_variables: &[],
        source_page: None,
        owners: &["Basileus"],
        source_file: "isg_abilities_races.lst",
        source_line: 100,
    },
    MonsterAbilityRecord {
        key: "Vendenopterix ~ Ability Drain",
        name: "Ability Drain",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["AttackOption"],
        description: Some("A vendenopterix drains energy from a mortal she lures into an act of passion, such as a kiss. An unwilling victim must be grappled before the vendenopterix can use this ability. The kiss drains 1 point of INT, WIS, or CHA (her choice), and has the effect of a Suggestion spell, asking the victim to accept another act of passion (DC %1 Will negates Suggestion)."),
        description_variables: &["VendenKissDC"],
        source_page: None,
        owners: &["Vendenopterix"],
        source_file: "isg_abilities_races.lst",
        source_line: 115,
    },
    MonsterAbilityRecord {
        key: "Vendenopterix ~ Poison",
        name: "Poison",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Injury; Save Fort DC %1; Frequency 1/round for 6 rounds; Effect 1d2 Dex damage; Cure 2 consecutive saves."),
        description_variables: &["PoisonSaveDC"],
        source_page: None,
        owners: &["Vendenopterix"],
        source_file: "isg_abilities_races.lst",
        source_line: 116,
    },
    MonsterAbilityRecord {
        key: "Vendenopterix ~ Swift Tracker",
        name: "Swift Tracker",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A Vendenopterix can move at normal speed while using Survival to follow tracks without taking the normal -5 penalty. She takes only a -10 penalty (instead of the normal -20) when moving at up to twice normal speed while tracking."),
        description_variables: &[],
        source_page: None,
        owners: &["Vendenopterix"],
        source_file: "isg_abilities_races.lst",
        source_line: 117,
    },
    MonsterAbilityRecord {
        key: "Vendenopterix ~ Change Shape",
        name: "Change Shape",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Any humanoid (as Alter Self)."),
        description_variables: &[],
        source_page: None,
        owners: &["Vendenopterix"],
        source_file: "isg_abilities_races.lst",
        source_line: 118,
    },
    MonsterAbilityRecord {
        key: "Vendenopterix ~ Enchantment Resistance",
        name: "Enchantment Resistance",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("+2 to saves versus enchantments."),
        description_variables: &[],
        source_page: None,
        owners: &["Vendenopterix"],
        source_file: "isg_abilities_races.lst",
        source_line: 119,
    },
    MonsterAbilityRecord {
        key: "Thais ~ Armor of Valor",
        name: "Armor of Valor",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Defensive"],
        description: Some("Thais adds her Charisma modifier as a deflection bonus to her AC and gains a +1 luck bonus on all saves."),
        description_variables: &[],
        source_page: None,
        owners: &["Thais"],
        source_file: "isg_abilities_races.lst",
        source_line: 122,
    },
    MonsterAbilityRecord {
        key: "Thais ~ Aura of Bravery",
        name: "Aura of Bravery",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Aura"],
        description: Some("Allies within Thais' aura are affected by Remove Fear and Remove Paralysis. Allies gain a +1 morale bonus on attack rolls, weapon damage rolls, saves, and skill checks; opponents take a -1 morale penalty on such rolls."),
        description_variables: &[],
        source_page: None,
        owners: &["Thais"],
        source_file: "isg_abilities_races.lst",
        source_line: 123,
    },
    MonsterAbilityRecord {
        key: "Thais ~ Luck Domain",
        name: "Luck Domain",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("3/day Thais can use the Luck domain powers (30 ft range for Bit of Luck)."),
        description_variables: &[],
        source_page: None,
        owners: &["Thais"],
        source_file: "isg_abilities_races.lst",
        source_line: 124,
    },
    MonsterAbilityRecord {
        key: "Thais ~ Penetrating Gaze",
        name: "Penetrating Gaze",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Lawful opponents within 30 feet take 5d6 damage and are dazed for 1 round. A successful DC %1 Will save halves the damage and negates the daze effect."),
        description_variables: &["ThaisGazeDC"],
        source_page: None,
        owners: &["Thais"],
        source_file: "isg_abilities_races.lst",
        source_line: 125,
    },
    MonsterAbilityRecord {
        key: "Thais ~ Change Shape",
        name: "Change Shape",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Female elf, half-elf, or human from Medium to Huge size (as Alter Self or Giant Form II)."),
        description_variables: &[],
        source_page: None,
        owners: &["Thais"],
        source_file: "isg_abilities_races.lst",
        source_line: 126,
    },
    MonsterAbilityRecord {
        key: "Ataxian ~ Possession",
        name: "Possession",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["AttackOption"],
        description: Some("An Ataxian does not require a receptacle to use its Magic Jar spell-like ability. When using this ability on the Material Plan, its body becomes ehtereal for the duration. When the Ataxian leaves its host, the host must succeed at a DC %1 Will save or fall asleep for 1d3 minutes."),
        description_variables: &["AtaxianPossessDC"],
        source_page: None,
        owners: &["Ataxian"],
        source_file: "isg_abilities_races.lst",
        source_line: 129,
    },
    MonsterAbilityRecord {
        key: "Ataxian ~ Staggered",
        name: "Staggered",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Any creature struck by an Ataxian's ray attack must succeed at a DC %1 Fortitude save or be staggered for 1d4 rounds."),
        description_variables: &["AtaxianStagDC"],
        source_page: None,
        owners: &["Ataxian"],
        source_file: "isg_abilities_races.lst",
        source_line: 130,
    },
    MonsterAbilityRecord {
        key: "Ataxian ~ Staggering Drunk",
        name: "Staggering Drunk",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("For each alcoholic drink an Ataxian has consumed in the past hour, it gains a +1 dodge bonus to AC and takes a -1 penalty on all attack rolls, saving throws, skill checks, and ability checks, to a maximum of +4 and -4 respectively. These effects wear off after 1 hour."),
        description_variables: &[],
        source_page: None,
        owners: &["Ataxian"],
        source_file: "isg_abilities_races.lst",
        source_line: 131,
    },
    MonsterAbilityRecord {
        key: "Ataxian ~ Ray",
        name: "Ray",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["AttackOption"],
        description: Some("An Ataxian can fire a ray of cold up to 30 feet with no range increment."),
        description_variables: &[],
        source_page: None,
        owners: &["Ataxian"],
        source_file: "isg_abilities_races.lst",
        source_line: 132,
    },
    MonsterAbilityRecord {
        key: "Night Monarch ~ No Breath",
        name: "No Breath",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The Night Monarch does not breathe, and is immune to effects that require breathing (such as inhaled poison), and this ability is imparted onto any riders. This does not give immunity to cloud or gas attacks that do not require breathing."),
        description_variables: &[],
        source_page: None,
        owners: &["Night Monarch"],
        source_file: "isg_abilities_races.lst",
        source_line: 135,
    },
    MonsterAbilityRecord {
        key: "Night Monarch ~ Immunity to Cold",
        name: "Immunity to Cold",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["Immunity"],
        description: Some("The Night Monarch never takes cold damage, and this ability is imparted onto any riders."),
        description_variables: &[],
        source_page: None,
        owners: &["Night Monarch"],
        source_file: "isg_abilities_races.lst",
        source_line: 136,
    },
    MonsterAbilityRecord {
        key: "Night Monarch ~ Breath Weapon",
        name: "Breath Weapon",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["BreathWeapon"],
        description: Some("The Night Monarch's breath weapon creates sticky webbing (as Web universal monster ability, DC %1). It can use this ability in the air to entangle flying creatures without requiring the use of anchor points to hold the web in place."),
        description_variables: &["MonarchWebDC"],
        source_page: None,
        owners: &["Night Monarch"],
        source_file: "isg_abilities_races.lst",
        source_line: 137,
    },
    MonsterAbilityRecord {
        key: "Night Monarch ~ Poison Flesh",
        name: "Poison Flesh",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Any creature that bites the Night Monarch is exposed to Black Lotus Extract poison (see Core Rulebook p.558). Eating its flesh gives the attacker a -4 penalty on the poison's saving throw."),
        description_variables: &[],
        source_page: None,
        owners: &["Night Monarch"],
        source_file: "isg_abilities_races.lst",
        source_line: 138,
    },
    MonsterAbilityRecord {
        key: "Night Monarch ~ Dream Dust",
        name: "Dream Dust",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["AttackOption"],
        description: Some("As a full-round action, the Night Monarch can flutter its wings to create a 30-foot burst of dust centered on itself. This dust affects creatures as Deep Slumber, but with no HD limit (Will DC %1 negates). This ability is usable once every 1d4 rounds."),
        description_variables: &["DreamDustDC"],
        source_page: None,
        owners: &["Night Monarch"],
        source_file: "isg_abilities_races.lst",
        source_line: 139,
    },
    MonsterAbilityRecord {
        key: "Night Monarch ~ Languages",
        name: "Languages",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Communicate"],
        description: Some("The Night Monarch is unable to speak, but can understand spoken languages. It can also use telepathy with any creature it touches."),
        description_variables: &[],
        source_page: None,
        owners: &["Night Monarch"],
        source_file: "isg_abilities_races.lst",
        source_line: 140,
    },
    MonsterAbilityRecord {
        key: "Zentragt ~ Adamantine Attacks",
        name: "Adamantine Attacks",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A zentragt's bite and claw attacks count as adamantine, chaotic, and magic for the purposes of overcoming damage reduction and bypassing hardness."),
        description_variables: &[],
        source_page: None,
        owners: &["Zentragt"],
        source_file: "isg_abilities_races.lst",
        source_line: 168,
    },
    MonsterAbilityRecord {
        key: "Zentragt ~ Eat Metal",
        name: "Eat Metal",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A zentragt can eat metal to heal itself. For every 5 pounds of iron or steel it consumes, it heals 5 hit points. Adamantine, cold iron, mithral, or metals with an enhancement bonus of +1 or higher heal it double this amount. It takes a zentragt 1 minute to eat 5 pounds of metal."),
        description_variables: &[],
        source_page: None,
        owners: &["Zentragt"],
        source_file: "isg_abilities_races.lst",
        source_line: 169,
    },
    MonsterAbilityRecord {
        key: "Personification of Fury ~ Water Mastery",
        name: "Water Mastery",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The herald gains a +1 bonus on attack and damage rolls if both it and its opponent are touching water. These modifiers apply to bull rush and overrun maneuvers, whether the elemental is initiating or resisting these kinds of attacks. (Unlike a water elemental, the herald does not have a penalty if it or its opponent is touching the ground.)"),
        description_variables: &[],
        source_page: None,
        owners: &["Personification of Fury"],
        source_file: "isg_abilities_races.lst",
        source_line: 172,
    },
    MonsterAbilityRecord {
        key: "Personification of Fury ~ Change Shape",
        name: "Change Shape",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Air or water elemental only (as Elemental Body IV)."),
        description_variables: &[],
        source_page: None,
        owners: &["Personification of Fury"],
        source_file: "isg_abilities_races.lst",
        source_line: 173,
    },
    MonsterAbilityRecord {
        key: "Personification of Fury ~ Energy Ray",
        name: "Energy Ray",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["AttackOption"],
        description: Some("The herald can shoot rays of cold or electricity up to 100 feet. These can threaten a critical hit on a roll of 18, 19, or 20."),
        description_variables: &[],
        source_page: None,
        owners: &["Personification of Fury"],
        source_file: "isg_abilities_races.lst",
        source_line: 174,
    },
    MonsterAbilityRecord {
        key: "Xocothian ~ Form of Sea and Sky",
        name: "Form of Sea and Sky",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Once per hour, a xocothian can transform itself into two Small elementals (one air and one water) for up to 7 minutes. These elementals appear in adjacent squares. Each have half of the xocothian's current hit points and share the same mind. They can reform into the xocothian as a standard action if they are adjacent to each other - the reformed xocothian's hit points are equal to the total of the two elementals' hit points. If either elemental is slain, the xocothian must use its standard action on its next turn to reform (treat a slain elemental's hit points as 0 when determining the reformed xocothian's total hit points)."),
        description_variables: &[],
        source_page: None,
        owners: &["Xocothian"],
        source_file: "isg_abilities_races.lst",
        source_line: 177,
    },
    MonsterAbilityRecord {
        key: "Xocothian ~ Speak with Animals",
        name: "Speak with Animals",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Communicate"],
        description: Some("A xocothian is permanently under the effects of Speak with Animals (as the spell)."),
        description_variables: &[],
        source_page: None,
        owners: &["Xocothian"],
        source_file: "isg_abilities_races.lst",
        source_line: 179,
    },
    MonsterAbilityRecord {
        key: "Hand of the Inheritor ~ Lay on Hands",
        name: "Lay on Hands",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["LayOnHands", "Lay on Hand"],
        description: Some("You can heal wounds (your own or those of others) by touch. Each day you can use this ability %1 times per day. With one use of this ability, you can heal %2d6 hit points of damage. Using this ability is a standard action, unless you target yourself, in which case it is a swift action. Despite the name of this ability, you only need one free hand to use this ability. Alternatively, you can use this healing power to deal damage to undead creatures, dealing %2d6 points of damage. Using Lay on Hands in this way requires a melee touch attack and doesn't provide an attack of opportunity. Undead do not receive a saving throw against this damage."),
        description_variables: &["LayOnHandsTimes", "LayOnHandsDice"],
        source_page: None,
        owners: &["Hand of the Inheritor"],
        source_file: "isg_abilities_races.lst",
        source_line: 182,
    },
    MonsterAbilityRecord {
        key: "Hand of the Inheritor ~ Divine Trigger",
        name: "Divine Trigger",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The Hand of the Inheritor can activate any paladin spell from a spell trigger item as if he were an 18th-level paladin."),
        description_variables: &[],
        source_page: None,
        owners: &["Hand of the Inheritor"],
        source_file: "isg_abilities_races.lst",
        source_line: 183,
    },
    MonsterAbilityRecord {
        key: "The Old Man ~ Regeneration",
        name: "Regeneration",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["ModifyHP"],
        description: Some("You are difficult to kill. You heal damage at %1 points per round, as with fast healing, but you cannot die as long as your regeneration is still functioning (although you still fall unconscious when their hit points are below 0). Chaotic weapons and effects cause your regeneration to stop functioning on the round following the attack. During this round, you cannot heal any damage and can die normally. Attack forms that don't deal hit point damage are not healed by regeneration. Regeneration also does not restore hit points lost from starvation, thirst, or suffocation. You can regrow lost portions of you body and can reattach severed limbs or body parts if they are brought together within 1 hour of severing. Severed parts that are not reattached wither and die normally."),
        description_variables: &["RegenerationRate"],
        source_page: None,
        owners: &["The Old Man"],
        source_file: "isg_abilities_races.lst",
        source_line: 191,
    },
    MonsterAbilityRecord {
        key: "The Old Man ~ Monk Abilities",
        name: "Monk Abilities",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: Some("The Old Man has the following abilities of a 16th-level monk: AC bonus (+4), fast movement (50 ft.), flurry of blows, high jump, ki pool (18 points, adamantine, cold iron, lawful, magic, silver), quivering palm (DC 28), slow fall (80 ft.), stunning fist (blinded, deafened, fatigued, staggered, or stunned), unarmed strike"),
        description_variables: &[],
        source_page: None,
        owners: &["The Old Man"],
        source_file: "isg_abilities_races.lst",
        source_line: 192,
    },
    MonsterAbilityRecord {
        key: "Pavbagha ~ Stunning Claw",
        name: "Stunning Claw",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("This ability functions like the Stunning Fist feat, except the pavbagha uses a claw attack instead of an unarmed strike. The servitor can use this ability %1 times per day. A successful DC %2 Fortitude saving throw negates this effect. The save DC is Wisdom-based."),
        description_variables: &["StunningClawTimes", "StunningClawDC"],
        source_page: None,
        owners: &["Pavbagha"],
        source_file: "isg_abilities_races.lst",
        source_line: 195,
    },
    MonsterAbilityRecord {
        key: "Pavbagha ~ Fade",
        name: "Fade",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("As a standard action, a pavbagha can fade from sight, as invisibility, for up to 10 rounds per day. These rounds need not be consecutive."),
        description_variables: &[],
        source_page: None,
        owners: &["Pavbagha"],
        source_file: "isg_abilities_races.lst",
        source_line: 196,
    },
    MonsterAbilityRecord {
        key: "Yethazmari ~ Breath Weapon",
        name: "Breath Weapon",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["BreathWeapon"],
        description: Some("%1' Cone of fire and smoke %2d%3 fire, DC %4, usable every 1d4 rounds. Targets also must make a DC %5 Will save or be confused for 1d6 rounds."),
        description_variables: &["BreathWeaponCone", "BreathWeaponDice", "BreathWeaponDamageDie", "BreathWeaponDC", "BreathWillDC"],
        source_page: None,
        owners: &["Yethazmari"],
        source_file: "isg_abilities_races.lst",
        source_line: 199,
    },
    MonsterAbilityRecord {
        key: "Yethazmari ~ Bay",
        name: "Bay",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["AttackOption"],
        description: Some("When the Yethazmari howls or barks, each creature within a 300-foot-radius spread must succeed at a DC 25 Will save or be panicked for 2d4 rounds. This is a sonic mind-affecting fear effect. Evil outsiders are immune to this ability. Whether or not it succeeds at its save, a creature in the area is immune to the Yethazmari's bay for 24 hours. The save DC is Charisma-based."),
        description_variables: &["BayDC"],
        source_page: None,
        owners: &["Yethazmari"],
        source_file: "isg_abilities_races.lst",
        source_line: 200,
    },
    MonsterAbilityRecord {
        key: "Yethazmari ~ Poison Gout",
        name: "Poison Gout",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["AttackOption"],
        description: Some("The Yethazmari's snake tail can shoot a gout of poison as a ranged touch attack against a single foe, dealing 6d10 acid damage plus exposing them to its poison."),
        description_variables: &[],
        source_page: None,
        owners: &["Yethazmari"],
        source_file: "isg_abilities_races.lst",
        source_line: 201,
    },
    MonsterAbilityRecord {
        key: "Yethazmari ~ Soul Scream",
        name: "Soul Scream",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Anytime the Yethazmari takes piercing or slashing damage, its wounds create a terrifying cacophony equivalent to its bay ability. Creatures within 10 feet of it take a -4 penalty on their saves against this effect."),
        description_variables: &[],
        source_page: None,
        owners: &["Yethazmari"],
        source_file: "isg_abilities_races.lst",
        source_line: 202,
    },
    MonsterAbilityRecord {
        key: "Yethazmari ~ Poison",
        name: "Poison",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Injury; Save Fort DC %1; Frequency 1/round for 4 rounds; Effect 1d6 Str damage; Cure 2 consecutive saves."),
        description_variables: &["PoisonSaveDC"],
        source_page: None,
        owners: &["Yethazmari"],
        source_file: "isg_abilities_races.lst",
        source_line: 203,
    },
    MonsterAbilityRecord {
        key: "Arcanotheign ~ Resistance to Divine Power",
        name: "Resistance to Divine Power",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["Resistance"],
        description: Some("The Arcanotheign has resistance against the first 30 points of damage from a divine source (such as Flame Strike)."),
        description_variables: &[],
        source_page: None,
        owners: &["Arcanotheign"],
        source_file: "isg_abilities_races.lst",
        source_line: 211,
    },
    MonsterAbilityRecord {
        key: "Arcanotheign ~ Change Shape",
        name: "Change Shape",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("As an immediate action, the herald can take physical form, losing its incorporeal special quality and subtype and its deflection bonus to AC, but gaining a Strength score of 20 and a natural armor bonus equal to its incorporeal deflection bonus."),
        description_variables: &[],
        source_page: None,
        owners: &["Arcanotheign"],
        source_file: "isg_abilities_races.lst",
        source_line: 212,
    },
    MonsterAbilityRecord {
        key: "Arcanotheign ~ Eldritch Blast",
        name: "Eldritch Blast",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["AttackOption"],
        description: Some("The herald chooses an additional effect for its eldritch blasts each round (DC %1 negates). A creature that fails its saves against both blasts in the same round suffers an increased effect. Dement (Will): The creature is confused for 1 minute. Increased effect: The creature goes insane (as insanity). Displace (Fortitude): The creature teleports (as dimension door) 5 feet in a random horizontal direction at the end of its turn each round for the next 10 rounds. Increased effect: The creature is affected by maze. Ignite (Reflex): The creature takes 2d6 points of fire damage. Increased effect: The creature catches on fire."),
        description_variables: &["EldritchDC"],
        source_page: None,
        owners: &["Arcanotheign"],
        source_file: "isg_abilities_races.lst",
        source_line: 213,
    },
    MonsterAbilityRecord {
        key: "Arcanotheign ~ Energy Channel Aura",
        name: "Energy Channel Aura",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Aura"],
        description: Some("On its turn, the herald can channel energy (Will DC %1 half) to deal 2d6 points of acid, cold, electricity, or fire damage to each creature in its aura. A creature struck by its incorporeal touch attack also takes this damage (no saving throw)."),
        description_variables: &["EnergyChannelDC"],
        source_page: None,
        owners: &["Arcanotheign"],
        source_file: "isg_abilities_races.lst",
        source_line: 214,
    },
    MonsterAbilityRecord {
        key: "Arcanotheign ~ Constant Spells",
        name: "Constant Spells",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &[],
        description: Some("The Arcanotheign is constantly under the effects of the following spells: Arcane Sight, Protection from Chaos/Evil/Good/Law."),
        description_variables: &[],
        source_page: None,
        owners: &["Arcanotheign"],
        source_file: "isg_abilities_races.lst",
        source_line: 215,
    },
    MonsterAbilityRecord {
        key: "Burleev ~ Frostfire Spirit",
        name: "Frostfire Spirit",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A burleev is surrounded by either cold or fire energy. The burleev can change the energy type as a swift action. When surrounded by fire, the burleev has the fire subtype, is immune to fire, it adds fire damage to its attacks, and creatures striking it with melee weapons, natural attacks, or unarmed strikes take 1d6 points of fire damage; when surrounded by cold, it instead gains the cold subtype, is immune to cold and deals cold damage rather than fire damage. It can also completely dampen its aura for 1d6 rounds, but cannot reactivate it until this time has passed."),
        description_variables: &[],
        source_page: None,
        owners: &["Burleev"],
        source_file: "isg_abilities_races.lst",
        source_line: 218,
    },
    MonsterAbilityRecord {
        key: "Karumzek ~ Change Shape",
        name: "Change Shape",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Diminutive spider (as Vermin Shape II)."),
        description_variables: &[],
        source_page: None,
        owners: &["Karumzek"],
        source_file: "isg_abilities_races.lst",
        source_line: 228,
    },
    MonsterAbilityRecord {
        key: "Karumzek ~ Deft Limbs",
        name: "Deft Limbs",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A karumzek's front pair of feet are as nimble and dexterous as human hands. It takes a karumzek half the normal amount of time to create alchemical items."),
        description_variables: &[],
        source_page: None,
        owners: &["Karumzek"],
        source_file: "isg_abilities_races.lst",
        source_line: 229,
    },
    MonsterAbilityRecord {
        key: "Karumzek ~ Poison",
        name: "Poison",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Injury; Save Fort DC %1; Frequency 1/round for 6 rounds; Effect 1d3 Str, Dex or Con damage (karumzek's choice); Cure 2 consecutive saves."),
        description_variables: &["PoisonSaveDC"],
        source_page: None,
        owners: &["Karumzek"],
        source_file: "isg_abilities_races.lst",
        source_line: 230,
    },
    MonsterAbilityRecord {
        key: "Karumzek ~ Sense Poison",
        name: "Sense Poison",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("As a free action, a karumzek can detect if a creature within 15 feet of it is poisoned. It can attempt to determine the exact type of poison, as if using Detect Poison."),
        description_variables: &[],
        source_page: None,
        owners: &["Karumzek"],
        source_file: "isg_abilities_races.lst",
        source_line: 231,
    },
    MonsterAbilityRecord {
        key: "Karumzek ~ Negate Aroma",
        name: "Negate Aroma",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &[],
        description: Some("A karumzek is constantly under the effect of the Negate Aroma spell."),
        description_variables: &[],
        source_page: None,
        owners: &["Karumzek"],
        source_file: "isg_abilities_races.lst",
        source_line: 232,
    },
    MonsterAbilityRecord {
        key: "Yhohm ~ Holy Fire",
        name: "Holy Fire",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Like a Flame Strike, half the fire damage from a yhohm's fire attacks is fire damage; the other half is divine power and is not subject to fire immunity or resistance."),
        description_variables: &[],
        source_page: None,
        owners: &["Yhohm"],
        source_file: "isg_abilities_races.lst",
        source_line: 247,
    },
    MonsterAbilityRecord {
        key: "Yhohm ~ Self-Resurrection",
        name: "Self-Resurrection",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A slain yhohm remains dead for only 1d4 rounds unless its body is completely destroyed by an effect such as disintegrate. Otherwise, a fully healed yhohm emerges from the remains 1d4 rounds after death, as if brought back to life via Resurrection. The yhohm gains 1 permanent negative level when this occurs. A yhohm can self-resurrect only once per year. If a yhohm dies a second time before that year passes, its death is permanent. A yhohm that dies within the area of a desecrate spell cannot self-resurrect until the desecrate effect ends, at which point the yhohm immediately resurrects. A yhohm brought back to life by other means never gains negative levels as a result."),
        description_variables: &[],
        source_page: None,
        owners: &["Yhohm"],
        source_file: "isg_abilities_races.lst",
        source_line: 248,
    },
    MonsterAbilityRecord {
        key: "Yhohm ~ Shroud of Flame",
        name: "Shroud of Flame",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Aura"],
        description: Some("A yhohm can cause its feathers to burst into fire as a free action. As long as its feathers are burning (up to 10 rounds), it deals an additional 1d6 points of fire damage with each natural attack, and any creature within 5 feet must attempt a DC %1 Reflex save each round or take 1d6 points of fire damage at the start of its turn. A creature that attacks the yhohm with a natural or non-reach melee weapon takes 1d6 points of fire damage (no save) with each successful hit."),
        description_variables: &["FlameShroudDC"],
        source_page: None,
        owners: &["Yhohm"],
        source_file: "isg_abilities_races.lst",
        source_line: 249,
    },
    MonsterAbilityRecord {
        key: "Dapsara ~ Bardic Performance",
        name: "Bardic Performance",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A dapsara has the bardic performance ability of a 5th-level bard."),
        description_variables: &[],
        source_page: None,
        owners: &["Dapsara"],
        source_file: "isg_abilities_races.lst",
        source_line: 261,
    },
    MonsterAbilityRecord {
        key: "Dapsara ~ Ghostly Arms",
        name: "Ghostly Arms",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A dapsara's two spectral arms may manipulate corporeal or incorporeal creatures and objects, as if they had the ghost touch weapon property. She may manifest or hide these arms at will in any shape, even in gaseous form."),
        description_variables: &[],
        source_page: None,
        owners: &["Dapsara"],
        source_file: "isg_abilities_races.lst",
        source_line: 262,
    },
    MonsterAbilityRecord {
        key: "Dapsara ~ Versatile Performance",
        name: "Versatile Performance",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A dapsara has the bard's versatile performance ability, using one Perform bonus in place of the skill bonuses of that Perform skill's associated skills."),
        description_variables: &[],
        source_page: None,
        owners: &["Dapsara"],
        source_file: "isg_abilities_races.lst",
        source_line: 263,
    },
    MonsterAbilityRecord {
        key: "Dapsara ~ Weapon Proficiencies",
        name: "Weapon Proficiencies",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A dapsara is proficient with all simple weapons, plus the glaive, longsword, rapier, sap, short sword, shortbow, and whip."),
        description_variables: &[],
        source_page: None,
        owners: &["Dapsara"],
        source_file: "isg_abilities_races.lst",
        source_line: 264,
    },
    MonsterAbilityRecord {
        key: "Dapsara ~ Change Shape",
        name: "Change Shape",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Any humanoid or a cloud of perfume (as Alter Self or Gaseous Form)."),
        description_variables: &[],
        source_page: None,
        owners: &["Dapsara"],
        source_file: "isg_abilities_races.lst",
        source_line: 265,
    },
    MonsterAbilityRecord {
        key: "Chalkost ~ Breath Weapon",
        name: "Breath Weapon",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("As a free action once every 1d4+1 rounds, a chalkost can breathe a 5-foot cone of electricity (2d6 electricity damage, DC %1 Reflex for half)."),
        description_variables: &["BreathWeaponDC"],
        source_page: None,
        owners: &["Chalkost"],
        source_file: "isg_abilities_races.lst",
        source_line: 274,
    },
    MonsterAbilityRecord {
        key: "Chalkost ~ Change Shape",
        name: "Change Shape",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("When a chalkost uses its change shape ability, it can turn into a boar with metallic flesh, coppery bristles, and glistening steel tusks. In this form, a chalkost retains its damage reduction and energy resistances. The copper boar has the same statistics as a normal boar, but its natural armor bonus is +6 and its gore attack deals an extra 1d6 points of electricity damage on a successful hit."),
        description_variables: &[],
        source_page: None,
        owners: &["Chalkost"],
        source_file: "isg_abilities_races.lst",
        source_line: 275,
    },
    MonsterAbilityRecord {
        key: "Chalkost ~ Dwarf Blood",
        name: "Dwarf Blood",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A chalkost counts as a dwarf for any effect related to race, and has the hardy, slow and steady, and stability dwarven racial traits."),
        description_variables: &[],
        source_page: None,
        owners: &["Chalkost"],
        source_file: "isg_abilities_races.lst",
        source_line: 276,
    },
    MonsterAbilityRecord {
        key: "Chalkost ~ Shock Cestus",
        name: "Shock Cestus",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["AttackOption"],
        description: Some("As a free action, a chalkost can summon or dismiss a masterwork cestus on one of its hands. While wielded by the chalkost, the cestus deals an extra 1d6 points of electricity damage on a successful hit. If the cestus is given away or taken, the chalkost loses this ability until it reclaims its weapon."),
        description_variables: &[],
        source_page: None,
        owners: &["Chalkost"],
        source_file: "isg_abilities_races.lst",
        source_line: 277,
    },
    MonsterAbilityRecord {
        key: "Mother's Maw ~ Spell Deflection",
        name: "Spell Deflection",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Defensive"],
        description: Some("If any of the following spells are cast at the Mother's Maw and overcome its spell resistance, they instead affect a devoured soul: banishment, chaos hammer, confusion, crushing despair, detect thoughts, dispel evil, dominate person, fear, geas/quest, holy word, hypnotism, imprisonment, magic jar, maze, suggestion, trap the soul, or any form of charm or compulsion. While none of these effects harms the soul, the caster makes a DC 25 caster level check when a spell is deflected -- success indicates that the trapped soul is released from its prison and the creature whose body it belonged to can now be restored to life as normal. Mother's Maw can only benefit from this ability while it has a soul devoured."),
        description_variables: &[],
        source_page: None,
        owners: &["Mother's Maw"],
        source_file: "isg_abilities_races.lst",
        source_line: 281,
    },
    MonsterAbilityRecord {
        key: "Mother's Maw ~ Devour Soul",
        name: "Devour Soul",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A creature swallowed by the herald must save every round against slay living (DC %1, caster level %2). The soul of a creature slain by this attack becomes trapped within the herald's skull and the mangled corpse is immediately regurgitated. The creature cannot be brought back to life until the herald's destruction releases its soul. The Maw can hold only one soul at a time. The trapped essence provides the Maw with fast healing 20, lasting 1 round for every Hit Die of the devoured soul. The trapped soul gains 1 permanent negative level for every round it spends within the Maw -- these negative levels remain if the creature is brought back to life (but don't stack with any negative levels imparted by being brought back to life). A soul that is completely consumed may be restored to life only by a miracle or wish spell."),
        description_variables: &["DevourSoulDC"],
        source_page: Some("p.82"),
        owners: &["Mother's Maw"],
        source_file: "isg_abilities_races.lst",
        source_line: 282,
    },
    MonsterAbilityRecord {
        key: "Mother's Maw ~ Deathless",
        name: "Deathless",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("If destroyed, the herald it returns to unlife 1 hour later at 1 hit point, allowing its fast healing to resume healing it. It can be permanently destroyed by positive energy, being reduced to 0 hit points in the area of a Bless or Hallow spell, or if 20 vials of holy water are sprinkled on its remains."),
        description_variables: &[],
        source_page: None,
        owners: &["Mother's Maw"],
        source_file: "isg_abilities_races.lst",
        source_line: 283,
    },
    MonsterAbilityRecord {
        key: "Mother's Maw ~ Breath Weapon",
        name: "Breath Weapon",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("As a free action once every 1d4+1 rounds, the herald can breathe a 60-foot cone of negative energy (15d6 negative energy damage, DC %1 Reflex for half)."),
        description_variables: &["BreathWeaponDC"],
        source_page: None,
        owners: &["Mother's Maw"],
        source_file: "isg_abilities_races.lst",
        source_line: 284,
    },
    MonsterAbilityRecord {
        key: "Mother's Maw ~ Channel Negative Energy",
        name: "Channel Negative Energy",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The herald can channel negative energy as a cleric."),
        description_variables: &[],
        source_page: None,
        owners: &["Mother's Maw"],
        source_file: "isg_abilities_races.lst",
        source_line: 285,
    },
    MonsterAbilityRecord {
        key: "Mother's Maw ~ Swallow Whole",
        name: "Swallow Whole",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["AttackOption"],
        description: Some("If the herald begins its turn with an opponent grappled in its mouth, it can attempt a new combat maneuver check. If it succeeds, it swallows its prey, and the opponent takes bite damage. The opponent can be up to one size category smaller than the Maw. Being swallowed causes a creature to take damage each round. A swallowed creature keeps the grappled condition, while the Maw does not. A swallowed creature can try to cut its way free with any light slashing or piercing weapon, or it can just try to escape the grapple. If a swallowed creature cuts its way out, you cannot use swallow whole again until the damage is healed. If the swallowed creature escapes the grapple, success puts it back in the Maw's mouth, where it may be bitten or swallowed again. (see Devour Soul, AC %1, %2 hp)"),
        description_variables: &["SwallowWholeAC", "SwallowWholeHP"],
        source_page: None,
        owners: &["Mother's Maw"],
        source_file: "isg_abilities_races.lst",
        source_line: 286,
    },
    MonsterAbilityRecord {
        key: "Sarcovalt ~ Detach Head",
        name: "Detach Head",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A sarcovalt can survive without its head. Attacks that sever its head (such as those of a vorpal weapon) do not kill it. If attacked by multiple creatures, it grapples one opponent, detaches its head (which continues to drain blood), and uses its body to continue attacking with spell-like abilities. Its head and body share a common pool of hit points but are otherwise treated as different creatures while separated. The head is AC 19, touch 15, flat-footed 16 (+3 Dex, +4 natural, +2 size) and can fly at the creature's normal speed. The head cannot initiate attacks on its own, and if removed from a target, it flies back to the body on its next turn. The body cannot see, but it can perceive through the head's eye cavities if it has line of effect to the head."),
        description_variables: &[],
        source_page: None,
        owners: &["Sarcovalt"],
        source_file: "isg_abilities_races.lst",
        source_line: 289,
    },
    MonsterAbilityRecord {
        key: "Sarcovalt ~ Disease Swarm",
        name: "Disease Swarm",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A sarcovalt's vomit swarm ability summons a cloud of flies instead of spiders, which has a fly speed of 40 feet (good) and infects its target with filth fever instead of poison."),
        description_variables: &[],
        source_page: None,
        owners: &["Sarcovalt"],
        source_file: "isg_abilities_races.lst",
        source_line: 290,
    },
];
