//! Advanced Race Guide per-class spell levels — the `CLASSES:` token of
//! every real ARG spell record, split out per class.
//!
//! **Generated. Do not hand-edit.** Regenerate with
//! `cargo run --bin ingest_class_spell_levels_arg -- --emit`.
//!
//! **Why this table exists.** `spell_list::SPELL_LIST`'s `level` field is
//! the MINIMUM level across every class in the record's `CLASSES:` token,
//! not the level for any one class — the same defect
//! `crb::wizard_spell_list` was built to remove for the Core Rulebook.
//! CRB, APG and ACG each had their per-class levels ingested into the
//! twelve `<class>_spell_list.rs` tables; ARG landed later and never did,
//! so until this module no ARG spell had a per-class level anywhere, and
//! `pilot_compute`'s prepared-spell level gate silently accepted every one
//! of them at every caster level.
//!
//! Source: `pathfinder/paizo/roleplaying_game/advanced_race_guide/arg_spells.lst`, 92 spell records (base rows plus
//! the file's own `.MOD` class grafts folded into the record they name;
//! `.COPY=` variant rows excluded, matching `spell_list.rs`), yielding
//! 389 (class, spell, level) rows across 13 classes. The
//! generator that produced this file reproduces all twelve shipped
//! CRB/APG/ACG per-class tables exactly from the same corpus token
//! (`--verify`), which is what makes its ARG output trustworthy.
//!
//! Corpus class names with no hub class id are deliberately absent rather
//! than mapped to a plausible neighbour.

/// `(class id, &[(spell key, that class's spell level)])`, classes and
/// spell keys both sorted. Chained by `rules_tables::class_spell_levels`.
///
/// The `allow` is for `src/bin/gen_book_cache.rs`, which still
/// `#[path]`-includes this book's `mod.rs` a second time into its own
/// crate. That include is stale — the module has since been registered
/// in `rules_tables/mod.rs` — and nothing in that binary consumes this
/// table, so the duplicate compilation reports it dead.
#[allow(dead_code)]
pub const ARG_CLASS_SPELL_LEVELS: &[(&str, &[(&str, u8)])] = &[
    ("class:alchemist", &[
        ("Absorbing Inhalation", 4),
        ("Ancestral Regression", 2),
        ("Battle Trance", 3),
        ("Blend", 1),
        ("Blood Blaze", 2),
        ("Blood Scent", 3),
        ("Delay Disease", 2),
        ("Earth Glide", 4),
        ("Fire Trail", 3),
        ("Half-Blood Extraction", 5),
        ("Healing Warmth", 4),
        ("Linebreaker", 1),
        ("Miasmatic Form", 4),
        ("Minor Dream", 2),
        ("Paragon Surge", 3),
        ("Prehensile Pilfer", 3),
        ("Recharge Innate Magic", 1),
        ("Scorching Ash Form", 4),
        ("Sickening Strikes", 2),
        ("Squeeze", 2),
        ("Urban Grace", 1),
        ("Vomit Twin", 3),
    ]),
    ("class:antipaladin", &[
        ("Agonizing Rebuke", 2),
        ("Ancestral Regression", 3),
        ("Battle Trance", 3),
        ("Blood Blaze", 1),
        ("Blood Scent", 2),
        ("Death Candle", 1),
        ("Enemy's Heart", 2),
        ("Improve Trap", 2),
        ("Ironbeard", 1),
        ("Linebreaker", 1),
        ("Savage Maw", 1),
        ("Sentry Skull", 1),
        ("Sickening Strikes", 2),
    ]),
    ("class:bard", &[
        ("Bestow Insight", 2),
        ("Commune With Birds", 2),
        ("Death From Below", 3),
        ("Escaping Ward", 2),
        ("Fearsome Duplicate", 3),
        ("Forgetful Slumber", 4),
        ("Jitterbugs", 1),
        ("Minor Dream", 3),
        ("Nixie's Lure", 3),
        ("Prehensile Pilfer", 3),
        ("Raging Rubble", 3),
        ("Recharge Innate Magic", 1),
        ("Shadow Anchor", 2),
        ("Sow Thought", 1),
        ("Steal Breath", 2),
        ("Toilsome Chant", 1),
        ("Truespeak", 4),
        ("Urban Grace", 1),
        ("Village Veil", 5),
        ("Windy Escape", 1),
    ]),
    ("class:cleric", &[
        ("Aboleth's Lung", 2),
        ("Agonizing Rebuke", 3),
        ("Alchemical Tinkering", 2),
        ("Ancestral Regression", 2),
        ("Battle Trance", 4),
        ("Bestow Insight", 3),
        ("Blessing of Luck and Resolve", 2),
        ("Blessing of Luck and Resolve (Mass)", 6),
        ("Blinding Ray", 2),
        ("Blood Blaze", 2),
        ("Blood Scent", 3),
        ("Death Candle", 2),
        ("Delay Disease", 2),
        ("Enemy's Heart", 2),
        ("Groundswell", 2),
        ("Half-Blood Extraction", 5),
        ("Healing Warmth", 4),
        ("Imbue With Elemental Might", 2),
        ("Ironbeard", 1),
        ("Karmic Blessing", 1),
        ("Life Channel", 2),
        ("Marid's Mastery", 1),
        ("Mighty Fist of the Earth", 1),
        ("Nine Lives", 8),
        ("Paragon Surge", 3),
        ("Raging Rubble", 3),
        ("Recharge Innate Magic", 1),
        ("Sacred Space", 2),
        ("Savage Maw", 2),
        ("Sentry Skull", 2),
        ("Spawn Ward", 5),
        ("Stone Shield", 1),
        ("Theft Ward", 1),
        ("Truespeak", 6),
        ("Village Veil", 5),
        ("Ward of the Season", 4),
        ("Whispering Lore", 2),
        ("Winter Feathers", 1),
    ]),
    ("class:druid", &[
        ("Aboleth's Lung", 2),
        ("Absorbing Inhalation", 4),
        ("Binding Earth", 2),
        ("Binding Earth (Mass)", 6),
        ("Black Mark", 7),
        ("Blend", 1),
        ("Blood Scent", 3),
        ("Cloud Shape", 4),
        ("Commune With Birds", 1),
        ("Delay Disease", 2),
        ("Earth Glide", 4),
        ("Fins to Feet", 3),
        ("Fury of the Sun", 2),
        ("Groundswell", 2),
        ("Gusting Sphere", 2),
        ("Half-Blood Extraction", 5),
        ("Healing Warmth", 4),
        ("Improve Trap", 3),
        ("Marid's Mastery", 1),
        ("Mighty Fist of the Earth", 1),
        ("Mudball", 1),
        ("Nereid's Grace", 1),
        ("Nixie's Lure", 4),
        ("Old Salt's Curse", 5),
        ("Path of the Winds", 6),
        ("Raging Rubble", 3),
        ("Recharge Innate Magic", 1),
        ("Savage Maw", 2),
        ("Sickening Strikes", 2),
        ("Steal Breath", 2),
        ("Stone Shield", 1),
        ("Strong Wings", 1),
        ("Touch of Combustion", 1),
        ("Ward of the Season", 3),
        ("Whispering Lore", 1),
        ("Wind Blades", 5),
        ("Windy Escape", 1),
        ("Winter Feathers", 1),
    ]),
    ("class:inquisitor", &[
        ("Agonizing Rebuke", 3),
        ("Battle Trance", 3),
        ("Bestow Insight", 2),
        ("Blessing of Luck and Resolve", 2),
        ("Blessing of Luck and Resolve (Mass)", 6),
        ("Blinding Ray", 3),
        ("Blood Scent", 3),
        ("Death Candle", 2),
        ("Delay Disease", 2),
        ("Escaping Ward", 2),
        ("Fearsome Duplicate", 3),
        ("Healing Warmth", 4),
        ("Improve Trap", 3),
        ("Linebreaker", 1),
        ("Recharge Innate Magic", 1),
        ("Savage Maw", 2),
        ("Spawn Ward", 5),
        ("Theft Ward", 1),
        ("Touch of Combustion", 1),
        ("Winter Feathers", 1),
    ]),
    ("class:magus", &[
        ("Blend", 1),
        ("Blood Blaze", 2),
        ("Chains of Fire", 6),
        ("Escaping Ward", 2),
        ("Fire Trail", 3),
        ("Firestream", 3),
        ("Gloomblind Bolts", 3),
        ("Groundswell", 2),
        ("Gusting Sphere", 2),
        ("Imbue With Elemental Might", 2),
        ("Ironbeard", 1),
        ("Linebreaker", 1),
        ("Mudball", 1),
        ("Paragon Surge", 4),
        ("Prehensile Pilfer", 3),
        ("Recharge Innate Magic", 1),
        ("Resilient Reservoir", 3),
        ("Savage Maw", 2),
        ("Sickening Strikes", 3),
        ("Stone Shield", 2),
        ("Touch of Combustion", 1),
        ("Vomit Twin", 3),
        ("Web Bolt", 1),
        ("Wind Blades", 5),
        ("Windy Escape", 1),
    ]),
    ("class:paladin", &[
        ("Blessing of Luck and Resolve", 2),
        ("Blessing of Luck and Resolve (Mass)", 4),
        ("Blinding Ray", 2),
        ("Delay Disease", 2),
        ("Ironbeard", 1),
        ("Linebreaker", 1),
        ("Paragon Surge", 4),
        ("Resilient Reservoir", 3),
        ("Sacred Space", 2),
        ("Veil of Heaven", 1),
    ]),
    ("class:ranger", &[
        ("Battle Trance", 3),
        ("Blend", 1),
        ("Blood Scent", 2),
        ("Cloud Shape", 4),
        ("Commune With Birds", 1),
        ("Delay Disease", 2),
        ("Escaping Ward", 2),
        ("Groundswell", 2),
        ("Improve Trap", 2),
        ("Ironbeard", 1),
        ("Linebreaker", 1),
        ("Marid's Mastery", 1),
        ("Savage Maw", 1),
        ("Sickening Strikes", 4),
        ("Strong Wings", 1),
        ("Urban Grace", 1),
        ("Ward of the Season", 3),
        ("Whispering Lore", 1),
        ("Winter Feathers", 1),
    ]),
    ("class:sorcerer", &[
        ("Aboleth's Lung", 2),
        ("Absorbing Inhalation", 4),
        ("Alchemical Tinkering", 1),
        ("Ancestral Regression", 3),
        ("Bestow Insight", 2),
        ("Blend", 1),
        ("Blood Blaze", 2),
        ("Blood Scent", 3),
        ("Chains of Fire", 6),
        ("Cloud Shape", 4),
        ("Commune With Birds", 2),
        ("Damnation Stride", 5),
        ("Death From Below", 2),
        ("Earth Glide", 4),
        ("Escaping Ward", 2),
        ("Fearsome Duplicate", 3),
        ("Fins to Feet", 3),
        ("Fire Trail", 3),
        ("Firestream", 3),
        ("Forgetful Slumber", 4),
        ("Ghost Wolf", 4),
        ("Gloomblind Bolts", 3),
        ("Gusting Sphere", 2),
        ("Half-Blood Extraction", 5),
        ("Hellmouth Lash", 4),
        ("Imbue With Elemental Might", 2),
        ("Improve Trap", 3),
        ("Jitterbugs", 2),
        ("Major Phantom Object", 5),
        ("Marid's Mastery", 1),
        ("Miasmatic Form", 4),
        ("Minor Dream", 3),
        ("Minor Phantom Object", 4),
        ("Mudball", 1),
        ("Nixie's Lure", 4),
        ("Paragon Surge", 3),
        ("Path of the Winds", 6),
        ("Prehensile Pilfer", 3),
        ("Raging Rubble", 3),
        ("Recharge Innate Magic", 1),
        ("Resilient Reservoir", 4),
        ("Scorching Ash Form", 4),
        ("Sentry Skull", 2),
        ("Shadow Anchor", 2),
        ("Shadowy Haven", 4),
        ("Sow Thought", 1),
        ("Squeeze", 2),
        ("Steal Breath", 2),
        ("Stone Shield", 1),
        ("Strong Wings", 1),
        ("Theft Ward", 1),
        ("Touch of Combustion", 1),
        ("Truespeak", 5),
        ("Undine's Curse", 1),
        ("Urban Grace", 1),
        ("Village Veil", 5),
        ("Vomit Twin", 4),
        ("Web Bolt", 1),
        ("Web Cloud", 4),
        ("Wind Blades", 5),
        ("Windy Escape", 1),
        ("Winter Feathers", 1),
    ]),
    ("class:summoner", &[
        ("Damnation Stride", 4),
        ("Ghost Wolf", 2),
        ("Nixie's Lure", 4),
        ("Stone Shield", 1),
        ("Vomit Twin", 3),
    ]),
    ("class:witch", &[
        ("Aboleth's Lung", 2),
        ("Agonizing Rebuke", 3),
        ("Alchemical Tinkering", 1),
        ("Ancestral Regression", 2),
        ("Battle Trance", 4),
        ("Bestow Insight", 2),
        ("Binding Earth", 2),
        ("Binding Earth (Mass)", 6),
        ("Black Mark", 7),
        ("Blend", 1),
        ("Blood Blaze", 2),
        ("Blood Scent", 3),
        ("Commune With Birds", 2),
        ("Damnation Stride", 5),
        ("Death Candle", 2),
        ("Delay Disease", 1),
        ("Enemy's Heart", 2),
        ("Fearsome Duplicate", 3),
        ("Fins to Feet", 3),
        ("Forgetful Slumber", 4),
        ("Fury of the Sun", 2),
        ("Gloomblind Bolts", 3),
        ("Half-Blood Extraction", 5),
        ("Hellmouth Lash", 4),
        ("Improve Trap", 3),
        ("Karmic Blessing", 1),
        ("Marid's Mastery", 1),
        ("Minor Dream", 2),
        ("Mudball", 1),
        ("Nereid's Grace", 1),
        ("Nine Lives", 8),
        ("Nixie's Lure", 4),
        ("Old Salt's Curse", 5),
        ("Paragon Surge", 3),
        ("Raging Rubble", 3),
        ("Recharge Innate Magic", 1),
        ("Resilient Reservoir", 4),
        ("Sentry Skull", 2),
        ("Shadow Anchor", 2),
        ("Sickening Strikes", 2),
        ("Sow Thought", 1),
        ("Squeeze", 2),
        ("Steal Breath", 2),
        ("Strong Wings", 1),
        ("Theft Ward", 1),
        ("Touch of Combustion", 1),
        ("Truespeak", 5),
        ("Undine's Curse", 1),
        ("Urban Grace", 1),
        ("Village Veil", 5),
        ("Ward of the Season", 3),
        ("Web Bolt", 1),
        ("Web Cloud", 4),
        ("Whispering Lore", 1),
        ("Wind Blades", 5),
    ]),
    ("class:wizard", &[
        ("Aboleth's Lung", 2),
        ("Absorbing Inhalation", 4),
        ("Alchemical Tinkering", 1),
        ("Ancestral Regression", 3),
        ("Bestow Insight", 2),
        ("Blend", 1),
        ("Blood Blaze", 2),
        ("Blood Scent", 3),
        ("Chains of Fire", 6),
        ("Cloud Shape", 4),
        ("Commune With Birds", 2),
        ("Damnation Stride", 5),
        ("Death From Below", 2),
        ("Earth Glide", 4),
        ("Escaping Ward", 2),
        ("Fearsome Duplicate", 3),
        ("Fins to Feet", 3),
        ("Fire Trail", 3),
        ("Firestream", 3),
        ("Forgetful Slumber", 4),
        ("Ghost Wolf", 4),
        ("Gloomblind Bolts", 3),
        ("Gusting Sphere", 2),
        ("Half-Blood Extraction", 5),
        ("Hellmouth Lash", 4),
        ("Imbue With Elemental Might", 2),
        ("Improve Trap", 3),
        ("Jitterbugs", 2),
        ("Major Phantom Object", 5),
        ("Marid's Mastery", 1),
        ("Miasmatic Form", 4),
        ("Minor Dream", 3),
        ("Minor Phantom Object", 4),
        ("Mudball", 1),
        ("Nixie's Lure", 4),
        ("Paragon Surge", 3),
        ("Path of the Winds", 6),
        ("Prehensile Pilfer", 3),
        ("Raging Rubble", 3),
        ("Recharge Innate Magic", 1),
        ("Resilient Reservoir", 4),
        ("Scorching Ash Form", 4),
        ("Sentry Skull", 2),
        ("Shadow Anchor", 2),
        ("Shadowy Haven", 4),
        ("Sow Thought", 1),
        ("Squeeze", 2),
        ("Steal Breath", 2),
        ("Stone Shield", 1),
        ("Strong Wings", 1),
        ("Theft Ward", 1),
        ("Touch of Combustion", 1),
        ("Truespeak", 5),
        ("Undine's Curse", 1),
        ("Urban Grace", 1),
        ("Village Veil", 5),
        ("Vomit Twin", 4),
        ("Web Bolt", 1),
        ("Web Cloud", 4),
        ("Wind Blades", 5),
        ("Windy Escape", 1),
        ("Winter Feathers", 1),
    ]),
];
