//! Advanced Race Guide (ARG) shared spell list.
//!
//! Source: the real `arg_spells.lst` corpus (SD-27 Cycle E2.1/E2.2 per-book
//! pre-build). Record coverage: every real, active (non-`.MOD`,
//! non-`.COPY=`) `SCHOOL:`+`CLASSES:`-bearing spell record -- 92 total. 7
//! further raw corpus rows (`Ghost Wolf.MOD`, `Vomit Twin.MOD`, `Stone
//! Shield.MOD`, `Damnation Stride.MOD`, `Nixie's Lure.MOD`, `Strong
//! Wings.MOD`, `Fins to Feet.COPY=Fins to Feet (self only)`) modify or copy
//! an already-cataloged base record rather than defining a distinct spell,
//! mirroring `rules_tables::acg::spell_list`'s own established `.MOD`
//! exclusion discipline -- excluded here for the same reason, not counted
//! twice.
//!
//! `level` is the minimum level across the record's `CLASSES:` token(s)
//! (every real ARG spell carries at least one `CLASSES:` token; no
//! `DOMAINS:`-only record exists in this corpus, unlike ACG's one domain-only
//! variant).
//!
//! Full text, not truncated: `arg_spells.lst` carries the complete
//! multi-sentence spell text directly on the base record's own `DESC:`
//! token, with no PCGen HTML-entity encoding present anywhere in this
//! corpus file (confirmed by direct grep: zero `&[a-z]+;` hits) -- only the
//! literal `%%` -> `%` de-escape applies, same as every other book's `DESC:`
//! convention.

/// The full 9-school PF1 spell-school enum, mirroring
/// `rules_tables::acg::spell_list::Pf1SchoolId` exactly. `Universal` does
/// not appear in `arg_spells.lst` today but is included for cross-book
/// schema parity.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Pf1SchoolId {
    Abjuration,
    Conjuration,
    Divination,
    Enchantment,
    Evocation,
    Illusion,
    Necromancy,
    Transmutation,
    Universal,
}

impl Pf1SchoolId {
    pub const ALL: &'static [Pf1SchoolId] = &[
        Pf1SchoolId::Abjuration,
        Pf1SchoolId::Conjuration,
        Pf1SchoolId::Divination,
        Pf1SchoolId::Enchantment,
        Pf1SchoolId::Evocation,
        Pf1SchoolId::Illusion,
        Pf1SchoolId::Necromancy,
        Pf1SchoolId::Transmutation,
        Pf1SchoolId::Universal,
    ];

    /// Maps the corpus's raw `SCHOOL:` string to this enum.
    pub fn from_corpus_str(raw: &str) -> Option<Self> {
        match raw {
            "Abjuration" => Some(Pf1SchoolId::Abjuration),
            "Conjuration" => Some(Pf1SchoolId::Conjuration),
            "Divination" => Some(Pf1SchoolId::Divination),
            "Enchantment" => Some(Pf1SchoolId::Enchantment),
            "Evocation" => Some(Pf1SchoolId::Evocation),
            "Illusion" => Some(Pf1SchoolId::Illusion),
            "Necromancy" => Some(Pf1SchoolId::Necromancy),
            "Transmutation" => Some(Pf1SchoolId::Transmutation),
            "Universal" => Some(Pf1SchoolId::Universal),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SpellListEntry {
    /// The spell's `name` is its identity in `arg_spells.lst` (no `KEY:`
    /// token on any in-scope record).
    pub key: &'static str,
    pub school: Pf1SchoolId,
    /// Minimum spell level across the record's `CLASSES:` tag(s).
    pub level: u8,
    /// Full corpus spell text -- see this module's doc comment.
    pub description: &'static str,
}

pub const SPELL_LIST: &[SpellListEntry] = &[
    SpellListEntry { key: "Aboleth's Lung", school: Pf1SchoolId::Transmutation, level: 2, description: "The targets are able to breathe water, freely. However, they can no longer breathe air. Divide the duration evenly among all the creatures you touch. This spell has no effect on creatures that can already breathe water." },
    SpellListEntry { key: "Absorbing Inhalation", school: Pf1SchoolId::Transmutation, level: 4, description: "You grant your lungs inhuman strength and capacity, allowing you to harmlessly and completely inhale one gas, fog, smoke, mist, or similar cloud-like effect. If the targeted cloud is a magical effect, you must succeed at a caster level check (DC 11 + the effect's caster level) to inhale it. Inhaling the cloud removes it from the area, leaving normal air in its place. If the cloud is too large for you to affect with a single casting of this spell, you may instead inhale a portion of the cloud, but you must inhale the portion of the cloud closest to you. This spell has no effect on gaseous creatures. It can only affect an instantaneous-duration cloud (such as a breath weapon) if you ready an action to cast the spell in response. While inhaled, the cloud does not harm you. You may keep the cloud harmlessly contained within you for up to %1 rounds, but you must hold your breath to do so (even if you do not normally have to breathe). If the cloud has a duration, the time the cloud is contained within you counts toward that duration. As a standard action, you may release the stored cloud as a breath weapon, filling a 60-foot cone (or the cloud's original area, if smaller than a 60-foot cone). Any creature in the breath's area is subject to its normal effects, making saving throws and spell resistance checks as appropriate against the cloud's original DC. The exhaled cloud resumes its duration, if any. Exhaling the stored cloud ends this spell. If you do not exhale the cloud before this spell's duration expires, you suffer the cloud's effects|CASTERLEVEL" },
    SpellListEntry { key: "Agonizing Rebuke", school: Pf1SchoolId::Illusion, level: 2, description: "With a word and a gesture, you instill such apprehension about attacking you in your target that doing so causes it mental distress and pain. Each time the target makes an attack against you, targets you with a harmful spell, or otherwise takes and action that would harm you, it takes 2d6 points of nonlethal damage." },
    SpellListEntry { key: "Alchemical Tinkering", school: Pf1SchoolId::Transmutation, level: 1, description: "You transform one alchemical item or firearm into another alchemical item or firearm of the same or lesser cost. Magic items are unaffected by this spell. At the end of the spell's duration, alchemical items used while transformed are destroyed and do not return to a usable state and firearms transformed revert back to their original type." },
    SpellListEntry { key: "Ancestral Regression", school: Pf1SchoolId::Transmutation, level: 2, description: "The target drow transforms into a surface elf. The drow loses her darkvision and light-blindness racial traits and gains the low-light vision racial trait in their place. The alignment and personality of the drow are not affected by the transformation, but the spell conceals her alignment as an undetectable alignment spell. The spell grants the target a +10 bonus on Disguise checks to pass as an elf, though she appears to be an elven analog of herself and can be recognized as such by other drow who know her." },
    SpellListEntry { key: "Battle Trance", school: Pf1SchoolId::Enchantment, level: 3, description: "You are transformed into a single-minded force of destruction. You gain the ferocity monster special ability, a number of temporary hit points equal to 1d6 + your caster level (maximum +10), and a +4 morale bonus on saving throws against mind-affecting effects. You cannot use the withdraw action or willingly move away from a creature that has attacked you. When you use this spell, you immediately take 4 points of Intelligence damage. You must make a DC 20 concentration check to cast spells, and all other concentration checks to cast spells have a -5 penalty." },
    SpellListEntry { key: "Bestow Insight", school: Pf1SchoolId::Enchantment, level: 2, description: "When casting this spell, choose a single skill that you have at least one rank in. The target gains a +%1 insight bonus on skill checks with this skill and is considered trained in that skill. Furthermore, once before the spell's duration, the target can choose to roll two checks and take the greater result. Doing so ends the spell's other effects.|min(6,2+CASTERLEVEL/4)" },
    SpellListEntry { key: "Binding Earth", school: Pf1SchoolId::Transmutation, level: 2, description: "If the target of this spell fails its Fortitude save, areas of earth and stone floor act as a snapping quagmire that pulls the target down and damages it if it attempts to move through such terrain. If the target is a creature, it treats all areas of earth and stone it moves through as difficult terrain. Furthermore, for each 5 feet a creature moves through such areas, it takes 1d6 points of damage. Creatures with a burrow speed or the earth glide ability are unaffected by binding earth. If cast on an unattended object resting on an area of stone or earth, the stone or earth warps and wraps around it, pulling it firmly to the ground. A DC 15 Strength check is required to pull the object free from snapping earth or stone." },
    SpellListEntry { key: "Binding Earth (Mass)", school: Pf1SchoolId::Transmutation, level: 6, description: "This spell functions as binding earth, except as noted above." },
    SpellListEntry { key: "Black Mark", school: Pf1SchoolId::Necromancy, level: 7, description: "You mark the target with a black marking on its skin; the mark's exact appearance determined by you, but can be no larger than your hand. The black mark functions as a mark of justice, and when the mark is activated, the target becomes shaken anytime it is on or in the water more than a 5 feet from shore. In addition, as long as the black mark is active, the target is affected as if subject to nature's exile, but all creatures with the aquatic or water subtype or with a swim speed are made hostile, even those not of the animal type, though nonaquatic animals are not." },
    SpellListEntry { key: "Blend", school: Pf1SchoolId::Illusion, level: 1, description: "You draw upon your elven link to the wilderness to change the coloration of yourself and your equipment to match that of your surroundings. This grants you a +4 circumstance bonus on Stealth checks and allows you to make Stealth checks without cover or concealment, but only while you move no more than half your base speed or less. If you move more than half your base speed on your turn, you gain no benefit from this spell until the start of your next turn. If you make an attack, this spell ends (as invisibility)." },
    SpellListEntry { key: "Blessing of Luck and Resolve", school: Pf1SchoolId::Enchantment, level: 2, description: "A favored blessing of halfling clerics, this spell grants its target a +2 morale bonus on saving throws against fear effects. If the target has the fearless racial trait, it is immune to fear instead. If the target fails a saving throw against fear, it can end the spell as an immediate action to reroll the save with a +4 morale bonus, and must take the new result, even if it is worse." },
    SpellListEntry { key: "Blessing of Luck and Resolve (Mass)", school: Pf1SchoolId::Enchantment, level: 4, description: "This spell functions like blessing of luck and resolve, except that it affects multiple creatures." },
    SpellListEntry { key: "Blinding Ray", school: Pf1SchoolId::Evocation, level: 2, description: "You blast your enemies with blinding rays of sunlight. You may fire %1 rays. Each ray requires a ranged touch attack to hit. If a ray hits, it explodes into powerful motes of light, and the target must save or be blinded for 1 round. If the target has light blindness, light sensitivity, or is otherwise vulnerable to bright light, it instead must save or be blinded for 1d4 rounds and take %2d4 points of damage. Any creature blinded by a ray sheds light as a sunrod for the duration of its blindness. The rays may be fired at the same or different targets, but all rays must be aimed at targets within 30 feet of each other and fired simultaneously.|min(3,1+(CASTERLEVEL-3)/4)|min(5,CASTERLEVEL/2)" },
    SpellListEntry { key: "Blood Blaze", school: Pf1SchoolId::Transmutation, level: 1, description: "The target gains a 5-foot-radius aura that causes the blood of creatures in that area to ignite upon contact with air. Any creature (including the spell's target) within the aura that takes at least 5 points of piercing, slashing, or bleed damage from a single attack automatically creates a spray of burning blood. The spray strikes a creature in a randomly determined square adjacent to the injured creature. The spray deals 1d6 points of fire damage to any creature in that square, and 1 point of splash damage to all creatures within 5 feet of the spray's target, including the target of this spell. A creature can only create one spray of burning blood per round. Creatures that do not have blood (including oozes and most constructs and undead) do not create blood sprays when attacked." },
    SpellListEntry { key: "Blood Scent", school: Pf1SchoolId::Transmutation, level: 2, description: "You greatly magnify the target's ability to smell the presence of blood. The target is considered to have the scent universal monster ability, but only for purposes of detecting and pinpointing injured creatures (below full hit points). Creatures below half their full hit points or suffering bleed damage are considered strong scents for this ability. Orcs and any creature under the effects of rage gain a +2 morale bonus on attack and damage rolls against creatures they can smell with this spell, or a +4 morale bonus if the target's blood counts as a strong scent." },
    SpellListEntry { key: "Chains of Fire", school: Pf1SchoolId::Evocation, level: 6, description: "This spell functions like chain lightning, except as noted above, and the spell deals fire damage instead of electricity damage." },
    SpellListEntry { key: "Cloud Shape", school: Pf1SchoolId::Transmutation, level: 4, description: "This spell functions like gaseous form, except you assume the shape of a Colossal cloud with a space of 30 feet. You choose the general appearance of the cloud (white, stormy, fluffy, flat, and so on), after which your appearance cannot be changed. Even the closest inspection cannot reveal that the cloud in question is actually a magically concealed creature. To all normal tests you are, in fact, a cloud, although a detect magic spell reveals a moderate transmutation aura on the cloud. Your fly speed in cloud form is 30 feet." },
    SpellListEntry { key: "Commune With Birds", school: Pf1SchoolId::Divination, level: 1, description: "You utter a question in the form of a low-pitched bird call that can be heard up to a mile away, and can understand the responses given by birds in the area. Over the next 10 minutes, the birds reply as if you had asked them the question using speak with animals, giving you a general consensus answer to the question based on their knowledge. For example, you could ask if there is drinkable water in the area, the location of predators or other creatures, directions to a mountaintop or other natural feature, and so on, and the local bird communities would answer to the best of their ability. If there are no birds in range, the spell has no effect and you do not get a response. Any creature using speak with animals (or a similar ability) who hears this bird call can understand your question, though it may not be able to reply in a way you can hear." },
    SpellListEntry { key: "Damnation Stride", school: Pf1SchoolId::Conjuration, level: 5, description: "This spell functions like dimension door, except you leave behind a burst of fire. Choose one corner of your starting square. A 10-foot-radius burst of flame explodes from that corner the moment you leave, dealing 4d6 points of fire damage." },
    SpellListEntry { key: "Death Candle", school: Pf1SchoolId::Necromancy, level: 1, description: "This spell functions like death knell, except instead of using the slain target's life energy to enhance yourself, you use it to summon a Small fire elemental resembling a burning, howling version of the slain creature. The elemental acts immediately on your turn and otherwise behaves as if you had summoned it with summon monster II. The elemental remains for a number of rounds equal to the Hit Dice of the slain creature." },
    SpellListEntry { key: "Death From Below", school: Pf1SchoolId::Abjuration, level: 2, description: "You grant the target a dodge bonus to its Armor Class against attacks from larger creatures. The bonus is equal to +1 for every size category the attacker is larger than the target of the spell, to a maximum of +1 per 3 caster levels. If the spell's target is a gnome, the maximum bonus is equal to +1 per 2 caster levels." },
    SpellListEntry { key: "Delay Disease", school: Pf1SchoolId::Conjuration, level: 1, description: "The target becomes temporarily immune to disease. Any disease to which it is exposed during the spell's duration does not affect the target until the spell's duration has expired. If the target is currently infected with a disease, you must make a caster level check against the disease's DC to suspend it for the duration of the spell; otherwise, that disease affects the target normally. Delay disease does not cure any damage a disease may have already done." },
    SpellListEntry { key: "Earth Glide", school: Pf1SchoolId::Transmutation, level: 4, description: "The target can pass through stone, dirt, or almost any other sort of earth except metal as easily as a fish swims through water, traveling at a speed of 5 feet. If protected against fire damage, it can move through lava. This movement leaves behind no tunnel or hole, nor does it create any ripple or other sign of its presence. It requires as much concentration as walking, so the subject can attack or cast spells normally, but cannot charge or run. Casting move earth on an area containing the target flings the target back 30 feet, stunning it for 1 round (DC 15 Fortitude negates). This spell does not give the target the ability to breathe underground, so when passing through solid material, the creature must hold its breath." },
    SpellListEntry { key: "Enemy's Heart", school: Pf1SchoolId::Necromancy, level: 2, description: "You cut out an enemy's heart and consume it, absorbing that enemy's power as your own. As part of casting this spell, you perform a coup de grace with a slashing weapon on a helpless, living adjacent target. If the target dies, you eat its heart to gain the spell's benefits. If the target survives, the spell is not wasted and you can try again as long as you continue concentrating on the spell. When you consume the heart, you gain the benefits of a death knell spell, except you gain 1d8 temporary hit points +1 per Hit Die of the target, and the bonus to Strength is a profane bonus." },
    SpellListEntry { key: "Escaping Ward", school: Pf1SchoolId::Abjuration, level: 2, description: "This ward grants you extra maneuverability when you avoid attacks against larger foes. While affected by this spell, when you are attacked and missed by a creature that is at least one size category larger than you, you can, as an immediate action, move up to %1 feet away from the attacking creature. This movement does not provoke attacks of opportunity.|(1+CASTERLEVEL/5)*5" },
    SpellListEntry { key: "Fearsome Duplicate", school: Pf1SchoolId::Illusion, level: 3, description: "You create a larger and far more menacing version of yourself that you can send forth, manipulate like a puppet, and use to interact with others. You can make the duplicate up to two size categories larger than you are and determine a theme as to how it alters your original appearance. However, this duplicate always retains some vestiges of your actual appearance. Creatures who already know you gain a +2 bonus on saving throws made to disbelieve this spell. Your duplicate has no actual substance, and you cannot use it to alter its surroundings or to attack or otherwise harm creatures it encounters. You can use the duplicate to speak, and interact verbally with creatures using the Bluff, Diplomacy, and Intimidate skills, and you gain a +2 competence bonus on Intimidate checks when using that skill through the duplicate. You can see, hear, taste, and smell your duplicate's surroundings as if you are actually present using your Perception skill. While you also remain aware of your own immediate surroundings when controlling your duplicate, controlling it does take a toll on your senses. You take a -4 penalty on Perception checks while you control your duplicate. The duplicate moves under your mental command, and while you need not act out its movements, you must take a standard action to control your duplicate for 1 round (concentrating on the spell) or it winks out of existence. You can maintain control of your duplicate even if you have no line of sight or line of effect to it. The duplicate immediately winks out of existence if it is hit by an attack or in the area of a damaging effect, or if it moves beyond the maximum range of the spell." },
    SpellListEntry { key: "Fins to Feet", school: Pf1SchoolId::Transmutation, level: 3, description: "You transform the target's fins, flippers, or tail into legs and feet, allowing it to walk on land. The target loses its swim speed but gains a base speed appropriate for a humanoid of its size (speed 30 if a Medium or larger creature, speed 20 if Small). If the creature is immersed in water for 1 round, the transformation reverts, allowing it to swim normally. One round after leaving the water, the transformation occurs again, allowing it to walk. This spell only works on merfolk, tritons, seals, fish, and other creatures whose bodies or limbs are used mainly for swimming and are not suitable for walking. It does not give the target the ability to breathe air." },
    SpellListEntry { key: "Fire Trail", school: Pf1SchoolId::Transmutation, level: 3, description: "When you cast this spell, flammable liquid oozes from your pores, dripping onto the ground and spontaneously combusting. The flame does not harm you. During this spell's duration, each time you leave your space, you create a trail of fire that burns within the spaces you move through for 1 round before it burns out. You can leave up to 60 feet of flame trail each round, assuming you are Small or Medium. If you are larger than Medium, the maximum trail length is reduced based on your size. If you are Large, you can leave a trail up to 30 feet long (and 10 feet wide), and if you are Huge, you can leave a trail up to 15 feet long (and 15 feet wide); even larger casters can only leave a trail up to 10 feet long (and as wide as your space) each round. You choose where to leave a flame trail. Creatures that start their turn adjacent to the flame trail take 1d6 points of fire damage. Creatures that start their turn within the flame trail or that enter an area of flame take a number of points of fire damage equal to 1d6 + 1 per caster level (maximum +10). If a creature moves into an area of the flame trail multiple times in a round, it takes this damage each time it enters the area of the flame trail. Flammable objects in or adjacent to the fire trail catch fire." },
    SpellListEntry { key: "Firestream", school: Pf1SchoolId::Evocation, level: 3, description: "A rushing stream of fire sprays from your outstretched hand, dealing 2d6 points of fire damage to every creature in the area. Each round you continue to concentrate on the spell, you can select a new area for it to affect. Firestream sets fire to combustibles and damages objects in the area. It can melt metals with low melting points, such as lead, gold, copper, silver, and bronze. If the damage caused to an interposing barrier shatters or breaks through it, the firestream may continue beyond the barrier if the area permits; otherwise it stops at the barrier just as any other spell effect does." },
    SpellListEntry { key: "Forgetful Slumber", school: Pf1SchoolId::Enchantment, level: 4, description: "This spell acts as the deeper slumber spell, but only affects one creature of 10 Hit Dice or fewer. In addition, a creature affected by this spell awakens with no knowledge of the events that led to the spell's casting. The target loses all memory from the 5 minutes prior to falling asleep. No effect short of a miracle or wish can restore memories lost by this spell." },
    SpellListEntry { key: "Fury of the Sun", school: Pf1SchoolId::Transmutation, level: 2, description: "You curse the target to suffer unbearable heat. On a failed saving throw, the target is immediately subjected to severe heat (Core Rulebook 444), takes 1d4 points of nonlethal damage, and is suffering from heatstroke (fatigued). The target must save every 10 minutes as normal for severe heat (starting at DC 15). Because this heat is internal, the target cannot avoid it using the normal methods for escaping heat dangers such as Survival checks or finding shade." },
    SpellListEntry { key: "Ghost Wolf", school: Pf1SchoolId::Conjuration, level: 4, description: "This spell conjures a Large, quasi-real, wolflike creature made of roiling black smoke. It functions as phantom steed, except as noted above. In addition, the creature radiates an aura of fear. Any creature with fewer than 6 Hit Dice within 30 feet (except the ghost wolf's rider) must make a Will save or become shaken for 1d4 rounds. A creature that makes its Will save is unaffected by the steed's fear aura for 24 hours. The ghost wolf may also be used in combat. Once per round, the rider may direct the ghost wolf to attack in battle as a free action (bite +10, 1d8+6 points of damage); unlike an animal mount, this does not require a Ride check or any training. Once the ghost wolf attacks, it lasts for only 1 round per level thereafter." },
    SpellListEntry { key: "Gloomblind Bolts", school: Pf1SchoolId::Conjuration, level: 3, description: "You create one or more bolts of negative energy infused with shadow pulled from the Shadow Plane. You can fire %1 bolts at the same or different targets, but all bolts must be aimed at targets within 30 feet of each other and require a ranged touch attack to hit. Each bolt deals 4d6 points of damage to a living creature or heals 4d6 points of damage to an undead creature. Furthermore, the bolt's energy spreads over the skin of creature, possibly blinding it for a short time. Any creature struck by a bolt must succeed at a Reflex saving throw or become blinded for 1 round.|min(3,1+(CASTERLEVEL+5)/4)" },
    SpellListEntry { key: "Groundswell", school: Pf1SchoolId::Transmutation, level: 2, description: "This spell allows the target to cause the ground to rise up beneath him. As a swift action, the target can cause the ground to rise 5 feet, while all adjacent squares are treated as steep slopes. The groundswell precludes flanking from creatures standing at lower elevations than the target. If the target moves after creating a groundswell, the ground returns to its normal elevation at the end of his turn; otherwise, it remains in place until the target moves or uses a swift action to return the ground to normal. A groundswell cannot increase elevation of the ground beyond 5 feet." },
    SpellListEntry { key: "Gusting Sphere", school: Pf1SchoolId::Evocation, level: 2, description: "A swirling ball of wind rolls in whichever direction you point, hurling those it strikes with great force. The sphere is treated in all ways as an area of severe wind, applying a -4 penalty on ranged weapon attacks that pass through it. The sphere moves 30 feet per round. As part of this movement, it can ascend or jump up to 30 feet to strike a target. If it enters a space containing a Medium or smaller creature, it stops moving for that round and generates a sharp thrust of wind to bull rush the creature. The sphere's CMB for bull rush combat maneuvers uses your caster level in place of its base attack bonus, with a +2 bonus for its Strength score (14). Whether or not the bull rush is successful, the creature takes 1d6 points of nonlethal bludgeoning damage from the attack. If the bull rush fails, the creature is still subject to the severe winds from the sphere as long as they remain in the same square as it. A gusting sphere rolls over objects or barriers that are less than 4 feet tall. The sphere moves as long as you actively direct it (a move action for you); otherwise, it merely stays at rest. A gusting sphere immediately dissipates if it exceeds the spell's range." },
    SpellListEntry { key: "Half-Blood Extraction", school: Pf1SchoolId::Transmutation, level: 5, description: "You transform the target half-orc into a full-blooded orc. The target loses all of its half-orc racial traits and gains the orc racial traits." },
    SpellListEntry { key: "Healing Warmth", school: Pf1SchoolId::Abjuration, level: 4, description: "This spell grants you temporary immunity to fire damage as protection from energy. As a standard action, you may sacrifice 12 points of remaining energy absorption from the spell to heal a touched creature of 1d8 points of damage. Healing a creature provokes an attack of opportunity. When the spell has absorbed %1 points of fire damage, it is discharged.|min(120,CASTERLEVEL*12)" },
    SpellListEntry { key: "Hellmouth Lash", school: Pf1SchoolId::Transmutation, level: 4, description: "Upon casting this spell, your tongue transforms into an energy whip weapon that can deal acid, electricity, or fire damage. You choose what type of energy damage the spell deals when you cast it. You attack with your tongue as if it were a whip, except you make touch attacks with it and it can harm creatures with armor or natural armor bonuses. You are considered proficient with this weapon. A successful touch attack with the tongue deals 1d8 points of energy damage per two caster levels (maximum of 5d8 points of damage at 10th level). While the spell is in effect, you cannot speak, cast spells requiring verbal components, or activate items requiring command words. The spell has the acid, electricity, or fire descriptor, depending on what type of energy damage you chose when you cast it." },
    SpellListEntry { key: "Imbue With Elemental Might", school: Pf1SchoolId::Evocation, level: 2, description: "This spell functions like imbue with spell ability, except you transfer the use of your elemental assault ability to the target. The target must have an Intelligence score of at least 5 to use the ability. The imbued elemental assault functions exactly like yours, except the ability's duration is based on the target's level or Hit Dice. Once you cast this spell, you cannot use your elemental assault ability until the duration of the spell is over." },
    SpellListEntry { key: "Improve Trap", school: Pf1SchoolId::Transmutation, level: 2, description: "When this spell is cast upon a trap, it improves one specific element of the trap chosen at the time of casting. The caster can improve the trap in any of the following ways (each one raises the trap's CR by +1). Increase DC of the Perception check required to locate the trap by +5. Increase DC of the Disable Device check required to disarm trap by +5. Increase the trap's attack bonus or saving throw by +2. To cast this on a trap, you must know that the trap exists and its precise location. A trap can only have one improvement from this spell at a time. A second casting changes the improvement on the trap, but does not add another improvement." },
    SpellListEntry { key: "Ironbeard", school: Pf1SchoolId::Transmutation, level: 1, description: "This spell causes a brushy beard of stiff iron to erupt from the face of a willing target. The ironbeard grants a +1 armor bonus to AC, and this bonus stacks with any armor worn by the creature. The ironbeard may also be used as a weapon equivalent to cold iron armor spikes. The ironbeard makes it difficult to speak, so any spellcasting with a verbal component has a 20%% spell failure chance." },
    SpellListEntry { key: "Jitterbugs", school: Pf1SchoolId::Illusion, level: 1, description: "You cause the target to perceive itself as being covered in creeping, crawling, stinging bugs. This causes the target to become jittery and unable to stay still, forcing it to constantly move and twitch. The target takes a -4 penalty on all Dexterity checks and Dexterity-based skill checks, and cannot take the delay, ready, or total defense actions." },
    SpellListEntry { key: "Karmic Blessing", school: Pf1SchoolId::Divination, level: 1, description: "The target treats one skill of your choice as a class skill." },
    SpellListEntry { key: "Life Channel", school: Pf1SchoolId::Transmutation, level: 2, description: "When cast on a creature with negative energy affinity, the target is able to convert channeled positive energy into temporary hit points. When subject to an effect that heals hit points only to living creatures (such as cure light wounds or channel positive energy), the target gains a number of temporary hit points equal to half the number of hit points that the positive energy would normally heal. These temporary hit points go away at the end of this spell's duration." },
    SpellListEntry { key: "Linebreaker", school: Pf1SchoolId::Transmutation, level: 1, description: "You gain a +20 foot bonus to your base speed when charging and a +2 bonus on combat maneuver checks made to bull rush or overrun." },
    SpellListEntry { key: "Major Phantom Object", school: Pf1SchoolId::Illusion, level: 5, description: "This spell functions as the major creation spell, except as noted above and the object created is a semi-real illusion. Any creature that interacts with the object may make a Will save, with success causing the object to cease to exist. A gnome casting this spell may make a Spellcraft check in place of any Craft check required to make a complex item." },
    SpellListEntry { key: "Marid's Mastery", school: Pf1SchoolId::Transmutation, level: 1, description: "The target gains a +1 bonus on attack and damage rolls if it and its opponent are touching water. If the opponent or the target is touching the ground, the target takes a -4 penalty on attack and damage rolls." },
    SpellListEntry { key: "Miasmatic Form", school: Pf1SchoolId::Transmutation, level: 4, description: "This spell functions like gaseous form, except the target's vaporous body is dangerous to creatures that touch it. A creature can make a Fortitude save (DC %1) on its turn to resist the vapors. When you cast this spell, you select one of the following options. Stinking cloud: The target's body nauseates creatures that fail their saving throws, as stinking cloud (Fortitude negates, see text). This form of the spell does not require a material component. Poisonous cloud: The target's body is deadly poison, dealing 1d2 points of Constitution damage to creatures that fail their saves (Fortitude halves). This form of the spell requires a material component.|14+INT" },
    SpellListEntry { key: "Mighty Fist of the Earth", school: Pf1SchoolId::Conjuration, level: 1, description: "You create a fist-sized rock that flies toward one enemy. Make an unarmed strike attack roll against the target as if it were in your threatened area. If the attack is successful, the rock deals bludgeoning damage to the target as if you had hit the target with your unarmed strike. If you have a ki pool, as long as you have at least 1 point in your ki pool, the rock counts as a ki strike." },
    SpellListEntry { key: "Minor Dream", school: Pf1SchoolId::Illusion, level: 2, description: "This spell functions as the dream spell, except as follows. The messenger must be yourself or a gnome touched. The message can be no longer than 20 words. If the recipient of the message is not asleep when the spell is cast, the spell automatically fails." },
    SpellListEntry { key: "Minor Phantom Object", school: Pf1SchoolId::Illusion, level: 4, description: "This spell functions as the minor creation spell, except the object created is a semi-real illusion. Any creature that interacts with the object may make a Will save, with success causing the object to cease to exist. A gnome casting this spell may make a Spellcraft check in place of any Craft check required to make a complex item." },
    SpellListEntry { key: "Mudball", school: Pf1SchoolId::Conjuration, level: 1, description: "When you cast this spell, you conjure a single ball of sticky mud and launch it at an enemy's face as a ranged touch attack. If the mudball hits, the target is blinded. Each round at the beginning of its turn, a creature blinded by this spell can attempt a Reflex saving throw to shake off the mud, ending the effect. The mudball can also be wiped off by the creature affected by it or by a creature adjacent to the creature affected by it as a standard action." },
    SpellListEntry { key: "Nereid's Grace", school: Pf1SchoolId::Abjuration, level: 1, description: "You radiate the unearthly grace of a nereid. If you're not wearing armor, you gain a deflection bonus to your AC and CMD equal to your Charisma bonus (maximum +3). The maximum increases by 1 for every 6 levels you possess (maximum +6 at 18th level)." },
    SpellListEntry { key: "Nine Lives", school: Pf1SchoolId::Abjuration, level: 8, description: "Despite its name, this powerful ward does not grant the target multiple lives, but rather gives the target the ability to get out of trouble and relieves harmful effects and conditions. For the spell's duration, the target can use any of the following abilities as an immediate action, but only up to a total of nine times, at which point the spell ends. Cat's Luck: The target can use this ability when it fails a saving throw. The target can reroll the failed saving throw, but must take the new result even if it is worse. Fortitude: The target uses this ability when a critical hit or sneak attack is scored against it. The critical hit or sneak attack is negated and the damage is instead rolled normally. Rejuvenate: The target uses this ability when it is reduced to 0 or fewer hit points. The target is instantly healed 3d6 points of damage. If enough hit points are regained to bring the target to positive hit points, it does not fall unconscious. If it is not enough to leave the target with positive hit points, the target automatically stabilizes. Both of these effects work even if the damage was originally enough to kill the target. Shake Off: The target uses this ability when it is under the effects of any of the following conditions: blinded, confused, cowering, dazed, dazzled, entangled, exhausted, fatigued, frightened, nauseated, panicked, shaken, sickened, or staggered. Using this ability ends one of those conditions. Shimmy Out: The target uses this ability when it is grappled or pinned. The target automatically escapes the grapple as if it had succeeded at an Escape Artist check to escape the grapple. Stay Up: The target uses this ability when it is tripped or otherwise knocked prone. The target steadies itself and stays upright." },
    SpellListEntry { key: "Nixie's Lure", school: Pf1SchoolId::Enchantment, level: 3, description: "This spell creates an unearthly and infectious song that seductively summons all who hear it. Nixie's lure affects a maximum of 24 Hit Dice of creatures. Creatures in the area who fail their saves are lured by the song and move toward you using the most direct means available. If the path leads them into a dangerous area such as through fire or off a cliff, the creatures each receive a second saving throw to end the effect before moving into peril. Creatures lured by the spell's song can take no actions other than to defend themselves. A victim within 5 feet of you simply stands still and for the duration of the spell remains fascinated." },
    SpellListEntry { key: "Old Salt's Curse", school: Pf1SchoolId::Necromancy, level: 5, description: "You inflict a curse of the roiling sea upon the target, making it permanently sickened. Anytime the target is on or in the water more than a mile from shore, it also becomes staggered with seasickness. This curse cannot be dispelled, though remove curse or break enchantment can negate it." },
    SpellListEntry { key: "Paragon Surge", school: Pf1SchoolId::Transmutation, level: 3, description: "You surge with ancestral power, temporarily embodying all the strengths of both elvenkind and humankind simultaneously, and transforming into a paragon of both races, something greater than elf or human alone. Unlike with most polymorph effects, your basic form does not change, so you keep all extraordinary and supernatural abilities of your half-elven form as well as all of your gear. For the duration of the spell, you receive a +2 enhancement bonus to Dexterity and Intelligence and are treated as if you possessed any one feat for which you meet the prerequisites, chosen when you cast this spell. The first time each day that you cast this spell, you must select a feat and make all the associated choices that come with it. Once that choice is made, it is set for the day and additional castings must make the exact same decisions." },
    SpellListEntry { key: "Path of the Winds", school: Pf1SchoolId::Evocation, level: 6, description: "With a sweeping gesture, you call forth mighty winds to clear a path ahead of you. The winds are the equivalent of a windstorm (Core Rulebook 439). During the first round of the spell, the winds sweep the designated area clear of anything of Small or smaller size, blowing it outward to the sides of the spell's effect (50%% chance of landing on either side). You may move within the effect without penalty, though all other creatures are subject to the wind's effects. On the second and all later rounds of the spell, the edges of the effect are treated as a wind wall. If the effect includes a body of water or other liquid, the winds create a channel up to 40 feet deep into the surface of the liquid. On your turn as a move action, you can move the effect of this spell, either rotating it at one of its ends up to 45 degrees, or moving it up to 50 feet in line with its current orientation (toward you or away from you)." },
    SpellListEntry { key: "Prehensile Pilfer", school: Pf1SchoolId::Transmutation, level: 3, description: "The target's tail moves and acts more quickly, almost with a mind of its own. When making a full-attack action, the target may use its tail to make a dirty trick or steal combat maneuver as a swift action. For the purpose of this attack, the target's tail is a natural weapon with a reach of 5 feet. This spell has no effect on creatures lacking a prehensile tail. If the target already has an extra attack from haste or a similar effect, this spell only allows the tail to make dirty trick and steal combat maneuvers, but does not grant an extra attack." },
    SpellListEntry { key: "Raging Rubble", school: Pf1SchoolId::Transmutation, level: 3, description: "You animate an area of rubble, gravel, or other small stones, creating a dangerous, rolling area of debris. The animated rubble has a space of 10 feet and acts like a swarm, damaging (1d6 hit points) and distracting (DC 12) anything within it. As a move action, you can direct the rubble to move up to 10 feet. If the rubble is attacked, treat it as a Medium animated object with the young creature simple template and the swarm subtype." },
    SpellListEntry { key: "Recharge Innate Magic", school: Pf1SchoolId::Transmutation, level: 1, description: "You channel magic energy into your own aura, recharging your innate magic abilities. You regain one use of all 0-level and 1st-level spell-like abilities you can use as a result of a racial trait." },
    SpellListEntry { key: "Resilient Reservoir", school: Pf1SchoolId::Transmutation, level: 3, description: "This spell creates a magical well of retribution that a caster can unleash with blinding speed. Upon casting this spell, damage from melee attacks and touch spells gets transferred into a special pool that you then redirect before the spell's duration expires. Each time you are struck by a melee attack or touch spell that deals hit point damage, 1 point of damage is negated and transferred into the reservoir created by this spell. The total number of points in the reservoir cannot exceed your caster level (to a maximum of 20 points at 20th level). As an immediate action, anytime before the spell's duration expires, you can expend a number of points of energy from the energy of the reservoir, granting yourself an insight bonus on one skill check, attack roll, damage roll, or combat maneuver check, but you must do so before the roll is made. The bonus is equal to the number of points spent. For every five caster levels, you may call upon the reservoir one additional time (maximum of four times at 15th level). If you are reduced to negative hit points while you are under the effect of this spell, the spell automatically release the remaining magic of the reservoir in a concussive blast of force. All creatures within a 15-foot radius take 1d6 points of force damage per 2 points remaining in the reserve (maximum of 10d6). A successful Reflex save halves this damage, and spell resistance applies to this effect." },
    SpellListEntry { key: "Sacred Space", school: Pf1SchoolId::Evocation, level: 2, description: "This spell sanctifies an area with heavenly power. The DC to resist spells or spell-like abilities with the good descriptor or channeled energy that damages evil outsiders (as when using Alignment Channel) increases by +2. In addition, evil outsiders take a -1 penalty on attack rolls, damage rolls, and saving throws, and they cannot be called or summoned into a sacred space. If the sacred space contains an altar, shrine, or other permanent fixture dedicated to your deity, pantheon, or good-aligned higher power, the modifiers given above are doubled. You cannot cast sacred space in an area with a permanent fixture dedicated to a deity other than yours." },
    SpellListEntry { key: "Savage Maw", school: Pf1SchoolId::Transmutation, level: 1, description: "Your teeth extend and sharpen, transforming your mouth into a maw of razor-sharp fangs. You gain a bite attack that deals 1d4 points of damage plus your Strength modifier. If you confirm a critical hit with this attack, it also deals 1 point of bleed damage. If you already have a bite attack, your bite deals 2 points of bleed damage on a critical hit. You are considered proficient with this attack. If used as part of a full-attack action, the bite is considered a secondary attack, is made at your full base attack bonus -5, and adds half your Strength modifier to its damage. You can end this spell before its normal duration by making a bestial roar as a swift action. When you do, you can make an Intimidate check to demoralize all foes within a 30-foot radius that can hear the roar." },
    SpellListEntry { key: "Scorching Ash Form", school: Pf1SchoolId::Transmutation, level: 4, description: "This spell functions like gaseous form, except the target becomes a visible swirl of hot ash and smoke instead of harmless translucent gas. The target gains the fire subtype. Any creature that begins its turn sharing a space with the target takes 2d6 points of fire damage and must make a Fortitude save (DC 15, + 1 per previous check) or suffer the effects of smoke inhalation." },
    SpellListEntry { key: "Sentry Skull", school: Pf1SchoolId::Necromancy, level: 1, description: "You restore the senses to the severed head of a humanoid or monstrous humanoid killed within the past 24 hours, creating a grisly sentinel. The head must be affixed to a pole, spear, tree branch, or other stable object, and the spell ends if the head or its object is moved. The head has darkvision 60 feet and low-light vision, can swivel in place to look in any direction, and has a +5 bonus on Perception checks. If you are within 30 feet of the head, as a standard action you can shift your senses to it, seeing and hearing from its location and gaining the benefit of its darkvision and low-light vision, and you may use its Perception skill instead of your own. While your senses are in the severed head, your body is blind and deaf until you spend a free action to shift your senses back to your own body. When you create the head, you can imprint it with a single triggering condition, similar to magic mouth. Once this triggering condition is set, it can never be changed. If you are within 30 feet of the head, you immediately know if it is triggered (if you have multiple active sentry skulls, you also know which one was triggered). This wakens you from normal sleep but does not otherwise disturb your concentration. For example, you could have a sentry skull alert you if any humanoid comes into view, if a particular rival approaches, if your guard animal is killed, and so on, as long as it occurs where the severed head can see it. This spell does not give the head any ability to speak, think, or take any kind of action other than to turn itself, though it is a suitable target for other spells such as magic mouth." },
    SpellListEntry { key: "Shadow Anchor", school: Pf1SchoolId::Illusion, level: 2, description: "The target's shadow becomes a flexible tether to its current square. The creature can move up to 5 feet from that square without penalty. Moving farther than 5 feet from the tether point requires the target to make a bull rush combat maneuver check against a CMB of %1 (if a witch or wizard) or %2 (if a bard or sorcerer). The target takes a -1 penalty for every 5 feet of distance between it and its tethered square. Failing this check means the target's move is wasted and it cannot move farther away. If it fails this check by 10 or more, it is pulled 5 feet toward the tether square and is knocked prone. If it beats the check by 10 or more, the spell ends. This spell does not work on creatures that do not cast shadows or reflections. If the target uses a teleportation effect or leaves the current plane, the spell ends.|10+CASTERLEVEL/2+INT|10+CASTERLEVEL/2+CHA" },
    SpellListEntry { key: "Shadowy Haven", school: Pf1SchoolId::Transmutation, level: 4, description: "This spell functions like rope trick, except the point of entry is through a 5-foot-square instead of a rope. The space holds as many as 10 creatures of any size. When this spell is cast upon a 5-foot-square part of a wall, it creates an extradimensional space adjacent to the Plane of Shadow. Creatures in the extradimensional space are hidden beyond the reach of spells (including divinations) unless those spells work across planes. The space holds as many as 10 creatures (of any size). The entrance to the extradimensional space remains visible as an area that is darker than the ambient illumination. Spells cannot be cast across the extradimensional interface, nor can area effects cross it. Those in the extradimensional space can see out of it as if a 5-foot-by-5-foot door or window were centered on the affected surface. The window is invisible (though it is within the shadowed entrance to the spell, which is visible), and even creatures that can see the window from the outside can't see through it. Anything inside the extradimensional space is ejected when the spell ends. Only one creature may enter or exit the extradimensional space at a time. The entrance is only open when the area around it is in dim light. Any other level of light (brighter or darker) closes the entrance, trapping creatures inside the extradimensional space. If the entrance is closed when the spell expires, there is a 50%% chance that creatures in it are ejected into the Shadow Plane instead of the location of the entrance. If this occurs, the creatures appear on the Shadow Plane 1d10 miles in a random direction from their corresponding location on the Material Plane. The spell has no effect if cast on a plane that is not adjacent to the Shadow Plane. Because the extradimensional space is adjacent to the Shadow Plane, any shadow walk spell or similar effect that allows travel to the Shadow Plane is more accurate, reducing the distance creatures arrive off-target by half." },
    SpellListEntry { key: "Sickening Strikes", school: Pf1SchoolId::Transmutation, level: 2, description: "You are imbued with disease, and any creature you strike with a melee attack must make a Fortitude save or be sickened for 1 minute. Creatures that are immune to disease are immune to this sickened effect." },
    SpellListEntry { key: "Sow Thought", school: Pf1SchoolId::Enchantment, level: 1, description: "You plant an idea, concept, or suspicion in the mind of the subject. The target genuinely believes that the idea is his own, but is not required to act upon it. If the idea is contrary to the target's normal thoughts (such as making a paladin think, \"I should murder my friends\") the target may suspect mindaltering magic is at play. The idea must be fairly clear, enough so that it can be conveyed in one or two sentences. You do not need to share a common language for the spell to succeed, but without a common language you can only sow the most basic rudimentary ideas." },
    SpellListEntry { key: "Spawn Ward", school: Pf1SchoolId::Necromancy, level: 5, description: "The target becomes resistant to the effects of energy drain and blood drain attacks made by undead creatures, and cannot be made into undead spawn if killed while the spell is in effect. If the attacking undead's Hit Dice is less than or equal to %1, the blood drain or energy drain has no effect. If the attacking undead's Hit Dice are greater than %1, the undead must make a Fortitude save (against the DC of the spell) with each attack for those special abilities to have any effect. The spell only prevents the Constitution damage from blood drain and negative levels from energy drain, but not any other effects of these attacks.|CASTERLEVEL" },
    SpellListEntry { key: "Squeeze", school: Pf1SchoolId::Transmutation, level: 2, description: "The target becomes flexible regardless of its actual size and mass. It can move through areas at least half its size with no penalty for squeezing. It can move through a space at least one-quarter its width using the penalties for squeezing through a space at least half its width" },
    SpellListEntry { key: "Steal Breath", school: Pf1SchoolId::Transmutation, level: 2, description: "You pull the breath from a creature's lungs, dealing damage and leaving it unable to speak, use breath weapons, or cast spells with verbal components. If the target fails its saving throw, it takes 2d6 points of damage, and it cannot speak, use breath weapons, or anything else requiring breathing, and a visible line of swirling air leaves the target's mouth and enters your mouth. If, during the duration, the target moves out of range or line of effect to you, the spell immediately ends. This spell has no effect on creatures that do not need to breathe air." },
    SpellListEntry { key: "Stone Shield", school: Pf1SchoolId::Conjuration, level: 1, description: "A 1-inch-thick slab of stone springs up from the ground, interposing itself between you and an opponent of your choice. The stone shield provides you with cover from that enemy (Core Rulebook 195) until the beginning of your next turn, granting you a +4 bonus to Armor Class and a +2 bonus on Reflex saving throws. If the opponent's attack misses you by 4 or less, the attack strikes the shield instead. The stone shield has hardness 8 and 15 hit points. If the shield is destroyed, the spell ends and the shield crumbles away into nothingness. Spells and effects that damage an area deal damage to the shield. You cannot use this spell if you are not adjacent to a large area of earth or stone such as the ground or a wall." },
    SpellListEntry { key: "Strong Wings", school: Pf1SchoolId::Transmutation, level: 1, description: "The target's wings grow more powerful, causing its fly speed to increase by +10 feet and its maneuverability to improve by one category (to a maximum of good). This increase counts as an enhancement bonus. This spell has no effect on wingless creatures or winged creatures that cannot fly." },
    SpellListEntry { key: "Theft Ward", school: Pf1SchoolId::Abjuration, level: 1, description: "You ward a single object in your possession against theft. You gain a +10 bonus on Perception checks to notice someone trying to take the object from you." },
    SpellListEntry { key: "Toilsome Chant", school: Pf1SchoolId::Enchantment, level: 1, description: "You can cast this spell as part of the action to begin an inspire competence bardic performance. The benefit of inspire competence persists for as long as is necessary to complete the target's next skill check using the chosen skill (up to a maximum of 1 hour per caster level), even if you cease your bardic performance." },
    SpellListEntry { key: "Touch of Combustion", school: Pf1SchoolId::Evocation, level: 1, description: "Your successful melee touch attack causes the target to ignite in a violent burst of flame, dealing 1d6 points of fire damage. If it fails its saving throw, the target also catches on fire (Core Rulebook 444). If the target catches fire, on the first round thereafter, creatures adjacent to it (including you) must each succeed at a Reflex save or take 1d4 points of fire damage." },
    SpellListEntry { key: "Truespeak", school: Pf1SchoolId::Divination, level: 4, description: "You can communicate with any creature that is not mindless. As long as you can be heard, your speech is understandable to all creatures, each of which hears you as though you were conversing in its language or other natural mode of communication, and you hear their responses as though in your own native language. You may ask questions and receive answers, though this spell does not make creatures more friendly or cooperative than normal, and non-sentient creatures may give limited responses. While using truespeak, your language-dependent effects can affect any creature that is not mindless." },
    SpellListEntry { key: "Undine's Curse", school: Pf1SchoolId::Necromancy, level: 1, description: "The target loses its body's natural ability to breathe automatically. As long as it remains conscious and is able to take physical actions, it keeps breathing and is able to function normally. If it is ever unconscious (including sleeping) or unable to take physical actions, it stops breathing and begins to suffocate. Creatures that do not have to breathe are immune to this spell." },
    SpellListEntry { key: "Urban Grace", school: Pf1SchoolId::Transmutation, level: 1, description: "You become one with the city around you, allowing you to move more easily through its crowds and buildings. For the duration of this spell, your base land speed increases by 10 feet. In addition, it does not cost you 2 squares of movement to enter a square with crowds, though the crowd still provides cover to you. This ability does not allow you to enter the space of enemy creatures without making the appropriate Acrobatics check. In addition, you receive a +4 circumstance bonus on Acrobatics checks made to move across uneven urban surfaces, such as roofs and broken pavement, and on Climb checks made to scale walls and other artificial surfaces. Whenever you make an Acrobatics check to make a long jump between two buildings or artificial structures, you are always treated as if you had a running start, regardless of the actual distance traveled." },
    SpellListEntry { key: "Veil of Heaven", school: Pf1SchoolId::Abjuration, level: 1, description: "You surround yourself with a veil of positive energy, making it harder for evil outsiders to harm you. For the duration of this spell, you gain a +2 sacred bonus to AC and on saves. Both of these bonuses apply only against attacks or effects created by outsiders with the evil subtype. You can dismiss this spell as a swift action to deal 1d8 points of damage + 1 point per paladin level to all such outsiders within 5 feet. A Will save halves this damage." },
    SpellListEntry { key: "Village Veil", school: Pf1SchoolId::Illusion, level: 5, description: "You throw an illusion over an area to make creatures that view or interact with it believe it has suffered some great catastrophe or calamity that renders it utterly worthless for their needs. You must set a few general guidelines when casting the spell as to the nature of this disaster (fire, tornado, bandit raid, plague, etc.), after which the illusion fills in the remaining details to make it seem realistic. When casting the spell, you can grant creatures with particular, clearly identifiable physical traits (race, gender, age category, etc.) immunity to this spell. This allows all such eligible creatures to perceive the true nature of the affected area instead of its illusory appearance. Creatures without this immunity that fail their saving throws always perceive the affected area as having absolutely nothing of interest or worth to them. Unless they have reason for suspicion, they always move on without closely investigating the area. Creatures with sufficient reasons for suspicion who do choose to investigate the area gain another saving throw, this one with a +2 bonus, as they enter the village and directly interact with the illusion. You can expand the area of this spell by casting it multiple times. Each time you do, you must effectively \"attach\" the spell to the existing area by using the same disaster and granting the same sorts of creatures immunity to its effects. If you fail to do this, the entire illusion, no matter how large, disappears." },
    SpellListEntry { key: "Vomit Twin", school: Pf1SchoolId::Conjuration, level: 3, description: "Upon casting this spell, you vomit forth a disgusting ooze copy of yourself into a single adjacent square. As long as the twin exists, whenever you take a move action to move, the twin can move as well, although it does not need to follow you and cannot take any other actions. On subsequent rounds, at the start of your turn, you can instantaneously exchange places with your twin, as if using teleport. This is not an action and does not provoke an attack of opportunity. The twin has a speed of 30 feet and provokes attacks of opportunity from movement as normal. It has an AC equal to %1 and %2 hit points. If the twin is reduced to 0 hit points, it is destroyed, although you can create a new one on your turn as a standard action as long as the duration persists. You cannot have more than one vomit twin at a time.|CASTERLEVEL/2+10|CASTERLEVEL" },
    SpellListEntry { key: "Ward of the Season", school: Pf1SchoolId::Abjuration, level: 3, description: "This spell harnesses the power of the seasons to protect the target and grant a number of bonuses. This spell has one of four different effects. The caster of the spell can select any one of the following four effects, but can change the effect as a standard action that reduces the total remaining duration by 1 hour. Spring: The target is wrapped in light vines, culminating in a crown of bright, beautiful flowers. While the spell remains in effect, the target is immune to bleed effects and regains 1 hit point per round whenever below 0 hit points, as long as the target is still alive. This stabilizes the target. For each hit point restored in this way, the spell's total remaining duration is reduced by 1 hour. Summer: The target is surrounded by tiny motes of light. While the spell remains in effect, the target's base speed increases 10 feet. The target may instead increase its base speed by 30 feet for 1 round by reducing the spell's total remaining duration by 1 hour. Fall: A cloak of autumn leaves appears on the target. While the spell remains in effect, the target gains a +2 morale bonus on Fortitude saves. The target can decide to roll twice on any saving throw against disease or poison and take the higher result by reducing the spell's total remaining duration by 1 hour. Winter: A flutter of snow and crisp air surrounds the target. While this spell remains in effect, the target automatically succeeds at Acrobatics skill checks made to avoid falling while moving across slick or narrow surfaces. The target can move freely through difficult terrain for 1 round by reducing the spell's remaining duration by 1 hour. Difficult terrain created by magic affects the target normally." },
    SpellListEntry { key: "Web Bolt", school: Pf1SchoolId::Conjuration, level: 1, description: "You launch a ball of webbing at a target, which must make a save or be affected as if by a web spell occupying only the creature's space. If the creature saves or breaks free of the webbing, the remaining webs dissolve and the square is not considered difficult terrain. The spell has no effect if the target is not on or adjacent to a solid surface that can support the webbing." },
    SpellListEntry { key: "Web Cloud", school: Pf1SchoolId::Conjuration, level: 4, description: "You create a cloud of flame-resistant strands of adhesive webbing that billows and flows much like a cloudkill spell. The cloud moves away from you at a rate of 10 feet per round, rolling along the surface of the ground. Figure out the cloud's new spread each round based on its new point of origin, which is 10 feet farther away from the point of origin where the caster cast the spell. Creatures trapped in the webbing remain trapped even after the cloud passes, but the area the cloud leaves behind does not count as difficult terrain. Because the webbing is heavier than air, it sinks to the lowest level of the land, even pouring down den or sinkhole openings. The cloud of webbing cannot penetrate liquids,nor can it be cast underwater. The cloud otherwise acts like a web spell. A creature in the cloud at the start of its turn must save against the cloud or be affected. The webbing of this spell is flammable (see the web spell), but has fire resistance 5." },
    SpellListEntry { key: "Whispering Lore", school: Pf1SchoolId::Divination, level: 1, description: "Upon casting this spell, you are able to gain knowledge from the land itself. As you walk through the terrain, it whispers information in a language you understand, though the whispering is so rambling it is hard to distinguish useful information. This whispering grants you a +4 insight bonus on a single Knowledge skill type appropriate to the type of terrain you are in. If you are within a cold, desert, forest, jungle, mountain, plains, swamp, or water environment, you gain the bonus on Knowledge (nature) checks. If you are within an underground environment, you gain the bonus on Knowledge (dungeoneering) checks. If you are within an urban environment, you gain the bonus on Knowledge (local) checks. If you are on a plane other than the Material Plane, you gain the bonus on Knowledge (planes) checks. If you enter a new terrain, you lose the previous terrain's skill bonus and gain the new bonus." },
    SpellListEntry { key: "Wind Blades", school: Pf1SchoolId::Transmutation, level: 5, description: "You harden the air around the target into jagged invisible blades that deal damage based on how fast the target moves. On its turn, the target takes 1d6 points of slashing damage if it moves at least 5 feet, plus 1d6 points of slashing damage for each additional 10 feet of movement. Movement that doesn't pass through air (such as burrowing, swimming, or teleportation) doesn't cause this damage. In areas of strong wind (Core Rulebook 439), the target takes damage on its turn, even if it doesn't move. The wind deals 1d8 points of slashing damage for strong wind, plus 1d8 for every wind category above strong. This extra damage does not occur from instantaneous wind effects (such as gust of wind), only from wind effects that last at least 1 round." },
    SpellListEntry { key: "Windy Escape", school: Pf1SchoolId::Transmutation, level: 1, description: "You respond to an attack by briefly becoming vaporous and insubstantial, allowing the attack to pass harmlessly through you. You gain DR 10/magic against this attack and are immune to any poison, sneak attacks, or critical hit effect from that attack. You cannot use windy escape against an attack of opportunity you provoked by casting a spell, using a spelllike ability, or using any other magical ability that provokes an attack of opportunity when used." },
    SpellListEntry { key: "Winter Feathers", school: Pf1SchoolId::Abjuration, level: 1, description: "The target's feathers thicken and fluff up to ward against winter's chill. The target suffers no harm from being in a cold environment, and can exist comfortably in conditions as low as -50 degrees Fahrenheit without having to make Fortitude saves. The creature's equipment is likewise protected. This spell doesn't provide any protection from cold damage, nor does it protect against other environmental hazards associated with cold weather (such as slipping on ice, blindness from snow, and so on). When you cast this spell, you may have the target's feathers turn white for the duration, granting it a +4 circumstance bonus on Stealth checks to hide in ice and snow." },
];

/// Resolves an ARG spell by name. Unlike `rules_tables::acg::spell_list::spell_resolve`,
/// this is not `RuleSetId`-scoped: this book's `rules_tables/` module is
/// compiled only into `src/bin/sd27_gen_book_cache.rs` via `#[path]`
/// (SD-27's per-cycle file-touch partition does not allow-list
/// `src/rules_core/rules_tables/mod.rs`, so this module is not — yet —
/// wired into the shared `RuleSetId` enum; see that binary's own module
/// doc comment for the full reasoning, mirroring
/// `rules_tables::pathfinder_unchained`'s identical precedent).
pub fn spell_resolve(key: &str) -> Option<&'static SpellListEntry> {
    SPELL_LIST.iter().find(|entry| entry.key == key)
}
