//! Package-backed mirror of the compiled `rules_tables` module `ultimate_psionics::cryptic_features` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::ultimate_psionics::cryptic_features::altered_defense_damage_reduction;
pub use rt::ultimate_psionics::cryptic_features::disrupt_pattern_range_feet;
pub use rt::ultimate_psionics::cryptic_features::enhanced_disruption_bonus_dice;
pub use rt::ultimate_psionics::cryptic_features::hidden_pattern_stealth_bonus;
pub use rt::ultimate_psionics::cryptic_features::trapmaker_bonus;
pub use rt::ultimate_psionics::cryptic_features::unchanging_pattern_power_resistance;
pub fn cryptic_power_points_total(level: u8, int_mod: i16) -> Option<i16> {
    if level < 1 {
        return None;
    }
    let ladder = crate::rules_core::rules_catalog::rows::<
        crate::rules_core::rules_data_package::PowerPointsBaseRow,
    >("ultimate_psionics/cryptic_features/cryptic_power_points_total");
    let base = ladder
        .iter()
        .find(|row| row.level == level.min(20))?
        .base_power_points;
    Some(base + (int_mod * i16::from(level)) / 2)
}
pub use rt::ultimate_psionics::cryptic_features::cryptic_max_power_level;
pub use rt::ultimate_psionics::cryptic_features::cryptic_powers_known;
