//! Package-backed mirror of the compiled `rules_tables` module `ultimate_psionics::psychic_warrior_features` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::ultimate_psionics::psychic_warrior_features::eternal_warrior_uses_per_day;
pub use rt::ultimate_psionics::psychic_warrior_features::pathweaving_uses_per_day;
pub use rt::ultimate_psionics::psychic_warrior_features::warriors_path_level;
pub fn psychic_warrior_power_points_total(level: u8, wis_mod: i16) -> Option<i16> {
    if level < 1 {
        return None;
    }
    let ladder =
        crate::rules_core::rules_catalog::rows::<
            crate::rules_core::rules_data_package::PowerPointsBaseRow,
        >("ultimate_psionics/psychic_warrior_features/psychic_warrior_power_points_total");
    let base = ladder
        .iter()
        .find(|row| row.level == level.min(20))?
        .base_power_points;
    Some(base + (wis_mod * i16::from(level)) / 2)
}
pub use rt::ultimate_psionics::psychic_warrior_features::psychic_warrior_max_power_level;
pub use rt::ultimate_psionics::psychic_warrior_features::psychic_warrior_powers_known;
