//! Package-backed mirror of the compiled `rules_tables` module `ultimate_psionics::vitalist_features` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::ultimate_psionics::vitalist_features::collective_minds;
pub use rt::ultimate_psionics::vitalist_features::health_sense_level;
pub use rt::ultimate_psionics::vitalist_features::request_aid_times_per_day;
pub use rt::ultimate_psionics::vitalist_features::steal_health_damage;
pub use rt::ultimate_psionics::vitalist_features::steal_life_dc;
pub use rt::ultimate_psionics::vitalist_features::transfer_wounds_times_per_day;
pub fn vitalist_power_points_total(level: u8, wis_mod: i16) -> Option<i16> {
    if level < 1 {
        return None;
    }
    let ladder = crate::rules_core::rules_catalog::rows::<
        crate::rules_core::rules_data_package::PowerPointsBaseRow,
    >("ultimate_psionics/vitalist_features/vitalist_power_points_total");
    let base = ladder
        .iter()
        .find(|row| row.level == level.min(20))?
        .base_power_points;
    Some(base + (wis_mod * i16::from(level)) / 2)
}
pub use rt::ultimate_psionics::vitalist_features::vitalist_max_power_level;
pub use rt::ultimate_psionics::vitalist_features::vitalist_powers_known;
