//! Inner Sea Races (`SOURCESHORT:ISR`) — `spell`.
//!
//! SD-32 `decisions.md §20`, no_record-to-zero wave: this book's FIRST
//! compiled rule set of any kind, first record family: base spell
//! declarations transcribed from `isr_spells.lst`
//! (`rules_tables::inner_sea_races::spell_list`), generated by the
//! config-driven `src/bin/ingest_spells.rs` (`decisions.md §17`) — same
//! shape as every other book onboarded through that binary, no new logic.

pub mod spell_list;
