//! Package-backed mirror of the compiled `rules_tables` module `mythic_adventures::spell_list` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::mythic_adventures::spell_list::Pf1SchoolId;
pub use rt::mythic_adventures::spell_list::SpellListEntry;
pub static SPELL_LIST: crate::rules_core::rules_catalog::Table<SpellListEntry> =
    crate::rules_core::rules_catalog::Table::new("mythic_adventures/spell_list/SPELL_LIST");
