//! inner_sea_world_guide monster + monster-ability tables, transcribed verbatim
//! from the book's own PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_monster_tables.py inner_sea_world_guide`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst` (which counts `.MOD`/`.COPY` overlays the
//! inventory correctly excludes).
//!
//! Sources, with the line each record was read from carried per row:
//!   * `iswg_races_bestiary.lst` -- 5 monster rows
//!   * `iswg_races.lst` -- 4 monster rows
//!   * `iswg_abilities_race.lst` -- 30 monster-ability rows
//!
//! 5 monster row(s) and 0 ability row(s) of this
//! book are Product Identity and are NOT transcribed -- either because the corpus
//! row DECLARES its name Product Identity (`NAMEISPI:YES`, PCGen's own
//! per-record marker) or because a `pi_screening::PI_BLACKLIST_TERMS` term lands
//! in a field neither the `§24` rename nor the description-redact path can fix
//! (an owner's name, a trait/variable value). A hit confined to the name/key or
//! description alone ships instead -- see the renamed/redacted lists below.
//! Reclassifying is `docs/governance/ogl-pi-blacklist.md` §3's per-book override,
//! an operator
//! decision, not a transcriber's:
//!   * `iswg_races_bestiary.lst:13` (monster row, NAMEISPI:YES)
//!   * `iswg_races.lst:13` (monster row, NAMEISPI:YES)
//!   * `iswg_races_bestiary.lst:14` (monster row, NAMEISPI:YES)
//!   * `iswg_races.lst:14` (monster row, NAMEISPI:YES)
//!   * `iswg_races.lst:16` (monster row, NAMEISPI:YES)
//!
//! 3 ability row(s) of this book have their OWN name/key match
//! a `pi_screening::PI_BLACKLIST_TERMS` term -- `decisions.md §24`'s "the name
//! itself is PI" case. Each ships under a Codex-generated NEUTRAL name/key
//! derived ONLY from `(kind, book, source_file, source_line)` -- never from the
//! original name, not even transformed -- `scripts/codex_neutral_name.py`. Per
//! `§24b`-4, the divergence record below stops at the coordinate and the reason;
//! the original string is never written here:
//!   * `iswg_abilities_race.lst:24` -> Codex-Named Unit (monster_ability_inner_sea_world_guide_iswg_abilities_race_lst_24) (name_pi_blocked)
//!   * `iswg_abilities_race.lst:25` -> Codex-Named Unit (monster_ability_inner_sea_world_guide_iswg_abilities_race_lst_25) (name_pi_blocked)
//!   * `iswg_abilities_race.lst:27` -> Codex-Named Unit (monster_ability_inner_sea_world_guide_iswg_abilities_race_lst_27) (name_pi_blocked)
//!
//! 1 ability row(s) of this book carry Product Identity in
//! their `description` field ONLY (declared `DESCISPI:YES`, or an undeclared
//! `pi_screening::PI_BLACKLIST_TERMS` term found by scanning) -- `description`
//! (and its `%N` variables) SHIP REDACTED to `shape_b_v1::REDACTED_PI_MARKER`
//! rather than dropped, because a description (unlike a name) can be redacted
//! and the record still works. Reclassifying is
//! `docs/governance/ogl-pi-blacklist.md` §3's per-book override, an operator
//! decision, not a transcriber's:
//!   * `iswg_abilities_race.lst:27` (Codex-Named Unit (monster_ability_inner_sea_world_guide_iswg_abilities_race_lst_27))
//!
//! 16 further ability row(s) in this book are ORPHANS -- no monster
//! row here claims them, so they SHIP with `owners: &[]` rather than being
//! dropped (`decisions.md §20`: an un-ingested row's shape cannot be measured,
//! and Gate 1's DoD needs every unit's shape measured). `list_monster_catalog`
//! only ever walks a monster's OWN `ability_keys`, so an owner-less record here
//! reaches no screen -- reachability is NOT claimed for these, and each key is
//! pinned as a named, provable non-reach in `reach_gate.rs::
//! UNREACHED_RECORD_FINDINGS`, never silently assumed reachable:
//!   * `iswg_abilities_race.lst:24`
//!   * `iswg_abilities_race.lst:25`
//!   * `iswg_abilities_race.lst:27`
//!   * `iswg_abilities_race.lst:50`
//!   * `iswg_abilities_race.lst:51`
//!   * `iswg_abilities_race.lst:52`
//!   * `iswg_abilities_race.lst:81`
//!   * `iswg_abilities_race.lst:82`
//!   * `iswg_abilities_race.lst:83`
//!   * `iswg_abilities_race.lst:86`
//!   * `iswg_abilities_race.lst:87`
//!   * `iswg_abilities_race.lst:90`
//!   * `iswg_abilities_race.lst:92`
//!   * `iswg_abilities_race.lst:96`
//!   * `iswg_abilities_race.lst:97`
//!   * `iswg_abilities_race.lst:98`

use crate::rules_core::rules_tables::monster_chassis::{MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterSpellLikeAbility, MonsterStatBlock, NaturalAttack, Speed, StatAdjustment};

/// Every inner_sea_world_guide monster stat block (9 rows).
pub(super) static MONSTERS: &[MonsterStatBlock] = &[
    MonsterStatBlock {
        key: "Rat (Donkey)",
        name: "Rat (Donkey)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 20 }],
        race_type: Some("Animal"),
        race_subtype: None,
        challenge_rating: Some("1/4"),
        monster_class: Some("Animal:1"),
        source_page: Some("p.254"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        ability_keys: &[],
        external_ability_refs: &["Scent"],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "iswg_races_bestiary.lst",
        source_line: 8,
    },
    MonsterStatBlock {
        key: "Spider (Drain)",
        name: "Spider (Drain)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        race_type: Some("Vermin"),
        race_subtype: None,
        challenge_rating: Some("1/4"),
        monster_class: Some("Vermin:1"),
        source_page: Some("p.254"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        ability_keys: &[],
        external_ability_refs: &["Giant Spider ~ Poison"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "iswg_races_bestiary.lst",
        source_line: 9,
    },
    MonsterStatBlock {
        key: "Aluum",
        name: "Aluum",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Construct"),
        race_subtype: None,
        challenge_rating: Some("10"),
        monster_class: Some("Construct:14"),
        source_page: Some("p.306"),
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: Some("2d10") }],
        ability_keys: &["Aluum ~ Immunity to Magic", "Aluum ~ Paralysis", "Aluum ~ Soul Shriek"],
        external_ability_refs: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 16 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CHA", amount: -10 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "iswg_races.lst",
        source_line: 10,
    },
    MonsterStatBlock {
        key: "Fennec (Firefoot)",
        name: "Fennec (Firefoot)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        race_type: Some("Animal"),
        race_subtype: None,
        challenge_rating: Some("1/3"),
        monster_class: Some("Animal:1"),
        source_page: Some("p.254"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        ability_keys: &[],
        external_ability_refs: &["Scent"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "iswg_races_bestiary.lst",
        source_line: 10,
    },
    MonsterStatBlock {
        key: "Calikang",
        name: "Calikang",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Monstrous Humanoid"),
        race_subtype: None,
        challenge_rating: Some("12"),
        monster_class: Some("Monstrous Humanoid:15"),
        source_page: Some("p.307"),
        natural_attacks: &[NaturalAttack { name: "Slam (Primary)", damage_dice: Some("1d6") }, NaturalAttack { name: "Slam (1H wpn)", damage_dice: Some("1d6") }, NaturalAttack { name: "Slam (2H wpns)", damage_dice: Some("1d6") }, NaturalAttack { name: "Slam (3H wpns)", damage_dice: Some("1d6") }, NaturalAttack { name: "Slam (4H wpns)", damage_dice: Some("1d6") }, NaturalAttack { name: "Slam (5H wpns)", damage_dice: Some("1d6") }],
        ability_keys: &["Calikang ~ Breath Weapon", "Calikang ~ Defensive Slam", "Calikang ~ Energy Absorption", "Calikang ~ Fast Healing", "Calikang ~ Suspend Animation", "Constant ~ Magic Weapon"],
        external_ability_refs: &["Air Walk ~ Constant", "True Seeing ~ Constant", "Water Walk ~ Constant"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 14 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CON", amount: 10 }, StatAdjustment { ability: "INT", amount: -2 }, StatAdjustment { ability: "CHA", amount: 6 }],
        has_spell_like_abilities: true,
        sla_cl_token: Some("(max(TL,1))"),
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("(max(TL,1))"), spell: "Lightning Bolt", save_dc_token: Some("13+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("(max(TL,1))"), spell: "Chain Lightning", save_dc_token: Some("16+CHA") }],
        source_file: "iswg_races.lst",
        source_line: 11,
    },
    MonsterStatBlock {
        key: "Gecko (Giant)",
        name: "Gecko (Giant)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        race_type: Some("Animal"),
        race_subtype: None,
        challenge_rating: Some("2"),
        monster_class: Some("Animal:3"),
        source_page: Some("p.254"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        ability_keys: &[],
        external_ability_refs: &["Grab", "Scent"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "iswg_races_bestiary.lst",
        source_line: 11,
    },
    MonsterStatBlock {
        key: "Charau-ka",
        name: "Charau-ka",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        race_type: Some("Humanoid"),
        race_subtype: Some("Charau-ka"),
        challenge_rating: Some("2"),
        monster_class: Some("Humanoid (Reflex):3"),
        source_page: Some("p.308"),
        natural_attacks: &[NaturalAttack { name: "Bite (Primary)", damage_dice: Some("1d3") }, NaturalAttack { name: "Bite (Weapon equipped)", damage_dice: Some("1d3") }],
        ability_keys: &["Charau-ka ~ Shrieking Frenzy", "Charau-ka ~ Thrown-Weapon Mastery"],
        external_ability_refs: &["Scent"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -2 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "iswg_races.lst",
        source_line: 12,
    },
    MonsterStatBlock {
        key: "Shark (Jigsaw)",
        name: "Shark (Jigsaw)",
        size: Some("L"),
        speeds: &[Speed { mode: "Swim", feet: 60 }],
        race_type: Some("Animal"),
        race_subtype: Some("Aquatic"),
        challenge_rating: Some("2"),
        monster_class: Some("Animal:4"),
        source_page: Some("p.255"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        ability_keys: &[],
        external_ability_refs: &["Shark ~ Keen Scent"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "CHA", amount: -8 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "iswg_races_bestiary.lst",
        source_line: 12,
    },
    MonsterStatBlock {
        key: "Dragon (Spine)",
        name: "Dragon (Spine)",
        size: Some("G"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Dragon"),
        race_subtype: Some("Earth"),
        challenge_rating: Some("16"),
        monster_class: Some("Dragon:16"),
        source_page: Some("p.312"),
        natural_attacks: &[NaturalAttack { name: "Tail", damage_dice: Some("2d8") }, NaturalAttack { name: "Spine", damage_dice: Some("2d8") }, NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        ability_keys: &["Spine Dragon ~ Breath Weapon", "Spine Dragon ~ Ray Deflection", "Spine Dragon ~ Spines"],
        external_ability_refs: &["Immunity to Sonic", "Resistance to Cold", "Resistance to Electricity", "Resistance to Fire"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 22 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 18 }, StatAdjustment { ability: "INT", amount: 6 }, StatAdjustment { ability: "WIS", amount: 12 }, StatAdjustment { ability: "CHA", amount: 8 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("(max(TL,1))"), spell: "Spike Growth", save_dc_token: Some("13+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("(max(TL,1))"), spell: "Spike Stones", save_dc_token: Some("14+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("(max(TL,1))"), spell: "Telekinesis", save_dc_token: Some("15+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("(max(TL,1))"), spell: "Telekinetic Sphere", save_dc_token: Some("18+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("(max(TL,1))"), spell: "Wall of Force", save_dc_token: None }],
        source_file: "iswg_races.lst",
        source_line: 15,
    },
];

/// Every inner_sea_world_guide monster-ability record (30 rows).
pub(super) static MONSTER_ABILITIES: &[MonsterAbilityRecord] = &[
    MonsterAbilityRecord {
        key: "Aluum ~ Immunity to Magic",
        name: "Immunity to Magic",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["Immunity"],
        description: Some("An aluum is immune to any spell or spell-like ability that allows spell resistance. In addition, certain spells and effects function differently against the creature. A magical attack that uses negative energy deals no damage, but speeds up the aluum's attacks and movment as if it were under the effects of a haste spell for 1d6 rounds. A magical attack that uses positive energy slows the aluum as if by a slow spell for 1d6 rounds and dispels any haste effects currently affecting it. Magic jar confuses the creature for 1d6 rounds."),
        description_variables: &[],
        source_page: Some("p.307"),
        owners: &["Aluum"],
        source_file: "iswg_abilities_race.lst",
        source_line: 7,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Aluum ~ Paralysis",
        name: "Paralysis",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The touch of an aluum paralyzes living creatures that fail a DC %1 Fortitude save for 1d4 minutes."),
        description_variables: &["10+TL/2+CON"],
        source_page: Some("p.307"),
        owners: &["Aluum"],
        source_file: "iswg_abilities_race.lst",
        source_line: 8,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Aluum ~ Soul Shriek",
        name: "Soul Shriek",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("As a free action every 1d4 rounds, the aluum's enslaved souls may emit a keening wail in a 15-ft. cone. Creatures in the cone take 10d6 points of sonic damage and are stunned for 1 round. A DC %1 Will save halves the damage and negates the stun effect. This is a sonic mind-affecting effect."),
        description_variables: &["8+TL/2+CON"],
        source_page: Some("p.307"),
        owners: &["Aluum"],
        source_file: "iswg_abilities_race.lst",
        source_line: 9,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Calikang ~ Fast Healing",
        name: "Fast Healing",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["ModifyHp"],
        description: Some("A calikang regains hit points at %1 per round. Fast healing does not restore hit points lost from starvation, thirst, or suffocation, nor does it allow a creature to regrow lost body parts or allow lost body parts to be reattached. Fast healing continues to function (even at negative hit points) until a creature dies, at which point the effects of fast healing end immediately."),
        description_variables: &["FastHealingRate"],
        source_page: Some("p.308"),
        owners: &["Calikang"],
        source_file: "iswg_abilities_race.lst",
        source_line: 12,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Calikang ~ Defensive Slam",
        name: "Defensive Slam",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A calikang gains a cumulative +1 shield bonus to its AC for each of its arms that does not wield a manufactured weapon, to a maximum of +4 for four hands. A calikang can make slam attacks with these arms without losing this AC bonus."),
        description_variables: &[],
        source_page: Some("p.308"),
        owners: &["Calikang"],
        source_file: "iswg_abilities_race.lst",
        source_line: 13,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Calikang ~ Energy Absorption",
        name: "Energy Absorption",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A spell that inflicts energy damage that is defeated by the calikang's SR or immunity to electricity is absorbed into its body, healing it for an amount of damage equal to the absorbed spell's caster level and granting an additional daily use of its breath weapon."),
        description_variables: &[],
        source_page: Some("p.308"),
        owners: &["Calikang"],
        source_file: "iswg_abilities_race.lst",
        source_line: 14,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Calikang ~ Breath Weapon",
        name: "Breath Weapon",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("%1-ft. line, %2d6 energy damage, Reflex DC %3 half, usable %4/day. A calikang can choose what kind of energy damage its breath weapon inflicts when it uses this ability. Calikangs are particularly adept at using electricity in this manner, and inflict %5 additional points of damage when they elect to inflict electricity damage with their breath weapon."),
        description_variables: &["BreathWeaponLine", "BreathWeaponDice", "BreathWeaponDC", "BreathWeaponTimes", "HD"],
        source_page: Some("p.308"),
        owners: &["Calikang"],
        source_file: "iswg_abilities_race.lst",
        source_line: 15,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Calikang ~ Suspend Animation",
        name: "Suspend Animation",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("As a full-round action, a calikang can enter a state of suspended animation, freezing in place and becoming motionless. It remains aware of its surroundings. In this state, the calikang is immune to disease, inhaled toxins, poison, starvation, and thirst, and receives a +4 bonus on all Fortitude saves. The calikang can exit this state as an immediate action - if it does so to attack a foe or initiate combat, it gains a +4 insight bonus on its Initiative check."),
        description_variables: &[],
        source_page: Some("p.308"),
        owners: &["Calikang"],
        source_file: "iswg_abilities_race.lst",
        source_line: 16,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Charau-ka ~ Shrieking Frenzy",
        name: "Shrieking Frenzy",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("1/day, a charau-ka can enter a state of shrieking frenzy as a free action. While in this state, the charau-ka automatically fails Stealth checks and cannot speak or cast spells that use verbal components (or use items that require command words to activate), but functions as if under the effects of a haste spell. The charau-ka can continue shrieking for up to 3 rounds, after which it is staggered for 1 round."),
        description_variables: &[],
        source_page: Some("p.309"),
        owners: &["Charau-ka"],
        source_file: "iswg_abilities_race.lst",
        source_line: 19,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Charau-ka ~ Thrown-Weapon Mastery",
        name: "Thrown-Weapon Mastery",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Charau-ka are masters of thrown weapons. All charau-ka gain Throw Anything as a bonus feat. In addition, a charau-ka gains a +1 racial bonus on all thrown weapons, and their threat range for thrown weapons is doubled, as if the charau-ka possessed the Improve Critical feat for all thrown weapons. This effect doesn't stack with any other effect that expands the threat range of a weapon."),
        description_variables: &[],
        source_page: Some("p.309"),
        owners: &["Charau-ka"],
        source_file: "iswg_abilities_race.lst",
        source_line: 20,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Codex-Named Unit (monster_ability_inner_sea_world_guide_iswg_abilities_race_lst_24)",
        name: "Codex-Named Unit (monster_ability_inner_sea_world_guide_iswg_abilities_race_lst_24)",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Bubonic Plague: Great claw--injury; save Fort DC %1; onset immediate; frequency 1/day; effect 1d4 damage and target is fatigued; cure 2 consecutive saves."),
        description_variables: &["DoUDiseaseDC"],
        source_page: Some("p.310"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 24,
        codex_generated_name: true,
        rename_reason: Some("name_pi_blocked"),
        rename_coordinate: Some("inner_sea_world_guide:iswg_abilities_race.lst:24"),
    },
    MonsterAbilityRecord {
        key: "Codex-Named Unit (monster_ability_inner_sea_world_guide_iswg_abilities_race_lst_25)",
        name: "Codex-Named Unit (monster_ability_inner_sea_world_guide_iswg_abilities_race_lst_25)",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("One of the daughter's hands is a tremendous scythe-shaped claw. This attack inflicts x4 damage on a critical hit, and is treated as an evil weapon for the purposes of penetrating damage reduction."),
        description_variables: &[],
        source_page: Some("p.310"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 25,
        codex_generated_name: true,
        rename_reason: Some("name_pi_blocked"),
        rename_coordinate: Some("inner_sea_world_guide:iswg_abilities_race.lst:25"),
    },
    MonsterAbilityRecord {
        key: "Codex-Named Unit (monster_ability_inner_sea_world_guide_iswg_abilities_race_lst_27)",
        name: "Codex-Named Unit (monster_ability_inner_sea_world_guide_iswg_abilities_race_lst_27)",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: Some("[redacted PI]"),
        description_variables: &[],
        source_page: Some("p.310"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 27,
        codex_generated_name: true,
        rename_reason: Some("name_pi_blocked"),
        rename_coordinate: Some("inner_sea_world_guide:iswg_abilities_race.lst:27"),
    },
    MonsterAbilityRecord {
        key: "Sandpoint Devil ~ Bay",
        name: "Bay",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("When the Sandpoint Devil screams as a standard action, all creatures within a 300-ft.-radius spread must succeed at a DC %1 Will save or become panicked for 2d5 rounds. This is a sonic, mind-affecting fear effect. Whether or not the save is successful, creatures within the effect are immune to the Sandpoint Devil's bay for 24 hours thereafter."),
        description_variables: &["10+(HD/2)+CHA"],
        source_page: Some("p.312"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 50,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Sandpoint Devil ~ Hellfire Breath",
        name: "Hellfire Breath",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Once every 1d4 rounds, the Sandpoint Devil can unleash a blast of infernal flame from its mouth as a standard action. This hellfire fills a 30-ft. cone and causes 10d6 points of fire damage (Reflex DC %1 half). Anyone who takes damage from this breath weapon must also make a DC %1 Wo;; save to avoid becoming cursed by the infernal flames--those who become cursed take a -4 penalty on all attack rolls, saving throws, and skill checks for a number of days equal to the damage taken--during this time, the victim's skin appears to be horribly burned in places regardless of any healing applied. This curse effect functions at caster level %2."),
        description_variables: &["10+(HD/2)+CON", "HD"],
        source_page: Some("p.312"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 51,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Sandpoint Devil ~ Kick",
        name: "Kick",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The Sandpoint Devil's hoof attacks are primary attacks that deal bludgeoning and slashing damage."),
        description_variables: &[],
        source_page: Some("p.312"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 52,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Spine Dragon ~ Breath Weapon",
        name: "Breath Weapon",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Once every 1d4 rounds as a standard action, a spine dragon can emit a devastating shriek of powerful sonic energy in a %1-ft. cone. Creatures caught in this cone take %2d6 sonic damage and are permanently deafened. A DC %3 Reflex save halves the damage and negates the deafness. This sonic damage is particularly devastating to constructs--they take a -4 penalty to save against its effects, and if they fail the save, they are staggered for 1d4 rounds as well."),
        description_variables: &["BreathWeaponCone", "BreathWeaponDice", "BreathWeaponDC"],
        source_page: Some("p.313"),
        owners: &["Dragon (Spine)"],
        source_file: "iswg_abilities_race.lst",
        source_line: 55,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Spine Dragon ~ Ray Deflection",
        name: "Ray Deflection",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A spine dragon's scales deflect rays and magic missile spells, rendering the spine dragon immune to such effects. There's a 30%% chance a deflected effect reflects back in full force at the caster; otherwise it is simply negated."),
        description_variables: &[],
        source_page: Some("p.313"),
        owners: &["Dragon (Spine)"],
        source_file: "iswg_abilities_race.lst",
        source_line: 56,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Spine Dragon ~ Spines",
        name: "Spines",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A spine dragon's body is covered with long, crystalling spines. It can fire up to four of these spines/round as a full-attack action (or one as a standard action). A creature that attacks a spine dragon with a melee weapon, unarmed strike, or natural weapon must make a DC %1 Reflex save or take 2d8+%2 points of piercing damage from the spines."),
        description_variables: &["10+(HD/2)+DEX", "STR"],
        source_page: Some("p.313"),
        owners: &["Dragon (Spine)"],
        source_file: "iswg_abilities_race.lst",
        source_line: 57,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Treerazer ~ Regeneration",
        name: "Regeneration",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["ModifyHP"],
        description: Some("You are difficult to kill. You heal damage at %1 points per round, and you cannot die as long as your regeneration is still functioning (although you still fall unconscious when your hit points are below 0). Good aligned damage causes your regeneration to stop functioning on the round following the attack: you cannot heal any damage and can die normally. Attack forms that don't deal hit point damage are not healed by regeneration. Regeneration also does not restore hit points lost from starvation, thirst, or suffocation. You can regrow lost portions of you body and can reattach severed limbs or body parts if they are brought together within 1 hour of severing. Severed parts that are not reattached wither and die normally."),
        description_variables: &["RegenerationRate"],
        source_page: Some("p.315"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 81,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Treerazer ~ Aura of Corruption",
        name: "Aura of Corruption",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Aura"],
        description: Some("Treerazer exudes an aura of corruption to a radius of 120 ft. This aura causes plants to grow hideous, sprouting thorns, twisting, and becoming fungoid in nature. Creatures with woodland stride or freedom of movement can move through this fungal bloom with ease. Living creatures within Treerazer's aura of corruption must make a DC %1 Fortitude save each round or their flesh grows pasty and clammy as tendrils of diseased plant matter and fungal growth sprout from it. This condition persists as long as the creature remains within Treerazer's aura of corruption and for 1 minute thereafter. While suffering the effects of this aura, the living creature is treated as a plant for the purposes of spells and effects that harm or otherwise inconvenience plant creatures more than other creatures. The corruption does not otherwise impart plant traits to creatures."),
        description_variables: &["10+(HD/2)+CON", "TYPE=Base"],
        source_page: Some("p.315"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 82,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Treerazer ~ Defoliation",
        name: "Defoliation",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("As a standard action once every 1d4 rounds, Treerazer can exude a pulse of defoliating energy in a 30-ft.-radius spread. This pulse appears as a wave of sickly green energy, and causes all plants and plant creatures in the area to blacken and wither. Such creatures take 20d10 points of damage and 1d8 points of Strength drain, or half with a successful DC %1 Fort save. A plant that isn't a creature (such as a tree or a shrub) doesn't receive a save and immediately withers and dies. Treerazer can choose to exclude any number of plants in the area from this effect, and generally does so to preserve twisted and corrupted plants and fungus."),
        description_variables: &["10+(HD/2)+CON", "TYPE=Base"],
        source_page: Some("p.315"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 83,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Nascent Demon Lord ~ Aligned Strike",
        name: "Aligned Strike",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A nascent demon lord's natural weapons, as well as any weapon it wields, are treated as chaotic, epic, and evil for the purpose of resolving damage reduction."),
        description_variables: &[],
        source_page: Some("p.315"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 86,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Nascent Demon Lord ~ Grant Spells",
        name: "Grant Spells",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Nascent demon lords can grant spells to their worshipers. Granting spells does not require any specific action on the nascent demon lord's behalf. All nascent demon lords grant access to the domains of Chaos and Evil--in addition, they grant access to two other domains and a favored weapon that vary according to the nascent demon lord's themes and interests."),
        description_variables: &[],
        source_page: Some("p.315"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 87,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Constant ~ Desecrate",
        name: "Desecrate",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &["Aura"],
        description: Some("You can use desecrate, as per the spell, as a constant ability. Constant spell-like abilities function at all times but can be dispelled. Constant spell-like abilities can be reactivated a as a swift action."),
        description_variables: &[],
        source_page: Some("p.265"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 90,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Constant ~ Magic Weapon",
        name: "Magic Weapon",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &[],
        description: Some("You can use magic weapon, as per the spell, as a constant ability. Constant spell-like abilities function at all times but can be dispelled. Constant spell-like abilities can be reactivated a as a swift action."),
        description_variables: &[],
        source_page: Some("p.310"),
        owners: &["Calikang"],
        source_file: "iswg_abilities_race.lst",
        source_line: 91,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Constant ~ Water Breathing",
        name: "Water Breathing",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &[],
        description: Some("You can use water breathing, as per the spell, as a constant ability. Constant spell-like abilities function at all times but can be dispelled. Constant spell-like abilities can be reactivated a as a swift action."),
        description_variables: &[],
        source_page: Some("p.368"),
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 92,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Clockwork ~ Winding",
        name: "Winding",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The construct must be wound with a special key in order to function. As a general rule, a fully wound clockwork can remain active for 1 day/HD, but shorter or longer durations are possible."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 96,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Clockwork ~ Swift Reactions",
        name: "Swift Reactions",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Clockwork constructs generally react much more swiftly than other constructs. They gain Improved Initiative and Lightning Reflexes as bonus feats, and gain a +2 dodge bonus to AC."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 97,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Clockwork ~ Difficult to Create",
        name: "Difficult to Create",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: Some("Increase the time and gp cost required to create a clockwork by 50%% over normal."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "iswg_abilities_race.lst",
        source_line: 98,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
];
