//! Inner Sea World Guide shared spell list.
//!
//! Generated by `src/bin/ingest_spells.rs` (config-driven, all
//! books) from the real `pathfinder/paizo/campaign_setting/inner_sea_world_guide/iswg_spells.lst` corpus. Record coverage: every
//! real, active (non-`.MOD`, non-`.COPY=`) base spell declaration.
//!
//! `level` is the minimum level across the record's `CLASSES:`/
//! `DOMAINS:` token(s), `None` for the rare record that states
//! neither (never fabricated -- these land `text-complete`, not
//! `ingested-magnitude`, via `v06_work_inventory::classify`'s
//! existing `Some(false)` branch).
//!
//! `school`/`description` are `Option` because a minority of
//! records carry neither token of their own on this book's base
//! row.

/// The full 9-school PF1 spell-school enum, mirroring every other book's
/// own copy exactly.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Pf1SchoolId {
    Abjuration,
    Conjuration,
    Divination,
    Enchantment,
    Evocation,
    Illusion,
    Necromancy,
    Transmutation,
    Universal,
}

impl Pf1SchoolId {
    pub fn from_corpus_str(raw: &str) -> Option<Self> {
        match raw {
            "Abjuration" => Some(Pf1SchoolId::Abjuration),
            "Conjuration" => Some(Pf1SchoolId::Conjuration),
            "Divination" => Some(Pf1SchoolId::Divination),
            "Enchantment" => Some(Pf1SchoolId::Enchantment),
            "Evocation" => Some(Pf1SchoolId::Evocation),
            "Illusion" => Some(Pf1SchoolId::Illusion),
            "Necromancy" => Some(Pf1SchoolId::Necromancy),
            "Transmutation" => Some(Pf1SchoolId::Transmutation),
            "Universal" => Some(Pf1SchoolId::Universal),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpellListEntry {
    pub key: &'static str,
    pub school: Option<Pf1SchoolId>,
    pub level: Option<u8>,
    pub description: Option<&'static str>,
}

pub const SPELL_LIST: &[SpellListEntry] = &[
    SpellListEntry { key: "Ancestral Memory", school: Some(Pf1SchoolId::Divination), level: Some(4), description: Some("Open your mind to vaste experiences of your ancestors. Gain +5 insight bonus to Intelligence-based skill checks. (70+CASTERLEVEL)%% chance of obtaining specific ancestral memory [GM discretion] to assist in overcoming problem.") },
    SpellListEntry { key: "Covetous Aura", school: Some(Pf1SchoolId::Abjuration), level: Some(5), description: Some("Anytime a harmless spell of 3rd level or lower is cast within the area of effect, you may choose to immediately gain the benefit. Doing so ends the covetous aura and the spell still affects the intended target.") },
    SpellListEntry { key: "Dirge of the Victorious Knights", school: Some(Pf1SchoolId::Illusion), level: Some(6), description: Some("[redacted PI]") },
    SpellListEntry { key: "Harrowing", school: Some(Pf1SchoolId::Divination), level: Some(3), description: Some("[redacted PI]") },
    SpellListEntry { key: "Infernal Healing", school: Some(Pf1SchoolId::Conjuration), level: Some(1), description: Some("Anoint a wounded creature with devil's blood or unholy water giving it fast healing 1. Does not repair silver or good damage. Target detects as evil for the duration.") },
    SpellListEntry { key: "Infernal Healing (Greater)", school: Some(Pf1SchoolId::Conjuration), level: Some(4), description: Some("Anoint a wounded creature with devil's blood or unholy water giving it fast healing 4. Does not repair silver or good damage. Target detects as an evil cleric for the duration.") },
    SpellListEntry { key: "Interplanetary Teleport", school: Some(Pf1SchoolId::Conjuration), level: Some(9), description: Some("Instantly transport you + (CASTERLEVEL/3) willing creature(s) [Medium-sized] to a specific or random destination on the target world. You do not need to have seen your destination, though you must have a solid grasp of to which world you wish to travel.") },
    SpellListEntry { key: "Lover's Vengeance", school: Some(Pf1SchoolId::Enchantment), level: Some(3), description: Some("Inspire self or recent lover to vengeful rage against enemy who has wronged you. When in combat with that enemy, gain benefit of rage spell against them for (CASTERLEVEL) rounds [double if enemy is an ex-lover].") },
    SpellListEntry { key: "Teleport Trap", school: Some(Pf1SchoolId::Abjuration), level: Some(7), description: Some("Ward an area, redirecting all teleportation into or out of the area to a specific open space on a solid surface within the area on a failed Will save. The teleport attempt fails and this spell ends if the save is successful. A teleport trap can exclude a category of creatures.") },
    SpellListEntry { key: "Unbreakable Heart", school: Some(Pf1SchoolId::Enchantment), level: Some(1), description: Some("Creature gains +4 morale bonus on saves against mind-affecting effects that rely on negative emotions or that would force him to harm an ally. Supresses such effects already in place.") },
    SpellListEntry { key: "Vermin Shape I", school: Some(Pf1SchoolId::Transmutation), level: Some(3), description: Some("Assume the form of any Small or Medium creature of the vermin type, gaining some abilities and a +2 resistance bonus to saves against mind-affecting spells.") },
    SpellListEntry { key: "Vermin Shape II", school: Some(Pf1SchoolId::Transmutation), level: Some(4), description: Some("Assume the form of any Tiny to Large creature of the vermin type, gaining many abilities and a +4 resistance bonus to saves against mind-affecting spells.") },
    SpellListEntry { key: "Summon Mantis", school: Some(Pf1SchoolId::Conjuration), level: None, description: Some("This spell summons your choice of one extraplanar advanced fiendish giant mantis, 1d3 fiendish giant mantises, or 1d4+1 giant mantises. They appear where you designate and act immediately, on your turn. You can mentally direct the actions of these summoned vermin as a free action. All mantises summoned by this spell-like ability are blood red, and gain no racial bonus on Stealth checks in forests. Creatures cannot be summoned into an environment that cannot support them. If you use this spell to summon fiendish mantises, it is an evil spell.") },
    SpellListEntry { key: "Quickened Dispel Magic (Greater)", school: Some(Pf1SchoolId::Abjuration), level: None, description: Some("This spell functions like dispel magic, except that it can end more than one spell on a target and it can be used to target multiple creatures.") },
    SpellListEntry { key: "Summon Demons (Nascent Demon Lord)", school: Some(Pf1SchoolId::Conjuration), level: None, description: Some("Calls any demon or combination of demons whose total combined CR is 20 or lower. This ability always works, and is equivalent to a 9th-level spell.") },
    SpellListEntry { key: "Animal Growth (Reptiles Only)", school: Some(Pf1SchoolId::Transmutation), level: Some(5), description: Some("The target reptile grows to twice its normal size and eight times its normal weight.") },
    SpellListEntry { key: "Animal Shapes (Reptiles Only)", school: Some(Pf1SchoolId::Transmutation), level: Some(8), description: Some("You change the form of up to (CASTERLEVEL) willing reptiles into an animal of your choice.") },
];
