//! horror_adventures monster + monster-ability tables, transcribed verbatim
//! from the book's own PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_monster_tables.py horror_adventures`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst` (which counts `.MOD`/`.COPY` overlays the
//! inventory correctly excludes).
//!
//! Sources, with the line each record was read from carried per row:
//!   * `ha_races.lst` -- 3 monster rows
//!   * `ha_abilities_race.lst` -- 71 monster-ability rows
//!
//! 65 further ability row(s) in this book are ORPHANS -- no monster
//! row here claims them, so they SHIP with `owners: &[]` rather than being
//! dropped (`decisions.md §20`: an un-ingested row's shape cannot be measured,
//! and Gate 1's DoD needs every unit's shape measured). `list_monster_catalog`
//! only ever walks a monster's OWN `ability_keys`, so an owner-less record here
//! reaches no screen -- reachability is NOT claimed for these, and each key is
//! pinned as a named, provable non-reach in `reach_gate.rs::
//! UNREACHED_RECORD_FINDINGS`, never silently assumed reachable:
//!   * `ha_abilities_race.lst:204`
//!   * `ha_abilities_race.lst:207`
//!   * `ha_abilities_race.lst:209`
//!   * `ha_abilities_race.lst:210`
//!   * `ha_abilities_race.lst:211`
//!   * `ha_abilities_race.lst:212`
//!   * `ha_abilities_race.lst:213`
//!   * `ha_abilities_race.lst:243`
//!   * `ha_abilities_race.lst:246`
//!   * `ha_abilities_race.lst:247`
//!   * `ha_abilities_race.lst:251`
//!   * `ha_abilities_race.lst:252`
//!   * `ha_abilities_race.lst:253`
//!   * `ha_abilities_race.lst:254`
//!   * `ha_abilities_race.lst:256`
//!   * `ha_abilities_race.lst:257`
//!   * `ha_abilities_race.lst:258`
//!   * `ha_abilities_race.lst:259`
//!   * `ha_abilities_race.lst:260`
//!   * `ha_abilities_race.lst:261`
//!   * `ha_abilities_race.lst:262`
//!   * `ha_abilities_race.lst:263`
//!   * `ha_abilities_race.lst:266`
//!   * `ha_abilities_race.lst:273`
//!   * `ha_abilities_race.lst:274`
//!   * `ha_abilities_race.lst:289`
//!   * `ha_abilities_race.lst:290`
//!   * `ha_abilities_race.lst:291`
//!   * `ha_abilities_race.lst:292`
//!   * `ha_abilities_race.lst:293`
//!   * `ha_abilities_race.lst:294`
//!   * `ha_abilities_race.lst:297`
//!   * `ha_abilities_race.lst:298`
//!   * `ha_abilities_race.lst:299`
//!   * `ha_abilities_race.lst:300`
//!   * `ha_abilities_race.lst:301`
//!   * `ha_abilities_race.lst:302`
//!   * `ha_abilities_race.lst:305`
//!   * `ha_abilities_race.lst:308`
//!   * `ha_abilities_race.lst:311`
//!   * `ha_abilities_race.lst:312`
//!   * `ha_abilities_race.lst:313`
//!   * `ha_abilities_race.lst:314`
//!   * `ha_abilities_race.lst:315`
//!   * `ha_abilities_race.lst:318`
//!   * `ha_abilities_race.lst:321`
//!   * `ha_abilities_race.lst:324`
//!   * `ha_abilities_race.lst:325`
//!   * `ha_abilities_race.lst:326`
//!   * `ha_abilities_race.lst:329`
//!   * `ha_abilities_race.lst:330`
//!   * `ha_abilities_race.lst:331`
//!   * `ha_abilities_race.lst:332`
//!   * `ha_abilities_race.lst:333`
//!   * `ha_abilities_race.lst:334`
//!   * `ha_abilities_race.lst:337`
//!   * `ha_abilities_race.lst:338`
//!   * `ha_abilities_race.lst:339`
//!   * `ha_abilities_race.lst:340`
//!   * `ha_abilities_race.lst:341`
//!   * `ha_abilities_race.lst:342`
//!   * `ha_abilities_race.lst:345`
//!   * `ha_abilities_race.lst:346`
//!   * `ha_abilities_race.lst:347`
//!   * `ha_abilities_race.lst:348`

use crate::rules_core::rules_tables::monster_chassis::{MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterStatBlock, NaturalAttack, Speed, StatAdjustment};

/// Every horror_adventures monster stat block (3 rows).
pub(super) static MONSTERS: &[MonsterStatBlock] = &[
    MonsterStatBlock {
        key: "Hive Larva Swarm",
        name: "Hive Larva Swarm",
        size: Some("F"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Climb", feet: 10 }],
        race_type: Some("Aberration"),
        race_subtype: Some("Hive|Swarm"),
        challenge_rating: Some("5"),
        monster_class: Some("Aberration:7"),
        source_page: Some("p.236"),
        natural_attacks: &[NaturalAttack { name: "Swarm", damage_dice: Some("2d6") }],
        ability_keys: &["Hive Larva Swarm ~ Infest", "Hive Larva Swarm ~ Poison"],
        external_ability_refs: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -10 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "CHA", amount: -10 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "ha_races.lst",
        source_line: 3,
    },
    MonsterStatBlock {
        key: "Hive Queen",
        name: "Hive Queen",
        size: Some("H"),
        speeds: &[Speed { mode: "Walk", feet: 50 }, Speed { mode: "Climb", feet: 20 }],
        race_type: Some("Aberration"),
        race_subtype: Some("Hive"),
        challenge_rating: Some("10"),
        monster_class: Some("Aberration:15"),
        source_page: Some("p.236"),
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: Some("1d10") }, NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Tail Slap", damage_dice: None }],
        ability_keys: &["Hive Queen ~ Egg Layer", "Hive Queen ~ Telepathy"],
        external_ability_refs: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 18 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: 8 }, StatAdjustment { ability: "INT", amount: 4 }, StatAdjustment { ability: "WIS", amount: 8 }, StatAdjustment { ability: "CHA", amount: -4 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "ha_races.lst",
        source_line: 4,
    },
    MonsterStatBlock {
        key: "Hive Warrior",
        name: "Hive Warrior",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 20 }],
        race_type: Some("Aberration"),
        race_subtype: Some("Hive"),
        challenge_rating: Some("5"),
        monster_class: Some("Aberration:8"),
        source_page: Some("p.237"),
        natural_attacks: &[NaturalAttack { name: "Acid Spit", damage_dice: Some("7d6") }, NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }, NaturalAttack { name: "Tail Slap", damage_dice: None }],
        ability_keys: &["Hive Warrior ~ Acid Spit", "Hive Warrior ~ Rending Mandibles"],
        external_ability_refs: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 6 }, StatAdjustment { ability: "CHA", amount: -6 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "ha_races.lst",
        source_line: 5,
    },
];

/// Every horror_adventures monster-ability record (71 rows).
pub(super) static MONSTER_ABILITIES: &[MonsterAbilityRecord] = &[
    MonsterAbilityRecord {
        key: "Traits Output ~ Deep One",
        name: "Deep One Traits",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Creatures with the deep one subtype have low-light vision."),
        description_variables: &[],
        source_page: Some("p.233"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 204,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Traits Output ~ Hive",
        name: "Hive Traits",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Immunity to acid. &nl; Blind - A hive creature is blind. It is immune to gaze attacks, visual effects, illusions, and other attack forms that rely on sight. Unlike other aberrations, a hive creature doesn't have darkvision. &nl; Blindsense 60 feet. &nl; Blindsight 10 feet. &nl; Corrosive Blood (Ex) A hive creature's blood is highly caustic. Every time the hive creature is damaged by a piercing or slashing weapon, the attacking creature takes acid damage according to the creature's size (or double damage if the attack is a critical hit). Using a reach weapon does not endanger the attacker in this way. If the hive creature has the swallow whole ability, it adds this damage to its swallow whole damage. - Medium or smaller 1d4 damage;Large 1d6 damage; Huge 1d8 damage; Gargantuan 2d6 damage; Colossal 2d8 damage. &nl; Death Throes (Ex) When a hive creature dies, it exudes a pool of its corrosive blood in the space it occupies. This pool deals 1d6 points of acid damage per Hit Die of the hive creature for 3 rounds to objects and creatures in those squares (Reflex half). This acid damages whatever surface it is on, and if it deals enough damage to destroy the surface, the acid falls down to any subsequent floor below and continues to deal damage. The save DC is Constitution-based. &nl; Heat Adaptability (Ex) Hive creatures are considered to always be under the effect of endure elements with regard to hot climates. &nl; Hive Mind (Ex) Hive creatures have no language of their own, instead communicating simple concepts via pheromone discharge and body language that other creatures with the hive subtype understand. This ability functions within line of sight. If one hive creature is able to act in the surprise round of combat, all other hive creatures in line of sight can also act, and a hive creature isn't flanked unless all hive creatures within line of sight are flanked. &nl; A hive creature doesn't need to eat, drink, or sleep."),
        description_variables: &[],
        source_page: Some("p.233"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 207,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive ~ Blind",
        name: "Blind",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: Some("A hive creature is blind. It is immune to gaze attacks, visual effects, illusions, and other attack forms that rely on sight. Unlike other aberrations, a hive creature doesn't have darkvision."),
        description_variables: &[],
        source_page: Some("p.233"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 209,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive ~ Corrosive Blood",
        name: "Corrosive Blood",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A hive creature's blood is highly caustic. Every time the hive creature is damaged by a piercing or slashing weapon, the attacking creature takes %1d%2 acid damage (or double damage if the attack is a critical hit). Using a reach weapon does not endanger the attacker in this way. If the hive creature has the swallow whole ability, it adds this damage to its swallow whole damage."),
        description_variables: &["HiveCorrosiveBloodDamageDie", "HiveCorrosiveBloodDamageSize"],
        source_page: Some("p.233"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 210,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive ~ Death Throes",
        name: "Death Throes",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("When a hive creature dies, it exudes a pool of its corrosive blood in the space it occupies. This pool deals %1d6 points of acid damage for 3 rounds to objects and creatures in those squares (Reflex DC %2 half). This acid damages whatever surface it is on, and if it deals enough damage to destroy the surface, the acid falls down to any subsequent floor below and continues to deal damage."),
        description_variables: &["HD", "10+HD/2+CON"],
        source_page: Some("p.233"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 211,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive ~ Heat Adaptability",
        name: "Heat Adaptability",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Hive creatures are considered to always be under the effect of endure elements with regard to hot climates."),
        description_variables: &[],
        source_page: Some("p.233"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 212,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive ~ Hive Mind",
        name: "Hive Mind",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Hive creatures have no language of their own, instead communicating simple concepts via pheromone discharge and body language that other creatures with the hive subtype understand. This ability functions within line of sight. If one hive creature is able to act in the surprise round of combat, all other hive creatures in line of sight can also act, and a hive creature isn't flanked unless all hive creatures within line of sight are flanked."),
        description_variables: &[],
        source_page: Some("p.233"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 213,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Accursed Creature ~ Cursed",
        name: "Cursed",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["AccursedCreature"],
        description: Some("The creature is under a particular curse. Natural attacks cause bestow curse (DC %1, CL %2) on a successful hit (this can inflict any effect of bestow curse or spread the creature's personal curse)"),
        description_variables: &["10+HD/2+CHA", "HD"],
        source_page: Some("p.248"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 243,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Bestial Werewolf ~ Change Shape",
        name: "Change Shape",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["BestialWerewolf"],
        description: Some("A bestial werewolf does not gain a hybrid form, and its animal form is that of a dire wolf, rather than an ordinary wolf. Otherwise, this ability functions identically to the change shape ability granted by the lycanthrope template."),
        description_variables: &[],
        source_page: Some("p.251"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 246,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Bestial Werewolf ~ Feral Counter",
        name: "Feral Counter",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["BestialWerewolf"],
        description: Some("While in animal form, the first time each round that a creature damages a bestial werewolf, the bestial werewolf can take an attack of opportunity against the creature. The werewolf must threaten the triggering creature to use this ability."),
        description_variables: &[],
        source_page: Some("p.251"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 247,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dread Lord ~ Landlocked",
        name: "Landlocked",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["DreadLord"],
        description: Some("A dread lord's power is drawn directly from its domain, which has a radius of %1 miles, centered on a fixed point of some significance to the dread lord. The dread lord loses all benefits of this template when not within its domain."),
        description_variables: &["5*TL"],
        source_page: Some("p.234"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 251,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dread Lord ~ One with the Land",
        name: "One with the Land",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["DreadLord"],
        description: Some("A dread lord can shape the hazardous landscapes formed as a consequence of its domain's creation to its will. It can replace any normal or supernatural hazard present in its domain with another hazard, but the process takes 24 hours, during which time neither hazard functions. The combined CR of all hazards found within a lord's domain (that is, the CR of a hypothetical encounter with all of the hazards at once) can't exceed twice its Hit Dice, and it cannot create any hazards whose CR exceeds its own. A dread lord's affinity with the land grants it a +2 bonus on all Will saves."),
        description_variables: &[],
        source_page: Some("p.235"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 252,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Cursed Lord ~ Immortal Curse",
        name: "Immortal Curse",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["CursedLord"],
        description: Some("Even death can't free a cursed lord from its domain, and cursed lords that are killed return to life 24 hours later. When a cursed lord is created, a specific condition is determined by the source of the cursed lord's curse, which must be performed in order for the cursed lord to be permanently slain. The exact means vary with each cursed lord, are difficult but never impossible, and should be created specifically for each cursed lord by the GM. Examples include disinterring the corpse of the lord's slain lover and reburying it outside the domain, stealing vast treasures from the lord's castle and returning them to the poor people they were stolen from, or destroying a dam to set free a river the cursed lord has prevented from flowing through its lands."),
        description_variables: &[],
        source_page: Some("p.235"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 253,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Cursed Lord ~ Trapped",
        name: "Trapped",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["CursedLord"],
        description: Some("A cursed lord is unable to leave its domain by any means, and effects such as plane shift, shadow walk, teleport, and even wish fail. If its domain is bordered by dread fog (see page 161), the mists inevitably guide the cursed lord back to its domain after 1 hour."),
        description_variables: &[],
        source_page: Some("p.235"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 254,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dread Lord ~ All-Seeing",
        name: "All-Seeing",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &["DreadLordSpecialPower"],
        description: Some("Nothing happens in the dread lord's realm without the dread lord becoming aware. It can use speak with animals, speak with plants, and stone tell as spell-like abilities each three times per day. It can use clairaudience/clairvoyance as a spell-like ability three times per day, and the spell's range extends to any place in its domain."),
        description_variables: &[],
        source_page: Some("p.234"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 256,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dread Lord ~ Dream Dominion",
        name: "Dream Dominion",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["DreadLordSpecialPower"],
        description: Some("The dread lord has dominion over even the dreams of its subjects. It can use dream and nightmare as spell-like abilities, each once per day, but targeting only creatures within its domain. Once per week it can attempt to gain control of a creature whose dreams it affects in this way. If the target fails a secondary Will saving throw (DC %1), the dread lord enslaves it, as per dominate monster, in addition to the dream or nightmare spell-like ability's normal effects."),
        description_variables: &["10+TL/2+CHA"],
        source_page: Some("p.235"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 257,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dread Lord ~ Fear Aura",
        name: "Fear Aura",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["DreadLordSpecialPower", "Aura"],
        description: Some("The dread lord is terrifying to behold. Any creature within a 60-foot radius that sees or hears the dread lord must succeed at a Will save (DC %1) or be shaken for as long as it is within the aura, and for 1 minute thereafter. Whether or not the save is successful, that creature cannot be affected again by the same dread lord's fear aura for 24 hours. This is a mind-affecting fear effect."),
        description_variables: &["10+TL/2+CHA"],
        source_page: Some("p.235"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 258,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dread Lord ~ Magical Mastery",
        name: "Magical Mastery",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["DreadLordSpecialPower"],
        description: Some("The dread lord draws magical power from its domain. It treats its caster level as 2 higher for the purposes of spells and spell- like abilities it casts, and the saving throw DCs of such spells and spell-like abilities increase by 1."),
        description_variables: &[],
        source_page: Some("p.235"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 259,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dread Lord ~ Master of the Four Winds",
        name: "Master of the Four Winds",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &["DreadLordSpecialPower"],
        description: Some("The dread lord can control the weather within its domain. It can use fog cloud and gust of wind as spell-like abilities each three times per day. It can use control weather as a spell-like ability once per day. It can use control winds as a spell-like ability once per day."),
        description_variables: &[],
        source_page: Some("p.235"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 260,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dread Lord ~ Physical Mastery",
        name: "Physical Mastery",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["DreadLordSpecialPower"],
        description: Some("The dread lord draws strength and deftness from its domain. It gains a +4 profane bonus to its Strength, Dexterity, and Constitution scores."),
        description_variables: &[],
        source_page: Some("p.235"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 261,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dread Lord ~ Plant Affinity",
        name: "Plant Affinity",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &["DreadLordSpecialPower"],
        description: Some("The dread lord's control over its lands extends to the very plants. It can use entangle as a spell-like ability at will, and plant growth as a spell-like ability once per day. It can use tree stride as a spell-like ability at will. It can use liveoak as a spell-like ability once per day."),
        description_variables: &[],
        source_page: Some("p.235"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 262,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dread Lord ~ Unquestioned Ruler",
        name: "Unquestioned Ruler",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &["DreadLordSpecialPower"],
        description: Some("The dread lord's subjects naturally bend to its will. It can use charm animal, charm person, and detect thoughts as spell-like abilities at will. It can use dominate animal, dominate person, and mass suggestion as spell-like abilities three times per day."),
        description_variables: &[],
        source_page: Some("p.235"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 263,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Familial Lich ~ Familial Possession",
        name: "Familial Possession",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["FamilialLich"],
        description: Some("When a familial lich is destroyed, its spirit departs its body and seeks out the lich's nearest living relative, a process that takes 1d10 days. The familial lich then tries to possess the relative, as per greater possession (OA) (the caster level is equal to the familial lich's HD, and the save DC is Charisma-based). If the relative succeeds at her save, she becomes permanently immune to this ability, and the familial lich must spend another 1d10 days searching for the next-nearest living relative, repeating the process until it succeeds or until no such relatives remain and it is destroyed instead. If the relative fails her saving throw, the familial lich's spirit takes root in her body. The familial lich's consciousness remains within the relative even after the greater possession effect ends, and it is able to share her senses. It can use greater possession on her once per day thereafter. If the relative fails on three consecutive saving throws to resist, the familial lich's spirit takes over, and she physically and mentally transforms into the familial lich permanently. Even if the relative continues succeeding, it is impossible to remove a familial lich without extremely powerful magic once it has taken root. Only lineal ancestors or descendants of the familial lich, as well as siblings, are eligible targets for possession (aunts, uncles, nieces, nephews, cousins, and so forth are immune)."),
        description_variables: &[],
        source_page: Some("p.251"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 266,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hellbound Creature ~ Contract Bound",
        name: "Contract Bound",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["HellboundCreature"],
        description: Some("The creature has signed a contract of service in return for this template. The devil must reveal its nature as a creature of Hell when it offers a contract, and it can't hide the details of the contract in any way. The creature must enter the agreement willingly (without magical compulsion). Usually the creature must perform one or more tasks for the devil, and in exchange the creature gains the template's abilities, whether immediately, after a specific amount of time, or once the tasks are completed. The contract always includes a clause that damns the creature's soul to Hell when the creature dies, with credit for the act and possession of the soul going to the devil signing the contract. When the creature dies, its soul is automatically imprisoned in a gem, which immediately appears in Hell as one of the devil's belongings. If the devil is dead when the creature dies, the creature's soul is destroyed, and can't be restored to life except by miracle or wish. If the creature fails to perform the tasks in the allotted time, its soul is still damned and the devil is not obligated to provide the promised abilities. Many contracts state that the devil, its agents, and its allies will not attempt to kill the creature. This doesn't protect against all devils, but does offer the creature a measure of protection against treachery from the signatory devil. Breaking a contract with a devil is difficult and dangerous. Furthermore, as long as the contract remains in effect, a slain victim can't be restored to life after death except by a miracle or wish. If the devilbound creature is restored to life, the devil immediately senses the name and location (as discern location) of the creature responsible."),
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 273,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hellbound Creature ~ Hellbound Summon",
        name: "Hellbound Summon",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &["HellboundCreature"],
        description: Some("Once per day, the hellbound creature can summon one lemure one bearded devil or 1d3 lemures one erinyes, 1d3 bearded devils, or 1d4+1 lemures one bone devil, 1d3 erinyes, or 1d4+1 bearded devils one barbed devil, 1d3 bone devils, or 1d4+1 erinyes one ice devil, 1d3 barbed devils, or 1d4+1 bone devils with a 100%% chance of success."),
        description_variables: &[],
        source_page: Some("p.249"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 274,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive Larva Swarm ~ Infest",
        name: "Infest",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["HiveLarvaSwarm"],
        description: Some("A hive larva swarm can enter the body of a single Small or larger helpless living creature. When it does so, a portion of the swarm enters a creature's mouth and gestates for 1d4 minutes. The gestated larvae ravage the host for 24 hours, during which time the infested creature falls unconscious and can't be woken by any means. During this period the larvae are vulnerable to expulsion by remove disease (DC %1). If successful, the hive larvae die inside of the host, dealing another 1d6 points of acid damage. In some cases, metabolized hive larvae corpses can infect the creature with the hive corruption (see page 24). After 24 hours, the hive larvae achieve symbiosis. The host awakens feeling healthy but hungry. Spells such as diagnose disease and Heal checks used to detect disease no longer detect the hive infestation, and the host creature is now treated as both its original creature type and an aberration for purposes of spells and effects (whichever is worse). A successful DC 25 Knowledge (dungeoneering) check can identify the symbiosis. If the host dies at this point, the larval infestation dies as well. However, if the host is then returned from the dead, the larvae are returned to life as well. The swarm fully matures 2d12 hours after symbiosis. By this point, there is no way to save the host short of a miracle or wish spell. Each round for 2d12 rounds, the host suffers agonizing pain and must succeed at a Fortitude save (DC %1) or be nauseated for 1 round. On each failed save, the host takes 4d6 points of damage as the mature hive creature forcibly separates itself. At the end of the 2d12 rounds, or after the host is slain by the damage, a fully formed hive creature (usually a hive warrior) explodes from within, destroying the host's body."),
        description_variables: &["10+HD/2+CON"],
        source_page: Some("p.236"),
        owners: &["Hive Larva Swarm"],
        source_file: "ha_abilities_race.lst",
        source_line: 277,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive Larva Swarm ~ Poison",
        name: "Poison",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["HiveLarvaSwarm"],
        description: Some("Swarm-injury; save Fort DC %1; frequency 1/round for 6 rounds; effect 1d4 Strength; cure 2 consecutive saves."),
        description_variables: &["HD+10+HD/2+CON"],
        source_page: Some("p.236"),
        owners: &["Hive Larva Swarm"],
        source_file: "ha_abilities_race.lst",
        source_line: 278,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive Queen ~ Egg Layer",
        name: "Egg Layer",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["HiveQueen"],
        description: Some("Once per week, a hive queen can lay a cluster of eggs, which hatch into 2d6 hive larvae swarms after 1d4 days."),
        description_variables: &[],
        source_page: Some("p.237"),
        owners: &["Hive Queen"],
        source_file: "ha_abilities_race.lst",
        source_line: 281,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive Queen ~ Telepathy",
        name: "Telepathy",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["HiveQueen"],
        description: Some("A hive queen can communicate telepathically with any creature with the hive subtype within 1 mile. This telepathy conveys empathic concepts rather than true language."),
        description_variables: &[],
        source_page: Some("p.237"),
        owners: &["Hive Queen"],
        source_file: "ha_abilities_race.lst",
        source_line: 282,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive Warrior ~ Acid Spit",
        name: "Acid Spit",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["HiveWarrior"],
        description: Some("A hive warrior can spray acid as a ranged touch attack out to a maximum range of 20 feet. Creatures struck by this spray takes %1d6 acid damage. Additionally, creatures damaged by a hive warrior's acid spit continue to take the same amount of acid damage for the next 1d3 rounds. A successful Reflex save (DC %2) halves the initial damage and negates the ongoing damage."),
        description_variables: &["HD", "10+HD/2+DEX"],
        source_page: Some("p.237"),
        owners: &["Hive Warrior"],
        source_file: "ha_abilities_race.lst",
        source_line: 285,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Hive Warrior ~ Rending Mandibles",
        name: "Rending Mandibles",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["HiveWarrior"],
        description: Some("When a hive warrior confirms a critical hit with its bite, it deals equal damage to the creature's armor."),
        description_variables: &[],
        source_page: Some("p.237"),
        owners: &["Hive Warrior"],
        source_file: "ha_abilities_race.lst",
        source_line: 286,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Implacable Stalker ~ Sense Fear",
        name: "Sense Fear",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["ImplacableStalker", "Senses"],
        description: Some("An implacable stalker is able to sense the fear of nearby living creatures. This functions similarly to blindsight, with a range of 120 feet, except it only allows the implacable stalker to detect creatures that are currently experiencing any level of fear ranging from spooked to horrified (see page 10). Additionally, this ability allows the implacable stalker to detect such creatures even through solid barriers, but 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt blocks it."),
        description_variables: &[],
        source_page: Some("p.238"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 289,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Implacable Stalker ~ Terrifying Inevitability",
        name: "Terrifying Inevitability",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["ImplacableStalker"],
        description: Some("An implacable stalker is even more difficult to kill when in the presence of fear. As long as the implacable stalker is able to see or hear a creature currently experiencing any level of fear ranging from spooked to horrified (see page 10), it gains fast healing %1, its damage reduction increases to 10/-, and it gains spell resistance %2."),
        description_variables: &["HD", "16+CR"],
        source_page: Some("p.238"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 290,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Implacable Stalker ~ Fear Aura",
        name: "Fear Aura",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["ImplacableStalker", "Aura"],
        description: Some("Creatures that have at least 5 fewer Hit Dice than the implacable stalker must succeed at a Will save (DC %1) or become frightened for 1 minute if they come within 60 feet of it. Even if they succeed at their saves, they gain the shaken condition for as long as they remain within 60 feet of the implacable stalker, and for 1 round thereafter. All other creatures within this radius must succeed at a Will save or become shaken for as long as they remain within 60 feet of the implacable stalker, and for 1 round thereafter. A creature that successfully saves cannot be affected again by the same implacable stalker's aura until the creature has left the aura and reentered it. This is a mind-affecting fear effect."),
        description_variables: &["10+HD/2+CHA"],
        source_page: Some("p.238"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 291,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Implacable Stalker ~ Gory Display",
        name: "Gory Display",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["ImplacableStalker"],
        description: Some("Whenever an implacable stalker kills a sentient living creature, as a swift action, it can revel in the kill, shredding its victim's corpse in a gruesome display of power. If it does, it chooses one of the following benefits -- gain a +4 morale bonus to Strength and Dexterity for 1 minute, regain a single use of a spell-like ability that it can normally use three or more times per day, or immediately heal a number of hit points equal to its Hit Dice. Alternatively, instead of any of these benefits, the implacable stalker can cause a single creature within 60 feet to become more vulnerable to fear. Creatures affected in this way lose any immunity to fear they may have. If the creature did not possess immunity to fear, it takes a -4 penalty on saving throws to resist fear effects, and all Intimidate checks attempted against it receive a +4 circumstance bonus. These effects last for 10 minutes. Finally, if the creature is currently immune to the implacable stalker's fear aura because it succeeded at a previous saving throw, it loses that immunity."),
        description_variables: &[],
        source_page: Some("p.239"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 292,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Implacable Stalker ~ Nightmare Resurrection",
        name: "Nightmare Resurrection",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["ImplacableStalker"],
        description: Some("When an implacable stalker dies, it creates a psychic imprint on the mind of each intelligent creature within 60 feet that witnessed its death. Each week, such creatures are subject to a nightmare effect (DC %1; the normal modifiers for nightmare based on knowledge and connection do not apply). In this nightmare, the creature is hunted and slain by the implacable stalker (for GMs using the nightmare dreamscape rules on page 162, these nightmares always have the \"being chased\" nightmare feature). A creature that succeeds at three consecutive saving throws to resist the effect is freed from it. If any creature fails at three consecutive saving throws to resist the nightmare, the implacable stalker returns to life, as per true resurrection. If its corpse has been completely destroyed, it returns to life in a random location within 5 miles of the creature that failed to resist the nightmare effects. Once the implacable stalker is returned to life, the psychic imprint fades from all creatures still affected by it."),
        description_variables: &["10+HD/2+CHA"],
        source_page: Some("p.239"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 293,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Implacable Stalker ~ Right Behind You",
        name: "Right Behind You",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &["ImplacableStalker"],
        description: Some("As a swift action, an implacable stalker can teleport to an unoccupied space, which must be adjacent to a creature the stalker is aware of that has the shaken, frightened, or panicked condition. The implacable stalker can travel a maximum distance of 480 feet with each use of this ability, and must wait 1d6 rounds between each use. Additionally, if the implacable stalker travels at least 40 feet, any shaken, frightened, or panicked creature it arrives adjacent to is denied its Dexterity bonus to AC against the implacable stalker's attacks until the beginning of the implacable stalker's next turn."),
        description_variables: &[],
        source_page: Some("p.239"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 294,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Kyton (Apostle) ~ Agonizing Prayer",
        name: "Agonizing Prayer",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["ApostleKyton"],
        description: Some("As a full-round action that provokes attacks of opportunity, an apostle kyton can orate a prayer so profane that it causes any non-kyton listening to erupt in bleeding wounds. Any non-kyton listener must succeed at a Will save (DC %1) or take %2d6 points of nonlethal damage, take bleed damage as if struck by the apostle kyton's bleeding touch, and become staggered for 1 round. Creatures that succeed on this save halve the nonlethal damage and negate the staggered effect, but they still take the bleed damage. A creature that has taken nonlethal damage greater than or equal to its current hit points is not normally rendered unconscious by this ability, but such a creature is still helpless, rendering it susceptible to the apostle kyton's seductive oration ability. This is a sonic pain effect."),
        description_variables: &["10+HD/2+CHA", "HD"],
        source_page: Some("p.240"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 297,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Kyton (Apostle) ~ Bleeding Touch",
        name: "Bleeding Touch",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["ApostleKyton"],
        description: Some("An apostle kyton that touches a creature deals 1 point of damage plus %1d6 points of bleed damage. If an apostle kyton attacks with natural or manufactured weapons, its weapons also deal this bleed damage."),
        description_variables: &["HD/10"],
        source_page: Some("p.240"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 298,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Kyton (Apostle) ~ Seductive Oration",
        name: "Seductive Oration",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["ApostleKyton"],
        description: Some("An apostle kyton has a unique perspective due to her transition into her current form. As a full-round action that provokes attacks of opportunity, an apostle kyton can speak to the pleasures and wonders it experienced during its transformation. Any creature that listens to this speech for 1 continuous minute must succeed at a Will save (DC %1) or take %2d6 points of Wisdom damage. %3 sanity damage. A creature that succeeds at its save can't be affected by that apostle kyton's seductive oration ability for 24 hours. After failing the save to resist the apostle kyton's seductive oration, the target begins to question the definitions of morality, physicality, and life. Once per week, as long as the affected creature remains in communication with the apostle kyton, it must attempt a saving throw against seductive oration again or have its alignment shift one step toward lawful evil and take 1d6 additional points of Wisdom damage. %4 additional points of sanity damage. The save DC increases by 1 per consecutive week of contact with the apostle kyton. A successful save prevents the alignment shift. A creature can't take damage from seductive oration more than once per week, even if it encounters multiple apostle kytons. When the target's alignment completely shifts to lawful evil (or if the target is lawful evil when first seduced), the target must immediately succeed at a Will save (with the same DC as seductive oration, including any increases from extended contact) or gain a greater madness (see page 182). If the target is turned lawful evil, the greater madness it gains is in addition to any madness it might gain from the sanity damage itself. Creatures that are driven insane by an apostle kyton often eventually become broken souls (Bestiary 4 p24), but some rare individuals gain the shadowbound corruption (see page 34) or even transform into apostle kytons themselves."),
        description_variables: &["10+HD/2+CHA", "1+HD/8", "CR/2", "CR/2"],
        source_page: Some("p.241"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 299,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Kyton (Apostle) ~ Unnerving Gaze",
        name: "Unnerving Gaze",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["ApostleKyton"],
        description: Some("An apostle kyton's unnerving gaze (see the kyton subtype) causes those who fail their saving throws to be fascinated by the apostle kyton. The apostle kyton's seductive oration doesn't break this fascination effect, but other attacks break the effect as normal."),
        description_variables: &[],
        source_page: Some("p.241"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 300,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Kyton (Apostle) ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &["ApostleKyton"],
        description: None,
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 301,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Kyton (Apostle) ~ Shadow Traveler",
        name: "Shadow Traveler",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["ApostleKyton"],
        description: Some("When an apostle kyton uses shadow walk, she moves at 100 miles per hour."),
        description_variables: &[],
        source_page: Some("p.241"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 302,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Lich Creature ~ Touch Attack",
        name: "Touch Attack",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["LichCreature"],
        description: Some("A lich creature can perform a touch attack that deals 1d8+%1 points to delivr its paralyzing touch"),
        description_variables: &["HD/2"],
        source_page: Some("p.249"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 305,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Lycanthropic Creature ~ Change Shape",
        name: "Change Shape",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["LycanthropicCreature"],
        description: Some("A lycanthropic creature has two forms--a humanoid form and a hybrid form. Equipment does not meld with the new form between humanoid and hybrid form. A lycanthropic creature can assume hybrid form as a full-round action by making a DC 15 Constitution check, or humanoid form as a move action."),
        description_variables: &[],
        source_page: Some("p.249"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 308,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Moonbound Werewolf ~ Moonbound",
        name: "Moonbound",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["MoonboundWerewolf"],
        description: Some("A moonbound werewolf gains benefits and drawbacks based on the current phase of the moon. For the purposes of this ability, the moon is in one of four phases at any given time: full, nearly full, new, and other. The moon is full for the 3-day period when the moon appears the largest in the sky, it is nearly full for 4 days before it is full and 4 days afterward, and it is new for a 3-day period when the moon appears the darkest in the sky. The \"other\" phase encompasses the rest of each month. GMs who need to randomly determine the phase of the moon can use the table below. [d8-Moon Phase] 1=New; 2-5=Other; 6-7=Nearly full; 8=Full"),
        description_variables: &[],
        source_page: Some("p.251"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 311,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Moonbound Werewolf ~ Moonbound (Full Moon)",
        name: "Moonbound (Full Moon)",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["MoonboundWerewolf"],
        description: Some("Regardless of whether it is a natural or afflicted lycanthrope, a moonbound werewolf in animal or hybrid form gains DR 10/silver and magic when the moon is full. When the moon is full, the moonbound werewolf also gains +4 Strength and +4 Constitution in human form, and the bonuses he gains in hybrid and animal forms increase to +6. These changes increase its CR by 1."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 312,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Moonbound Werewolf ~ Moonbound (Near Full Moon)",
        name: "Moonbound (Near Full Moon)",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["MoonboundWerewolf"],
        description: Some("Regardless of whether it is a natural or afflicted lycanthrope, a moonbound werewolf in animal or hybrid form gains DR 10/silver when the moon is near full. When the moon is near full, the moonbound werewolf also gains +2 Strength and +2 Constitution in human form, and the bonuses he gains in hybrid and animal forms increase to +4. These changes increase its CR by 1."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 313,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Moonbound Werewolf ~ Moonbound (Other Moon)",
        name: "Moonbound (Other Moon)",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["MoonboundWerewolf"],
        description: Some("Regardless of whether it is a natural or afflicted lycanthrope, a moonbound werewolf in animal or hybrid form gains DR 5/silver during other phases."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 314,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Moonbound Werewolf ~ Moonbound (New Moon)",
        name: "Moonbound (New Moon)",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["MoonboundWerewolf"],
        description: Some("A moonbound werewolf in animal or hybrid form loses its damage reduction during a new moon. During this time, the moonbound werewolf also suffers -2 Strength and -2 Constitution in all forms, instead of the normal +2 bonuses. These changes decrease its CR by 1."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 315,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Possessed Creature ~ Two Minds",
        name: "Two Minds",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["PossessedCreature"],
        description: Some("After failing a save against a mind-affecting effect, a possessed creature can reroll the save, but the spirit takes control if the second save succeeds. A possessed creature always acts on the surprise round."),
        description_variables: &[],
        source_page: Some("p.250"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 318,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Promethean Creature ~ Promethean Metabolism",
        name: "Promethean Metabolism",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["PrometheanCreature"],
        description: Some("A promethean creature gains a +4 bonus on saving throws vs. poison and disease, is immune to emotion effects except those that produce rage, hatred, or anger. Promethean creatures automatically stabilize when below 0 hp. A promethean creature doesn't need to eat, sleep, or drink."),
        description_variables: &[],
        source_page: Some("p.250"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 321,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Shadowbound Creature ~ Weaver of Lies",
        name: "Weaver of Lies",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["ShadowboundCreature"],
        description: Some("A shadowbound creature can't gain morale bonuses."),
        description_variables: &[],
        source_page: Some("p.250"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 324,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Shadowbound Creature ~ Regretful Gaze",
        name: "Regretful Gaze",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["ShadowboundCreature"],
        description: Some("Gaze attack (shaken 1 round, 30 ft., Will negates, DC %1)"),
        description_variables: &["10+HD/2+CHA"],
        source_page: Some("p.250"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 325,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Shadowbound Creature ~ Refuge in Pain",
        name: "Refuge in Pain",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["ShadowboundCreature"],
        description: Some("After taking %1 points of damage in a single attack, a shadowbound creature gains a +2 profane bonus on attack rolls, damage rolls, saving throws, and skill checks for 1 round"),
        description_variables: &["HD*3"],
        source_page: Some("p.250"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 326,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Trompe l'Oeil ~ Armor Class",
        name: "Armor Class",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["TrompeLOeil"],
        description: Some("If a trompe l'oeil is depicted wearing armor or a shield, these items are masterwork and gain an enhancement bonus (or equivalent armor special abilities) when worn by the trompe l'oeil, as indicated in the table. If the trompe l'oeil is depicted without armor, add the armor enhancement bonus to its natural armor bonus instead. Armor and shields equipped by a trompe l'oeil melt into puddles of nonmagical paint when the creature is destroyed. [Armor Enhancement Bonus already added as natural armor bonus/Shield Enhancement Bonus is %1"),
        description_variables: &["TrompeLOeilShield"],
        source_page: Some("p.242"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 329,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Trompe l'Oeil ~ Attacks",
        name: "Attacks",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: None,
        traits: &["TrompeLOeil"],
        description: Some("A trompe l'oeil retains all weapon proficiencies and natural weapons. If it's depicted wielding any manufactured weapons, the weapons are masterwork and gain a +%1 enhancement bonus (or equivalent weapon special abilities) when wielded by it. The bonus is based on its HD. A trompe l'oeil's weapons melt into puddles of nonmagical paint when the creature is destroyed."),
        description_variables: &["TrompeLOeilWeapon"],
        source_page: Some("p.242"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 330,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Trompe l'Oeil ~ Rejuvenation",
        name: "Rejuvenation",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["TrompeLOeil"],
        description: Some("When a trompe l'oeil is destroyed, it reforms 2d4 days later on its original canvas (see page 243). The only way to permanently destroy a trompe l'oeil is to destroy the original canvas before the creature reforms."),
        description_variables: &[],
        source_page: Some("p.242"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 331,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Trompe l'Oeil ~ Skills",
        name: "Skills",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["TrompeLOeil"],
        description: Some("A trompe l'oeil gains a +10 racial bonus on Disguise checks to appear as the base creature. It also receives a +5 bonus on Bluff checks to pretend to be the base creature and a +5 bonus on Stealth checks to appear as part of a painting."),
        description_variables: &[],
        source_page: Some("p.242"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 332,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Trompe l'Oeil ~ Autotelic",
        name: "Autotelic",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["TrompeLOeil"],
        description: Some("A trompe l'oeil uses its Charisma score in place of its Constitution score when calculating hit points, Fortitude saves, and any special ability that relies on Constitution (such as when calculating a breath weapon's DC)."),
        description_variables: &[],
        source_page: Some("p.243"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 333,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Trompe l'Oeil ~ Enter Painting",
        name: "Enter Painting",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["TrompeLOeil"],
        description: Some("As a standard action, a trompe l'oeil can enter a painting it touches. When it does so, its physical body disappears, and its image appears in the painting. The trompe l'oeil can use its normal senses and attempt Perception checks to notice anything occurring near the painting. While within a painting, the trompe l'oeil can talk and move anywhere within the picture or even temporarily alter it (such as by picking a flower in the painting). It cannot use any spells or other abilities while within an image. In addition, the trompe l'oeil gains the freeze universal monster ability to appear as part of the painting. The trompe l'oeil can leave the painting as a move action. Once it leaves the painting, the image immediately reverts to the appearance it had before the trompe l'oeil entered. If someone destroys or damages the painting, the trompe l'oeil is unharmed, but exits the image."),
        description_variables: &[],
        source_page: Some("p.243"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 334,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Unknown ~ Psyche Erosion",
        name: "Psyche Erosion",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["UnknownTemplate"],
        description: Some("Once per day, a target affected by an unknown's victimize ability that sees the unknown's true appearance must succeed at a Will save (DC %1) or take 1d6 points of Charisma damage. A successful save negates the Charisma 1d6 points of sanity damage. A successful save negates the sanity damage and also ends the unknown's victimize effect on that target. As long as a creature is the target of an unknown's victimize ability, it can't recover the damage from psyche erosion, even through magic. If the Charisma damage from psyche erosion is equal to the target's Charisma score, that creature doesn't recover ability score damage naturally even if it ceases being the target of victimize. If the sanity damage from psyche erosion is equal to the target's sanity score, that creature doesn't recover ability score damage naturally even if it ceases being the target of victimize.  Only magic can fully heal this damage. When its Charisma damage is equal to its Charisma score, When its sanity damage is equal to its sanity score, the target falls into a nightmare-filled catatonia where it continues to be followed by an unknown. This dream state lasts for 1d4 days, and at the end, the character awakes if its Charisma damage has been reduced to less than its Charisma score. sanity damage has been reduced to less than its sanity score. If not, the creature immediately loses all sense of self, becoming an unknown thrall. It replaces its Charisma score with the unknown's Charisma score, and no longer takes Charisma damage from exposure to the unknown. Over time, typically 1 to 2 weeks, the thrall becomes a new unknown, gaining this template. The unknown can share its senses with any of its thralls (even if it changes the target of its victimize ability), and as a full-round action, it can assume control of a thrall's body, as per possession (OA) . Typically, an unknown uses this ability to keep the thrall close by until it becomes an unknown. Unknowns often use thralls to lure new victims to its lair. Psyche erosion is a mind-affecting effect."),
        description_variables: &["10+TL+CHA"],
        source_page: Some("p.244"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 337,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Unknown ~ Victimize",
        name: "Victimize",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["UnknownTemplate"],
        description: Some("As a swift action, an unknown can target a single creature within line of sight with this ability. After designating a target, the unknown can't change the target of this ability for 24 hours, or until the target dies or succeeds at its save against the unknown's psyche erosion ability. An unknown always knows the exact location of a victimized creature and the shortest route to reach it, even if it is on another plane (similar to a combined discern location and find the path); this is a divination effect and can only be prevented by mind blank and similar effects. A creature can be the target of only one unknown's victimize ability at a time, and an unknown can victimize only one creature at a time."),
        description_variables: &[],
        source_page: Some("p.245"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 338,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Unknown ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &["UnknownTemplate"],
        description: None,
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 339,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Unknown ~ Assume Likeness",
        name: "Assume Likeness",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["UnknownTemplate"],
        description: Some("As a standard action while using hallucinatory camouflage, an unknown is able to disguise itself as a specific creature known to the target of its victimize ability. If the victimized creature succeeds at a Will save (DC %1) it negates this effect, and the unknown can't use this ability again for 24 hours or until it changes victims, whichever comes first. Otherwise, the unknown's features and mannerisms change to match the creature known to its victim, granting it a +20 circumstance bonus on Disguise checks to impersonate this creature. Unlike hallucinatory camouflage, this ability works against the target of victimize. This is a mind-affecting illusion (glamer) effect."),
        description_variables: &["10+TL+CHA"],
        source_page: Some("p.245"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 340,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Unknown ~ Dream Movements",
        name: "Dream Movements",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["UnknownTemplate"],
        description: Some("To the unknown, all worlds are tinted with the shades of nightmares from the Dimension of Dreams, allowing them to defy the laws of physics as they move as if in a dream. An unknown gains an insight bonus to AC equal to its Charisma bonus. It can travel as if by dimension door as a move action at will, but only to enter or leave an area within line of sight of the target of its victimize ability. The victimized creature and the intended destination must both be within long range of the unknown."),
        description_variables: &[],
        source_page: Some("p.245"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 341,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Unknown ~ Hallucinatory Camouflage",
        name: "Hallucinatory Camouflage",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["UnknownTemplate"],
        description: Some("As long as an unknown is targeting a creature with its victimize ability, it hides its appearance behind a veil of illusions, appearing to be an unremarkable member of the victimized creature's race to everyone except the target of victimize. A successful Will save (DC %1) allows a creature that interacts with the illusion to disbelieve the effect. This is a mind-affecting illusion (glamer) effect."),
        description_variables: &["10+TL+CHA"],
        source_page: Some("p.245"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 342,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Undead Phantom ~ Cling of the Grave",
        name: "Cling of the Grave",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("An undead phantom can hold the charge on a touch spell of the necromancy school up to a maximum of 1 round per spiritualist level of the necrologist. This ability alters share spells."),
        description_variables: &[],
        source_page: Some("p.69"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 345,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Undead Phantom ~ Unnatural Aura",
        name: "Unnatural Aura",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Animals do not willingly approach within 30 feet of a fully manifested undead phantom unless the necrologist succeeds at a Handle Animal, Ride, or wild empathy check (DC %1)."),
        description_variables: &["10+PhantomMasterLVL/2+CHA"],
        source_page: Some("p.69"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 346,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Undead Phantom ~ Channel Resistance",
        name: "Channel Resistance",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A necrologist's phantom gains a +4 bonus on saving throws to resist the effects of channel energy."),
        description_variables: &[],
        source_page: Some("p.69"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 347,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Undead Phantom ~ Lifedrinker",
        name: "Lifedrinker",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("When a necrologist's phantom reduces a creature to fewer than 0 hit points with an attack or spell, the necrologist can expend one use of her channel energy ability as a swift action to affect the same target withdeath knell. If the target fails its save, the necrologist can choose either herself or her phantom to gain the benefit of the spell."),
        description_variables: &[],
        source_page: Some("p.69"),
        owners: &[],
        source_file: "ha_abilities_race.lst",
        source_line: 348,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
];
