//! Package-backed mirror of the compiled `rules_tables` module `beastiary1` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

pub use super::companion_chassis::{CompanionAbilityRecord, CompanionRecord};
use crate::rules_core::rules_catalog::RuleSetId;
pub(crate) mod companion_data;
pub mod equipment_data;
pub mod equipment_tables;
pub mod natural_attack_provenance;
/// Identifies which Bestiary 1 monster a chassis query targets. Subset
/// 01's and subset 02's corrected rosters (see this module's doc
/// comment).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[cfg_attr(test, derive(schemars::JsonSchema))]
pub enum MonsterId {
    Ghoul,
    Gnoll,
    GoblinDog,
    Lizardfolk,
    Wolf,
    Darkmantle,
    Horse,
    Hyena,
    Octopus,
    SpiderSwarm,
    BatSwarm,
    Boar,
    Boggard,
    Bugbear,
    CaveFisher,
    Choker,
    Crocodile,
    DarkCreeper,
    IronCobra,
    Morlock,
    RatSwarm,
    Sahuagin,
    Shark,
    ShockerLizard,
    Skum,
    Squid,
    Troglodyte,
    Vargouille,
    Wolverine,
    Worg,
    YellowMuskCreeper,
    Ankheg,
    AssassinVine,
    Centaur,
    Cockatrice,
    Derro,
    Doppelganger,
    Dryad,
    Ettercap,
    GelatinousCube,
    HellHound,
    Lion,
    Ogre,
    Pegasus,
    RustMonster,
    Shadow,
}
impl MonsterId {
    /// Every real Bestiary 1 `MonsterId` variant, in declaration order
    /// (subsets 01-08, per this module's doc comment). Mirrors
    /// `ClassId::ALL`/`ApgClassId::ALL`/`AcgClassId::ALL` on the other
    /// three books (`decisions.md §11.6`) — this book had none before,
    /// forcing `apps/desktop/src-tauri/src/corpus_ingest_diagnostic.rs`
    /// to hand-maintain its own duplicate 41-entry workaround list
    /// (`ALL_BESTIARY1_MONSTERS`, now replaced with this constant) and
    /// `SD-26`'s `cache_gen::beastiary1` JSON-cache generator to need one
    /// too. A future roster addition/removal that forgets to update this
    /// list fails to compile at every call site that pattern-matches
    /// exhaustively on `MonsterId` (e.g. `monster_resolve`'s own `match`),
    /// so this list can't silently drift from the real enum.
    pub const ALL: &'static [MonsterId] = &[
        MonsterId::Ghoul,
        MonsterId::Gnoll,
        MonsterId::GoblinDog,
        MonsterId::Lizardfolk,
        MonsterId::Wolf,
        MonsterId::Darkmantle,
        MonsterId::Horse,
        MonsterId::Hyena,
        MonsterId::Octopus,
        MonsterId::SpiderSwarm,
        MonsterId::BatSwarm,
        MonsterId::Boar,
        MonsterId::Boggard,
        MonsterId::Bugbear,
        MonsterId::CaveFisher,
        MonsterId::Choker,
        MonsterId::Crocodile,
        MonsterId::DarkCreeper,
        MonsterId::IronCobra,
        MonsterId::Morlock,
        MonsterId::RatSwarm,
        MonsterId::Sahuagin,
        MonsterId::Shark,
        MonsterId::ShockerLizard,
        MonsterId::Skum,
        MonsterId::Squid,
        MonsterId::Troglodyte,
        MonsterId::Vargouille,
        MonsterId::Wolverine,
        MonsterId::Worg,
        MonsterId::YellowMuskCreeper,
        MonsterId::Ankheg,
        MonsterId::AssassinVine,
        MonsterId::Centaur,
        MonsterId::Cockatrice,
        MonsterId::Derro,
        MonsterId::Doppelganger,
        MonsterId::Dryad,
        MonsterId::Ettercap,
        MonsterId::GelatinousCube,
        MonsterId::HellHound,
        MonsterId::Lion,
        MonsterId::Ogre,
        MonsterId::Pegasus,
        MonsterId::RustMonster,
        MonsterId::Shadow,
    ];
}
/// A Bestiary 1 monster's chassis data, bounded to the fields literally
/// present as tokens on the real bare monster row (see
/// `pcgen_import::lst_parser::monster_stat_block`'s module doc comment
/// for the scope-boundary rationale: AC/HP/saves are PCGen-computed, not
/// literal row tokens, and are deliberately out of scope for this
/// cycle).
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[cfg_attr(test, derive(schemars::JsonSchema))]
#[cfg_attr(test, schemars(rename = "beastiary1__MonsterStatBlock"))]
pub struct MonsterStatBlock {
    pub name: String,
    pub challenge_rating: f32,
    pub size: String,
    pub speed_ft: u32,
    pub race_type: String,
    pub race_subtype: Option<String>,
    pub source_page: String,
    pub natural_attacks: Vec<NaturalAttack>,
}
/// A single natural-weapon attack.
///
/// Usually transcribed from a `NATURALATTACKS:` token on the monster's
/// real source file row. Twelve Bestiary 1 monsters instead carry only an
/// `ABILITY:Internal|AUTOMATIC|<Name>` cross-reference, which names the
/// attack but supplies no dice at any hop — for those, `damage_dice` is
/// grounded from published values and every one is documented, with its
/// sources, in [`natural_attack_provenance`]. **Read that module before
/// changing any `natural_attacks` list back to empty.**
///
/// `damage_dice` is the die expression only, with no Strength modifier
/// (`"1d6"`, not `"1d6+1"`). `"0"` means a real attack that deals no
/// damage — e.g. Cave Fisher's Filament, whose own corpus token ends
/// `,*1,0`. The per-attack `*N` count on a `NATURALATTACKS:` token is
/// deliberately **not** modelled: this struct records distinct attack
/// types, so a Ghoul's `Claw,...,*2,1d6` yields one `Claw` entry.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[cfg_attr(test, derive(schemars::JsonSchema))]
#[cfg_attr(test, schemars(rename = "beastiary1__NaturalAttack"))]
pub struct NaturalAttack {
    pub name: String,
    pub damage_dice: String,
}
pub fn monster_resolve(monster_id: MonsterId, rule_set: RuleSetId) -> Option<MonsterStatBlock> {
    if rule_set != RuleSetId::Bestiary1 {
        return None;
    }
    crate::rules_core::rules_catalog::rows::<
        crate::rules_core::rules_data_package::Beastiary1MonsterRow,
    >("beastiary1/monster_resolve")
    .iter()
    .find(|row| row.monster == monster_id)
    .map(|row| row.stat_block.clone())
}
/// The canonical `beastiary1:monster:<slug>` key for a resolved stat block:
/// lowercase the display name, spaces to underscores.
///
/// The single source of truth for this derivation (SD28-E16, `decisions.md`
/// §36 instance 9, caught while fixing instance 6): `apps/desktop/
/// src-tauri/src/monster_catalog.rs`'s own key-building used to be a
/// second, independent copy of this exact formula in a different crate --
/// harmless only because nothing had yet exercised a name the two
/// implementations would disagree on, which is precisely how instances 1-8
/// went unnoticed too. `monster_catalog.rs` now calls this function
/// directly instead of re-implementing it. No name in this book's roster
/// carries a character this simple derivation mishandles (an apostrophe, a
/// hyphen colliding with the `_` separator) -- checked, not assumed, by
/// `no_monster_name_carries_a_character_the_key_derivation_cannot_handle`
/// below.
pub fn monster_key(name: &str) -> String {
    format!("beastiary1:monster:{}", name.to_lowercase().replace(' ', "_"))
}
pub fn monster_key_resolve(key: &str, rule_set: RuleSetId) -> Option<MonsterStatBlock> {
    for &id in MonsterId::ALL {
        // Resolve unconditionally (not gated on `rule_set` first) so a
        // `rule_set` mismatch on a real key still returns `None` via
        // `monster_resolve`'s own gate, rather than this loop silently
        // skipping every candidate for the wrong rule set.
        let Some(block) = monster_resolve(id, rule_set) else {
            continue;
        };
        if monster_key(&block.name) == key {
            return Some(block);
        }
    }
    None
}
pub fn companions_static() -> &'static [CompanionRecord] {
    &*companion_data::COMPANIONS
}
pub fn companion_abilities_static() -> &'static [CompanionAbilityRecord] {
    &*companion_data::COMPANION_ABILITIES
}
pub fn companions() -> &'static [CompanionRecord] {
    companions_static()
}
pub fn companion_abilities() -> &'static [CompanionAbilityRecord] {
    companion_abilities_static()
}

#[cfg(test)]
mod companion_tests {
    use super::*;

    /// From `docs/work-inventory.json`'s own units for this book: 154 companion
    /// units, of which 55 creature rows and 71 ability rows ship, none gated
    /// and none a `*_classes_companion` class row.
    ///
    /// **The two halves are pinned by SOURCE FILE, not only in total.** This
    /// book's companion table draws from two places, and they fail
    /// independently:
    ///
    /// * `b1_races_companion` / `b1_abilities_companion` -- 24 + 35,
    ///   the book's own directory, unchanged since SD-29 Epic 7 round 3.
    /// * `ce_races_familiar_cr` / `ce_abilities_familiar_race_cr` --
    ///   31 + 36. Both files sit under PCGen's `core_essentials/` packaging
    ///   directory and both declare `SOURCELONG:Bestiary` in their own headers,
    ///   so `decisions.md §9` re-attribution files their rows here. The `_cr`
    ///   filename suffix means "the Core Rulebook classes' familiar list" and
    ///   is NOT a book signal -- reading it as one is what put these 67 records
    ///   under `core_rulebook` on disk while the engine served them from a
    ///   `core_essentials` table, which is how all 67 came to reach no player
    ///   surface at all (`SD31-CE-COMPANION-001`).
    #[test]
    fn the_book_defines_fifty_five_companions_and_seventy_one_abilities() {
        assert_eq!(companions().len(), 55);
        assert_eq!(companion_abilities().len(), 71);

        let own_creatures =
            companions().iter().filter(|c| c.source_file.starts_with("b1_")).count();
        let own_abilities =
            companion_abilities().iter().filter(|a| a.source_file.starts_with("b1_")).count();
        assert_eq!(own_creatures, 24, "rows from this book's own directory");
        assert_eq!(own_abilities, 35, "rows from this book's own directory");

        let reattributed_creatures =
            companions().iter().filter(|c| c.source_file.starts_with("ce_")).count();
        let reattributed_abilities =
            companion_abilities().iter().filter(|a| a.source_file.starts_with("ce_")).count();
        assert_eq!(reattributed_creatures, 31, "rows re-attributed here by decisions.md §9");
        assert_eq!(reattributed_abilities, 36, "rows re-attributed here by decisions.md §9");
    }

    /// The five rows that made this book look unregisterable, pinned BY NAME.
    ///
    /// `classify_companion_rows.py` reported them as orphans until
    /// `decisions.md §54.1` added the granted-by shape: each is named by an
    /// `ABILITY:Special Ability|AUTOMATIC|` token on a `CompanionAdvancement`
    /// row, and that row — not the creature row — is what reaches them. A
    /// regression that dropped the shape would leave these five with no owner,
    /// and this test says so by name rather than by a count.
    #[test]
    fn the_five_granted_by_advancement_abilities_resolve_to_their_creature() {
        for (ability_key, owner) in [
            ("Ankylosaurus ~ Stun", "Companion (Dinosaur (Ankylosaurus))"),
            ("Electric Eel ~ Electricity", "Companion (Eel (Electric))"),
            ("Giant Moray Eel ~ Gnaw", "Companion (Eel (Giant Moray))"),
            ("Lizard Monitor ~ Poison", "Companion (Lizard (Monitor))"),
            ("Tyrannosaurus ~ Powerful Bite", "Companion (Dinosaur (Tyrannosaurus))"),
        ] {
            let ability = companion_abilities()
                .iter()
                .find(|a| a.key == ability_key)
                .unwrap_or_else(|| panic!("{ability_key} is in this book"));
            assert!(
                ability.owners.contains(&owner),
                "{ability_key} must be owned by {owner} (granted-by shape, decisions.md §54.1); \
                 owners were {:?}",
                ability.owners
            );
            let creature = companions()
                .iter()
                .find(|c| c.key == owner)
                .unwrap_or_else(|| panic!("{owner} is in this book"));
            assert!(
                creature.ability_keys.contains(&ability_key),
                "{owner} must name {ability_key} back"
            );
        }
    }

    /// Verbatim spot-check against `b1_races_companion:7`.
    #[test]
    fn the_dire_bat_companion_matches_its_corpus_row() {
        let companion = companions()
            .iter()
            .find(|c| c.key == "Companion (Bat (Dire))")
            .expect("the dire bat is in this book");
        assert_eq!(companion.size, Some("M"));
        assert_eq!(companion.monster_class, Some("Companion:2"));
        assert_eq!(companion.source_page, Some("p.30"));
        assert_eq!(
            companion.speeds,
            &[
                super::super::companion_chassis::Speed { mode: "Walk", feet: 20 },
                super::super::companion_chassis::Speed { mode: "Fly", feet: 40 },
            ]
        );
    }

    /// Every ability row is owned by a creature row of this book, and every
    /// owner names it back.
    #[test]
    fn every_ability_row_names_at_least_one_owner_in_this_book() {
        let keys: Vec<_> = companions().iter().map(|c| c.key).collect();
        for ability in companion_abilities() {
            assert!(!ability.owners.is_empty(), "{} is an orphan", ability.key);
            for owner in ability.owners {
                assert!(
                    keys.contains(owner),
                    "{}: owner {owner} is not a creature in this book",
                    ability.key
                );
            }
        }
    }

    /// The companion population and the monster population are different
    /// things that this book contributes under one `RuleSetId`. Nothing may
    /// silently reconcile them: `Companion (Wolf)` is not the `Wolf` stat
    /// block, and the 46 monsters are not 46 of the 24 companions.
    #[test]
    fn the_companion_rows_are_not_this_module_s_monster_rows() {
        let monsters: Vec<String> = super::MonsterId::ALL
            .iter()
            .filter_map(|id| super::monster_resolve(*id, super::RuleSetId::Bestiary1))
            .map(|block| super::monster_key(&block.name))
            .collect();
        assert_eq!(monsters.len(), super::MonsterId::ALL.len(), "every monster resolves");
        for companion in companions() {
            assert!(
                !monsters.contains(&super::monster_key(companion.key)),
                "{} collides with a monster key",
                companion.key
            );
        }
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn all_has_exactly_the_46_real_monsters_with_no_duplicates() {
        assert_eq!(MonsterId::ALL.len(), 46, "real, corrected roster across subsets 01-09 (this module's doc comment)");
        let unique: HashSet<MonsterId> = MonsterId::ALL.iter().copied().collect();
        assert_eq!(unique.len(), 46, "MonsterId::ALL must not repeat any variant");
    }

    #[test]
    fn every_all_entry_resolves_a_real_stat_block_for_bestiary1() {
        for &id in MonsterId::ALL {
            assert!(monster_resolve(id, RuleSetId::Bestiary1).is_some(), "{id:?} must resolve for RuleSetId::Bestiary1");
        }
    }

    /// SD28-E16 (`decisions.md` §36 instance 6): `monster_key_resolve` is
    /// now derived from `MonsterId::ALL` rather than hand-written, so this
    /// is the test that makes a future roster addition self-verifying --
    /// every variant must round-trip through its own derived key, with no
    /// second list for a future subset to remember to update.
    #[test]
    fn every_monster_id_all_variant_round_trips_through_monster_key_resolve() {
        for &id in MonsterId::ALL {
            let block = monster_resolve(id, RuleSetId::Bestiary1).unwrap_or_else(|| panic!("{id:?} must resolve"));
            let key = monster_key(&block.name);
            let resolved = monster_key_resolve(&key, RuleSetId::Bestiary1)
                .unwrap_or_else(|| panic!("{id:?}'s own derived key {key:?} must resolve back via monster_key_resolve"));
            assert_eq!(resolved.name, block.name, "{key:?} resolved to a different monster than {id:?}");
        }
    }

    /// The derivation `monster_key` uses (lowercase, spaces to underscores)
    /// only round-trips cleanly if no monster's display name carries a
    /// character the slug would need to escape (an apostrophe, a hyphen
    /// colliding with the `_` separator, etc.) -- asserted directly rather
    /// than assumed, since `monster_catalog.rs`'s own `monster_key` uses
    /// the identical derivation and both must keep agreeing as the roster
    /// grows.
    #[test]
    fn no_monster_name_carries_a_character_the_key_derivation_cannot_handle() {
        for &id in MonsterId::ALL {
            let block = monster_resolve(id, RuleSetId::Bestiary1).unwrap_or_else(|| panic!("{id:?} must resolve"));
            assert!(
                block.name.chars().all(|c| c.is_ascii_alphanumeric() || c == ' '),
                "{:?}: name {:?} carries a character other than ASCII letters/digits/spaces, which \
                 monster_key's simple lowercase+underscore derivation does not handle",
                id,
                block.name
            );
        }
    }
}
