//! Package-backed mirror of the compiled `rules_tables` module `beastiary1::natural_attack_provenance` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

/// Where a single natural attack's `damage_dice` value actually came
/// from. Mirrors the two `SD-26 decisions.md §11.2` discriminated-union
/// kinds that apply to this data; the other three kinds
/// (`lst_inherited_copy`, `lst_corrected_ingest`, `same_book_fallback`)
/// have no instance here.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[cfg_attr(test, derive(schemars::JsonSchema))]
pub enum AttackSource {
    /// A real, checkable `NATURALATTACKS:` token in the live PCGen
    /// corpus — just not on the monster's own `b1_races` row.
    LstToken {
        /// Corpus-root-relative path of the file carrying the token.
        path: &'static str,
        /// 1-based line number of the record within `path`.
        line: u32,
        /// The record's `KEY:` (or first-column name) at `line`.
        record_key: &'static str,
    },
    /// Grounded from the published Bestiary 1 text via `§11.5`'s
    /// allowed-domain web methodology.
    WebSecondSource {
        /// Independent agreeing sources. `§11.5` permits only
        /// `aonprd.com` / `legacy.aonprd.com` / `d20pfsrd.com`; the
        /// grounding bar requires **at least two**, both asserted by
        /// `tests/v06_beastiary1_natural_attack_grounding.rs`.
        #[serde(deserialize_with = "crate::rules_core::rules_data_package::leak_slice")]
        urls: &'static [&'static str],
        /// ISO-8601 date the sources were read.
        fetched_at: &'static str,
        /// Which fields beyond the name confirmed this is the right
        /// creature — `§11.5`'s "reject same-named cross-book /
        /// edition-cousin false matches" discipline.
        identity_match_basis: &'static str,
    },
}
/// One natural attack whose `damage_dice` is not transcribed from the
/// monster's own `b1_races` row.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[cfg_attr(test, derive(schemars::JsonSchema))]
pub struct GroundedAttack {
    /// Canonical `beastiary1:monster:<slug>` key, matching
    /// `super::monster_key_resolve`'s key shape.
    pub monster_key: &'static str,
    /// Must equal the shipped `NaturalAttack::name`.
    pub attack_name: &'static str,
    /// Must equal the shipped `NaturalAttack::damage_dice`.
    pub damage_dice: &'static str,
    /// The real token on the monster's own row that *names* this attack
    /// (the dice are what the corpus lacks, not the name).
    pub corpus_name_token: &'static str,
    /// Verbatim published "Melee" text the dice were read from, kept so
    /// a future reader can re-check the transcription without refetching.
    pub published_melee_text: &'static str,
    /// Where `damage_dice` came from.
    pub source: AttackSource,
}
pub static GROUNDED_NATURAL_ATTACKS: crate::rules_core::rules_catalog::Table<GroundedAttack> =
    crate::rules_core::rules_catalog::Table::new(
        "beastiary1/natural_attack_provenance/GROUNDED_NATURAL_ATTACKS",
    );
pub fn provenance_for(monster_key: &str) -> Vec<&'static GroundedAttack> {
    GROUNDED_NATURAL_ATTACKS
        .iter()
        .filter(|g| g.monster_key == monster_key)
        .collect()
}
