//! Package-backed mirror of the compiled `rules_tables` module `beastiary1::natural_attack_provenance` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::beastiary1::natural_attack_provenance::AttackSource;
pub use rt::beastiary1::natural_attack_provenance::GroundedAttack;
pub static GROUNDED_NATURAL_ATTACKS: crate::rules_core::rules_catalog::Table<GroundedAttack> =
    crate::rules_core::rules_catalog::Table::new(
        "beastiary1/natural_attack_provenance/GROUNDED_NATURAL_ATTACKS",
    );
pub fn provenance_for(monster_key: &str) -> Vec<&'static GroundedAttack> {
    GROUNDED_NATURAL_ATTACKS
        .iter()
        .filter(|g| g.monster_key == monster_key)
        .collect()
}
