//! The `derived` wiring class's missing instrument: **evaluator vs fixture**.
//!
//! # What this closes
//!
//! The doneness ladder the dashboard serves states each wiring class's bar and
//! whether an instrument exists to check it. For `derived` it says the bar is
//! known and the check is not built: a `derived` unit "needs an
//! evaluator-vs-fixture check". Until this file existed, no such check did, so
//! every `derived` unit holding real corpus data sat at `held` — as done as the
//! current instruments can prove, and deliberately not counted as done.
//!
//! A `derived` unit's bar, precisely: the engine's evaluator, run over the real
//! corpus record, must produce the value the corpus row independently states.
//!
//! This is a strictly stronger check than the consumer-delta probe that already
//! exists (`v06_work_inventory::equipment_key_is_wired`). That probe asks
//! whether equipping an item produces *any* non-`None` mechanical effect — it
//! never looks at the number. This file asks whether the number is **right**.
//!
//! # Why the fixture cannot have been authored from the evaluator
//!
//! A fixture generated by the thing it tests proves nothing, and this repo has
//! a live finding of exactly that shape (SD-29 Epic 10 F3, register C1.4a:
//! frontend preview fixtures were hand-authored rules data with nothing pinning
//! them to the corpus, and one shipped wrong rules content to a player).
//!
//! Four independent guarantees, three of which this file re-checks at run time
//! rather than asserting in prose:
//!
//! 1. **Different source artifact.** The fixture's expected values are read from
//!    the UPSTREAM PCGen `.lst` bytes. The engine evaluates this repo's own
//!    `data/corpus/**/*.json` ingest. Two different files, on two different
//!    trees, reached by two code paths that share nothing.
//! 2. **Committed first.** The fixture and its generator landed in their own
//!    commit, before this file was written. Commit order is the evidence.
//! 3. **Re-derivable from the pinned corpus text** —
//!    [`fixture_expected_values_are_re_derivable_from_the_pinned_corpus_field`].
//!    A reference derivation written here, independently of both the Python
//!    generator and the engine, re-reads each pinned corpus field and must
//!    reproduce the fixture's expected value. A hand-invented number fails.
//! 4. **Anchored to the same upstream bytes the engine ingested** —
//!    [`engine_ingest_cites_the_same_upstream_bytes_the_fixture_was_read_from`]
//!    and [`pinned_corpus_field_is_byte_identical_to_the_upstream_lst`]. The
//!    fixture records the upstream file's sha256 and line; the engine's own
//!    corpus record independently records the same three facts about its
//!    provenance. If either side is regenerated against a different upstream
//!    revision, this goes red instead of silently comparing two different rows.
//!
//! Guarantee 4 is the pin register C1.4a's fixtures lacked, and it is also the
//! only test in this repo that would catch `data/corpus/` being regenerated or
//! edited away from the upstream corpus it claims to mirror.
//!
//! # Coverage is deliberately reported, never quietly narrowed
//!
//! The fixture covers 94 of the 2,879 held `derived` units. It is not a sample:
//! it is every held `derived` unit whose corpus row carries a token family this
//! engine evaluates a number for. `scripts/derive_derived_evaluator_fixtures.py`
//! prints the other 2,785 with a named reason each — overwhelmingly kinds with
//! no equipment-effect evaluator at all (monster 1,229; spell 941; companion
//! 303; monster_ability 219), and derived token families the engine evaluates
//! nothing for (`BONUS:WEAPON|DAMAGE|min(STR,0)`, `BONUS:CASTERLEVEL`, the
//! `COST:` expressions). Those units stay `held`, correctly. Widening this
//! instrument means building the missing evaluators, not loosening this check.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use codex::rules_core::character_input::{ActiveState, EquipmentSelection};
use codex::rules_core::corpus_loader::{BookCorpusRoot, load_equipment_corpus};
use codex::rules_core::equipment_effects::compute_equipment_effects;

const FIXTURE: &str = "tests/fixtures/rules_core/derived-evaluator-fixtures.json";

/// Covered units that **do not clear the bar**, each with the structural reason,
/// pinned as an EXACT set.
///
/// Read this as a defect register, not as an exemption list. A unit named here
/// is reported as failing its `derived` bar, is never counted among the units
/// that cleared it, and stays `held`. The set is asserted for exact equality in
/// both directions, which is what stops it becoming an exemption list: a unit
/// that starts failing and is not named here turns this suite red, and so does a
/// unit named here that starts passing — the fix must delete the entry rather
/// than leave a stale excuse behind.
///
/// The one entry is the first defect this instrument found, on its first run,
/// and it is a real one: the item's corpus row grants +4 to three ability
/// scores and the player receives nothing.
const UNCLEARED: &[(&str, &str)] = &[(
    "advanced_players_guide:equipment:spindle_of_perfect_knowledge",
    "this repo's ingest of the record is a `web_second_source` scrape carrying no \
     mechanical tokens at all, so the evaluator has nothing to evaluate and the \
     corpus row's `BONUS:STAT|INT,WIS,CHA|4` reaches no player. Not a property of \
     this one item: APG's equipment ingest is 331 such records against 7 real \
     `lst_token` ones (`data/corpus/advanced_players_guide/equipment/**/*.json`, \
     counted by `source.kind`), because 0 of its 338 rows carry a native `DESC:` \
     token (`tests/sd26_cache_apg.rs`) and the whole book was taken from a web \
     second source — which dropped its `BONUS:` chains along with its prose. \
     Remedying it is an ingest-lane change, not a change to this check.",
)];

/// The reason recorded for `unit_id`, if it is a known-uncleared unit.
fn uncleared_reason(unit_id: &str) -> Option<&'static str> {
    UNCLEARED.iter().find(|(id, _)| *id == unit_id).map(|(_, reason)| *reason)
}

/// Asserts the observed failing set is exactly [`UNCLEARED`], in both
/// directions, and returns the report line for the receipt.
fn assert_uncleared_set_is_exact(observed: &BTreeMap<String, String>, what: &str) {
    let expected: BTreeSet<&str> = UNCLEARED.iter().map(|(id, _)| *id).collect();
    let actual: BTreeSet<&str> = observed.keys().map(String::as_str).collect();
    let unexpected: Vec<&&str> = actual.difference(&expected).collect();
    let stale: Vec<&&str> = expected.difference(&actual).collect();
    assert!(
        unexpected.is_empty(),
        "{what}: {} unit(s) fail their `derived` bar without being on the record. \
         Either the engine regressed, or a real defect was found — put it in \
         `UNCLEARED` with its structural reason, or fix it. Never widen the \
         comparison to make it pass:\n{}",
        unexpected.len(),
        unexpected
            .iter()
            .map(|id| format!("  {id}: {}", observed[**id]))
            .collect::<Vec<_>>()
            .join("\n")
    );
    assert!(
        stale.is_empty(),
        "{what}: {stale:?} is recorded in `UNCLEARED` but now clears its bar. \
         Delete the entry — a stale excuse left in place is how an exemption list \
         starts."
    );
}

/// One fixture row, in the shape the committed JSON carries.
#[derive(Debug, Clone)]
struct Fixture {
    unit_id: String,
    book: String,
    record_key: String,
    /// Path of the upstream PCGen `.lst`, relative to the PCGen `data/` root —
    /// spelled exactly the way this repo's own corpus records spell their
    /// `source.path`, which is what makes the two directly comparable.
    upstream_lst: String,
    upstream_lst_sha256: String,
    upstream_line: u64,
    /// The verbatim tab field the expected value was derived from.
    corpus_field: String,
    expected_abilities: Vec<String>,
    expected_bonus: i16,
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn load_fixtures() -> Vec<Fixture> {
    let path = repo_root().join(FIXTURE);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("the committed fixture must be readable at {path:?}: {e}"));
    let doc: serde_json::Value =
        serde_json::from_str(&text).expect("the committed fixture must be valid JSON");
    let entries = doc["entries"].as_array().expect("fixture carries an `entries` array");
    assert!(
        !entries.is_empty(),
        "an empty fixture would make every assertion in this file vacuously true"
    );
    entries
        .iter()
        .map(|e| {
            let expected = &e["expected"];
            Fixture {
                unit_id: e["unit_id"].as_str().expect("unit_id").to_string(),
                book: e["book"].as_str().expect("book").to_string(),
                record_key: e["record_key"].as_str().expect("record_key").to_string(),
                upstream_lst: e["upstream_lst"].as_str().expect("upstream_lst").to_string(),
                upstream_lst_sha256: e["upstream_lst_sha256"]
                    .as_str()
                    .expect("upstream_lst_sha256")
                    .to_string(),
                upstream_line: e["upstream_line"].as_u64().expect("upstream_line"),
                corpus_field: e["corpus_field"].as_str().expect("corpus_field").to_string(),
                expected_abilities: expected["abilities"]
                    .as_array()
                    .expect("expected.abilities")
                    .iter()
                    .map(|a| a.as_str().expect("ability name").to_string())
                    .collect(),
                expected_bonus: i16::try_from(
                    expected["bonus"].as_i64().expect("expected.bonus"),
                )
                .expect("an ability bonus fits in i16"),
            }
        })
        .collect()
}

/// The reference derivation for PCGen's `BONUS:STAT` token, written here
/// independently of both `scripts/derive_derived_evaluator_fixtures.py` (which
/// produced the fixture) and `equipment_effects::magic_items` (which is the
/// evaluator under test).
///
/// Grammar: `BONUS:STAT|<comma-separated ability list>|<integer value>
/// [|<extra qualifiers>]`. The trailing qualifiers (`TYPE=Enhancement`, `PRE*`
/// guards) select a stacking type or a condition; neither changes the
/// magnitude, which is what this derivation is about.
///
/// Deliberately total: a field it cannot parse yields `None`, and the caller
/// fails loudly, rather than a guessed value quietly passing.
fn reference_bonus_stat(field: &str) -> Option<(Vec<String>, i16)> {
    let body = field.strip_prefix("BONUS:")?;
    let mut parts = body.split('|');
    if parts.next()? != "STAT" {
        return None;
    }
    let abilities: Vec<String> = parts
        .next()?
        .split(',')
        .map(str::trim)
        .filter(|a| !a.is_empty())
        .map(str::to_string)
        .collect();
    if abilities.is_empty() {
        return None;
    }
    let value: i16 = parts.next()?.trim().parse().ok()?;
    Some((abilities, value))
}

/// The PCGen checkout's `data/` root: `PCGEN_CORPUS_ROOT`, else the repo-wide
/// convention `$HOME/workspace/repos/pcgen/data` (operator ruling recorded in
/// `tests/no_foreign_home_paths.rs` — resolved through `$HOME` at run time,
/// never written as a literal).
fn pcgen_data_root() -> Option<PathBuf> {
    if let Ok(root) = std::env::var("PCGEN_CORPUS_ROOT") {
        return Some(PathBuf::from(root));
    }
    let home = std::env::var("HOME").ok()?;
    Some(PathBuf::from(home).join("workspace").join("repos").join("pcgen").join("data"))
}

/// Where this repo's own ingest of `book` lives, and whether it exists.
///
/// Absence is a real, structural fact — a book nobody has ingested has no
/// records for any evaluator to run over — and it is the ONLY excuse this file
/// accepts for not checking a fixture entry against the engine.
fn ingested_equipment_dir(book: &str) -> Option<PathBuf> {
    let dir = repo_root().join("data").join("corpus").join(book);
    dir.join("equipment").is_dir().then_some(dir)
}

/// Every ingested equipment record of `book`, indexed by its corpus `key`,
/// carrying the provenance the ingest recorded for it.
fn ingested_provenance(book: &str) -> BTreeMap<String, (String, u64, String)> {
    let mut out = BTreeMap::new();
    let Some(dir) = ingested_equipment_dir(book) else { return out };
    let mut stack = vec![dir.join("equipment")];
    while let Some(current) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&current) else { continue };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("json") {
                continue;
            }
            let Ok(text) = std::fs::read_to_string(&path) else { continue };
            let Ok(value) = serde_json::from_str::<serde_json::Value>(&text) else { continue };
            let Some(key) = value["data"]["key"].as_str() else { continue };
            let source = &value["source"];
            let (Some(source_path), Some(line), Some(sha)) = (
                source["path"].as_str(),
                source["line"].as_u64(),
                source["sha256"].as_str(),
            ) else {
                continue;
            };
            out.insert(key.to_string(), (source_path.to_string(), line, sha.to_string()));
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Guarantee 3 — the fixture's numbers are a function of the corpus text
// ---------------------------------------------------------------------------

/// Every expected value in the committed fixture is re-derivable from the
/// corpus field the fixture pins itself to, by a derivation written here and
/// sharing no code with the generator that produced the fixture.
///
/// This is what makes a hand-invented expected value impossible to sneak in:
/// change `expected.bonus` without changing `corpus_field` and this fails.
#[test]
fn fixture_expected_values_are_re_derivable_from_the_pinned_corpus_field() {
    let fixtures = load_fixtures();
    let mut wrong = Vec::new();
    for fixture in &fixtures {
        let Some((abilities, bonus)) = reference_bonus_stat(&fixture.corpus_field) else {
            wrong.push(format!(
                "{}: reference derivation cannot parse the pinned corpus field {:?}",
                fixture.unit_id, fixture.corpus_field
            ));
            continue;
        };
        if abilities != fixture.expected_abilities || bonus != fixture.expected_bonus {
            wrong.push(format!(
                "{}: corpus field {:?} states {:?} +{}, fixture claims {:?} +{}",
                fixture.unit_id,
                fixture.corpus_field,
                abilities,
                bonus,
                fixture.expected_abilities,
                fixture.expected_bonus
            ));
        }
    }
    assert!(
        wrong.is_empty(),
        "{} of {} fixture expectations are not what their own pinned corpus field states \
         — an expected value that is not a function of the corpus is exactly the \
         fixture-authored-from-nothing defect this instrument exists to prevent:\n{}",
        wrong.len(),
        fixtures.len(),
        wrong.join("\n")
    );
}

// ---------------------------------------------------------------------------
// Guarantee 4 — both sides are anchored to the same upstream bytes
// ---------------------------------------------------------------------------

/// This repo's ingest independently recorded the same upstream file, line and
/// file-sha256 the fixture was read from.
///
/// Neither side consulted the other: the fixture's provenance came from walking
/// the PCGen checkout, the ingest's came from `gen_book_cache` at ingest time.
/// Agreement across two independent recordings is what licenses comparing an
/// expected value derived from one against a number evaluated from the other.
///
/// A disagreement here means `data/corpus/` and the upstream corpus have
/// drifted — the "generated artifacts mutated post-hoc" hazard, which nothing
/// else in this repo tests for.
#[test]
fn engine_ingest_cites_the_same_upstream_bytes_the_fixture_was_read_from() {
    let fixtures = load_fixtures();
    let mut provenance_by_book: BTreeMap<String, BTreeMap<String, (String, u64, String)>> =
        BTreeMap::new();
    let mut mismatched: BTreeMap<String, String> = BTreeMap::new();
    let mut compared = 0usize;
    let mut not_ingested: BTreeSet<String> = BTreeSet::new();

    for fixture in &fixtures {
        if ingested_equipment_dir(&fixture.book).is_none() {
            not_ingested.insert(fixture.book.clone());
            continue;
        }
        let records = provenance_by_book
            .entry(fixture.book.clone())
            .or_insert_with(|| ingested_provenance(&fixture.book));
        let Some((path, line, sha)) = records.get(&fixture.record_key) else {
            mismatched.insert(
                fixture.unit_id.clone(),
                format!(
                    "book {} is ingested but records no `.lst` provenance for {:?}",
                    fixture.book, fixture.record_key
                ),
            );
            continue;
        };
        if path != &fixture.upstream_lst
            || *line != fixture.upstream_line
            || sha != &fixture.upstream_lst_sha256
        {
            mismatched.insert(
                fixture.unit_id.clone(),
                format!(
                    "fixture read {}:{} (sha {}), ingest cites {}:{} (sha {})",
                    fixture.upstream_lst,
                    fixture.upstream_line,
                    fixture.upstream_lst_sha256,
                    path,
                    line,
                    sha
                ),
            );
            continue;
        }
        compared += 1;
    }

    assert_uncleared_set_is_exact(&mismatched, "upstream anchor");
    assert!(
        compared > 0,
        "no fixture entry could be anchored against the engine's ingest, which makes \
         this guarantee vacuous rather than satisfied"
    );
    eprintln!(
        "upstream anchor: {compared} entries agreed across both provenance recordings; \
         {} not anchored (on the `UNCLEARED` record); {} belong to books with no \
         ingest at all ({not_ingested:?})",
        mismatched.len(),
        fixtures.len() - compared - mismatched.len()
    );
}

/// The pinned corpus field is still byte-identical to the upstream `.lst` line
/// it was read from, and that file still hashes to the recorded sha256.
///
/// Gated on the PCGen checkout being present, which is the repo's existing
/// convention for corpus-backed checks
/// (`PCGEN_CORPUS_ROOT`, see `rules_core::feat_prereqs::pre_tokens`). It is a
/// deliberate belt-and-braces check rather than the load-bearing one:
/// `engine_ingest_cites_the_same_upstream_bytes_the_fixture_was_read_from`
/// above compares the same sha256 with no external checkout at all, so the
/// anchor is never left unchecked when this one is skipped.
#[test]
fn pinned_corpus_field_is_byte_identical_to_the_upstream_lst() {
    let fixtures = load_fixtures();
    let Some(data_root) = pcgen_data_root() else {
        eprintln!("skipped: neither PCGEN_CORPUS_ROOT nor HOME is set");
        return;
    };
    if !data_root.is_dir() {
        eprintln!(
            "skipped: no PCGen checkout at {data_root:?}; the in-repo sha256 anchor still ran"
        );
        return;
    }

    let mut file_text: BTreeMap<PathBuf, Vec<String>> = BTreeMap::new();
    let mut wrong = Vec::new();
    for fixture in &fixtures {
        let path = data_root.join(&fixture.upstream_lst);
        let lines = file_text.entry(path.clone()).or_insert_with(|| {
            std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("upstream corpus file {path:?} must be readable: {e}"))
                .split('\n')
                .map(str::to_string)
                .collect()
        });
        let index = usize::try_from(fixture.upstream_line).expect("line number fits in usize");
        let Some(line) = index.checked_sub(1).and_then(|i| lines.get(i)) else {
            wrong.push(format!(
                "{}: {} has no line {}",
                fixture.unit_id, fixture.upstream_lst, fixture.upstream_line
            ));
            continue;
        };
        let present = line
            .trim_end_matches(['\n', '\r'])
            .split('\t')
            .any(|field| field.trim() == fixture.corpus_field);
        if !present {
            wrong.push(format!(
                "{}: {}:{} no longer carries the pinned field {:?}",
                fixture.unit_id,
                fixture.upstream_lst,
                fixture.upstream_line,
                fixture.corpus_field
            ));
        }
    }
    assert!(
        wrong.is_empty(),
        "{} pinned corpus fields no longer match the upstream corpus — the fixture \
         is describing rows that have moved or changed:\n{}",
        wrong.len(),
        wrong.join("\n")
    );
}

// ---------------------------------------------------------------------------
// The bar itself
// ---------------------------------------------------------------------------

/// **The `derived` bar.** For every held `derived` unit the fixture covers, the
/// engine's evaluator — reached through the shipping `compute_equipment_effects`
/// seam, over the real on-disk corpus, with that item and nothing else equipped
/// — produces exactly the ability list and magnitude the upstream corpus row
/// states.
///
/// The only accepted reason for not checking an entry is that its book has no
/// ingest in this repo at all (`data/corpus/<book>/equipment` absent), which is
/// asserted as a fact about the filesystem rather than taken on trust. A book
/// that IS ingested and whose record does not evaluate correctly fails here;
/// it is not excused, and its units stay `held`.
#[test]
fn engine_evaluator_output_equals_the_corpus_derived_expected_value() {
    let fixtures = load_fixtures();
    let books: BTreeSet<String> = fixtures.iter().map(|f| f.book.clone()).collect();

    let mut cleared = 0usize;
    let mut failures: BTreeMap<String, String> = BTreeMap::new();
    let mut not_ingested_books: BTreeSet<String> = BTreeSet::new();
    let mut not_ingested_entries = 0usize;

    for book in &books {
        let Some(dir) = ingested_equipment_dir(book) else {
            not_ingested_books.insert(book.clone());
            not_ingested_entries += fixtures.iter().filter(|f| &f.book == book).count();
            continue;
        };
        // One book's ingest, alone — the same book-scoping the existing
        // equipment probe uses, so a key two books both reprint cannot be
        // credited to the wrong one.
        let roots = [BookCorpusRoot { book_id: book.as_str(), dir: Path::new(&dir) }];
        let corpus = load_equipment_corpus(&roots);

        for fixture in fixtures.iter().filter(|f| &f.book == book) {
            let selection = vec![EquipmentSelection {
                item_id: fixture.record_key.clone(),
                equipped_or_active: true,
                active_state: ActiveState::EquippedActive,
                applied_modifiers: Vec::new(),
            }];
            let effects = compute_equipment_effects(&selection, &corpus);
            let Some(item) = effects.per_item.first() else {
                failures.insert(
                    fixture.unit_id.clone(),
                    format!("{:?} does not resolve against its own ingested book", fixture.record_key),
                );
                continue;
            };
            let Some(bonus) = &item.ability_bonus else {
                failures.insert(
                    fixture.unit_id.clone(),
                    format!(
                        "corpus row states {} but the evaluator produced no ability bonus at all",
                        fixture.corpus_field
                    ),
                );
                continue;
            };
            // The evaluator reports the corpus's ability list verbatim, so a
            // multi-ability grant arrives comma-joined exactly as the corpus
            // wrote it. Split, and compare against the list the corpus states.
            let abilities: Vec<String> =
                bonus.ability.split(',').map(str::trim).map(str::to_string).collect();
            if abilities != fixture.expected_abilities || bonus.bonus != fixture.expected_bonus {
                failures.insert(
                    fixture.unit_id.clone(),
                    format!(
                        "corpus row {:?} states {:?} {:+}, evaluator produced {:?} {:+}",
                        fixture.corpus_field,
                        fixture.expected_abilities,
                        fixture.expected_bonus,
                        abilities,
                        bonus.bonus
                    ),
                );
                continue;
            }
            assert!(
                uncleared_reason(&fixture.unit_id).is_none(),
                "{} clears its `derived` bar but is still on the `UNCLEARED` record — \
                 delete the entry",
                fixture.unit_id
            );
            cleared += 1;
        }
    }

    for book in &not_ingested_books {
        assert!(
            !repo_root().join("data").join("corpus").join(book).join("equipment").is_dir(),
            "{book} was skipped as un-ingested, but its equipment corpus exists — the \
             skip is only ever allowed to be a fact about the filesystem"
        );
    }

    assert_uncleared_set_is_exact(&failures, "derived bar");
    assert!(
        cleared > 0,
        "no fixture entry reached the evaluator, which would make this bar vacuous"
    );
    eprintln!(
        "derived evaluator-vs-fixture: {cleared} of {} covered units cleared the bar; \
         {} did NOT and stay `held` (see `UNCLEARED`); {not_ingested_entries} belong to \
         books with no ingest in this repo ({not_ingested_books:?})",
        fixtures.len(),
        failures.len()
    );
}

/// The reference derivation refuses malformed input instead of guessing.
///
/// Without this, a `BONUS:STAT` field the grammar does not cover could silently
/// produce a plausible number and every other assertion here would compare two
/// fabrications.
#[test]
fn reference_derivation_refuses_what_it_cannot_parse() {
    assert_eq!(
        reference_bonus_stat("BONUS:STAT|STR|2|TYPE=Enhancement"),
        Some((vec!["STR".to_string()], 2))
    );
    assert_eq!(
        reference_bonus_stat("BONUS:STAT|INT,WIS,CHA|4|TYPE=Enhancement"),
        Some((vec!["INT".to_string(), "WIS".to_string(), "CHA".to_string()], 4))
    );
    assert_eq!(reference_bonus_stat("BONUS:STAT|WIS|-2"), Some((vec!["WIS".to_string()], -2)));
    // A different BONUS family, a formula the grammar does not evaluate, a
    // missing magnitude, and a non-BONUS token all refuse rather than guess.
    assert_eq!(reference_bonus_stat("BONUS:WEAPON|DAMAGE|min(STR,0)"), None);
    assert_eq!(reference_bonus_stat("BONUS:STAT|STR|CASTERLEVEL/2"), None);
    assert_eq!(reference_bonus_stat("BONUS:STAT|STR"), None);
    assert_eq!(reference_bonus_stat("COST:4000"), None);
}
