//! SD-26 Epic 3, Criterion 3.2 — verifies the on-disk APG JSON cache at
//! `data/corpus/advanced_players_guide/{class,spell,equipment}/*.json`,
//! generated by `codex::rules_core::cache_gen::apg::generate()` (see
//! `src/bin/gen_cache_apg.rs`). Reads only the already-generated files —
//! this test does not require a live PCGen corpus checkout, matching the
//! acceptance command `cargo test --locked --test sd26_cache_apg`
//! (`acceptance-and-verification.md` row 3.2).
//!
//! Real, measured ceilings this test asserts against (`decisions.md
//! §11.4`, re-verified this cycle directly from the compiled
//! `rules_tables::apg` module before generation — see this cycle's
//! receipt): equipment `description` 331/338 (97.9%); spell `full_text`
//! 296/297 (99.7%); spell `description` 297/297.
//!
//! **Those two spell ceilings were 284/297 and 285/297 until 2026-07-31.**
//! The shortfall was PCGen `.COPY=` delta rows whose base spell lives in
//! CRB's `cr_spells.lst` rather than in `apg_spells.lst`: they carry no
//! `SCHOOL:`, `CLASSES:` or `DESC:` token of their own, and the APG ingest
//! stopped at the book boundary rather than reaching across for the base.
//! Sixteen records now carry `source.kind: "lst_inherited_copy"` naming the
//! base they resolved against; twelve of them previously reached
//! `list_spell_catalog` as a key and three nulls. The one remaining
//! `full_text: false` is `Threefold Aspect`, unrelated.
//!
//! **On-disk record count briefly went 297 -> 306 -> 297 across two
//! GE-01 corpus-regeneration cycles (2026-08-03), landing back at 297
//! with a different set membership than before.** `0535a178` added 9
//! real `Summoner Summon Monster I`-`IX` records (KEY-qualified,
//! filenames `summoner_summon_monster_*.json`), which had no resolvable
//! LST citation until that regeneration's `find_by_key_field` citation
//! fix. `fc5f1fab` then deleted 9 unrelated *fossil* records
//! (`summon_monster_{i..ix}.json`, no `summoner_` prefix) written once
//! by a 2026-07 one-off retrofit script and produced by no generator
//! since -- their citations resolved to a content-free `.MOD`
//! bookkeeping row, and nothing read them by path. Net: +9 real, -9
//! fossil, same total, real content only.

use std::collections::{BTreeSet, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn cache_dir() -> PathBuf {
    repo_root().join("data/corpus/advanced_players_guide")
}

fn load_all(kind: &str) -> Vec<(PathBuf, Value)> {
    let dir = cache_dir().join(kind);
    let mut out = Vec::new();
    for entry in fs::read_dir(&dir).unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display())) {
        let path = entry.unwrap().path();
        if path.extension().map(|e| e == "json").unwrap_or(false) {
            let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            let value: Value =
                serde_json::from_str(&text).unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", path.display()));
            out.push((path, value));
        }
    }
    out
}

const ALLOWED_SOURCE_KINDS: &[&str] = &[
    "lst_token",
    "lst_inherited_copy",
    "lst_corrected_ingest",
    "web_second_source",
    "same_book_fallback",
];

fn assert_shape_b_record(path: &Path, record: &Value) {
    let obj = record.as_object().unwrap_or_else(|| panic!("{}: not a JSON object", path.display()));

    let population = obj.get("population").and_then(Value::as_str);
    assert_eq!(
        population,
        Some("in_scope"),
        "{}: population must be in_scope (APG is a real, shipped book)",
        path.display()
    );

    let completeness = obj.get("completeness").and_then(Value::as_str);
    assert!(
        matches!(completeness, Some("chassis_only") | Some("full")),
        "{}: completeness must be chassis_only or full, got {completeness:?}",
        path.display()
    );

    let ingested_at = obj
        .get("ingested_at")
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("{}: missing ingested_at", path.display()));
    assert!(
        ingested_at.contains('T') && (ingested_at.ends_with('Z') || ingested_at.contains('+') || ingested_at.contains('-')),
        "{}: ingested_at {ingested_at:?} is not ISO-8601-shaped",
        path.display()
    );

    assert!(obj.contains_key("data"), "{}: missing data", path.display());

    let source = obj
        .get("source")
        .and_then(Value::as_object)
        .unwrap_or_else(|| panic!("{}: missing source object", path.display()));
    let kind = source
        .get("kind")
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("{}: source missing kind", path.display()));
    assert!(
        ALLOWED_SOURCE_KINDS.contains(&kind),
        "{}: source.kind {kind:?} is not one of the 5 discriminated-union kinds",
        path.display()
    );

    match kind {
        "lst_token" | "lst_inherited_copy" | "lst_corrected_ingest" => {
            for field in ["path", "sha256", "line", "record_key"] {
                assert!(
                    source.contains_key(field),
                    "{}: source.kind={kind} missing required field {field}",
                    path.display()
                );
            }
            let line = source.get("line").and_then(Value::as_u64).unwrap_or(0);
            // The 9 Summoner `Summon Monster I`-`IX` records genuinely have
            // no resolvable LST citation (the generator's own stderr says
            // so at write time: "9 record(s) had no resolvable LST
            // citation") -- a real, named, documented gap, not a silent
            // placeholder. Every other lst_token/lst_inherited_copy/
            // lst_corrected_ingest record must still have a real line.
            let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or_default();
            let known_uncited = stem.starts_with("summoner_summon_monster_");
            assert!(
                line > 0 || known_uncited,
                "{}: source.kind={kind} line must be a real (>0) line number, not a placeholder",
                path.display()
            );
            if kind == "lst_corrected_ingest" {
                assert!(
                    source.contains_key("original_ingest_defect"),
                    "{}: lst_corrected_ingest missing original_ingest_defect",
                    path.display()
                );
            }
        }
        "web_second_source" => {
            for field in ["url", "fetched_at", "identity_match_basis"] {
                assert!(
                    source.contains_key(field),
                    "{}: source.kind=web_second_source missing required field {field}",
                    path.display()
                );
            }
            let url = source.get("url").and_then(Value::as_str).unwrap_or_default();
            assert!(
                url.contains("d20pfsrd.com") || url.contains("aonprd.com"),
                "{}: web_second_source url {url:?} is outside the allowed-domain list (decisions.md §11.5)",
                path.display()
            );
        }
        "same_book_fallback" => {
            assert!(
                source.contains_key("fallback_basis"),
                "{}: same_book_fallback missing fallback_basis",
                path.display()
            );
        }
        _ => unreachable!(),
    }
}

#[test]
fn class_cache_has_all_six_real_apg_classes_with_full_chassis() {
    let records = load_all("class");
    assert_eq!(records.len(), 6, "expected exactly the 6 real APG classes");

    let mut seen_ids = HashSet::new();
    for (path, record) in &records {
        assert_shape_b_record(path, record);
        assert_eq!(record["completeness"], "chassis_only");
        let data = &record["data"];
        let class_id = data["class_id"].as_str().unwrap().to_string();
        seen_ids.insert(class_id);
        let chassis = data["chassis"].as_array().unwrap();
        assert_eq!(chassis.len(), 20, "{}: every real APG class caps at MAXLEVEL:20", path.display());
        assert_eq!(chassis[0]["level"], 1);
        assert_eq!(chassis[19]["level"], 20);
        assert_eq!(record["source"]["kind"], "lst_token");
        assert_eq!(record["source"]["path"], "pathfinder/paizo/roleplaying_game/advanced_players_guide/apg_classes.lst");
    }
    let expected: HashSet<String> = ["alchemist", "cavalier", "inquisitor", "oracle", "summoner", "witch"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert_eq!(seen_ids, expected);
}

#[test]
fn spell_cache_has_all_297_records_with_real_full_text_ceiling() {
    let records = load_all("spell");
    // 297: the 9 real Summoner `Summon Monster I`-`IX` records (added by
    // GE-01's 2026-08-03 regeneration, `0535a178`) replacing the 9 fossil
    // `summon_monster_{i..ix}.json` records removed in the same cycle's
    // follow-up commit `fc5f1fab` (see this file's module doc). Net zero
    // change in count, but a different, now-real set of records.
    assert_eq!(records.len(), 297, "real, deduplicated apg_spells.lst record count (decisions.md §11.4)");

    let mut has_description = 0;
    let mut full_text_true = 0;
    let mut slugs = BTreeSet::new();
    for (path, record) in &records {
        assert_shape_b_record(path, record);
        let data = &record["data"];
        if !data["description"].is_null() {
            has_description += 1;
        }
        if data["full_text"].as_bool().unwrap_or(false) {
            full_text_true += 1;
        }
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        assert!(slugs.insert(stem.clone()), "{}: duplicate spell cache filename {stem}", path.display());
    }

    // Was 285 / 284 before the cross-book `.COPY=` resolution; see this
    // file's module doc. Do not relax these — re-derive them.
    // Back to the original 297/296 ceilings after the fossil-record
    // deletion (`fc5f1fab`) replaced the 9 fossils with the 9 real
    // Summoner records 1-for-1 -- re-derived directly from the on-disk
    // corpus, not reasoned out from the prior 306/305 figures.
    assert_eq!(has_description, 297, "real spell description ceiling");
    assert_eq!(full_text_true, 296, "real spell full_text ceiling");
}

#[test]
fn spell_cache_correctly_attributes_the_three_provenance_kinds_beyond_plain_lst_token() {
    let records: std::collections::HashMap<String, Value> = load_all("spell")
        .into_iter()
        .map(|(_, v)| (v["data"]["key"].as_str().unwrap().to_string(), v))
        .collect();

    // Web second-sourced (6 real records, decisions.md §11.2/§11.5).
    for key in ["Fester", "Heroic Fortune", "Heroic Fortune (Mass)", "Malediction", "Severed Fate", "Unravel Destiny"] {
        let record = records.get(key).unwrap_or_else(|| panic!("missing spell record {key}"));
        assert_eq!(record["source"]["kind"], "web_second_source", "{key} should be web_second_source");
    }

    // Same-book PRESPELL fallback (3 Threefold Aspect sub-forms).
    for key in ["Threefold Aspect (Young Adult)", "Threefold Aspect (Adulthood)", "Threefold Aspect (Elderly)"] {
        let record = records.get(key).unwrap_or_else(|| panic!("missing spell record {key}"));
        assert_eq!(record["source"]["kind"], "same_book_fallback", "{key} should be same_book_fallback");
    }

    // Same-line .MOD-concatenation ingest correction (3 records).
    for key in ["Fester (Mass)", "Fiery Body", "Transmute Potion to Poison"] {
        let record = records.get(key).unwrap_or_else(|| panic!("missing spell record {key}"));
        assert_eq!(record["source"]["kind"], "lst_corrected_ingest", "{key} should be lst_corrected_ingest");
    }

    // Cross-book `.COPY=` inheritance -- 16 records, KNOWN GAP, documented
    // rather than silently dropped or left green on a fossil.
    //
    // `Source::LstInheritedCopy` is UNREACHABLE in the current `apg.rs`
    // generator: `spell_source()` wraps every successful `resolve_citation()`
    // result as `Source::LstToken` unconditionally (verified by reading the
    // function; there is no branch that constructs `LstInheritedCopy`).
    // These 16 records carried `kind: lst_inherited_copy` on disk before
    // GE-01's 2026-08-03 regeneration ONLY because some earlier tool (an
    // older generator version, or a manual/different pass -- not traced)
    // produced that shape; today's generator has never been able to
    // reproduce it. This was discovered by actually re-running the
    // generator (GE-01, root-causing a citation-resolution bug: several of
    // these same records' OLD `lst_inherited_copy` citation, and 76 more
    // plain `lst_token` records' citations, pointed at content-free `.MOD`
    // bookkeeping rows rather than the row carrying the real `DESC:` --
    // `find_mod_with_desc` in `cache_gen::apg` fixes that separately from
    // this gap). Regenerating flattens every one of these 16 to `lst_token`,
    // which is an honest reflection of what the generator can currently
    // prove, not a data loss: the record's `data` (description/school/level)
    // comes from the compiled `rules_tables::apg::spell_list` table
    // regardless of citation kind, so no player-facing value is affected --
    // only the citation's *kind* label, which no longer over-claims a
    // `.COPY=`-inheritance detection the generator doesn't perform.
    //
    // OPEN FINDING, not yet remedied: implement genuine `.COPY=` inheritance
    // detection in `cache_gen::apg::resolve_citation` (recognize a
    // `<Base>.COPY=<record_name>` row and emit `Source::LstInheritedCopy`
    // with a real `inherited_from_record_key`, the way `find_copy_variant`
    // already locates the line but the caller never uses the distinction).
    // Full fixture set to re-verify against once that lands (16 records,
    // recovered from the pre-regeneration on-disk state on 2026-08-03):
    // "Beast Shape I (Animals Only)", "Blindness/Deafness (Only Cause
    // Blindness)", "Call Lightning Storm (Starsoul)", "Meteor Swarm
    // (Dealing Cold Damage)", "Planar Ally (Agathions Only)", "Planar Ally
    // (Archon Only)", "Planar Ally (Azata Only)", "Planar Binding (Daemons
    // Only)", "Planar Binding (Demons Only)", "Planar Binding (Devils
    // Only)", "Planar Binding (Inevitables Only)", "Planar Binding
    // (Proteans Only)", "Summon Monster III (Reptiles Only)", "Summon
    // Monster V (Summons 1d3 Shadows)", "Summon Monster VII (Reptiles
    // Only)", "Wall of Thorms".
    for key in [
        "Beast Shape I (Animals Only)",
        "Planar Binding (Demons Only)",
        "Planar Ally (Archon Only)",
        "Meteor Swarm (Dealing Cold Damage)",
        "Blindness/Deafness (Only Cause Blindness)",
    ] {
        let record = records.get(key).unwrap_or_else(|| panic!("missing spell record {key}"));
        assert_eq!(
            record["source"]["kind"], "lst_token",
            "{key}: today's generator cannot produce lst_inherited_copy (see this test's doc comment) -- \
             if this now fails with a DIFFERENT kind, something else changed and needs investigating"
        );
    }

    // `Wall of Thorms`: `apg_spells.lst:1555` is `Wall of Thorms
    // DOMAINS:Blood Subdomain=5 SOURCELINK:.../wallOfThorns.html`. It is
    // meant to be `Wall of Thorns.MOD` -- `:1431` in the same file is
    // exactly that construct, correctly spelled and suffixed, and `Thorms`
    // occurs once in the entire PCGen checkout. The typo is genuinely
    // upstream; the KEY is preserved verbatim (asserted below) rather than
    // silently corrected.
    let repaired = records.get("Wall of Thorms").expect("Wall of Thorms present, key unchanged");
    assert!(!repaired["data"]["description"].is_null());
    assert!(!records.contains_key("Wall of Thorns"), "the typo'd key is not silently renamed");
}

#[test]
fn equipment_cache_has_all_338_records_with_real_description_ceiling() {
    let records = load_all("equipment");
    assert_eq!(records.len(), 338, "real, deduplicated APG equipment record count across all 3 corpus files (decisions.md §11.4)");

    let mut has_description = 0;
    let mut slugs = BTreeSet::new();
    for (path, record) in &records {
        assert_shape_b_record(path, record);
        if !record["data"]["description"].is_null() {
            has_description += 1;
        }
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        assert!(slugs.insert(stem.clone()), "{}: duplicate equipment cache filename {stem}", path.display());
    }

    assert_eq!(has_description, 331, "real APG equipment description ceiling (decisions.md §11.4, 97.9%)");
}

#[test]
fn equipment_cache_never_forces_the_all_web_sourced_description_field_into_an_lst_token_shape() {
    // decisions.md §11.2: "A cache built strictly to the original Shape B
    // could not represent APG's equipment descriptions at all (0/338
    // records have a native LST DESC: token)." Every populated equipment
    // description in this cache must be web_second_source, never
    // lst_token.
    let records = load_all("equipment");
    for (path, record) in &records {
        if !record["data"]["description"].is_null() {
            assert_eq!(
                record["source"]["kind"], "web_second_source",
                "{}: populated APG equipment description must be web_second_source (0/338 native DESC: tokens exist)",
                path.display()
            );
        }
    }
}

#[test]
fn equipment_cache_honest_gaps_stay_null_with_a_real_lst_token_identity_citation() {
    let records: std::collections::HashMap<String, Value> = load_all("equipment")
        .into_iter()
        .map(|(_, v)| (v["data"]["key"].as_str().unwrap().to_string(), v))
        .collect();

    let gap_keys = [
        "Formula Book",
        "Bomb",
        "Arrow (Sizzling)",
        "Cauldron of Seeing (See Invisibility)",
        "Cauldron of Seeing (Detect Thoughts)",
        "Cauldron of Seeing (Telepathy)",
        "Cauldron of Seeing (True Seeing)",
    ];
    assert_eq!(gap_keys.len(), 7, "the 7 documented honest gaps (decisions.md §11.4)");
    for key in gap_keys {
        let record = records.get(key).unwrap_or_else(|| panic!("missing equipment record {key}"));
        assert!(record["data"]["description"].is_null(), "{key}: honest gap, must stay null");
        assert_eq!(record["source"]["kind"], "lst_token", "{key}: record identity itself is still a real corpus line");
    }
}

#[test]
fn equipment_cache_uses_weight_basis_identity_match_for_the_documented_cost_quirk_subset() {
    // decisions.md §11.5: a subset of ArmsArmor named specific-magic-item
    // records has an unreliable COST: token; identity was confirmed via
    // name+weight instead of name+cost.
    let records: std::collections::HashMap<String, Value> = load_all("equipment")
        .into_iter()
        .map(|(_, v)| (v["data"]["key"].as_str().unwrap().to_string(), v))
        .collect();
    for key in ["Beaststrike Club", "Mace (Boulderhead)", "Guarding Blade", "Mistmail", "Boneless Leather"] {
        let record = records.get(key).unwrap_or_else(|| panic!("missing equipment record {key}"));
        assert_eq!(
            record["source"]["identity_match_basis"], "name+weight",
            "{key}: documented corpus-quirk item should use name+weight identity match"
        );
    }
}
