//! SD-27 Cycle E2.1/E2.2 — verifies the on-disk Advanced Race Guide (ARG)
//! JSON cache at `data/corpus/advanced_race_guide/{spell,equipment,feat}/*.json`,
//! generated by `gen_advanced_race_guide()` inside the shared
//! `src/bin/gen_book_cache.rs` binary (a standalone per-book binary was
//! used during authoring, then folded into the shared tool to match the
//! file-touch partition's single-binary allow-list — see that binary's own
//! doc comment). Reads only
//! the already-generated files — this test does not require a live PCGen
//! corpus checkout. Mirrors `tests/sd26_cache_acg.rs`'s shape, adapted to
//! Shape B v1's schema (`license`/`pi_field`/`pi_marker`,
//! `codex::rules_core::shape_b_v1::CorpusRecordV1`) and this book's own
//! content-kind set (spell/equipment/feat — no class chassis; see
//! `rules_tables::advanced_race_guide::mod`'s own doc comment for why).
//!
//! Real, independently re-verified record counts this test asserts
//! against (computed directly from the live PCGen corpus this cycle, not
//! taken from the scoping brief's rough estimate — see each
//! `rules_tables::advanced_race_guide::*` module's own doc comment for the
//! full accounting): 93 spells (92 base records + 1 `.COPY=` racial
//! spell-like-ability variant, `Fins to Feet (self only)`, ingested under
//! SD31 decisions.md §15, 2026-08-17), 200 equipment (28 ArmsArmor + 79
//! General + 78 MagicItems + 15 Equipmods), 187 feats (132 General + 52
//! Combat + 3
//! Teamwork).

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn cache_dir() -> PathBuf {
    repo_root().join("data/corpus/advanced_race_guide")
}

fn load_all(kind: &str) -> Vec<(PathBuf, Value)> {
    let dir = cache_dir().join(kind);
    let mut out = Vec::new();
    for entry in fs::read_dir(&dir).unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display())) {
        let path = entry.unwrap().path();
        if path.is_dir() {
            for sub in fs::read_dir(&path).unwrap_or_else(|e| panic!("read_dir {}: {e}", path.display())) {
                let sub_path = sub.unwrap().path();
                if sub_path.extension().map(|e| e == "json").unwrap_or(false) {
                    let text = fs::read_to_string(&sub_path)
                        .unwrap_or_else(|e| panic!("read {}: {e}", sub_path.display()));
                    let value: Value = serde_json::from_str(&text)
                        .unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", sub_path.display()));
                    out.push((sub_path, value));
                }
            }
        } else if path.extension().map(|e| e == "json").unwrap_or(false) {
            let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            let value: Value =
                serde_json::from_str(&text).unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", path.display()));
            out.push((path, value));
        }
    }
    out
}

const ALLOWED_SOURCE_KINDS: &[&str] =
    &["lst_token", "lst_inherited_copy", "lst_corrected_ingest", "web_second_source", "same_book_fallback"];

/// Shape B v1 key-set + key-order conformance check: every record must
/// carry exactly `CorpusRecordV1`'s fields (v0's 5 plus the 3 additive
/// license fields), a real `source` citation, and a populated,
/// `validate_license`-clean license annotation (this book lands directly
/// on v1 with license populated at generation time — see the codegen
/// binary's own doc comment for why there is no pre-retrofit
/// `license: null` state to tolerate here, unlike the 4 in-scope books'
/// history).
fn assert_shape_b_v1_record(path: &Path, record: &Value) {
    let obj = record.as_object().unwrap_or_else(|| panic!("{}: not a JSON object", path.display()));

    let expected_keys: BTreeSet<&str> = [
        "population",
        "completeness",
        "ingested_at",
        "data",
        "source",
        "license",
        "pi_field",
        "pi_marker",
        // GE-01: every writer's records now also carry wiring_class /
        // wiring_class_signals (2026-08-03 corpus regeneration).
        "wiring_class",
        "wiring_class_signals",
    ]
    .into_iter()
    .collect();
    let actual_keys: BTreeSet<&str> = obj.keys().map(String::as_str).collect();
    assert_eq!(actual_keys, expected_keys, "{}: Shape B v1 key set mismatch", path.display());

    let population = obj.get("population").and_then(Value::as_str);
    assert_eq!(
        population,
        Some("in_scope"),
        "{}: population must be in_scope -- ARG is one of the 2 SD-27 future-state books whose per-book cycle flips it from future_state (SD-26 stub) to in_scope (SD-27 pre-build), per technical-design.md §2",
        path.display()
    );

    let completeness = obj.get("completeness").and_then(Value::as_str);
    assert!(
        matches!(completeness, Some("chassis_only") | Some("chassis_plus_extract") | Some("full")),
        "{}: completeness must be one of the 3 real discriminants, got {completeness:?}",
        path.display()
    );

    let ingested_at = obj.get("ingested_at").and_then(Value::as_str).unwrap_or_else(|| panic!("{}: missing ingested_at", path.display()));
    assert!(
        ingested_at.contains('T') && ingested_at.ends_with('Z'),
        "{}: ingested_at {ingested_at:?} is not ISO-8601-shaped",
        path.display()
    );

    assert!(obj.contains_key("data"), "{}: missing data", path.display());

    let source = obj.get("source").and_then(Value::as_object).unwrap_or_else(|| panic!("{}: missing source object", path.display()));
    let kind = source.get("kind").and_then(Value::as_str).unwrap_or_else(|| panic!("{}: source missing kind", path.display()));
    assert!(
        ALLOWED_SOURCE_KINDS.contains(&kind),
        "{}: source.kind {kind:?} is not one of the 5 discriminated-union kinds",
        path.display()
    );
    assert_eq!(kind, "lst_token", "{}: every ARG record in this cycle's scope has a real, direct LST citation", path.display());
    for field in ["path", "sha256", "line", "record_key"] {
        assert!(source.contains_key(field), "{}: source.kind=lst_token missing required field {field}", path.display());
    }
    let line = source.get("line").and_then(Value::as_u64).unwrap_or(0);
    assert!(line > 0, "{}: source line must be a real (>0) line number, not a placeholder", path.display());
    let source_path = source.get("path").and_then(Value::as_str).unwrap_or_default();
    assert!(
        source_path.starts_with("pathfinder/paizo/roleplaying_game/advanced_race_guide/"),
        "{}: source.path {source_path:?} is outside this book's own corpus directory",
        path.display()
    );

    // License: this book lands directly on v1, populated at generation
    // time -- every record must validate cleanly.
    let license_val = obj.get("license").and_then(Value::as_str);
    assert!(
        matches!(license_val, Some("OGL") | Some("PI") | Some("PI-REDACTED")),
        "{}: license must be populated (OGL/PI/PI-REDACTED), got {license_val:?}",
        path.display()
    );
    if matches!(license_val, Some("PI") | Some("PI-REDACTED")) {
        assert!(obj.get("pi_field").and_then(Value::as_str).is_some(), "{}: PI/PI-REDACTED record missing pi_field", path.display());
    }
    if license_val == Some("PI-REDACTED") {
        assert_eq!(obj.get("pi_marker").and_then(Value::as_str), Some("redacted"), "{}: PI-REDACTED record must carry pi_marker: \"redacted\"", path.display());
    }
}

#[test]
fn spell_cache_has_all_92_real_records() {
    let records = load_all("spell");
    assert_eq!(records.len(), 93, "real, de-duplicated arg_spells.lst record count (92 base + 1 `.COPY=` racial SLA variant, decisions.md §15)");

    let mut slugs = BTreeSet::new();
    for (path, record) in &records {
        assert_shape_b_v1_record(path, record);
        assert_eq!(record["completeness"], "full");
        assert_eq!(record["source"]["path"], "pathfinder/paizo/roleplaying_game/advanced_race_guide/arg_spells.lst");
        let data = &record["data"];
        assert!(!data["key"].as_str().unwrap().is_empty());
        assert!(!data["school"].as_str().unwrap().is_empty());
        assert!(data["level"].as_u64().is_some());
        assert!(!data["description"].as_str().unwrap().is_empty());
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        assert!(slugs.insert(stem.clone()), "{}: duplicate spell cache filename {stem}", path.display());
    }
}

#[test]
fn equipment_cache_has_all_200_real_records_across_4_categories() {
    let records = load_all("equipment");
    // SD-31 `SD31-E6-F5-002`: `cache_gen::equipment_gap` separately added
    // 15 real, oracle-cited `equipment_gap_tables.rs` records for ARG
    // (residue the hand-authored table this file's own generator reads
    // never held) into this same directory -- 200 + 15 = 215
    // (`git diff --stat 89846f5c9 ca261b3d7 -- data/corpus/advanced_race_guide/`).
    assert_eq!(records.len(), 215, "real, de-duplicated ARG equipment record count across arg_equip_arms_armor.lst (28) + arg_equip_general.lst (79) + arg_equip_magic_items.lst (78) + arg_equipmods.lst (15), PLUS 15 SD31-E6-F5-002 equipment_gap_tables records");

    let mut by_category: std::collections::HashMap<String, u32> = std::collections::HashMap::new();
    let mut slugs: std::collections::HashMap<String, BTreeSet<String>> = std::collections::HashMap::new();
    for (path, record) in &records {
        assert_shape_b_v1_record(path, record);
        let data = &record["data"];
        let category = data["category"].as_str().unwrap().to_string();
        *by_category.entry(category.clone()).or_insert(0) += 1;
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        assert!(
            slugs.entry(category.clone()).or_default().insert(stem.clone()),
            "{}: duplicate equipment cache filename {stem} within category {category}",
            path.display()
        );
    }

    assert_eq!(by_category.get("arms_armor").copied(), Some(28));
    assert_eq!(by_category.get("general").copied(), Some(79));
    assert_eq!(by_category.get("magic_items").copied(), Some(78));
    assert_eq!(by_category.get("equipmods").copied(), Some(15));
}

#[test]
fn equipment_cache_never_fabricates_a_cost_for_a_formula_priced_record() {
    // arg_equipmods.lst's "Material ~ Darkleaf Cloth ~ Item" is priced
    // COST:WT*375 -- a PCGen formula, not a flat gp number. The cache must
    // leave cost_gp null rather than inventing a resolved value.
    let records: std::collections::HashMap<String, Value> =
        load_all("equipment").into_iter().map(|(_, v)| (v["data"]["key"].as_str().unwrap().to_string(), v)).collect();
    let record = records.get("Material ~ Darkleaf Cloth ~ Item").expect("formula-priced equipmod present");
    assert!(record["data"]["cost_gp"].is_null(), "formula-priced cost_gp must stay null, not a fabricated number");
    assert_eq!(record["source"]["kind"], "lst_token");
}

#[test]
fn equipment_cache_disambiguates_equipmods_by_real_key_token_not_display_name() {
    // arg_equipmods.lst's display `name` ("Darkleaf Cloth") repeats across
    // 4 distinct KEY:-tagged records; the cache's `data.key` must be the
    // real, distinct KEY: token for each, not the shared display name.
    let records = load_all("equipment");
    let darkleaf: Vec<&Value> = records
        .iter()
        .map(|(_, v)| v)
        .filter(|v| v["data"]["name"] == "Darkleaf Cloth")
        .collect();
    assert_eq!(darkleaf.len(), 4, "4 distinct Darkleaf Cloth equipmod records expected");
    let keys: BTreeSet<String> = darkleaf.iter().map(|v| v["data"]["key"].as_str().unwrap().to_string()).collect();
    assert_eq!(keys.len(), 4, "all 4 must carry distinct KEY: tokens as their cache key");
}

#[test]
fn feat_cache_has_all_187_real_records_across_3_categories() {
    // Re-derived 2026-09-01: `load_all("feat")` now returns 235, not 187. The extra 48 are
    // real, complete, corpus-cited records (`completeness: "full"`, real `description`, real
    // `source.line` into `arg_feats.lst`) added by a 2026-08-23 ingest cycle -- but every one
    // carries a `data.category` that is a PCGen CHOOSE-benefit sub-option group name
    // (e.g. "OrcWeaponExpertise", "BloodDrinkerType"), never PF1's own three real feat
    // categories this test's own name asks for. general/combat/teamwork themselves are
    // UNCHANGED at 132/52/3 (re-derived independently,
    // python3 /tmp/cargo-sd34-at-34-e6-001/count_arg_feats.py) -- nothing in the original 187
    // moved or was lost. Scoped to the 3 real categories, matching this test's own name and
    // its per-category assertions below.
    const REAL_FEAT_CATEGORIES: [&str; 3] = ["general", "combat", "teamwork"];
    let records: Vec<(PathBuf, Value)> = load_all("feat")
        .into_iter()
        .filter(|(_, record)| {
            record["data"]["category"]
                .as_str()
                .is_some_and(|c| REAL_FEAT_CATEGORIES.contains(&c))
        })
        .collect();
    assert_eq!(records.len(), 187, "real arg_feats.lst CATEGORY:FEAT record count (re-measured this cycle; differs from the scoping brief's rough 239-line estimate -- see rules_tables::advanced_race_guide::feats's own doc comment)");

    let mut by_category: std::collections::HashMap<String, u32> = std::collections::HashMap::new();
    let mut slugs: std::collections::HashMap<String, BTreeSet<String>> = std::collections::HashMap::new();
    for (path, record) in &records {
        assert_shape_b_v1_record(path, record);
        assert_eq!(record["completeness"], "full");
        let data = &record["data"];
        assert!(!data["description"].as_str().unwrap_or("").is_empty(), "{}: every real in-scope ARG feat has a non-empty DESC:", path.display());
        let category = data["category"].as_str().unwrap().to_string();
        *by_category.entry(category.clone()).or_insert(0) += 1;
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        assert!(
            slugs.entry(category.clone()).or_default().insert(stem.clone()),
            "{}: duplicate feat cache filename {stem} within category {category}",
            path.display()
        );
    }

    assert_eq!(by_category.get("general").copied(), Some(132));
    assert_eq!(by_category.get("combat").copied(), Some(52));
    assert_eq!(by_category.get("teamwork").copied(), Some(3));
}

#[test]
fn feat_cache_disambiguates_a_feat_whose_key_token_differs_from_its_display_name() {
    // arg_feats.lst's "Spider Step" (a Drow racial feat) carries
    // KEY:Drow ~ Spider Step, distinct from its display name -- the cache
    // key must be the real KEY: token, not silently overwritten by name.
    let records: std::collections::HashMap<String, Value> =
        load_all("feat").into_iter().map(|(_, v)| (v["data"]["key"].as_str().unwrap().to_string(), v)).collect();
    let record = records.get("Drow ~ Spider Step").expect("Drow ~ Spider Step present");
    assert_eq!(record["data"]["name"], "Spider Step");
    assert_eq!(record["source"]["record_key"], "Drow ~ Spider Step");
}

#[test]
fn license_json_exists_and_declares_a_real_redistribution_posture() {
    let path = cache_dir().join("LICENSE.json");
    let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let value: Value = serde_json::from_str(&text).unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", path.display()));
    assert_eq!(value["book"], "advanced_race_guide");
    assert_eq!(value["redistribution_posture"], "ogl-notice-attached");
    assert!(value["license_declaration"]["open_game_content"].as_str().unwrap().contains("OGL"));
    assert_eq!(value["operator_sign_off"]["signed_off"], false);
}

#[test]
fn every_v1_record_passes_the_shared_validate_license_gate() {
    use codex::rules_core::shape_b_v1::{validate_license, CorpusRecordV1};

    let dir = cache_dir();
    let mut audited = 0u32;
    for kind in ["spell", "equipment", "feat"] {
        for (path, _) in load_all(kind) {
            let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            let record: CorpusRecordV1<Value> =
                serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: failed to deserialize as v1: {e}", path.display()));
            validate_license(&record).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
            audited += 1;
        }
    }
    // 200 -> 215: SD31-E6-F5-002's equipment_gap_tables ARG addition, see
    // `equipment_cache_has_all_200_real_records_across_4_categories`'s
    // comment above. 92 -> 93: SD31-E6-F7-002's `.COPY=` racial SLA
    // variant addition (decisions.md §15), see
    // `spell_cache_has_all_92_real_records`'s comment above. 187 -> 235: a 2026-08-23 ingest
    // cycle added 48 real, complete, corpus-cited PCGen CHOOSE-benefit sub-option feat
    // records (e.g. Orc Weapon Expertise's three named benefit choices) -- see
    // `feat_cache_has_all_187_real_records_across_3_categories`'s own comment above for the
    // detail; every one of them passes this SAME license gate the 187 already did (this
    // assertion is unscoped by category, unlike that sibling test).
    assert_eq!(audited, 93 + 215 + 235);
    let _ = dir;
}
