//! core_essentials companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py core_essentials`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `ce_races_familiar_apg.lst` -- 8 companion creature rows
//!   * `ce_races_familiar_cr.lst` -- 31 companion creature rows
//!   * `ce_races_familiar_um.lst` -- 19 companion creature rows
//!   * `ce_abilities_familiar_race_cr.lst` -- 36 companion ability rows
//!   * `ce_abilities_familiar_race_um.lst` -- 8 companion ability rows
//!
//! NOT transcribed -- ability rows no creature row of this book owns, so
//! nothing could ever reach them on screen. Dropped rather than emitted
//! unreachable (`decisions.md §50`, adopted from the monster lane; §56.1).
//! These rows keep their `not-ingested` status in
//! `docs/work-inventory.json`, which is where the shortfall is counted; they
//! are NOT a `reach_gate` `OPEN_FINDINGS` entry, because that list is keyed by
//! FAMILY and this book's `companions` family does reach a player:
//!   * `Familiar Alertness Choice ~ Alertness Active`
//!   * `Familiar Alertness Choice ~ Alertness Inactive`
//!   * `Familiar ~ Alertness`
//!   * `Familiar ~ Deliver Touch Spells`
//!   * `Familiar ~ Empathic Link`
//!   * `Familiar ~ Improved Evasion`
//!   * `Familiar ~ Intelligence Score`
//!   * `Familiar ~ Natural Armor Bonus`
//!   * `Familiar ~ Scry on Familiar`
//!   * `Familiar ~ Share Spells`
//!   * `Familiar ~ Speak One Language`
//!   * `Familiar ~ Speak with Animals of Its Kind`
//!   * `Familiar ~ Speak with Master`
//!   * `Familiar ~ Spell Resistance`
//!   * `Greensting Scorpion ~ Poison`
//!   * `Mephit ~ Summon`
//!
//! NOT transcribed -- rows that state a DELTA on another record rather than
//! a record of their own. Transcribing one verbatim ships a card with almost
//! every field empty; resolving it needs a second citation this chassis does
//! not carry (`decisions.md §59.2`, adopting the monster lane's `.COPY=`
//! screen). Their owners no longer name them:
//!   * `Universal Monster Rule ~ Change Shape` (`origin: mod_only`)
//!   * `Universal Monster Rule ~ Disease (Extraordinary)` (`origin: mod_only`)
//!   * `Universal Monster Rule ~ Fast Healing` (`origin: mod_only`)
//!   * `Universal Monster Rule ~ Poison (Extraordinary)` (`origin: mod_only`)
//!
//! NOT transcribed -- CREATURE rows that state a DELTA on another record
//! (`decisions.md §62.1`). PCGen copies the base creature whole and applies
//! the few tokens the copy row carries, so the row itself states no `SIZE:`,
//! no `MOVE:` and no `MONSTERCLASS:` -- transcribed verbatim it is a creature
//! card with a name and nothing else. Any ability reachable only from one of
//! these is carried as an orphan above, not shipped unowned:
//!   * `Bat (Celestial)` (`origin: copy`)
//!   * `Bat (Fiendish)` (`origin: copy`)
//!   * `Cat (Celestial)` (`origin: copy`)
//!   * `Cat (Fiendish)` (`origin: copy`)
//!   * `Hawk (Celestial)` (`origin: copy`)
//!   * `Hawk (Fiendish)` (`origin: copy`)
//!   * `Lizard (Celestial)` (`origin: copy`)
//!   * `Lizard (Fiendish)` (`origin: copy`)
//!   * `Monkey (Celestial)` (`origin: copy`)
//!   * `Monkey (Fiendish)` (`origin: copy`)
//!   * `Owl (Celestial)` (`origin: copy`)
//!   * `Owl (Fiendish)` (`origin: copy`)
//!   * `Rat (Celestial)` (`origin: copy`)
//!   * `Rat (Fiendish)` (`origin: copy`)
//!   * `Raven (Celestial)` (`origin: copy`)
//!   * `Raven (Fiendish)` (`origin: copy`)
//!   * `Toad (Celestial)` (`origin: copy`)
//!   * `Toad (Fiendish)` (`origin: copy`)
//!   * `Viper (Celestial)` (`origin: copy`)
//!   * `Viper (Fiendish)` (`origin: copy`)
//!   * `Weasel (Celestial)` (`origin: copy`)
//!   * `Weasel (Fiendish)` (`origin: copy`)
//!
//! NOT transcribed -- OWNED rows that state nothing this chassis models
//! (`decisions.md §62.3`). The row carries no `TYPE:`, no `DESC:` and no
//! `BONUS:`, so every modelled field transcribes empty and the card reads as
//! a name over a page number. What each one DOES state is an `ASPECT:`, which
//! no chassis in this program models yet -- the disposition is `§61.2`'s:
//! dropped, named here, left honestly `not-ingested`:
//!   * `Pseudodragon ~ Tail`

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, Speed, StatAdjustment};

/// Every core_essentials companion creature (58 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Familiar (Blue-Ringed Octopus)",
        name: "Familiar (Blue-Ringed Octopus)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 30 }, Speed { mode: "Jet", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Tentacles", damage_dice: Some("0") }, NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 10 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: None,
        source_page: Some("p.117"),
        ability_keys: &["Blue-Ringed Octopus ~ Ink Cloud", "Blue-Ringed Octopus ~ Jet", "Blue-Ringed Octopus ~ Poison"],
        external_ability_refs: &["Can't Be Tripped", "Grab"],
        source_file: "ce_races_familiar_um.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Familiar (Centipede (House))",
        name: "Familiar (Centipede (House))",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Climb", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Vermin"),
        race_subtype: None,
        monster_class: Some("Vermin:1"),
        type_segments: &["Companion", "Familiar"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -9 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CHA", amount: -8 }, StatAdjustment { ability: "INT", amount: -9 }],
        natural_armor: Some(2),
        source_page: Some("p.43"),
        ability_keys: &[],
        external_ability_refs: &["Can't Be Tripped", "Giant Centipede Companion ~ Poison"],
        source_file: "ce_races_familiar_apg.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Familiar (Crab (Giant King))",
        name: "Familiar (Crab (Giant King))",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Vermin"),
        race_subtype: None,
        monster_class: Some("Vermin:1"),
        type_segments: &["Companion", "Familiar"],
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }, StatAdjustment { ability: "INT", amount: -9 }],
        natural_armor: Some(5),
        source_page: Some("p.50"),
        ability_keys: &[],
        external_ability_refs: &["Constrict", "Crab Companion ~ Water Dependency", "Grab"],
        source_file: "ce_races_familiar_apg.lst",
        source_line: 7,
    },
    CompanionRecord {
        key: "Familiar (Donkey Rat)",
        name: "Familiar (Donkey Rat)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.117"),
        ability_keys: &[],
        external_ability_refs: &["Scent"],
        source_file: "ce_races_familiar_um.lst",
        source_line: 7,
    },
    CompanionRecord {
        key: "Familiar (Fox)",
        name: "Familiar (Fox)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.87"),
        ability_keys: &[],
        external_ability_refs: &["Scent"],
        source_file: "ce_races_familiar_apg.lst",
        source_line: 8,
    },
    CompanionRecord {
        key: "Familiar (Goat)",
        name: "Familiar (Goat)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.118"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Familiar (Octopus)",
        name: "Familiar (Octopus)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:2"),
        type_segments: &["Companion", "Familiar"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Tentacle", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(1),
        source_page: Some("p.219"),
        ability_keys: &[],
        external_ability_refs: &["Can't Be Tripped", "Grab", "Octopus Companion ~ Ink Cloud", "Octopus Companion ~ Jet", "Octopus Companion ~ Poison"],
        source_file: "ce_races_familiar_apg.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Familiar (Scorpion (Greensting))",
        name: "Familiar (Scorpion (Greensting))",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Vermin"),
        race_subtype: None,
        monster_class: Some("Vermin:1"),
        type_segments: &["Companion", "Familiar"],
        natural_attacks: &[NaturalAttack { name: "Sting", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CHA", amount: -8 }, StatAdjustment { ability: "INT", amount: -9 }],
        natural_armor: Some(3),
        source_page: Some("p.118"),
        ability_keys: &[],
        external_ability_refs: &["Greensting Scorpion Companion ~ Poison"],
        source_file: "ce_races_familiar_apg.lst",
        source_line: 10,
    },
    CompanionRecord {
        key: "Familiar (Hedgehog)",
        name: "Familiar (Hedgehog)",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -9 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: -4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.119"),
        ability_keys: &["Hedgehog ~ Spiny Defense"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 11,
    },
    CompanionRecord {
        key: "Familiar (Spider (Scarlet))",
        name: "Familiar (Spider (Scarlet))",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Vermin"),
        race_subtype: None,
        monster_class: Some("Vermin:1"),
        type_segments: &["Companion", "Familiar"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }, StatAdjustment { ability: "INT", amount: -9 }],
        natural_armor: Some(1),
        source_page: Some("p.258"),
        ability_keys: &[],
        external_ability_refs: &["Giant Spider Companion ~ Poison"],
        source_file: "ce_races_familiar_apg.lst",
        source_line: 11,
    },
    CompanionRecord {
        key: "Bat",
        name: "Bat",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -10 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.131"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Familiar (Parrot)",
        name: "Familiar (Parrot)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.133"),
        ability_keys: &[],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "ce_races_familiar_apg.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Familiar (Pig)",
        name: "Familiar (Pig)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 0 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.119"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Cat",
        name: "Cat",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.131"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 15,
    },
    CompanionRecord {
        key: "Familiar (Thrush)",
        name: "Familiar (Thrush)",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -9 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.120"),
        ability_keys: &[],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "ce_races_familiar_um.lst",
        source_line: 16,
    },
    CompanionRecord {
        key: "Hawk",
        name: "Hawk",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.131"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 16,
    },
    CompanionRecord {
        key: "Familiar (Turtle)",
        name: "Familiar (Turtle)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: -4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(6),
        source_page: Some("p.120"),
        ability_keys: &["Turtle ~ Shell Retreat"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 17,
    },
    CompanionRecord {
        key: "Lizard",
        name: "Lizard",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Climb", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -9 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: None,
        source_page: Some("p.131"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 17,
    },
    CompanionRecord {
        key: "Parrot",
        name: "Parrot",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.133"),
        ability_keys: &[],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "ce_races_familiar_apg.lst",
        source_line: 17,
    },
    CompanionRecord {
        key: "Monkey",
        name: "Monkey",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.132"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 18,
    },
    CompanionRecord {
        key: "Owl",
        name: "Owl",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.132"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 19,
    },
    CompanionRecord {
        key: "Blue-Ringed Octopus",
        name: "Blue-Ringed Octopus",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 30 }, Speed { mode: "Jet", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Tentacles", damage_dice: Some("0") }, NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 10 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: None,
        source_page: Some("p.117"),
        ability_keys: &["Blue-Ringed Octopus ~ Ink Cloud", "Blue-Ringed Octopus ~ Jet", "Blue-Ringed Octopus ~ Poison"],
        external_ability_refs: &["Can't Be Tripped", "Grab"],
        source_file: "ce_races_familiar_um.lst",
        source_line: 20,
    },
    CompanionRecord {
        key: "Rat",
        name: "Rat",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 15 }, Speed { mode: "Climb", feet: 15 }, Speed { mode: "Swim", feet: 15 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: None,
        source_page: Some("p.132"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 20,
    },
    CompanionRecord {
        key: "Donkey Rat",
        name: "Donkey Rat",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.117"),
        ability_keys: &[],
        external_ability_refs: &["Scent"],
        source_file: "ce_races_familiar_um.lst",
        source_line: 21,
    },
    CompanionRecord {
        key: "Raven",
        name: "Raven",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.133"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 21,
    },
    CompanionRecord {
        key: "Fox",
        name: "Fox",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.117"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 22,
    },
    CompanionRecord {
        key: "Toad",
        name: "Toad",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 5 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -9 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: -4 }, StatAdjustment { ability: "INT", amount: -9 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.133"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 22,
    },
    CompanionRecord {
        key: "Goat",
        name: "Goat",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.118"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 23,
    },
    CompanionRecord {
        key: "Viper",
        name: "Viper",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -6 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -9 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: None,
        source_page: Some("p.133"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 23,
    },
    CompanionRecord {
        key: "Scorpion (Greensting))",
        name: "Scorpion (Greensting))",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Vermin"),
        race_subtype: None,
        monster_class: Some("Vermin:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Sting", damage_dice: Some("1d2") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: 0 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(3),
        source_page: Some("p.118"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 24,
    },
    CompanionRecord {
        key: "Weasel",
        name: "Weasel",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Climb", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.133"),
        ability_keys: &["Weasel ~ Attach"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 24,
    },
    CompanionRecord {
        key: "Hedgehog",
        name: "Hedgehog",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -9 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: -4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.119"),
        ability_keys: &["Hedgehog ~ Spiny Defense"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 25,
    },
    CompanionRecord {
        key: "House Centipede",
        name: "House Centipede",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Climb", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Vermin"),
        race_subtype: None,
        monster_class: Some("Vermin:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -9 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(2),
        source_page: Some("p.119"),
        ability_keys: &["House Centipede ~ Poison"],
        external_ability_refs: &["Can't Be Tripped"],
        source_file: "ce_races_familiar_um.lst",
        source_line: 26,
    },
    CompanionRecord {
        key: "King Crab",
        name: "King Crab",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Vermin"),
        race_subtype: None,
        monster_class: Some("Vermin:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: Some("1d2") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(4),
        source_page: Some("p.119"),
        ability_keys: &["King Crab ~ Water Dependency"],
        external_ability_refs: &["Grab"],
        source_file: "ce_races_familiar_um.lst",
        source_line: 27,
    },
    CompanionRecord {
        key: "Pig",
        name: "Pig",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 0 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.119"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 28,
    },
    CompanionRecord {
        key: "Scarlet Spider",
        name: "Scarlet Spider",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Vermin"),
        race_subtype: None,
        monster_class: Some("Vermin:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 10 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(1),
        source_page: Some("p.120"),
        ability_keys: &["Scarlet Spider ~ Poison"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 29,
    },
    CompanionRecord {
        key: "Thrush",
        name: "Thrush",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -9 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.120"),
        ability_keys: &[],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "ce_races_familiar_um.lst",
        source_line: 30,
    },
    CompanionRecord {
        key: "Turtle",
        name: "Turtle",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: -4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(6),
        source_page: Some("p.120"),
        ability_keys: &["Turtle ~ Shell Retreat"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_um.lst",
        source_line: 31,
    },
    CompanionRecord {
        key: "Rat (Dire)",
        name: "Rat, Dire",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.232"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 61,
    },
    CompanionRecord {
        key: "Elemental (Air/Small)",
        name: "Elemental, Air (Small)",
        size: Some("S"),
        speeds: &[Speed { mode: "Fly", feet: 100 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Air|Elemental|Extraplanar"),
        monster_class: Some("Outsider (Fort/Ref):2"),
        type_segments: &["Elemental"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.120"),
        ability_keys: &["Air Elemental ~ Air Mastery"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 66,
    },
    CompanionRecord {
        key: "Elemental (Earth/Small)",
        name: "Elemental, Earth (Small)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Burrow", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Earth|Elemental|Extraplanar"),
        monster_class: Some("Outsider (Fort/Will):2"),
        type_segments: &["Elemental"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.122"),
        ability_keys: &["Earth Elemental ~ Earth Glide", "Earth Elemental ~ Earth Mastery"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 67,
    },
    CompanionRecord {
        key: "Elemental (Fire/Small)",
        name: "Elemental, Fire (Small)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Elemental|Extraplanar|Fire"),
        monster_class: Some("Outsider (Fort/Ref):2"),
        type_segments: &["Elemental"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.124"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 68,
    },
    CompanionRecord {
        key: "Elemental (Water/Small)",
        name: "Elemental, Water (Small)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 90 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Elemental|Extraplanar|Water"),
        monster_class: Some("Outsider (Fort/Ref):2"),
        type_segments: &["Elemental"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.126"),
        ability_keys: &["Water Elemental ~ Drench", "Water Elemental ~ Vortex", "Water Elemental ~ Water Mastery"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 69,
    },
    CompanionRecord {
        key: "Stirge",
        name: "Stirge",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:1"),
        type_segments: &["Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Touch", damage_dice: None }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.260"),
        ability_keys: &["Stirge ~ Attach", "Stirge ~ Blood Drain", "Stirge ~ Diseased"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 70,
    },
    CompanionRecord {
        key: "Homunculus",
        name: "Homunculus",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Construct"),
        race_subtype: None,
        monster_class: Some("Construct:2"),
        type_segments: &["Cosntruct"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.176"),
        ability_keys: &["Homunculus ~ Telepathic Link"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 75,
    },
    CompanionRecord {
        key: "Devil (Imp)",
        name: "Devil, Imp",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Devil|Evil|Extraplanar|Lawful"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: None,
        source_page: Some("p.78"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 76,
    },
    CompanionRecord {
        key: "Mephit (Air)",
        name: "Mephit, Air",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Air"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.202"),
        ability_keys: &["Air Mephit ~ Breath Weapon", "Air Mephit ~ Fast Healing"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 77,
    },
    CompanionRecord {
        key: "Mephit (Dust)",
        name: "Mephit, Dust",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Air"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.202"),
        ability_keys: &["Dust Mephit ~ Breath Weapon", "Dust Mephit ~ Fast Healing"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 78,
    },
    CompanionRecord {
        key: "Mephit (Earth)",
        name: "Mephit, Earth",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Earth"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.202"),
        ability_keys: &["Earth Mephit ~ Change Size", "Earth Mephit ~ Breath Weapon", "Earth Mephit ~ Fast Healing"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 79,
    },
    CompanionRecord {
        key: "Mephit (Fire)",
        name: "Mephit, Fire",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Fire"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.202"),
        ability_keys: &["Fire Mephit ~ Breath Weapon", "Fire Mephit ~ Fast Healing"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 80,
    },
    CompanionRecord {
        key: "Mephit (Ice)",
        name: "Mephit, Ice",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Cold"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.202"),
        ability_keys: &["Ice Mephit ~ Breath Weapon", "Ice Mephit ~ Fast Healing"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 81,
    },
    CompanionRecord {
        key: "Mephit (Magma)",
        name: "Mephit, Magma",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Fire"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.202"),
        ability_keys: &["Magma Mephit ~ Magma Form", "Magma Mephit ~ Breath Weapon", "Magma Mephit ~ Fast Healing"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 82,
    },
    CompanionRecord {
        key: "Mephit (Ooze)",
        name: "Mephit, Ooze",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 40 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Water"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.202"),
        ability_keys: &["Ooze Mephit ~ Breath Weapon", "Ooze Mephit ~ Fast Healing"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 83,
    },
    CompanionRecord {
        key: "Mephit (Salt)",
        name: "Mephit, Salt",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Earth"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.202"),
        ability_keys: &["Salt Mephit ~ Dehydrate", "Salt Mephit ~ Breath Weapon", "Salt Mephit ~ Fast Healing"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 84,
    },
    CompanionRecord {
        key: "Mephit (Steam)",
        name: "Mephit, Steam",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Fire"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.202"),
        ability_keys: &["Steam Mephit ~ Boiling Rain", "Steam Mephit ~ Breath Weapon", "Steam Mephit ~ Fast Healing"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 85,
    },
    CompanionRecord {
        key: "Mephit (Water)",
        name: "Mephit, Water",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 40 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Water"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.202"),
        ability_keys: &["Water Mephit ~ Breath Weapon", "Water Mephit ~ Fast Healing"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 86,
    },
    CompanionRecord {
        key: "Pseudodragon",
        name: "Pseudodragon",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 15 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Dragon"),
        race_subtype: None,
        monster_class: Some("Dragon:2"),
        type_segments: &["Dragon"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.229"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 87,
    },
    CompanionRecord {
        key: "Demon (Quasit)",
        name: "Demon, Quasit",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Demon|Evil|Extraplanar"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.66"),
        ability_keys: &["Quasit ~ Telepathy"],
        external_ability_refs: &[],
        source_file: "ce_races_familiar_cr.lst",
        source_line: 88,
    },
];

/// Every core_essentials companion ability record (44 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Blue-Ringed Octopus ~ Ink Cloud",
        name: "Ink Cloud",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("While within water, an octopus can emit a 5-foot-radius sphere of ink once per minute as a swift action. This ink provides total concealment and persists for 1 minute."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.117"),
        owners: &["Familiar (Blue-Ringed Octopus)", "Blue-Ringed Octopus"],
        source_file: "ce_abilities_familiar_race_um.lst",
        source_line: 10,
    },
    CompanionAbilityRecord {
        key: "Blue-Ringed Octopus ~ Jet",
        name: "Jet",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("The octopus can jet 60 feet in a straight line as a full-round action.  This does not provoke attacks of opportunity."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.117"),
        owners: &["Familiar (Blue-Ringed Octopus)", "Blue-Ringed Octopus"],
        source_file: "ce_abilities_familiar_race_um.lst",
        source_line: 11,
    },
    CompanionAbilityRecord {
        key: "Blue-Ringed Octopus ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Bite - injury; save Fort DC %1; frequency 1/round for 6 rounds; effect 1 Str; cure 1 save."),
        description_variables: &["PoisonSaveDC"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.117"),
        owners: &["Familiar (Blue-Ringed Octopus)", "Blue-Ringed Octopus"],
        source_file: "ce_abilities_familiar_race_um.lst",
        source_line: 12,
    },
    CompanionAbilityRecord {
        key: "Hedgehog ~ Spiny Defense",
        name: "Spiny Defense",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("As a move action, a hedgehog can roll itself up into a spiny ball. While rolled up, it gains a +1 enhancement bonus to its existing natural armor, and any creature attempting to grapple the hedgehog takes 1d3 damage on making a grapple check. While rolled up, a hedgehog cannot take any action other than leaving this state. The hedgehog can leave this state as a move action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.119"),
        owners: &["Familiar (Hedgehog)", "Hedgehog"],
        source_file: "ce_abilities_familiar_race_um.lst",
        source_line: 20,
    },
    CompanionAbilityRecord {
        key: "House Centipede ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Bite - injury; save Fort DC %1; frequency 1/round for 2 rounds; effect daze 1 round; cure 1 save."),
        description_variables: &["PoisonSaveDC"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.119"),
        owners: &["House Centipede"],
        source_file: "ce_abilities_familiar_race_um.lst",
        source_line: 24,
    },
    CompanionAbilityRecord {
        key: "King Crab ~ Water Dependency",
        name: "Water Dependency",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Weakness", "Extraordinary"],
        description: Some("This crab can survive out of the water for %1 hours.  Beyond this limit, a crab runs the risk of suffocation, as if it were drowning."),
        description_variables: &["CONSCORE"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.119"),
        owners: &["King Crab"],
        source_file: "ce_abilities_familiar_race_um.lst",
        source_line: 28,
    },
    CompanionAbilityRecord {
        key: "Scarlet Spider ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Bite - injury; save Fort DC %1; frequency 1/round for 4 rounds; effect 1 Str; cure 1 save."),
        description_variables: &["PoisonSaveDC"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.120"),
        owners: &["Scarlet Spider"],
        source_file: "ce_abilities_familiar_race_um.lst",
        source_line: 32,
    },
    CompanionAbilityRecord {
        key: "Turtle ~ Shell Retreat",
        name: "Shell Retreat",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("A turtle can retreat within its shell as a swift action, gaining a +2 enhancement bonus to its existing natural armor. While in its shell, a turtle cannot take any action except to end the retreat. The turtle can end its retreat with a free action on its turn."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.120"),
        owners: &["Familiar (Turtle)", "Turtle"],
        source_file: "ce_abilities_familiar_race_um.lst",
        source_line: 36,
    },
    CompanionAbilityRecord {
        key: "Weasel ~ Attach",
        name: "Attach",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "SpecialAttack", "Extraordinary"],
        description: Some("When a weasel hits with a bite attack, it automatically grapples its foe, inflicting automatic bite damage each round."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.133"),
        owners: &["Weasel"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 76,
    },
    CompanionAbilityRecord {
        key: "Air Elemental ~ Air Mastery",
        name: "Air Mastery",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Special Ability", "Extraordinary", "Defensive"],
        description: Some("Airborne creatures take a -1 penalty on attack and damage rolls against an air elemental."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.120"),
        owners: &["Elemental (Air/Small)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 97,
    },
    CompanionAbilityRecord {
        key: "Earth Elemental ~ Earth Glide",
        name: "Earth Glide",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Special Ability", "Extraordinary", "ModifyMovement"],
        description: Some("A burrowing earth elemental can pass through stone, dirt, or almost any other sort of earth except metal as easily as a fish swims through water. If protected against fire damage, it can even glide through lava. Its burrowing leaves behind no tunnel or hole, nor does it create any ripple or other sign of its presence. A Move Earth spell cast on an area containing a burrowing earth elemental flings the elemental back 30 feet, stunning the creature for 1 round unless it succeeds on a DC 15 Fortitude save."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.122"),
        owners: &["Elemental (Earth/Small)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 105,
    },
    CompanionAbilityRecord {
        key: "Earth Elemental ~ Earth Mastery",
        name: "Earth Mastery",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Extraordinary"],
        description: Some("An earth elemental gains a +1 bonus on attack and damage rolls if both it and its foe are touching the ground. If an opponent is airborne or waterborne, the elemental takes a -4 penalty on attack and damage rolls. These modifiers apply to bull rush and overrun maneuvers, whether the elemental is initiating or resisting these kinds of attacks. (These modifiers are not included in the statistics block.)"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.122"),
        owners: &["Elemental (Earth/Small)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 106,
    },
    CompanionAbilityRecord {
        key: "Water Elemental ~ Drench",
        name: "Drench",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Extraordinary"],
        description: Some("The elemental's touch puts out nonmagical flames of Large size or smaller. The creature can dispel magical fire it touches as Dispel Magic (caster level %1)."),
        description_variables: &["TL"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.126"),
        owners: &["Elemental (Water/Small)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 121,
    },
    CompanionAbilityRecord {
        key: "Water Elemental ~ Vortex",
        name: "Vortex",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "AttackOption"],
        description: Some("A water elemental can create a whirlpool as a standard action, at will. This ability functions identically to the whirlwind special attack (see page Bestiary Appendix 3: Universal Monster Rules), but can only form underwater and cannot leave the water.&nl;Some creatures can transform themselves into vortexes and remain in that form for up to 1 round for every 2 HD they have. If the creature has a swim speed, it can continue to swim at that same speed while in vortex form, otherwise it gains a swim speed equal to its base land speed while in vortex form.&nl;The vortex is always 5 feet wide at its base, but its height and width at the top vary from creature to creature (minimum 10 feet high). A vortex's width at its peak is always equal to half of its height. The creature controls the exact height, but it must be at least 10 feet high.&nl;The vortex form does not provoke attacks of opportunity, even if the creature enters the space another creature occupies. Another creature might be caught in the vortex if it touches or enters the vortex, or if the vortex moves into or through a creature's space. A creature in vortex form cannot make its normal attacks and does not threaten the area around it.&nl;Creatures one or more size categories smaller than the vortex might take damage when caught in the vortex (generally damage equal to the monster's slam attack for a creature of its size) and may be lifted into the air. An affected creature must succeed on a Reflex save (DC 10 + half monster's HD + the monster's Strength modifier) when it comes into contact with the vortex or take damage as if it were hit by the vortex creature's slam attack. It must also succeed on a second Reflex save or be picked up bodily and held suspended in the powerful currents, automatically taking the indicated damage each round. A creature that can swim is allowed a Reflex save each round to escape the vortex. The creature still takes damage but can leave if the save is successful.&nl;Creatures trapped in the vortex cannot move except to go where the vortex carries them or to escape the vortex. Trapped creatures can otherwise act normally, but must succeed on a concentration check (DC 15 + spell level) to cast a spell. Creatures caught in the vortex take a -4 penalty to Dexterity and a -2 penalty on attack rolls. The vortex can have only as many creatures trapped inside at one time as will fit inside the vortex's volume. The vortex can eject any carried creatures whenever it wishes as a free action, depositing them in its space.&nl;If the vortex's base touches the ground, it creates a swirling cloud of debris. This cloud is centered on the creature and has a diameter equal to half the vortex's height. The cloud obscures all vision, including darkvision, beyond 5 feet. Creatures 5 feet away have concealment, while those farther away have total concealment. Those caught in the cloud of debris must succeed on a concentration check (DC 15 + spell level) to cast a spell."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.126"),
        owners: &["Elemental (Water/Small)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 122,
    },
    CompanionAbilityRecord {
        key: "Water Elemental ~ Water Mastery",
        name: "Water Mastery",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Extraordinary"],
        description: Some("A water elemental gains a +1 bonus on attack and damage rolls if both it and its opponent are touching water. If the opponent or the elemental is touching the ground, the elemental takes a -4 penalty on attack and damage rolls. These modifiers apply to bull rush and overrun maneuvers, whether the elemental is initiating or resisting these kinds of attacks."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.126"),
        owners: &["Elemental (Water/Small)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 123,
    },
    CompanionAbilityRecord {
        key: "Stirge ~ Attach",
        name: "Attach",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Special Ability", "Extraordinary"],
        description: Some("When a stirge hits with a touch attack, its barbed legs latch onto the target, anchoring it in place. An attached stirge is effectively grappling its prey. The stirge loses its Dexterity bonus to AC, but holds on with great tenacity and inserts its proboscis into the grappled target's flesh. A stirge has a +8 racial bonus to maintain its grapple on a foe once it is attached. An attached stirge can be struck with a weapon or grappled itself. If its prey manages to win a grapple check or Escape Artist check against it, the stirge is removed."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.260"),
        owners: &["Stirge"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 130,
    },
    CompanionAbilityRecord {
        key: "Stirge ~ Blood Drain",
        name: "Blood Drain",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Extraordinary"],
        description: Some("A stirge drains blood at the end of its turn if it is attached to a foe, inflicting 1 point of Constitution damage. Once a stirge has dealt 4 points of Constitution damage, it detaches and flies off to digest the meal. If its victim dies before the stirge’s appetite has been sated, the stirge detaches and seeks a new target."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.260"),
        owners: &["Stirge"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 131,
    },
    CompanionAbilityRecord {
        key: "Stirge ~ Diseased",
        name: "Diseased",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Special Quality", "Special Ability", "Extraordinary"],
        description: Some("Due to the stagnant swamps in which they live and their contact with the blood of numerous creatures, stirges are harbingers of disease. Any creature subjected to a stirge’s blood drain attack has a 10%% chance of being exposed to filth fever, blinding sickness, or a similar disease (Pathfinder RPG Core Appendix 1: Special Abilities, Diseases). Once this check is made, the victim can no longer be infected by this particular stirge, though attacks by different stirges are resolved normally and may result in multiple illnesses."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.260"),
        owners: &["Stirge"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 132,
    },
    CompanionAbilityRecord {
        key: "Homunculus ~ Telepathic Link",
        name: "Telepathic Link",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialQuality", "Special Ability", "Supernatural", "Communicate"],
        description: Some("A homunculus cannot speak, but the process of creating one links it telepathically with its creator. A homunculus knows what its master knows and can convey to him or her everything it sees and hears, out to a distance of 1,500 feet."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.176"),
        owners: &["Homunculus"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 139,
    },
    CompanionAbilityRecord {
        key: "Earth Mephit ~ Change Size",
        name: "Change Size",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: None,
        type_segments: &["SpecialQuality", "Special Quality", "Special Ability"],
        description: Some("Once per day, an earth mephit can enlarge one size category, as enlarge person, except that it only works on the earth mephit. This power acts as a 2nd-level spell."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Earth)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 173,
    },
    CompanionAbilityRecord {
        key: "Magma Mephit ~ Magma Form",
        name: "Magma Form",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialQuality", "Special Quality", "Special Ability", "Supernatural"],
        description: Some("Once per hour, a magma mephit can assume the form of a pool of lava, 3 feet in diameter and 6 inches deep. While in this form, its DR increases to 20/ magic and it cannot attack. It can move at a speed of 10 feet per round and can pass through small openings and cracks. Anything touching this pool takes 1d6 fire damage. A magma mephit may remain in this form for up to 10 minutes."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Magma)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 174,
    },
    CompanionAbilityRecord {
        key: "Salt Mephit ~ Dehydrate",
        name: "Dehydrate",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural"],
        description: Some("Once per day a salt mephit can draw the moisture from an area in a 20-foot radius centered on itself. Living creatures within range take 2d8 points of damage (Fortitude DC 14 half; caster level 6th). This effect is especially devastating to plant and aquatic creatures, which take a -2 penalty on their saving throws. This ability is the equivalent of a 2nd-level spell."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.203"),
        owners: &["Mephit (Salt)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 175,
    },
    CompanionAbilityRecord {
        key: "Steam Mephit ~ Boiling Rain",
        name: "Boiling Rain",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural"],
        description: Some("Once per day a steam mephit can create a rainstorm of boiling water in a 20-foot-square area. Living creatures within the area take 2d6 points of fire damage (Fortitude DC 14 half; caster level 6th). This ability is the equivalent of a 2nd-level spell."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.203"),
        owners: &["Mephit (Steam)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 176,
    },
    CompanionAbilityRecord {
        key: "Air Mephit ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "BreathWeapon"],
        description: Some("Air mephits can unleash a cone of sand and grit that deals 1d8 slashing damage as a breath weapon every 4 rounds as a standard action. The DC is Constitution-based and includes a +1 racial bonus."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Air)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 178,
    },
    CompanionAbilityRecord {
        key: "Dust Mephit ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "BreathWeapon"],
        description: Some("Dust mephits can unleash a cone of dust that deals 1d4 slashing damage as a breath weapon every 4 rounds as a standard action. The dust also causes living creatures to be sickened for 3 rounds. A Reflex save halves the damage and negates the sickened effect. The DC is Constitution-based and includes a +1 racial bonus."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Dust)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 179,
    },
    CompanionAbilityRecord {
        key: "Earth Mephit ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "BreathWeapon"],
        description: Some("Earth mephits can unleash a cone of rocks that deals 1d8 bludgeoning damage as a breath weapon every 4 rounds as a standard action. The DC is Constitution-based and includes a +1 racial bonus."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Earth)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 180,
    },
    CompanionAbilityRecord {
        key: "Fire Mephit ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "BreathWeapon"],
        description: Some("Fire mephits can unleash a cone of flames that deals 1d8 fire damage as a breath weapon every 4 rounds as a standard action. The DC is Constitution-based and includes a +1 racial bonus."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Fire)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 181,
    },
    CompanionAbilityRecord {
        key: "Ice Mephit ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "BreathWeapon"],
        description: Some("Ice mephits can unleash a cone of ice that deals 1d4 cold damage as a breath weapon every 4 rounds as a standard action. The cold also causes living creatures to be sickened for 3 rounds. A Reflex save halves the damage and negates the sickened effect. The DC is Constitution-based and includes a +1 racial bonus."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Ice)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 182,
    },
    CompanionAbilityRecord {
        key: "Magma Mephit ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "BreathWeapon"],
        description: Some("Magma mephits can unleash a one of fire that deals 1d8 fire damage as a breath weapon every 4 rounds as a standard action. The DC is Constitution-based and includes a +1 racial bonus."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Magma)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 183,
    },
    CompanionAbilityRecord {
        key: "Ooze Mephit ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "BreathWeapon"],
        description: Some("Ooze mephits can unleash a cone of slime that deals 1d4 acid damage as a breath weapon every 4 rounds as a standard action. The slime also causes living creatures to be sickened for 3 rounds. A Reflex save halves the damage and negates the sickened effect. The DC is Constitution-based and includes a +1 racial bonus."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Ooze)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 184,
    },
    CompanionAbilityRecord {
        key: "Salt Mephit ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "BreathWeapon"],
        description: Some("Salt mephits can unleash a cone of salt crystals that deals 1d4 slashing damage as a breath weapon every 4 rounds as a standard action. The salt also causes living creatures to be sickened for 3 rounds. A Reflex save halves the damage and negates the sickened effect. The DC is Constitution-based and includes a +1 racial bonus."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Salt)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 185,
    },
    CompanionAbilityRecord {
        key: "Steam Mephit ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "BreathWeapon"],
        description: Some("Steam mephits can unleash a cone of steam that deals 1d4 fire damage as a breath weapon every 4 rounds as a standard action. The scalding water also causes living creatures to be sickened for 3 rounds. A Reflex save halves the damage and negates the sickened effect. The DC is Constitution-based and includes a +1 racial bonus."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Steam)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 186,
    },
    CompanionAbilityRecord {
        key: "Water Mephit ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Supernatural", "BreathWeapon"],
        description: Some("Water mephits can unleash a cone of acid that deals 1d8 acid damage as a breath weapon every 4 rounds as a standard action. The DC is Constitution-based and includes a +1 racial bonus."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Water)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 187,
    },
    CompanionAbilityRecord {
        key: "Air Mephit ~ Fast Healing",
        name: "Fast Healing",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "Extraordinary"],
        description: Some("Works only in gusty and windy areas."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Air)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 199,
    },
    CompanionAbilityRecord {
        key: "Dust Mephit ~ Fast Healing",
        name: "Fast Healing",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "Extraordinary"],
        description: Some("Works only in dusty environments."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Dust)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 200,
    },
    CompanionAbilityRecord {
        key: "Earth Mephit ~ Fast Healing",
        name: "Fast Healing",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "Extraordinary"],
        description: Some("Works only while underground."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Earth)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 201,
    },
    CompanionAbilityRecord {
        key: "Fire Mephit ~ Fast Healing",
        name: "Fast Healing",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "Extraordinary"],
        description: Some("Works only while in contact with fire."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Fire)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 202,
    },
    CompanionAbilityRecord {
        key: "Ice Mephit ~ Fast Healing",
        name: "Fast Healing",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "Extraordinary"],
        description: Some("Works only in areas below freezing."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Ice)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 203,
    },
    CompanionAbilityRecord {
        key: "Magma Mephit ~ Fast Healing",
        name: "Fast Healing",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "Extraordinary"],
        description: Some("Works only in contact with magma or lava."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Magma)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 204,
    },
    CompanionAbilityRecord {
        key: "Ooze Mephit ~ Fast Healing",
        name: "Fast Healing",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "Extraordinary"],
        description: Some("Works only in wet or muddy environments."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Ooze)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 205,
    },
    CompanionAbilityRecord {
        key: "Salt Mephit ~ Fast Healing",
        name: "Fast Healing",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "Extraordinary"],
        description: Some("Works only in arid environments."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Salt)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 206,
    },
    CompanionAbilityRecord {
        key: "Steam Mephit ~ Fast Healing",
        name: "Fast Healing",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "Extraordinary"],
        description: Some("Works only in boiling water or steam."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Steam)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 207,
    },
    CompanionAbilityRecord {
        key: "Water Mephit ~ Fast Healing",
        name: "Fast Healing",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Special Ability", "Extraordinary"],
        description: Some("Works only while the mephit is underwater."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.202"),
        owners: &["Mephit (Water)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 208,
    },
    CompanionAbilityRecord {
        key: "Quasit ~ Telepathy",
        name: "Telepathy",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialQuality", "Supernatural", "Communicate"],
        description: Some("The creature can mentally communicate with any other creature within a certain range (specified in the creature's entry, usually 100 feet) that has a language. It is possible to address multiple creatures at once telepathically, although maintaining a telepathic conversation with more than one creature at a time is just as difficult as simultaneously speaking and listening to multiple people at the same time."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.305"),
        owners: &["Demon (Quasit)"],
        source_file: "ce_abilities_familiar_race_cr.lst",
        source_line: 225,
    },
];
