#!/usr/bin/env python3
"""SD-37 E4a.4: turn E4a.2's equivalence list (catalog == compiled, per table and view) into a
golden-digest test that survives the compiled module's removal.

Reads src/rules_core/rules_catalog/equivalence_tests.rs (every `same`/`same_debug` call) and writes
src/rules_core/rules_catalog/golden_tests.rs: one transcript per table / view / lookup domain,
built by a macro over a module root, so the SAME expressions run against the compiled module
(`rt`, while it exists: the digests are written from it) and against the catalog (`cat`, always).
Run from the repo root.  --with-compiled keeps the compiled half (pre-removal).
"""
import re, sys
src = open('src/rules_core/rules_catalog/equivalence_tests.rs').read()
calls = re.findall(r'\b(same|same_debug)\(\s*"([^"]+)",\s*&(\*?)crate::rules_core::rules_catalog::([A-Za-z0-9_:]+?)(\(\s*\))?,\s*&rt::([A-Za-z0-9_:]+?)(\(\))?,?\s*\);', src, re.S)
with_compiled = '--with-compiled' in sys.argv
tables = [c for c in calls if c[2] == '*']
views = [c for c in calls if c[2] != '*']
assert len(tables) == 222, len(tables)
lines = []
for kind, ident, star, cpath, cparen, rpath, rparen in calls:
    assert cpath == rpath, (cpath, rpath)
    f = 'debug_of' if kind == 'same_debug' else 'json_of'
    if star:
        expr = f'{f}(rows_of(&$r::{cpath}))'
    else:
        expr = f'{f}(&$r::{cpath}())'
    lines.append(f'        out.push(("{ident}", {expr}));')
body = '\n'.join(lines)
compiled_part = '''
/// The compiled half: the same transcripts over the compiled module, the oracle the digests are
/// written from (`RULES_CATALOG_GOLDEN_WRITE=1`). Removed with the module (E4a.4).
#[test]
fn the_golden_digests_are_the_compiled_tables_digests() {
    use crate::rules_core::rules_tables as rt;
    let compiled = digests(transcripts!(rt));
    if std::env::var_os("RULES_CATALOG_GOLDEN_WRITE").is_some() {
        let text: String = compiled.iter().map(|(id, d)| format!("{d}  {id}\\n")).collect();
        std::fs::write(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/rules_core/rules_catalog/golden_digests.txt"),
            text,
        )
        .expect("write golden_digests.txt");
    }
    assert_eq!(manifest(), compiled, "golden_digests.txt is not the compiled tables' digest set");
}
''' if with_compiled else ''
out = f'''//! Golden digests of every package-backed table, view and table-reading lookup (SD-37 E4a.4).
//!
//! E4a.2 proved the catalog equal to the compiled `rules_tables` module row for row
//! (`equivalence_tests`, `override_tests`). E4a.4 deletes that module, so the proof is kept as
//! data: `golden_digests.txt` holds one sha256 per transcript, written FROM THE COMPILED MODULE
//! on the last tree that had it, and this test re-derives every transcript from the catalog (the
//! package plus the catalog's own code) and requires the same digest. A package row edited by
//! hand, or a moved type that serialises differently, changes a digest and names its id.
//! Generated by `artifacts/epic_4a/E4a.4_tools/gen_golden_tests.py` from E4a.2's equivalence list.
#![allow(clippy::all)]

use crate::rules_core::rules_catalog as cat;
use sha2::{{Digest, Sha256}};
use std::fmt::Debug;

/// A table's rows as a slice, whichever shape holds them (a catalog `Table`/`Derived`, a
/// compiled array or slice).
trait Rows {{
    type Item;
    fn rows(&self) -> &[Self::Item];
}}
impl<T> Rows for [T] {{
    type Item = T;
    fn rows(&self) -> &[T] {{ self }}
}}
impl<T, const N: usize> Rows for [T; N] {{
    type Item = T;
    fn rows(&self) -> &[T] {{ self }}
}}
impl<T> Rows for &[T] {{
    type Item = T;
    fn rows(&self) -> &[T] {{ self }}
}}
impl<T> Rows for cat::Table<T>
where
    T: serde::Deserialize<'static> + Send + Sync + 'static,
{{
    type Item = T;
    fn rows(&self) -> &[T] {{ self }}
}}
impl<T: Send + Sync + 'static> Rows for cat::Derived<T> {{
    type Item = T;
    fn rows(&self) -> &[T] {{ self }}
}}
fn rows_of<R: Rows + ?Sized>(r: &R) -> &[R::Item] {{
    r.rows()
}}
fn json_of<T: serde::Serialize + ?Sized>(value: &T) -> String {{
    serde_json::to_string(value).expect("serialise")
}}
fn debug_of<T: Debug + ?Sized>(value: &T) -> String {{
    format!("{{value:?}}")
}}

macro_rules! transcripts {{
    ($r:ident) => {{{{
        let mut out: Vec<(&'static str, String)> = Vec::new();
{body}
        // The lookups E4a.2 hand-wrote over the package (`override_tests`), over their domains.
        let mut ladders = String::new();
        for level in 0..=40u8 {{
            for m in -5..=12i16 {{
                ladders.push_str(&format!(
                    "{{:?}}{{:?}}{{:?}}{{:?}}{{:?}}{{:?}}{{:?}}{{:?}};",
                    $r::ultimate_psionics::psion_features::psion_power_points_total(level, m),
                    $r::ultimate_psionics::wilder_features::wilder_power_points_total(level, m),
                    $r::ultimate_psionics::vitalist_features::vitalist_power_points_total(level, m),
                    $r::ultimate_psionics::tactician_features::tactician_power_points_total(level, m),
                    $r::ultimate_psionics::psychic_warrior_features::psychic_warrior_power_points_total(level, m),
                    $r::ultimate_psionics::marksman_features::marksman_power_points_total(level, m),
                    $r::ultimate_psionics::dread_features::dread_power_points_total(level, m),
                    $r::ultimate_psionics::cryptic_features::cryptic_power_points_total(level, m),
                ));
            }}
        }}
        out.push(("lookup:psionic_power_point_ladders", ladders));
        let rule_sets = [$r::RuleSetId::Crb, $r::RuleSetId::Bestiary1, $r::RuleSetId::Pu, $r::RuleSetId::Apg];
        let mut monsters = String::new();
        for &id in $r::beastiary1::MonsterId::ALL {{
            for rule_set in rule_sets {{
                monsters.push_str(&format!("{{:?}};", $r::beastiary1::monster_resolve(id, rule_set)));
            }}
            let name = $r::beastiary1::monster_resolve(id, $r::RuleSetId::Bestiary1).expect("every monster resolves").name;
            let key = $r::beastiary1::monster_key(&name);
            for rule_set in rule_sets {{
                monsters.push_str(&format!("{{key}}={{:?}};", $r::beastiary1::monster_key_resolve(&key, rule_set)));
            }}
        }}
        for key in ["", "beastiary1:monster:no_such_monster", "bestiary:monster:wolf"] {{
            monsters.push_str(&format!("{{key}}={{:?}};", $r::beastiary1::monster_key_resolve(key, $r::RuleSetId::Bestiary1)));
        }}
        out.push(("lookup:beastiary1_monster_resolve", monsters));
        let mut chassis = String::new();
        for class_id in $r::pathfinder_unchained::class_chassis::PuClassId::ALL {{
            for level in 0..=25u8 {{
                for rule_set in rule_sets {{
                    chassis.push_str(&format!(
                        "{{:?}};",
                        $r::pathfinder_unchained::class_chassis::class_chassis_resolve(class_id, level, rule_set)
                    ));
                }}
            }}
        }}
        out.push(("lookup:unchained_class_chassis_resolve", chassis));
        let mut books = String::new();
        for book in $r::monster_chassis::MONSTER_BOOKS.iter() {{
            books.push_str(&format!(
                "{{}}|{{:?}}|{{:?}}|{{:?}}|{{:?}};",
                book.corpus_book,
                book.monsters,
                book.monster_abilities,
                book.cross_table_owner_names,
                $r::monster_chassis::monster_book(book.corpus_book).map(|b| b.corpus_book)
            ));
        }}
        books.push_str(&format!("{{:?}};", $r::monster_chassis::monster_book("no_such_book").map(|b| b.corpus_book)));
        for book in $r::companion_chassis::COMPANION_BOOKS.iter() {{
            books.push_str(&format!(
                "{{}}|{{:?}}|{{:?}}|{{:?}}|{{:?}};",
                book.corpus_book,
                book.companions,
                book.companion_abilities,
                book.companion_classes,
                $r::companion_chassis::companion_book(book.corpus_book).map(|b| b.corpus_book)
            ));
        }}
        books.push_str(&format!("{{:?}};", $r::companion_chassis::companion_book("no_such_book").map(|b| b.corpus_book)));
        out.push(("lookup:book_registries", books));
        let classes: Vec<&str> = $r::class_spell_levels::classes_with_spell_lists();
        let mut keys: Vec<&str> = $r::crb::spell_list::SPELL_LIST.iter().map(|e| e.key).collect();
        keys.extend($r::apg::spell_list::SPELL_LIST.iter().map(|e| e.key));
        keys.extend($r::acg::spell_list::SPELL_LIST.iter().map(|e| e.key));
        keys.extend($r::advanced_race_guide::spell_list::SPELL_LIST.iter().map(|e| e.key));
        keys.push("no_such_spell");
        let mut spell_levels = format!("{{classes:?}};");
        for class in classes.iter().copied().chain(["class:fighter", "", "class:magus"]) {{
            spell_levels.push_str(&format!(
                "{{class}}|{{:?}}|{{:?}};",
                $r::class_spell_levels::class_has_spell_list(class),
                $r::class_spell_levels::class_spell_list_entries(class)
            ));
            for key in &keys {{
                spell_levels.push_str(&format!("{{:?}},", $r::class_spell_levels::class_spell_level(class, key)));
            }}
        }}
        spell_levels.push_str(&format!(
            "{{:?}}",
            $r::advanced_race_guide::class_spell_levels::ARG_CLASS_SPELL_LEVELS.iter().collect::<Vec<_>>()
        ));
        out.push(("lookup:class_spell_levels", spell_levels));
        let gap: Vec<_> = $r::equipment_gap_tables::equipment_gap_rows().collect();
        out.push(("lookup:equipment_gap_rows", format!("{{gap:?}}")));
        out
    }}}};
}}

fn digests(transcripts: Vec<(&'static str, String)>) -> Vec<(String, String)> {{
    transcripts
        .into_iter()
        .map(|(id, text)| {{
            let digest: String = Sha256::digest(text.as_bytes()).iter().map(|b| format!("{{b:02x}}")).collect();
            (id.to_owned(), digest)
        }})
        .collect()
}}

fn manifest() -> Vec<(String, String)> {{
    include_str!("golden_digests.txt")
        .lines()
        .filter(|line| !line.is_empty())
        .map(|line| {{
            let (digest, id) = line.split_once("  ").expect("`<sha256>  <id>` lines");
            (id.to_owned(), digest.to_owned())
        }})
        .collect()
}}

/// Every catalog transcript has the digest the compiled module gave it.
#[test]
fn every_catalog_table_view_and_lookup_matches_its_golden_digest() {{
    let expected = manifest();
    assert_eq!(expected.len(), {len(calls)} + 6, "golden_digests.txt rows");
    let actual = digests(transcripts!(cat));
    let differing: Vec<&str> = expected
        .iter()
        .zip(&actual)
        .filter(|(e, a)| e != a)
        .map(|(e, _)| e.0.as_str())
        .collect();
    assert_eq!(expected.len(), actual.len());
    assert!(differing.is_empty(), "transcripts whose digest moved: {{differing:#?}}");
}}
{compiled_part}'''
open('src/rules_core/rules_catalog/golden_tests.rs', 'w').write(out)
print('calls', len(calls), 'tables', len(tables), 'views', len(views))
