//! inner_sea_combat companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py inner_sea_combat`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `isc_races_companion.lst` -- 4 companion creature rows
//!   * `isc_abilities_companion.lst` -- 6 companion ability rows

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, Speed, StatAdjustment};

/// Every inner_sea_combat companion creature (4 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Companion (Griffon)",
        name: "Companion (Griffon)",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: None,
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -6 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(4),
        source_page: None,
        ability_keys: &["Unable to carry a rider while flying", "Companion Advancement ~ Griffon"],
        external_ability_refs: &["Scent"],
        source_file: "isc_races_companion.lst",
        source_line: 5,
    },
    CompanionRecord {
        key: "Companion (Hippocampus)",
        name: "Companion (Hippocampus)",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Swim", feet: 40 }],
        reach_feet: None,
        race_type: Some("Magical Beast"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(4),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Hippocampus"],
        external_ability_refs: &["Hippocampus ~ Water Dependency", "Scent"],
        source_file: "isc_races_companion.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Companion (Hippogriff)",
        name: "Companion (Hippogriff)",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: None,
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(2),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Hippogriff", "Unable to carry a rider while flying"],
        external_ability_refs: &["Flight Maneuverability", "Scent"],
        source_file: "isc_races_companion.lst",
        source_line: 7,
    },
    CompanionRecord {
        key: "Companion (Worg)",
        name: "Companion (Worg)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: None,
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: Some(2),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Worg", "Worg ~ Mastery"],
        external_ability_refs: &["Scent"],
        source_file: "isc_races_companion.lst",
        source_line: 8,
    },
];

/// Every inner_sea_combat companion ability record (6 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Griffon",
        name: "Companion Advancement (Griffon)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Griffon)"],
        cross_book_owners: &[],
        source_file: "isc_abilities_companion.lst",
        source_line: 5,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Hippocampus",
        name: "Companion Advancement (Hippocampus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }],
        source_page: None,
        owners: &["Companion (Hippocampus)"],
        cross_book_owners: &[],
        source_file: "isc_abilities_companion.lst",
        source_line: 6,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Hippogriff",
        name: "Companion Advancement (Hippogriff)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Hippogriff)"],
        cross_book_owners: &[],
        source_file: "isc_abilities_companion.lst",
        source_line: 7,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Worg",
        name: "Companion Advancement (Worg)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Worg)"],
        cross_book_owners: &[],
        source_file: "isc_abilities_companion.lst",
        source_line: 8,
    },
    CompanionAbilityRecord {
        key: "Unable to carry a rider while flying",
        name: "Unable to carry a rider while flying",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: None,
        type_segments: &["SpecialQuality"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Griffon)", "Companion (Hippogriff)"],
        cross_book_owners: &[],
        source_file: "isc_abilities_companion.lst",
        source_line: 9,
    },
    CompanionAbilityRecord {
        key: "Worg ~ Mastery",
        name: "Mastery (7th Level)",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: None,
        type_segments: &["SpecialQuality"],
        description: Some("Once per day as a standard action, the worg can make a fearful howl. This functions as the fear cone (30 ft.) version of the fear universal monster rule."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Worg)"],
        cross_book_owners: &[],
        source_file: "isc_abilities_companion.lst",
        source_line: 10,
    },
];
