//! Controls on the catalog's own shape (generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`; the `REPLACED` list is
//! every compiled table, view and table-reading lookup the catalog re-implements over the package).

use std::path::{Path, PathBuf};

use crate::rules_core::rules_data_package::{TABLE_IDS, VIEWS};

fn source_files(root: &Path, skip: &dyn Fn(&Path) -> bool, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(root) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if skip(&path) {
            continue;
        }
        if path.is_dir() {
            source_files(&path, skip, out);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            out.push(path);
        }
    }
}

fn catalog_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("src/rules_core/rules_catalog")
}

/// The catalog files that are generated mirrors (not the tests that compare against the compiled
/// tables).
fn mirror_files() -> Vec<PathBuf> {
    let mut files = Vec::new();
    source_files(&catalog_dir(), &|_| false, &mut files);
    files
        .into_iter()
        .filter(|p| {
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
            !matches!(
                name,
                "equivalence_tests.rs" | "override_tests.rs" | "control_tests.rs"
            )
        })
        .collect()
}

/// Registered package tables that are also TYPES: the package carries each variant's facts
/// (`key`, `name`, `declaring_line`, `min_level`), but the enum's own methods still answer from
/// compiled `match` arms. The catalog re-exports the type; settling those methods is E4a.4's
/// ("no `.rs` left" has to place every non-table value), logged as a retro deferral.
const TYPES_WITH_COMPILED_METHODS: &[&str] = &[
    "pathfinder_unchained/rogue_features/UnchainedRogueFeature",
    "pathfinder_unchained/summoner_features/UnchainedSummonerFeature",
];

/// A catalog module re-exports a compiled item only by name (`pub use rt::<module>::<Name>;`),
/// never a table, a view or a lookup the catalog replaces, and never by glob.
#[test]
fn no_compiled_table_view_or_reader_is_re_exported_from_the_compiled_module() {
    let replaced: std::collections::BTreeSet<&str> = REPLACED
        .iter()
        .copied()
        .chain(TABLE_IDS.iter().copied())
        .chain(VIEWS.iter().map(|(id, _)| *id))
        .collect();
    let mut offenders = Vec::new();
    let mut re_exports = 0usize;
    for file in mirror_files() {
        let text = std::fs::read_to_string(&file).expect("read a catalog file");
        for line in text.lines() {
            let line = line.trim();
            let Some(path) = line
                .strip_prefix("pub use rt::")
                .or_else(|| line.strip_prefix("pub(crate) use rt::"))
                .and_then(|rest| rest.strip_suffix(';'))
            else {
                continue;
            };
            re_exports += 1;
            if path.contains('*') || path.contains('{') {
                offenders.push(format!(
                    "{}: glob or group re-export: {line}",
                    file.display()
                ));
                continue;
            }
            let id = path.replace("::", "/");
            if replaced.contains(id.as_str()) && !TYPES_WITH_COMPILED_METHODS.contains(&id.as_str())
            {
                offenders.push(format!("{}: re-exports the compiled {id}", file.display()));
            }
        }
    }
    assert!(
        offenders.is_empty(),
        "the catalog hands out compiled data: {offenders:#?}"
    );
    assert!(re_exports > 400, "scanned {re_exports} re-exports");
}

/// The other direction: every table in the package and every view of the compiled module has a
/// catalog replacement, so nothing a caller could ask the catalog for is left to the compiled copy
/// -- except the two enum types named above, whose methods stay compiled (E4a.4).
#[test]
fn every_package_table_and_view_has_a_catalog_replacement() {
    let replaced: std::collections::BTreeSet<&str> = REPLACED.iter().copied().collect();
    let missing: Vec<&str> = TABLE_IDS
        .iter()
        .copied()
        .chain(VIEWS.iter().map(|(id, _)| *id))
        .filter(|id| !replaced.contains(id) && !TYPES_WITH_COMPILED_METHODS.contains(id))
        .collect();
    assert!(
        missing.is_empty(),
        "tables or views with no catalog replacement: {missing:#?}"
    );
}

/// The compiled module is named in the catalog only through the `rt` alias of a re-export.
#[test]
fn the_catalog_reaches_the_compiled_module_only_through_re_exports() {
    let needle = format!("{}{}", "rules_tables", "::");
    let mut offenders = Vec::new();
    for file in mirror_files() {
        let text = std::fs::read_to_string(&file).expect("read a catalog file");
        for (n, line) in text.lines().enumerate() {
            if line.contains(&needle) {
                offenders.push(format!("{}:{}: {}", file.display(), n + 1, line.trim()));
            }
        }
    }
    assert!(offenders.is_empty(), "{offenders:#?}");
}

/// The acceptance rule of E4a.2, as a test: no file outside the compiled module (and outside
/// this test) names the compiled module with a path.
#[test]
fn no_importer_names_the_compiled_tables() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let needle = format!("{}{}", "rules_tables", "::");
    let compiled = root.join("src/rules_core/rules_tables");
    let skip = |p: &Path| {
        let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
        name == "target" || name == "node_modules" || name == ".git" || p == compiled
    };
    let mut files = Vec::new();
    for dir in ["src", "crates", "apps/desktop/src-tauri", "tests"] {
        source_files(&root.join(dir), &skip, &mut files);
    }
    let mut importers = Vec::new();
    for file in &files {
        let text = std::fs::read_to_string(file).unwrap_or_default();
        if text.contains(&needle) {
            importers.push(
                file.strip_prefix(root)
                    .unwrap_or(file)
                    .display()
                    .to_string(),
            );
        }
    }
    assert!(
        importers.is_empty(),
        "files still importing the compiled tables: {importers:#?}"
    );
    assert!(files.len() > 1000, "scanned {} files", files.len());
}

const REPLACED: &[&str] = &[
    "acg/archetype_tables/archetype_swap_tables",
    "acg/bloodrager_spell_list/BLOODRAGER_SPELL_LIST",
    "acg/bloodrager_spell_list/bloodrager_spell_level",
    "acg/class_arcanist/class_table",
    "acg/class_bloodrager/class_table",
    "acg/class_brawler/class_table",
    "acg/class_chassis_resolve",
    "acg/class_coverage",
    "acg/class_hunter/class_table",
    "acg/class_investigator/class_table",
    "acg/class_shaman/class_table",
    "acg/class_skald/class_table",
    "acg/class_slayer/class_table",
    "acg/class_swashbuckler/class_table",
    "acg/class_warpriest/class_table",
    "acg/coverage_report",
    "acg/equipment_data/arms_armor/ARMS_ARMOR_TABLE",
    "acg/equipment_data/equipmods/EQUIPMODS_TABLE",
    "acg/equipment_data/general/GENERAL_TABLE",
    "acg/equipment_data/magic_items/MAGIC_ITEMS_TABLE",
    "acg/equipment_tables/equipment_resolve",
    "acg/equipment_tables/equipment_tables",
    "acg/equipment_tables/field_coverage_report",
    "acg/feat_data/combat/COMBAT_TABLE",
    "acg/feat_data/general/GENERAL_TABLE",
    "acg/feat_data/panache/PANACHE_TABLE",
    "acg/feat_data/teamwork/TEAMWORK_TABLE",
    "acg/feats/feat_tables",
    "acg/hunter_spell_list/hunter_spell_level",
    "acg/shaman_spell_list/SHAMAN_SPELLS_NOT_INGESTED",
    "acg/shaman_spell_list/SHAMAN_SPELL_LIST",
    "acg/shaman_spell_list/shaman_spell_level",
    "acg/spell_list/ARCHETYPE_QUALIFIED_KEYS",
    "acg/spell_list/SPELL_LIST",
    "acg/spell_list/spell_coverage_report",
    "acg/spell_list/spell_resolve",
    "advanced_race_guide/archetype_tables/archetype_swap_tables",
    "advanced_race_guide/class_spell_levels/ARG_CLASS_SPELL_LEVELS",
    "advanced_race_guide/companion_abilities",
    "advanced_race_guide/companion_abilities_static",
    "advanced_race_guide/companion_data/COMPANIONS",
    "advanced_race_guide/companion_data/COMPANION_ABILITIES",
    "advanced_race_guide/companions",
    "advanced_race_guide/companions_static",
    "advanced_race_guide/equipment_data/arms_armor/ARMS_ARMOR_TABLE",
    "advanced_race_guide/equipment_data/equipmods/EQUIPMODS_TABLE",
    "advanced_race_guide/equipment_data/general/GENERAL_TABLE",
    "advanced_race_guide/equipment_data/magic_items/MAGIC_ITEMS_TABLE",
    "advanced_race_guide/equipment_tables/equipment_resolve",
    "advanced_race_guide/equipment_tables/equipment_tables",
    "advanced_race_guide/equipment_tables/field_coverage_report",
    "advanced_race_guide/feat_data/combat/COMBAT_TABLE",
    "advanced_race_guide/feat_data/general/GENERAL_TABLE",
    "advanced_race_guide/feat_data/teamwork/TEAMWORK_TABLE",
    "advanced_race_guide/feats/feat_resolve",
    "advanced_race_guide/feats/feat_tables",
    "advanced_race_guide/monster_abilities_static",
    "advanced_race_guide/monster_data/MONSTERS",
    "advanced_race_guide/monster_data/MONSTER_ABILITIES",
    "advanced_race_guide/monsters_static",
    "advanced_race_guide/spell_list/SPELL_LIST",
    "advanced_race_guide/spell_list/spell_resolve",
    "adventurers_guide/spell_list/SPELL_LIST",
    "apg/alchemist_spell_list/ALCHEMIST_SPELL_LIST",
    "apg/alchemist_spell_list/alchemist_spell_level",
    "apg/archetype_tables/archetype_swap_tables",
    "apg/class_alchemist/class_table",
    "apg/class_cavalier/class_table",
    "apg/class_chassis_resolve",
    "apg/class_coverage",
    "apg/class_inquisitor/class_table",
    "apg/class_oracle/class_table",
    "apg/class_summoner/class_table",
    "apg/class_witch/class_table",
    "apg/companion_abilities",
    "apg/companion_abilities_static",
    "apg/companion_data/COMPANIONS",
    "apg/companion_data/COMPANION_ABILITIES",
    "apg/companions",
    "apg/companions_static",
    "apg/coverage_report",
    "apg/equipment_data/EQUIPMENT_RECORDS",
    "apg/equipment_tables/EQUIPMENT_TABLE",
    "apg/equipment_tables/equipment_resolve",
    "apg/equipment_tables/field_coverage_report",
    "apg/feat_data/combat/COMBAT_TABLE",
    "apg/feat_data/general/GENERAL_TABLE",
    "apg/feat_data/metamagic/METAMAGIC_TABLE",
    "apg/feat_data/teamwork/TEAMWORK_TABLE",
    "apg/feats/feat_tables",
    "apg/inquisitor_spell_list/INQUISITOR_SPELL_LIST",
    "apg/inquisitor_spell_list/inquisitor_spell_level",
    "apg/spell_list/ARCHETYPE_QUALIFIED_KEYS",
    "apg/spell_list/SPELL_LIST",
    "apg/spell_list/spell_coverage_report",
    "apg/spell_list/spell_resolve",
    "apg/witch_spell_list/WITCH_SPELL_LIST",
    "apg/witch_spell_list/witch_spell_level",
    "beastiary1/companion_abilities",
    "beastiary1/companion_abilities_static",
    "beastiary1/companion_data/COMPANIONS",
    "beastiary1/companion_data/COMPANION_ABILITIES",
    "beastiary1/companions",
    "beastiary1/companions_static",
    "beastiary1/equipment_data/EQUIPMENT_RECORDS",
    "beastiary1/equipment_tables/EQUIPMENT_TABLE",
    "beastiary1/equipment_tables/equipment_resolve",
    "beastiary1/equipment_tables/field_coverage_report",
    "beastiary1/monster_key_resolve",
    "beastiary1/monster_resolve",
    "beastiary1/natural_attack_provenance/GROUNDED_NATURAL_ATTACKS",
    "beastiary1/natural_attack_provenance/provenance_for",
    "bestiary/cross_table_owner_names",
    "bestiary/monster_abilities",
    "bestiary/monster_abilities_static",
    "bestiary/monster_data/MONSTERS",
    "bestiary/monster_data/MONSTER_ABILITIES",
    "bestiary/monsters",
    "bestiary/monsters_static",
    "bestiary/spell_list/SPELL_LIST",
    "bestiary_2/companion_abilities",
    "bestiary_2/companion_abilities_static",
    "bestiary_2/companion_data/COMPANIONS",
    "bestiary_2/companion_data/COMPANION_ABILITIES",
    "bestiary_2/companions",
    "bestiary_2/companions_static",
    "bestiary_2/monster_abilities",
    "bestiary_2/monster_abilities_static",
    "bestiary_2/monster_data/MONSTERS",
    "bestiary_2/monster_data/MONSTER_ABILITIES",
    "bestiary_2/monsters",
    "bestiary_2/monsters_static",
    "bestiary_3/companion_abilities",
    "bestiary_3/companion_abilities_static",
    "bestiary_3/companion_data/COMPANIONS",
    "bestiary_3/companion_data/COMPANION_ABILITIES",
    "bestiary_3/companions",
    "bestiary_3/companions_static",
    "bestiary_3/monster_abilities",
    "bestiary_3/monster_abilities_static",
    "bestiary_3/monster_data/MONSTERS",
    "bestiary_3/monster_data/MONSTER_ABILITIES",
    "bestiary_3/monsters",
    "bestiary_3/monsters_static",
    "bestiary_4/companion_abilities",
    "bestiary_4/companion_abilities_static",
    "bestiary_4/companion_data/COMPANIONS",
    "bestiary_4/companion_data/COMPANION_ABILITIES",
    "bestiary_4/companions",
    "bestiary_4/companions_static",
    "bestiary_4/monster_abilities",
    "bestiary_4/monster_abilities_static",
    "bestiary_4/monster_data/MONSTERS",
    "bestiary_4/monster_data/MONSTER_ABILITIES",
    "bestiary_4/monsters",
    "bestiary_4/monsters_static",
    "bestiary_4/spell_list/SPELL_LIST",
    "bestiary_5/companion_abilities",
    "bestiary_5/companion_abilities_static",
    "bestiary_5/companion_data/COMPANIONS",
    "bestiary_5/companion_data/COMPANION_ABILITIES",
    "bestiary_5/companions",
    "bestiary_5/companions_static",
    "bestiary_5/monster_abilities_static",
    "bestiary_5/monster_data/MONSTERS",
    "bestiary_5/monster_data/MONSTER_ABILITIES",
    "bestiary_5/monsters_static",
    "bestiary_6/companion_abilities",
    "bestiary_6/companion_abilities_static",
    "bestiary_6/companion_data/COMPANIONS",
    "bestiary_6/companion_data/COMPANION_ABILITIES",
    "bestiary_6/companions",
    "bestiary_6/companions_static",
    "bestiary_6/monster_abilities_static",
    "bestiary_6/monster_data/MONSTERS",
    "bestiary_6/monster_data/MONSTER_ABILITIES",
    "bestiary_6/monsters_static",
    "bestiary_6/spell_list/SPELL_LIST",
    "bonus_bestiary/abilities_of",
    "bonus_bestiary/monster_abilities",
    "bonus_bestiary/monster_abilities_static",
    "bonus_bestiary/monster_ability_resolve",
    "bonus_bestiary/monster_data/MONSTERS",
    "bonus_bestiary/monster_data/MONSTER_ABILITIES",
    "bonus_bestiary/monster_resolve",
    "bonus_bestiary/monsters",
    "bonus_bestiary/monsters_static",
    "book_of_the_damned_volume_1/companion_abilities",
    "book_of_the_damned_volume_1/companion_abilities_static",
    "book_of_the_damned_volume_1/companion_classes_static",
    "book_of_the_damned_volume_1/companion_data/COMPANIONS",
    "book_of_the_damned_volume_1/companion_data/COMPANION_ABILITIES",
    "book_of_the_damned_volume_1/companion_data/COMPANION_CLASSES",
    "book_of_the_damned_volume_1/companions",
    "book_of_the_damned_volume_1/companions_static",
    "book_of_the_damned_volume_1/monster_abilities",
    "book_of_the_damned_volume_1/monster_abilities_static",
    "book_of_the_damned_volume_1/monster_data/MONSTERS",
    "book_of_the_damned_volume_1/monster_data/MONSTER_ABILITIES",
    "book_of_the_damned_volume_1/monsters",
    "book_of_the_damned_volume_1/monsters_static",
    "book_of_the_damned_volume_1/spell_list/SPELL_LIST",
    "book_of_the_damned_volume_2/monster_abilities",
    "book_of_the_damned_volume_2/monster_abilities_static",
    "book_of_the_damned_volume_2/monster_data/MONSTERS",
    "book_of_the_damned_volume_2/monster_data/MONSTER_ABILITIES",
    "book_of_the_damned_volume_2/monsters",
    "book_of_the_damned_volume_2/monsters_static",
    "book_of_the_damned_volume_2/spell_list/SPELL_LIST",
    "class_spell_levels/STATIC_CLASS_SPELL_LISTS",
    "class_spell_levels/arg_supplement_entries",
    "class_spell_levels/arg_supplement_level",
    "class_spell_levels/class_has_spell_list",
    "class_spell_levels/class_spell_level",
    "class_spell_levels/class_spell_list_entries",
    "class_spell_levels/classes_with_spell_lists",
    "class_spell_levels/hunter_arg_supplement_level",
    "companion_chassis/COMPANION_BOOKS",
    "companion_chassis/COMPANION_BOOK_REGISTRY",
    "companion_chassis/GRANT_TOKEN_ONLY_DISPATCH_ROWS",
    "companion_chassis/companion_book",
    "companion_chassis/grant_token_only_dispatch_reason",
    "crb/bard_spell_list/BARD_SPELL_LIST",
    "crb/bard_spell_list/bard_spell_level",
    "crb/class_skill_tables/CLASS_SKILL_LISTS",
    "crb/class_skill_tables/class_skill_list",
    "crb/class_tables/CLASS_META",
    "crb/class_tables/class_tables",
    "crb/class_tables/good_saves_for",
    "crb/class_tables/hit_die_for",
    "crb/cleric_spell_list/CLERIC_SPELL_LIST",
    "crb/cleric_spell_list/cleric_spell_level",
    "crb/companion_abilities",
    "crb/companion_abilities_static",
    "crb/companion_classes_static",
    "crb/companion_data/COMPANIONS",
    "crb/companion_data/COMPANION_ABILITIES",
    "crb/companion_data/COMPANION_CLASSES",
    "crb/companions",
    "crb/companions_static",
    "crb/druid_spell_list/DRUID_SPELL_LIST",
    "crb/druid_spell_list/druid_spell_level",
    "crb/equipment_data/arms_armor/ARMS_ARMOR_TABLE",
    "crb/equipment_data/equipmods/EQUIPMODS_TABLE",
    "crb/equipment_data/general/GENERAL_TABLE",
    "crb/equipment_data/magic_items/MAGIC_ITEMS_TABLE",
    "crb/equipment_tables/equipment_tables",
    "crb/equipment_tables/field_coverage_report",
    "crb/feat_data/combat/COMBAT_TABLE",
    "crb/feat_data/general/GENERAL_TABLE",
    "crb/feat_data/item_creation/ITEM_CREATION_TABLE",
    "crb/feat_data/metamagic/METAMAGIC_TABLE",
    "crb/feats/feat_tables",
    "crb/paladin_spell_list/PALADIN_SPELL_LIST",
    "crb/paladin_spell_list/paladin_spell_level",
    "crb/race_tables/RACE_TRAITS",
    "crb/race_tables/race_traits",
    "crb/ranger_spell_list/RANGER_SPELL_LIST",
    "crb/ranger_spell_list/ranger_spell_level",
    "crb/sorcerer_spell_list/SORCERER_SPELL_LIST",
    "crb/sorcerer_spell_list/sorcerer_spell_level",
    "crb/spell_list/SPELL_LIST",
    "crb/spell_list/spell_coverage_report",
    "crb/weapon_tables/CLASS_ARMOR_PROFICIENCIES",
    "crb/weapon_tables/CLASS_WEAPON_PROFICIENCIES",
    "crb/weapon_tables/FINESSEABLE_WEAPON_KEYS",
    "crb/weapon_tables/WEAPON_TABLE",
    "crb/weapon_tables/class_armor_proficiency",
    "crb/weapon_tables/class_weapon_proficiency",
    "crb/weapon_tables/weapon_by_key",
    "crb/weapon_tables/weapon_is_finesseable",
    "crb/wizard_spell_list/WIZARD_SPELL_LIST",
    "crb/wizard_spell_list/wizard_school_zero_level_spells",
    "crb/wizard_spell_list/wizard_spell_level",
    "equipment_gap_tables/ADVANCED_CLASS_GUIDE_GAP_ROWS",
    "equipment_gap_tables/ADVANCED_PLAYERS_GUIDE_GAP_ROWS",
    "equipment_gap_tables/ADVANCED_RACE_GUIDE_GAP_ROWS",
    "equipment_gap_tables/ADVENTURERS_GUIDE_GAP_ROWS",
    "equipment_gap_tables/BEGINNER_BOX_GAP_ROWS",
    "equipment_gap_tables/BESTIARY_2_GAP_ROWS",
    "equipment_gap_tables/BESTIARY_3_GAP_ROWS",
    "equipment_gap_tables/BESTIARY_4_GAP_ROWS",
    "equipment_gap_tables/BESTIARY_GAP_ROWS",
    "equipment_gap_tables/BOOK_OF_THE_DAMNED_VOLUME_2_GAP_ROWS",
    "equipment_gap_tables/CORE_RULEBOOK_GAP_ROWS",
    "equipment_gap_tables/HORROR_ADVENTURES_GAP_ROWS",
    "equipment_gap_tables/INNER_SEA_COMBAT_GAP_ROWS",
    "equipment_gap_tables/INNER_SEA_GODS_GAP_ROWS",
    "equipment_gap_tables/INNER_SEA_INTRIGUE_GAP_ROWS",
    "equipment_gap_tables/INNER_SEA_MAGIC_GAP_ROWS",
    "equipment_gap_tables/INNER_SEA_RACES_GAP_ROWS",
    "equipment_gap_tables/INNER_SEA_TEMPLES_GAP_ROWS",
    "equipment_gap_tables/INNER_SEA_WORLD_GUIDE_GAP_ROWS",
    "equipment_gap_tables/MONSTER_CODEX_GAP_ROWS",
    "equipment_gap_tables/MYTHIC_ADVENTURES_GAP_ROWS",
    "equipment_gap_tables/OCCULT_ADVENTURES_GAP_ROWS",
    "equipment_gap_tables/ULTIMATE_COMBAT_GAP_ROWS",
    "equipment_gap_tables/ULTIMATE_EQUIPMENT_GAP_ROWS",
    "equipment_gap_tables/ULTIMATE_INTRIGUE_GAP_ROWS",
    "equipment_gap_tables/ULTIMATE_MAGIC_GAP_ROWS",
    "equipment_gap_tables/ULTIMATE_PSIONICS_GAP_ROWS",
    "equipment_gap_tables/ULTIMATE_WILDERNESS_GAP_ROWS",
    "equipment_gap_tables/equipment_gap_rows",
    "feat_gap_tables/ADVANCED_RACE_GUIDE_FEAT_GAP_ROWS",
    "feat_gap_tables/BOOK_OF_THE_DAMNED_VOLUME_2_FEAT_GAP_ROWS",
    "feat_gap_tables/CORE_ESSENTIALS_FEAT_GAP_ROWS",
    "feat_gap_tables/CORE_RULEBOOK_FEAT_GAP_ROWS",
    "feat_gap_tables/HORROR_ADVENTURES_FEAT_GAP_ROWS",
    "feat_gap_tables/INNER_SEA_COMBAT_FEAT_GAP_ROWS",
    "feat_gap_tables/INNER_SEA_GODS_FEAT_GAP_ROWS",
    "feat_gap_tables/INNER_SEA_INTRIGUE_FEAT_GAP_ROWS",
    "feat_gap_tables/INNER_SEA_RACES_FEAT_GAP_ROWS",
    "feat_gap_tables/INNER_SEA_TAVERNS_FEAT_GAP_ROWS",
    "feat_gap_tables/INNER_SEA_WORLD_GUIDE_FEAT_GAP_ROWS",
    "feat_gap_tables/MONSTER_CODEX_FEAT_GAP_ROWS",
    "feat_gap_tables/MYTHIC_ADVENTURES_FEAT_GAP_ROWS",
    "feat_gap_tables/OCCULT_ADVENTURES_FEAT_GAP_ROWS",
    "feat_gap_tables/ULTIMATE_COMBAT_FEAT_GAP_ROWS",
    "feat_gap_tables/ULTIMATE_INTRIGUE_FEAT_GAP_ROWS",
    "feat_gap_tables/ULTIMATE_MAGIC_FEAT_GAP_ROWS",
    "feat_gap_tables/ULTIMATE_PSIONICS_FEAT_GAP_ROWS",
    "feat_gap_tables/ULTIMATE_WILDERNESS_FEAT_GAP_ROWS",
    "feat_gap_tables/feat_gap_rows_for",
    "feats_all/acg_records",
    "feats_all/all_feat_tables",
    "feats_all/apg_records",
    "feats_all/arg_records",
    "feats_all/crb_records",
    "feats_all/hand_authored_feat_tables",
    "feats_all/map_uca_entry",
    "feats_all/pu_records",
    "feats_all/uc_records",
    "feats_all/uca_records",
    "feats_all/ui_records",
    "feats_all/um_records",
    "feats_all/upsi_records",
    "feats_all/uw_records",
    "horror_adventures/companion_abilities",
    "horror_adventures/companion_abilities_static",
    "horror_adventures/companion_data/COMPANIONS",
    "horror_adventures/companion_data/COMPANION_ABILITIES",
    "horror_adventures/companions",
    "horror_adventures/companions_static",
    "horror_adventures/monster_abilities",
    "horror_adventures/monster_abilities_static",
    "horror_adventures/monster_data/MONSTERS",
    "horror_adventures/monster_data/MONSTER_ABILITIES",
    "horror_adventures/monsters",
    "horror_adventures/monsters_static",
    "horror_adventures/spell_list/SPELL_LIST",
    "inner_sea_bestiary/monster_abilities",
    "inner_sea_bestiary/monster_abilities_static",
    "inner_sea_bestiary/monster_data/MONSTERS",
    "inner_sea_bestiary/monster_data/MONSTER_ABILITIES",
    "inner_sea_bestiary/monsters",
    "inner_sea_bestiary/monsters_static",
    "inner_sea_combat/companion_abilities",
    "inner_sea_combat/companion_abilities_static",
    "inner_sea_combat/companion_data/COMPANIONS",
    "inner_sea_combat/companion_data/COMPANION_ABILITIES",
    "inner_sea_combat/companions",
    "inner_sea_combat/companions_static",
    "inner_sea_faiths/spell_list/SPELL_LIST",
    "inner_sea_gods/monster_abilities",
    "inner_sea_gods/monster_abilities_static",
    "inner_sea_gods/monster_data/MONSTERS",
    "inner_sea_gods/monster_data/MONSTER_ABILITIES",
    "inner_sea_gods/monsters",
    "inner_sea_gods/monsters_static",
    "inner_sea_gods/spell_list/SPELL_LIST",
    "inner_sea_intrigue/companion_abilities",
    "inner_sea_intrigue/companion_abilities_static",
    "inner_sea_intrigue/companion_data/COMPANIONS",
    "inner_sea_intrigue/companion_data/COMPANION_ABILITIES",
    "inner_sea_intrigue/companions",
    "inner_sea_intrigue/companions_static",
    "inner_sea_intrigue/spell_list/SPELL_LIST",
    "inner_sea_magic/spell_list/SPELL_LIST",
    "inner_sea_races/spell_list/SPELL_LIST",
    "inner_sea_temples/spell_list/SPELL_LIST",
    "inner_sea_world_guide/monster_abilities",
    "inner_sea_world_guide/monster_abilities_static",
    "inner_sea_world_guide/monster_data/MONSTERS",
    "inner_sea_world_guide/monster_data/MONSTER_ABILITIES",
    "inner_sea_world_guide/monsters",
    "inner_sea_world_guide/monsters_static",
    "inner_sea_world_guide/spell_list/SPELL_LIST",
    "monster_chassis/MONSTER_BOOKS",
    "monster_chassis/MONSTER_BOOK_REGISTRY",
    "monster_chassis/monster_book",
    "monster_codex/companion_abilities",
    "monster_codex/companion_abilities_static",
    "monster_codex/companion_data/COMPANIONS",
    "monster_codex/companion_data/COMPANION_ABILITIES",
    "monster_codex/companions",
    "monster_codex/companions_static",
    "monster_codex/monster_abilities",
    "monster_codex/monster_abilities_static",
    "monster_codex/monster_data/MONSTERS",
    "monster_codex/monster_data/MONSTER_ABILITIES",
    "monster_codex/monsters",
    "monster_codex/monsters_static",
    "monster_codex/spell_list/SPELL_LIST",
    "mythic_adventures/monster_abilities_static",
    "mythic_adventures/monster_data/MONSTERS",
    "mythic_adventures/monster_data/MONSTER_ABILITIES",
    "mythic_adventures/monsters_static",
    "mythic_adventures/spell_list/SPELL_LIST",
    "occult_adventures/monster_abilities_static",
    "occult_adventures/monster_data/MONSTERS",
    "occult_adventures/monster_data/MONSTER_ABILITIES",
    "occult_adventures/monsters_static",
    "occult_adventures/spell_list/SPELL_LIST",
    "pathfinder_unchained/barbarian_features/FEATURES",
    "pathfinder_unchained/barbarian_features/feature",
    "pathfinder_unchained/barbarian_features/features",
    "pathfinder_unchained/class_chassis/class_chassis_resolve",
    "pathfinder_unchained/class_chassis/hit_die_for",
    "pathfinder_unchained/equipment_tables/equipment_tables",
    "pathfinder_unchained/feat_tables/feat_tables",
    "pathfinder_unchained/monk_features/FEATURES",
    "pathfinder_unchained/monk_features/feature",
    "pathfinder_unchained/monk_features/features",
    "pathfinder_unchained/monster_abilities_static",
    "pathfinder_unchained/monster_data/MONSTERS",
    "pathfinder_unchained/monster_data/MONSTER_ABILITIES",
    "pathfinder_unchained/monsters_static",
    "pathfinder_unchained/rogue_features/active_level",
    "pathfinder_unchained/rogue_features/class_skills",
    "pathfinder_unchained/rogue_features/danger_sense_bonus",
    "pathfinder_unchained/rogue_features/finesse_training_weapon_choices",
    "pathfinder_unchained/rogue_features/master_strike_dc",
    "pathfinder_unchained/rogue_features/rogue_talents_known",
    "pathfinder_unchained/rogue_features/rogues_edge_skill_unlocks",
    "pathfinder_unchained/rogue_features/sneak_attack_dice",
    "pathfinder_unchained/rogue_features/trapfinding_bonus",
    "pathfinder_unchained/rogue_features/uncanny_dodge_flanking_level",
    "pathfinder_unchained/rogue_features/uncanny_dodge_tracker_steps",
    "pathfinder_unchained/summoner_features/EIDOLON_EVOLUTION_THRESHOLDS",
    "pathfinder_unchained/summoner_features/active_level",
    "pathfinder_unchained/summoner_features/class_skills",
    "pathfinder_unchained/summoner_features/eidolon_companion_level",
    "pathfinder_unchained/summoner_features/eidolon_evolution_pool",
    "pathfinder_unchained/summoner_features/eidolon_subtypes",
    "pathfinder_unchained/summoner_features/summon_monster_spell_level",
    "pathfinder_unchained/summoner_features/summon_monster_uses_per_day",
    "pathfinder_unchained/summoner_features/unchained_summoner_marker",
    "simple_kind_tables/SEVEN_KIND_DIRS",
    "simple_kind_tables/kind_dir_for",
    "simple_kind_tables/load_simple_kind_table",
    "ultimate_campaign/feat_tables/DEFERRED_WITH_REASON",
    "ultimate_campaign/feat_tables/feat_tables",
    "ultimate_combat/archetype_tables/archetype_swap_tables",
    "ultimate_combat/class_chassis_resolve",
    "ultimate_combat/class_gunslinger/class_table",
    "ultimate_combat/class_ninja/class_table",
    "ultimate_combat/class_samurai/class_table",
    "ultimate_combat/equipment_tables/ARMS_ARMOR_TABLE",
    "ultimate_combat/equipment_tables/EQUIPMODS_TABLE",
    "ultimate_combat/equipment_tables/GENERAL_TABLE",
    "ultimate_combat/equipment_tables/MAGIC_ITEMS_TABLE",
    "ultimate_combat/equipment_tables/equipment_resolve",
    "ultimate_combat/equipment_tables/equipment_tables",
    "ultimate_combat/equipment_tables/equipmod_tables",
    "ultimate_combat/equipment_tables/field_coverage_report",
    "ultimate_combat/feat_tables/feat_tables",
    "ultimate_combat/spell_list/SPELL_LIST",
    "ultimate_equipment/equipment_tables/equipment_tables",
    "ultimate_equipment/equipment_tables/equipmod_tables",
    "ultimate_equipment/spell_list/SPELL_LIST",
    "ultimate_intrigue/equipment_tables/equipment_tables",
    "ultimate_intrigue/equipment_tables/equipmod_tables",
    "ultimate_intrigue/feat_tables/feat_tables",
    "ultimate_intrigue/monster_abilities_static",
    "ultimate_intrigue/monster_data/MONSTERS",
    "ultimate_intrigue/monster_data/MONSTER_ABILITIES",
    "ultimate_intrigue/monsters_static",
    "ultimate_intrigue/spell_list/SPELL_LIST",
    "ultimate_magic/archetype_tables/archetype_swap_tables",
    "ultimate_magic/companion_abilities",
    "ultimate_magic/companion_abilities_static",
    "ultimate_magic/companion_classes_static",
    "ultimate_magic/companion_data/COMPANIONS",
    "ultimate_magic/companion_data/COMPANION_ABILITIES",
    "ultimate_magic/companion_data/COMPANION_CLASSES",
    "ultimate_magic/companions",
    "ultimate_magic/companions_static",
    "ultimate_magic/equipment_tables/ARMS_ARMOR_TABLE",
    "ultimate_magic/equipment_tables/GENERAL_TABLE",
    "ultimate_magic/equipment_tables/equipment_resolve",
    "ultimate_magic/equipment_tables/equipment_tables",
    "ultimate_magic/equipment_tables/equipmod_tables",
    "ultimate_magic/equipment_tables/field_coverage_report",
    "ultimate_magic/feat_tables/feat_tables",
    "ultimate_magic/monster_abilities_static",
    "ultimate_magic/monster_data/MONSTERS",
    "ultimate_magic/monster_data/MONSTER_ABILITIES",
    "ultimate_magic/monsters_static",
    "ultimate_magic/spell_list/SPELL_LIST",
    "ultimate_magic_wordsofpower/spell_list/SPELL_LIST",
    "ultimate_psionics/archetype_tables/archetype_swap_tables",
    "ultimate_psionics/cryptic_features/cryptic_power_points_total",
    "ultimate_psionics/dread_features/dread_power_points_total",
    "ultimate_psionics/equipment_tables/EQUIPMENT_TABLE",
    "ultimate_psionics/equipment_tables/EQUIPMODS_TABLE",
    "ultimate_psionics/equipment_tables/EXCLUDED_LEGACY_ALIAS_SHORT_CODES",
    "ultimate_psionics/equipment_tables/equipment_resolve",
    "ultimate_psionics/equipment_tables/equipment_tables",
    "ultimate_psionics/equipment_tables/equipmod_tables",
    "ultimate_psionics/equipment_tables/field_coverage_report",
    "ultimate_psionics/feat_tables/feat_tables",
    "ultimate_psionics/marksman_features/marksman_power_points_total",
    "ultimate_psionics/monster_abilities",
    "ultimate_psionics/monster_abilities_static",
    "ultimate_psionics/monster_data/MONSTERS",
    "ultimate_psionics/monster_data/MONSTER_ABILITIES",
    "ultimate_psionics/monsters",
    "ultimate_psionics/monsters_static",
    "ultimate_psionics/psion_features/psion_power_points_total",
    "ultimate_psionics/psychic_warrior_features/psychic_warrior_power_points_total",
    "ultimate_psionics/tactician_features/tactician_power_points_total",
    "ultimate_psionics/vitalist_features/vitalist_power_points_total",
    "ultimate_psionics/wilder_features/wilder_power_points_total",
    "ultimate_wilderness/archetype_tables/archetype_swap_tables",
    "ultimate_wilderness/companion_abilities",
    "ultimate_wilderness/companion_abilities_static",
    "ultimate_wilderness/companion_data/COMPANIONS",
    "ultimate_wilderness/companion_data/COMPANION_ABILITIES",
    "ultimate_wilderness/companions",
    "ultimate_wilderness/companions_static",
    "ultimate_wilderness/feat_tables/feat_tables",
    "ultimate_wilderness/monster_abilities_static",
    "ultimate_wilderness/monster_data/MONSTERS",
    "ultimate_wilderness/monster_data/MONSTER_ABILITIES",
    "ultimate_wilderness/monsters_static",
    "ultimate_wilderness/spell_list/SPELL_LIST",
];
