//! Package-backed mirror of the compiled `rules_tables` module `equipment_gap_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::equipment_gap_tables::EquipmentGapRow;
pub fn equipment_gap_rows() -> impl Iterator<Item = &'static EquipmentGapRow> {
    [
        &*CORE_RULEBOOK_GAP_ROWS,
        &*BESTIARY_GAP_ROWS,
        &*ADVANCED_PLAYERS_GUIDE_GAP_ROWS,
        &*ADVANCED_CLASS_GUIDE_GAP_ROWS,
        &*ADVANCED_RACE_GUIDE_GAP_ROWS,
        &*ULTIMATE_COMBAT_GAP_ROWS,
        &*ULTIMATE_INTRIGUE_GAP_ROWS,
        &*ULTIMATE_EQUIPMENT_GAP_ROWS,
        &*ULTIMATE_PSIONICS_GAP_ROWS,
        &*ULTIMATE_WILDERNESS_GAP_ROWS,
        &*OCCULT_ADVENTURES_GAP_ROWS,
        &*HORROR_ADVENTURES_GAP_ROWS,
        &*INNER_SEA_RACES_GAP_ROWS,
        &*INNER_SEA_WORLD_GUIDE_GAP_ROWS,
        &*MONSTER_CODEX_GAP_ROWS,
        &*BESTIARY_2_GAP_ROWS,
        &*BESTIARY_3_GAP_ROWS,
        &*BESTIARY_4_GAP_ROWS,
        &*INNER_SEA_GODS_GAP_ROWS,
        &*MYTHIC_ADVENTURES_GAP_ROWS,
        &*INNER_SEA_COMBAT_GAP_ROWS,
        &*INNER_SEA_INTRIGUE_GAP_ROWS,
        &*BOOK_OF_THE_DAMNED_VOLUME_2_GAP_ROWS,
        &*INNER_SEA_TEMPLES_GAP_ROWS,
        &*INNER_SEA_MAGIC_GAP_ROWS,
        &*ADVENTURERS_GUIDE_GAP_ROWS,
        &*ULTIMATE_MAGIC_GAP_ROWS,
        &*BEGINNER_BOX_GAP_ROWS,
    ]
    .into_iter()
    .flat_map(|rows| rows.iter())
}
pub static CORE_RULEBOOK_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/CORE_RULEBOOK_GAP_ROWS");
pub static BESTIARY_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/BESTIARY_GAP_ROWS");
pub static ADVANCED_PLAYERS_GUIDE_GAP_ROWS: crate::rules_core::rules_catalog::Table<
    EquipmentGapRow,
> = crate::rules_core::rules_catalog::Table::new(
    "equipment_gap_tables/ADVANCED_PLAYERS_GUIDE_GAP_ROWS",
);
pub static ADVANCED_CLASS_GUIDE_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new(
        "equipment_gap_tables/ADVANCED_CLASS_GUIDE_GAP_ROWS",
    );
pub static ADVANCED_RACE_GUIDE_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new(
        "equipment_gap_tables/ADVANCED_RACE_GUIDE_GAP_ROWS",
    );
pub static ULTIMATE_COMBAT_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/ULTIMATE_COMBAT_GAP_ROWS");
pub static ULTIMATE_INTRIGUE_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/ULTIMATE_INTRIGUE_GAP_ROWS");
pub static ULTIMATE_EQUIPMENT_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new(
        "equipment_gap_tables/ULTIMATE_EQUIPMENT_GAP_ROWS",
    );
pub static ULTIMATE_PSIONICS_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/ULTIMATE_PSIONICS_GAP_ROWS");
pub static ULTIMATE_WILDERNESS_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new(
        "equipment_gap_tables/ULTIMATE_WILDERNESS_GAP_ROWS",
    );
pub static OCCULT_ADVENTURES_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/OCCULT_ADVENTURES_GAP_ROWS");
pub static HORROR_ADVENTURES_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/HORROR_ADVENTURES_GAP_ROWS");
pub static INNER_SEA_RACES_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/INNER_SEA_RACES_GAP_ROWS");
pub static INNER_SEA_WORLD_GUIDE_GAP_ROWS: crate::rules_core::rules_catalog::Table<
    EquipmentGapRow,
> = crate::rules_core::rules_catalog::Table::new(
    "equipment_gap_tables/INNER_SEA_WORLD_GUIDE_GAP_ROWS",
);
pub static MONSTER_CODEX_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/MONSTER_CODEX_GAP_ROWS");
pub static BESTIARY_2_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/BESTIARY_2_GAP_ROWS");
pub static BESTIARY_3_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/BESTIARY_3_GAP_ROWS");
pub static BESTIARY_4_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/BESTIARY_4_GAP_ROWS");
pub static INNER_SEA_GODS_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/INNER_SEA_GODS_GAP_ROWS");
pub static MYTHIC_ADVENTURES_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/MYTHIC_ADVENTURES_GAP_ROWS");
pub static INNER_SEA_COMBAT_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/INNER_SEA_COMBAT_GAP_ROWS");
pub static INNER_SEA_INTRIGUE_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new(
        "equipment_gap_tables/INNER_SEA_INTRIGUE_GAP_ROWS",
    );
pub static BOOK_OF_THE_DAMNED_VOLUME_2_GAP_ROWS: crate::rules_core::rules_catalog::Table<
    EquipmentGapRow,
> = crate::rules_core::rules_catalog::Table::new(
    "equipment_gap_tables/BOOK_OF_THE_DAMNED_VOLUME_2_GAP_ROWS",
);
pub static INNER_SEA_TEMPLES_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/INNER_SEA_TEMPLES_GAP_ROWS");
pub static INNER_SEA_MAGIC_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/INNER_SEA_MAGIC_GAP_ROWS");
pub static ADVENTURERS_GUIDE_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/ADVENTURERS_GUIDE_GAP_ROWS");
pub static ULTIMATE_MAGIC_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/ULTIMATE_MAGIC_GAP_ROWS");
pub static BEGINNER_BOX_GAP_ROWS: crate::rules_core::rules_catalog::Table<EquipmentGapRow> =
    crate::rules_core::rules_catalog::Table::new("equipment_gap_tables/BEGINNER_BOX_GAP_ROWS");
