//! Golden digests of every package-backed table, view and table-reading lookup (SD-37 E4a.4).
//!
//! E4a.2 proved the catalog equal to the compiled `rules_tables` module row for row
//! (`equivalence_tests`, `override_tests`). E4a.4 deletes that module, so the proof is kept as
//! data: `golden_digests.txt` holds one sha256 per transcript, written FROM THE COMPILED MODULE
//! on the last tree that had it, and this test re-derives every transcript from the catalog (the
//! package plus the catalog's own code) and requires the same digest. A package row edited by
//! hand, or a moved type that serialises differently, changes a digest and names its id.
//! Generated by `artifacts/epic_4a/E4a.4_tools/gen_golden_tests.py` from E4a.2's equivalence list.
#![allow(clippy::all)]

use crate::rules_core::rules_catalog as cat;
use sha2::{Digest, Sha256};
use std::fmt::Debug;

/// A table's rows as a slice, whichever shape holds them (a catalog `Table`/`Derived`, a
/// compiled array or slice).
trait Rows {
    type Item;
    fn rows(&self) -> &[Self::Item];
}
impl<T> Rows for [T] {
    type Item = T;
    fn rows(&self) -> &[T] { self }
}
impl<T, const N: usize> Rows for [T; N] {
    type Item = T;
    fn rows(&self) -> &[T] { self }
}
impl<T> Rows for &[T] {
    type Item = T;
    fn rows(&self) -> &[T] { self }
}
impl<T> Rows for cat::Table<T>
where
    T: serde::Deserialize<'static> + Send + Sync + 'static,
{
    type Item = T;
    fn rows(&self) -> &[T] { self }
}
impl<T: Send + Sync + 'static> Rows for cat::Derived<T> {
    type Item = T;
    fn rows(&self) -> &[T] { self }
}
fn rows_of<R: Rows + ?Sized>(r: &R) -> &[R::Item] {
    r.rows()
}
fn json_of<T: serde::Serialize + ?Sized>(value: &T) -> String {
    serde_json::to_string(value).expect("serialise")
}
fn debug_of<T: Debug + ?Sized>(value: &T) -> String {
    format!("{value:?}")
}

macro_rules! transcripts {
    ($r:ident) => {{
        let mut out: Vec<(&'static str, String)> = Vec::new();
        out.push(("acg/bloodrager_spell_list/BLOODRAGER_SPELL_LIST", json_of(rows_of(&$r::acg::bloodrager_spell_list::BLOODRAGER_SPELL_LIST))));
        out.push(("acg/equipment_data/arms_armor/ARMS_ARMOR_TABLE", json_of(rows_of(&$r::acg::equipment_data::arms_armor::ARMS_ARMOR_TABLE))));
        out.push(("acg/equipment_data/equipmods/EQUIPMODS_TABLE", json_of(rows_of(&$r::acg::equipment_data::equipmods::EQUIPMODS_TABLE))));
        out.push(("acg/equipment_data/general/GENERAL_TABLE", json_of(rows_of(&$r::acg::equipment_data::general::GENERAL_TABLE))));
        out.push(("acg/equipment_data/magic_items/MAGIC_ITEMS_TABLE", json_of(rows_of(&$r::acg::equipment_data::magic_items::MAGIC_ITEMS_TABLE))));
        out.push(("acg/feat_data/combat/COMBAT_TABLE", json_of(rows_of(&$r::acg::feat_data::combat::COMBAT_TABLE))));
        out.push(("acg/feat_data/general/GENERAL_TABLE", json_of(rows_of(&$r::acg::feat_data::general::GENERAL_TABLE))));
        out.push(("acg/feat_data/panache/PANACHE_TABLE", json_of(rows_of(&$r::acg::feat_data::panache::PANACHE_TABLE))));
        out.push(("acg/feat_data/teamwork/TEAMWORK_TABLE", json_of(rows_of(&$r::acg::feat_data::teamwork::TEAMWORK_TABLE))));
        out.push(("acg/shaman_spell_list/SHAMAN_SPELL_LIST", json_of(rows_of(&$r::acg::shaman_spell_list::SHAMAN_SPELL_LIST))));
        out.push(("acg/shaman_spell_list/SHAMAN_SPELLS_NOT_INGESTED", json_of(rows_of(&$r::acg::shaman_spell_list::SHAMAN_SPELLS_NOT_INGESTED))));
        out.push(("acg/spell_list/SPELL_LIST", json_of(rows_of(&$r::acg::spell_list::SPELL_LIST))));
        out.push(("acg/spell_list/ARCHETYPE_QUALIFIED_KEYS", json_of(rows_of(&$r::acg::spell_list::ARCHETYPE_QUALIFIED_KEYS))));
        out.push(("advanced_race_guide/companion_data/COMPANIONS", json_of(rows_of(&$r::advanced_race_guide::companion_data::COMPANIONS))));
        out.push(("advanced_race_guide/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::advanced_race_guide::companion_data::COMPANION_ABILITIES))));
        out.push(("advanced_race_guide/equipment_data/arms_armor/ARMS_ARMOR_TABLE", json_of(rows_of(&$r::advanced_race_guide::equipment_data::arms_armor::ARMS_ARMOR_TABLE))));
        out.push(("advanced_race_guide/equipment_data/equipmods/EQUIPMODS_TABLE", json_of(rows_of(&$r::advanced_race_guide::equipment_data::equipmods::EQUIPMODS_TABLE))));
        out.push(("advanced_race_guide/equipment_data/general/GENERAL_TABLE", json_of(rows_of(&$r::advanced_race_guide::equipment_data::general::GENERAL_TABLE))));
        out.push(("advanced_race_guide/equipment_data/magic_items/MAGIC_ITEMS_TABLE", json_of(rows_of(&$r::advanced_race_guide::equipment_data::magic_items::MAGIC_ITEMS_TABLE))));
        out.push(("advanced_race_guide/feat_data/combat/COMBAT_TABLE", json_of(rows_of(&$r::advanced_race_guide::feat_data::combat::COMBAT_TABLE))));
        out.push(("advanced_race_guide/feat_data/general/GENERAL_TABLE", json_of(rows_of(&$r::advanced_race_guide::feat_data::general::GENERAL_TABLE))));
        out.push(("advanced_race_guide/feat_data/teamwork/TEAMWORK_TABLE", json_of(rows_of(&$r::advanced_race_guide::feat_data::teamwork::TEAMWORK_TABLE))));
        out.push(("advanced_race_guide/monster_data/MONSTERS", json_of(rows_of(&$r::advanced_race_guide::monster_data::MONSTERS))));
        out.push(("advanced_race_guide/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::advanced_race_guide::monster_data::MONSTER_ABILITIES))));
        out.push(("advanced_race_guide/spell_list/SPELL_LIST", json_of(rows_of(&$r::advanced_race_guide::spell_list::SPELL_LIST))));
        out.push(("adventurers_guide/spell_list/SPELL_LIST", json_of(rows_of(&$r::adventurers_guide::spell_list::SPELL_LIST))));
        out.push(("apg/alchemist_spell_list/ALCHEMIST_SPELL_LIST", json_of(rows_of(&$r::apg::alchemist_spell_list::ALCHEMIST_SPELL_LIST))));
        out.push(("apg/companion_data/COMPANIONS", json_of(rows_of(&$r::apg::companion_data::COMPANIONS))));
        out.push(("apg/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::apg::companion_data::COMPANION_ABILITIES))));
        out.push(("apg/equipment_data/EQUIPMENT_RECORDS", json_of(rows_of(&$r::apg::equipment_data::EQUIPMENT_RECORDS))));
        out.push(("apg/equipment_tables/EQUIPMENT_TABLE", json_of(rows_of(&$r::apg::equipment_tables::EQUIPMENT_TABLE))));
        out.push(("apg/feat_data/combat/COMBAT_TABLE", json_of(rows_of(&$r::apg::feat_data::combat::COMBAT_TABLE))));
        out.push(("apg/feat_data/general/GENERAL_TABLE", json_of(rows_of(&$r::apg::feat_data::general::GENERAL_TABLE))));
        out.push(("apg/feat_data/metamagic/METAMAGIC_TABLE", json_of(rows_of(&$r::apg::feat_data::metamagic::METAMAGIC_TABLE))));
        out.push(("apg/feat_data/teamwork/TEAMWORK_TABLE", json_of(rows_of(&$r::apg::feat_data::teamwork::TEAMWORK_TABLE))));
        out.push(("apg/inquisitor_spell_list/INQUISITOR_SPELL_LIST", json_of(rows_of(&$r::apg::inquisitor_spell_list::INQUISITOR_SPELL_LIST))));
        out.push(("apg/spell_list/SPELL_LIST", json_of(rows_of(&$r::apg::spell_list::SPELL_LIST))));
        out.push(("apg/spell_list/ARCHETYPE_QUALIFIED_KEYS", json_of(rows_of(&$r::apg::spell_list::ARCHETYPE_QUALIFIED_KEYS))));
        out.push(("apg/witch_spell_list/WITCH_SPELL_LIST", json_of(rows_of(&$r::apg::witch_spell_list::WITCH_SPELL_LIST))));
        out.push(("beastiary1/companion_data/COMPANIONS", json_of(rows_of(&$r::beastiary1::companion_data::COMPANIONS))));
        out.push(("beastiary1/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::beastiary1::companion_data::COMPANION_ABILITIES))));
        out.push(("beastiary1/equipment_data/EQUIPMENT_RECORDS", json_of(rows_of(&$r::beastiary1::equipment_data::EQUIPMENT_RECORDS))));
        out.push(("beastiary1/equipment_tables/EQUIPMENT_TABLE", json_of(rows_of(&$r::beastiary1::equipment_tables::EQUIPMENT_TABLE))));
        out.push(("beastiary1/natural_attack_provenance/GROUNDED_NATURAL_ATTACKS", json_of(rows_of(&$r::beastiary1::natural_attack_provenance::GROUNDED_NATURAL_ATTACKS))));
        out.push(("bestiary/monster_data/MONSTERS", json_of(rows_of(&$r::bestiary::monster_data::MONSTERS))));
        out.push(("bestiary/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::bestiary::monster_data::MONSTER_ABILITIES))));
        out.push(("bestiary/spell_list/SPELL_LIST", json_of(rows_of(&$r::bestiary::spell_list::SPELL_LIST))));
        out.push(("bestiary_2/companion_data/COMPANIONS", json_of(rows_of(&$r::bestiary_2::companion_data::COMPANIONS))));
        out.push(("bestiary_2/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::bestiary_2::companion_data::COMPANION_ABILITIES))));
        out.push(("bestiary_2/monster_data/MONSTERS", json_of(rows_of(&$r::bestiary_2::monster_data::MONSTERS))));
        out.push(("bestiary_2/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::bestiary_2::monster_data::MONSTER_ABILITIES))));
        out.push(("bestiary_3/companion_data/COMPANIONS", json_of(rows_of(&$r::bestiary_3::companion_data::COMPANIONS))));
        out.push(("bestiary_3/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::bestiary_3::companion_data::COMPANION_ABILITIES))));
        out.push(("bestiary_3/monster_data/MONSTERS", json_of(rows_of(&$r::bestiary_3::monster_data::MONSTERS))));
        out.push(("bestiary_3/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::bestiary_3::monster_data::MONSTER_ABILITIES))));
        out.push(("bestiary_4/companion_data/COMPANIONS", json_of(rows_of(&$r::bestiary_4::companion_data::COMPANIONS))));
        out.push(("bestiary_4/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::bestiary_4::companion_data::COMPANION_ABILITIES))));
        out.push(("bestiary_4/monster_data/MONSTERS", json_of(rows_of(&$r::bestiary_4::monster_data::MONSTERS))));
        out.push(("bestiary_4/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::bestiary_4::monster_data::MONSTER_ABILITIES))));
        out.push(("bestiary_4/spell_list/SPELL_LIST", json_of(rows_of(&$r::bestiary_4::spell_list::SPELL_LIST))));
        out.push(("bestiary_5/companion_data/COMPANIONS", json_of(rows_of(&$r::bestiary_5::companion_data::COMPANIONS))));
        out.push(("bestiary_5/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::bestiary_5::companion_data::COMPANION_ABILITIES))));
        out.push(("bestiary_5/monster_data/MONSTERS", json_of(rows_of(&$r::bestiary_5::monster_data::MONSTERS))));
        out.push(("bestiary_5/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::bestiary_5::monster_data::MONSTER_ABILITIES))));
        out.push(("bestiary_6/companion_data/COMPANIONS", json_of(rows_of(&$r::bestiary_6::companion_data::COMPANIONS))));
        out.push(("bestiary_6/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::bestiary_6::companion_data::COMPANION_ABILITIES))));
        out.push(("bestiary_6/monster_data/MONSTERS", json_of(rows_of(&$r::bestiary_6::monster_data::MONSTERS))));
        out.push(("bestiary_6/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::bestiary_6::monster_data::MONSTER_ABILITIES))));
        out.push(("bestiary_6/spell_list/SPELL_LIST", json_of(rows_of(&$r::bestiary_6::spell_list::SPELL_LIST))));
        out.push(("bonus_bestiary/monster_data/MONSTERS", json_of(rows_of(&$r::bonus_bestiary::monster_data::MONSTERS))));
        out.push(("bonus_bestiary/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::bonus_bestiary::monster_data::MONSTER_ABILITIES))));
        out.push(("book_of_the_damned_volume_1/companion_data/COMPANIONS", json_of(rows_of(&$r::book_of_the_damned_volume_1::companion_data::COMPANIONS))));
        out.push(("book_of_the_damned_volume_1/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::book_of_the_damned_volume_1::companion_data::COMPANION_ABILITIES))));
        out.push(("book_of_the_damned_volume_1/companion_data/COMPANION_CLASSES", json_of(rows_of(&$r::book_of_the_damned_volume_1::companion_data::COMPANION_CLASSES))));
        out.push(("book_of_the_damned_volume_1/monster_data/MONSTERS", json_of(rows_of(&$r::book_of_the_damned_volume_1::monster_data::MONSTERS))));
        out.push(("book_of_the_damned_volume_1/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::book_of_the_damned_volume_1::monster_data::MONSTER_ABILITIES))));
        out.push(("book_of_the_damned_volume_1/spell_list/SPELL_LIST", json_of(rows_of(&$r::book_of_the_damned_volume_1::spell_list::SPELL_LIST))));
        out.push(("book_of_the_damned_volume_2/monster_data/MONSTERS", json_of(rows_of(&$r::book_of_the_damned_volume_2::monster_data::MONSTERS))));
        out.push(("book_of_the_damned_volume_2/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::book_of_the_damned_volume_2::monster_data::MONSTER_ABILITIES))));
        out.push(("book_of_the_damned_volume_2/spell_list/SPELL_LIST", json_of(rows_of(&$r::book_of_the_damned_volume_2::spell_list::SPELL_LIST))));
        out.push(("companion_chassis/GRANT_TOKEN_ONLY_DISPATCH_ROWS", json_of(rows_of(&$r::companion_chassis::GRANT_TOKEN_ONLY_DISPATCH_ROWS))));
        out.push(("crb/bard_spell_list/BARD_SPELL_LIST", json_of(rows_of(&$r::crb::bard_spell_list::BARD_SPELL_LIST))));
        out.push(("crb/class_skill_tables/CLASS_SKILL_LISTS", json_of(rows_of(&$r::crb::class_skill_tables::CLASS_SKILL_LISTS))));
        out.push(("crb/class_tables/CLASS_META", json_of(rows_of(&$r::crb::class_tables::CLASS_META))));
        out.push(("crb/cleric_spell_list/CLERIC_SPELL_LIST", json_of(rows_of(&$r::crb::cleric_spell_list::CLERIC_SPELL_LIST))));
        out.push(("crb/companion_data/COMPANIONS", json_of(rows_of(&$r::crb::companion_data::COMPANIONS))));
        out.push(("crb/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::crb::companion_data::COMPANION_ABILITIES))));
        out.push(("crb/companion_data/COMPANION_CLASSES", json_of(rows_of(&$r::crb::companion_data::COMPANION_CLASSES))));
        out.push(("crb/druid_spell_list/DRUID_SPELL_LIST", json_of(rows_of(&$r::crb::druid_spell_list::DRUID_SPELL_LIST))));
        out.push(("crb/equipment_data/arms_armor/ARMS_ARMOR_TABLE", json_of(rows_of(&$r::crb::equipment_data::arms_armor::ARMS_ARMOR_TABLE))));
        out.push(("crb/equipment_data/equipmods/EQUIPMODS_TABLE", json_of(rows_of(&$r::crb::equipment_data::equipmods::EQUIPMODS_TABLE))));
        out.push(("crb/equipment_data/general/GENERAL_TABLE", json_of(rows_of(&$r::crb::equipment_data::general::GENERAL_TABLE))));
        out.push(("crb/equipment_data/magic_items/MAGIC_ITEMS_TABLE", json_of(rows_of(&$r::crb::equipment_data::magic_items::MAGIC_ITEMS_TABLE))));
        out.push(("crb/feat_data/combat/COMBAT_TABLE", json_of(rows_of(&$r::crb::feat_data::combat::COMBAT_TABLE))));
        out.push(("crb/feat_data/general/GENERAL_TABLE", json_of(rows_of(&$r::crb::feat_data::general::GENERAL_TABLE))));
        out.push(("crb/feat_data/item_creation/ITEM_CREATION_TABLE", json_of(rows_of(&$r::crb::feat_data::item_creation::ITEM_CREATION_TABLE))));
        out.push(("crb/feat_data/metamagic/METAMAGIC_TABLE", json_of(rows_of(&$r::crb::feat_data::metamagic::METAMAGIC_TABLE))));
        out.push(("crb/paladin_spell_list/PALADIN_SPELL_LIST", json_of(rows_of(&$r::crb::paladin_spell_list::PALADIN_SPELL_LIST))));
        out.push(("crb/race_tables/RACE_TRAITS", json_of(rows_of(&$r::crb::race_tables::RACE_TRAITS))));
        out.push(("crb/ranger_spell_list/RANGER_SPELL_LIST", json_of(rows_of(&$r::crb::ranger_spell_list::RANGER_SPELL_LIST))));
        out.push(("crb/sorcerer_spell_list/SORCERER_SPELL_LIST", json_of(rows_of(&$r::crb::sorcerer_spell_list::SORCERER_SPELL_LIST))));
        out.push(("crb/spell_list/SPELL_LIST", json_of(rows_of(&$r::crb::spell_list::SPELL_LIST))));
        out.push(("crb/weapon_tables/WEAPON_TABLE", json_of(rows_of(&$r::crb::weapon_tables::WEAPON_TABLE))));
        out.push(("crb/weapon_tables/FINESSEABLE_WEAPON_KEYS", json_of(rows_of(&$r::crb::weapon_tables::FINESSEABLE_WEAPON_KEYS))));
        out.push(("crb/weapon_tables/CLASS_WEAPON_PROFICIENCIES", json_of(rows_of(&$r::crb::weapon_tables::CLASS_WEAPON_PROFICIENCIES))));
        out.push(("crb/weapon_tables/CLASS_ARMOR_PROFICIENCIES", json_of(rows_of(&$r::crb::weapon_tables::CLASS_ARMOR_PROFICIENCIES))));
        out.push(("crb/wizard_spell_list/WIZARD_SPELL_LIST", json_of(rows_of(&$r::crb::wizard_spell_list::WIZARD_SPELL_LIST))));
        out.push(("equipment_gap_tables/CORE_RULEBOOK_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::CORE_RULEBOOK_GAP_ROWS))));
        out.push(("equipment_gap_tables/BESTIARY_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::BESTIARY_GAP_ROWS))));
        out.push(("equipment_gap_tables/ADVANCED_PLAYERS_GUIDE_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::ADVANCED_PLAYERS_GUIDE_GAP_ROWS))));
        out.push(("equipment_gap_tables/ADVANCED_CLASS_GUIDE_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::ADVANCED_CLASS_GUIDE_GAP_ROWS))));
        out.push(("equipment_gap_tables/ADVANCED_RACE_GUIDE_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::ADVANCED_RACE_GUIDE_GAP_ROWS))));
        out.push(("equipment_gap_tables/ULTIMATE_COMBAT_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::ULTIMATE_COMBAT_GAP_ROWS))));
        out.push(("equipment_gap_tables/ULTIMATE_INTRIGUE_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::ULTIMATE_INTRIGUE_GAP_ROWS))));
        out.push(("equipment_gap_tables/ULTIMATE_EQUIPMENT_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::ULTIMATE_EQUIPMENT_GAP_ROWS))));
        out.push(("equipment_gap_tables/ULTIMATE_PSIONICS_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::ULTIMATE_PSIONICS_GAP_ROWS))));
        out.push(("equipment_gap_tables/ULTIMATE_WILDERNESS_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::ULTIMATE_WILDERNESS_GAP_ROWS))));
        out.push(("equipment_gap_tables/OCCULT_ADVENTURES_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::OCCULT_ADVENTURES_GAP_ROWS))));
        out.push(("equipment_gap_tables/HORROR_ADVENTURES_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::HORROR_ADVENTURES_GAP_ROWS))));
        out.push(("equipment_gap_tables/INNER_SEA_RACES_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::INNER_SEA_RACES_GAP_ROWS))));
        out.push(("equipment_gap_tables/INNER_SEA_WORLD_GUIDE_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::INNER_SEA_WORLD_GUIDE_GAP_ROWS))));
        out.push(("equipment_gap_tables/MONSTER_CODEX_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::MONSTER_CODEX_GAP_ROWS))));
        out.push(("equipment_gap_tables/BESTIARY_2_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::BESTIARY_2_GAP_ROWS))));
        out.push(("equipment_gap_tables/BESTIARY_3_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::BESTIARY_3_GAP_ROWS))));
        out.push(("equipment_gap_tables/BESTIARY_4_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::BESTIARY_4_GAP_ROWS))));
        out.push(("equipment_gap_tables/INNER_SEA_GODS_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::INNER_SEA_GODS_GAP_ROWS))));
        out.push(("equipment_gap_tables/MYTHIC_ADVENTURES_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::MYTHIC_ADVENTURES_GAP_ROWS))));
        out.push(("equipment_gap_tables/INNER_SEA_COMBAT_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::INNER_SEA_COMBAT_GAP_ROWS))));
        out.push(("equipment_gap_tables/INNER_SEA_INTRIGUE_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::INNER_SEA_INTRIGUE_GAP_ROWS))));
        out.push(("equipment_gap_tables/BOOK_OF_THE_DAMNED_VOLUME_2_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::BOOK_OF_THE_DAMNED_VOLUME_2_GAP_ROWS))));
        out.push(("equipment_gap_tables/INNER_SEA_TEMPLES_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::INNER_SEA_TEMPLES_GAP_ROWS))));
        out.push(("equipment_gap_tables/INNER_SEA_MAGIC_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::INNER_SEA_MAGIC_GAP_ROWS))));
        out.push(("equipment_gap_tables/ADVENTURERS_GUIDE_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::ADVENTURERS_GUIDE_GAP_ROWS))));
        out.push(("equipment_gap_tables/ULTIMATE_MAGIC_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::ULTIMATE_MAGIC_GAP_ROWS))));
        out.push(("equipment_gap_tables/BEGINNER_BOX_GAP_ROWS", json_of(rows_of(&$r::equipment_gap_tables::BEGINNER_BOX_GAP_ROWS))));
        out.push(("feat_gap_tables/CORE_RULEBOOK_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::CORE_RULEBOOK_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/CORE_ESSENTIALS_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::CORE_ESSENTIALS_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/ADVANCED_RACE_GUIDE_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::ADVANCED_RACE_GUIDE_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/ULTIMATE_COMBAT_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::ULTIMATE_COMBAT_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/ULTIMATE_INTRIGUE_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::ULTIMATE_INTRIGUE_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/ULTIMATE_MAGIC_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::ULTIMATE_MAGIC_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/ULTIMATE_PSIONICS_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::ULTIMATE_PSIONICS_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/ULTIMATE_WILDERNESS_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::ULTIMATE_WILDERNESS_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/HORROR_ADVENTURES_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::HORROR_ADVENTURES_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/INNER_SEA_RACES_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::INNER_SEA_RACES_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/OCCULT_ADVENTURES_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::OCCULT_ADVENTURES_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/INNER_SEA_WORLD_GUIDE_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::INNER_SEA_WORLD_GUIDE_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/MONSTER_CODEX_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::MONSTER_CODEX_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/MYTHIC_ADVENTURES_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::MYTHIC_ADVENTURES_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/INNER_SEA_INTRIGUE_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::INNER_SEA_INTRIGUE_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/BOOK_OF_THE_DAMNED_VOLUME_2_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::BOOK_OF_THE_DAMNED_VOLUME_2_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/INNER_SEA_TAVERNS_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::INNER_SEA_TAVERNS_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/INNER_SEA_COMBAT_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::INNER_SEA_COMBAT_FEAT_GAP_ROWS))));
        out.push(("feat_gap_tables/INNER_SEA_GODS_FEAT_GAP_ROWS", json_of(rows_of(&$r::feat_gap_tables::INNER_SEA_GODS_FEAT_GAP_ROWS))));
        out.push(("horror_adventures/companion_data/COMPANIONS", json_of(rows_of(&$r::horror_adventures::companion_data::COMPANIONS))));
        out.push(("horror_adventures/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::horror_adventures::companion_data::COMPANION_ABILITIES))));
        out.push(("horror_adventures/monster_data/MONSTERS", json_of(rows_of(&$r::horror_adventures::monster_data::MONSTERS))));
        out.push(("horror_adventures/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::horror_adventures::monster_data::MONSTER_ABILITIES))));
        out.push(("horror_adventures/spell_list/SPELL_LIST", json_of(rows_of(&$r::horror_adventures::spell_list::SPELL_LIST))));
        out.push(("inner_sea_bestiary/monster_data/MONSTERS", json_of(rows_of(&$r::inner_sea_bestiary::monster_data::MONSTERS))));
        out.push(("inner_sea_bestiary/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::inner_sea_bestiary::monster_data::MONSTER_ABILITIES))));
        out.push(("inner_sea_combat/companion_data/COMPANIONS", json_of(rows_of(&$r::inner_sea_combat::companion_data::COMPANIONS))));
        out.push(("inner_sea_combat/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::inner_sea_combat::companion_data::COMPANION_ABILITIES))));
        out.push(("inner_sea_faiths/spell_list/SPELL_LIST", json_of(rows_of(&$r::inner_sea_faiths::spell_list::SPELL_LIST))));
        out.push(("inner_sea_gods/monster_data/MONSTERS", json_of(rows_of(&$r::inner_sea_gods::monster_data::MONSTERS))));
        out.push(("inner_sea_gods/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::inner_sea_gods::monster_data::MONSTER_ABILITIES))));
        out.push(("inner_sea_gods/spell_list/SPELL_LIST", json_of(rows_of(&$r::inner_sea_gods::spell_list::SPELL_LIST))));
        out.push(("inner_sea_intrigue/companion_data/COMPANIONS", json_of(rows_of(&$r::inner_sea_intrigue::companion_data::COMPANIONS))));
        out.push(("inner_sea_intrigue/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::inner_sea_intrigue::companion_data::COMPANION_ABILITIES))));
        out.push(("inner_sea_intrigue/spell_list/SPELL_LIST", json_of(rows_of(&$r::inner_sea_intrigue::spell_list::SPELL_LIST))));
        out.push(("inner_sea_magic/spell_list/SPELL_LIST", json_of(rows_of(&$r::inner_sea_magic::spell_list::SPELL_LIST))));
        out.push(("inner_sea_races/spell_list/SPELL_LIST", json_of(rows_of(&$r::inner_sea_races::spell_list::SPELL_LIST))));
        out.push(("inner_sea_temples/spell_list/SPELL_LIST", json_of(rows_of(&$r::inner_sea_temples::spell_list::SPELL_LIST))));
        out.push(("inner_sea_world_guide/monster_data/MONSTERS", json_of(rows_of(&$r::inner_sea_world_guide::monster_data::MONSTERS))));
        out.push(("inner_sea_world_guide/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::inner_sea_world_guide::monster_data::MONSTER_ABILITIES))));
        out.push(("inner_sea_world_guide/spell_list/SPELL_LIST", json_of(rows_of(&$r::inner_sea_world_guide::spell_list::SPELL_LIST))));
        out.push(("monster_codex/companion_data/COMPANIONS", json_of(rows_of(&$r::monster_codex::companion_data::COMPANIONS))));
        out.push(("monster_codex/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::monster_codex::companion_data::COMPANION_ABILITIES))));
        out.push(("monster_codex/monster_data/MONSTERS", json_of(rows_of(&$r::monster_codex::monster_data::MONSTERS))));
        out.push(("monster_codex/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::monster_codex::monster_data::MONSTER_ABILITIES))));
        out.push(("monster_codex/spell_list/SPELL_LIST", json_of(rows_of(&$r::monster_codex::spell_list::SPELL_LIST))));
        out.push(("mythic_adventures/monster_data/MONSTERS", json_of(rows_of(&$r::mythic_adventures::monster_data::MONSTERS))));
        out.push(("mythic_adventures/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::mythic_adventures::monster_data::MONSTER_ABILITIES))));
        out.push(("mythic_adventures/spell_list/SPELL_LIST", json_of(rows_of(&$r::mythic_adventures::spell_list::SPELL_LIST))));
        out.push(("occult_adventures/monster_data/MONSTERS", json_of(rows_of(&$r::occult_adventures::monster_data::MONSTERS))));
        out.push(("occult_adventures/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::occult_adventures::monster_data::MONSTER_ABILITIES))));
        out.push(("occult_adventures/spell_list/SPELL_LIST", json_of(rows_of(&$r::occult_adventures::spell_list::SPELL_LIST))));
        out.push(("pathfinder_unchained/barbarian_features/FEATURES", json_of(rows_of(&$r::pathfinder_unchained::barbarian_features::FEATURES))));
        out.push(("pathfinder_unchained/monk_features/FEATURES", json_of(rows_of(&$r::pathfinder_unchained::monk_features::FEATURES))));
        out.push(("pathfinder_unchained/monster_data/MONSTERS", json_of(rows_of(&$r::pathfinder_unchained::monster_data::MONSTERS))));
        out.push(("pathfinder_unchained/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::pathfinder_unchained::monster_data::MONSTER_ABILITIES))));
        out.push(("pathfinder_unchained/summoner_features/EIDOLON_EVOLUTION_THRESHOLDS", json_of(rows_of(&$r::pathfinder_unchained::summoner_features::EIDOLON_EVOLUTION_THRESHOLDS))));
        out.push(("simple_kind_tables/SEVEN_KIND_DIRS", json_of(rows_of(&$r::simple_kind_tables::SEVEN_KIND_DIRS))));
        out.push(("ultimate_campaign/feat_tables/DEFERRED_WITH_REASON", json_of(rows_of(&$r::ultimate_campaign::feat_tables::DEFERRED_WITH_REASON))));
        out.push(("ultimate_combat/equipment_tables/GENERAL_TABLE", json_of(rows_of(&$r::ultimate_combat::equipment_tables::GENERAL_TABLE))));
        out.push(("ultimate_combat/equipment_tables/MAGIC_ITEMS_TABLE", json_of(rows_of(&$r::ultimate_combat::equipment_tables::MAGIC_ITEMS_TABLE))));
        out.push(("ultimate_combat/equipment_tables/ARMS_ARMOR_TABLE", json_of(rows_of(&$r::ultimate_combat::equipment_tables::ARMS_ARMOR_TABLE))));
        out.push(("ultimate_combat/equipment_tables/EQUIPMODS_TABLE", json_of(rows_of(&$r::ultimate_combat::equipment_tables::EQUIPMODS_TABLE))));
        out.push(("ultimate_combat/spell_list/SPELL_LIST", json_of(rows_of(&$r::ultimate_combat::spell_list::SPELL_LIST))));
        out.push(("ultimate_equipment/spell_list/SPELL_LIST", json_of(rows_of(&$r::ultimate_equipment::spell_list::SPELL_LIST))));
        out.push(("ultimate_intrigue/monster_data/MONSTERS", json_of(rows_of(&$r::ultimate_intrigue::monster_data::MONSTERS))));
        out.push(("ultimate_intrigue/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::ultimate_intrigue::monster_data::MONSTER_ABILITIES))));
        out.push(("ultimate_intrigue/spell_list/SPELL_LIST", json_of(rows_of(&$r::ultimate_intrigue::spell_list::SPELL_LIST))));
        out.push(("ultimate_magic/companion_data/COMPANIONS", json_of(rows_of(&$r::ultimate_magic::companion_data::COMPANIONS))));
        out.push(("ultimate_magic/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::ultimate_magic::companion_data::COMPANION_ABILITIES))));
        out.push(("ultimate_magic/companion_data/COMPANION_CLASSES", json_of(rows_of(&$r::ultimate_magic::companion_data::COMPANION_CLASSES))));
        out.push(("ultimate_magic/equipment_tables/GENERAL_TABLE", json_of(rows_of(&$r::ultimate_magic::equipment_tables::GENERAL_TABLE))));
        out.push(("ultimate_magic/equipment_tables/ARMS_ARMOR_TABLE", json_of(rows_of(&$r::ultimate_magic::equipment_tables::ARMS_ARMOR_TABLE))));
        out.push(("ultimate_magic/monster_data/MONSTERS", json_of(rows_of(&$r::ultimate_magic::monster_data::MONSTERS))));
        out.push(("ultimate_magic/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::ultimate_magic::monster_data::MONSTER_ABILITIES))));
        out.push(("ultimate_magic/spell_list/SPELL_LIST", json_of(rows_of(&$r::ultimate_magic::spell_list::SPELL_LIST))));
        out.push(("ultimate_magic_wordsofpower/spell_list/SPELL_LIST", json_of(rows_of(&$r::ultimate_magic_wordsofpower::spell_list::SPELL_LIST))));
        out.push(("ultimate_psionics/equipment_tables/EQUIPMENT_TABLE", json_of(rows_of(&$r::ultimate_psionics::equipment_tables::EQUIPMENT_TABLE))));
        out.push(("ultimate_psionics/equipment_tables/EQUIPMODS_TABLE", json_of(rows_of(&$r::ultimate_psionics::equipment_tables::EQUIPMODS_TABLE))));
        out.push(("ultimate_psionics/equipment_tables/EXCLUDED_LEGACY_ALIAS_SHORT_CODES", json_of(rows_of(&$r::ultimate_psionics::equipment_tables::EXCLUDED_LEGACY_ALIAS_SHORT_CODES))));
        out.push(("ultimate_psionics/monster_data/MONSTERS", json_of(rows_of(&$r::ultimate_psionics::monster_data::MONSTERS))));
        out.push(("ultimate_psionics/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::ultimate_psionics::monster_data::MONSTER_ABILITIES))));
        out.push(("ultimate_wilderness/companion_data/COMPANIONS", json_of(rows_of(&$r::ultimate_wilderness::companion_data::COMPANIONS))));
        out.push(("ultimate_wilderness/companion_data/COMPANION_ABILITIES", json_of(rows_of(&$r::ultimate_wilderness::companion_data::COMPANION_ABILITIES))));
        out.push(("ultimate_wilderness/monster_data/MONSTERS", json_of(rows_of(&$r::ultimate_wilderness::monster_data::MONSTERS))));
        out.push(("ultimate_wilderness/monster_data/MONSTER_ABILITIES", json_of(rows_of(&$r::ultimate_wilderness::monster_data::MONSTER_ABILITIES))));
        out.push(("ultimate_wilderness/spell_list/SPELL_LIST", json_of(rows_of(&$r::ultimate_wilderness::spell_list::SPELL_LIST))));
        out.push(("acg/coverage_report", debug_of(&$r::acg::coverage_report())));
        out.push(("acg/archetype_tables/archetype_swap_tables", json_of(&$r::acg::archetype_tables::archetype_swap_tables())));
        out.push(("acg/class_arcanist/class_table", json_of(&$r::acg::class_arcanist::class_table())));
        out.push(("acg/class_bloodrager/class_table", json_of(&$r::acg::class_bloodrager::class_table())));
        out.push(("acg/class_brawler/class_table", json_of(&$r::acg::class_brawler::class_table())));
        out.push(("acg/class_hunter/class_table", json_of(&$r::acg::class_hunter::class_table())));
        out.push(("acg/class_investigator/class_table", json_of(&$r::acg::class_investigator::class_table())));
        out.push(("acg/class_shaman/class_table", json_of(&$r::acg::class_shaman::class_table())));
        out.push(("acg/class_skald/class_table", json_of(&$r::acg::class_skald::class_table())));
        out.push(("acg/class_slayer/class_table", json_of(&$r::acg::class_slayer::class_table())));
        out.push(("acg/class_swashbuckler/class_table", json_of(&$r::acg::class_swashbuckler::class_table())));
        out.push(("acg/class_warpriest/class_table", json_of(&$r::acg::class_warpriest::class_table())));
        out.push(("acg/equipment_tables/equipment_tables", json_of(&$r::acg::equipment_tables::equipment_tables())));
        out.push(("acg/feats/feat_tables", json_of(&$r::acg::feats::feat_tables())));
        out.push(("advanced_race_guide/companions_static", json_of(&$r::advanced_race_guide::companions_static())));
        out.push(("advanced_race_guide/companion_abilities_static", json_of(&$r::advanced_race_guide::companion_abilities_static())));
        out.push(("advanced_race_guide/companions", json_of(&$r::advanced_race_guide::companions())));
        out.push(("advanced_race_guide/companion_abilities", json_of(&$r::advanced_race_guide::companion_abilities())));
        out.push(("advanced_race_guide/monsters_static", json_of(&$r::advanced_race_guide::monsters_static())));
        out.push(("advanced_race_guide/monster_abilities_static", json_of(&$r::advanced_race_guide::monster_abilities_static())));
        out.push(("advanced_race_guide/archetype_tables/archetype_swap_tables", json_of(&$r::advanced_race_guide::archetype_tables::archetype_swap_tables())));
        out.push(("advanced_race_guide/equipment_tables/equipment_tables", json_of(&$r::advanced_race_guide::equipment_tables::equipment_tables())));
        out.push(("advanced_race_guide/feats/feat_tables", json_of(&$r::advanced_race_guide::feats::feat_tables())));
        out.push(("apg/companions_static", json_of(&$r::apg::companions_static())));
        out.push(("apg/companion_abilities_static", json_of(&$r::apg::companion_abilities_static())));
        out.push(("apg/companions", json_of(&$r::apg::companions())));
        out.push(("apg/companion_abilities", json_of(&$r::apg::companion_abilities())));
        out.push(("apg/coverage_report", debug_of(&$r::apg::coverage_report())));
        out.push(("apg/archetype_tables/archetype_swap_tables", json_of(&$r::apg::archetype_tables::archetype_swap_tables())));
        out.push(("apg/class_alchemist/class_table", json_of(&$r::apg::class_alchemist::class_table())));
        out.push(("apg/class_cavalier/class_table", json_of(&$r::apg::class_cavalier::class_table())));
        out.push(("apg/class_inquisitor/class_table", json_of(&$r::apg::class_inquisitor::class_table())));
        out.push(("apg/class_oracle/class_table", json_of(&$r::apg::class_oracle::class_table())));
        out.push(("apg/class_summoner/class_table", json_of(&$r::apg::class_summoner::class_table())));
        out.push(("apg/class_witch/class_table", json_of(&$r::apg::class_witch::class_table())));
        out.push(("apg/feats/feat_tables", json_of(&$r::apg::feats::feat_tables())));
        out.push(("beastiary1/companions_static", json_of(&$r::beastiary1::companions_static())));
        out.push(("beastiary1/companion_abilities_static", json_of(&$r::beastiary1::companion_abilities_static())));
        out.push(("beastiary1/companions", json_of(&$r::beastiary1::companions())));
        out.push(("beastiary1/companion_abilities", json_of(&$r::beastiary1::companion_abilities())));
        out.push(("bestiary/monsters_static", json_of(&$r::bestiary::monsters_static())));
        out.push(("bestiary/monster_abilities_static", json_of(&$r::bestiary::monster_abilities_static())));
        out.push(("bestiary/monsters", json_of(&$r::bestiary::monsters())));
        out.push(("bestiary/monster_abilities", json_of(&$r::bestiary::monster_abilities())));
        out.push(("bestiary/cross_table_owner_names", json_of(&$r::bestiary::cross_table_owner_names())));
        out.push(("bestiary_2/companions_static", json_of(&$r::bestiary_2::companions_static())));
        out.push(("bestiary_2/companion_abilities_static", json_of(&$r::bestiary_2::companion_abilities_static())));
        out.push(("bestiary_2/companions", json_of(&$r::bestiary_2::companions())));
        out.push(("bestiary_2/companion_abilities", json_of(&$r::bestiary_2::companion_abilities())));
        out.push(("bestiary_2/monsters_static", json_of(&$r::bestiary_2::monsters_static())));
        out.push(("bestiary_2/monster_abilities_static", json_of(&$r::bestiary_2::monster_abilities_static())));
        out.push(("bestiary_2/monsters", json_of(&$r::bestiary_2::monsters())));
        out.push(("bestiary_2/monster_abilities", json_of(&$r::bestiary_2::monster_abilities())));
        out.push(("bestiary_3/monsters_static", json_of(&$r::bestiary_3::monsters_static())));
        out.push(("bestiary_3/monster_abilities_static", json_of(&$r::bestiary_3::monster_abilities_static())));
        out.push(("bestiary_3/monsters", json_of(&$r::bestiary_3::monsters())));
        out.push(("bestiary_3/monster_abilities", json_of(&$r::bestiary_3::monster_abilities())));
        out.push(("bestiary_3/companions_static", json_of(&$r::bestiary_3::companions_static())));
        out.push(("bestiary_3/companion_abilities_static", json_of(&$r::bestiary_3::companion_abilities_static())));
        out.push(("bestiary_3/companions", json_of(&$r::bestiary_3::companions())));
        out.push(("bestiary_3/companion_abilities", json_of(&$r::bestiary_3::companion_abilities())));
        out.push(("bestiary_4/monsters_static", json_of(&$r::bestiary_4::monsters_static())));
        out.push(("bestiary_4/monster_abilities_static", json_of(&$r::bestiary_4::monster_abilities_static())));
        out.push(("bestiary_4/monsters", json_of(&$r::bestiary_4::monsters())));
        out.push(("bestiary_4/monster_abilities", json_of(&$r::bestiary_4::monster_abilities())));
        out.push(("bestiary_4/companions_static", json_of(&$r::bestiary_4::companions_static())));
        out.push(("bestiary_4/companion_abilities_static", json_of(&$r::bestiary_4::companion_abilities_static())));
        out.push(("bestiary_4/companions", json_of(&$r::bestiary_4::companions())));
        out.push(("bestiary_4/companion_abilities", json_of(&$r::bestiary_4::companion_abilities())));
        out.push(("bestiary_5/companions_static", json_of(&$r::bestiary_5::companions_static())));
        out.push(("bestiary_5/companion_abilities_static", json_of(&$r::bestiary_5::companion_abilities_static())));
        out.push(("bestiary_5/companions", json_of(&$r::bestiary_5::companions())));
        out.push(("bestiary_5/companion_abilities", json_of(&$r::bestiary_5::companion_abilities())));
        out.push(("bestiary_5/monsters_static", json_of(&$r::bestiary_5::monsters_static())));
        out.push(("bestiary_5/monster_abilities_static", json_of(&$r::bestiary_5::monster_abilities_static())));
        out.push(("bestiary_6/companions_static", json_of(&$r::bestiary_6::companions_static())));
        out.push(("bestiary_6/companion_abilities_static", json_of(&$r::bestiary_6::companion_abilities_static())));
        out.push(("bestiary_6/companions", json_of(&$r::bestiary_6::companions())));
        out.push(("bestiary_6/companion_abilities", json_of(&$r::bestiary_6::companion_abilities())));
        out.push(("bestiary_6/monsters_static", json_of(&$r::bestiary_6::monsters_static())));
        out.push(("bestiary_6/monster_abilities_static", json_of(&$r::bestiary_6::monster_abilities_static())));
        out.push(("bonus_bestiary/monsters_static", json_of(&$r::bonus_bestiary::monsters_static())));
        out.push(("bonus_bestiary/monster_abilities_static", json_of(&$r::bonus_bestiary::monster_abilities_static())));
        out.push(("bonus_bestiary/monsters", json_of(&$r::bonus_bestiary::monsters())));
        out.push(("bonus_bestiary/monster_abilities", json_of(&$r::bonus_bestiary::monster_abilities())));
        out.push(("book_of_the_damned_volume_1/companions_static", json_of(&$r::book_of_the_damned_volume_1::companions_static())));
        out.push(("book_of_the_damned_volume_1/companion_abilities_static", json_of(&$r::book_of_the_damned_volume_1::companion_abilities_static())));
        out.push(("book_of_the_damned_volume_1/companion_classes_static", json_of(&$r::book_of_the_damned_volume_1::companion_classes_static())));
        out.push(("book_of_the_damned_volume_1/companions", json_of(&$r::book_of_the_damned_volume_1::companions())));
        out.push(("book_of_the_damned_volume_1/companion_abilities", json_of(&$r::book_of_the_damned_volume_1::companion_abilities())));
        out.push(("book_of_the_damned_volume_1/monsters_static", json_of(&$r::book_of_the_damned_volume_1::monsters_static())));
        out.push(("book_of_the_damned_volume_1/monster_abilities_static", json_of(&$r::book_of_the_damned_volume_1::monster_abilities_static())));
        out.push(("book_of_the_damned_volume_1/monsters", json_of(&$r::book_of_the_damned_volume_1::monsters())));
        out.push(("book_of_the_damned_volume_1/monster_abilities", json_of(&$r::book_of_the_damned_volume_1::monster_abilities())));
        out.push(("book_of_the_damned_volume_2/monsters_static", json_of(&$r::book_of_the_damned_volume_2::monsters_static())));
        out.push(("book_of_the_damned_volume_2/monster_abilities_static", json_of(&$r::book_of_the_damned_volume_2::monster_abilities_static())));
        out.push(("book_of_the_damned_volume_2/monsters", json_of(&$r::book_of_the_damned_volume_2::monsters())));
        out.push(("book_of_the_damned_volume_2/monster_abilities", json_of(&$r::book_of_the_damned_volume_2::monster_abilities())));
        out.push(("class_spell_levels/classes_with_spell_lists", json_of(&$r::class_spell_levels::classes_with_spell_lists())));
        out.push(("crb/companions_static", json_of(&$r::crb::companions_static())));
        out.push(("crb/companion_abilities_static", json_of(&$r::crb::companion_abilities_static())));
        out.push(("crb/companion_classes_static", json_of(&$r::crb::companion_classes_static())));
        out.push(("crb/companions", json_of(&$r::crb::companions())));
        out.push(("crb/companion_abilities", json_of(&$r::crb::companion_abilities())));
        out.push(("crb/class_tables/class_tables", json_of(&$r::crb::class_tables::class_tables())));
        out.push(("crb/equipment_tables/equipment_tables", json_of(&$r::crb::equipment_tables::equipment_tables())));
        out.push(("crb/feats/feat_tables", json_of(&$r::crb::feats::feat_tables())));
        out.push(("crb/race_tables/race_traits", json_of(&$r::crb::race_tables::race_traits())));
        out.push(("feats_all/hand_authored_feat_tables", debug_of(&$r::feats_all::hand_authored_feat_tables())));
        out.push(("feats_all/all_feat_tables", debug_of(&$r::feats_all::all_feat_tables())));
        out.push(("horror_adventures/companions_static", json_of(&$r::horror_adventures::companions_static())));
        out.push(("horror_adventures/companion_abilities_static", json_of(&$r::horror_adventures::companion_abilities_static())));
        out.push(("horror_adventures/companions", json_of(&$r::horror_adventures::companions())));
        out.push(("horror_adventures/companion_abilities", json_of(&$r::horror_adventures::companion_abilities())));
        out.push(("horror_adventures/monsters_static", json_of(&$r::horror_adventures::monsters_static())));
        out.push(("horror_adventures/monster_abilities_static", json_of(&$r::horror_adventures::monster_abilities_static())));
        out.push(("horror_adventures/monsters", json_of(&$r::horror_adventures::monsters())));
        out.push(("horror_adventures/monster_abilities", json_of(&$r::horror_adventures::monster_abilities())));
        out.push(("inner_sea_bestiary/monsters_static", json_of(&$r::inner_sea_bestiary::monsters_static())));
        out.push(("inner_sea_bestiary/monster_abilities_static", json_of(&$r::inner_sea_bestiary::monster_abilities_static())));
        out.push(("inner_sea_bestiary/monsters", json_of(&$r::inner_sea_bestiary::monsters())));
        out.push(("inner_sea_bestiary/monster_abilities", json_of(&$r::inner_sea_bestiary::monster_abilities())));
        out.push(("inner_sea_combat/companions_static", json_of(&$r::inner_sea_combat::companions_static())));
        out.push(("inner_sea_combat/companion_abilities_static", json_of(&$r::inner_sea_combat::companion_abilities_static())));
        out.push(("inner_sea_combat/companions", json_of(&$r::inner_sea_combat::companions())));
        out.push(("inner_sea_combat/companion_abilities", json_of(&$r::inner_sea_combat::companion_abilities())));
        out.push(("inner_sea_gods/monsters_static", json_of(&$r::inner_sea_gods::monsters_static())));
        out.push(("inner_sea_gods/monster_abilities_static", json_of(&$r::inner_sea_gods::monster_abilities_static())));
        out.push(("inner_sea_gods/monsters", json_of(&$r::inner_sea_gods::monsters())));
        out.push(("inner_sea_gods/monster_abilities", json_of(&$r::inner_sea_gods::monster_abilities())));
        out.push(("inner_sea_intrigue/companions_static", json_of(&$r::inner_sea_intrigue::companions_static())));
        out.push(("inner_sea_intrigue/companion_abilities_static", json_of(&$r::inner_sea_intrigue::companion_abilities_static())));
        out.push(("inner_sea_intrigue/companions", json_of(&$r::inner_sea_intrigue::companions())));
        out.push(("inner_sea_intrigue/companion_abilities", json_of(&$r::inner_sea_intrigue::companion_abilities())));
        out.push(("inner_sea_world_guide/monsters_static", json_of(&$r::inner_sea_world_guide::monsters_static())));
        out.push(("inner_sea_world_guide/monster_abilities_static", json_of(&$r::inner_sea_world_guide::monster_abilities_static())));
        out.push(("inner_sea_world_guide/monsters", json_of(&$r::inner_sea_world_guide::monsters())));
        out.push(("inner_sea_world_guide/monster_abilities", json_of(&$r::inner_sea_world_guide::monster_abilities())));
        out.push(("monster_codex/companions_static", json_of(&$r::monster_codex::companions_static())));
        out.push(("monster_codex/companion_abilities_static", json_of(&$r::monster_codex::companion_abilities_static())));
        out.push(("monster_codex/companions", json_of(&$r::monster_codex::companions())));
        out.push(("monster_codex/companion_abilities", json_of(&$r::monster_codex::companion_abilities())));
        out.push(("monster_codex/monsters_static", json_of(&$r::monster_codex::monsters_static())));
        out.push(("monster_codex/monster_abilities_static", json_of(&$r::monster_codex::monster_abilities_static())));
        out.push(("monster_codex/monsters", json_of(&$r::monster_codex::monsters())));
        out.push(("monster_codex/monster_abilities", json_of(&$r::monster_codex::monster_abilities())));
        out.push(("mythic_adventures/monsters_static", json_of(&$r::mythic_adventures::monsters_static())));
        out.push(("mythic_adventures/monster_abilities_static", json_of(&$r::mythic_adventures::monster_abilities_static())));
        out.push(("occult_adventures/monsters_static", json_of(&$r::occult_adventures::monsters_static())));
        out.push(("occult_adventures/monster_abilities_static", json_of(&$r::occult_adventures::monster_abilities_static())));
        out.push(("pathfinder_unchained/monsters_static", json_of(&$r::pathfinder_unchained::monsters_static())));
        out.push(("pathfinder_unchained/monster_abilities_static", json_of(&$r::pathfinder_unchained::monster_abilities_static())));
        out.push(("pathfinder_unchained/barbarian_features/features", json_of(&$r::pathfinder_unchained::barbarian_features::features())));
        out.push(("pathfinder_unchained/equipment_tables/equipment_tables", json_of(&$r::pathfinder_unchained::equipment_tables::equipment_tables())));
        out.push(("pathfinder_unchained/feat_tables/feat_tables", json_of(&$r::pathfinder_unchained::feat_tables::feat_tables())));
        out.push(("pathfinder_unchained/monk_features/features", json_of(&$r::pathfinder_unchained::monk_features::features())));
        out.push(("pathfinder_unchained/rogue_features/class_skills", json_of(&$r::pathfinder_unchained::rogue_features::class_skills())));
        out.push(("pathfinder_unchained/summoner_features/class_skills", json_of(&$r::pathfinder_unchained::summoner_features::class_skills())));
        out.push(("pathfinder_unchained/summoner_features/eidolon_subtypes", json_of(&$r::pathfinder_unchained::summoner_features::eidolon_subtypes())));
        out.push(("ultimate_campaign/feat_tables/feat_tables", json_of(&$r::ultimate_campaign::feat_tables::feat_tables())));
        out.push(("ultimate_combat/archetype_tables/archetype_swap_tables", json_of(&$r::ultimate_combat::archetype_tables::archetype_swap_tables())));
        out.push(("ultimate_combat/class_gunslinger/class_table", json_of(&$r::ultimate_combat::class_gunslinger::class_table())));
        out.push(("ultimate_combat/class_ninja/class_table", json_of(&$r::ultimate_combat::class_ninja::class_table())));
        out.push(("ultimate_combat/class_samurai/class_table", json_of(&$r::ultimate_combat::class_samurai::class_table())));
        out.push(("ultimate_combat/equipment_tables/equipment_tables", json_of(&$r::ultimate_combat::equipment_tables::equipment_tables())));
        out.push(("ultimate_combat/equipment_tables/equipmod_tables", json_of(&$r::ultimate_combat::equipment_tables::equipmod_tables())));
        out.push(("ultimate_combat/feat_tables/feat_tables", json_of(&$r::ultimate_combat::feat_tables::feat_tables())));
        out.push(("ultimate_equipment/equipment_tables/equipment_tables", json_of(&$r::ultimate_equipment::equipment_tables::equipment_tables())));
        out.push(("ultimate_equipment/equipment_tables/equipmod_tables", json_of(&$r::ultimate_equipment::equipment_tables::equipmod_tables())));
        out.push(("ultimate_intrigue/monsters_static", json_of(&$r::ultimate_intrigue::monsters_static())));
        out.push(("ultimate_intrigue/monster_abilities_static", json_of(&$r::ultimate_intrigue::monster_abilities_static())));
        out.push(("ultimate_intrigue/equipment_tables/equipment_tables", json_of(&$r::ultimate_intrigue::equipment_tables::equipment_tables())));
        out.push(("ultimate_intrigue/equipment_tables/equipmod_tables", json_of(&$r::ultimate_intrigue::equipment_tables::equipmod_tables())));
        out.push(("ultimate_intrigue/feat_tables/feat_tables", json_of(&$r::ultimate_intrigue::feat_tables::feat_tables())));
        out.push(("ultimate_magic/companions_static", json_of(&$r::ultimate_magic::companions_static())));
        out.push(("ultimate_magic/companion_abilities_static", json_of(&$r::ultimate_magic::companion_abilities_static())));
        out.push(("ultimate_magic/companion_classes_static", json_of(&$r::ultimate_magic::companion_classes_static())));
        out.push(("ultimate_magic/companions", json_of(&$r::ultimate_magic::companions())));
        out.push(("ultimate_magic/companion_abilities", json_of(&$r::ultimate_magic::companion_abilities())));
        out.push(("ultimate_magic/monsters_static", json_of(&$r::ultimate_magic::monsters_static())));
        out.push(("ultimate_magic/monster_abilities_static", json_of(&$r::ultimate_magic::monster_abilities_static())));
        out.push(("ultimate_magic/archetype_tables/archetype_swap_tables", json_of(&$r::ultimate_magic::archetype_tables::archetype_swap_tables())));
        out.push(("ultimate_magic/equipment_tables/equipment_tables", json_of(&$r::ultimate_magic::equipment_tables::equipment_tables())));
        out.push(("ultimate_magic/equipment_tables/equipmod_tables", json_of(&$r::ultimate_magic::equipment_tables::equipmod_tables())));
        out.push(("ultimate_magic/feat_tables/feat_tables", json_of(&$r::ultimate_magic::feat_tables::feat_tables())));
        out.push(("ultimate_psionics/monsters_static", json_of(&$r::ultimate_psionics::monsters_static())));
        out.push(("ultimate_psionics/monster_abilities_static", json_of(&$r::ultimate_psionics::monster_abilities_static())));
        out.push(("ultimate_psionics/monsters", json_of(&$r::ultimate_psionics::monsters())));
        out.push(("ultimate_psionics/monster_abilities", json_of(&$r::ultimate_psionics::monster_abilities())));
        out.push(("ultimate_psionics/archetype_tables/archetype_swap_tables", json_of(&$r::ultimate_psionics::archetype_tables::archetype_swap_tables())));
        out.push(("ultimate_psionics/equipment_tables/equipment_tables", json_of(&$r::ultimate_psionics::equipment_tables::equipment_tables())));
        out.push(("ultimate_psionics/equipment_tables/equipmod_tables", json_of(&$r::ultimate_psionics::equipment_tables::equipmod_tables())));
        out.push(("ultimate_psionics/feat_tables/feat_tables", json_of(&$r::ultimate_psionics::feat_tables::feat_tables())));
        out.push(("ultimate_wilderness/companions_static", json_of(&$r::ultimate_wilderness::companions_static())));
        out.push(("ultimate_wilderness/companion_abilities_static", json_of(&$r::ultimate_wilderness::companion_abilities_static())));
        out.push(("ultimate_wilderness/companions", json_of(&$r::ultimate_wilderness::companions())));
        out.push(("ultimate_wilderness/companion_abilities", json_of(&$r::ultimate_wilderness::companion_abilities())));
        out.push(("ultimate_wilderness/monsters_static", json_of(&$r::ultimate_wilderness::monsters_static())));
        out.push(("ultimate_wilderness/monster_abilities_static", json_of(&$r::ultimate_wilderness::monster_abilities_static())));
        out.push(("ultimate_wilderness/archetype_tables/archetype_swap_tables", json_of(&$r::ultimate_wilderness::archetype_tables::archetype_swap_tables())));
        out.push(("ultimate_wilderness/feat_tables/feat_tables", json_of(&$r::ultimate_wilderness::feat_tables::feat_tables())));
        // The lookups E4a.2 hand-wrote over the package (`override_tests`), over their domains.
        let mut ladders = String::new();
        for level in 0..=40u8 {
            for m in -5..=12i16 {
                ladders.push_str(&format!(
                    "{:?}{:?}{:?}{:?}{:?}{:?}{:?}{:?};",
                    $r::ultimate_psionics::psion_features::psion_power_points_total(level, m),
                    $r::ultimate_psionics::wilder_features::wilder_power_points_total(level, m),
                    $r::ultimate_psionics::vitalist_features::vitalist_power_points_total(level, m),
                    $r::ultimate_psionics::tactician_features::tactician_power_points_total(level, m),
                    $r::ultimate_psionics::psychic_warrior_features::psychic_warrior_power_points_total(level, m),
                    $r::ultimate_psionics::marksman_features::marksman_power_points_total(level, m),
                    $r::ultimate_psionics::dread_features::dread_power_points_total(level, m),
                    $r::ultimate_psionics::cryptic_features::cryptic_power_points_total(level, m),
                ));
            }
        }
        out.push(("lookup:psionic_power_point_ladders", ladders));
        let rule_sets = [$r::RuleSetId::Crb, $r::RuleSetId::Bestiary1, $r::RuleSetId::Pu, $r::RuleSetId::Apg];
        let mut monsters = String::new();
        for &id in $r::beastiary1::MonsterId::ALL {
            for rule_set in rule_sets {
                monsters.push_str(&format!("{:?};", $r::beastiary1::monster_resolve(id, rule_set)));
            }
            let name = $r::beastiary1::monster_resolve(id, $r::RuleSetId::Bestiary1).expect("every monster resolves").name;
            let key = $r::beastiary1::monster_key(&name);
            for rule_set in rule_sets {
                monsters.push_str(&format!("{key}={:?};", $r::beastiary1::monster_key_resolve(&key, rule_set)));
            }
        }
        for key in ["", "beastiary1:monster:no_such_monster", "bestiary:monster:wolf"] {
            monsters.push_str(&format!("{key}={:?};", $r::beastiary1::monster_key_resolve(key, $r::RuleSetId::Bestiary1)));
        }
        out.push(("lookup:beastiary1_monster_resolve", monsters));
        let mut chassis = String::new();
        for class_id in $r::pathfinder_unchained::class_chassis::PuClassId::ALL {
            for level in 0..=25u8 {
                for rule_set in rule_sets {
                    chassis.push_str(&format!(
                        "{:?};",
                        $r::pathfinder_unchained::class_chassis::class_chassis_resolve(class_id, level, rule_set)
                    ));
                }
            }
        }
        out.push(("lookup:unchained_class_chassis_resolve", chassis));
        let mut books = String::new();
        for book in $r::monster_chassis::MONSTER_BOOKS.iter() {
            books.push_str(&format!(
                "{}|{:?}|{:?}|{:?}|{:?};",
                book.corpus_book,
                book.monsters,
                book.monster_abilities,
                book.cross_table_owner_names,
                $r::monster_chassis::monster_book(book.corpus_book).map(|b| b.corpus_book)
            ));
        }
        books.push_str(&format!("{:?};", $r::monster_chassis::monster_book("no_such_book").map(|b| b.corpus_book)));
        for book in $r::companion_chassis::COMPANION_BOOKS.iter() {
            books.push_str(&format!(
                "{}|{:?}|{:?}|{:?}|{:?};",
                book.corpus_book,
                book.companions,
                book.companion_abilities,
                book.companion_classes,
                $r::companion_chassis::companion_book(book.corpus_book).map(|b| b.corpus_book)
            ));
        }
        books.push_str(&format!("{:?};", $r::companion_chassis::companion_book("no_such_book").map(|b| b.corpus_book)));
        out.push(("lookup:book_registries", books));
        let classes: Vec<&str> = $r::class_spell_levels::classes_with_spell_lists();
        let mut keys: Vec<&str> = $r::crb::spell_list::SPELL_LIST.iter().map(|e| e.key).collect();
        keys.extend($r::apg::spell_list::SPELL_LIST.iter().map(|e| e.key));
        keys.extend($r::acg::spell_list::SPELL_LIST.iter().map(|e| e.key));
        keys.extend($r::advanced_race_guide::spell_list::SPELL_LIST.iter().map(|e| e.key));
        keys.push("no_such_spell");
        let mut spell_levels = format!("{classes:?};");
        for class in classes.iter().copied().chain(["class:fighter", "", "class:magus"]) {
            spell_levels.push_str(&format!(
                "{class}|{:?}|{:?};",
                $r::class_spell_levels::class_has_spell_list(class),
                $r::class_spell_levels::class_spell_list_entries(class)
            ));
            for key in &keys {
                spell_levels.push_str(&format!("{:?},", $r::class_spell_levels::class_spell_level(class, key)));
            }
        }
        spell_levels.push_str(&format!(
            "{:?}",
            $r::advanced_race_guide::class_spell_levels::ARG_CLASS_SPELL_LEVELS.iter().collect::<Vec<_>>()
        ));
        out.push(("lookup:class_spell_levels", spell_levels));
        let gap: Vec<_> = $r::equipment_gap_tables::equipment_gap_rows().collect();
        out.push(("lookup:equipment_gap_rows", format!("{gap:?}")));
        out
    }};
}

fn digests(transcripts: Vec<(&'static str, String)>) -> Vec<(String, String)> {
    transcripts
        .into_iter()
        .map(|(id, text)| {
            let digest: String = Sha256::digest(text.as_bytes()).iter().map(|b| format!("{b:02x}")).collect();
            (id.to_owned(), digest)
        })
        .collect()
}

fn manifest() -> Vec<(String, String)> {
    include_str!("golden_digests.txt")
        .lines()
        .filter(|line| !line.is_empty())
        .map(|line| {
            let (digest, id) = line.split_once("  ").expect("`<sha256>  <id>` lines");
            (id.to_owned(), digest.to_owned())
        })
        .collect()
}

/// Every catalog transcript has the digest the compiled module gave it.
#[test]
fn every_catalog_table_view_and_lookup_matches_its_golden_digest() {
    let expected = manifest();
    assert_eq!(expected.len(), 423 + 6, "golden_digests.txt rows");
    let actual = digests(transcripts!(cat));
    let differing: Vec<&str> = expected
        .iter()
        .zip(&actual)
        .filter(|(e, a)| e != a)
        .map(|(e, _)| e.0.as_str())
        .collect();
    assert_eq!(expected.len(), actual.len());
    assert!(differing.is_empty(), "transcripts whose digest moved: {differing:#?}");
}
