//! Package-backed mirror of the compiled `rules_tables` module `simple_kind_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::simple_kind_tables::SimpleKindRecord;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;
pub static SEVEN_KIND_DIRS: crate::rules_core::rules_catalog::Table<(&str, &str)> =
    crate::rules_core::rules_catalog::Table::new("simple_kind_tables/SEVEN_KIND_DIRS");
pub fn kind_dir_for(kind: &str) -> Option<&'static str> {
    SEVEN_KIND_DIRS
        .iter()
        .find(|(k, _)| *k == kind)
        .map(|(_, d)| *d)
}
pub use rt::simple_kind_tables::SimpleKindTable;
pub fn load_simple_kind_table(repo_root: &Path, kind: &str) -> SimpleKindTable {
    let dir = match kind_dir_for(kind) {
        Some(d) => d,
        None => {
            return SimpleKindTable {
                kind: kind.to_string(),
                dir: "",
                records: BTreeMap::new(),
                by_coordinate: BTreeMap::new(),
            };
        }
    };
    load_simple_kind_table_for_dir(repo_root, kind, dir)
}
pub use rt::simple_kind_tables::load_simple_kind_table_for_dir;
pub use rt::simple_kind_tables::transcript_line;
