//! ARG arms armor equipment -- generated from the real
//! `arg_equip_arms_armor.lst` corpus (SD-27 Cycle E2.1/E2.2 per-book pre-build). Not
//! hand-authored -- see `equipment_tables.rs`'s own doc comment for the
//! generation method and per-category record count.
//! See `equipment_tables.rs` for record-count/defect notes.

use super::super::equipment_tables::{EquipmentCategory, EquipmentTableEntry};

pub const ARMS_ARMOR_TABLE: &[EquipmentTableEntry] = &[
    EquipmentTableEntry { key: "Celestial Shield", category: EquipmentCategory::ArmsArmor, name: "Celestial Shield", cost_gp: Some(13170.0), weight_lbs: Some(7.0), description: Some("Allows the wielder to use feather fall on himself once per day. A creature wearing celestial armor while wielding a celestial shield may command the armor to provide overland flight rather than fly once per day.") },
    EquipmentTableEntry { key: "Claw Blades (Catfolk)", category: EquipmentCategory::ArmsArmor, name: "Claw Blades (Catfolk)", cost_gp: Some(305.0), weight_lbs: Some(2.0), description: Some("Bought in a set of five, they fit over the wearer's claws on one hand. The blades grant the wearer a +1 enhancement bonus on claw attack rolls with that hand and change the weapon type from a natural weapon to a light slashing weapon. Catfolk with the cat's claws racial trait are proficient with this weapon.") },
    EquipmentTableEntry { key: "Dogslicer", category: EquipmentCategory::ArmsArmor, name: "Dogslicer", cost_gp: Some(8.0), weight_lbs: Some(1.0), description: Some("This short, curved sword is a favorite weapon of goblins, who show unusual cunning by drilling numerous holes in the blade to reduce the weapon's weight. Masterwork versions of a dogslicer lose the fragile special weapon ability.") },
    EquipmentTableEntry { key: "Earthbind Rod", category: EquipmentCategory::ArmsArmor, name: "Earthbind Rod", cost_gp: Some(26500.0), weight_lbs: Some(5.0), description: Some("Grants its wielder a +4 circumstance bonus to its CMD against bull rush, grapple, overrun, reposition, and trip combat maneuvers, but only if the wielder is an oread, has the earth subtype, or is standing on earth or stone. Three times per day, when the wielder hits a creature with this rod, as long as the target of this attack is standing on stone or earth, the wielder can attempt to entangle that creature (Fortitude DC 18 negates) for 1d4 rounds.") },
    EquipmentTableEntry { key: "Elysian Shield", category: EquipmentCategory::ArmsArmor, name: "Elysian Shield", cost_gp: Some(52620.0), weight_lbs: Some(45.0), description: Some("The wielder is immune to the create spawn ability of undead, and once per day as an immediate action can negate a single energy drain, ability drain, or ability damage attack by an undead creature. In addition, once per day as a standard action, the wielder can release a wave of positive energy that panics undead, as the Turn Undead feat (DC 20 Will negates).") },
    EquipmentTableEntry { key: "Gloom Blade", category: EquipmentCategory::ArmsArmor, name: "Gloom Blade", cost_gp: Some(8810.0), weight_lbs: Some(2.0), description: Some("acts as a +1 short sword when in dim light. In darkness, it acts as +2 short sword. When surrounded by supernatural darkness, such as in an area of deeper darkness, it acts a +2 short sword and bestows the benefit of the Blind-Fight feat to its wielder.") },
    EquipmentTableEntry { key: "Heartstake Bolts (5)", category: EquipmentCategory::ArmsArmor, name: "Heartstake Bolts (5)", cost_gp: Some(100.0), weight_lbs: Some(3.0), description: Some("A vampire struck with a heartstake bolt takes the normal damage but must also succeed at a DC 20 Fortitude saving throw or fall to the ground helpless for 1 round.") },
    EquipmentTableEntry { key: "Helmet (Dwarven Boulder)", category: EquipmentCategory::ArmsArmor, name: "Helmet (Dwarven Boulder)", cost_gp: Some(20.0), weight_lbs: Some(10.0), description: Some("This heavy, reinforced helmet can be used to make melee attacks. The wearer may also use the helmet when attempting bull rush maneuvers, granting a +2 circumstance bonus on the check, but after completing the maneuver (whether successful or not), the wearer is staggered until the end of his next turn. In addition, the helmet grants a +2 circumstance bonus to the wearer's AC against critical hit confirmation rolls. A dwarven boulder helmet adds 20%% to the wearer's arcane spell failure chance. It occupies the head slot and is made of metal, not stone, meaning that it can be crafted from unusual materials as a metal weapon. A dwarven boulder helmet can be enchanted as a weapon (not as armor, despite providing some protection).") },
    EquipmentTableEntry { key: "Horsechopper", category: EquipmentCategory::ArmsArmor, name: "Horsechopper", cost_gp: Some(10.0), weight_lbs: Some(12.0), description: Some("Crafted by goblins to give themselves an advantage against horses, this weapon is essentially a halberd with an enlarged hook opposite the blade.") },
    EquipmentTableEntry { key: "Jolting Dart", category: EquipmentCategory::ArmsArmor, name: "Jolting Dart", cost_gp: Some(100.0), weight_lbs: Some(0.5), description: Some("1d6 Electricity") },
    EquipmentTableEntry { key: "Longaxe (Dwarven)", category: EquipmentCategory::ArmsArmor, name: "Longaxe (Dwarven)", cost_gp: Some(50.0), weight_lbs: Some(14.0), description: Some("These ornate and heavy blades are mounted atop a long, steel-shod haft for greater reach. They are rare among cave-dwelling dwarves but common in mountain dwarf clans that commonly feud with giants.") },
    EquipmentTableEntry { key: "Longhammer (Dwarven)", category: EquipmentCategory::ArmsArmor, name: "Longhammer (Dwarven)", cost_gp: Some(70.0), weight_lbs: Some(20.0), description: Some("These heavy-headed bludgeons are often carved or cast with monstrous faces or drilled with tiny holes to create a menacing whistling as they are swung through the air.") },
    EquipmentTableEntry { key: "Rod of Shadows", category: EquipmentCategory::ArmsArmor, name: "Rod of Shadows", cost_gp: Some(64305.0), weight_lbs: Some(5.0), description: Some("Allows its wielder to see in darkness as if it had the see in darkness ability (Bestiary 2 301). Three times per day, the wielder can use it to create a deeper darkness effect (caster level 8th).") },
    EquipmentTableEntry { key: "Rod of Steadfast Resolve", category: EquipmentCategory::ArmsArmor, name: "Rod of Steadfast Resolve", cost_gp: Some(38305.0), weight_lbs: Some(5.0), description: Some("While a creature wields this rod, it grants all its allies within a 20-foot radius burst a +2 morale bonus on saving throws against fear and emotion effects, or a +4 morale bonus on such saves if the ally has the human subtype. Also, once per day as an immediate action, the wielder can activate the rod to allow himself or a single ally within the rod's aura to reroll a failed saving throw against a spell or effect with the fear or emotion descriptor. The affected creature must take the result of the reroll, even if it is worse.") },
    EquipmentTableEntry { key: "Sea-Knife", category: EquipmentCategory::ArmsArmor, name: "Sea-Knife", cost_gp: Some(8.0), weight_lbs: Some(1.0), description: Some("The wearer cannot use a leg with a sea-knife strapped to it for walking or running. A sea-knife can be used as a light melee weapon when the wielder is swimming, flying, or prone. This allows the wielder to use a two-handed weapon, or wield a weapon with one hand and carry a shield, and still make off-hand attacks with the sea-knife.") },
    EquipmentTableEntry { key: "Snag Net", category: EquipmentCategory::ArmsArmor, name: "Snag Net", cost_gp: Some(30.0), weight_lbs: Some(10.0), description: Some("You make a ranged touch attack against your target. A net's maximum range is 10 feet. If you hit, the target is entangled. If you entangle an opponent and hold the trailing rope, on your turn in place of a melee attack you may make a trip combat maneuver check against that opponent; if you succeed, you may trip the opponent or deal 1 point of piercing damage to the opponent.") },
    EquipmentTableEntry { key: "Swift Obsidian Greataxe", category: EquipmentCategory::ArmsArmor, name: "Swift Obsidian Greataxe", cost_gp: Some(11320.0), weight_lbs: Some(12.0), description: Some("When the wielder charges an enemy, he receives a +10 foot enhancement bonus to his speed that round. Once per day, he can command the axe to grant all allies within 30 feet a +10 foot enhancement bonus to base speed for 1 round.") },
    EquipmentTableEntry { key: "Tail Attachment (Long Lash)", category: EquipmentCategory::ArmsArmor, name: "Tail Attachment (Long Lash)", cost_gp: Some(15.0), weight_lbs: Some(1.0), description: Some("This slender cord has tiny bits of glass and stone embedded in its length.") },
    EquipmentTableEntry { key: "Tail Attachment (Pounder)", category: EquipmentCategory::ArmsArmor, name: "Tail Attachment (Pounder)", cost_gp: Some(1.0), weight_lbs: Some(4.0), description: Some("This squat ball is made from some sort of dull metal.") },
    EquipmentTableEntry { key: "Tail Attachment (Razored)", category: EquipmentCategory::ArmsArmor, name: "Tail Attachment (Razored)", cost_gp: Some(3.0), weight_lbs: Some(2.0), description: Some("This metal wedge has a prickly edge on one of its sides.") },
    EquipmentTableEntry { key: "Tail Attachment (Spiked)", category: EquipmentCategory::ArmsArmor, name: "Tail Attachment (Spiked)", cost_gp: Some(3.0), weight_lbs: Some(2.0), description: Some("This narrow spike tapers to a sharp point.") },
    EquipmentTableEntry { key: "Tail Attachment (Sweeper)", category: EquipmentCategory::ArmsArmor, name: "Tail Attachment (Sweeper)", cost_gp: Some(7.0), weight_lbs: Some(3.0), description: Some("When properly used, this sharply curved piece of metal can knock opponents off their feet. Unlike most trip weapons, you cannot drop it if you are tripped during your own trip attempt.") },
    EquipmentTableEntry { key: "Tailblade (Ratfolk)", category: EquipmentCategory::ArmsArmor, name: "Tailblade (Ratfolk)", cost_gp: Some(11.0), weight_lbs: Some(0.5), description: Some("A tailblade is a small, sharp knife designed to be strapped to the tip of a wielder's tail. A ratfolk wielding a tailblade can make a tail attack, adding its Strength modifier to the tailblade's damage. Ratfolk are considered proficient with such attacks and can apply feats or effects appropriate to natural attacks to tail attacks made with a tailblade. If used as part of a full attack action, attacks with a tailblade are considered secondary attacks.") },
    EquipmentTableEntry { key: "Terror Kite", category: EquipmentCategory::ArmsArmor, name: "Terror Kite", cost_gp: Some(20.0), weight_lbs: None, description: Some("Participants in a kite battle make alternating sunder combat maneuvers against each other's kites; each successful maneuver allows a competitor to roll 1d6 points of damage against the opponent's kite. When a kite reaches 0 hit points, it is broken or its string is cut, and its player loses the match. In some matches, points are awarded for touching the kite's top to the opponent's string, with the winner being the first to reach a set point total.") },
    EquipmentTableEntry { key: "Underwater Crossbow (Heavy)", category: EquipmentCategory::ArmsArmor, name: "Underwater Crossbow (Heavy)", cost_gp: Some(100.0), weight_lbs: Some(8.0), description: Some("An underwater crossbow functions like its normal counterpart above water, and can be used underwater. When fired underwater, the crossbow has a range increment of 20 feet.; 20 ft increment underwater") },
    EquipmentTableEntry { key: "Underwater Crossbow (Light)", category: EquipmentCategory::ArmsArmor, name: "Underwater Crossbow (Light)", cost_gp: Some(70.0), weight_lbs: Some(4.0), description: Some("An underwater crossbow functions like its normal counterpart above water, and can be used underwater. When fired underwater, the crossbow has a range increment of 20 feet.; 20 ft increment underwater") },
    EquipmentTableEntry { key: "Waraxe (Dwarven Double)", category: EquipmentCategory::ArmsArmor, name: "Waraxe (Dwarven Double)", cost_gp: Some(60.0), weight_lbs: Some(10.0), description: Some("This hefty waraxe is similar to the common dwarven waraxe, but its recurved blade spans forward and back from its head like a deadly butterfly. A dwarven double waraxe grants a +1 bonus on all attack rolls after the first when using Cleave or Great Cleave.") },
    EquipmentTableEntry { key: "Weapon (Dwarven Boulder)", category: EquipmentCategory::ArmsArmor, name: "Weapon (Dwarven Boulder)", cost_gp: None, weight_lbs: None, description: None },
];
