//! Ultimate Equipment (UE). SD-28 Epic 25 (`epic-25-ue-complete`) --
//! from-scratch book ingest, first slice: the equipment catalog (1,380
//! equipment + 180 equipment-modifier records, after excluding 54
//! cross-book republished-item collisions). See
//! `equipment_tables`'s own module doc comment for the catalog and its
//! collision-exclusion and `.COPY=`-variant rulings.

pub mod equipment_tables;
/// SD-32 `decisions.md §20`, no_record-to-zero wave: base spell
/// declarations transcribed from `ue_spells.lst`, generated by the
/// config-driven `src/bin/ingest_spells.rs` (`decisions.md §17`).
pub mod spell_list;
