//! Package-backed mirror of the compiled `rules_tables` module `inner_sea_combat` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

pub use super::companion_chassis::{
    CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord,
    NaturalAttack, Speed, StatAdjustment,
};
pub(crate) mod companion_data;
pub fn companions_static() -> &'static [CompanionRecord] {
    &*companion_data::COMPANIONS
}
pub fn companion_abilities_static() -> &'static [CompanionAbilityRecord] {
    &*companion_data::COMPANION_ABILITIES
}
pub fn companions() -> &'static [CompanionRecord] {
    companions_static()
}
pub fn companion_abilities() -> &'static [CompanionAbilityRecord] {
    companion_abilities_static()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Both counts come from `docs/work-inventory.json`'s units for this book,
    /// never a line count over the source file:
    /// `python3 -c "import json; d=json.load(open('docs/work-inventory.json'));
    /// print(sum(1 for u in d['units'] if u['book']=='inner_sea_combat' and
    /// u['kind']=='companion'))"` -> 10, split 4 creature / 6 ability by
    /// `scripts/classify_companion_rows.py`.
    #[test]
    fn the_book_defines_four_companions_and_six_abilities() {
        assert_eq!(companions().len(), 4);
        assert_eq!(companion_abilities().len(), 6);
    }

    /// Verbatim spot-check against `isc_races_companion:5`.
    #[test]
    fn the_griffon_matches_its_corpus_row() {
        let griffon = companions()
            .iter()
            .find(|c| c.key == "Companion (Griffon)")
            .expect("Companion (Griffon) is in this book");
        assert_eq!(griffon.source_line, 5);
        assert_eq!(griffon.size, Some("L"));
        assert_eq!(griffon.race_type, Some("Magical Beast"));
        assert_eq!(griffon.monster_class, Some("Companion:2"));
        assert_eq!(griffon.natural_armor, Some(4));
        assert_eq!(
            griffon.speeds,
            &[
                Speed { mode: "Walk", feet: 30 },
                Speed { mode: "Fly", feet: 40 },
            ]
        );
        // The row's own `BONUS:STAT` tokens, in row order. Adjustments, not
        // scores: the row states `BONUS:STAT|STR|6`, and a Griffon's Strength
        // is not 6.
        assert_eq!(
            griffon.stat_adjustments,
            &[
                StatAdjustment { ability: "STR", amount: 6 },
                StatAdjustment { ability: "DEX", amount: 4 },
                StatAdjustment { ability: "CON", amount: 6 },
                StatAdjustment { ability: "INT", amount: -6 },
                StatAdjustment { ability: "WIS", amount: 2 },
                StatAdjustment { ability: "CHA", amount: -2 },
            ]
        );
        // `Scent` is named by the row and defined in Core Rulebook, not here.
        assert_eq!(griffon.external_ability_refs, &["Scent"]);
    }

    /// The shared, key-less ability row — the one that needs shape 1
    /// (row-named) ownership, because it has neither a `PRERACE:` gate nor a
    /// namespaced key.
    #[test]
    fn the_flight_restriction_is_owned_by_both_flying_companions() {
        let book = super::super::companion_chassis::companion_book("inner_sea_combat")
            .expect("Inner Sea Combat is registered");
        let restriction = book
            .companion_ability_resolve("Unable to carry a rider while flying")
            .expect("the row is in this book");
        assert_eq!(restriction.source_line, 9);
        assert_eq!(
            restriction.owners,
            &["Companion (Griffon)", "Companion (Hippogriff)"]
        );
        assert_eq!(restriction.facet, Some(CompanionAbilityFacet::SpecialQuality));
    }

    /// Every advancement row of this book states its `PRERACE:` owner, and the
    /// stat adjustments it applies are transcribed rather than folded into the
    /// creature's own.
    #[test]
    fn the_worg_advancement_carries_its_own_stat_adjustments() {
        let advancement = companion_abilities()
            .iter()
            .find(|a| a.key == "Companion Advancement ~ Worg")
            .expect("the Worg advancement is in this book");
        assert_eq!(advancement.facet, Some(CompanionAbilityFacet::CompanionAdvancement));
        assert_eq!(advancement.owners, &["Companion (Worg)"]);
        assert_eq!(
            advancement.stat_adjustments,
            &[
                StatAdjustment { ability: "STR", amount: 2 },
                StatAdjustment { ability: "CON", amount: 2 },
            ]
        );
    }

    /// The `DESC:`-carrying row of this book, pinned by content: a description
    /// that reached the screen empty would be indistinguishable from a row the
    /// corpus never described.
    #[test]
    fn the_worg_mastery_row_carries_its_rules_text() {
        let mastery = companion_abilities()
            .iter()
            .find(|a| a.key == "Worg ~ Mastery")
            .expect("Worg ~ Mastery is in this book");
        let description = mastery.description.expect("the row carries a DESC: token");
        assert!(
            description.contains("fearful howl"),
            "unexpected rules text: {description}"
        );
    }
}
