//! Generated from the real PCGen corpus file `apg_feats.lst` (Advanced Player's Guide):
//! every non-comment, non-`.MOD` record whose `TYPE:` facet resolves to
//! `Combat` under the rule `apg::feats` documents. 81 records,
//! transcribed verbatim (`KEY:`/name, `TYPE:`, `DESC:`, `BONUS:`, and
//! every top-level `PRE`-family token). Generated programmatically by
//! the same offline method as `crb/feat_data/` -- do not hand-edit;
//! regenerate if the corpus changes.

use crate::rules_core::rules_tables::crb::feats::{FeatCategory, FeatEffectBonus, FeatTableEntry};

pub const COMBAT_TABLE: &[FeatTableEntry] = &[
    FeatTableEntry { key: "Bashing Finish", category: FeatCategory::Combat, name: "Bashing Finish", description: Some("You follow a powerful blow from your weapon with an opportunistic bash from your shield."), effect: None},
    FeatTableEntry { key: "Bloody Assault", category: FeatCategory::Combat, name: "Bloody Assault", description: Some("Sacrificing accuracy, you can inflict bloody wounds that are slow to heal."), effect: None},
    FeatTableEntry { key: "Bodyguard", category: FeatCategory::Combat, name: "Bodyguard", description: Some("Your swift strikes ward off enemies attacking nearby allies."), effect: None},
    FeatTableEntry { key: "Bull Rush Strike", category: FeatCategory::Combat, name: "Bull Rush Strike", description: Some("Your critical hits can push back your foes."), effect: None},
    FeatTableEntry { key: "Charge Through", category: FeatCategory::Combat, name: "Charge Through", description: Some("You can overrun enemies when charging."), effect: None},
    FeatTableEntry { key: "Cockatrice Strike", category: FeatCategory::Combat, name: "Cockatrice Strike", description: Some("With a single strike, you transmute flesh to stone."), effect: None},
    FeatTableEntry { key: "Combat Patrol", category: FeatCategory::Combat, name: "Combat Patrol", description: Some("You range across the battlefield, dealing with threats wherever they arise."), effect: None},
    FeatTableEntry { key: "Coordinated Defense", category: FeatCategory::Combat, name: "Coordinated Defense", description: Some("You are adept at working with allies to avoid being tripped, grappled, and subjected to other maneuvers."), effect: None},
    FeatTableEntry { key: "Coordinated Maneuvers", category: FeatCategory::Combat, name: "Coordinated Maneuvers", description: Some("You are skilled at working with your allies to perform dangerous combat maneuvers."), effect: None},
    FeatTableEntry { key: "Covering Defense", category: FeatCategory::Combat, name: "Covering Defense", description: Some("You are skilled at protecting yourself and your allies with your shield."), effect: None},
    FeatTableEntry { key: "Crippling Critical", category: FeatCategory::Combat, name: "Crippling Critical", description: Some("You are able to maim a target and hinder its movement."), effect: None},
    FeatTableEntry { key: "Crossbow Mastery", category: FeatCategory::Combat, name: "Crossbow Mastery", description: Some("You can load crossbows with blinding speed and even fire them in melee with little fear of reprisal."), effect: None},
    FeatTableEntry { key: "Dastardly Finish", category: FeatCategory::Combat, name: "Dastardly Finish", description: Some("You can take advantage of an enemy's debilitated state to attempt a coup de grace."), effect: None},
    FeatTableEntry { key: "Dazing Assault", category: FeatCategory::Combat, name: "Dazing Assault", description: Some("You can daze foes with wild attacks."), effect: None},
    FeatTableEntry { key: "Disarming Strike", category: FeatCategory::Combat, name: "Disarming Strike", description: Some("Your critical hits can disarm your foes."), effect: None},
    FeatTableEntry { key: "Disrupting Shot", category: FeatCategory::Combat, name: "Disrupting Shot", description: Some("With a well-placed shot, you make it harder for a nearby opponent to cast spells."), effect: None},
    FeatTableEntry { key: "Dreadful Carnage", category: FeatCategory::Combat, name: "Dreadful Carnage", description: Some("Slaying an enemy demoralizes your other nearby foes."), effect: None},
    FeatTableEntry { key: "Eldritch Claws", category: FeatCategory::Combat, name: "Eldritch Claws", description: Some("Who needs magic weapons? Eldritch tricks are no match for your bestial ferocity."), effect: None},
    FeatTableEntry { key: "Elemental Fist", category: FeatCategory::Combat, name: "Elemental Fist", description: None, effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "ElementalFistDamage", "1"] }, FeatEffectBonus { qualifiers: &["VAR", "ElementalFistUses", "classlevel(\"Monk\")"] }, FeatEffectBonus { qualifiers: &["VAR", "ElementalFistUses", "(TL-classlevel(\"Monk\"))/4"] }, FeatEffectBonus { qualifiers: &["VAR", "ElementalFistFullVersion", "1", "PREMULT:1,[PREVAREQ:ElementalFistGranted,1],[PREMULT:3,[PRETOTALAB:8],[PREABILITY:1,CATEGORY=FEAT,Improved Unarmed Strike],[PRESTAT:2,CON=13,WIS=13]]"] }])},
    FeatTableEntry { key: "Elemental Fist ~ Dragon Ferocity", category: FeatCategory::Combat, name: "Elemental Fist", description: Some("You empower your strike with elemental energy"), effect: Some(&[FeatEffectBonus { qualifiers: &["ABILITYPOOL", "Elemental Fist Choice", "1"] }])},
    FeatTableEntry { key: "Elemental Fist ~ Full Version", category: FeatCategory::Combat, name: "Elemental Fist", description: Some("You empower your strike with elemental energy"), effect: None},
    FeatTableEntry { key: "Elven Accuracy", category: FeatCategory::Combat, name: "Elven Accuracy", description: Some("Your sharp eyesight makes difficult shots easier."), effect: None},
    FeatTableEntry { key: "Enforcer", category: FeatCategory::Combat, name: "Enforcer", description: Some("You are skilled at causing fear in those you brutalize."), effect: None},
    FeatTableEntry { key: "Focused Shot", category: FeatCategory::Combat, name: "Focused Shot", description: Some("Your anatomical insight adds deadliness to your shots."), effect: None},
    FeatTableEntry { key: "Following Step", category: FeatCategory::Combat, name: "Following Step", description: Some("You can repeatedly close the distance when foes try to move away, without impeding your normal movement."), effect: None},
    FeatTableEntry { key: "Furious Focus", category: FeatCategory::Combat, name: "Furious Focus", description: Some("Even in the midst of fierce and furious blows, you can find focus in the carnage and your seemingly wild blows strike home."), effect: None},
    FeatTableEntry { key: "Gang Up", category: FeatCategory::Combat, name: "Gang Up", description: Some("You are adept at using greater numbers against foes."), effect: None},
    FeatTableEntry { key: "Greater Blind-Fight", category: FeatCategory::Combat, name: "Greater Blind-Fight", description: Some("Your enemies cannot hide from you."), effect: None},
    FeatTableEntry { key: "Greater Dirty Trick", category: FeatCategory::Combat, name: "Greater Dirty Trick", description: Some("When you pull a dirty trick, your foe is truly hindered."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_DirtyTrick", "2"] }])},
    FeatTableEntry { key: "Greater Drag", category: FeatCategory::Combat, name: "Greater Drag", description: Some("Foes that you drag around are thrown out of balance."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Drag", "2"] }])},
    FeatTableEntry { key: "Greater Reposition", category: FeatCategory::Combat, name: "Greater Reposition", description: Some("When you reposition foes, they are left vulnerable to attacks of your allies."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMD_Reposition", "2"] }])},
    FeatTableEntry { key: "Greater Shield Specialization", category: FeatCategory::Combat, name: "Greater Shield Specialization", description: Some("Your masterful shieldwork provides even greater protection to your vital areas."), effect: None},
    FeatTableEntry { key: "Greater Steal", category: FeatCategory::Combat, name: "Greater Steal", description: Some("You have a knack for snatching items from your opponent in combat."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMD_Steal", "2"] }])},
    FeatTableEntry { key: "Improved Blind-Fight", category: FeatCategory::Combat, name: "Improved Blind-Fight", description: Some("Your keen senses guide your hand against hidden foes."), effect: None},
    FeatTableEntry { key: "Improved Dirty Trick", category: FeatCategory::Combat, name: "Improved Dirty Trick", description: Some("You are skilled at pulling dirty tricks on your foes."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_DirtyTrick,CMD_DirtyTrick", "2"] }])},
    FeatTableEntry { key: "Improved Drag", category: FeatCategory::Combat, name: "Improved Drag", description: Some("You are skilled at dragging foes around the battlefield"), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Drag,CMD_Drag", "2"] }])},
    FeatTableEntry { key: "Improved Ki Throw", category: FeatCategory::Combat, name: "Improved Ki Throw", description: Some("Your enemies are living weapons in your hands."), effect: None},
    FeatTableEntry { key: "Improved Reposition", category: FeatCategory::Combat, name: "Improved Reposition", description: Some("You have learned how to force your enemies to move around the battlefield."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Reposition,CMD_Reposition", "2"] }])},
    FeatTableEntry { key: "Improved Second Chance", category: FeatCategory::Combat, name: "Improved Second Chance", description: Some("You can turn a missed strike into a second chance without sacrificing later attacks."), effect: None},
    FeatTableEntry { key: "Improved Sidestep", category: FeatCategory::Combat, name: "Improved Sidestep", description: Some("You are adept at sidestepping your opponent's melee attacks without compromising your mobility."), effect: None},
    FeatTableEntry { key: "Improved Steal", category: FeatCategory::Combat, name: "Improved Steal", description: Some("You have a knack for snatching items from your opponents."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMB_Steal,CMD_Steal", "2"] }])},
    FeatTableEntry { key: "In Harm's Way", category: FeatCategory::Combat, name: "In Harm's Way", description: Some("You put yourself in danger's path to save your allies."), effect: None},
    FeatTableEntry { key: "Ki Throw", category: FeatCategory::Combat, name: "Ki Throw", description: Some("Your physical control and mastery of momentum allows you to throw enemies."), effect: None},
    FeatTableEntry { key: "Lookout", category: FeatCategory::Combat, name: "Lookout", description: Some("Your allies help you avoid being surprised."), effect: None},
    FeatTableEntry { key: "Low Profile", category: FeatCategory::Combat, name: "Low Profile", description: Some("Your small stature helps you avoid ranged attacks."), effect: None},
    FeatTableEntry { key: "Missile Shield", category: FeatCategory::Combat, name: "Missile Shield", description: Some("You are skilled at deflecting ranged attacks with your shield."), effect: None},
    FeatTableEntry { key: "Mounted Shield", category: FeatCategory::Combat, name: "Mounted Shield", description: Some("Your defensive tactics defend both you and your mount."), effect: None},
    FeatTableEntry { key: "Mounted Skirmisher", category: FeatCategory::Combat, name: "Mounted Skirmisher", description: Some("You are adept at attacking from upon a swift moving steed."), effect: None},
    FeatTableEntry { key: "Outflank", category: FeatCategory::Combat, name: "Outflank", description: Some("You look for every edge when flanking an enemy."), effect: None},
    FeatTableEntry { key: "Paired Opportunists", category: FeatCategory::Combat, name: "Paired Opportunists", description: Some("You know how to make an enemy pay for lax defenses."), effect: None},
    FeatTableEntry { key: "Parting Shot", category: FeatCategory::Combat, name: "Parting Shot", description: Some("You are an expert skirmisher, able to rain missiles upon your enemies whether advancing or retreating."), effect: None},
    FeatTableEntry { key: "Perfect Strike", category: FeatCategory::Combat, name: "Perfect Strike", description: Some("When wielding a monk weapon, your attacks can be extremely precise."), effect: None},
    FeatTableEntry { key: "Point Blank Master", category: FeatCategory::Combat, name: "Point Blank Master", description: Some("You are adept at firing ranged weapons in close quarters."), effect: None},
    FeatTableEntry { key: "Practiced Tactician", category: FeatCategory::Combat, name: "Practiced Tactician", description: Some("With only a few quick gestures and commands, you can direct others in combat."), effect: None},
    FeatTableEntry { key: "Precise Strike", category: FeatCategory::Combat, name: "Precise Strike", description: Some("You are skilled at striking where it counts, as long as an ally distracts your foe."), effect: None},
    FeatTableEntry { key: "Punishing Kick", category: FeatCategory::Combat, name: "Punishing Kick", description: Some("Your kicks are so powerful you use them to push or knock back."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "PunishingKickDC", "10+(TL/2)+WIS"] }, FeatEffectBonus { qualifiers: &["VAR", "PunishingKickTimes", "TL/4"] }])},
    FeatTableEntry { key: "Pushing Assault", category: FeatCategory::Combat, name: "Pushing Assault", description: Some("A strike made with a two-handed weapon can push a similar sized opponent backward."), effect: None},
    FeatTableEntry { key: "Ray Shield", category: FeatCategory::Combat, name: "Ray Shield", description: Some("You can even deflect rays with your shield."), effect: None},
    FeatTableEntry { key: "Rending Claws", category: FeatCategory::Combat, name: "Rending Claws", description: Some("Your claw attacks do greater harm to your enemy."), effect: None},
    FeatTableEntry { key: "Repositioning Strike", category: FeatCategory::Combat, name: "Repositioning Strike", description: Some("Your critical hits can move your foes where you wish."), effect: None},
    FeatTableEntry { key: "Saving Shield", category: FeatCategory::Combat, name: "Saving Shield", description: Some("You def lect attacks that could mean your ally's death."), effect: None},
    FeatTableEntry { key: "Second Chance", category: FeatCategory::Combat, name: "Second Chance", description: Some("Quick reflexes turn missed strikes into second chances."), effect: None},
    FeatTableEntry { key: "Shadow Strike", category: FeatCategory::Combat, name: "Shadow Strike", description: Some("You accurately strike even those you cannot clearly see."), effect: None},
    FeatTableEntry { key: "Shield of Swings", category: FeatCategory::Combat, name: "Shield of Swings", description: Some("A wild frenzy of attacks serves to bolster your defenses."), effect: None},
    FeatTableEntry { key: "Shield Specialization", category: FeatCategory::Combat, name: "Shield Specialization", description: Some("You have mastered the use of one type of shield."), effect: None},
    FeatTableEntry { key: "Shield Wall", category: FeatCategory::Combat, name: "Shield Wall", description: Some("You form a unified defense with those around you."), effect: None},
    FeatTableEntry { key: "Sidestep", category: FeatCategory::Combat, name: "Sidestep", description: Some("You can reposition yourself after a foe's missed swing."), effect: None},
    FeatTableEntry { key: "Smash", category: FeatCategory::Combat, name: "Smash", description: Some("You overcome obstacles by breaking them."), effect: None},
    FeatTableEntry { key: "Stabbing Shot", category: FeatCategory::Combat, name: "Stabbing Shot", description: Some("You can clear the way to continue using your bow."), effect: None},
    FeatTableEntry { key: "Step Up and Strike", category: FeatCategory::Combat, name: "Step Up and Strike", description: Some("When a foe tries to move away, you can follow and make an attack."), effect: None},
    FeatTableEntry { key: "Stunning Assault", category: FeatCategory::Combat, name: "Stunning Assault", description: Some("You powerful but imprecise attacks can stun your enemies."), effect: None},
    FeatTableEntry { key: "Sundering Strike", category: FeatCategory::Combat, name: "Sundering Strike", description: Some("Your critical hits can sunder your foes' weapons."), effect: None},
    FeatTableEntry { key: "Swap Places", category: FeatCategory::Combat, name: "Swap Places", description: Some("You are skilled at changing places with your ally during a chaotic melee."), effect: None},
    FeatTableEntry { key: "Swift Aid", category: FeatCategory::Combat, name: "Swift Aid", description: Some("With a quick but harmless swipe, you can aid an ally's assault."), effect: None},
    FeatTableEntry { key: "Team Up", category: FeatCategory::Combat, name: "Team Up", description: Some("When you are ganging up against an enemy, you can aid an ally with a quick feint."), effect: None},
    FeatTableEntry { key: "Teleport Tactician", category: FeatCategory::Combat, name: "Teleport Tactician", description: Some("You are highly alert for enemies using teleportation to approach you or flee from you."), effect: None},
    FeatTableEntry { key: "Touch of Serenity", category: FeatCategory::Combat, name: "Touch of Serenity", description: Some("With a single touch you can reduce the threat of even the most savage of foes."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "TouchOfSerenityDC", "10+WIS+(TL/2)"] }, FeatEffectBonus { qualifiers: &["VAR", "TouchOfSerenityTimes", "min(1,(TL/4))"] }, FeatEffectBonus { qualifiers: &["VAR", "TouchOfSerenityDuration", "1"] }])},
    FeatTableEntry { key: "Trick Riding", category: FeatCategory::Combat, name: "Trick Riding", description: Some("You are not only skilled at controlling a horse in combat; you can make it look like art."), effect: None},
    FeatTableEntry { key: "Tripping Strike", category: FeatCategory::Combat, name: "Tripping Strike", description: Some("The force intrinsic to your critical hits can knock your foes down."), effect: None},
    FeatTableEntry { key: "Under and Over", category: FeatCategory::Combat, name: "Under and Over", description: Some("You can slip under a foe trying to grab you, knocking him off balance."), effect: None},
    FeatTableEntry { key: "Underfoot", category: FeatCategory::Combat, name: "Underfoot", description: Some("You slip under and around your larger foes."), effect: None},
];
