//! Package-backed mirror of the compiled `rules_tables` module `inner_sea_gods::monster_data` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

use crate::rules_core::rules_catalog::monster_chassis::{
    MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterStatBlock,
    NaturalAttack, Speed, StatAdjustment,
};
pub(crate) static MONSTERS: crate::rules_core::rules_catalog::Table<MonsterStatBlock> =
    crate::rules_core::rules_catalog::Table::new("inner_sea_gods/monster_data/MONSTERS");
pub(crate) static MONSTER_ABILITIES: crate::rules_core::rules_catalog::Table<MonsterAbilityRecord> =
    crate::rules_core::rules_catalog::Table::new("inner_sea_gods/monster_data/MONSTER_ABILITIES");
