//! Package-backed mirror of the compiled `rules_tables` module `bestiary` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use super::monster_chassis::{
    MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterStatBlock,
    NaturalAttack, Speed,
};
pub(crate) mod monster_data;
pub mod spell_list;
pub fn monsters_static() -> &'static [MonsterStatBlock] {
    &*monster_data::MONSTERS
}
pub fn monster_abilities_static() -> &'static [MonsterAbilityRecord] {
    &*monster_data::MONSTER_ABILITIES
}
pub fn monsters() -> &'static [MonsterStatBlock] {
    monsters_static()
}
pub fn monster_abilities() -> &'static [MonsterAbilityRecord] {
    monster_abilities_static()
}
pub(crate) fn cross_table_owner_names() -> &'static [&'static str] {
    crate::rules_core::rules_catalog::rows::<&'static str>("bestiary/cross_table_owner_names")
}
