//! Package-backed mirror of the compiled `rules_tables` module `pathfinder_unchained::class_chassis` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

use super::monk_features;
use crate::rules_core::rules_catalog::RuleSetId;
use crate::rules_core::rules_catalog::apg::{self, ApgClassId};
use crate::rules_core::rules_catalog::crb::class_tables::{self, ClassId};
pub use rt::pathfinder_unchained::class_chassis::ClassTableRow;
pub use rt::pathfinder_unchained::class_chassis::PuClassId;
pub fn hit_die_for(class_id: PuClassId) -> u8 {
    match class_id {
        // `class_tables::hit_die_for` returns `Option`, but only because it
        // must answer for a `ClassId` its own `&*CLASS_META` might not carry.
        // Barbarian and Rogue are both in `&*CLASS_META` (and the tests below
        // pin that), so the `expect` documents an invariant rather than
        // hiding a fallible lookup.
        PuClassId::UnchainedBarbarian => class_tables::hit_die_for(ClassId::Barbarian)
            .expect("crb::class_tables carries a Barbarian row"),
        PuClassId::UnchainedMonk => monk_features::HIT_DIE,
        PuClassId::UnchainedRogue => class_tables::hit_die_for(ClassId::Rogue)
            .expect("crb::class_tables carries a Rogue row"),
        PuClassId::UnchainedSummoner => apg::hit_die_for(ApgClassId::Summoner),
    }
}
pub fn class_chassis_resolve(
    class_id: PuClassId,
    level: u8,
    rule_set: RuleSetId,
) -> Option<ClassTableRow> {
    if rule_set != RuleSetId::Pu {
        return None;
    }
    crate::rules_core::rules_catalog::rows::<crate::rules_core::rules_data_package::UnchainedClassRow>("pathfinder_unchained/class_chassis/class_chassis_resolve")
        .iter()
        .find(|row| row.class_id == class_id && row.row.level == level)
        .map(|row| row.row)
}
