//! pathfinder_unchained monster + monster-ability tables, transcribed verbatim
//! from the book's own PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_monster_tables.py pathfinder_unchained`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst` (which counts `.MOD`/`.COPY` overlays the
//! inventory correctly excludes).
//!
//! Sources, with the line each record was read from carried per row:
//!   * `pu_abilities_race.lst` -- 72 monster-ability rows
//!
//! 72 further ability row(s) in this book are ORPHANS -- no monster
//! row here claims them, so they SHIP with `owners: &[]` rather than being
//! dropped (`decisions.md §20`: an un-ingested row's shape cannot be measured,
//! and Gate 1's DoD needs every unit's shape measured). `list_monster_catalog`
//! only ever walks a monster's OWN `ability_keys`, so an owner-less record here
//! reaches no screen -- reachability is NOT claimed for these, and each key is
//! pinned as a named, provable non-reach in `reach_gate.rs::
//! UNREACHED_RECORD_FINDINGS`, never silently assumed reachable:
//!   * `pu_abilities_race.lst:98`
//!   * `pu_abilities_race.lst:99`
//!   * `pu_abilities_race.lst:100`
//!   * `pu_abilities_race.lst:101`
//!   * `pu_abilities_race.lst:102`
//!   * `pu_abilities_race.lst:103`
//!   * `pu_abilities_race.lst:105`
//!   * `pu_abilities_race.lst:106`
//!   * `pu_abilities_race.lst:107`
//!   * `pu_abilities_race.lst:108`
//!   * `pu_abilities_race.lst:109`
//!   * `pu_abilities_race.lst:110`
//!   * `pu_abilities_race.lst:112`
//!   * `pu_abilities_race.lst:113`
//!   * `pu_abilities_race.lst:114`
//!   * `pu_abilities_race.lst:115`
//!   * `pu_abilities_race.lst:116`
//!   * `pu_abilities_race.lst:117`
//!   * `pu_abilities_race.lst:119`
//!   * `pu_abilities_race.lst:120`
//!   * `pu_abilities_race.lst:121`
//!   * `pu_abilities_race.lst:122`
//!   * `pu_abilities_race.lst:123`
//!   * `pu_abilities_race.lst:124`
//!   * `pu_abilities_race.lst:126`
//!   * `pu_abilities_race.lst:127`
//!   * `pu_abilities_race.lst:128`
//!   * `pu_abilities_race.lst:129`
//!   * `pu_abilities_race.lst:130`
//!   * `pu_abilities_race.lst:131`
//!   * `pu_abilities_race.lst:133`
//!   * `pu_abilities_race.lst:134`
//!   * `pu_abilities_race.lst:135`
//!   * `pu_abilities_race.lst:136`
//!   * `pu_abilities_race.lst:137`
//!   * `pu_abilities_race.lst:138`
//!   * `pu_abilities_race.lst:140`
//!   * `pu_abilities_race.lst:141`
//!   * `pu_abilities_race.lst:142`
//!   * `pu_abilities_race.lst:143`
//!   * `pu_abilities_race.lst:144`
//!   * `pu_abilities_race.lst:145`
//!   * `pu_abilities_race.lst:147`
//!   * `pu_abilities_race.lst:148`
//!   * `pu_abilities_race.lst:149`
//!   * `pu_abilities_race.lst:150`
//!   * `pu_abilities_race.lst:151`
//!   * `pu_abilities_race.lst:152`
//!   * `pu_abilities_race.lst:154`
//!   * `pu_abilities_race.lst:155`
//!   * `pu_abilities_race.lst:156`
//!   * `pu_abilities_race.lst:157`
//!   * `pu_abilities_race.lst:158`
//!   * `pu_abilities_race.lst:159`
//!   * `pu_abilities_race.lst:161`
//!   * `pu_abilities_race.lst:162`
//!   * `pu_abilities_race.lst:163`
//!   * `pu_abilities_race.lst:164`
//!   * `pu_abilities_race.lst:165`
//!   * `pu_abilities_race.lst:166`
//!   * `pu_abilities_race.lst:168`
//!   * `pu_abilities_race.lst:169`
//!   * `pu_abilities_race.lst:170`
//!   * `pu_abilities_race.lst:171`
//!   * `pu_abilities_race.lst:172`
//!   * `pu_abilities_race.lst:173`
//!   * `pu_abilities_race.lst:175`
//!   * `pu_abilities_race.lst:176`
//!   * `pu_abilities_race.lst:177`
//!   * `pu_abilities_race.lst:178`
//!   * `pu_abilities_race.lst:179`
//!   * `pu_abilities_race.lst:180`

use crate::rules_core::rules_tables::monster_chassis::{MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterStatBlock, NaturalAttack, Speed, StatAdjustment};

/// Every pathfinder_unchained monster stat block (0 rows).
pub(super) static MONSTERS: &[MonsterStatBlock] = &[
];

/// Every pathfinder_unchained monster-ability record (72 rows).
pub(super) static MONSTER_ABILITIES: &[MonsterAbilityRecord] = &[
    MonsterAbilityRecord {
        key: "Agathion ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AgathionLVL1"],
        description: Some("Starting at 1st level, agathion eidolons gain the resistance (electricity) evolution. They also gain a +4 bonus on saving throws against poison and petrification."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 98,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Agathion ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AgathionLVL4"],
        description: Some("At 4th level, agathion eidolons gain cold resistance 10 and sonic resistance 10."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 99,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Agathion ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AgathionLVL8"],
        description: Some("At 8th level, agathion eidolons gain lay on hands as paladins with levels equal to their Hit Dice."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 100,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Agathion ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AgathionLVL12"],
        description: Some("At 12th level, agathion eidolons gain DR 5/evil. They also gain immunity to petrification and the truespeech ability (see the agathion subtype on page 306 of Pathfinder RPG Bestiary 2)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 101,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Agathion ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AgathionLVL16"],
        description: Some("At 16th level, agathion eidolons lose the resistance (electricity) evolution, and instead gain the immunity (electricity) evolution. They also gain the agathion's speak with animals ability (see the agathion subtype on page 306 of Bestiary 2)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 102,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Agathion ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AgathionLVL20"],
        description: Some("At 20th level, agathion eidolons gain detect thoughts as a spell-like ability at will and also increase their damage reduction to DR 10/evil."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 103,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Angel ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AngelLVL1"],
        description: Some("At 1st level, angel eidolons gain the resistance (acid) and resistance (cold) evolutions. They also gain a +4 bonus on saving throws against poison."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 105,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Angel ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AngelLVL4"],
        description: Some("At 4th level, angel eidolons gain electricity resistance 10 and fire resistance 10."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 106,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Angel ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AngelLVL8"],
        description: Some("At 8th level, angel eidolons grow large, feathery wings, gaining the flight evolution."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 107,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Angel ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AngelLVL12"],
        description: Some("At 12th level, angel eidolons gain DR 5/evil. They also gain immunity to petrification and the truespeech ability (see the angel subtype on page 310 of the Bestiary)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 108,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Angel ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AngelLVL16"],
        description: Some("At 16th level, angel eidolons lose the resistance (acid) and resistance (cold) evolutions, and instead gain the immunity (acid) and immunity (cold) evolutions."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 109,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Angel ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AngelLVL20"],
        description: Some("At 20th level, angel eidolons gain the protective aura ability (see the angel subtype on page 310 of the Bestiary)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 110,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Archon ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ArchonLVL1"],
        description: Some("At 1st level, archon eidolons gain the resistance (electricity) evolution and the skilled (Intimidate) evolution. They also gain a +4 bonus on saving throws against poison."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 112,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Archon ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ArchonLVL4"],
        description: Some("At 4th level, archon eidolons add 1 point to their evolution pools."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 113,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Archon ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ArchonLVL8"],
        description: Some("At 8th level, archon eidolons gain the ability increase evolution, applied to an ability score the summoner chooses."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 114,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Archon ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ArchonLVL12"],
        description: Some("At 12th level, archon eidolons gain DR 5/evil. They also gain immunity to petrification and the truespeech ability (see the archon subtype on page 310 of the Bestiary)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 115,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Archon ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ArchonLVL16"],
        description: Some("At 16th level, archon eidolons lose the resistance (electricity) evolution and skilled (Intimidate) evolution, and instead gain the immunity (electricity) evolution. In addition, they gain the aura of menace ability (see the archon subtype on page 310 of the Bestiary)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 116,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Archon ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ArchonLVL20"],
        description: Some("At 20th level, archon eidolons gain the ability to use greater teleport at will, as the spell (caster level 14th), except they can teleport only themselves and up to 50 pounds of carried objects."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 117,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Azata ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AzataLVL1"],
        description: Some("At 1st level, azata eidolons gain the resistance (electricity) evolution and the 4-point weapon training evolution (proficiency in martial weapons)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 119,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Azata ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AzataLVL4"],
        description: Some("At 4th level, azata eidolons gain cold resistance 10 and fire resistance 10."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 120,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Azata ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AzataLVL8"],
        description: Some("At 8th level, azata eidolons grow large, feathery wings, gaining the flight evolution."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 121,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Azata ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AzataLVL12"],
        description: Some("At 12th level, azata eidolons gain DR 5/evil. They also gain immunity to petrification and the truespeech ability (see the azata subtype on page 311 of the Bestiary)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 122,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Azata ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AzataLVL16"],
        description: Some("At 16th level, azata eidolons lose the resistance (electricity) evolution, and instead gain the immunity (electricity) evolution. They also gain the ability increase evolution, applied to an ability score of the summoner's choice."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 123,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Azata ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["AzataLVL20"],
        description: Some("At 20th level, an azata eidolon gains the ability to switch between its normal form and an energy form as a standard action. In its energy form, an azata eidolon is incorporeal and doubles its fly speed, but it can't make natural or manufactured weapon attacks; it can, however, activate any spell-like ability evolutions it possesses."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 124,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Daemon ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DaemonLVL1"],
        description: Some("Starting at 1st level, daemon eidolons gain the resistance (acid) evolution as well as a +4 bonus on saving throws against death effects, disease, and poison."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 126,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Daemon ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DaemonLVL4"],
        description: Some("At 4th level, daemon eidolons gain cold resistance 10, electricity resistance 10, and fire resistance 10."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 127,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Daemon ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DaemonLVL8"],
        description: Some("At 8th level, daemon eidolons add 1 point to their evolution pools."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 128,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Daemon ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DaemonLVL12"],
        description: Some("At 12th level, daemon eidolons gain DR 5/good. They also gain immunity to death effects, disease, and poison."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 129,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Daemon ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DaemonLVL16"],
        description: Some("At 16th level, daemon eidolons lose the resistance (acid) evolution, and instead gain the immunity (acid) evolution. They also gain telepathy (Bestiary 305)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 130,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Daemon ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DaemonLVL20"],
        description: Some("At 20th level, as a standard action, a daemon eidolon can devour a portion of the soul of a dying creature or a creature that died no earlier than 1 round ago. This kills the creature and provides the daemon eidolon a profane bonus on attack rolls, saving throws, and skill checks for 24 hours. The bonus is equal to +1 per 5 Hit Dice the slain creature possessed. A creature whose soul was devoured in this way requires resurrection or more powerful magic to return from the dead."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 131,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Demon ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DemonLVL1"],
        description: Some("Starting at 1st level, demon eidolons gain the resistance (electricity) and resistance (fire) evolutions as well as a +4 bonus on saving throws against poison."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 133,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Demon ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DemonLVL4"],
        description: Some("At 4th level, demon eidolons gain acid resistance 10 and cold resistance 10."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 134,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Demon ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DemonLVL8"],
        description: Some("At 8th level, demon eidolons lose the +4 bonus on saving throws against poison and gain immunity to poison. They also add 1 point to their evolution pools."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 135,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Demon ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DemonLVL12"],
        description: Some("At 12th level, demon eidolons gain DR 5/good. They also gain the ability increase evolution in an ability score of the summoner's choice."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 136,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Demon ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DemonLVL16"],
        description: Some("At 16th level, demon eidolons lose the resistance (electricity) evolution, and instead gain the immunity (electricity) evolution. They also gain telepathy (Bestiary 305)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 137,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Demon ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DemonLVL20"],
        description: Some("At 20th level, demon eidolons gain true seeing as a constant spell-like ability."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 138,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Devil ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DevilLVL1"],
        description: Some("Starting at 1st level, devil eidolons gain the resistance (fire) evolution and the skilled (Bluff) evolution. They also gain a +4 bonus on saving throws against poison."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 140,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Devil ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DevilLVL4"],
        description: Some("At 4th level, devil eidolons gain acid resistance 10 and cold resistance 10."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 141,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Devil ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DevilLVL8"],
        description: Some("At 8th level, devil eidolons gain the skilled (Diplomacy) evolution and gain immunity to poison."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 142,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Devil ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DevilLVL12"],
        description: Some("At 12th level, devil eidolons gain DR 5/good. They also gain see in darkness (see the devil subtype on page 311 of the Bestiary)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 143,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Devil ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DevilLVL16"],
        description: Some("At 16th level, devil eidolons lose the resistance (fire) evolution, and instead gain the immunity (fire) evolution. They also gain telepathy (Bestiary 305)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 144,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Devil ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DevilLVL20"],
        description: Some("At 20th level, devil eidolons gain regeneration 5 (good weapons, good spells). They are still banished to Hell as normal for eidolons if they take enough damage."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 145,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Div ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DivLVL1"],
        description: Some("Starting at 1st level, div eidolons gain the resistance (fire) evolution. They also gain a +4 bonus on saving throws against poison."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 147,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Div ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DivLVL4"],
        description: Some("At 4th level, div eidolons gain acid resistance 10 and electricity resistance 10."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 148,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Div ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DivLVL8"],
        description: Some("At 8th level, div eidolons add 1 point to their evolution pools and immunity to poison."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 149,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Div ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DivLVL12"],
        description: Some("At 12th level, div eidolons gain DR 5/good. They also gain see in darkness (see the div subtype on page 305 of Pathfinder RPG Bestiary 3)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 150,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Div ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DivLVL16"],
        description: Some("At 16th level, div eidolons lose the resistance (fire) evolution, and instead gain the immunity (fire) evolution. They also gain telepathy (Bestiary 305)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 151,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Div ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["DivLVL20"],
        description: Some("At 20th level, div eidolons gain the ability to use greater teleport at will, as per the spell (caster level 14th), except they can teleport only themselves and up to 50 pounds of carried objects."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 152,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Elemental ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ElementalLVL1"],
        description: Some("At 1st level, all elemental eidolons gain immunity to paralysis and sleep. In addition,  Air elemental eidolons gain the immunity (electricity) evolution.  Earth elemental eidolons gain the immunity (acid) evolution.  Fire elemental eidolons gain the immunity (fire) evolution.  Water elemental eidolons gain the immunity (cold) evolution."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 154,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Elemental ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ElementalLVL4"],
        description: Some("At 4th level, all elemental eidolons add 1 point to their evolution pools."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 155,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Elemental ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ElementalLVL8"],
        description: Some("At 8th level,  Air elemental eidolons gain the flight evolution (using magic) with a speed equal to their base speed.  Earth elemental eidolons gain the burrow evolution.  Fire elemental eidolons increase their base speed by 20 feet.  Water elemental eidolons gain the swim evolution twice, gaining a swim speed equal to their base speed + 20 feet. They also gain the gills evolution, which allows them to breathe underwater."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 156,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Elemental ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ElementalLVL12"],
        description: Some("At 12th level, all elemental eidolons gain immunity to bleed, poison, and stun. In addition, they can no longer be flanked."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 157,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Elemental ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ElementalLVL16"],
        description: Some("At 16th level, all elemental eidolons gain immunity to critical hits and do not take additional damage from precision-based attacks, such as sneak attack."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 158,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Elemental ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ElementalLVL20"],
        description: Some("At 20th level,  Air elemental eidolon gains the whirlwind ability (Bestiary 306), with a maximum height of 15 feet (30 feet for a Large air elemental) and dealing 1d6 points of damage (1d8 for a Large air elemental).  Earth elemental eidolons gain the earth mastery ability (Bestiary 122) and DR 5/-.  Fire elemental eidolons gain the energy attacks (fire) evolution and the burn ability (Bestiary 298).  Water elemental eidolons gain the drench and vortex abilities (Bestiary 126). The vortex ability works as the air elemental eidolon's whirlwind ability (except as noted in the vortex ability's description)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 159,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Inevitable ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["InevitableLVL1"],
        description: Some("At 1st level, inevitable eidolons count as both constructs and outsiders for the purpose of effects such as the bane weapon special ability and the favored enemy class feature. They gain a +4 bonus on saving throws against death effects, disease, necromancy effects, paralysis, poison, sleep, and stun."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 161,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Inevitable ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["InevitableLVL4"],
        description: Some("At 4th level, inevitable eidolons gain a +4 bonus on saving throws against mind-affecting effects and immunity to nonlethal damage, fatigue, and exhaustion."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 162,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Inevitable ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["InevitableLVL8"],
        description: Some("At 8th level, inevitable eidolons gain immunity to death effects, disease, and poison."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 163,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Inevitable ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["InevitableLVL12"],
        description: Some("At 12th level, inevitable eidolons gain DR 5/chaotic. They also gain immunity to sleep, as well as the true speech ability (see the inevitable subtype on page 307 of Bestiary 2)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 164,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Inevitable ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["InevitableLVL16"],
        description: Some("At 16th level, inevitable eidolons lose the +4 bonus on saving throws against necromancy effects and gain immunity to ability damage, ability drain, energy drain, and necromancy effects."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 165,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Inevitable ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["InevitableLVL20"],
        description: Some("At 20th level, inevitable eidolons gain immunity to paralysis, sleep, stun, and any effect that requires a Fortitude save (unless the effect also works on objects)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 166,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Protean ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ProteanLVL1"],
        description: Some("At 1st level, protean eidolons gain the resistance (acid) evolution as well as the grab evolution, tied to an attack type of the summoner's choice. Whenever the summoner changes the protean eidolon's evolutions, he can also change the attack type for grab."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 168,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Protean ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ProteanLVL4"],
        description: Some("At 4th level, protean eidolons gain electricity resistance 10 and sonic resistance 10."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 169,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Protean ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ProteanLVL8"],
        description: Some("At 8th level, protean eidolons gain the constrict evolution."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 170,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Protean ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ProteanLVL12"],
        description: Some("At 12th level, protean eidolons gain DR 5/lawful. They also gain the blindsense evolution and the ability to fly without wings with perfect maneuverability, as the flight evolution with 4 points spent."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 171,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Protean ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ProteanLVL16"],
        description: Some("At 16th level, protean eidolons lose the resistance (acid) evolution and instead gain the immunity (acid) evolution. They also gain the amorphous anatomy ability (see the protean subtype on page 308 of Bestiary 2)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 172,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Protean ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["ProteanLVL20"],
        description: Some("At 20th level, protean eidolons gain constant freedom of movement and the protean version of the change shape (greater polymorph) ability (see the protean subtype on page 308 of Bestiary 2)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 173,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Psychopomp ~ Unchained Eidolon LVL01",
        name: "Eidolon Progession Lv.1",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["PsychopompLVL1"],
        description: Some("Starting at 1st level, psychopomp eidolons gain immunity to death effects, disease, and poison"),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 175,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Psychopomp ~ Unchained Eidolon LVL04",
        name: "Eidolon Progession Lv.4",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["PsychopompLVL4"],
        description: Some("At 4th level, psychopomp eidolons gain cold resistance 10 and electricity resistance 10."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 176,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Psychopomp ~ Unchained Eidolon LVL08",
        name: "Eidolon Progession Lv.8",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["PsychopompLVL8"],
        description: Some("At 8th level, psychopomp eidolons gain the spirit touch ability (see the psychopomp subtype on page 308 of Pathfinder RPG Bestiary 4) and add 1 point to their evolution pools."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 177,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Psychopomp ~ Unchained Eidolon LVL12",
        name: "Eidolon Progession Lv.12",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["PsychopompLVL12"],
        description: Some("At 12th level, psychopomp eidolons gain DR 5/adamantine. They also gain the spiritsense ability (see the psychopomp subtype on page 308 of Bestiary 4)."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 178,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Psychopomp ~ Unchained Eidolon LVL16",
        name: "Eidolon Progession Lv.16",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["PsychopompLVL16"],
        description: Some("At 16th level, psychopomp eidolons gain the ability increase evolution, applied to an ability score of the summoner's choice. They also gain the ability to cast invisibility (self only) as a spell-like ability at will."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 179,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Psychopomp ~ Unchained Eidolon LVL20",
        name: "Eidolon Progession Lv.20",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &["PsychopompLVL20"],
        description: Some("At 20th level, psychopomp eidolons increase their damage reduction to 10/adamantine and gain the immunity (cold) and immunity (electricity) evolutions."),
        description_variables: &[],
        source_page: None,
        owners: &[],
        source_file: "pu_abilities_race.lst",
        source_line: 180,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
];
