//! bonus_bestiary monster + monster-ability tables, transcribed verbatim
//! from the book's own PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_monster_tables.py bonus_bestiary`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst` (which counts `.MOD`/`.COPY` overlays the
//! inventory correctly excludes).
//!
//! Sources, with the line each record was read from carried per row:
//!   * `bb_races.lst` -- 14 monster rows
//!   * `bb_abilities_race.lst` -- 17 monster-ability rows

use crate::rules_core::rules_tables::monster_chassis::{MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterSpellLikeAbility, MonsterStatBlock, NaturalAttack, Speed, StatAdjustment};

/// Every bonus_bestiary monster stat block (14 rows).
pub(super) static MONSTERS: &[MonsterStatBlock] = &[
    MonsterStatBlock {
        key: "Allip",
        name: "Allip",
        size: Some("M"),
        speeds: &[Speed { mode: "Fly", feet: 30 }],
        race_type: Some("Undead"),
        race_subtype: Some("Incorporeal"),
        challenge_rating: Some("3"),
        monster_class: Some("Undead:4"),
        source_page: Some("p.4"),
        natural_attacks: &[NaturalAttack { name: "Incorporeal touch", damage_dice: Some("0") }],
        ability_keys: &["Babble", "Madness", "Touch of Insanity"],
        external_ability_refs: &["Channel Resistance", "Flight Maneuverability"],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CHA", amount: 6 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "bb_races.lst",
        source_line: 6,
    },
    MonsterStatBlock {
        key: "Ant Lion (Giant)",
        name: "Ant Lion (Giant)",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Burrow", feet: 10 }],
        race_type: Some("Vermin"),
        race_subtype: None,
        challenge_rating: Some("5"),
        monster_class: Some("Vermin:8"),
        source_page: Some("p.5"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        ability_keys: &["Sand Trap"],
        external_ability_refs: &["Grab"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 10 }, StatAdjustment { ability: "CON", amount: 6 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "bb_races.lst",
        source_line: 7,
    },
    MonsterStatBlock {
        key: "Ant Lion (Mature)",
        name: "Ant Lion (Mature)",
        size: Some("H"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 60 }],
        race_type: Some("Vermin"),
        race_subtype: None,
        challenge_rating: Some("6"),
        monster_class: Some("Vermin:10"),
        source_page: Some("p.5"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        ability_keys: &[],
        external_ability_refs: &["Flight Maneuverability"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 14 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 8 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "bb_races.lst",
        source_line: 8,
    },
    MonsterStatBlock {
        key: "Ascomoid",
        name: "Ascomoid",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        race_type: Some("Plant"),
        race_subtype: None,
        challenge_rating: Some("5"),
        monster_class: Some("Plant:7"),
        source_page: Some("p.6"),
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        ability_keys: &["Spores"],
        external_ability_refs: &["Resistance to Electricity", "Resistance to Fire", "Trample"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 8 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "CHA", amount: -9 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "bb_races.lst",
        source_line: 9,
    },
    MonsterStatBlock {
        key: "Axe Beak",
        name: "Axe Beak",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        race_type: Some("Animal"),
        race_subtype: None,
        challenge_rating: Some("2"),
        monster_class: Some("Animal:3"),
        source_page: Some("p.7"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        ability_keys: &["Sudden Charge"],
        external_ability_refs: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 8 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "bb_races.lst",
        source_line: 10,
    },
    MonsterStatBlock {
        key: "Caryatid Column",
        name: "Caryatid Column",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }],
        race_type: Some("Construct"),
        race_subtype: None,
        challenge_rating: Some("3"),
        monster_class: Some("Construct:3"),
        source_page: Some("p.8"),
        natural_attacks: &[],
        ability_keys: &["Caryatid Column ~ Immunity to Magic", "Shatter Weapons", "Statue"],
        external_ability_refs: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 8 }, StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "CHA", amount: -9 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "bb_races.lst",
        source_line: 11,
    },
    MonsterStatBlock {
        key: "Dragon (Faerie)",
        name: "Dragon (Faerie)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 60 }, Speed { mode: "Swim", feet: 30 }],
        race_type: Some("Dragon"),
        race_subtype: None,
        challenge_rating: Some("2"),
        monster_class: Some("Faerie Dragon:3"),
        source_page: Some("p.9"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        ability_keys: &["Faerie Dragon ~ Breath Weapon"],
        external_ability_refs: &["Flight Maneuverability", "Immunity to Paralysis", "Immunity to Sleep"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: 6 }, StatAdjustment { ability: "CHA", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 4 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("3"), spell: "Invisibility (Greater/self only)", save_dc_token: None }],
        source_file: "bb_races.lst",
        source_line: 12,
    },
    MonsterStatBlock {
        key: "Dragonne",
        name: "Dragonne",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Fly", feet: 30 }],
        race_type: Some("Magical Beast"),
        race_subtype: None,
        challenge_rating: Some("7"),
        monster_class: Some("Magical Beast:9"),
        source_page: Some("p.10"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        ability_keys: &["Roar"],
        external_ability_refs: &["Flight Maneuverability", "Pounce", "Scent"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "bb_races.lst",
        source_line: 13,
    },
    MonsterStatBlock {
        key: "Hag (Annis)",
        name: "Hag (Annis)",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        race_type: Some("Monstrous Humanoid"),
        race_subtype: None,
        challenge_rating: Some("6"),
        monster_class: Some("Monstrous Humanoid:7"),
        source_page: Some("p.11"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        ability_keys: &[],
        external_ability_refs: &["Grab", "Rend"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 14 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CON", amount: 8 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("7"), spell: "Disguise Self", save_dc_token: Some("11+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("7"), spell: "Fog Cloud", save_dc_token: Some("12+CHA") }],
        source_file: "bb_races.lst",
        source_line: 14,
    },
    MonsterStatBlock {
        key: "Huecuva",
        name: "Huecuva",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Undead"),
        race_subtype: None,
        challenge_rating: Some("2"),
        monster_class: Some("Undead:3"),
        source_page: Some("p.12"),
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: None }],
        ability_keys: &["Faithless", "Huecuva ~ Disease"],
        external_ability_refs: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -6 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("3"), spell: "Disguise Self", save_dc_token: Some("11+CHA") }],
        source_file: "bb_races.lst",
        source_line: 15,
    },
    MonsterStatBlock {
        key: "Lammasu",
        name: "Lammasu",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 60 }],
        race_type: Some("Magical Beast"),
        race_subtype: None,
        challenge_rating: Some("8"),
        monster_class: Some("Lammasu:9"),
        source_page: Some("p.13"),
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: None }],
        ability_keys: &["Magic Circle against Evil"],
        external_ability_refs: &["Flight Maneuverability", "Pounce", "Rake"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 12 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 8 }, StatAdjustment { ability: "INT", amount: 6 }, StatAdjustment { ability: "WIS", amount: 6 }, StatAdjustment { ability: "CHA", amount: 4 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("9"), spell: "Dimension Door", save_dc_token: Some("14+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("2"), time_unit: None, caster_level_token: Some("9"), spell: "Invisibility (Greater/self only)", save_dc_token: None }],
        source_file: "bb_races.lst",
        source_line: 16,
    },
    MonsterStatBlock {
        key: "Naga (Water)",
        name: "Naga (Water)",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 50 }],
        race_type: Some("Aberration"),
        race_subtype: None,
        challenge_rating: Some("7"),
        monster_class: Some("Water Naga:8"),
        source_page: Some("p.14"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        ability_keys: &["Water Naga ~ Poison"],
        external_ability_refs: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "WIS", amount: 6 }, StatAdjustment { ability: "CHA", amount: 6 }, StatAdjustment { ability: "DEX", amount: 12 }, StatAdjustment { ability: "CON", amount: 10 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "bb_races.lst",
        source_line: 17,
    },
    MonsterStatBlock {
        key: "Nixie",
        name: "Nixie",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 30 }],
        race_type: Some("Fey"),
        race_subtype: Some("Aquatic"),
        challenge_rating: Some("1"),
        monster_class: Some("Fey:2"),
        source_page: Some("p.15"),
        natural_attacks: &[],
        ability_keys: &[],
        external_ability_refs: &["Wild Empathy"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 8 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("12"), spell: "Water Breathing", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("12"), spell: "Charm Person", save_dc_token: Some("11+CHA") }],
        source_file: "bb_races.lst",
        source_line: 18,
    },
    MonsterStatBlock {
        key: "Shadow Mastiff",
        name: "Shadow Mastiff",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Evil|Extraplanar"),
        challenge_rating: Some("5"),
        monster_class: Some("Outsider (Fort/Ref):6"),
        source_page: Some("p.16"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        ability_keys: &["Shadow Mastiff ~ Bay", "Shadow Mastiff ~ Shadow Blend"],
        external_ability_refs: &["Scent", "Trip"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -6 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "bb_races.lst",
        source_line: 19,
    },
];

/// Every bonus_bestiary monster-ability record (17 rows).
pub(super) static MONSTER_ABILITIES: &[MonsterAbilityRecord] = &[
    MonsterAbilityRecord {
        key: "Babble",
        name: "Babble",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Aura"],
        description: Some("An allip constantly mutters and whines to itself, creating a hypnotic effect. All sane creatures within 60 feet of the allip must succeed on a DC %1 Will save or be fascinated for 2d4 rounds. While a target is fascinated, the allip can approach without breaking the effect, but an attack by the allip breaks the effect. This is a sonic, mind-affecting compulsion effect. Creatures that successfully save cannot be affected by the same allip's babble for 24 hours."),
        description_variables: &["BabbleDC"],
        source_page: Some("p.4"),
        owners: &["Allip"],
        source_file: "bb_abilities_race.lst",
        source_line: 6,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Madness",
        name: "Madness",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Anyone targeting an allip with a thought detection, mind control, or telepathic ability makes direct contact with its tortured mind and takes 1d4 points of Wisdom damage."),
        description_variables: &[],
        source_page: Some("p.4"),
        owners: &["Allip"],
        source_file: "bb_abilities_race.lst",
        source_line: 7,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Touch of Insanity",
        name: "Touch of Insanity",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The touch of an allip deals 1d4 points of Wisdom damage. A successful critical hit causes 1d4 points of Wisdom damage and 1 point of Wisdom drain (instead of double Wisdom damage). On each such successful attack, an allip gains 5 temporary hit points."),
        description_variables: &[],
        source_page: Some("p.4"),
        owners: &["Allip"],
        source_file: "bb_abilities_race.lst",
        source_line: 8,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Sand Trap",
        name: "Sand Trap",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A giant ant lion can create a 60-foot-diameter trap in any sand or soft earth surface (mechanical trap, Perception DC 15, 20 ft. deep, no damage; DC 15 Reflex to avoid; DC 20 Climb check to climb out). Creating a sand trap takes 1 hour. A giant ant lion can make an attack of opportunity against any creature that falls to the bottom of its sand trap. These creatures can move across sand traps at their normal speed and are immune to these trap effects."),
        description_variables: &[],
        source_page: Some("p.5"),
        owners: &["Ant Lion (Giant)"],
        source_file: "bb_abilities_race.lst",
        source_line: 12,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Spores",
        name: "Spores",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Once per round, as a free action, an ascomoid can release a jet of deadly spores in a 30-foot line. Upon impacting a solid surface, such as a wall or creature, the jet billows out into a cloud of spores, that fills a 10-foot-radius area. This cloud lasts for 1 round before dispersing. Any creature in the cloud inhales ascomoid poison (Save Fortitude DC %1, Frequency 1 round (7), Effect 1 Con damage, Cure 1 save). Even if the save succeeds, creatures inside the cloud are nauseated as long as they remain in the cloud. Ascomoids are immune to ascomoid spores."),
        description_variables: &["SporesDC"],
        source_page: Some("p.6"),
        owners: &["Ascomoid"],
        source_file: "bb_abilities_race.lst",
        source_line: 16,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Sudden Charge",
        name: "Sudden Charge",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("When making a charge attack, an axe beak makes a single bite attack. If successful, it may also attempt to trip its opponent as a free action without provoking a attack of opportunity. If the attempt fails, the axe beak is not tripped in return."),
        description_variables: &[],
        source_page: Some("p.7"),
        owners: &["Axe Beak"],
        source_file: "bb_abilities_race.lst",
        source_line: 20,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Caryatid Column ~ Immunity to Magic",
        name: "Immunity to Magic",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["Immunity"],
        description: Some("A caryatid column is immune to any spell or spell-like ability that allows spell resistance. In addition, certain spells and effects function differently against the creature. A Transmute Rock to Mud spell deals 1d6 points of damage per caster level to a caryatid column, with no saving throw. Transmute Mud to Rock, on the other hand, heals any lost hit points. A Stone to Flesh spell does not actually change the column's structure but negates its damage reduction and immunity to magic for 1 round."),
        description_variables: &[],
        source_page: Some("p.8"),
        owners: &["Caryatid Column"],
        source_file: "bb_abilities_race.lst",
        source_line: 24,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Shatter Weapons",
        name: "Shatter Weapons",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Whenever a character strikes a caryatid column with a weapon (magical or nonmagical), the weapon takes 3d6 points of damage. Apply the weapon's hardness normally. Weapons that take any amount of damage in excess of their hardness gain the broken quality."),
        description_variables: &[],
        source_page: Some("p.8"),
        owners: &["Caryatid Column"],
        source_file: "bb_abilities_race.lst",
        source_line: 25,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Statue",
        name: "Statue",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A caryatid column can stand perfectly still, emulating a statue (usually one that is holding up the ceiling, like a carved column). An observer must succeed on a DC 20 Perception check to notice the caryatid column is alive."),
        description_variables: &[],
        source_page: Some("p.8"),
        owners: &["Caryatid Column"],
        source_file: "bb_abilities_race.lst",
        source_line: 26,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Faerie Dragon ~ Breath Weapon",
        name: "Breath Weapon",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("5-foot cone, euphoria for 1d6 rounds, DC %1 Fortitude negates. Affected creatures are staggered, sickened, and immunte to fear effects for the duration of the euphoria. A faerie dragon can use this breath weapon once every 1d4 rounds."),
        description_variables: &["BreathWeaponDC"],
        source_page: Some("p.9"),
        owners: &["Dragon (Faerie)"],
        source_file: "bb_abilities_race.lst",
        source_line: 30,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Roar",
        name: "Roar",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A dragonne can unleash a devastating roar every 1d4 rounds as a standard action. All creatures except dragonnes within 120 feet must succed on a DC %1 Fortitude save or become fatigued. Those within 30 feet who fail their saves are also deafened for 2d4 rounds. This is a sonic effect."),
        description_variables: &["RoarDC"],
        source_page: Some("p.10"),
        owners: &["Dragonne"],
        source_file: "bb_abilities_race.lst",
        source_line: 34,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Huecuva ~ Disease",
        name: "Disease",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Claw, Save Fortitude DC %1, Frequency 1d3 days/1 day, Effect 1d3 Dex damage and 1d3 Con damage, Cure 2 consecutive saves."),
        description_variables: &["HuecuvaDiseaseDC"],
        source_page: Some("p.12"),
        owners: &["Huecuva"],
        source_file: "bb_abilities_race.lst",
        source_line: 38,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Faithless",
        name: "Faithless",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Aura"],
        description: Some("The huecuva and all undead creatures within 30 feet receive a +2 profane bonus on Will saves made toresist channeled energy and any effects based off that ability. This bonus stacks with channel resistance."),
        description_variables: &[],
        source_page: Some("p.12"),
        owners: &["Huecuva"],
        source_file: "bb_abilities_race.lst",
        source_line: 39,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Magic Circle against Evil",
        name: "Magic Circle against Evil",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: None,
        description_variables: &[],
        source_page: None,
        owners: &["Lammasu"],
        source_file: "bb_abilities_race.lst",
        source_line: 43,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Water Naga ~ Poison",
        name: "Poison",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Bite, Level 7, Save Fortitude DC %1, Frequency 1 round (10), Effect 1 Con damage, Cure 1 save."),
        description_variables: &["WaterNagaPoisonDC"],
        source_page: Some("p.14"),
        owners: &["Naga (Water)"],
        source_file: "bb_abilities_race.lst",
        source_line: 47,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Shadow Mastiff ~ Bay",
        name: "Bay",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("When a shadow mastiff howls or barks, all creatures except evil outsiders within a 300-foot spread must succeed on a DC %1 Will save or become panicked for 2d4 rounds. This is a sonic, mind-affecting fear effect. A creature that successfully saves cannot be affected by the same mastiff's bay for 24 hours."),
        description_variables: &["BayDC"],
        source_page: Some("p.16"),
        owners: &["Shadow Mastiff"],
        source_file: "bb_abilities_race.lst",
        source_line: 51,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Shadow Mastiff ~ Shadow Blend",
        name: "Shadow Blend",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("In any condition of illumination other than full daylight, a shadow mastiff disappears into the shadows, giving it total concealment. Artificial illumination, even a Light or Continual Flame spell, does not negate this ability. A Daylight spell, however, will. A shadow mastiff can suspend or resume this ability as a free action."),
        description_variables: &[],
        source_page: Some("p.16"),
        owners: &["Shadow Mastiff"],
        source_file: "bb_abilities_race.lst",
        source_line: 52,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
];
