//! inner_sea_intrigue companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py inner_sea_intrigue`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `isi_races_companion.lst` -- 2 companion creature rows
//!   * `isi_abilities_race_companion.lst` -- 9 companion ability rows

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, SkillAbilityDiffBonus, Speed, StatAdjustment};

/// Every inner_sea_intrigue companion creature (2 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Familiar (Clockwork Spy)",
        name: "Familiar (Clockwork Spy)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Construct"),
        race_subtype: Some("Clockwork"),
        monster_class: Some("Construct:1"),
        type_segments: &["Companion", "Familiar", "Construct"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 0 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: 0 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: -10 }],
        natural_armor: None,
        source_page: Some("p.47"),
        ability_keys: &["Clockwork Spy ~ Record Audio", "Clockwork Spy ~ Self-Destruct", "Clockwork Spy ~ Tinkering"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "isi_races_companion.lst",
        source_line: 8,
    },
    CompanionRecord {
        key: "Familiar (Clockwork Familiar)",
        name: "Familiar (Clockwork Familiar)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Construct"),
        race_subtype: Some("Clockwork"),
        monster_class: Some("Construct:3"),
        type_segments: &["Companion", "Familiar", "Construct"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 0 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: 0 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 0 }],
        natural_armor: Some(2),
        source_page: Some("p.47"),
        ability_keys: &["Clockwork Familiar ~ Electricity", "Clockwork Familiar ~ Item Installation", "Clockwork Familiar ~ Tinkering", "Clockwork Familiar ~ Potion Installation", "Clockwork Familiar ~ Scroll Installation", "Clockwork Familiar ~ Wand Installation"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "isi_races_companion.lst",
        source_line: 9,
    },
];

/// Every inner_sea_intrigue companion ability record (9 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Clockwork Spy ~ Record Audio",
        name: "Record Audio",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["ClockworkSpyRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("A clockwork spy can record nearby sounds as a swift action, archiving all sound within a 20-foot spread onto a small gemstone worth 50 gp embedded in its body. The clockwork spy can record up to 1 hour of sound per Hit Die it possesses. Starting and stopping playback of recorded sound is a swift action. Removing a gemstone or installing a gemstone into a clockwork spy requires a DC 25 Disable Device check as a full-round action-failure does not damage the gemstone but does erase any recorded sounds on the gemstone. Since clockwork spies are not intelligent, they must be given simple commands as to when they are to start recording sounds. A clockwork spy can differentiate between creature types and subtypes, but not between specific individuals-a spy can be ordered to start recording sound as soon as a humanoid (human) or an aberration comes in range, but it cannot be ordered to start recording when a specific person comes within range. Once a clockwork spy begins recording sound, it cannot cease recording early. Likewise, it cannot record sound onto a gemstone that already contains a recording."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Clockwork Spy)"],
        cross_book_owners: &[],
        source_file: "isi_abilities_race_companion.lst",
        source_line: 11,
    },
    CompanionAbilityRecord {
        key: "Clockwork Spy ~ Self-Destruct",
        name: "Self-Destruct",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["ClockworkSpyRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("Unless specifically programmed otherwise by its creator, a clockwork spy explodes 1 round after it is destroyed. During this round, the thing shrieks and thrashes about as if undergoing convulsions. On what would normally have been the clockwork spy's next action, it explodes, dealing 1d6 points of fire damage in a 5-foot radius (Reflex DC 10 for half damage). A DC 20 Disable Device check made as a standard action can halt the spy's self-destruct sequence, but does not prevent it from dying. A clockwork spy that self-destructs automatically destroys its gemstone, along with any information contained inside it. The save DC is Constitution-based."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Clockwork Spy)"],
        cross_book_owners: &[],
        source_file: "isi_abilities_race_companion.lst",
        source_line: 12,
    },
    CompanionAbilityRecord {
        key: "Clockwork Spy ~ Tinkering",
        name: "Tinkering",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["ClockworkSpyRacialAbility", "SpecialQuality", "Extraordinary"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Clockwork Spy)"],
        cross_book_owners: &[],
        source_file: "isi_abilities_race_companion.lst",
        source_line: 13,
    },
    CompanionAbilityRecord {
        key: "Clockwork Familiar ~ Electricity",
        name: "Electricity",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["ClockworkFamiliarRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("A clockwork familiar's bite does an additional 1d6 electricity damage."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Clockwork Familiar)"],
        cross_book_owners: &[],
        source_file: "isi_abilities_race_companion.lst",
        source_line: 26,
    },
    CompanionAbilityRecord {
        key: "Clockwork Familiar ~ Item Installation",
        name: "Item Installation",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["ClockworkFamiliarRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("Each clockwork familiar possesses the ability to carry a magic item in its body. This specific item type is chosen at the time of the construct's creation, and cannot be changed. While the creature cannot activate or use the item, it gains certain constant abilities from the resonant magic fields, and can drain the item's magic as a free action in order to gain additional magical effects. In addition, any clockwork construct can drain a single charge or spell level from its installed item to heal itself for 1d6 hit points as a standard action. Removing a spent item and installing a new one is a full-round action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Clockwork Familiar)"],
        cross_book_owners: &[],
        source_file: "isi_abilities_race_companion.lst",
        source_line: 27,
    },
    CompanionAbilityRecord {
        key: "Clockwork Familiar ~ Tinkering",
        name: "Tinkering",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["ClockworkFamiliarRacialAbility", "SpecialQuality", "Extraordinary"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Clockwork Familiar)"],
        cross_book_owners: &[],
        source_file: "isi_abilities_race_companion.lst",
        source_line: 28,
    },
    CompanionAbilityRecord {
        key: "Clockwork Familiar ~ Potion Installation",
        name: "Potion Installation",
        facet: None,
        delivery: None,
        type_segments: &["ClockworkFamiliarInstalledItem"],
        description: Some("The clockwork familiar gains a constant protection from good/evil/law/chaos effect (one type only, chosen each time a new potion is installed). In addition, a clockwork familiar can drain the magic from the potion in order to grant this ability to a creature sharing its space. This ability to include others in the protection effect lasts for 1 minute per spell level of the potion drained."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Clockwork Familiar)"],
        cross_book_owners: &[],
        source_file: "isi_abilities_race_companion.lst",
        source_line: 30,
    },
    CompanionAbilityRecord {
        key: "Clockwork Familiar ~ Scroll Installation",
        name: "Scroll Installation",
        facet: None,
        delivery: None,
        type_segments: &["ClockworkFamiliarInstalledItem"],
        description: Some("The clockwork familiar gains a constant detect magic effect as a spell-like ability. Draining magic from a scroll allows the familiar to cast a single identify spell on behalf of its master for each spell level of the spell inscribed on the scroll-these castings may be stored and saved, though a scroll used in this manner becomes instantly useless, even if not all spell levels have been drained."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Clockwork Familiar)"],
        cross_book_owners: &[],
        source_file: "isi_abilities_race_companion.lst",
        source_line: 31,
    },
    CompanionAbilityRecord {
        key: "Clockwork Familiar ~ Wand Installation",
        name: "Wand Installation",
        facet: None,
        delivery: None,
        type_segments: &["ClockworkFamiliarInstalledItem"],
        description: Some("The clockwork familiar gains the ability to spit a glob of acid up to 30 feet as a ranged touch attack, dealing 1d4 points of damage. Draining a charge increases the damage to 2d4 points for a single attack. This charge is spent before the attack is rolled."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Clockwork Familiar)"],
        cross_book_owners: &[],
        source_file: "isi_abilities_race_companion.lst",
        source_line: 32,
    },
];
