//! bestiary_4 companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py bestiary_4`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `b4_races_companion.lst` -- 34 companion creature rows
//!   * `b4_abilities_companion.lst` -- 40 companion ability rows
//!   * `b4_abilities_race_ce_companion.lst` -- 4 companion ability rows
//!
//! NOT transcribed -- rows that state a DELTA on another record rather than
//! a record of their own. Transcribing one verbatim ships a card with almost
//! every field empty; resolving it needs a second citation this chassis does
//! not carry (`decisions.md §59.2`, adopting the monster lane's `.COPY=`
//! screen). Their owners no longer name them:
//!   * `Pooka ~ Change Shape` (`origin: copy`)
//!   * `Psychopomp (Nosoi) ~ Change Shape` (`origin: copy`)

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, NaturalAttackDamageBonus, SkillAbilityDiffBonus, Speed, StatAdjustment};

/// Every bestiary_4 companion creature (34 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Companion (Dinosaur (Dimorphodon))",
        name: "Companion (Dinosaur (Dimorphodon))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 80 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Dimorphodon)", "Companion (Dinosaur (Dimorphodon)) ~ Poison"],
        external_ability_refs: &["Scent"],
        source_file: "b4_races_companion.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Diplodocus))",
        name: "Companion (Dinosaur (Diplodocus))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Tail Slap", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(6),
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Diplodocus)", "Companion (Dinosaur (Diplodocus)) ~ Tail Lash"],
        external_ability_refs: &["Scent"],
        source_file: "b4_races_companion.lst",
        source_line: 7,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Styracosaurus))",
        name: "Companion (Dinosaur (Styracosaurus))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Gore", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(6),
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Styracosaurus)", "Companion (Dinosaur (Styracosaurus)) ~ Reflexive Strike"],
        external_ability_refs: &["Scent"],
        source_file: "b4_races_companion.lst",
        source_line: 8,
    },
    CompanionRecord {
        key: "Companion (Giraffe)",
        name: "Companion (Giraffe)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Hoof", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(2),
        source_page: Some("p.311"),
        ability_keys: &["Companion (Giraffe) ~ Natural Weapons", "Companion Advancement ~ Giraffe"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Companion (Stag)",
        name: "Companion (Stag)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Gore", formula: "max(0,(STR/2))|PREVARLT:MasterLevel,4" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: None,
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Stag"],
        external_ability_refs: &["Scent"],
        source_file: "b4_races_companion.lst",
        source_line: 10,
    },
    CompanionRecord {
        key: "Companion (Seahorse)",
        name: "Companion (Seahorse)",
        size: Some("L"),
        speeds: &[Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(10),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(4),
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Seahorse", "Companion (Seahorse) ~ Anchor"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 11,
    },
    CompanionRecord {
        key: "Companion (Trumpeter Swan)",
        name: "Companion (Trumpeter Swan)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 80 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Wing", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Trumpeter Swan"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 12,
    },
    CompanionRecord {
        key: "Companion (Tortoise)",
        name: "Companion (Tortoise)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 10 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(6),
        source_page: Some("p.311"),
        ability_keys: &["Companion Advancement ~ Tortoise"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 13,
    },
    CompanionRecord {
        key: "Companion (Weasel (Giant))",
        name: "Companion (Weasel (Giant))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 10 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.311"),
        ability_keys: &["Grab ~ Medium", "Companion Advancement ~ Weasel (Giant)"],
        external_ability_refs: &["Scent", "Blood Drain"],
        source_file: "b4_races_companion.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Companion (Walrus)",
        name: "Companion (Walrus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Swim", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(4),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Walrus"],
        external_ability_refs: &["Hold Breath"],
        source_file: "b4_races_companion.lst",
        source_line: 15,
    },
    CompanionRecord {
        key: "Familiar (Archaeopteryx)",
        name: "Familiar (Archaeopteryx)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Climb", feet: 10 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.96"),
        ability_keys: &["Archaeopteryx ~ Weak Flier"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 17,
    },
    CompanionRecord {
        key: "Familiar (Dodo)",
        name: "Familiar (Dodo)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: -2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.96"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 18,
    },
    CompanionRecord {
        key: "Familiar (Platypus)",
        name: "Familiar (Platypus)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Swim", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Spur", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Spur", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.96"),
        ability_keys: &["Platypus ~ Electrolocation", "Platypus ~ Poison", "Platypus ~ Semiaquatic"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 19,
    },
    CompanionRecord {
        key: "Familiar (Sloth)",
        name: "Familiar (Sloth)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Climb", feet: 5 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -6 }, StatAdjustment { ability: "DEX", amount: -4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.97"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 20,
    },
    CompanionRecord {
        key: "Familiar (Tuatara)",
        name: "Familiar (Tuatara)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Climb", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.97"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 21,
    },
    CompanionRecord {
        key: "Familiar (Giant Flea)",
        name: "Familiar (Giant Flea)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Vermin"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Vermin:1"),
        type_segments: &["Companion", "Familiar", "Vermin"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.99"),
        ability_keys: &["Flea (Giant) ~ Disease", "Flea (Giant) ~ Uncanny Leap"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 22,
    },
    CompanionRecord {
        key: "Familiar (Almiraj)",
        name: "Familiar (Almiraj)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Burrow", feet: 10 }],
        reach_feet: Some(5),
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:2"),
        type_segments: &["Companion", "Familiar", "Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("2d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -6 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.8"),
        ability_keys: &["Almiraj ~ Hex-Prone", "Almiraj ~ Magic Horn"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 25,
    },
    CompanionRecord {
        key: "Familiar (Beheaded)",
        name: "Familiar (Beheaded)",
        size: Some("T"),
        speeds: &[Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Undead"),
        race_subtype: None,
        monster_class: Some("Undead:1"),
        type_segments: &["Companion", "Familiar", "Undead"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }],
        natural_armor: None,
        source_page: Some("p.17"),
        ability_keys: &["Beheaded ~ Base", "Beheaded ~ Belching", "Beheaded ~ Flaming", "Beheaded ~ Grabbing", "Beheaded ~ Screaming", "Beheaded ~ Swarming"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 26,
    },
    CompanionRecord {
        key: "Familiar (Shadow Drake)",
        name: "Familiar (Shadow Drake)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 90 }],
        reach_feet: Some(0),
        race_type: Some("Dragon"),
        race_subtype: Some("Cold"),
        monster_class: Some("Dragon:3"),
        type_segments: &["Companion", "Familiar", "Dragon"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 10 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 6 }],
        natural_armor: Some(1),
        source_page: Some("p.80"),
        ability_keys: &["Drake (Shadow) ~ Shadow Blend", "Drake (Shadow) ~ Speed Surge", "Drake (Shadow) ~ Stygian Breath"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 27,
    },
    CompanionRecord {
        key: "Familiar (Isitoq)",
        name: "Familiar (Isitoq)",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Undead"),
        race_subtype: None,
        monster_class: Some("Undead:2"),
        type_segments: &["Companion", "Familiar", "Undead"],
        natural_attacks: &[NaturalAttack { name: "Wing", damage_dice: Some("1d1") }, NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -6 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: -4 }, StatAdjustment { ability: "WIS", amount: 4 }],
        natural_armor: None,
        source_page: Some("p.159"),
        ability_keys: &["Isitoq ~ Daze", "Isitoq ~ Tears of Anguish", "Isitoq ~ Visual Sensor"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 28,
    },
    CompanionRecord {
        key: "Familiar (Nycar)",
        name: "Familiar (Nycar)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Dragon"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Dragon:3"),
        type_segments: &["Companion", "Familiar", "Dragon"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -6 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(1),
        source_page: Some("p.207"),
        ability_keys: &["Nycar ~ Elusive", "Nycar ~ Poison"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 29,
    },
    CompanionRecord {
        key: "Familiar (Pipefox)",
        name: "Familiar (Pipefox)",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:3"),
        type_segments: &["Companion", "Familiar", "Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -10 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: None,
        source_page: Some("p.215"),
        ability_keys: &["Comprehend Languages ~ Constant"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 30,
    },
    CompanionRecord {
        key: "Familiar (Pooka)",
        name: "Familiar (Pooka)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Fey"),
        race_subtype: None,
        monster_class: Some("Fey:4"),
        type_segments: &["Companion", "Familiar", "Fey"],
        natural_attacks: &[],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.216"),
        ability_keys: &["Pooka ~ Poison"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 31,
    },
    CompanionRecord {
        key: "Familiar (Nosoi)",
        name: "Familiar (Nosoi)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Psychopomp"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 6 }],
        natural_armor: None,
        source_page: Some("p.220"),
        ability_keys: &["Psychopomp (Nosoi) ~ Haunting Melody"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 32,
    },
    CompanionRecord {
        key: "Familiar (Ratling)",
        name: "Familiar (Ratling)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Burrow", feet: 10 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:3"),
        type_segments: &["Companion", "Familiar", "Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.226"),
        ability_keys: &["Ratling ~ Scroll Use", "Read Magic ~ Constant", "Speak with Animals (Rodents only) ~ Constant"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 33,
    },
    CompanionRecord {
        key: "Almiraj",
        name: "Almiraj",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Burrow", feet: 10 }],
        reach_feet: Some(5),
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:2"),
        type_segments: &["Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("2d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -6 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.8"),
        ability_keys: &["Almiraj ~ Hex-Prone", "Almiraj ~ Magic Horn"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 37,
    },
    CompanionRecord {
        key: "Beheaded",
        name: "Beheaded",
        size: Some("T"),
        speeds: &[Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Undead"),
        race_subtype: None,
        monster_class: Some("Undead:1"),
        type_segments: &["Undead"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }],
        natural_armor: None,
        source_page: Some("p.17"),
        ability_keys: &["Beheaded ~ Base", "Beheaded ~ Belching", "Beheaded ~ Flaming", "Beheaded ~ Grabbing", "Beheaded ~ Screaming", "Beheaded ~ Swarming"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 38,
    },
    CompanionRecord {
        key: "Isitoq",
        name: "Isitoq",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Undead"),
        race_subtype: None,
        monster_class: Some("Undead:2"),
        type_segments: &["Undead"],
        natural_attacks: &[NaturalAttack { name: "Wing", damage_dice: Some("1d1") }, NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -6 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: -4 }, StatAdjustment { ability: "WIS", amount: 4 }],
        natural_armor: None,
        source_page: Some("p.159"),
        ability_keys: &["Isitoq ~ Daze", "Isitoq ~ Tears of Anguish", "Isitoq ~ Visual Sensor"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 39,
    },
    CompanionRecord {
        key: "Drake (Shadow)",
        name: "Shadow Drake",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 90 }],
        reach_feet: Some(0),
        race_type: Some("Dragon"),
        race_subtype: Some("Cold"),
        monster_class: Some("Dragon:3"),
        type_segments: &["Dragon"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 10 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 6 }],
        natural_armor: Some(1),
        source_page: Some("p.80"),
        ability_keys: &["Drake (Shadow) ~ Shadow Blend", "Drake (Shadow) ~ Speed Surge", "Drake (Shadow) ~ Stygian Breath"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 40,
    },
    CompanionRecord {
        key: "Nycar",
        name: "Nycar",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Dragon"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Dragon:3"),
        type_segments: &["Dragon"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -6 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(1),
        source_page: Some("p.207"),
        ability_keys: &["Nycar ~ Elusive", "Nycar ~ Poison"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 41,
    },
    CompanionRecord {
        key: "Pipefox",
        name: "Pipefox",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:3"),
        type_segments: &["Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -10 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: None,
        source_page: Some("p.215"),
        ability_keys: &["Comprehend Languages ~ Constant"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 42,
    },
    CompanionRecord {
        key: "Pooka",
        name: "Pooka",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Fey"),
        race_subtype: None,
        monster_class: Some("Fey:4"),
        type_segments: &["Fey"],
        natural_attacks: &[],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.216"),
        ability_keys: &["Pooka ~ Poison"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 43,
    },
    CompanionRecord {
        key: "Psychopomp (Nosoi)",
        name: "Nosoi",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Psychopomp"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 6 }],
        natural_armor: None,
        source_page: Some("p.220"),
        ability_keys: &["Psychopomp (Nosoi) ~ Haunting Melody"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 44,
    },
    CompanionRecord {
        key: "Ratling",
        name: "Ratling",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Burrow", feet: 10 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:3"),
        type_segments: &["Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.226"),
        ability_keys: &["Ratling ~ Scroll Use", "Read Magic ~ Constant", "Speak with Animals (Rodents only) ~ Constant"],
        external_ability_refs: &[],
        source_file: "b4_races_companion.lst",
        source_line: 45,
    },
];

/// Every bestiary_4 companion ability record (44 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Dimorphodon)",
        name: "Companion Advancement (Dinosaur (Dimorphodon))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Dinosaur (Dimorphodon))"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 7,
    },
    CompanionAbilityRecord {
        key: "Comprehend Languages ~ Constant",
        name: "Comprehend Languages",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["Communicate", "SpellLike"],
        description: Some("You can comprehend languages, as per the spell, as a constant ability. Constant spell-like abilities function at all times but can be dispelled. Constant spell-like abilities can be reactivated a as a swift action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Pipefox)", "Pipefox"],
        cross_book_owners: &[],
        source_file: "b4_abilities_race_ce_companion.lst",
        source_line: 7,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Diplodocus)",
        name: "Companion Advancement (Dinosaur (Diplodocus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 2 }],
        source_page: None,
        owners: &["Companion (Dinosaur (Diplodocus))"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 8,
    },
    CompanionAbilityRecord {
        key: "Read Magic ~ Constant",
        name: "Read Magic",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["SpecialQuality", "SpellLike"],
        description: Some("You can read magic, as per the spell, as a constant ability. Constant spell-like abilities function at all times but can be dispelled. Constant spell-like abilities can be reactivated a as a swift action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Ratling)", "Ratling"],
        cross_book_owners: &[],
        source_file: "b4_abilities_race_ce_companion.lst",
        source_line: 8,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Styracosaurus)",
        name: "Companion Advancement (Dinosaur (Styracosaurus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Styracosaurus))"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 9,
    },
    CompanionAbilityRecord {
        key: "Speak with Animals (Rodents only) ~ Constant",
        name: "Speak with Animals (rodents only)",
        facet: None,
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["Communicate", "SpellLike"],
        description: Some("You can use speak with animals, as per the spell, as a constant ability, but only to speak with rodents. Constant spell-like abilities function at all times but can be dispelled. Constant spell-like abilities can be reactivated as a swift action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Ratling)", "Ratling"],
        cross_book_owners: &[],
        source_file: "b4_abilities_race_ce_companion.lst",
        source_line: 9,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Giraffe",
        name: "Companion Advancement (Giraffe)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }],
        source_page: None,
        owners: &["Companion (Giraffe)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 10,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Stag",
        name: "Companion Advancement (Stag)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }],
        source_page: None,
        owners: &["Companion (Stag)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 11,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Seahorse",
        name: "Companion Advancement (Seahorse)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Seahorse)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 12,
    },
    CompanionAbilityRecord {
        key: "Grab ~ Medium",
        name: "Grab",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary", "AttackOption"],
        description: Some("If you hit with the indicated attack (usually a claw or bite attack), you deal normal damage and can attempt to start a grapple as a free action without provoking an attack of opportunity. You have the option to conduct the grapple normally, or simply use the part of your body you used in the grab to hold the opponent. If you choose to do the latter, you takes a -20 penalty on your CMB check to make and maintain the grapple, but do not gain the grappled condition itself. A successful hold does not deal any extra damage unless you also have the constrict special attack. If you do not constrict, each successful grapple check you make during successive rounds automatically deals the damage indicated for the attack that established the hold. Otherwise, you deal constriction damage as well. You receive a +4 bonus on combat maneuver checks made to start and maintain a grapple. Unless otherwise noted, grab can only be used on creatures of size Medium or smaller."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.301"),
        owners: &["Companion (Weasel (Giant))"],
        cross_book_owners: &[],
        source_file: "b4_abilities_race_ce_companion.lst",
        source_line: 12,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Tortoise",
        name: "Companion Advancement (Tortoise)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "CON", amount: -2 }],
        source_page: None,
        owners: &["Companion (Tortoise)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 13,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Trumpeter Swan",
        name: "Companion Advancement (Trumpeter Swan)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Trumpeter Swan)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 14,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Weasel (Giant)",
        name: "Companion Advancement (Weasel (Giant))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Weasel (Giant))"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 15,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Walrus",
        name: "Companion Advancement (Walrus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Walrus)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 16,
    },
    CompanionAbilityRecord {
        key: "Companion (Dinosaur (Dimorphodon)) ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Bite-injury; save Fort DC %1; frequency 1/round for 6 rounds; effect 1 Str; cure 1 save."),
        description_variables: &["10+HD/2+CON"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Dimorphodon))"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 19,
    },
    CompanionAbilityRecord {
        key: "Companion (Dinosaur (Diplodocus)) ~ Tail Lash",
        name: "Tail Lash",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("The diplodocus prefers to attack with its tail. The dinosaur can snap its incredibly long tail with surprising speed like an enormous whip-this is a primary attack that deals bludgeoning and slashing damage. A diplodocus can make two separate attacks with its tail lash as a full-attack action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Diplodocus))"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 21,
    },
    CompanionAbilityRecord {
        key: "Companion (Dinosaur (Styracosaurus)) ~ Reflexive Strike",
        name: "Reflexive Strike",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("A styracosaurus can make three additional attacks of opportunity each round-combined with its bonus Combat Reflexes feat, this allows the dinosaur to make up to five of these attacks of opportunity per round. The dinosaur makes these attacks with its horned crest, but they are treated as normal gore attacks."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Styracosaurus))"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 23,
    },
    CompanionAbilityRecord {
        key: "Companion (Giraffe) ~ Natural Weapons",
        name: "Natural Weapons",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("A giraffe's hoof attacks are primary attacks and its slam attack is a secondary attack."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Giraffe)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 25,
    },
    CompanionAbilityRecord {
        key: "Companion (Seahorse) ~ Anchor",
        name: "Anchor",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("As a move action, a seahorse can wrap its tail around a stationary object. The seahorse remains anchored to the object until it releases its grip (a free action) or is forcibly moved. An anchored seahorse gains a +4 bonus to its combat maneuver defense and on checks and saving throws against effects that would move it against its will."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Seahorse)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 27,
    },
    CompanionAbilityRecord {
        key: "Archaeopteryx ~ Weak Flier",
        name: "Weak Flier",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("An archaeopteryx can't hover or fly up at an angle greater than 45 degrees while flying. Archaeopteryxes are primitive birds. Instead of beaks, they have lizardlike heads with serrated teeth."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Archaeopteryx)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 37,
    },
    CompanionAbilityRecord {
        key: "Platypus ~ Electrolocation",
        name: "Electrolocation",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary", "Senses"],
        description: Some("While underwater, platypuses can sense the tiny electrical currents that trigger muscle movement. This allows them to locate living prey and to distinguish it from inanimate objects. Treat electrolocation as lifesense with a range of 30 feet, but that functions only underwater."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Platypus)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 40,
    },
    CompanionAbilityRecord {
        key: "Platypus ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Spur-injury; save Fort DC 9; frequency 1/round for 4 rounds; effect 1 nonlethal damage; cure 1 save."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Platypus)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 41,
    },
    CompanionAbilityRecord {
        key: "Platypus ~ Semiaquatic",
        name: "Semiaquatic",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("Platypuses can hold their breath underwater for up to 5 minutes before they must start attempting Constitution checks to avoid suffocation."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Platypus)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 42,
    },
    CompanionAbilityRecord {
        key: "Almiraj ~ Hex-Prone",
        name: "Hex-Prone",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialQuality", "Supernatural"],
        description: Some("An almiraj takes a -2 penalty on all saving throws against harmful witch hexes. The duration of any beneficial hexes longer than 1 round that affect an almiraj is increased by 50%%."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Almiraj)", "Almiraj"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 67,
    },
    CompanionAbilityRecord {
        key: "Almiraj ~ Magic Horn",
        name: "Magic Horn",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Supernatural"],
        description: Some("While on the creature's head, an almiraj's horn is treated as a +1 weapon. Any living creature slain by an almiraj's gore attack immediately turns to stone (as if by the flesh to stone spell, with no saving throw, and the creature is still dead). A severed almiraj horn retains a wisp of its former magic, and counts as a masterwork weapon if used to create a magical dagger or similar small piercing weapon."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Almiraj)", "Almiraj"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 68,
    },
    CompanionAbilityRecord {
        key: "Beheaded ~ Base",
        name: "Base Beheaded",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: None,
        type_segments: &["SpecialQuality"],
        description: Some("A neutral evil spellcaster can gain a beheaded as a familiar at 3rd level by taking the Improved Familiar feat. A beheaded familiar loses the mindless trait and has an Intelligence score appropriate for its master's level. A variant beheaded counts as an additional Hit Die toward the maximum Hit Dice of controlled undead."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Beheaded)", "Beheaded"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 71,
    },
    CompanionAbilityRecord {
        key: "Beheaded ~ Belching",
        name: "Belching",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Supernatural"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Beheaded)", "Beheaded"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 72,
    },
    CompanionAbilityRecord {
        key: "Beheaded ~ Flaming",
        name: "Flaming",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Supernatural"],
        description: Some("The beheaded gains fire immunity and a +2 bonus to Charisma. Its slam attack also deals 1d6 points of fire damage and might catch the target on fire (Core Rulebook p.444)"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Beheaded)", "Beheaded"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 73,
    },
    CompanionAbilityRecord {
        key: "Beheaded ~ Grabbing",
        name: "Grabbing",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("This type of beheaded has long tendrils of ragged hair or other limblike growths (such as a medusa's snake hair). Its slam attack gains the grab (Medium) special ability."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Beheaded)", "Beheaded"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 74,
    },
    CompanionAbilityRecord {
        key: "Beheaded ~ Screaming",
        name: "Screaming",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Supernatural"],
        description: Some("This type of beheaded can scream out once every 1d4 rounds. Every creature within 30 feet must succeed at a Will save or be shaken for 1d4 rounds. The save DC is equal to 10 + 1/2 the screaming skull's racial Hit Dice + the screaming skull's Charisma modifier. This is a sonic mind-affecting fear effect. Whether or not the save is successful, any creature in the area can't be affected by that beheaded's scream for the next 24 hours."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Beheaded)", "Beheaded"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 75,
    },
    CompanionAbilityRecord {
        key: "Beheaded ~ Swarming",
        name: "Swarming",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("The beheaded gains 1 additional Hit Die, the swarm subtype, swarm immunities, and the distraction special ability. It loses its slam attack but gains a swarm attack that deals 1d6 points of damage. This counts as two abilities for the purpose of determining the beheaded's CR."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Beheaded)", "Beheaded"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 76,
    },
    CompanionAbilityRecord {
        key: "Drake (Shadow) ~ Shadow Blend",
        name: "Shadow Blend",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["Supernatural", "SpecialQuality"],
        description: Some("In conditions of illumination other than bright light, a shadow drake disappears into the shadows, giving it concealment (20%% miss chance). It can resume or suspend this ability as a free action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Drake (Shadow)", "Familiar (Shadow Drake)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 79,
    },
    CompanionAbilityRecord {
        key: "Drake (Shadow) ~ Speed Surge",
        name: "Speed Surge",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["Extraordinary", "SpecialAttack"],
        description: Some("Three times per day as a swift action, a shadow drake may draw on its draconic heritage for a boost of strength and speed to take an additional move action in that round."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Drake (Shadow)", "Familiar (Shadow Drake)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 80,
    },
    CompanionAbilityRecord {
        key: "Drake (Shadow) ~ Stygian Breath",
        name: "Stygian Breath",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["Supernatural", "SpecialAttack"],
        description: Some("As a standard action, a shadow drake can exhale a ball of black liquid that explodes into a cloud of frigid black mist. This attack has a range of 60 feet and deals 2d6 points of cold damage (Reflex DC %1 half) to all creatures within a 5-foot-radius spread. The mist snuffs out light sources in the area effect, extinguishing nonmagical light sources and dispelling light spells of 1st level or lower. Once a shadow drake has used its stygian breath, it cannot do so again for 1d6 rounds."),
        description_variables: &["11+CON"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Drake (Shadow)", "Familiar (Shadow Drake)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 81,
    },
    CompanionAbilityRecord {
        key: "Flea (Giant) ~ Disease",
        name: "Disease",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Bite-injury; save Fort DC %1; onset 1d3 days; frequency 1 day; effect 1 Con damage; cure 1 save."),
        description_variables: &["10+CON"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Giant Flea)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 84,
    },
    CompanionAbilityRecord {
        key: "Flea (Giant) ~ Uncanny Leap",
        name: "Uncanny Leap",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("As a full-round action, a giant flea can jump up to 120 feet. A flea can treat this jump as a charge, as long as the leap is made in a straight line."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Giant Flea)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 85,
    },
    CompanionAbilityRecord {
        key: "Isitoq ~ Daze",
        name: "Daze",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("An isitoq's nerves form grotesque wings. Any creature struck by the creature's wings must succeed at a DC %1 Will save or be dazed for 1 round as the target's mind is flooded with images of the last seconds of the isitoq's existence as a living creature. This is a mind-affecting fear effect."),
        description_variables: &["11+CHA"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Isitoq)", "Isitoq"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 88,
    },
    CompanionAbilityRecord {
        key: "Isitoq ~ Tears of Anguish",
        name: "Tears of Anguish",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Supernatural"],
        description: Some("As a full-round action, an isitoq can make a ranged touch attack to squirt tears into the eyes of a creature within 30 feet. If the target fails a DC %1 saving throw, it experiences the effect of the isitoq's daze ability."),
        description_variables: &["11+CHA"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Isitoq)", "Isitoq"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 89,
    },
    CompanionAbilityRecord {
        key: "Isitoq ~ Visual Sensor",
        name: "Visual Sensor",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialQuality", "Supernatural"],
        description: Some("An isitoq's creator or master can see through its eye at a range of 60 feet, using the eye's normal vision and darkvision. The following spells have a 5%% chance per caster level of the isitoq's creator of operating through the isitoq: detect chaos, detect evil, detect good, detect law, detect magic, and message. If the creator is 15th level or higher, the following spells have the same chance of functioning through the isitoq: read magic and tongues."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Isitoq)", "Isitoq"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 90,
    },
    CompanionAbilityRecord {
        key: "Nycar ~ Elusive",
        name: "Elusive",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("A nycar can make an Escape Artist check as a swift action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Nycar)", "Nycar"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 93,
    },
    CompanionAbilityRecord {
        key: "Nycar ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Bite-injury; save Fort DC 12; frequency 1/round for 6 rounds; effect 1d4 acid and 1 Con damage; cure 2 consecutive saves."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Nycar)", "Nycar"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 94,
    },
    CompanionAbilityRecord {
        key: "Pooka ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Supernatural"],
        description: Some("As a standard action, a pooka can blow across her palm and create a 5-foot-diameter cloud of intoxicating dust. The pooka decides when she uses this ability whether the dust acts as an inhaled poison or a mild intoxicant (equivalent to 1-2 glasses of beer). [Pooka Dust] Inhaled; save Fort DC 13; frequency 1/round for 6 rounds; effect 1d2 Wis and 1d2 Cha (or intoxication); cure 2 consecutive saves."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Pooka)", "Pooka"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 100,
    },
    CompanionAbilityRecord {
        key: "Psychopomp (Nosoi) ~ Haunting Melody",
        name: "Haunting Melody",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Supernatural"],
        description: Some("A nosoi's song has the power to grip the spirits of those that hear it. All living and undead creatures within a 60-foot spread must succeed at a DC %1 Will saving throw or be fascinated. A creature that successfully saves is not subject to that nosoi's song for 24 hours. This effect continues for as long as the nosoi sings and for 1 round thereafter. A nosoi can sing for a number or rounds per day equal to twice its Hit Dice. This is a sonic mind-affecting charm effect. This ability can affect undead creatures, even though the undead subtype makes such creatures immune to mind-affecting effects (though undead creatures with immunity to mind-affecting effects from a source other than their creature type are still immune)."),
        description_variables: &["11+CHA"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Psychopomp (Nosoi)", "Familiar (Nosoi)"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 104,
    },
    CompanionAbilityRecord {
        key: "Ratling ~ Scroll Use",
        name: "Scroll Use",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("A ratling can cast spells from any magic scroll as if it had the spell on its spell list."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Familiar (Ratling)", "Ratling"],
        cross_book_owners: &[],
        source_file: "b4_abilities_companion.lst",
        source_line: 107,
    },
];
