//! book_of_the_damned_volume_1 monster + monster-ability tables, transcribed verbatim
//! from the book's own PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_monster_tables.py book_of_the_damned_volume_1`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst` (which counts `.MOD`/`.COPY` overlays the
//! inventory correctly excludes).
//!
//! Sources, with the line each record was read from carried per row:
//!   * `botd1_races.lst` -- 5 monster rows
//!   * `botd1_abilities_race.lst` -- 36 monster-ability rows

use crate::rules_core::rules_tables::monster_chassis::{MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterStatBlock, NaturalAttack, Speed, StatAdjustment};

/// Every book_of_the_damned_volume_1 monster stat block (5 rows).
pub(super) static MONSTERS: &[MonsterStatBlock] = &[
    MonsterStatBlock {
        key: "Devil (Apostate)",
        name: "Devil, Apostate (Deimavigga)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Devil|Evil|Extraplanar|Lawful"),
        challenge_rating: Some("17"),
        monster_class: Some("Outsider (Fort/Will):18"),
        source_page: Some("p.54"),
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: None }],
        ability_keys: &["Apostate Devil ~ Boundless Reach", "Apostate Devil ~ Evangelization", "Apostate Devil ~ Indomitable Oration", "Apostate Devil ~ Malleable Form", "Apostate Devil ~ Ohrwurm", "Apostate Devil ~ Spell-Like Abilities", "Apostate Devil ~ Summon Devil", "Apostate Devil ~ Wisdom Drain"],
        external_ability_refs: &["Flight Maneuverability", "Regeneration"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 18 }, StatAdjustment { ability: "DEX", amount: 20 }, StatAdjustment { ability: "CON", amount: 18 }, StatAdjustment { ability: "INT", amount: 10 }, StatAdjustment { ability: "WIS", amount: 14 }, StatAdjustment { ability: "CHA", amount: 18 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "botd1_races.lst",
        source_line: 9,
    },
    MonsterStatBlock {
        key: "Devil (Heresy)",
        name: "Devil, Heresy (Ayngavhaul)",
        size: Some("H"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 40 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Devil|Evil|Extraplanar|Lawful"),
        challenge_rating: Some("12"),
        monster_class: Some("Outsider (Fort/Will):13"),
        source_page: Some("p.56"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Slam", damage_dice: None }],
        ability_keys: &["Heresy Devil ~ Blasphemous Bile", "Heresy Devil ~ Corpulence", "Heresy Devil ~ Devil Summoner", "Heresy Devil ~ Searing Word", "Heresy Devil ~ Spell-Like Abilities", "Heresy Devil ~ Summon Devil", "Heresy Devil ~ Throne of Skulls"],
        external_ability_refs: &["Fast Healing", "Flight Maneuverability"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 14 }, StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "CON", amount: 14 }, StatAdjustment { ability: "INT", amount: 12 }, StatAdjustment { ability: "WIS", amount: 10 }, StatAdjustment { ability: "CHA", amount: 10 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "botd1_races.lst",
        source_line: 10,
    },
    MonsterStatBlock {
        key: "Devil (Lesser Host)",
        name: "Devil, Lesser Host (Gaav)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Fly", feet: 60 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Devil|Evil|Extraplanar|Lawful"),
        challenge_rating: Some("3"),
        monster_class: Some("Outsider (Fort/Ref):4"),
        source_page: Some("p.58"),
        natural_attacks: &[],
        ability_keys: &["Lesser Host Devil ~ Noxious Breath", "Lesser Host Devil ~ Shared Senses", "Lesser Host Devil ~ Spell-Like Abilities", "Lesser Host Devil ~ Summon Devil", "Lesser Host Devil ~ Superior Grappler", "Lesser Host Devil ~ Swarming"],
        external_ability_refs: &["Flight Maneuverability"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }, StatAdjustment { ability: "WIS", amount: -2 }, StatAdjustment { ability: "CHA", amount: -2 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "botd1_races.lst",
        source_line: 11,
    },
    MonsterStatBlock {
        key: "Devil (Greater Host)",
        name: "Devil, Greater Host (Magaav)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Devil|Evil|Extraplanar|Lawful"),
        challenge_rating: Some("6"),
        monster_class: Some("Outsider (Fort/Ref):7"),
        source_page: Some("p.58"),
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: Some("2d4") }],
        ability_keys: &["Greater Host Devil ~ Infernal Wound", "Greater Host Devil ~ Master Grappler", "Greater Host Devil ~ Noxious Breath", "Greater Host Devil ~ Rend", "Greater Host Devil ~ Shared Senses", "Greater Host Devil ~ Spell-Like Abilities", "Greater Host Devil ~ Summon Devil"],
        external_ability_refs: &["Flight Maneuverability"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 8 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "WIS", amount: 2 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "botd1_races.lst",
        source_line: 12,
    },
    MonsterStatBlock {
        key: "Devil (Warmonger)",
        name: "Devil, Warmonger (Levaloch)",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Climb", feet: 40 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Devil|Evil|Extraplanar|Lawful"),
        challenge_rating: Some("7"),
        monster_class: Some("Outsider (Fort/Ref):8"),
        source_page: Some("p.60"),
        natural_attacks: &[NaturalAttack { name: "Leg", damage_dice: Some("1d8") }, NaturalAttack { name: "Claw", damage_dice: None }],
        ability_keys: &["Warmonger Devil ~ Construct Form", "Warmonger Devil ~ Hellstrider", "Warmonger Devil ~ Merciless Blow", "Warmonger Devil ~ Phalanx", "Warmonger Devil ~ Skills", "Warmonger Devil ~ Spell-Like Abilities", "Warmonger Devil ~ Stability", "Warmonger Devil ~ Summon Devil"],
        external_ability_refs: &["Warmonger Devil ~ Trample"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 10 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 8 }, StatAdjustment { ability: "INT", amount: 4 }, StatAdjustment { ability: "WIS", amount: 6 }, StatAdjustment { ability: "CHA", amount: 4 }],
        has_spell_like_abilities: false,
        sla_cl_token: None,
        spell_like_abilities: &[],
        source_file: "botd1_races.lst",
        source_line: 13,
    },
];

/// Every book_of_the_damned_volume_1 monster-ability record (36 rows).
pub(super) static MONSTER_ABILITIES: &[MonsterAbilityRecord] = &[
    MonsterAbilityRecord {
        key: "Apostate Devil ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &[],
        description: None,
        description_variables: &[],
        source_page: Some("p.54"),
        owners: &["Devil (Apostate)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 8,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Apostate Devil ~ Boundless Reach",
        name: "Boundless Reach",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A deimavigga's claws slice through reality, allowing it to make melee attacks against any creature it is aware of-typically meaning creatures within 100 feet. The devil still only threatens the 10-foot area around it and it cannot make attacks of opportunity against creatures farther away. This ability can span vast distances, allowing a deimavigga making use of divination magic to detect distant creatures and attack foes separated by miles or even planes. Spells like forbiddance, which prevent planar travel, also protect against a deimavigga's claws. The spell dimensional anchor also prevents a deimavigga from using this ability for the duration of that spell. An attacked creature can retaliate that round, striking at the devil's claws with weapons or spells as if its entire body were present, but cannot grapple or otherwise prevent the claws from vanishing out of reach at the end of the round."),
        description_variables: &[],
        source_page: Some("p.54"),
        owners: &["Devil (Apostate)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 9,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Apostate Devil ~ Evangelization",
        name: "Evangelization",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The words of deimaviggas are poison to the mind. Every round a deimavigga speaks (a free action), all non-devils with an Intelligence score of 3 or higher within 30 feet must make a DC %1 Will save or become vulnerable to its blasphemous discourse. The DC of this Will save increases by +1 for each consecutive round a creature has listened to the same deimavigga speak. Creatures must be listening to a deimavigga to be affected by its oration. Deafened creatures and those in combat-either with the deimavigga or other creatures-are not considered to be listening. Victims cannot simply declare they are not listening without taking steps to impede their hearing. Upon failing this save, a victim can be affected by the heretical power of a deimavigga's words. The devil may use its speech to affect a listener in ways that mimic any of the following spells: calm emotions (DC %2), charm monster (DC %3), command (DC %4), confusion (DC %5), crushing despair (DC %6), deep slumber (DC %7), enthrall (DC %8), modify memory (DC %9), rage (DC %10), or suggestion (DC %11). Victims still receive saving throws against these spell effects, but if they fail their saves they are not aware the devil is working its power upon them. A deimavigga can affect multiple victims with different spell effects in the same round. A creature that makes its save against this ability is immune to that particular devil's evangelization for the next 24 hours. This is a sonic mind-affecting effect. The base save DC is Charisma-based."),
        description_variables: &["Evangelization_DC", "DC_Calm_Emotions", "DC_charm_monster", "DC_command", "DC_confusion", "DC_crushing_despair", "DC_deep_slumber", "DC_enthrall", "DC_modify_memory", "DC_rage", "DC_suggestion"],
        source_page: Some("p.54"),
        owners: &["Devil (Apostate)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 10,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Apostate Devil ~ Indomitable Oration",
        name: "Indomitable Oration",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A deimavigga's speech is always perfectly clear and cannot be silenced or warped. In areas of incredible noise, through water or airless voids, even in areas of magical silence, these devil's voices can still be heard normally. All beings understand deimaviggas, as if these devils constantly spoke in all tongues at once."),
        description_variables: &[],
        source_page: Some("p.54"),
        owners: &["Devil (Apostate)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 11,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Apostate Devil ~ Malleable Form",
        name: "Malleable Form",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A deimavigga has complete control over its physical form, and if transformed into another shape against its will, it can revert to its own form as a free action."),
        description_variables: &[],
        source_page: Some("p.54"),
        owners: &["Devil (Apostate)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 12,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Apostate Devil ~ Ohrwurm",
        name: "Ohrwurm",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("As a standard action, three times per day, a deimavigga can whisper a fundamental and terrifying multiversal truth to one creature within 5 feet. The target must make a DC 28 Will save or have the devil's words take root in its psyche. Outsiders and elementals have a +2 bonus on their saves to resist this ability. Initially, the deimavigga's words seem to have no effect. Anytime the victim tries to rest, though, he must make an additional DC %1 Will save or be affected as per the spell nightmare (even if the victim doesn't technically sleep). After a night of suffering vivid dreams and wrestling with the devil's words, the victim must make yet another DC 28 Will save or have its alignment shift one step toward lawful evil. Only by unlearning what the deimavigga told it can a victim be free of this effect, requiring a spell such as miracle, modify memory, or wish."),
        description_variables: &["Ohrwurm_DC"],
        source_page: Some("p.54"),
        owners: &["Devil (Apostate)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 13,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Apostate Devil ~ Summon Devil",
        name: "Summon Devil",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &[],
        description: Some("Once per day a deimavigga can attempt to summon 1d6 osyluths or 2d4 barbazu with a 50%% chance of success, or 1 gelugon with a 20%% chance of success. This ability is the equivalent of an 8th-level spell."),
        description_variables: &[],
        source_page: Some("p.55"),
        owners: &["Devil (Apostate)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 14,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Apostate Devil ~ Wisdom Drain",
        name: "Wisdom Drain",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A deimavigga drains 1d6 points of Wisdom each time it hits with its claw attack. (A deimavigga does not heal any damage when it uses its Wisdom drain.)"),
        description_variables: &[],
        source_page: Some("p.55"),
        owners: &["Devil (Apostate)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 15,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Heresy Devil ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: None,
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &["Devil (Heresy)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 19,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Heresy Devil ~ Corpulence",
        name: "Corpulence",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Ayngavhauls are greasy and grossly obese. This extraordinary bulk provides them with a +10 bonus on their combat maneuver defense."),
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &["Devil (Heresy)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 20,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Heresy Devil ~ Blasphemous Bile",
        name: "Blasphemous Bile",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("30-ft. line, once every 1d4 hours; damage 4d6 acid, Reflex DC 23 half. Those struck by this bile find themselves drenched in liquid corruption so profound it impedes the power of non-evil divine magic for 10 minutes. Any non-evil divine spellcaster who casts a spell targeting a creature soaked in an ayngavhaul's bile must make a DC 23 caster level check or have the spell fail. A creature affected by this bile may wash off the sludge by spending a round and using at least a gallon of fluid to cleanse itself. The save DC is Constitution-based."),
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &["Devil (Heresy)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 21,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Heresy Devil ~ Devil Summoner",
        name: "Devil Summoner",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Ayngavhauls know the secrets of all breeds of devils, utilizing such leverage in the summoning of their kind. Any devil within 30 feet of an ayngavhaul has half again the normal chance of having a fiend respond to its summon devil ability. For example, an osyluth's usual 35%% chance to summon another bone devil increases to 52%% when within 30 feet of an ayngavhaul. Summoning bonuses provided by multiple ayngavahuls do not stack. Ayngavahuls are immune to this ability, from both themselves and others of their kind."),
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &["Devil (Heresy)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 22,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Heresy Devil ~ Searing Word",
        name: "Searing Word",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("An ayngavhaul can speak words of torment, giving them shape and sending them streaking toward their enemies in the form of diabolical sigils. Any good-aligned creature struck by one of these infernal words takes 3d6 points of hellfire damage (half fire, half evil energy); nongood creatures take half damage. These words cannot affect creatures affected by protection from evil or within an area of magical silence. [+10 to Hit]"),
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &["Devil (Heresy)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 23,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Heresy Devil ~ Summon Devil",
        name: "Summon Devil",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &[],
        description: Some("Once per day an ayngavhaul can attempt to summon 2d6 imps, 1d4 bearded devils, or 2 bone devils with an 80%% chance of success, or a contract devil (see Pathfinder Adventure Path volume #12) with a 45%% chance of success. This ability is the equivalent of a 6th-level spell."),
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &["Devil (Heresy)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 24,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Heresy Devil ~ Throne of Skulls",
        name: "Throne of Skulls",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("All ayngavhauls hover upon fearsome infernal thrones. These thrones grant the devils their fly speed and a +4 armor bonus. Should an ayngavhaul be grappled or knocked down, it is unseated from its throne and loses these benefits. An ayngavhaul has telepathic command over its throne and may call its conveyance back and reseat itself as a full-round action."),
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &["Devil (Heresy)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 25,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Lesser Host Devil ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: None,
        description_variables: &[],
        source_page: Some("p.58"),
        owners: &["Devil (Lesser Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 28,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Lesser Host Devil ~ Superior Grappler",
        name: "Superior Grappler",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A gaav can wield a weapon and still make grapple checks. If it's not wielding a weapon, a gaav gains a +4 bonus on grapple checks. In addition, it takes up to eight gaavs cooperatively to lift a creature that one or more of them is grappling; each gaav can lift up to 50 pounds and still fly without being impeded."),
        description_variables: &[],
        source_page: Some("p.58"),
        owners: &["Devil (Lesser Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 29,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Lesser Host Devil ~ Noxious Breath",
        name: "Noxious Breath",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Three times per day, a gaav can exhale a breath that reeks of pure corruption upon a creature within 5 feet. The target must make a DC %1 Fortitude save or be sickened for 1d4 rounds. The save DC is Constitution-based. Creatures that successfully save cannot be affected by the same gaav's noxious breath for 24 hours. A delay poison or neutralize poison spell removes the effect from the sickened creature. Creatures with immunity to poison are unaffected, and creatures resistant to poison receive their normal bonus on their saving throws. Once a gaav uses its breath weapon, it can't breathe again until 1d4 rounds later."),
        description_variables: &["NoxiousBreathDC"],
        source_page: Some("p.58"),
        owners: &["Devil (Lesser Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 30,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Lesser Host Devil ~ Shared Senses",
        name: "Shared Senses",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("All gaavs and magaavs within 100 feet of one another share the same senses. Thus, if one individual perceives something (for example, with a successful Perception check), all others within range are immediately aware of it. Senses are instantly relayed from one gaav or magaav to the next, allowing for the senses of a single devil to potentially spread through and inform an entire massive swarm instantly. It is still possible for a gaav to be surprised or flat-footed even if other gaavs nearby are not."),
        description_variables: &[],
        source_page: Some("p.58"),
        owners: &["Devil (Lesser Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 31,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Lesser Host Devil ~ Summon Devil",
        name: "Summon Devil",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Once per day a gaav can attempt to summon an imp with a 35%% chance of success. This ability is the equivalent of a 3rd-level spell."),
        description_variables: &[],
        source_page: Some("p.58"),
        owners: &["Devil (Lesser Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 32,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Lesser Host Devil ~ Swarming",
        name: "Swarming",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Up to two gaavs can share the same space at the same time. If two gaavs in the same square attack the same foe, they are considered to be flanking that foe as if they were in two opposite squares."),
        description_variables: &[],
        source_page: Some("p.58"),
        owners: &["Devil (Lesser Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 33,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Greater Host Devil ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: None,
        description_variables: &[],
        source_page: Some("p.59"),
        owners: &["Devil (Greater Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 36,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Greater Host Devil ~ Infernal Wound",
        name: "Infernal Wound",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The damage a magaav deals with its claws or rend causes a persistent wound. An injured creature loses 1 additional hit point each round. The wound does not heal naturally and resists healing spells. The continuing hit point loss can be stopped by a DC 16 Heal check or any spell that cures hit point damage; casting a curative spell on the injured creature requires a successful DC 15 caster level check, otherwise the spell has no effect. The check DC is Constitution-based."),
        description_variables: &[],
        source_page: Some("p.59"),
        owners: &["Devil (Greater Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 37,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Greater Host Devil ~ Master Grappler",
        name: "Master Grappler",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A magaav can wield a weapon and still make grapple checks. If it's not wielding a weapon, a magaav gains a +4 bonus on grapple checks. Noxious Breath (Su) Three times per day, a magaav can exhale a breath that reeks of pure corruption upon a creature within 5 feet. The target must make a DC 16 Fortitude save or be sickened for 1d4 rounds. The save DC is Constitutionbased. Creatures that successfully save cannot be affected by the same magaav's noxious breath for 24 hours. A delay poison or neutralize poison spell removes the effect from the sickened creature. Creatures with immunity to poison are unaffected, and creatures resistant to poison receive their normal bonuses on their saving throws. Once a magaav uses its breath weapon, it can't breathe again until 1d4 rounds later."),
        description_variables: &[],
        source_page: Some("p.59"),
        owners: &["Devil (Greater Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 38,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Greater Host Devil ~ Shared Senses",
        name: "Shared Senses",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("All gaavs (and magaavs) within 100 feet of one another share the same senses. Thus, if one individual perceives something (for example, with a successful Perception check), all others within range are immediately aware of it. Senses are instantly relayed from one gaav or magaav to the next, allowing for the senses of a single devil to potentially spread through and inform an entire massive swarm instantly. It is still possible for a magaav to be surprised or flat-footed even if other gaavs or magaavs nearby are not. All magaavs may telepathically communicate with all other gaavs and magaavs within 100 feet at once, allowing the greater host devils to command entire swarms. Although magaavs rarely contradict one another, if faced with competing orders, gaavs follow the commands of the closest magaav."),
        description_variables: &[],
        source_page: Some("p.59"),
        owners: &["Devil (Greater Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 39,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Greater Host Devil ~ Summon Devil",
        name: "Summon Devil",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Once per day a magaav can attempt to summon 1d2 gaavs with a 60%% chance of success. This ability is the equivalent of a 3rd-level spell."),
        description_variables: &[],
        source_page: Some("p.59"),
        owners: &["Devil (Greater Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 40,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Greater Host Devil ~ Noxious Breath",
        name: "Noxious Breath",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Three times per day, a Magaav can exhale a breath that reeks of pure corruption upon a creature within 5 feet. The target must make a DC %1 Fortitude save or be sickened for 1d4 rounds. The save DC is Constitution-based. Creatures that successfully save cannot be affected by the same gaav's noxious breath for 24 hours. A delay poison or neutralize poison spell removes the effect from the sickened creature. Creatures with immunity to poison are unaffected, and creatures resistant to poison receive their normal bonus on their saving throws. Once a gaav uses its breath weapon, it can't breathe again until 1d4 rounds later."),
        description_variables: &["NoxiousBreathDC"],
        source_page: Some("p.59"),
        owners: &["Devil (Greater Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 41,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Greater Host Devil ~ Rend",
        name: "Rend",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: None,
        traits: &[],
        description: Some("2 Claws, 1d6+1"),
        description_variables: &[],
        source_page: Some("p.59"),
        owners: &["Devil (Greater Host)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 42,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Warmonger Devil ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: None,
        description_variables: &[],
        source_page: Some("p.60"),
        owners: &["Devil (Warmonger)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 45,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Warmonger Devil ~ Construct Form",
        name: "Construct Form",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: Some("Despite being true devils, levalochs possess a number of immunities common to constructs, including immunity to ability damage, ability drain, death effects, death from massive damage, disease, energy drain, exhaustion, fatigue, necromancy effects, nonlethal damage, paralysis, sleep effects, and stunning. Upon being reduced to 0 hit points, they are immediately destroyed."),
        description_variables: &[],
        source_page: Some("p.60"),
        owners: &["Devil (Warmonger)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 47,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Warmonger Devil ~ Hellstrider",
        name: "Hellstrider",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A levaloch is not impeded by rough terrain, and can move or charge through such squares as normal. It can also cross areas covered with deadly impediments (such as caltrops or thorns) without being damaged or hindered. In addition to being entirely immune to fire, the creature's legs are immune to acid and cold, allowing it to cross even rivers of acid or lava without being damaged or hindered as long as the material is less than 4 feet deep. This ability does not protect a levaloch against magical hindrances like black tentacles, web, or similar spells."),
        description_variables: &[],
        source_page: Some("p.60"),
        owners: &["Devil (Warmonger)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 48,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Warmonger Devil ~ Merciless Blow",
        name: "Merciless Blow",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Levalochs show no mercy to the vulnerable. Any trident attacks they make against entangled creatures (including those entangled by its net) deal an extra 2d6 points damage."),
        description_variables: &[],
        source_page: Some("p.60"),
        owners: &["Devil (Warmonger)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 49,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Warmonger Devil ~ Phalanx",
        name: "Phalanx",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Devils gain a +1 morale bonus on attacks and to AC while adjacent to a levaloch."),
        description_variables: &[],
        source_page: Some("p.60"),
        owners: &["Devil (Warmonger)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 50,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Warmonger Devil ~ Stability",
        name: "Stability",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Levalochs receive a +4 racial bonus to their CMD when resisting a bull rush or trip attempt while standing on the ground."),
        description_variables: &[],
        source_page: None,
        owners: &["Devil (Warmonger)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 51,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Warmonger Devil ~ Summon Devil",
        name: "Summon Devil",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::SpellLike),
        traits: &[],
        description: Some("Once per day a levaloch can attempt to summon 1d4 lemures or 1 bearded devil with a 40%% chance of success. This ability is the equivalent of a 4th-level spell."),
        description_variables: &[],
        source_page: Some("p.60"),
        owners: &["Devil (Warmonger)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 52,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Warmonger Devil ~ Skills",
        name: "Skills",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: Some("Levalochs have a +2 racial bonus on Stealth and Perception checks. This Stealth bonus increases to +8 when a levaloch is concealed amid metal objects or debris."),
        description_variables: &[],
        source_page: Some("p.60"),
        owners: &["Devil (Warmonger)"],
        source_file: "botd1_abilities_race.lst",
        source_line: 53,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
];
