//! Book of the Damned, Volume 1 shared spell list.
//!
//! Generated by `src/bin/ingest_spells.rs` (config-driven, all
//! books) from the real `pathfinder/paizo/campaign_setting/book_of_the_damned_volume_1/botd1_spells.lst` corpus. Record coverage: every
//! real, active (non-`.MOD`) base spell declaration, PLUS every
//! `.COPY=` variant declared in this book (its own new identity is
//! the name after `.COPY=`; `level`/`school` inherit from the base
//! record it names, resolved corpus-wide, when its own row states
//! neither).
//!
//! `level` is the minimum level across the record's `CLASSES:`/
//! `DOMAINS:` token(s), `None` for the rare record that states
//! neither (never fabricated -- these land `text-complete`, not
//! `ingested-magnitude`, via `v06_work_inventory::classify`'s
//! existing `Some(false)` branch).
//!
//! `school`/`description` are `Option` because a minority of
//! records carry neither token of their own on this book's base
//! row.

/// The full 9-school PF1 spell-school enum, mirroring every other book's
/// own copy exactly.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Pf1SchoolId {
    Abjuration,
    Conjuration,
    Divination,
    Enchantment,
    Evocation,
    Illusion,
    Necromancy,
    Transmutation,
    Universal,
}

impl Pf1SchoolId {
    pub fn from_corpus_str(raw: &str) -> Option<Self> {
        match raw {
            "Abjuration" => Some(Pf1SchoolId::Abjuration),
            "Conjuration" => Some(Pf1SchoolId::Conjuration),
            "Divination" => Some(Pf1SchoolId::Divination),
            "Enchantment" => Some(Pf1SchoolId::Enchantment),
            "Evocation" => Some(Pf1SchoolId::Evocation),
            "Illusion" => Some(Pf1SchoolId::Illusion),
            "Necromancy" => Some(Pf1SchoolId::Necromancy),
            "Transmutation" => Some(Pf1SchoolId::Transmutation),
            "Universal" => Some(Pf1SchoolId::Universal),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpellListEntry {
    pub key: &'static str,
    /// `decisions.md §24`: `Some(line)` ONLY when `key` above
    /// is a Codex-generated neutral identity (the row's real
    /// name is Product Identity) -- carries the real citation
    /// line so `cache_gen::spell_lane_dump` can resolve it
    /// without a name-based lookup. `None` for an ordinary entry.
    pub name_pi_line: Option<u32>,
    pub school: Option<Pf1SchoolId>,
    pub level: Option<u8>,
    pub description: Option<&'static str>,
}

pub const SPELL_LIST: &[SpellListEntry] = &[
    SpellListEntry { key: "Agonize", name_pi_line: None, school: Some(Pf1SchoolId::Evocation), level: Some(3), description: Some("You afflict a creature you have conjured with a calling spell with bolts of vicious energy to make it more pliant to your will.") },
    SpellListEntry { key: "Hellfire Ray", name_pi_line: None, school: Some(Pf1SchoolId::Evocation), level: Some(6), description: Some("A blast of hellfire blazes from your hands and deals (min(15,CASTERLEVEL))d6 points of damage.") },
    SpellListEntry { key: "Maledication", name_pi_line: None, school: Some(Pf1SchoolId::Necromancy), level: Some(4), description: Some("Target's soul is damned to hell and cannot be resurrected if killed while the spell lasts.") },
    SpellListEntry { key: "Sacrifice", name_pi_line: None, school: Some(Pf1SchoolId::Enchantment), level: Some(4), description: Some("You make a sacrifice to aid in conjuring and commanding a creature called with planar ally, planar binding, or a similar spell.") },
    SpellListEntry { key: "Vision of Hell", name_pi_line: None, school: Some(Pf1SchoolId::Illusion), level: Some(3), description: Some("You overlay a realistic illusion of a terrifying hellscape upon an area, causing creatures to be shaken.") },
    SpellListEntry { key: "Greater Teleport (Self Plus 50 Lbs. Of Objects Only)", name_pi_line: None, school: Some(Pf1SchoolId::Conjuration), level: Some(7), description: None },
];
