//! Package-backed mirror of the compiled `rules_tables` module `apg::antipaladin_features` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::apg::antipaladin_features::CHANNEL_NEGATIVE_ENERGY_DIE_SIZE;
pub use rt::apg::antipaladin_features::aura_of_depravity_damage_reduction;
pub use rt::apg::antipaladin_features::aura_of_evil_strength_level;
pub use rt::apg::antipaladin_features::channel_negative_energy_dc;
pub use rt::apg::antipaladin_features::channel_negative_energy_dice;
pub use rt::apg::antipaladin_features::cruelties_known;
pub use rt::apg::antipaladin_features::cruelty_dc;
pub use rt::apg::antipaladin_features::detect_good_caster_level;
pub use rt::apg::antipaladin_features::fiendish_boon_selections;
pub use rt::apg::antipaladin_features::smite_good_attack_and_ac_bonus;
pub use rt::apg::antipaladin_features::smite_good_damage_bonus;
pub use rt::apg::antipaladin_features::smite_good_uses_per_day;
pub use rt::apg::antipaladin_features::touch_of_corruption_damage_dice;
pub use rt::apg::antipaladin_features::touch_of_corruption_uses_per_day;
pub use rt::apg::antipaladin_features::unholy_champion_banishment_caster_level;
pub use rt::apg::antipaladin_features::unholy_resilience_save_bonus;
