//! Package-backed mirror of the compiled `rules_tables` module `apg::archetype_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

use super::super::archetype_swap::{ArchetypeGrant, ArchetypeSwapEntry};
pub fn archetype_swap_tables() -> &'static [ArchetypeSwapEntry] {
    crate::rules_core::rules_catalog::rows::<ArchetypeSwapEntry>(
        "apg/archetype_tables/archetype_swap_tables",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_has_80_records() {
        assert_eq!(archetype_swap_tables().len(), 80);
    }

    #[test]
    fn keys_are_unique_within_book() {
        let keys: std::collections::BTreeSet<&str> =
            archetype_swap_tables().iter().map(|e| e.key).collect();
        assert_eq!(keys.len(), archetype_swap_tables().len());
    }

    /// A real, systematic exception, confirmed against the raw corpus
    /// rows directly: 9 of this book's 12 Rogue archetypes genuinely
    /// carry no `DESC:`/`BENEFIT:` on their own master row -- not one
    /// stray record, a whole-subfamily gap in this book's own PCGen
    /// conversion. Named explicitly, all 9, rather than silently
    /// loosening the assertion for every record.
    const ROGUE_MASTERS_WITHOUT_DESC: &[&str] = &[
        "Rogue Archetype ~ Burglar",
        "Rogue Archetype ~ Cutpurse",
        "Rogue Archetype ~ Investigator",
        "Rogue Archetype ~ Poisoner",
        "Rogue Archetype ~ Rake",
        "Rogue Archetype ~ Sniper",
        "Rogue Archetype ~ Spy",
        "Rogue Archetype ~ Thug",
        "Rogue Archetype ~ Trapsmith",
    ];

    #[test]
    fn every_master_record_carries_a_real_description() {
        for e in archetype_swap_tables() {
            if ROGUE_MASTERS_WITHOUT_DESC.contains(&e.key) {
                assert!(e.description.is_none(), "{} was expected to still lack DESC: -- re-check the corpus row if this now fails", e.key);
                continue;
            }
            assert!(e.description.is_some(), "{} has no DESC:", e.key);
        }
        let without_desc = archetype_swap_tables().iter().filter(|e| e.description.is_none()).count();
        assert_eq!(without_desc, ROGUE_MASTERS_WITHOUT_DESC.len(), "exactly the named Rogue exceptions, nothing else");
    }

    /// APG's own rate: 52% (42/80) -- higher than UPsi's/ACG's own 33%,
    /// confirming the rate is book-dependent.
    #[test]
    fn the_type_and_ability_lists_genuinely_disagree() {
        let total_replaces: usize =
            archetype_swap_tables().iter().map(|e| e.replaces.map_or(0, |r| r.len())).sum();
        let total_grants: usize = archetype_swap_tables().iter().map(|e| e.grants.len()).sum();
        assert_eq!(total_replaces, 333, "total TYPE: replaced-slot count across all 80 records");
        assert_eq!(total_grants, 392, "total ABILITY: granted-feature count across all 80 records");
        assert_ne!(total_replaces, total_grants);

        let equal_count_records = archetype_swap_tables()
            .iter()
            .filter(|e| e.replaces.map_or(0, |r| r.len()) == e.grants.len())
            .count();
        assert_eq!(equal_count_records, 42, "of 80 (52%) -- APG's own rate, higher than UPsi's/ACG's 33%");
    }

    #[test]
    fn every_grant_names_a_real_level_and_key() {
        for e in archetype_swap_tables() {
            for g in e.grants {
                assert!(!g.grants_feature_key.is_empty(), "{} has an empty grant key", e.key);
                assert!(g.at_level >= 1 && g.at_level <= 20, "{} grant {} has an implausible level {}", e.key, g.grants_feature_key, g.at_level);
            }
        }
    }

    #[test]
    fn resolved_grant_descriptions_are_the_real_count() {
        let resolved: usize = archetype_swap_tables()
            .iter()
            .flat_map(|e| e.grants.iter())
            .filter(|g| g.description.is_some() || g.benefit.is_some())
            .count();
        assert_eq!(resolved, 364, "364 of 392 grants carry real DESC:/BENEFIT: text -- see this module's own doc comment for the 28 that did not (1 failed lookup, 25 shared unresolved names across 5 sibling Shaman-totem archetypes, 2 bare markers)");
    }
}
