//! Package-backed mirror of the compiled `rules_tables` module `apg::class_witch` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

use super::ClassTableRow;
/// `HD:6` on the real `CLASS:Witch` record (v0.6 alpha swarm, risks item
/// 8), verified directly against `apg_classes` line 172.
pub const HIT_DIE: u8 = 6;
/// `MAXLEVEL:20` on the real `CLASS:Witch` record.
pub const MAX_SUPPORTED_LEVEL: u8 = 20;
pub fn class_table() -> Vec<ClassTableRow> {
    crate::rules_core::rules_catalog::rows_vec::<ClassTableRow>("apg/class_witch/class_table")
}
