//! Package-backed mirror of the compiled `rules_tables` module `apg::witch_spell_list` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub static WITCH_SPELL_LIST: crate::rules_core::rules_catalog::Table<(&str, u8)> =
    crate::rules_core::rules_catalog::Table::new("apg/witch_spell_list/WITCH_SPELL_LIST");
pub fn witch_spell_level(spell_key: &str) -> Option<u8> {
    WITCH_SPELL_LIST
        .iter()
        .find(|(key, _)| *key == spell_key)
        .map(|(_, level)| *level)
}
