//! Package-backed mirror of the compiled `rules_tables` module `ultimate_combat::equipment_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::ultimate_combat::equipment_tables::EquipmentCategory;
pub use rt::ultimate_combat::equipment_tables::EquipmentFieldCoverage;
pub use rt::ultimate_combat::equipment_tables::EquipmentTableEntry;
pub fn field_coverage_report() -> EquipmentFieldCoverage {
    let table = equipment_tables();
    EquipmentFieldCoverage {
        total_records: table.len() as u32,
        records_expected: 185,
        has_cost: table.iter().filter(|entry| entry.cost_gp.is_some()).count() as u32,
        has_weight: table
            .iter()
            .filter(|entry| entry.weight_lbs.is_some())
            .count() as u32,
        has_description: table
            .iter()
            .filter(|entry| entry.description.is_some())
            .count() as u32,
    }
}
pub(crate) static GENERAL_TABLE: crate::rules_core::rules_catalog::Table<EquipmentTableEntry> =
    crate::rules_core::rules_catalog::Table::new("ultimate_combat/equipment_tables/GENERAL_TABLE");
pub(crate) static MAGIC_ITEMS_TABLE: crate::rules_core::rules_catalog::Table<EquipmentTableEntry> =
    crate::rules_core::rules_catalog::Table::new(
        "ultimate_combat/equipment_tables/MAGIC_ITEMS_TABLE",
    );
pub(crate) static ARMS_ARMOR_TABLE: crate::rules_core::rules_catalog::Table<EquipmentTableEntry> =
    crate::rules_core::rules_catalog::Table::new(
        "ultimate_combat/equipment_tables/ARMS_ARMOR_TABLE",
    );
pub(crate) static EQUIPMODS_TABLE: crate::rules_core::rules_catalog::Table<EquipmentTableEntry> =
    crate::rules_core::rules_catalog::Table::new(
        "ultimate_combat/equipment_tables/EQUIPMODS_TABLE",
    );
pub fn equipment_tables() -> &'static [EquipmentTableEntry] {
    static TABLES: std::sync::OnceLock<Vec<EquipmentTableEntry>> = std::sync::OnceLock::new();
    TABLES.get_or_init(|| {
        let mut all = Vec::with_capacity(
            GENERAL_TABLE.len() + MAGIC_ITEMS_TABLE.len() + ARMS_ARMOR_TABLE.len(),
        );
        all.extend_from_slice(&*GENERAL_TABLE);
        all.extend_from_slice(&*MAGIC_ITEMS_TABLE);
        all.extend_from_slice(&*ARMS_ARMOR_TABLE);
        all
    })
}
pub fn equipmod_tables() -> &'static [EquipmentTableEntry] {
    &*EQUIPMODS_TABLE
}
pub fn equipment_resolve(key: &str) -> Option<&'static EquipmentTableEntry> {
    equipment_tables()
        .iter()
        .chain(equipmod_tables())
        .find(|entry| entry.key == key)
}
