//! Package-backed mirror of the compiled `rules_tables` module `crb::class_skill_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

use ClassSkillEntry::{Family, Named};
pub use rt::crb::class_skill_tables::ClassSkillEntry;
pub use rt::crb::class_skill_tables::ClassSkillList;
pub static CLASS_SKILL_LISTS: crate::rules_core::rules_catalog::Table<ClassSkillList> =
    crate::rules_core::rules_catalog::Table::new("crb/class_skill_tables/CLASS_SKILL_LISTS");
pub fn class_skill_list(owner_id: &str) -> Option<&'static ClassSkillList> {
    CLASS_SKILL_LISTS
        .iter()
        .find(|entry| entry.owner_id == owner_id)
}
