//! Package-backed mirror of the compiled `rules_tables` module `crb::cleric_spell_list` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

pub static CLERIC_SPELL_LIST: crate::rules_core::rules_catalog::Table<(&str, u8)> =
    crate::rules_core::rules_catalog::Table::new("crb/cleric_spell_list/CLERIC_SPELL_LIST");
pub fn cleric_spell_level(spell_key: &str) -> Option<u8> {
    CLERIC_SPELL_LIST
        .iter()
        .find(|(key, _)| *key == spell_key)
        .map(|(_, level)| *level)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules_core::rules_catalog::acg::spell_list as acg_spell_list;
    use crate::rules_core::rules_catalog::apg::spell_list as apg_spell_list;
    use crate::rules_core::rules_catalog::crb::spell_list::SPELL_LIST;

    #[test]
    fn cleric_spell_list_has_the_real_corpus_verified_count() {
        assert_eq!(CLERIC_SPELL_LIST.len(), 301);
    }

    /// Guards the book-scope widening (task #31). One anchor per ingested
    /// book, each naming Cleric mid-group so its raw line carries no
    /// `Cleric=` substring at all:
    /// `Air Walk` is `CLASSES:Cleric,Druid=4` (CRB),
    /// `Ant Haul` is `CLASSES:Alchemist,Cleric,Druid,Ranger,Sorcerer,Wizard=1` (APG),
    /// `Air Step` is
    /// `CLASSES:Alchemist,Bard,Cleric,Druid,Ranger,Sorcerer,Witch,Wizard=2` (ACG).
    #[test]
    fn spells_tagged_mid_list_in_their_classes_group_are_present() {
        assert_eq!(cleric_spell_level("Air Walk"), Some(4));
        assert_eq!(cleric_spell_level("Ant Haul"), Some(1));
        assert_eq!(cleric_spell_level("Air Step"), Some(2));
    }

    /// The four records whose level carries a trailing optional-rule gate
    /// (APG Hero Points, `=N[PREVAREQ:Heroic,1]`). Cleric has more of
    /// these than any other class. Included per item 54; these are
    /// exactly the records a naive `int(level)` discards silently.
    #[test]
    fn optional_rule_gated_spells_are_on_the_list() {
        assert_eq!(cleric_spell_level("Heroic Fortune"), Some(2));
        assert_eq!(cleric_spell_level("Heroic Fortune (Mass)"), Some(5));
        assert_eq!(cleric_spell_level("Severed Fate"), Some(3));
        assert_eq!(cleric_spell_level("Unravel Destiny"), Some(3));
    }

    /// Domain spells stay OUT of this list, and that exclusion survives
    /// the widening structurally rather than by luck: the corpus carries
    /// them in a separate `DOMAINS:` token (242 CRB records have one),
    /// which this table's `CLASSES:`-only parse never reads. `Bless
    /// Water` is a real Cleric spell and IS here; a domain-only grant is
    /// not reachable through this table at all.
    #[test]
    fn the_general_list_still_excludes_domain_only_grants() {
        assert_eq!(cleric_spell_level("Bless Water"), Some(1));
        assert_eq!(cleric_spell_level("Not A Real Spell"), None);
    }

    #[test]
    fn every_cleric_spell_level_is_within_the_real_cleric_ceiling() {
        for (key, level) in &*CLERIC_SPELL_LIST {
            assert!(
                (0..=9).contains(level),
                "{key} has out-of-range Cleric spell level {level}"
            );
        }
    }

    /// Cleric's list spans all three ingested books, so a CRB-only
    /// cross-check would reject every APG/ACG entry as fictional. Checks
    /// the union instead -- still a real "never an invented name"
    /// guarantee, just scoped to everything this repo actually ingests.
    #[test]
    fn every_cleric_spell_key_is_a_real_spell_list_entry() {
        for (key, _) in &*CLERIC_SPELL_LIST {
            let known = SPELL_LIST.iter().any(|entry| entry.key == *key)
                || apg_spell_list::SPELL_LIST.iter().any(|entry| entry.key == *key)
                || acg_spell_list::SPELL_LIST.iter().any(|entry| entry.key == *key);
            assert!(known, "{key} is not a real spell key in any ingested book");
        }
    }

    #[test]
    fn cleric_spell_level_looks_up_known_values() {
        assert_eq!(cleric_spell_level("Cure Light Wounds"), Some(1));
        assert_eq!(cleric_spell_level("Guidance"), Some(0));
        assert_eq!(cleric_spell_level("Magic Missile"), None);
    }

    #[test]
    fn level_distribution_matches_the_real_corpus_parse() {
        let count_at =
            |level: u8| CLERIC_SPELL_LIST.iter().filter(|(_, l)| *l == level).count();
        assert_eq!(count_at(0), 13);
        assert_eq!(count_at(1), 36);
        assert_eq!(count_at(2), 49);
        assert_eq!(count_at(3), 48);
        assert_eq!(count_at(4), 40);
        assert_eq!(count_at(5), 37);
        assert_eq!(count_at(6), 28);
        assert_eq!(count_at(7), 18);
        assert_eq!(count_at(8), 20);
        assert_eq!(count_at(9), 12);
    }
}
