//! Package-backed mirror of the compiled `rules_tables` module `crb` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use super::companion_chassis::{CompanionAbilityRecord, CompanionClassRecord, CompanionRecord};
pub mod bard_spell_list;
pub mod class_skill_tables;
pub mod class_tables;
pub mod cleric_spell_list;
pub(crate) mod companion_data;
pub mod druid_spell_list;
pub mod equipment_data;
pub mod equipment_tables;
pub mod feat_data;
pub mod feats;
pub mod json_cache;
pub mod paladin_spell_list;
pub mod race_tables;
pub mod ranger_spell_list;
pub mod sorcerer_spell_list;
pub mod spell_list;
pub mod weapon_tables;
pub mod wizard_spell_list;
pub fn companions_static() -> &'static [CompanionRecord] {
    &*companion_data::COMPANIONS
}
pub fn companion_abilities_static() -> &'static [CompanionAbilityRecord] {
    &*companion_data::COMPANION_ABILITIES
}
pub fn companion_classes_static() -> &'static [CompanionClassRecord] {
    &*companion_data::COMPANION_CLASSES
}
pub fn companions() -> &'static [CompanionRecord] {
    companions_static()
}
pub fn companion_abilities() -> &'static [CompanionAbilityRecord] {
    companion_abilities_static()
}
