//! Package-backed mirror of the compiled `rules_tables` module `crb::sorcerer_spell_list` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

pub static SORCERER_SPELL_LIST: crate::rules_core::rules_catalog::Table<(&str, u8)> =
    crate::rules_core::rules_catalog::Table::new("crb/sorcerer_spell_list/SORCERER_SPELL_LIST");
pub fn sorcerer_spell_level(spell_key: &str) -> Option<u8> {
    SORCERER_SPELL_LIST
        .iter()
        .find(|(key, _)| *key == spell_key)
        .map(|(_, level)| *level)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules_core::rules_catalog::acg::spell_list as acg_spell_list;
    use crate::rules_core::rules_catalog::apg::spell_list as apg_spell_list;
    use crate::rules_core::rules_catalog::crb::spell_list::SPELL_LIST;

    #[test]
    fn sorcerer_spell_list_has_the_real_corpus_verified_count() {
        assert_eq!(SORCERER_SPELL_LIST.len(), 578);
    }

    /// Guards the book-scope widening (task #30). One anchor per ingested
    /// book. Sorcerer is the extreme case of the mid-group shape: it is
    /// almost always listed before Wizard, so **all 394** CRB records name
    /// it mid-group and a `Sorcerer=` substring grep would find ZERO of
    /// them. Raw lines:
    /// `Acid Arrow` is `CLASSES:Sorcerer,Wizard=2` (CRB),
    /// `Alter Winds` is `CLASSES:Druid,Sorcerer,Wizard=1` (APG),
    /// `Adhesive Blood` is
    /// `CLASSES:Alchemist,Bloodrager,Sorcerer,Witch,Wizard=2` (ACG).
    #[test]
    fn spells_tagged_mid_list_in_their_classes_group_are_present() {
        assert_eq!(sorcerer_spell_level("Acid Arrow"), Some(2));
        assert_eq!(sorcerer_spell_level("Alter Winds"), Some(1));
        assert_eq!(sorcerer_spell_level("Adhesive Blood"), Some(2));
    }

    /// The two records whose level carries a trailing optional-rule gate
    /// (`CLASSES:Sorcerer,Witch,Wizard=3[PREVAREQ:Heroic,1]` and
    /// `CLASSES:Cleric,Sorcerer,Witch,Wizard=3[PREVAREQ:Heroic,1]`).
    /// These are the exact records a naive `int(level)` throws away
    /// silently; included per item 54.
    #[test]
    fn optional_rule_gated_spells_are_on_the_list() {
        assert_eq!(sorcerer_spell_level("Malediction"), Some(3));
        assert_eq!(sorcerer_spell_level("Unravel Destiny"), Some(3));
    }

    #[test]
    fn every_sorcerer_spell_level_is_within_the_real_sorcerer_ceiling() {
        for (key, level) in &*SORCERER_SPELL_LIST {
            assert!(
                (0..=9).contains(level),
                "{key} has out-of-range Sorcerer spell level {level}"
            );
        }
    }

    /// Sorcerer's list spans all three ingested books, so a CRB-only
    /// cross-check would reject every APG/ACG entry as fictional. Checks
    /// the union instead -- still a real "never an invented name"
    /// guarantee, just scoped to everything this repo actually ingests.
    #[test]
    fn every_sorcerer_spell_key_is_a_real_spell_list_entry() {
        for (key, _) in &*SORCERER_SPELL_LIST {
            let known = SPELL_LIST.iter().any(|entry| entry.key == *key)
                || apg_spell_list::SPELL_LIST.iter().any(|entry| entry.key == *key)
                || acg_spell_list::SPELL_LIST.iter().any(|entry| entry.key == *key);
            assert!(known, "{key} is not a real spell key in any ingested book");
        }
    }

    #[test]
    fn sorcerer_spell_level_looks_up_known_values() {
        assert_eq!(sorcerer_spell_level("Acid Splash"), Some(0));
        assert_eq!(sorcerer_spell_level("Wish"), Some(9));
        assert_eq!(sorcerer_spell_level("Magic Missile"), Some(1));
        assert_eq!(sorcerer_spell_level("Nonexistent Spell"), None);
    }

    #[test]
    fn level_distribution_matches_the_real_corpus_parse() {
        let count_at =
            |level: u8| SORCERER_SPELL_LIST.iter().filter(|(_, l)| *l == level).count();
        assert_eq!(count_at(0), 21);
        assert_eq!(count_at(1), 82);
        assert_eq!(count_at(2), 86);
        assert_eq!(count_at(3), 82);
        assert_eq!(count_at(4), 68);
        assert_eq!(count_at(5), 60);
        assert_eq!(count_at(6), 57);
        assert_eq!(count_at(7), 49);
        assert_eq!(count_at(8), 42);
        assert_eq!(count_at(9), 31);
    }
}
