//! Package-backed mirror of the compiled `rules_tables` module `crb::spell_list` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::crb::spell_list::Pf1SchoolId;
pub use rt::crb::spell_list::SpellFieldCoverage;
pub use rt::crb::spell_list::SpellListEntry;
pub fn spell_coverage_report() -> SpellFieldCoverage {
    let total = SPELL_LIST.len() as u32;
    SpellFieldCoverage {
        total_records: total,
        records_expected: 664,
        has_description: total,
        full_text_verified: total,
    }
}
pub static SPELL_LIST: crate::rules_core::rules_catalog::Table<SpellListEntry> =
    crate::rules_core::rules_catalog::Table::new("crb/spell_list/SPELL_LIST");
