//! Package-backed mirror of the compiled `rules_tables` module `crb::weapon_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::crb::weapon_tables::WeaponProficiency;
pub use rt::crb::weapon_tables::WeaponTableEntry;
pub use rt::crb::weapon_tables::weapon_critical_threat_low;
pub fn weapon_by_key(key: &str) -> Option<&'static WeaponTableEntry> {
    WEAPON_TABLE.iter().find(|entry| entry.key == key)
}
pub static WEAPON_TABLE: crate::rules_core::rules_catalog::Table<WeaponTableEntry> =
    crate::rules_core::rules_catalog::Table::new("crb/weapon_tables/WEAPON_TABLE");
pub static FINESSEABLE_WEAPON_KEYS: crate::rules_core::rules_catalog::Table<&str> =
    crate::rules_core::rules_catalog::Table::new("crb/weapon_tables/FINESSEABLE_WEAPON_KEYS");
pub fn weapon_is_finesseable(entry: &WeaponTableEntry) -> bool {
    FINESSEABLE_WEAPON_KEYS.contains(&entry.key)
}
pub use rt::crb::weapon_tables::ClassWeaponProficiency;
pub static CLASS_WEAPON_PROFICIENCIES: crate::rules_core::rules_catalog::Table<
    ClassWeaponProficiency,
> = crate::rules_core::rules_catalog::Table::new("crb/weapon_tables/CLASS_WEAPON_PROFICIENCIES");
pub fn class_weapon_proficiency(class_id: &str) -> Option<&'static ClassWeaponProficiency> {
    CLASS_WEAPON_PROFICIENCIES
        .iter()
        .find(|entry| entry.class_id == class_id)
}
pub use rt::crb::weapon_tables::ClassArmorProficiency;
pub use rt::crb::weapon_tables::class_is_proficient_with;
pub static CLASS_ARMOR_PROFICIENCIES: crate::rules_core::rules_catalog::Table<
    ClassArmorProficiency,
> = crate::rules_core::rules_catalog::Table::new("crb/weapon_tables/CLASS_ARMOR_PROFICIENCIES");
pub fn class_armor_proficiency(class_id: &str) -> Option<&'static ClassArmorProficiency> {
    CLASS_ARMOR_PROFICIENCIES
        .iter()
        .find(|entry| entry.class_id == class_id)
}
