//! Package-backed mirror of the compiled `rules_tables` module `crb::wizard_spell_list` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

pub static WIZARD_SPELL_LIST: crate::rules_core::rules_catalog::Table<(&str, u8)> =
    crate::rules_core::rules_catalog::Table::new("crb/wizard_spell_list/WIZARD_SPELL_LIST");
pub fn wizard_spell_level(spell_key: &str) -> Option<u8> {
    WIZARD_SPELL_LIST
        .iter()
        .find(|(key, _)| *key == spell_key)
        .map(|(_, level)| *level)
}
pub fn wizard_school_zero_level_spells(
    school: crate::rules_core::rules_catalog::crb::spell_list::Pf1SchoolId,
) -> Vec<&'static str> {
    use crate::rules_core::rules_catalog::crb::spell_list::SPELL_LIST;
    let mut spells: Vec<&'static str> = WIZARD_SPELL_LIST
        .iter()
        .filter(|(_, level)| *level == 0)
        .filter_map(|(key, _)| {
            SPELL_LIST
                .iter()
                .find(|entry| entry.key == *key && entry.school == school)
                .map(|entry| entry.key)
        })
        .collect();
    spells.sort_unstable();
    spells
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules_core::rules_catalog::acg::spell_list as acg_spell_list;
    use crate::rules_core::rules_catalog::apg::spell_list as apg_spell_list;
    use crate::rules_core::rules_catalog::crb::sorcerer_spell_list::SORCERER_SPELL_LIST;
    use crate::rules_core::rules_catalog::crb::spell_list::SPELL_LIST;

    #[test]
    fn wizard_spell_list_has_the_real_corpus_verified_count() {
        assert_eq!(WIZARD_SPELL_LIST.len(), 580);
    }


    /// One anchor per ingested book, each a record where Wizard is NOT the
    /// first name in its `CLASSES:` comma group. Raw lines:
    /// `Acid Arrow` is `CLASSES:Sorcerer,Wizard=2` (CRB),
    /// `Alter Winds` is `CLASSES:Druid,Sorcerer,Wizard=1` (APG),
    /// `Adhesive Blood` is
    /// `CLASSES:Alchemist,Bloodrager,Sorcerer,Witch,Wizard=2` (ACG).
    #[test]
    fn spells_tagged_mid_list_in_their_classes_group_are_present() {
        assert_eq!(wizard_spell_level("Acid Arrow"), Some(2));
        assert_eq!(wizard_spell_level("Alter Winds"), Some(1));
        assert_eq!(wizard_spell_level("Adhesive Blood"), Some(2));
    }

    /// The two records whose level carries a trailing optional-rule gate
    /// (`CLASSES:Sorcerer,Witch,Wizard=3[PREVAREQ:Heroic,1]` and
    /// `CLASSES:Cleric,Sorcerer,Witch,Wizard=3[PREVAREQ:Heroic,1]`).
    /// These are the exact records a naive `int(level)` throws away
    /// silently; included per item 54.
    #[test]
    fn optional_rule_gated_spells_are_on_the_list() {
        assert_eq!(wizard_spell_level("Malediction"), Some(3));
        assert_eq!(wizard_spell_level("Unravel Destiny"), Some(3));
    }

    #[test]
    fn every_wizard_spell_level_is_within_the_real_wizard_ceiling() {
        for (key, level) in &*WIZARD_SPELL_LIST {
            assert!(
                (0..=9).contains(level),
                "{key} has out-of-range Wizard spell level {level}"
            );
        }
    }

    #[test]
    fn every_wizard_spell_key_is_a_real_spell_list_entry() {
        for (key, _) in &*WIZARD_SPELL_LIST {
            let known = SPELL_LIST.iter().any(|entry| entry.key == *key)
                || apg_spell_list::SPELL_LIST.iter().any(|entry| entry.key == *key)
                || acg_spell_list::SPELL_LIST.iter().any(|entry| entry.key == *key);
            assert!(known, "{key} is not a real spell key in any ingested book");
        }
    }

    #[test]
    fn no_spell_key_appears_twice() {
        let mut keys: Vec<&str> = WIZARD_SPELL_LIST.iter().map(|(key, _)| *key).collect();
        keys.sort_unstable();
        let total = keys.len();
        keys.dedup();
        assert_eq!(keys.len(), total, "a spell key is listed twice");
    }

    #[test]
    fn wizard_spell_level_looks_up_known_values() {
        assert_eq!(wizard_spell_level("Acid Splash"), Some(0));
        assert_eq!(wizard_spell_level("Wish"), Some(9));
        assert_eq!(wizard_spell_level("Magic Missile"), Some(1));
        assert_eq!(wizard_spell_level("Nonexistent Spell"), None);
    }

    /// The bug this table exists to fix, at its canonical example.
    /// `Hideous Laughter` is `CLASSES:Bard=1|Sorcerer,Wizard=2`, so the
    /// record's own minimum-across-classes level is 1 -- which is what
    /// `crb::spell_list` carries and what the Character Sheet used to show
    /// a Wizard. A Wizard learns it at 2.
    #[test]
    fn hideous_laughter_is_second_level_for_a_wizard_not_first() {
        let record_level = SPELL_LIST
            .iter()
            .find(|entry| entry.key == "Hideous Laughter")
            .expect("Hideous Laughter is a real CRB record")
            .level;
        assert_eq!(record_level, 1, "the record's own level is the Bard level");
        assert_eq!(wizard_spell_level("Hideous Laughter"), Some(2));
    }

    #[test]
    fn level_distribution_matches_the_real_corpus_parse() {
        let count_at = |level: u8| WIZARD_SPELL_LIST.iter().filter(|(_, l)| *l == level).count();
        assert_eq!(count_at(0), 21);
        assert_eq!(count_at(1), 82);
        assert_eq!(count_at(2), 86);
        assert_eq!(count_at(3), 82);
        assert_eq!(count_at(4), 69);
        assert_eq!(count_at(5), 60);
        assert_eq!(count_at(6), 58);
        assert_eq!(count_at(7), 49);
        assert_eq!(count_at(8), 42);
        assert_eq!(count_at(9), 31);
    }

    /// Pins the Sorcerer relationship as an OBSERVATION -- see this
    /// module's doc comment for why it is not used as a derivation. If a
    /// corpus revision ever splits the two arcane lists, this test is the
    /// one that reports it; it is not a correctness constraint on either
    /// table.
    #[test]
    fn the_sorcerer_overlap_is_an_observation_not_a_derivation() {
        let wizard_only: Vec<&str> = WIZARD_SPELL_LIST
            .iter()
            .filter(|(key, _)| !SORCERER_SPELL_LIST.iter().any(|(other, _)| other == key))
            .map(|(key, _)| *key)
            .collect();
        assert_eq!(wizard_only, vec!["Mage's Lucubration", "Mnemonic Enhancer"]);
        assert_eq!(wizard_spell_level("Mage's Lucubration"), Some(6));
        assert_eq!(wizard_spell_level("Mnemonic Enhancer"), Some(4));

        let sorcerer_only: Vec<&str> = SORCERER_SPELL_LIST
            .iter()
            .filter(|(key, _)| !WIZARD_SPELL_LIST.iter().any(|(other, _)| other == key))
            .map(|(key, _)| *key)
            .collect();
        assert!(sorcerer_only.is_empty(), "sorcerer-only keys: {sorcerer_only:?}");

        let disagreements: Vec<&str> = SORCERER_SPELL_LIST
            .iter()
            .filter(|(key, level)| wizard_spell_level(key).is_some_and(|w| w != *level))
            .map(|(key, _)| *key)
            .collect();
        assert!(
            disagreements.is_empty(),
            "the two arcane lists disagree on: {disagreements:?}"
        );
    }

    /// The scale of the defect this table fixes, re-derived here rather
    /// than asserted from memory: how many of the 580 Wizard spells the
    /// record's own `level` field gets wrong. Every one of them is biased
    /// LOW (the record's level is a minimum), never high.
    #[test]
    fn the_record_level_understates_the_wizard_level_for_67_of_580_spells() {
        let record_level = |key: &str| -> Option<u8> {
            SPELL_LIST
                .iter()
                .find(|entry| entry.key == key)
                .map(|entry| entry.level)
                .or_else(|| {
                    apg_spell_list::SPELL_LIST
                        .iter()
                        .find(|entry| entry.key == key)
                        .and_then(|entry| entry.level)
                })
                .or_else(|| {
                    acg_spell_list::SPELL_LIST
                        .iter()
                        .find(|entry| entry.key == key)
                        .map(|entry| entry.level)
                })
        };

        let mut wrong = 0;
        let mut biased_high = 0;
        let mut no_record_level = 0;
        for (key, wizard_level) in &*WIZARD_SPELL_LIST {
            match record_level(key) {
                None => no_record_level += 1,
                Some(shown) if shown == *wizard_level => {}
                Some(shown) => {
                    wrong += 1;
                    if shown > *wizard_level {
                        biased_high += 1;
                    }
                }
            }
        }
        assert_eq!(wrong, 67, "spells whose record level is a wrong number");
        assert_eq!(biased_high, 0, "the bias is always low, never high");
        // The remaining two are `Malediction` and `Unravel Destiny`: their
        // APG records carry no usable `level`, so the sheet showed no
        // number at all rather than a wrong one. This table supplies 3
        // for both.
        assert_eq!(no_record_level, 2);
    }
}
