//! Package-backed mirror of the compiled `rules_tables` module `book_of_the_damned_volume_1::companion_data` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

use crate::rules_core::rules_catalog::companion_chassis::{
    CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityGrant, CompanionAbilityRecord,
    CompanionClassRecord, CompanionRecord, NaturalAttack, Speed, StatAdjustment,
};
pub(crate) static COMPANIONS: crate::rules_core::rules_catalog::Table<CompanionRecord> =
    crate::rules_core::rules_catalog::Table::new(
        "book_of_the_damned_volume_1/companion_data/COMPANIONS",
    );
pub(crate) static COMPANION_ABILITIES: crate::rules_core::rules_catalog::Table<
    CompanionAbilityRecord,
> = crate::rules_core::rules_catalog::Table::new(
    "book_of_the_damned_volume_1/companion_data/COMPANION_ABILITIES",
);
pub(crate) static COMPANION_CLASSES: crate::rules_core::rules_catalog::Table<CompanionClassRecord> =
    crate::rules_core::rules_catalog::Table::new(
        "book_of_the_damned_volume_1/companion_data/COMPANION_CLASSES",
    );
