//! Package-backed mirror of the compiled `rules_tables` module `book_of_the_damned_volume_1` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

pub use super::companion_chassis::{CompanionAbilityRecord, CompanionClassRecord, CompanionRecord};
pub use super::monster_chassis::{
    MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterStatBlock,
    NaturalAttack, Speed,
};
pub(crate) mod companion_data;
pub(crate) mod monster_data;
pub mod spell_list;
pub fn companions_static() -> &'static [CompanionRecord] {
    &*companion_data::COMPANIONS
}
pub fn companion_abilities_static() -> &'static [CompanionAbilityRecord] {
    &*companion_data::COMPANION_ABILITIES
}
pub fn companion_classes_static() -> &'static [CompanionClassRecord] {
    &*companion_data::COMPANION_CLASSES
}
pub fn companions() -> &'static [CompanionRecord] {
    companions_static()
}
pub fn companion_abilities() -> &'static [CompanionAbilityRecord] {
    companion_abilities_static()
}
pub fn monsters_static() -> &'static [MonsterStatBlock] {
    &*monster_data::MONSTERS
}
pub fn monster_abilities_static() -> &'static [MonsterAbilityRecord] {
    &*monster_data::MONSTER_ABILITIES
}
pub fn monsters() -> &'static [MonsterStatBlock] {
    monsters_static()
}
pub fn monster_abilities() -> &'static [MonsterAbilityRecord] {
    monster_abilities_static()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Both counts come from `docs/work-inventory.json`'s units for this book,
    /// never a line count over the source file:
    /// `python3 -c "import json; d=json.load(open('docs/work-inventory.json'));
    /// print(sum(1 for u in d['units'] if
    /// u['book']=='book_of_the_damned_volume_1' and u['kind']=='monster'))"`
    /// -> 5, and the same for `monster_ability` -> 36.
    #[test]
    fn the_book_defines_five_monsters_and_thirty_six_abilities() {
        assert_eq!(monsters().len(), 5);
        assert_eq!(monster_abilities().len(), 36);
    }

    /// Verbatim spot-check against `botd1_races:11`, checkable against the
    /// named line rather than merely self-consistent. This row is also the
    /// book's only monster whose corpus row names no natural attack at all —
    /// an honest empty, not a transcription that dropped one.
    #[test]
    fn the_lesser_host_devil_matches_its_corpus_row() {
        let devil = monsters()
            .iter()
            .find(|m| m.key == "Devil (Lesser Host)")
            .expect("Devil (Lesser Host) is in this book");
        assert_eq!(devil.source_line, 11);
        assert_eq!(devil.name, "Devil, Lesser Host (Gaav)");
        assert_eq!(devil.size, Some("S"));
        assert_eq!(devil.challenge_rating, Some("3"));
        assert_eq!(devil.monster_class, Some("Outsider (Fort/Ref):4"));
        assert_eq!(devil.race_type, Some("Outsider"));
        assert_eq!(devil.source_page, Some("p.58"));
        assert_eq!(
            devil.speeds,
            &[
                Speed { mode: "Walk", feet: 5 },
                Speed { mode: "Fly", feet: 60 },
            ]
        );
        assert!(
            devil.natural_attacks.is_empty(),
            "botd1_races:11 carries no NATURALATTACKS: token"
        );
        assert_eq!(devil.external_ability_refs, &["Flight Maneuverability"]);
    }

    /// The Warmonger Devil's row names `Warmonger Devil ~ Trample`, which this
    /// book *does* define upstream — as `TYPE:Internal`
    /// (`botd1_abilities_race:46`), which the inventory's
    /// `internal_namespace` trap excludes from the unit set. It must therefore
    /// be carried as an external reference and must NOT be a record here: a
    /// transcription that ingested it would ship a row the inventory does not
    /// count, and one that dropped the reference would hide a real citation.
    #[test]
    fn an_internal_typed_ability_stays_an_external_reference() {
        let devil = monsters()
            .iter()
            .find(|m| m.key == "Devil (Warmonger)")
            .expect("Devil (Warmonger) is in this book");
        assert!(devil.external_ability_refs.contains(&"Warmonger Devil ~ Trample"));
        assert!(
            !monster_abilities()
                .iter()
                .any(|a| a.key == "Warmonger Devil ~ Trample"),
            "an internal-typed row must not become a served record"
        );
    }

    /// Every ability row of this book is owned by a monster row of this book —
    /// the property that made it the correct next target, held as a test rather
    /// than left in a receipt.
    #[test]
    fn no_ability_row_of_this_book_is_an_orphan() {
        for ability in monster_abilities() {
            assert!(
                !ability.owners.is_empty(),
                "{} reaches no monster and would load without ever being shown",
                ability.key
            );
        }
    }
}
