//! Ultimate Magic (Words of Power examples) shared spell list.
//!
//! Generated by `src/bin/ingest_spells.rs` (config-driven, all
//! books) from the real `pathfinder/paizo/roleplaying_game/ultimate_magic/um_spells_wordsofpower.lst` corpus. Record coverage: every
//! real, active (non-`.MOD`, non-`.COPY=`) base spell declaration.
//!
//! `level` is the minimum level across the record's `CLASSES:`/
//! `DOMAINS:` token(s), `None` for the rare record that states
//! neither (never fabricated -- these land `text-complete`, not
//! `ingested-magnitude`, via `v06_work_inventory::classify`'s
//! existing `Some(false)` branch).
//!
//! `school`/`description` are `Option` because a minority of
//! records carry neither token of their own on this book's base
//! row.

/// The full 9-school PF1 spell-school enum, mirroring every other book's
/// own copy exactly.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Pf1SchoolId {
    Abjuration,
    Conjuration,
    Divination,
    Enchantment,
    Evocation,
    Illusion,
    Necromancy,
    Transmutation,
    Universal,
}

impl Pf1SchoolId {
    pub fn from_corpus_str(raw: &str) -> Option<Self> {
        match raw {
            "Abjuration" => Some(Pf1SchoolId::Abjuration),
            "Conjuration" => Some(Pf1SchoolId::Conjuration),
            "Divination" => Some(Pf1SchoolId::Divination),
            "Enchantment" => Some(Pf1SchoolId::Enchantment),
            "Evocation" => Some(Pf1SchoolId::Evocation),
            "Illusion" => Some(Pf1SchoolId::Illusion),
            "Necromancy" => Some(Pf1SchoolId::Necromancy),
            "Transmutation" => Some(Pf1SchoolId::Transmutation),
            "Universal" => Some(Pf1SchoolId::Universal),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpellListEntry {
    pub key: &'static str,
    /// `decisions.md §24`: `Some(line)` ONLY when `key` above
    /// is a Codex-generated neutral identity (the row's real
    /// name is Product Identity) -- carries the real citation
    /// line so `cache_gen::spell_lane_dump` can resolve it
    /// without a name-based lookup. `None` for an ordinary entry.
    pub name_pi_line: Option<u32>,
    pub school: Option<Pf1SchoolId>,
    pub level: Option<u8>,
    pub description: Option<&'static str>,
}

pub const SPELL_LIST: &[SpellListEntry] = &[
    SpellListEntry { key: "Burst Fire Blast", name_pi_line: None, school: Some(Pf1SchoolId::Evocation), level: Some(3), description: Some("Deals (min(10,CASTERLEVEL))d6 fire damage in 10 foot burst.") },
    SpellListEntry { key: "Selected Ice Blast Life Leech", name_pi_line: None, school: None, level: Some(6), description: Some("Deals (min(10,CASTERLEVEL))d6 cold damage, entangles target for 1d4 rounds, and gives 1d4 temporary negative levels.") },
    SpellListEntry { key: "Selected Alignment Shield Enhance Form Grave Bane", name_pi_line: None, school: None, level: Some(6), description: Some("Grants +2 to AC and saves when attacked by chosen alignment type, +4 Strength, Dexterity, or Constitution, and +4 on saves vs. death magic; subject cannot gain negative levels and is automatically stabilized.") },
];
