//! bestiary companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py bestiary`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `b1_races_companion.lst` -- 24 companion creature rows
//!   * `b1_abilities_companion.lst` -- 35 companion ability rows

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, Speed, StatAdjustment};

/// Every bestiary companion creature (24 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Companion (Bat (Dire))",
        name: "Companion (Bat (Dire))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.30"),
        ability_keys: &["Companion Advancement ~ Bat (Dire)"],
        external_ability_refs: &["Flight Maneuverability", "Animal Traits Output"],
        source_file: "b1_races_companion.lst",
        source_line: 7,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Ankylosaurus))",
        name: "Companion (Dinosaur (Ankylosaurus))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Tail", damage_dice: Some("1d6") }],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "CHA", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(9),
        source_page: Some("p.83"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Ankylosaurus)", "Ankylosaurus ~ Stun"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 8,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Brachiosaurus))",
        name: "Companion (Dinosaur (Brachiosaurus))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Tail", damage_dice: Some("2d4") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(3),
        source_page: Some("p.82"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Brachiosaurus)"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Elasmosaurus))",
        name: "Companion (Dinosaur (Elasmosaurus))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d8") }],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(2),
        source_page: Some("p.84"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Elasmosaurus)"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 10,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Pteranodon))",
        name: "Companion (Dinosaur (Pteranodon))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d8") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 10 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.85"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Pteranodon)"],
        external_ability_refs: &["Flight Maneuverability", "Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 11,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Stegosaurus))",
        name: "Companion (Dinosaur (Stegosaurus))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Tail", damage_dice: Some("2d6") }],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(6),
        source_page: Some("p.85"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Stegosaurus)"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 12,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Triceratops))",
        name: "Companion (Dinosaur (Triceratops))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("1d8") }],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(6),
        source_page: Some("p.86"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Triceratops)"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 13,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Tyrannosaurus))",
        name: "Companion (Dinosaur (Tyrannosaurus))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d8") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }],
        natural_armor: Some(4),
        source_page: Some("p.86"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Tyrannosaurus)", "Tyrannosaurus ~ Powerful Bite"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Companion (Dolphin)",
        name: "Companion (Dolphin)",
        size: Some("M"),
        speeds: &[Speed { mode: "Swim", feet: 80 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: Some("1d4") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.88"),
        ability_keys: &["Dolphin ~ Hold Breath", "Companion Advancement ~ Dolphin"],
        external_ability_refs: &[],
        source_file: "b1_races_companion.lst",
        source_line: 15,
    },
    CompanionRecord {
        key: "Companion (Dolphin (Orca))",
        name: "Companion (Dolphin (Orca))",
        size: Some("M"),
        speeds: &[Speed { mode: "Swim", feet: 80 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(6),
        source_page: Some("p.88"),
        ability_keys: &["Dolphin ~ Hold Breath", "Companion Advancement ~ Dolphin (Orca)"],
        external_ability_refs: &[],
        source_file: "b1_races_companion.lst",
        source_line: 16,
    },
    CompanionRecord {
        key: "Companion (Frog (Giant))",
        name: "Companion (Frog (Giant))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }, NaturalAttack { name: "Tongue", damage_dice: Some("0") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -9 }, StatAdjustment { ability: "WIS", amount: -2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.135"),
        ability_keys: &["Giant Frog ~ Tongue", "Companion Advancement ~ Frog (Giant)"],
        external_ability_refs: &["Grab", "Pull", "Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 17,
    },
    CompanionRecord {
        key: "Companion (Eel (Electric))",
        name: "Companion (Eel (Electric))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 8 }, StatAdjustment { ability: "INT", amount: -9 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.119"),
        ability_keys: &["Companion Advancement ~ Eel (Electric)", "Electric Eel ~ Electricity"],
        external_ability_refs: &["Amphibious", "Can't Be Tripped"],
        source_file: "b1_races_companion.lst",
        source_line: 18,
    },
    CompanionRecord {
        key: "Companion (Eel (Giant Moray))",
        name: "Companion (Eel (Giant Moray))",
        size: Some("M"),
        speeds: &[Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d8") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -9 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(5),
        source_page: Some("p.119"),
        ability_keys: &["Companion Advancement ~ Eel (Giant Moray)", "Giant Moray Eel ~ Gnaw"],
        external_ability_refs: &["Grab", "Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 19,
    },
    CompanionRecord {
        key: "Companion (Elephant (Mastodon))",
        name: "Companion (Elephant (Mastodon))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("1d8") }, NaturalAttack { name: "Slam", damage_dice: Some("1d6") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(4),
        source_page: Some("p.128"),
        ability_keys: &["Companion Advancement ~ Elephant (Mastodon)"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 20,
    },
    CompanionRecord {
        key: "Companion (Elephant)",
        name: "Companion (Elephant)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("1d8") }, NaturalAttack { name: "Slam", damage_dice: Some("1d6") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(4),
        source_page: Some("p.128"),
        ability_keys: &["Companion Advancement ~ Elephant (Mastodon)"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 21,
    },
    CompanionRecord {
        key: "Companion (Goblin Dog)",
        name: "Companion (Goblin Dog)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d4") }],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: None,
        source_page: Some("p.157"),
        ability_keys: &["Goblin Dog ~ Allergic Reaction", "Companion Advancement ~ Goblin Dog"],
        external_ability_refs: &["Immunity to Disease"],
        source_file: "b1_races_companion.lst",
        source_line: 22,
    },
    CompanionRecord {
        key: "Companion (Herd Animal (Aurochs))",
        name: "Companion (Herd Animal (Aurochs))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("1d6") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.174"),
        ability_keys: &["Companion Advancement ~ Herd Animal (Aurochs)"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 23,
    },
    CompanionRecord {
        key: "Companion (Herd Animal (Bison))",
        name: "Companion (Herd Animal (Bison))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("1d6") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.174"),
        ability_keys: &["Companion Advancement ~ Herd Animal (Aurochs)"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 24,
    },
    CompanionRecord {
        key: "Companion (Hyena)",
        name: "Companion (Hyena)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d4") }],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(2),
        source_page: Some("p.179"),
        ability_keys: &["Companion Advancement ~ Hyena"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 25,
    },
    CompanionRecord {
        key: "Companion (Lizard (Monitor))",
        name: "Companion (Lizard (Monitor))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.194"),
        ability_keys: &["Companion Advancement ~ Monitor Lizard", "Lizard Monitor ~ Poison"],
        external_ability_refs: &["Grab", "Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 26,
    },
    CompanionRecord {
        key: "Companion (Octopus)",
        name: "Companion (Octopus)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Tentacle", damage_dice: Some("0") }, NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(1),
        source_page: Some("p.219"),
        ability_keys: &["Octopus ~ Ink Cloud", "Octopus ~ Jet", "Companion Advancement ~ Octopus", "Octopus ~ Poison"],
        external_ability_refs: &["Can't Be Tripped", "Grab"],
        source_file: "b1_races_companion.lst",
        source_line: 27,
    },
    CompanionRecord {
        key: "Companion (Rhinoceros)",
        name: "Companion (Rhinoceros)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("1d8") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(4),
        source_page: Some("p.235"),
        ability_keys: &["Companion Advancement ~ Rhinoceros"],
        external_ability_refs: &["Scent"],
        source_file: "b1_races_companion.lst",
        source_line: 28,
    },
    CompanionRecord {
        key: "Companion (Roc)",
        name: "Companion (Roc)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 80 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Talons", damage_dice: Some("1d4") }, NaturalAttack { name: "Bite", damage_dice: Some("1d6") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(5),
        source_page: Some("p.236"),
        ability_keys: &["Companion Advancement ~ Roc"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "b1_races_companion.lst",
        source_line: 29,
    },
    CompanionRecord {
        key: "Companion (Squid)",
        name: "Companion (Squid)",
        size: Some("M"),
        speeds: &[Speed { mode: "Swim", feet: 60 }, Speed { mode: "Jet", feet: 240 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }, NaturalAttack { name: "Tentacles", damage_dice: Some("1d4") }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.259"),
        ability_keys: &["Squid ~ Ink Cloud", "Squid ~ Jet", "Companion Advancement ~ Squid"],
        external_ability_refs: &["Grab"],
        source_file: "b1_races_companion.lst",
        source_line: 30,
    },
];

/// Every bestiary companion ability record (35 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Bat (Dire)",
        name: "Companion Advancement (Bat (Dire))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Bat (Dire))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 6,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Ankylosaurus)",
        name: "Companion Advancement (Dinosaur (Ankylosaurus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Ankylosaurus))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 7,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Brachiosaurus)",
        name: "Companion Advancement (Dinosaur (Brachiosaurus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Brachiosaurus))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 8,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Elasmosaurus)",
        name: "Companion Advancement (Dinosaur (Elasmosaurus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Elasmosaurus))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 9,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Pteranodon)",
        name: "Companion Advancement (Dinosaur (Pteranodon))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Pteranodon))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 10,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Stegosaurus)",
        name: "Companion Advancement (Dinosaur (Stegosaurus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Stegosaurus))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 11,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Triceratops)",
        name: "Companion Advancement (Dinosaur (Triceratops))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Triceratops))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 12,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Tyrannosaurus)",
        name: "Companion Advancement (Dinosaur (Tyrannosaurus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Tyrannosaurus))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 13,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dolphin",
        name: "Companion Advancement (Dolphin)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }],
        source_page: None,
        owners: &["Companion (Dolphin)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 14,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dolphin (Orca)",
        name: "Companion Advancement (Dolphin (Orca))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dolphin (Orca))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 15,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Frog (Giant)",
        name: "Companion Advancement (Frog (Giant))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }],
        source_page: None,
        owners: &["Companion (Frog (Giant))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 16,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Eel (Electric)",
        name: "Companion Advancement (Eel (Electric))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Eel (Electric))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 17,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Eel (Giant Moray)",
        name: "Companion Advancement (Eel (Giant Moray))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Eel (Giant Moray))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 18,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Elephant (Mastodon)",
        name: "Companion Advancement (Elephant (Mastodon))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Elephant (Mastodon))", "Companion (Elephant)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 19,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Goblin Dog",
        name: "Companion Advancement (Goblin Dog)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Goblin Dog)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 20,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Herd Animal (Aurochs)",
        name: "Companion Advancement (Herd Animal (Aurochs))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Herd Animal (Aurochs))", "Companion (Herd Animal (Bison))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 21,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Hyena",
        name: "Companion Advancement (Hyena)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Hyena)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 22,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Monitor Lizard",
        name: "Companion Advancement (Monitor Lizard)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Lizard (Monitor))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 23,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Octopus",
        name: "Companion Advancement (Octopus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }],
        source_page: None,
        owners: &["Companion (Octopus)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 24,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Rhinoceros",
        name: "Companion Advancement (Rhinoceros)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Rhinoceros)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 25,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Roc",
        name: "Companion Advancement (Roc)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Roc)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 26,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Squid",
        name: "Companion Advancement (Squid)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Squid)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 27,
    },
    CompanionAbilityRecord {
        key: "Ankylosaurus ~ Stun",
        name: "Stun",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("The ankylosaurus's tail can deliver a powerful, stunning blow. A creature struck by this attack must make a DC %1 save or be dazed for 1 round. If the strike is a critical hit and the target fails its save, it is instead stunned for 1d4 rounds."),
        description_variables: &["StunDC"],
        stat_adjustments: &[],
        source_page: Some("p.83"),
        owners: &["Companion (Dinosaur (Ankylosaurus))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 31,
    },
    CompanionAbilityRecord {
        key: "Dolphin ~ Hold Breath",
        name: "Hold Breath",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("You can hold your breath for %1 rounds before it risks drowning."),
        description_variables: &["HoldBreathDuration"],
        stat_adjustments: &[],
        source_page: Some("p.88"),
        owners: &["Companion (Dolphin)", "Companion (Dolphin (Orca))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 32,
    },
    CompanionAbilityRecord {
        key: "Electric Eel ~ Electricity",
        name: "Electricity",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("An electric eel can produce a powerful jolt of electricity from its tail, delivering the jolt with a successful touch attack. On a critical hit, the creature struck must make a DC %1 Fortitude save or be stunned for 1d4 rounds."),
        description_variables: &["ElectricityDC"],
        stat_adjustments: &[],
        source_page: Some("p.119"),
        owners: &["Companion (Eel (Electric))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 33,
    },
    CompanionAbilityRecord {
        key: "Giant Frog ~ Tongue",
        name: "Tongue",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("A giant frog's tongue is a primary attack with reach equal to three times the frog's normal reach (15 feet for a Medium giant frog). A giant frog's tongue deals no damage on a hit, but can be used to grab. A giant frog does not gain the grappled condition while using its tongue in this manner."),
        description_variables: &[],
        stat_adjustments: &[],
        source_page: Some("p.135"),
        owners: &["Companion (Frog (Giant))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 34,
    },
    CompanionAbilityRecord {
        key: "Giant Moray Eel ~ Gnaw",
        name: "Gnaw",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("If a giant moray begins a round with a grabbed foe, it inflicts automatic bite damage (2d6+%1 points of damage). A giant moray eel possesses a second set of jaws in its throat that aid in swallowing - it can make a second bite attack (same attack bonus, 1d6+%2 damage) against a foe it has already grabbed."),
        description_variables: &["STR*3/2", "STR/2"],
        stat_adjustments: &[],
        source_page: Some("p.119"),
        owners: &["Companion (Eel (Giant Moray))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 35,
    },
    CompanionAbilityRecord {
        key: "Goblin Dog ~ Allergic Reaction",
        name: "Allergic Reaction",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Your dander is highly irritating to all creatures save those with the goblinoid subtype. A non-goblinoid creature damaged by your bite, who deals damage to you with a natural weapon or unarmed attack, or who otherwise comes into contact with you (including attempts to grapple or ride you) must make a DC %1 Fortitude save or break out in an itching rash. A creature affected by this rash takes a -2 penalty to Dexterity and Charisma for 1 day (multiple allergic reactions do not stack). Remove disease or any magical healing removes the rash instantly. This is a disease effect."),
        description_variables: &["AllergicReactionDC"],
        stat_adjustments: &[],
        source_page: Some("p.157"),
        owners: &["Companion (Goblin Dog)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 36,
    },
    CompanionAbilityRecord {
        key: "Lizard Monitor ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Bite--injury; save Fort DC %1; onset 1 minute; frequency 1/hour for 6 hours; effect 1d2 Dexterity damage; cure 1 save."),
        description_variables: &["PoisonSaveDC"],
        stat_adjustments: &[],
        source_page: Some("p.194"),
        owners: &["Companion (Lizard (Monitor))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 37,
    },
    CompanionAbilityRecord {
        key: "Octopus ~ Ink Cloud",
        name: "Ink Cloud",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary", "Defensive"],
        description: Some("An octopus can emit a 10ft radius sphere of ink once per minute as a free action. The ink provides total concealment in water, and persists for 1 minute."),
        description_variables: &[],
        stat_adjustments: &[],
        source_page: Some("p.219"),
        owners: &["Companion (Octopus)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 38,
    },
    CompanionAbilityRecord {
        key: "Octopus ~ Jet",
        name: "Jet",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary", "ModifyMovement"],
        description: Some("An octopus can jet backward once per round as a full-round action, at a speed of 200 ft. It must move in a straight line while jetting, and does not provoke attacks of opportunity when it does so."),
        description_variables: &[],
        stat_adjustments: &[],
        source_page: Some("p.219"),
        owners: &["Companion (Octopus)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 39,
    },
    CompanionAbilityRecord {
        key: "Octopus ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Bite-injury; save Fort DC 13; frequency 1/round for 6 rounds; effect 1 Str; cure 1 save."),
        description_variables: &[],
        stat_adjustments: &[],
        source_page: Some("p.219"),
        owners: &["Companion (Octopus)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 40,
    },
    CompanionAbilityRecord {
        key: "Squid ~ Ink Cloud",
        name: "Ink Cloud",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary", "Defensive"],
        description: Some("A squid can emit a %1 foot-radius cloud of ink once per minute as a free action while underwater. This cloud provides total concealment. The ink persists for 1 minute."),
        description_variables: &["InkCloudRadius"],
        stat_adjustments: &[],
        source_page: Some("p.259"),
        owners: &["Companion (Squid)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 41,
    },
    CompanionAbilityRecord {
        key: "Squid ~ Jet",
        name: "Jet",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("A squid can jet in a straight line as a full-round action. It does not provoke attacks of opportunity while jetting."),
        description_variables: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Squid)"],
        source_file: "b1_abilities_companion.lst",
        source_line: 42,
    },
    CompanionAbilityRecord {
        key: "Tyrannosaurus ~ Powerful Bite",
        name: "Powerful Bite",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("A tyrannosaurus applies twice its Strength modifier to bite damage."),
        description_variables: &[],
        stat_adjustments: &[],
        source_page: Some("p.86"),
        owners: &["Companion (Dinosaur (Tyrannosaurus))"],
        source_file: "b1_abilities_companion.lst",
        source_line: 43,
    },
];
