//! bestiary_2 companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py bestiary_2`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `b2_races_familiar.lst` -- 15 companion creature rows
//!   * `b2_abilities_familiar_race.lst` -- 1 companion ability rows

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, NaturalAttackDamageBonus, SkillAbilityDiffBonus, Speed, StatAdjustment};

/// Every bestiary_2 companion creature (15 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Familiar (Compsognathus)",
        name: "Familiar (Compsognathus)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.90"),
        ability_keys: &[],
        external_ability_refs: &["Compsognathus ~ Poison", "Scent"],
        source_file: "b2_races_familiar.lst",
        source_line: 5,
    },
    CompanionRecord {
        key: "Familiar (Snapping Turtle)",
        name: "Familiar (Snapping Turtle)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -6 }, StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.273"),
        ability_keys: &["Snapping Turtle ~ Shell"],
        external_ability_refs: &["Scent"],
        source_file: "b2_races_familiar.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Familiar (Paracletus)",
        name: "Familiar (Paracletus)",
        size: Some("S"),
        speeds: &[Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Aeon|Extraplanar"),
        monster_class: Some("Outsider (Fort/Will):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: 0 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.11"),
        ability_keys: &[],
        external_ability_refs: &["Can't Be Tripped", "Flight Maneuverability", "Paracletus ~ Electricity"],
        source_file: "b2_races_familiar.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Familiar (Silvanshee)",
        name: "Familiar (Silvanshee)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 90 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Agathion|Extraplanar|Good"),
        monster_class: Some("Outsider (Fort/Ref):2"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.21"),
        ability_keys: &[],
        external_ability_refs: &["Flight ~ Su", "Flight Maneuverability", "Know Direction ~ Constant", "Pounce", "Silvanshee ~ Cat's Luck", "Silvanshee ~ Heroic Strength", "Silvanshee ~ Spectral Mist"],
        source_file: "b2_races_familiar.lst",
        source_line: 10,
    },
    CompanionRecord {
        key: "Familiar (Cassisian)",
        name: "Familiar (Cassisian)",
        size: Some("S"),
        speeds: &[Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Angel ~ Cassisian|Extraplanar|Good"),
        monster_class: Some("Outsider (Fort/Ref):2"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Slam", formula: "max(0,STR/2)" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -4 }],
        natural_armor: Some(3),
        source_page: Some("p.26"),
        ability_keys: &[],
        external_ability_refs: &["Can't Be Tripped", "Cassisian ~ Breath Weapon", "Cassisian ~ Change Shape", "Cassisian ~ Lesser Protective Aura", "Cassisian ~ Perfect Memory", "Detect Evil ~ Constant", "Flight Maneuverability", "Know Direction ~ Constant"],
        source_file: "b2_races_familiar.lst",
        source_line: 11,
    },
    CompanionRecord {
        key: "Familiar (Lyrakien)",
        name: "Familiar (Lyrakien)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 80 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Azata|Chaotic|Extraplanar|Good"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -6 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: 4 }, StatAdjustment { ability: "WIS", amount: 6 }, StatAdjustment { ability: "CHA", amount: 10 }],
        natural_armor: None,
        source_page: Some("p.38"),
        ability_keys: &[],
        external_ability_refs: &["Detect Evil ~ Constant", "Detect Magic ~ Constant", "Flight Maneuverability", "Freedom of Movement ~ Constant", "Lyrakien ~ Starlight Blast", "Lyrakien ~ Traveler's Friend", "Resistance to Cold", "Resistance to Fire"],
        source_file: "b2_races_familiar.lst",
        source_line: 12,
    },
    CompanionRecord {
        key: "Familiar (Brownie)",
        name: "Familiar (Brownie)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Fey"),
        race_subtype: None,
        monster_class: Some("Fey:1"),
        type_segments: &["Companion", "Familiar", "Fey"],
        natural_attacks: &[],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: 4 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: 6 }],
        natural_armor: None,
        source_page: Some("p.49"),
        ability_keys: &[],
        external_ability_refs: &["Brownie ~ Bonus vs Illusions"],
        source_file: "b2_races_familiar.lst",
        source_line: 13,
    },
    CompanionRecord {
        key: "Familiar (Cacodaemon)",
        name: "Familiar (Cacodaemon)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Daemon|Evil|Extraplanar"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }, StatAdjustment { ability: "INT", amount: -2 }],
        natural_armor: Some(4),
        source_page: Some("p.64"),
        ability_keys: &[],
        external_ability_refs: &["Cacodaemon ~ Change Shape", "Cacodaemon ~ Disease", "Cacodaemon ~ Soul Lock", "Detect Good ~ Constant", "Detect Magic ~ Constant", "Fast Healing", "Flight Maneuverability"],
        source_file: "b2_races_familiar.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Familiar (Elemental (Ice/Small))",
        name: "Familiar (Elemental (Ice/Small))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Air|Cold|Elemental|Extraplanar|Water"),
        monster_class: Some("Outsider (Fort/Ref):2"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Slam", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "INT", amount: -6 }],
        natural_armor: Some(6),
        source_page: Some("p.114"),
        ability_keys: &[],
        external_ability_refs: &["Can't Be Tripped", "Ice Elemental ~ Burrow", "Ice Elemental ~ Cold", "Ice Elemental ~ Ice Glide", "Ice Elemental ~ Icewalking", "Ice Elemental ~ Numbing Cold", "Ice Elemental ~ Snow Vision"],
        source_file: "b2_races_familiar.lst",
        source_line: 15,
    },
    CompanionRecord {
        key: "Familiar (Elemental (Lightning/Small))",
        name: "Familiar (Elemental (Lightning/Small))",
        size: Some("S"),
        speeds: &[Speed { mode: "Fly", feet: 100 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Air|Elemental|Extraplanar"),
        monster_class: Some("Outsider (Fort/Ref):2"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Slam", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.116"),
        ability_keys: &[],
        external_ability_refs: &["Flight Maneuverability", "Immunity to electricity", "Lightning Elemental ~ Electricity", "Lightning Elemental ~ Metal Mastery", "Lightning Elemental ~ Spark Leap"],
        source_file: "b2_races_familiar.lst",
        source_line: 16,
    },
    CompanionRecord {
        key: "Familiar (Elemental (Magma/Small))",
        name: "Familiar (Elemental (Magma/Small))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Burrow", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Earth|Elemental|Extraplanar|Fire"),
        monster_class: Some("Outsider (Fort/Ref):2"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Slam", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "INT", amount: -6 }],
        natural_armor: Some(5),
        source_page: Some("p.118"),
        ability_keys: &[],
        external_ability_refs: &["Burn", "Magma Elemental ~ Earth Glide", "Magma Elemental ~ Lava Puddle"],
        source_file: "b2_races_familiar.lst",
        source_line: 17,
    },
    CompanionRecord {
        key: "Familiar (Elemental (Mud/Small))",
        name: "Familiar (Elemental (Mud/Small))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Burrow", feet: 10 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Outsider"),
        race_subtype: Some("Earth|Elemental|Extraplanar|Water"),
        monster_class: Some("Outsider (Fort/Ref):2"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Slam", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -6 }],
        natural_armor: Some(6),
        source_page: Some("p.120"),
        ability_keys: &[],
        external_ability_refs: &["Immunity to acid", "Mud Elemental ~ Earth Glide", "Mud Elemental ~ Entrap"],
        source_file: "b2_races_familiar.lst",
        source_line: 18,
    },
    CompanionRecord {
        key: "Familiar (Arbiter)",
        name: "Familiar (Arbiter)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Extraplanar|Inevitable|Lawful"),
        monster_class: Some("Outsider (Fort/Will):2"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: None,
        source_page: Some("p.162"),
        ability_keys: &[],
        external_ability_refs: &["Arbiter ~ Constant Vigilance", "Arbiter ~ Electrical Burst", "Arbiter ~ Locate Inevitable", "Detect Chaos ~ Constant", "Flight Maneuverability"],
        source_file: "b2_races_familiar.lst",
        source_line: 19,
    },
    CompanionRecord {
        key: "Familiar (Voidworm)",
        name: "Familiar (Voidworm)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Extraplanar|Protean ~ Voidworm|Shapechanger"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -2 }, StatAdjustment { ability: "WIS", amount: -2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.217"),
        ability_keys: &[],
        external_ability_refs: &["Can't Be Tripped", "Detect Law ~ Constant", "Fast Healing", "Flight Maneuverability", "Voidworm ~ Change Shape", "Voidworm ~ Confusion"],
        source_file: "b2_races_familiar.lst",
        source_line: 20,
    },
    CompanionRecord {
        key: "Familiar (Cythnigot)",
        name: "Familiar (Cythnigot)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Evil|Extraplanar|Qlippoth"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "WIS", amount: -2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.221"),
        ability_keys: &[],
        external_ability_refs: &["Cythnigot ~ Horrific Appearance", "Cythnigot ~ Spores", "Detect Law ~ Constant", "Detect Magic ~ Constant", "Fly ~ Constant", "Telepathy ~ Touch"],
        source_file: "b2_races_familiar.lst",
        source_line: 21,
    },
];

/// Every bestiary_2 companion ability record (1 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Snapping Turtle ~ Shell",
        name: "Shell",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("As a move action, a snapping turtle can pull its extremities and head into its shell.  It cannot move or attack as long as it remains in this state, but its armor bonus from natural armor increases by +4 as long as it does."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.273"),
        owners: &["Familiar (Snapping Turtle)"],
        cross_book_owners: &[],
        source_file: "b2_abilities_familiar_race.lst",
        source_line: 6,
    },
];
