//! ARG Combat feats -- generated from the real `arg_feats.lst`
//! corpus (SD-27 Cycle E2.1/E2.2 per-book pre-build). Not hand-authored --
//! see `feats.rs`'s own doc comment for the generation method.
//! See `feats.rs` for the full corpus-coverage/exclusion accounting.

use super::super::feats::{FeatCategory, FeatEffectBonus, FeatTableEntry};

pub const COMBAT_TABLE: &[FeatTableEntry] = &[
    FeatTableEntry { key: "Blazing Aura", category: FeatCategory::Combat, name: "Blazing Aura", description: Some("An inferno rages inside you, causing your body to radiate intense heat."), effect: None },
    FeatTableEntry { key: "Blistering Feint", category: FeatCategory::Combat, name: "Blistering Feint", description: Some("Your foes flinch from the heat of your weapon, giving you an opportunity to slip past their defenses."), effect: None },
    FeatTableEntry { key: "Blood Beak", category: FeatCategory::Combat, name: "Blood Beak", description: Some("Your bleed attack is bloody and dangerous."), effect: Some(&[FeatEffectBonus { qualifiers: &["WEAPONPROF=Beak", "DAMAGESIZE", "1"] }]) },
    FeatTableEntry { key: "Blundering Defense", category: FeatCategory::Combat, name: "Blundering Defense", description: Some("Your feverish and sometimes comical defensive techniques offer enough distraction to aid allies."), effect: None },
    FeatTableEntry { key: "Bullying Blow", category: FeatCategory::Combat, name: "Bullying Blow", description: Some("With a simple hit, you more easily intimidate an opponent."), effect: None },
    FeatTableEntry { key: "Cautious Fighter", category: FeatCategory::Combat, name: "Cautious Fighter", description: Some("You care more about survival than victory."), effect: None },
    FeatTableEntry { key: "Claw Pounce", category: FeatCategory::Combat, name: "Claw Pounce", description: Some("You can charge and make an attack with your paws."), effect: None },
    FeatTableEntry { key: "Cleave Through", category: FeatCategory::Combat, name: "Cleave Through", description: Some("You are ferocious at hewing smaller opponents."), effect: None },
    FeatTableEntry { key: "Cloven Helm", category: FeatCategory::Combat, name: "Cloven Helm", description: Some("Your helm turns aside lethal blows."), effect: None },
    FeatTableEntry { key: "Critical Versatility", category: FeatCategory::Combat, name: "Critical Versatility", description: Some("An open mind and combat training grant versatility to your critical hits."), effect: None },
    FeatTableEntry { key: "Demoralizing Lash", category: FeatCategory::Combat, name: "Demoralizing Lash", description: Some("You cow your enemies with the lash of a whip."), effect: None },
    FeatTableEntry { key: "Dented Helm", category: FeatCategory::Combat, name: "Dented Helm", description: Some("Your helm protects you from hard hits."), effect: None },
    FeatTableEntry { key: "Desperate Swing", category: FeatCategory::Combat, name: "Desperate Swing", description: Some("You land your most telling blows in desperate situations."), effect: None },
    FeatTableEntry { key: "Destroyer's Blessing", category: FeatCategory::Combat, name: "Destroyer's Blessing", description: Some("Breaking things adds to your power."), effect: None },
    FeatTableEntry { key: "Elven Battle Training", category: FeatCategory::Combat, name: "Elven Battle Training", description: Some("You have been specially trained to wield a variety of traditional elven weapons."), effect: None },
    FeatTableEntry { key: "Ferocious Tenacity", category: FeatCategory::Combat, name: "Ferocious Tenacity", description: Some("You spit in the face of death."), effect: None },
    FeatTableEntry { key: "Fire Hand", category: FeatCategory::Combat, name: "Fire Hand", description: Some("Born with a torch in your hand, you have a gift with anything that burns."), effect: None },
    FeatTableEntry { key: "Giant Killer", category: FeatCategory::Combat, name: "Giant Killer", description: Some("Your cleaving strokes menace giants and larger foes."), effect: None },
    FeatTableEntry { key: "Gloom Strike", category: FeatCategory::Combat, name: "Gloom Strike", description: Some("Few creatures are as accustomed to fighting in the shadows as you."), effect: None },
    FeatTableEntry { key: "Gnome Weapon Focus", category: FeatCategory::Combat, name: "Gnome Weapon Focus", description: Some("Your extensive training with traditional gnome weapons gives you an advantage."), effect: Some(&[FeatEffectBonus { qualifiers: &["WEAPONPROF=TYPE.Gnome", "TOHIT", "1"] }]) },
    FeatTableEntry { key: "Goblin Cleaver", category: FeatCategory::Combat, name: "Goblin Cleaver", description: Some("You are ferocious at hewing smaller opponents."), effect: None },
    FeatTableEntry { key: "Goblin Gunslinger", category: FeatCategory::Combat, name: "Goblin Gunslinger", description: Some("You have learned how to fire the big guns."), effect: Some(&[FeatEffectBonus { qualifiers: &["WEAPONPROF=Firearms", "PCSIZE", "1"] }]) },
    FeatTableEntry { key: "Great Hatred", category: FeatCategory::Combat, name: "Great Hatred", description: Some("Your rage burns with vast intensity."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "Gnome_Hatred_AttackBonus", "1"] }]) },
    FeatTableEntry { key: "Grudge Fighter", category: FeatCategory::Combat, name: "Grudge Fighter", description: Some("You feel great anger at anyone who dares to attack you, and this fury makes your own attacks that much stronger."), effect: None },
    FeatTableEntry { key: "Hard-Headed", category: FeatCategory::Combat, name: "Hard-Headed", description: Some("Your thick skull is almost a weapon unto itself."), effect: None },
    FeatTableEntry { key: "Improved Low Blow", category: FeatCategory::Combat, name: "Improved Low Blow", description: Some("You are adept at hitting larger opponents where it hurts."), effect: None },
    FeatTableEntry { key: "Improved Surprise Follow-Through", category: FeatCategory::Combat, name: "Improved Surprise Follow-Through", description: Some("You follow up an attack with a surprising series of sweeping blows."), effect: None },
    FeatTableEntry { key: "Inner Flame", category: FeatCategory::Combat, name: "Inner Flame", description: Some("Your body generates so much heat that your mere touch scorches your enemies."), effect: None },
    FeatTableEntry { key: "Kobold Ambusher", category: FeatCategory::Combat, name: "Kobold Ambusher", description: Some("You are adept at moving fast and staying hidden."), effect: None },
    FeatTableEntry { key: "Kobold Sniper", category: FeatCategory::Combat, name: "Kobold Sniper", description: Some("You snipe quickly, making it harder for others to find the location of your attack."), effect: None },
    FeatTableEntry { key: "Lucky Strike", category: FeatCategory::Combat, name: "Lucky Strike", description: Some("Your luck increases the potency of your weapon attacks."), effect: None },
    FeatTableEntry { key: "Martial Mastery", category: FeatCategory::Combat, name: "Martial Mastery", description: Some("You broaden your study of weapons to encompass multiple similar weapons."), effect: None },
    FeatTableEntry { key: "Martial Versatility", category: FeatCategory::Combat, name: "Martial Versatility", description: Some("You further broaden your study of weapons to encompass multiple similar weapons."), effect: None },
    FeatTableEntry { key: "Nimble Striker", category: FeatCategory::Combat, name: "Nimble Striker", description: Some("You were born to charge your enemies and nobody does it better."), effect: None },
    FeatTableEntry { key: "Orc Hewer", category: FeatCategory::Combat, name: "Orc Hewer", description: Some("You are ferocious at hewing your enemies, especially orcs."), effect: None },
    FeatTableEntry { key: "Orc Weapon Expertise", category: FeatCategory::Combat, name: "Orc Weapon Expertise", description: Some("You can do more with the weapons orcs favor the most."), effect: Some(&[FeatEffectBonus { qualifiers: &["ABILITYPOOL", "Orc Weapon Expertise", "1"] }]) },
    FeatTableEntry { key: "Reverse-Feint", category: FeatCategory::Combat, name: "Reverse-Feint", description: Some("You can goad an opponent into attacking you in order to make your counter attack all the more powerful."), effect: None },
    FeatTableEntry { key: "Risky Striker", category: FeatCategory::Combat, name: "Risky Striker", description: Some("You can make yourself a little more vulnerable to larger creatures in order to land a devastating blow."), effect: None },
    FeatTableEntry { key: "Scorching Weapons", category: FeatCategory::Combat, name: "Scorching Weapons", description: Some("Elemental fire stirs within your body, boiling your blood and rendering you resistant to flame."), effect: None },
    FeatTableEntry { key: "Sea Hunter", category: FeatCategory::Combat, name: "Sea Hunter", description: Some("Your blows knock swimming opponents off balance."), effect: None },
    FeatTableEntry { key: "Sharpclaw", category: FeatCategory::Combat, name: "Sharpclaw", description: Some("Your nails are large and strong."), effect: None },
    FeatTableEntry { key: "Shatterspell", category: FeatCategory::Combat, name: "Shatterspell", description: Some("Your mighty blows shatter your enemy's magic."), effect: None },
    FeatTableEntry { key: "Spit Venom", category: FeatCategory::Combat, name: "Spit Venom", description: Some("You have mastered the nagaji warrior technique of spitting venom into your opponent's eyes."), effect: None },
    FeatTableEntry { key: "Surprise Follow-Through", category: FeatCategory::Combat, name: "Surprise Follow-Through", description: Some("When striking one opponent, you catch its ally off guard."), effect: None },
    FeatTableEntry { key: "Surprise Strike", category: FeatCategory::Combat, name: "Surprise Strike", description: Some("You actually seem to do more damage when frantically trying to avoid your enemies."), effect: None },
    FeatTableEntry { key: "Sympathetic Rage", category: FeatCategory::Combat, name: "Sympathetic Rage", description: Some("Seeing an ally rage fills you with your own fury."), effect: None },
    FeatTableEntry { key: "Tail Terror", category: FeatCategory::Combat, name: "Tail Terror", description: Some("You have strengthened your tail enough to make slap attacks with it."), effect: Some(&[FeatEffectBonus { qualifiers: &["SLOTS", "WEAPON", "1", "PREEQUIP:1,TYPE=KoboldTailAttachment"] }]) },
    FeatTableEntry { key: "Tangle Feet", category: FeatCategory::Combat, name: "Tangle Feet", description: Some("Creatures who cross your path find themselves tripping over their own feet."), effect: None },
    FeatTableEntry { key: "Taskmaster", category: FeatCategory::Combat, name: "Taskmaster", description: Some("You intimidate weaker allies into reckless ferocity."), effect: None },
    FeatTableEntry { key: "Tree Hanger", category: FeatCategory::Combat, name: "Tree Hanger", description: Some("You can use your tail to defend against trip attacks and to hang from nearby protrusions."), effect: Some(&[FeatEffectBonus { qualifiers: &["VAR", "CMD_Trip", "2"] }]) },
    FeatTableEntry { key: "Uncanny Defense", category: FeatCategory::Combat, name: "Uncanny Defense", description: Some("Your instinct for self-preservation gives you many advantages."), effect: None },
    FeatTableEntry { key: "Vast Hatred", category: FeatCategory::Combat, name: "Vast Hatred", description: Some("Your rage stretches beyond normal bounds."), effect: None },
];
