//! Package-backed mirror of the compiled `rules_tables` module `ultimate_magic::feat_tables` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

use super::super::crb::feats::FeatCategory as SharedFeatCategory;
pub use rt::ultimate_magic::feat_tables::FeatCategory;
pub use rt::ultimate_magic::feat_tables::UmFeatEntry;
pub fn feat_tables() -> &'static [UmFeatEntry] {
    crate::rules_core::rules_catalog::rows::<UmFeatEntry>("ultimate_magic/feat_tables/feat_tables")
}
