//! Package-backed mirror of the compiled `rules_tables` module `ultimate_magic::magus_features` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::ultimate_magic::magus_features::arcane_pool;
pub use rt::ultimate_magic::magus_features::arcane_pool_enhancement_bonus;
pub use rt::ultimate_magic::magus_features::armor_proficiency_level;
pub use rt::ultimate_magic::magus_features::bonus_feats_pool;
pub use rt::ultimate_magic::magus_features::fighter_training_level;
pub use rt::ultimate_magic::magus_features::magus_arcana_pool;
