//! Corpus `feat` records that belong to an ALREADY-COMPILED book whose
//! hand-authored per-book feat table does not hold them — the
//! `not-ingested` population of `docs/work-inventory.json`'s `feat` kind,
//! closed corpus-wide.
//!
//! **GENERATED — do not edit by hand.** Regenerate with
//! `PCGEN_CORPUS_ROOT=<pcgen>/data cargo run --locked --bin gen_feat_gap_tables`.
//! The generator applies `v06_work_inventory`'s own record predicate for
//! `Kind::Feat`, so a row here is exactly a row that inventory reported
//! `not-ingested`.
//!
//! `description` is the record's `DESC:` joined with its `BENEFIT:` when
//! both are present, and `None` when it carries neither — never a
//! fabricated placeholder. `prerequisites` is every top-level `PRE`-family
//! token verbatim, and `None` (never `Some(&[])`) when there are none.
//! `category` is the corpus `TYPE:` token's first dot-segment verbatim,
//! NOT a per-book `FeatCategory` variant name: a gap row has no per-book
//! table to take a variant from, and mapping the corpus facet onto some
//! book's enum would invent a classification the corpus never made.
//!
//! Total: 83 rows.

use super::feats_all::FeatCatalogRecord;
use super::RuleSetId;

/// The gap rows for one rule set, or an empty slice when that book has
/// none. Chained AFTER the book's hand-authored records by
/// `feats_all::all_feat_tables`, so a first-match key lookup keeps
/// resolving to the hand-authored record.
pub fn feat_gap_rows_for(rule_set: RuleSetId) -> &'static [FeatCatalogRecord] {
    match rule_set {
        RuleSetId::Crb => CORE_RULEBOOK_FEAT_GAP_ROWS,
        RuleSetId::Ce => CORE_ESSENTIALS_FEAT_GAP_ROWS,
        RuleSetId::Arg => ADVANCED_RACE_GUIDE_FEAT_GAP_ROWS,
        RuleSetId::Uc => ULTIMATE_COMBAT_FEAT_GAP_ROWS,
        RuleSetId::Ui => ULTIMATE_INTRIGUE_FEAT_GAP_ROWS,
        RuleSetId::Um => ULTIMATE_MAGIC_FEAT_GAP_ROWS,
        RuleSetId::Upsi => ULTIMATE_PSIONICS_FEAT_GAP_ROWS,
        RuleSetId::Uw => ULTIMATE_WILDERNESS_FEAT_GAP_ROWS,
        _ => &[],
    }
}

/// core_rulebook — 1 record(s) the hand-authored `core_rulebook` feat table does not hold.
pub static CORE_RULEBOOK_FEAT_GAP_ROWS: &[FeatCatalogRecord] = &[
    FeatCatalogRecord { key: "Leadership Score", category: "Special", name: "Leadership Score", description: None, prerequisites: None },
];

/// core_essentials — 15 record(s) the hand-authored `core_essentials` feat table does not hold.
pub static CORE_ESSENTIALS_FEAT_GAP_ROWS: &[FeatCatalogRecord] = &[
    FeatCatalogRecord { key: "Ability Focus", category: "General", name: "Ability Focus", description: Some("One of this creature's special attacks is particularly difficult to resist. Choose one of the creature's special attacks. Add +2 to the DC for all saving throws against the special attack on which the creature focuses. Special: A creature can gain this feat multiple times. Its effects do not stack. Each time the creature takes the feat, it applies to a different special attack."), prerequisites: Some(&["PREABILITY:1,CATEGORY=Ability Focus,TYPE.Ability Focus"]) },
    FeatCatalogRecord { key: "Awesome Blow", category: "General", name: "Awesome Blow", description: Some("This creature can send opponents flying. As a standard action, the creature may perform an awesome blow combat manuever. If the creature's maneuver succeeds against a corporeal opponent smaller than itself, its opponent is knocked flying 10 feet in a direction of the attacking creature's choice and falls prone. The attacking creature can only push the opponent in a straight line, and the opponent can't move closer to the attacking creature than the square it started in. If an obstacle prevents the completion of the opponent's move, the opponent and the obstacle each take 1d6 points of damage, and the opponent is knocked prone in the space adjacent to the obstacle."), prerequisites: Some(&["PREABILITY:2,CATEGORY=FEAT,Power Attack,Improved Bull Rush", "PRESIZEGTEQ:L", "PRESTAT:1,STR=25"]) },
    FeatCatalogRecord { key: "Craft Construct", category: "ItemCreation", name: "Craft Construct", description: Some("You can create construct creatures like golems. You can create any construct whose prerequisites you meet. The act of animating a construct takes one day for each 1,000 gp in its market price. To create a construct, you must use up raw materials costing half of its base price, plus the full cost of the basic body created for the construct. Each construct has a special section that summarizes its costs and other prerequisites. A newly created construct has average hit points for its Hit Dice."), prerequisites: Some(&["PREABILITY:2,CATEGORY=FEAT,Craft Magic Arms and Armor,Craft Wondrous Item", "PREMULT:1,[PRECLASS:1,SPELLCASTER=5],[PREVARGTEQ:CasterLevel_Highest,5]"]) },
    FeatCatalogRecord { key: "Empower Spell-Like Ability ~ Ability", category: "General", name: "Empower Spell-Like Ability ~ Ability", description: Some("One of this creature's spell-like abilities is particularly potent and powerful. Choose one of the creature's spell-like abilities, subject to the restrictions below. The creature can use that ability as an empowered spell-like ability three times per day (or less, if the ability is normally usable only once or twice per day). When a creature uses an empowered spell-like ability, all variable, numeric effects of the spell-like ability are increased by half (+50%%). Saving throws and opposed rolls are not affected. Spell-like abilities without random variables are not affected. The creature can only select a spell-like ability duplicating a spell with a level less than or equal to 1/2 its caster level (round down) - 2. For a summary, see the table in the description of the Quicken Spell-Like Ability feat on page 316. Special: This feat can be taken multiple times. Each time it is taken, the creature can apply it to a different spell-like ability."), prerequisites: Some(&["PRETEXT:Spell-like ability at caster level 6th or higher."]) },
    FeatCatalogRecord { key: "Empower Spell-Like Ability ~ Spell", category: "General", name: "Empower Spell-Like Ability ~ Spell", description: Some("One of this creature's spell-like abilities is particularly potent and powerful. Choose one of the creature's spell-like abilities, subject to the restrictions below. The creature can use that ability as an empowered spell-like ability three times per day (or less, if the ability is normally usable only once or twice per day). When a creature uses an empowered spell-like ability, all variable, numeric effects of the spell-like ability are increased by half (+50%%). Saving throws and opposed rolls are not affected. Spell-like abilities without random variables are not affected. The creature can only select a spell-like ability duplicating a spell with a level less than or equal to 1/2 its caster level (round down) - 2. For a summary, see the table in the description of the Quicken Spell-Like Ability feat on page 316. Special: This feat can be taken multiple times. Each time it is taken, the creature can apply it to a different spell-like ability."), prerequisites: Some(&["PRETEXT:Spell-like ability at caster level 6th or higher."]) },
    FeatCatalogRecord { key: "Flyby Attack", category: "General", name: "Flyby Attack", description: Some("This creature can make an attack before and after it moves while flying. When flying, the creature can take a move action and another standard action at any point during the move. The creature cannot take a second move action during a round when it makes a flyby attack. Normal: Without this feat, the creature takes a standard action either before or after its move."), prerequisites: Some(&["PREMOVE:1,Fly=1"]) },
    FeatCatalogRecord { key: "Hover", category: "General", name: "Hover", description: Some("This creature can hover in place with ease and can kick up clouds of dust and debris. A creature with this feat can halt its movement while flying, allowing it to hover without needing to make a Fly skill check. If a creature of size Large or larger with this feat hovers within 20 feet of the ground in an area with lots of loose debris, the draft from its wings creates a hemispherical cloud with a radius of 60 feet. The winds generated can snuff torches, small campfires, exposed lanterns, and other small, open flames of non-magical origin. Clear vision within the cloud is limited to 10 feet. Creatures have concealment at 15 to 20 feet (20%% miss chance). At 25 feet or more, creatures have total concealment (50%% miss chance, and opponents cannot use sight to locate the creature). Normal: Without this feat, a creature must make a Fly skill check to hover and the creature does not create a cloud of debris while hovering."), prerequisites: Some(&["PREMOVE:1,Fly=1"]) },
    FeatCatalogRecord { key: "Improved Natural Armor", category: "General", name: "Improved Natural Armor", description: Some("This creature's hide is tougher than most. The creature's natural armor bonus increases by +1. Special: A creature can gain this feat multiple times. Each time the creature takes the feat, its natural armor bonus increases by another point."), prerequisites: Some(&["PRESTAT:1,CON=13", "PREVARGTEQ:BONUS.COMBAT.AC.NaturalArmor,1"]) },
    FeatCatalogRecord { key: "Improved Natural Attack", category: "General", name: "Improved Natural Attack", description: Some("Attacks made by one natural weapon leaves vicious wounds. Choose one of the creature's natural attack forms. The damage for this natural attack increases by one step on the following list, as if the creature's size had increased by one category. Damage dice increase as follows: 1d2, 1d3, 1d4, 1d6, 1d8, 2d6, 3d6, 4d6, 6d6, 8d6, 12d6. A weapon or attack that deals 1d10 points of damage increases as follows: 1d10, 2d8, 3d8, 4d8, 6d8, 8d8, 12d8."), prerequisites: Some(&["PRETOTALAB:4", "PREWEAPONPROF:1,TYPE.Natural"]) },
    FeatCatalogRecord { key: "Multiattack", category: "General", name: "Multiattack", description: Some("This creature is particularly skilled at making attacks with its natural weapons. The creature's secondary attacks with natural weapons take only a -2 penalty. Normal: Without this feat, the creature's secondary attacks with natural weapons take a -5 penalty."), prerequisites: Some(&["PREWEAPONPROF:3,TYPE.Natural"]) },
    FeatCatalogRecord { key: "Multiweapon Fighting", category: "General", name: "Multiweapon Fighting", description: Some("This multi-armed creature is skilled at making attacks with multiple weapons. Penalties for fighting with multiple weapons are reduced by -2 with the primary hand and by -6 with off hands. Normal: A creature without this feat takes a -6 penalty on attacks made with its primary hand and a -10 penalty on attacks made with all of its off hands. (It has one primary hand, and all the others are off hands.) See Two-Weapon Fighting in the Pathfinder RPG Core Rulebook. Special: This feat replaces the Two-Weapon Fighting feat for creatures with more than two arms."), prerequisites: Some(&["PREHANDSGTEQ:3", "PREMULT:1,[PREVARGTEQ:PreStatScore_DEX,13],[PREVARGTEQ:FeatDexRequirement,13]"]) },
    FeatCatalogRecord { key: "Quicken Spell-Like Ability ~ Ability", category: "General", name: "Quicken Spell-Like Ability ~ Ability", description: Some("This creature can use one of its spell-like abilities with next to no effort. Choose one of the creature's spell-like abilities, subject to the restrictions described in this feat. The creature can use the chosen spell-like ability as a quickened spell-like ability three times per day (or less, if the ability is normally usable only once or twice per day). Using a quickened spell-like ability is a swift action that does not provoke an attack of opportunity. The creature can perform another action-including the use of another spell-like ability (but not another swift action)-in the same round that it uses a quickened spelllike ability. The creature may use only one quickened spell-like ability per round. The creature can only select a spell-like ability duplicating a spell with a level less than or equal to 1/2 its caster level (round down) - 4. For a summary, see the table on page 316. A spell-like ability that duplicates a spell with a casting time greater than 1 full round cannot be quickened. Normal: The use of a spell-like ability normally requires a standard action (at the very least) and provokes an attack of opportunity. Special: This feat can be taken multiple times. Each time it is taken, the creature can apply it to a different one of its spell-like abilities."), prerequisites: Some(&["PRETEXT:Spell-like ability at caster level 10th or higher."]) },
    FeatCatalogRecord { key: "Quicken Spell-Like Ability ~ Spell", category: "General", name: "Quicken Spell-Like Ability ~ Spell", description: Some("This creature can use one of its spell-like abilities with next to no effort. Choose one of the creature's spell-like abilities, subject to the restrictions described in this feat. The creature can use the chosen spell-like ability as a quickened spell-like ability three times per day (or less, if the ability is normally usable only once or twice per day). Using a quickened spell-like ability is a swift action that does not provoke an attack of opportunity. The creature can perform another action-including the use of another spell-like ability (but not another swift action)-in the same round that it uses a quickened spelllike ability. The creature may use only one quickened spell-like ability per round. The creature can only select a spell-like ability duplicating a spell with a level less than or equal to 1/2 its caster level (round down) - 4. For a summary, see the table on page 316. A spell-like ability that duplicates a spell with a casting time greater than 1 full round cannot be quickened. Normal: The use of a spell-like ability normally requires a standard action (at the very least) and provokes an attack of opportunity. Special: This feat can be taken multiple times. Each time it is taken, the creature can apply it to a different one of its spell-like abilities."), prerequisites: Some(&["PRETEXT:Spell-like ability at caster level 10th or higher."]) },
    FeatCatalogRecord { key: "Snatch", category: "General", name: "Snatch", description: Some("This creature can grab other creatures with ease. The creature can start a grapple when it hits with a claw or bite attack, as though it had the grab ability. If it grapples a creature three or more sizes smaller, it squeezes each round for automatic bite or claw damage with a successful grapple check. A snatched opponent held in the creature's mouth is not allowed a Reflex save against the creature's breath weapon, if it has one. The creature can drop a creature it has snatched as a free action or use a standard action to fling it aside. A flung creature travels 1d6 x 10 feet, and takes 1d6 points of damage per 10 feet traveled. If the creature flings a snatched opponent while flying, the opponent takes this amount or falling damage, whichever is greater."), prerequisites: Some(&["PRESIZEGTEQ:H"]) },
    FeatCatalogRecord { key: "Wingover", category: "General", name: "Wingover", description: Some("This creature can make turns with ease while flying. Once each round, a creature with this feat can turn up to 180 degrees as a free action without making a Fly skill check. This free turn does not consume any additional movement from the creature. Normal: A flying creature can turn up to 90 degrees by making a DC 15 Fly skill check and expending 5 feet of movement. A flying creature can turn up to 180 degrees by making a DC 20 Fly skill check and expending 10 feet of movement."), prerequisites: Some(&["PREMOVE:1,Fly=1"]) },
];

/// advanced_race_guide — 48 record(s) the hand-authored `advanced_race_guide` feat table does not hold.
pub static ADVANCED_RACE_GUIDE_FEAT_GAP_ROWS: &[FeatCatalogRecord] = &[
    FeatCatalogRecord { key: "Multitalented Mastery ~ Bonus Hit Point", category: "MultitalentedMasteryBonus", name: "Bonus Hit Point", description: None, prerequisites: None },
    FeatCatalogRecord { key: "Multitalented Mastery ~ Bonus Skill Point", category: "MultitalentedMasteryBonus", name: "Bonus Skill Rank", description: None, prerequisites: None },
    FeatCatalogRecord { key: "Mother's Gift ~ Hag Claws", category: "Extraordinary", name: "Hag Claws", description: Some("You gain a +1 bonus on attack and damage rolls with your claws."), prerequisites: None },
    FeatCatalogRecord { key: "Mother's Gift ~ Surprisingly Tough", category: "Extraordinary", name: "Surprisingly Tough", description: Some("Your natural armor bonus increases by +1."), prerequisites: None },
    FeatCatalogRecord { key: "Mother's Gift ~ Uncanny Resistance", category: "Supernatural", name: "Uncanny Resistance", description: Some("You gain spell resistance equal to 6 + your character level. %1.|TL+6"), prerequisites: None },
    FeatCatalogRecord { key: "Angelic Flesh ~ Brazen", category: "AngelicFleshOption", name: "Brazen", description: Some("You take a -2 penalty on Disguise and Stealth checks but gain fire resistance 5 and a +2 bonus on saves against fire effects."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Angelic Blood", "PREFACT:1,TEMPLATES,IsAasimar=true"]) },
    FeatCatalogRecord { key: "Angelic Flesh ~ Golden", category: "AngelicFleshOption", name: "Golden", description: Some("You take a -2 penalty on Disguise and Stealth checks but gain a +2 bonus on saves against blindness, dazzling, patterns, and effects with the light descriptor. When you cast spells or use spell-like abilities that are from the illusion (pattern) subschool or have the light descriptor, you do so at +1 caster level."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Angelic Blood", "PREFACT:1,TEMPLATES,IsAasimar=true"]) },
    FeatCatalogRecord { key: "Angelic Flesh ~ Silver", category: "AngelicFleshOption", name: "Silver", description: Some("You take a -2 penalty on Disguise and Stealth checks but gain a +2 bonus on saves against paralysis, petrification, and poison, and your unarmed strikes or natural weapons count as silver for the purpose of overcoming damage reduction."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Angelic Blood", "PREFACT:1,TEMPLATES,IsAasimar=true"]) },
    FeatCatalogRecord { key: "Angelic Flesh ~ Steel", category: "AngelicFleshOption", name: "Steel", description: Some("You take a -2 penalty on Disguise and Stealth checks but gain a +1 natural armor bonus to AC, and your unarmed strikes or natural weapons count as cold iron for the purpose of overcoming damage reduction."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Angelic Blood", "PREFACT:1,TEMPLATES,IsAasimar=true"]) },
    FeatCatalogRecord { key: "Heavenly Radiance ~ Flare  Burst", category: "HeavenlyRadianceOption", name: "Flare Burst", description: Some("By expending a use of daylight, you may use this spell as a spell-like ability."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Heavenly Radiance", "PRELEVEL:MIN=1"]) },
    FeatCatalogRecord { key: "Heavenly Radiance ~ Wake of Light", category: "HeavenlyRadianceOption", name: "Wake of Light", description: Some("By expending a use of daylight, you may use this spell as a spell-like ability."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Heavenly Radiance", "PRELEVEL:MIN=3"]) },
    FeatCatalogRecord { key: "Heavenly Radiance ~ Searing Light", category: "HeavenlyRadianceOption", name: "Searing Light", description: Some("By expending a use of daylight, you may use this spell as a spell-like ability."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Heavenly Radiance", "PRELEVEL:MIN=5"]) },
    FeatCatalogRecord { key: "Heavenly Radiance ~ Wandering Star Motes", category: "HeavenlyRadianceOption", name: "Wandering Star Motes", description: Some("By expending a use of daylight, you may use this spell as a spell-like ability."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Heavenly Radiance", "PRELEVEL:MIN=7"]) },
    FeatCatalogRecord { key: "Heavenly Radiance ~ Sunbeam", category: "HeavenlyRadianceOption", name: "Sunbeam", description: Some("By expending a use of daylight, you may use this spell as a spell-like ability."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Heavenly Radiance", "PRELEVEL:MIN=9"]) },
    FeatCatalogRecord { key: "Catfolk Exemplar ~ Enhanced Senses", category: "CatfolkExemplarOption", name: "Enhanced Senses", description: Some("If you have low-light vision, you gain the scent catfolk racial trait. If you have the scent racial trait, you gain low-light vision."), prerequisites: Some(&["PREFACT:1,TEMPLATES,IsCatfolk=true"]) },
    FeatCatalogRecord { key: "Catfolk Exemplar ~ Fast Sprinter", category: "CatfolkExemplarOption", name: "Fast Sprinter", description: Some("You gain a 10-foot racial bonus to your speed when using the charge, run, or withdraw actions. If you have the sprinter racial trait, your racial bonus to speed when using the charge, run, or withdraw action increases to a 20-foot bonus."), prerequisites: Some(&["PREFACT:1,TEMPLATES,IsCatfolk=true"]) },
    FeatCatalogRecord { key: "Catfolk Exemplar ~ Sharp Claws", category: "CatfolkExemplarOption", name: "Sharp Claws", description: Some("If you do not have the cat's claws racial trait or the claws of the beast manifestation from the Aspect of the Beast feat , you gain the cat's claws racial trait. If you have either the cat's claws racial trait or the claws of the beast manifestation, your claw damage increases to 1d6."), prerequisites: Some(&["PREFACT:1,TEMPLATES,IsCatfolk=true"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Aquatic)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Aquatic)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Dwarf)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Dwarf)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Elf)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Elf)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Giant)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Giant)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Gnoll)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Gnoll)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Gnome)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Gnome)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Goblinoid)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Goblinoid)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Halfling)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Halfling)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Human)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Human)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Orc)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Orc)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Humanoid (Reptilian)", category: "BloodDrinkerType", name: "Blood Drinker Humanoid (Reptilian)", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Blood Drinker Monstrous Humanoid", category: "BloodDrinkerType", name: "Blood Drinker Monstrous Humanoid", description: Some("You have acquired a taste for the blood of creatures with this subtype."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Blood Drinker"]) },
    FeatCatalogRecord { key: "Umbral Scion Spell ~ Dispel Magic", category: "Umbral Scion Spell", name: "Dispel Magic", description: None, prerequisites: None },
    FeatCatalogRecord { key: "Umbral Scion Spell ~ Divine Favor", category: "Umbral Scion Spell", name: "Divine Favor", description: None, prerequisites: None },
    FeatCatalogRecord { key: "Umbral Scion Spell ~ Suggestion", category: "Umbral Scion Spell", name: "Suggestion", description: None, prerequisites: None },
    FeatCatalogRecord { key: "Black", category: "Kobold Scale Color", name: "Black", description: None, prerequisites: Some(&["PREMULT:1,[PREABILITY:1,CATEGORY=Kobold Scale Color,Black],[!PREABILITY:1,CATEGORY=Kobold Scale Color,TYPE.Kobold Scale Color]"]) },
    FeatCatalogRecord { key: "Blue", category: "Kobold Scale Color", name: "Blue", description: None, prerequisites: Some(&["PREMULT:1,[PREABILITY:1,CATEGORY=Kobold Scale Color,Blue],[!PREABILITY:1,CATEGORY=Kobold Scale Color,TYPE.Kobold Scale Color]"]) },
    FeatCatalogRecord { key: "Green", category: "Kobold Scale Color", name: "Green", description: None, prerequisites: Some(&["PREMULT:1,[PREABILITY:1,CATEGORY=Kobold Scale Color,Green],[!PREABILITY:1,CATEGORY=Kobold Scale Color,TYPE.Kobold Scale Color]"]) },
    FeatCatalogRecord { key: "Red", category: "Kobold Scale Color", name: "Red", description: None, prerequisites: Some(&["PREMULT:1,[PREABILITY:1,CATEGORY=Kobold Scale Color,Red],[!PREABILITY:1,CATEGORY=Kobold Scale Color,TYPE.Kobold Scale Color]"]) },
    FeatCatalogRecord { key: "White", category: "Kobold Scale Color", name: "White", description: None, prerequisites: Some(&["PREMULT:1,[PREABILITY:1,CATEGORY=Kobold Scale Color,White],[!PREABILITY:1,CATEGORY=Kobold Scale Color,TYPE.Kobold Scale Color]"]) },
    FeatCatalogRecord { key: "Kobold Dragon Breath ~ Acid Line", category: "Supernatural", name: "Acid Line", description: Some("You breathe a 30-foot line of acid that deals 2d6 points of acid damage."), prerequisites: None },
    FeatCatalogRecord { key: "Kobold Dragon Breath ~ Electricity Line", category: "Supernatural", name: "Electricity Line", description: Some("You breathe a 30-foot line of electricity that deals 2d6 points of electricity damage."), prerequisites: None },
    FeatCatalogRecord { key: "Kobold Dragon Breath ~ Acid Cone", category: "Supernatural", name: "Acid Cone", description: Some("You breathe a 15-foot cone of acid that deals 2d6 points of acid damage."), prerequisites: None },
    FeatCatalogRecord { key: "Kobold Dragon Breath ~ Fire Cone", category: "Supernatural", name: "Fire Cone", description: Some("You breathe a 15-foot cone of fire that deals 2d6points of fire damage."), prerequisites: None },
    FeatCatalogRecord { key: "Kobold Dragon Breath ~ Cold Cone", category: "Supernatural", name: "Cold Cone", description: Some("You breathe a 15-foot cone of cold that deals 2d6 points of cold damage."), prerequisites: None },
    FeatCatalogRecord { key: "Orc Weapon Expertise ~ Bully", category: "OrcWeaponExpertise", name: "Bully", description: Some("Whenever you wield a weapon that has \"orc\" in its name, you gain the benefit you chose so long as you are actually proficient with that weapon."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]) },
    FeatCatalogRecord { key: "Orc Weapon Expertise ~ Defender", category: "OrcWeaponExpertise", name: "Defender", description: Some("Whenever you wield a weapon that has \"orc\" in its name, you gain the benefit you chose so long as you are actually proficient with that weapon."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]) },
    FeatCatalogRecord { key: "Orc Weapon Expertise ~ Disrupter", category: "OrcWeaponExpertise", name: "Disrupter", description: Some("Whenever you wield a weapon that has \"orc\" in its name, you gain the benefit you chose so long as you are actually proficient with that weapon."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]) },
    FeatCatalogRecord { key: "Orc Weapon Expertise ~ Killer", category: "OrcWeaponExpertise", name: "Killer", description: Some("Whenever you wield a weapon that has \"orc\" in its name, you gain the benefit you chose so long as you are actually proficient with that weapon."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]) },
    FeatCatalogRecord { key: "Orc Weapon Expertise ~ Thug", category: "OrcWeaponExpertise", name: "Thug", description: Some("Whenever you wield a weapon that has \"orc\" in its name, you gain the benefit you chose so long as you are actually proficient with that weapon."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]) },
    FeatCatalogRecord { key: "Orc Weapon Expertise ~ Trickster", category: "OrcWeaponExpertise", name: "Trickster", description: Some("Whenever you wield a weapon that has \"orc\" in its name, you gain the benefit you chose so long as you are actually proficient with that weapon."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Orc Weapon Expertise"]) },
];

/// ultimate_combat — 2 record(s) the hand-authored `ultimate_combat` feat table does not hold.
pub static ULTIMATE_COMBAT_FEAT_GAP_ROWS: &[FeatCatalogRecord] = &[
    FeatCatalogRecord { key: "Gundarme Bonus Feat", category: "General", name: "Gundarme Bonus Feat", description: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=Archetype,Cavalier Archetype ~ Gundarme", "PREABILITY:7,CATEGORY=FEAT,Improved Bull Rush,Mounted Combat,Power Attack,Ride-By Attack,Spirited Charge,Spring Attack,Unseat"]) },
    FeatCatalogRecord { key: "Deathless Master (Vigor/Wounds)", category: "Combat", name: "Deathless Master (Vigor/Wounds)", description: None, prerequisites: Some(&["PREABILITY:4,CATEGORY=FEAT,Deathless Initiate (Vigor/Wound),Diehard (Vigor/Wound),Endurance,Ironhide", "PREFACT:1,TEMPLATES,IsOrc=true,IsHalfOrc=true", "PRERULE:1,DAMAGE_VW", "PRESTAT:2,STR=13,CON=15", "PRETOTALAB:9"]) },
];

/// ultimate_intrigue — 3 record(s) the hand-authored `ultimate_intrigue` feat table does not hold.
pub static ULTIMATE_INTRIGUE_FEAT_GAP_ROWS: &[FeatCatalogRecord] = &[
    FeatCatalogRecord { key: "Gaze Reflection", category: "General", name: "Gaze Reflection", description: Some("The power of your psychic stare wards you from the potent gazes of your enemies. When you avert your eyes from a creature with a gaze attack (including one produced by a spell like eyebite or burning gaze or by a magic item), you can roll twice and select the better result when checking to see whether you are exposed to that gaze attack and when rolling your miss chance on attacks made against that creature (the latter doesn't stack with Blind-Fight). In addition, as a swift action, you can expend one mesmerist trick to make yourself immune to that creature's gaze until the beginning of your next turn. If you expend two mesmerist tricks instead, you gain immunity to that creature's gaze and also reflect its gaze back at it, affecting it with its own gaze. [Special] A mesmerist's hypnotic stare, a witch's or hag's evil eye, and a vampire's dominate ability are treated as gaze attacks for the purpose of this feat, as are abilities that are triggered when looking at a creature, such as a nymph's blinding beauty or a sea hag's horrific appearance. Spending two mesmerist tricks on this feat does not bypass any immunity the creature might have to its own gaze, such as a vampire's immunity to mind-affecting effects or the fact that the nymph's blinding beauty works only on humanoids."), prerequisites: Some(&["PREABILITY:2,CATEGORY=Special Ability,Mesmerist ~ Mesmerist Tricks,Mesmerist ~ Bold Stare", "PRESKILL:1,Spellcraft=10", "PRETEXT:Spellcraft 10 ranks, bold stare and mesmerist tricks class features."]) },
    FeatCatalogRecord { key: "Improved Legendary Influence", category: "General", name: "Improved Legendary Influence", description: Some("Each legend grants you more of its power in return for greater influence. For each spirit you can channel, choose a second feat other than an item creation feat. Whenever you allow a spirit to gain 1 point of influence over you to gain that spirit's associated feat via Legendary Influence, you can allow that spirit to gain 1 additional point of influence over you to gain the second feat."), prerequisites: Some(&["PREABILITY:1,CATEGORY=FEAT,Legendary Influence", "PREABILITY:2,CATEGORY=Special Ability,Medium ~ Propitiation,Medium ~ Spirit", "PRETEXT:Legendary Influence, lesser spirit power and propitiation class features."]) },
    FeatCatalogRecord { key: "Legendary Influence", category: "General", name: "Legendary Influence", description: Some("Each legend grants you more of its power in return for greater influence. Immediately select one feat (other than an item creation feat) for each spirit you can channel. Whenever you perform a seance to channel a spirit, you can allow the spirit to gain 1 point of influence over you to gain access to that spirit's Legendary Influence feat for as long as you channel that spirit. You can use this bonus feat as a prerequisite for any feats granted by a spirit power (such as the champion's legendary champion ability), but not for any other feats."), prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,Medium ~ Spirit", "PRETEXT:Lesser spirit power class feature."]) },
];

/// ultimate_magic — 12 record(s) the hand-authored `ultimate_magic` feat table does not hold.
pub static ULTIMATE_MAGIC_FEAT_GAP_ROWS: &[FeatCatalogRecord] = &[
    FeatCatalogRecord { key: "Unsanctioned Knowledge ~ Level 1", category: "SpecialQuality", name: "Unsanctioned Knowledge ~ Level 1", description: Some("Sub-feat for Unsanctioned Knowledge feat."), prerequisites: None },
    FeatCatalogRecord { key: "Unsanctioned Knowledge ~ Level 2", category: "SpecialQuality", name: "Unsanctioned Knowledge ~ Level 2", description: Some("Sub-feat for Unsanctioned Knowledge feat."), prerequisites: None },
    FeatCatalogRecord { key: "Unsanctioned Knowledge ~ Level 3", category: "SpecialQuality", name: "Unsanctioned Knowledge ~ Level 3", description: Some("Sub-feat for Unsanctioned Knowledge feat."), prerequisites: None },
    FeatCatalogRecord { key: "Unsanctioned Knowledge ~ Level 4", category: "SpecialQuality", name: "Unsanctioned Knowledge ~ Level 4", description: Some("Sub-feat for Unsanctioned Knowledge feat."), prerequisites: None },
    FeatCatalogRecord { key: "Skill Focus Knowledge Arcana", category: "DragonShamanBonus", name: "Skill Focus (Knowledge [Arcana])", description: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=Internal,Dragon Shaman Bonus Feats"]) },
    FeatCatalogRecord { key: "Skill Focus Intimidate", category: "SaurianShamanBonus", name: "Skill Focus (Intimidate)", description: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=Internal,Saurian Shaman Bonus Feats"]) },
    FeatCatalogRecord { key: "Skill Focus Swim", category: "SharkShamanBonus", name: "Skill Focus (Swim)", description: None, prerequisites: Some(&["PREABILITY:1,CATEGORY=Internal,Shark Shaman Bonus Feats"]) },
    FeatCatalogRecord { key: "Experimental Spellcaster", category: "General", name: "Experimental Spellcaster", description: Some("Learn some words of power"), prerequisites: Some(&["PRESPELLTYPE:1,ANY=0"]) },
    FeatCatalogRecord { key: "Experimental Spellcaster First", category: "Internal", name: "Experimental Spellcaster First", description: None, prerequisites: None },
    FeatCatalogRecord { key: "Experimental Spellcaster Rest", category: "Internal", name: "Experimental Spellcaster Rest", description: None, prerequisites: None },
    FeatCatalogRecord { key: "Extra Word", category: "General", name: "Extra Word", description: Some("Learn an additional effect word, or two lower-level words."), prerequisites: Some(&["PREMULT:1,[PRECLASS:1,SPELLCASTER=1],[PREVARGTEQ:CasterLevel_Highest,1]", "PREMULT:1,[PREABILITY:1,CATEGORY=Archetype,TYPE.WordsOfPower],[PREABILITY:1,CATEGORY=FEAT,Experimental Spellcaster]"]) },
    FeatCatalogRecord { key: "Meta Word Mastery", category: "General", name: "Meta Word Mastery", description: Some("You can use meta words three additional times per day, and learn an additional meta word."), prerequisites: Some(&["PREMULT:1,[PREABILITY:1,CATEGORY=Archetype,TYPE.WordsOfPower],[PREABILITY:1,CATEGORY=FEAT,Experimental Spellcaster]"]) },
];

/// ultimate_psionics — 1 record(s) the hand-authored `ultimate_psionics` feat table does not hold.
pub static ULTIMATE_PSIONICS_FEAT_GAP_ROWS: &[FeatCatalogRecord] = &[
    FeatCatalogRecord { key: "Feral Combat Training", category: "Combat", name: "Feral Combat Training", description: Some("You were taught a style of martial arts that relies on the natural weapons from your racial ability or class feature. Choose one of your natural weapons. While using the selected natural weapon, you can apply the effects of feats that have Improved Unarmed Strike as a prerequisite, as well as effects that augment an unarmed strike. &nl; [Special]If you are a monk, you can use the selected natural weapon with your flurry of blows class feature."), prerequisites: Some(&["PREABILITY:2,CATEGORY=FEAT,Improved Unarmed Strike,Weapon Focus (TYPE=Natural)"]) },
];

/// ultimate_wilderness — 1 record(s) the hand-authored `ultimate_wilderness` feat table does not hold.
pub static ULTIMATE_WILDERNESS_FEAT_GAP_ROWS: &[FeatCatalogRecord] = &[
    FeatCatalogRecord { key: "Extended Animal Focus", category: "General", name: "Extended Animal Focus", description: Some("You can assume the aspects of an animal for longer stretches of time than most of your rivals and allies. Add your Wisdom bonus (minimum 1) to the number of minutes per day that you can use your animal focus ability to assume the aspects of an animal."), prerequisites: Some(&["PREABILITY:1,CATEGORY=Special Ability,Hunter ~ Animal Focus"]) },
];
