//! mythic_adventures monster + monster-ability tables, transcribed verbatim
//! from the book's own PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_monster_tables.py mythic_adventures`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst` (which counts `.MOD`/`.COPY` overlays the
//! inventory correctly excludes).
//!
//! Sources, with the line each record was read from carried per row:
//!   * `ma_abilities_race.lst` -- 21 monster-ability rows
//!
//! 21 further ability row(s) in this book are ORPHANS -- no monster
//! row here claims them, so they SHIP with `owners: &[]` rather than being
//! dropped (`decisions.md §20`: an un-ingested row's shape cannot be measured,
//! and Gate 1's DoD needs every unit's shape measured). `list_monster_catalog`
//! only ever walks a monster's OWN `ability_keys`, so an owner-less record here
//! reaches no screen -- reachability is NOT claimed for these, and each key is
//! pinned as a named, provable non-reach in `reach_gate.rs::
//! UNREACHED_RECORD_FINDINGS`, never silently assumed reachable:
//!   * `ma_abilities_race.lst:342`
//!   * `ma_abilities_race.lst:343`
//!   * `ma_abilities_race.lst:344`
//!   * `ma_abilities_race.lst:345`
//!   * `ma_abilities_race.lst:346`
//!   * `ma_abilities_race.lst:347`
//!   * `ma_abilities_race.lst:348`
//!   * `ma_abilities_race.lst:349`
//!   * `ma_abilities_race.lst:350`
//!   * `ma_abilities_race.lst:351`
//!   * `ma_abilities_race.lst:352`
//!   * `ma_abilities_race.lst:353`
//!   * `ma_abilities_race.lst:354`
//!   * `ma_abilities_race.lst:355`
//!   * `ma_abilities_race.lst:357`
//!   * `ma_abilities_race.lst:358`
//!   * `ma_abilities_race.lst:359`
//!   * `ma_abilities_race.lst:360`
//!   * `ma_abilities_race.lst:361`
//!   * `ma_abilities_race.lst:362`
//!   * `ma_abilities_race.lst:363`

use crate::rules_core::rules_tables::monster_chassis::{MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterStatBlock};

/// Every mythic_adventures monster stat block (0 rows).
pub(super) static MONSTERS: &[MonsterStatBlock] = &[
];

/// Every mythic_adventures monster-ability record (21 rows).
pub(super) static MONSTER_ABILITIES: &[MonsterAbilityRecord] = &[
    MonsterAbilityRecord {
        key: "Block Attacks",
        name: "Block Attacks",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Once per round, when the creature is hit by a melee or ranged attack, it can attempt a melee attack using its highest attack bonus. If this result exceeds the result from the attack against it, the creature is unaffected by the attack (as if the attack had missed)."),
        description_variables: &[],
        source_page: Some("p.226"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 342,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dragon Blood",
        name: "Dragon Blood",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The mythic dragon's blood and other fluids are infused with acid, cold, electricity, or fire, matching the dragon's breath weapon energy type. Every time the dragon is damaged by a piercing or slashing weapon, the attacking creature takes energy damage according to Table 6-6: Dragon Blood Damage (or double damage if the attack is a critical hit). Using a reach weapon does not endanger the attacker in this way. If the dragon has the swallow whole ability, it adds this damage to its swallow whole damage."),
        description_variables: &[],
        source_page: Some("p.226"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 343,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dragon Cantrips",
        name: "Dragon Cantrips",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("If the mythic dragon is able to cast arcane spells, it automatically knows all cantrips for its equivalent spellcasting class and can cast them at will."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 344,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dragon Fury",
        name: "Dragon Fury",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("If a mythic dragon confirms a critical hit with a natural weapon, it adds its dragon blood damage to the damage dealt by the natural attack."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 345,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Dual Initiative",
        name: "Dual Initiative",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The monster gets two turns each round, one on its initiative count and another on its initiative count - 20. For example, if the monster's initiative is 23, for its first turn it could make a full attack (and take a 5 foot step) at initiative 23, and for its second turn at initiative 3 it could take a move action and cast a spell. This allows the monster to perform two actions per round that normally take an entire round, such as using a summon monster spell. For the purposes of spells and effects that have a duration of a round or longer or trigger at the beginning of the creature's round or the start of its turn such as saving throws against ongoing effects or taking bleed damage, only the monster's first turn each round counts toward such durations."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 346,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Feral Savagery",
        name: "Feral Savagery",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Under the circumstances listed in the monster's stat block-such as when it makes a full attack or a rend attack-it can immediately attempt an additional attack against an opponent. This attack is made using the creature's full base attack bonus, plus any modifiers appropriate to the situation. This additional attack doesn't stack with similar means of gaining additional attacks, such as the haste spell or a speed weapon. This ability doesn't grant an extra action, so you can't use it to cast a second spell or otherwise take an extra action in the round."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 347,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Fortification",
        name: "Fortification",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The monster has an 50%% chance to treat any critical hit or sneak attack as a normal hit, as if wearing moderate fortification armor."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 348,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Greensight",
        name: "Greensight",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The monster can see through thick plant matter as though it were transparent, usually with a range of 60 feet. Leaves, vines, greenery, and undergrowth offer no concealment to the monster's sight, though solid wood still blocks its line of sight."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 349,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Lingering Breath",
        name: "Lingering Breath",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The creature can expend one use of mythic power as a free action when it uses its breath weapon to make the area radiate energy damage (of the same type as the breath weapon) for 1 round per mythic rank. Any creature in, entering, or passing through the breath weapon's area during this duration takes damage according to the creature's size. This ability has no effect on breath weapons that do not deal energy damage."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 350,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Mistsight",
        name: "Mistsight",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The monster can see through fog, mist, and murky water as if they were perfectly clear, ignoring the miss chance for these obstructions, up to its normal range of vision."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 351,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Mythic Magic",
        name: "Mythic Magic",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Up to three times per day, when the creature casts a spell, it can cast the mythic version instead (as with all mythic spells, the creature must expend mythic power to cast a mythic spell in this way)."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 352,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Mythic Power",
        name: "Mythic Power",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The mythic monster can draw upon a wellspring of power to accomplish amazing deeds and cheat fate. Each day, it can expend a number of uses of mythic power equal to its mythic rank. This amount is its maximum amount of mythic power. If an ability allows it to regain mythic power, it can never gain more than this amount. The monster automatically has the surge ability (see page 228), and can use this mythic power to activate it. It may have other abilities that rely on mythic power."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 353,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Poisonous Blood",
        name: "Poisonous Blood",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Any creature that confirms a critical hit against the monster with a piercing or slashing melee weapon is sprayed with poison. (Melee weapons with reach don't endanger their users in this way.) The type of poison depends on the monster. Unless otherwise stated, this poison uses the poison's normal DC, though some monsters might have a poison DC that's Constitution-based."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 354,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Powerful Blows",
        name: "Powerful Blows",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The specified attack adds 1-1/2 times the creature's Strength bonus on damage rolls instead of its normal Strength bonus or half its Strength bonus."),
        description_variables: &[],
        source_page: Some("p.227"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 355,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Second Save",
        name: "Second Save",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("Whenever the creature fails a saving throw against an effect with a duration greater than 1 round, it can keep trying to shake off the effect. At the start of its turn, if it's still affected, it can attempt the save one more time as a free action. If this save succeeds, the effect affects the creature as if it had succeeded at its initial saving throw. If the effect already allows another saving throw on a later turn to break the effect (such as for hold monster), this ability is in addition to the extra saving throw from the effect."),
        description_variables: &[],
        source_page: Some("p.228"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 357,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Simple Arcane Spellcasting",
        name: "Simple Arcane Spellcasting",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: Some("The creature gains the ability to cast spells from the sorcerer/wizard spell list. Select a number of spells with total spell levels equal to twice the creature's CR. No spell for this ability should have a level higher than 1 + 1/2 the creature's CR. A 0-level spell counts as 1/2 spell level toward this total. The creature can cast each of these spells once per day. Its caster level is equal to its Hit Dice. It uses the higher of its Intelligence or Charisma modifiers to determine its spell DCs."),
        description_variables: &[],
        source_page: Some("p.228"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 358,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Simple Divine Spellcasting",
        name: "Simple Divine Spellcasting",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: None,
        traits: &[],
        description: Some("The creature gains the ability to cast spells from the cleric or druid spell list. Select a number of spells with total spell levels equal to twice the creature's CR. No spell for this ability should have a level higher than 1 + 1/2 the creature's CR. A 0-level spell counts as 1/2 spell level toward this total. The creature can cast each of these spells once per day. Its caster level is equal to its Hit Dice. It uses its Wisdom or Charisma (whichever is higher) to determine its spell DCs."),
        description_variables: &[],
        source_page: Some("p.228"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 359,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Smother",
        name: "Smother",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("If the creature's grappled opponent is holding its breath, the monster can force that opponent to expel or consume some of its breath, or can otherwise reduce the time remaining until the target has to attempt checks to avoid suffocation (Core Rulebook 445). If the monster succeeds at a grapple check against the opponent, the remaining duration for which the opponent can hold its breath decreases by 1d6 rounds. If this reduces the remaining time that the creature can hold its breath to 0 rounds or fewer, the DCs of its suffocation checks increase by 5. For example, if the monster is grappling a creature that has 10 rounds remaining before it has to attempt suffocation checks, a successful grapple check reduces that duration by 1d6 rounds. If the monster has another ability (such as constrict) that harms the opponent when it succeeds at a grapple check, it can automatically use the smother ability when it succeeds at the grapple check to use the other ability."),
        description_variables: &[],
        source_page: Some("p.228"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 360,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Steal",
        name: "Steal",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("The creature can attempt a steal combat maneuver (Pathfinder RPG Advanced Player's Guide 322) against its opponent as a free action without provoking attacks of opportunity if it hits with the specified attack."),
        description_variables: &[],
        source_page: Some("p.228"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 361,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Surge",
        name: "Surge",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The monster can call upon its mythic power to overcome difficult challenges. It can expend one use of mythic power to increase any d20 roll it just made by rolling 1d6 and adding it to the result. Using this ability is an immediate action taken after the original roll is made and the results are revealed. The bonus die gained by using this ability increases to 1d8 at 4th rank, 1d10 at 7th rank, and 1d12 at 10th rank. The monster can use this ability even if it's mindless or of animal-level intelligence."),
        description_variables: &[],
        source_page: Some("p.228"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 362,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "X-Ray Vision",
        name: "X-Ray Vision",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The monster can see through solid matter as if wearing a ring of x-ray vision. This is as exhausting as if the monster were actually using the ring."),
        description_variables: &[],
        source_page: Some("p.228"),
        owners: &[],
        source_file: "ma_abilities_race.lst",
        source_line: 363,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
];
