#!/usr/bin/env python3
"""Derive `monster_sla_entries` for `derived-evaluator-fixtures.json` FROM THE
PINNED PCGEN ORACLE -- never from `data/corpus/`, never from
`src/rules_core/rules_tables/`, and never by importing or running any part of
this repo's own Rust evaluator.

WHY (the same constraint the sibling `derive_*_fixtures.py` scripts state):
a fixture generated by the thing it tests proves nothing.

WHAT MAKES THIS SEAM NON-CIRCULAR
---------------------------------
The other seams in this family derive their expected value from the SAME
corpus field the evaluator parses, and lean on provenance pinning plus an
independent parser for their independence.  This one is stronger, and
deliberately so.

* The **evaluator** (`derived_evaluator_fixture_check::spell_like_ability_
  save_dc`) reads a MONSTER row's `SPELLS:…|<spell>,<N>+<ABIL>` token and
  applies PF1's Universal Monster Rule -- *a spell-like ability's save DC is
  10 + the spell's level + the creature's ability modifier* -- backwards, to
  state the spell's own level as `N - 10`.
* The **expected value** is read from a completely DIFFERENT FILE: the
  granted spell's own PCGen record, whose `CLASSES:<class list>=<level>`
  token states the spell's level directly.  This script never looks at the
  DC token to decide what it expects.

So the check is: *does the level implied by the monster row's printed save DC
match the level the spell's own definition states?*  Two independently
authored corpus facts, in two files, joined only by the printed rule.  A
mutation to the rule constant, to the parser, or to either corpus fact makes
it go red.

THE EXPECTED VALUE IS TRANSCRIBED, NEVER COMPUTED
-------------------------------------------------
``expected.spell_level`` is the number the SPELL's own record states.  It is
never `constant - 10` -- that would make the fixture a restatement of the
evaluator and it could not fail.  Consequently a DC token only produces a
fixture row when the spell's own `CLASSES:` token determines exactly ONE
level.  A spell printed at different levels for different classes (`Suggestion`
= Bard 2, Sorcerer/Wizard 3) leaves the spell file alone unable to say which
level this creature's printing used, and **no rule recovers it** -- re-derived
over this population's own 81 such tokens: the DC matches `max(levels)` 62
times, `min(levels)` 17, an interior value once, and neither once.  A "pick
the highest" rule would therefore be a 77 %-accurate guess dressed as a
derivation.  Those tokens are counted and reported, and produce nothing.

WHAT IT REFUSES
---------------
* A spell name the oracle's spell files do not define at all (`Quickened
  Fireball`, `Suggestion (Nereid)`, `Confusion (single target only)` -- PCGen
  metamagic/scope variants that carry no record of their own).
* A spell whose own record states more than one class level (above).
* **Any unit carrying a DC token that CONTRADICTS its spell's stated single
  level.**  A contradiction is evidence the row's magnitude is wrong, and it
  disqualifies the whole unit, not just that token -- 8 units on this
  population.  These are recorded by `--report` and left OUT of the fixture:
  they are a real finding about the corpus, not something to paper over by
  loosening the check.

A unit is banked when at least one of its DC tokens is verified against an
independently-stated single level AND none of its DC tokens contradicts one.
Undetermined tokens neither bank nor block, and their count ships in the
fixture's own `monster_sla_coverage` block so the gap is visible rather than
implied.

Usage::

    python3 scripts/derive_monster_sla_spell_level_fixtures.py --report
    python3 scripts/derive_monster_sla_spell_level_fixtures.py --check
    python3 scripts/derive_monster_sla_spell_level_fixtures.py

``PCGEN_CORPUS_ROOT`` may point at a local PCGen ``data/`` checkout; it
defaults to ``$HOME/workspace/repos/pcgen/data``.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "rules_core" / "derived-evaluator-fixtures.json"
INVENTORY_PATH = REPO_ROOT / "docs" / "work-inventory.json"

# The `beastiary`-vs-`bestiary` spelling split this repo has carried since
# SD-22: `data/corpus/` and the compiled registry file Bestiary 1 under
# `beastiary`, while every work-inventory `book` field (and therefore every
# `unit_id`) spells it `bestiary`.  The fixture is keyed by `unit_id`, so it
# uses the inventory spelling; the corpus lookup below needs the other one.
CORPUS_DIR_ALIAS = {"bestiary": "beastiary"}

# The DC tail shape this seam commits to: `<constant>+<ABILITY>`.
DC_TOKEN = re.compile(r"^(?P<constant>\d+)\+(?P<ability>[A-Za-z]+)$")

# PF1 Universal Monster Rules, Spell-Like Abilities.  Stated here as its own
# named constant so the mutation test has one place to move, mirroring
# `SPELL_LIKE_ABILITY_SAVE_DC_BASE` on the Rust side -- but derived
# independently, not imported.
SAVE_DC_BASE = 10


def pcgen_data_root() -> Path:
    root = os.environ.get("PCGEN_CORPUS_ROOT")
    if root:
        return Path(root)
    home = os.environ.get("HOME")
    if not home:
        sys.exit("HOME must be set (or PCGEN_CORPUS_ROOT given) to locate the PCGen corpus")
    return Path(home) / "workspace" / "repos" / "pcgen" / "data"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def target_units():
    """Every `monster` unit the board still holds at `derived`+`grounded`.

    `docs/work-inventory.json` is read for IDENTITY ONLY -- which `unit_id` a
    `(book, corpus_key)` pair carries, and which units are in the target
    population.  No magnitude and no engine-computed value is ever taken from
    it.
    """
    inventory = json.loads(INVENTORY_PATH.read_text())
    return [
        u
        for u in inventory["units"]
        if u["kind"] == "monster"
        and u["wiring_class"] == "derived"
        and u["status"] == "grounded"
    ]


def monster_row(data_root: Path, unit) -> tuple[Path, int, str] | None:
    """The unit's own upstream `.lst` path, 1-based line and raw text.

    Resolved through the repo's ingested corpus record, which is the only
    thing that states the upstream PATH for a given unit (the inventory
    carries a bare file NAME).  Only `source.path`/`source.line` are read --
    identity, not magnitude; the row text itself comes from the oracle bytes.

    Returns `None` for a record whose `data.corpus_key` is absent.  That is
    not a cosmetic gap: **46 of Bestiary 1's 326 ingested monster records
    carry no `corpus_key`**, and those are exactly the records the compiled
    `monster_chassis` registry does not define -- they reach `grounded` only
    through the older SD-22 `beastiary1` `MonsterId` table, whose stat-block
    type carries no `SPELLS:` data at all.  A fixture naming one of them
    could never clear the bar, because the bar resolves through the chassis
    registry by `KEY:`.  Derro, Doppelganger and Dryad are the three of them
    that carry a save-DC token, and this guard is what keeps them out of the
    fixture instead of shipping three rows that fail the gate.
    """
    book_dir = CORPUS_DIR_ALIAS.get(unit["book"], unit["book"])
    slug = unit["id"].rsplit(":", 1)[1]
    record = REPO_ROOT / "data" / "corpus" / book_dir / "monster" / f"{slug}.json"
    if not record.is_file():
        return None
    document = json.loads(record.read_text())
    if document["data"].get("corpus_key") != unit["corpus_key"]:
        return None
    source = document["source"]
    path = data_root / source["path"]
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8", errors="strict").split("\n")
    return path, source["line"], text[source["line"] - 1]


def dc_tokens(row: str):
    """`(spell_name, dc_token)` for every `SPELLS:` grant on the row that
    states a save DC.  An independent re-implementation of
    `transcribe_monster_tables.parse_spell_like_abilities`'s split, kept
    separate on purpose -- this script must not share code with the thing
    that produced the table the evaluator reads."""
    out = []
    for field in row.split("\t"):
        field = field.strip()
        if not field.startswith("SPELLS:"):
            continue
        for segment in field[len("SPELLS:"):].split("|")[1:]:
            segment = segment.strip()
            if not segment or segment.startswith("PRE") or "=" in segment.split(",")[0]:
                continue
            if "," not in segment:
                continue
            name, _, tail = segment.partition(",")
            out.append((name.strip(), tail.strip()))
    return out


def spell_level_index(data_root: Path):
    """`spell identity -> (path, 1-based line, CLASSES token, {levels})`,
    built from every PCGen spell `.lst` under the pinned oracle.

    The level comes from the spell record's OWN `CLASSES:` token, which is a
    different file from any monster row.  A spell defined more than once (a
    later book restating it) keeps the FIRST definition encountered in sorted
    path order, and the ambiguity is reported rather than silently resolved.
    """
    index: dict[str, tuple] = {}
    duplicates: set[str] = set()
    for path in sorted(data_root.glob("pathfinder/**/*spells*.lst")):
        try:
            text = path.read_text(encoding="utf-8", errors="strict")
        except (UnicodeDecodeError, OSError):
            continue
        for number, line in enumerate(text.split("\n"), start=1):
            if not line.strip() or line.startswith("#") or line.startswith("SOURCE"):
                continue
            fields = line.split("\t")
            name = fields[0].strip()
            if not name or name.startswith("."):
                continue
            key = None
            classes = None
            for field in fields[1:]:
                field = field.strip()
                if field.startswith("KEY:"):
                    key = field[len("KEY:"):]
                elif field.startswith("CLASSES:"):
                    classes = field
            identity = key or name
            if classes is None:
                continue
            levels = {
                int(m.group(1))
                for chunk in classes[len("CLASSES:"):].split("|")
                if (m := re.search(r"=(\d+)\s*$", chunk))
            }
            if not levels:
                continue
            if identity in index:
                duplicates.add(identity)
                continue
            index[identity] = (path, number, classes, levels)
    return index, duplicates


def derive(data_root: Path):
    index, duplicates = spell_level_index(data_root)
    spell_sha: dict[Path, str] = {}

    per_unit_rows: dict[str, list] = collections.defaultdict(list)
    refused: list[str] = []
    stats = collections.Counter()

    for unit in target_units():
        located = monster_row(data_root, unit)
        if located is None:
            refused.append(
                f"{unit['id']}: no chassis-keyed corpus record locates its upstream row"
            )
            stats["unit_no_corpus_record"] += 1
            continue
        path, line_no, row = located
        tokens = dc_tokens(row)
        if not tokens:
            stats["unit_no_dc_token"] += 1
            continue
        sha = spell_sha.setdefault(path, sha256_file(path))
        rows = []
        contradicted = False
        for spell, tail in tokens:
            stats["dc_token"] += 1
            m = DC_TOKEN.fullmatch(tail)
            if not m:
                stats["undetermined_dc_shape"] += 1
                continue
            implied = int(m.group("constant")) - SAVE_DC_BASE
            entry = index.get(spell)
            if entry is None:
                stats["undetermined_spell_absent"] += 1
                continue
            spell_path, spell_line, classes, levels = entry
            if len(levels) != 1:
                stats["undetermined_multi_level"] += 1
                continue
            # THE EXPECTED VALUE, transcribed from the SPELL's own record.
            stated = next(iter(levels))
            if stated != implied:
                refused.append(
                    f"{unit['id']}: {spell!r} DC {tail} implies spell level {implied}, but "
                    f"{spell_path.name}:{spell_line} states level {stated}"
                )
                stats["contradiction"] += 1
                contradicted = True
                continue
            stats["verified"] += 1
            rows.append(
                {
                    "unit_id": unit["id"],
                    "book": unit["book"],
                    "record_key": unit["corpus_key"],
                    "upstream_lst": str(Path(path).relative_to(data_root)),
                    "upstream_lst_sha256": sha,
                    "upstream_line": line_no,
                    "spell": spell,
                    "corpus_field": tail,
                    "spell_level_lst": str(Path(spell_path).relative_to(data_root)),
                    "spell_level_lst_sha256": spell_sha.setdefault(
                        spell_path, sha256_file(spell_path)
                    ),
                    "spell_level_line": spell_line,
                    "spell_level_corpus_field": classes,
                    "expected": {
                        "spell_level": stated,
                        "ability": m.group("ability"),
                    },
                }
            )
        if contradicted:
            stats["unit_refused"] += 1
            continue
        if rows:
            per_unit_rows[unit["id"]] = rows
            stats["unit_banked"] += 1
        else:
            stats["unit_undetermined"] += 1

    entries = [row for unit_id in sorted(per_unit_rows) for row in per_unit_rows[unit_id]]
    return entries, refused, stats, duplicates


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="derive and print, write nothing")
    ap.add_argument("--report", action="store_true", help="census only, write nothing")
    args = ap.parse_args()

    data_root = pcgen_data_root()
    entries, refused, stats, duplicates = derive(data_root)

    coverage = {
        "dc_tokens_seen": stats["dc_token"],
        "dc_tokens_verified": stats["verified"],
        "dc_tokens_contradicting": stats["contradiction"],
        "dc_tokens_undetermined_multi_level": stats["undetermined_multi_level"],
        "dc_tokens_undetermined_spell_absent": stats["undetermined_spell_absent"],
        "dc_tokens_undetermined_shape": stats["undetermined_dc_shape"],
        "units_banked": stats["unit_banked"],
        "units_refused_for_a_contradiction": stats["unit_refused"],
        "units_with_no_determinable_token": stats["unit_undetermined"],
        "target_units_with_no_dc_token_at_all": stats["unit_no_dc_token"],
        "target_units_with_no_ingested_corpus_record": stats["unit_no_corpus_record"],
    }

    if args.report or args.check:
        for line in refused:
            print(f"REFUSED: {line}", file=sys.stderr)
        print(f"\n{json.dumps(coverage, indent=2)}", file=sys.stderr)
        print(
            f"{len(duplicates)} spell names are defined more than once in the oracle",
            file=sys.stderr,
        )
        if args.check:
            print(json.dumps(entries, indent=2))
        return

    doc = json.loads(FIXTURE_PATH.read_text())
    doc["monster_sla_token_family"] = (
        "SPELLS:<label>|TIMES=<n>|CASTERLEVEL=<v>|<spell>,<constant>+<ABILITY> "
        "(the spell-like-ability save DC)"
    )
    doc["monster_sla_derivation"] = (
        "PF1 Universal Monster Rules, Spell-Like Abilities: a spell-like ability's save DC is "
        "10 + the spell's level + the creature's ability modifier. The modifier is NEVER "
        "resolved -- a monster's ability SCORES are not a corpus-stated fact in this repo "
        "(SD31-E6-F1-002) and inventing one would be fabrication. expected.spell_level and "
        "expected.ability restate the FORMULA's own parameters, matching the DURATION/RANGE "
        "seams' posture."
    )
    doc["monster_sla_independence"] = (
        "expected.spell_level is read from a DIFFERENT FILE than the one the evaluator parses: "
        "the granted spell's own PCGen record, whose CLASSES:<classes>=<level> token states the "
        "level directly (spell_level_lst / spell_level_line / spell_level_corpus_field pin it, "
        "with its own sha256). scripts/derive_monster_sla_spell_level_fixtures.py re-reads the "
        "pinned upstream .lst bytes for both files, splits the SPELLS: token with its own "
        "from-scratch parser, opens no file under src/rules_core/rules_tables/, and imports no "
        "engine module. expected.spell_level is TRANSCRIBED from that record, never computed "
        "from the DC token under test, so a fixture row only exists where the spell's own "
        "CLASSES: token determines exactly ONE level. A unit is banked when at least one of "
        "its DC tokens is verified that way and NONE of them contradicts a stated single "
        "level; monster_sla_coverage states how many tokens fell in each bucket."
    )
    doc["monster_sla_coverage"] = coverage
    doc["monster_sla_entries"] = entries
    FIXTURE_PATH.write_text(json.dumps(doc, indent=2) + "\n")
    for line in refused:
        print(f"REFUSED: {line}", file=sys.stderr)
    print(
        f"wrote {len(entries)} monster_sla_entries over {stats['unit_banked']} units "
        f"({stats['unit_refused']} units refused for a contradiction) to {FIXTURE_PATH}"
    )


if __name__ == "__main__":
    main()
