#!/usr/bin/env python3
"""Derive `companion_entries` for `derived-evaluator-fixtures.json` FROM THE
PINNED PCGEN ORACLE -- never from `data/corpus/`, never from this repo's Rust
tables, and never by importing or running any part of its evaluator.

WHY (the same constraint `derive_derived_evaluator_fixtures.py`,
`derive_spell_range_fixtures.py` and `derive_class_feature_level_scaling_fixtures.py`
each state for their own family): a fixture generated by the thing it tests
proves nothing. This script reads the UPSTREAM `.lst` bytes directly, extracts
the token with its own regex, classifies its shape with its own tiny
from-scratch classifier (`classify_shape`, below -- a different implementation
in a different language from
`src/rules_core/derived_evaluator_fixture_check.rs`'s
`parse_companion_strength_damage`), and computes every expected damage bonus
from PF1's OWN halve-and-round-down convention with `math.floor`, so the two
sides cannot silently agree on a shared bug.

`docs/work-inventory.json` is read for IDENTITY AND SELECTION ONLY -- which
`unit_id` a `(book, corpus_key)` pair carries, and which units are the
`wiring_class=derived, status=grounded` population this seam exists to move. No
magnitude and no engine-computed value is ever taken from it.

THE RULE, AND THE FACT THAT UPSTREAM DOES NOT FOLLOW IT UNIFORMLY
-----------------------------------------------------------------
PF1 CRB p.182, *Natural Attacks*: "If a creature has only one natural attack,
it adds 1-1/2 times its Strength bonus on damage rolls." PCGen encodes the
EXTRA HALF as `BONUS:WEAPONPROF=<attack>|DAMAGE|max(0,(STR/2))` -- the base
attack already applies the full modifier -- and the `max(0,...)` is why a
Strength PENALTY is never multiplied (the rule is stated about a Strength
*bonus*).

**The token's presence is NOT a corpus invariant and this script never infers
it.** Crossing natural-attack count against half-Strength-token presence over
all 927 ingested companion records (2026-08-19) gives (1 attack, 0 tokens) =
129 and (2 attacks, 1 token) = 3, alongside (1,1) = 185. Deriving the
expectation from the attack count would manufacture 129 false failures against
data upstream simply does not state that way. What is derived here is what
PF1's rounding convention makes of the formula the row ACTUALLY carries;
`--report` prints the count-rule agreement census so the non-invariance stays
visible rather than being quietly designed around.

WHAT IS DELIBERATELY NOT COVERED
--------------------------------
`STR/2` and `-(STR/2)` (3 rows corpus-wide): an UNCLAMPED halving's value at a
negative odd Strength modifier depends on whether PCGen's formula engine floors
or truncates, and this repo has no proof of which. Skipped and reported, never
guessed.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import math
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "rules_core" / "derived-evaluator-fixtures.json"
INVENTORY_PATH = REPO_ROOT / "docs" / "work-inventory.json"

# The Strength modifiers each entry pins. Chosen for MUTATION SENSITIVITY, not
# for coverage of plausible companions: a negative even and a negative odd
# (an evaluator that dropped the `max(0,...)` clamp goes red), an odd positive
# (an evaluator that rounded UP or truncated toward +inf goes red), an even
# positive (an evaluator that applied the FULL modifier instead of half goes
# red), and zero (an evaluator that added a constant goes red).
STRENGTH_MODIFIER_LADDER = (-4, -3, -1, 0, 1, 2, 3, 6, 7)

TOKEN_RE = re.compile(r"^BONUS:WEAPONPROF=(?P<attack>[^|]+)\|DAMAGE\|(?P<formula>.+)$")


def pcgen_data_root() -> Path:
    root = os.environ.get("PCGEN_CORPUS_ROOT")
    if root:
        return Path(root)
    home = os.environ.get("HOME")
    if not home:
        sys.exit("HOME must be set (or PCGEN_CORPUS_ROOT given) to locate the PCGen corpus")
    return Path(home) / "workspace" / "repos" / "pcgen" / "data"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def classify_shape(formula: str) -> str | None:
    """Independent re-implementation of the Rust seam's
    `parse_companion_strength_damage`, over the corpus-observed shapes.

    Returns the shape name, or `None` for a shape this seam refuses (see the
    module doc's "WHAT IS DELIBERATELY NOT COVERED").
    """
    f = "".join(formula.split())
    if f in ("max(0,(STR/2))", "max(0,STR/2)"):
        return "half_strength_never_negative"
    if f == "STR":
        return "full_strength"
    if f == "-STR":
        return "negated_full_strength"
    if re.fullmatch(r"[+-]?\d+", f):
        return "flat"
    return None


def expected_damage_bonus(shape: str, formula: str, strength_modifier: int) -> int:
    """PF1 CRB p.9: "whenever you are asked to halve a number, round down."

    `math.floor` explicitly, never Python's `//` shorthand and never Rust's
    truncating `/`, so the rounding this program's rule doctrine states is the
    one written here.
    """
    if shape == "half_strength_never_negative":
        return max(0, math.floor(strength_modifier / 2))
    if shape == "full_strength":
        return strength_modifier
    if shape == "negated_full_strength":
        return -strength_modifier
    if shape == "flat":
        return int("".join(formula.split()))
    raise AssertionError(f"unclassified shape {shape!r}")


def read_rows(path: Path) -> list[list[str]]:
    """Every non-comment, non-header row of a PCGen `.lst`, as tab fields,
    1-indexed by position in the returned list's enumerate(start=1)."""
    text = path.read_bytes().decode("utf-8")
    return [line.rstrip("\r\n").split("\t") for line in text.split("\n")]


def row_identity(fields: list[str]) -> str | None:
    """A row's record identity: its `KEY:` token where it carries one, else its
    first tab field -- which is exactly what PCGen itself does, and what this
    repo's own ingest records as `corpus_key`."""
    for f in fields:
        if f.startswith("KEY:"):
            return f[len("KEY:") :].strip() or None
    first = fields[0].strip() if fields else ""
    if not first or first.startswith("#") or first.startswith("SOURCE"):
        return None
    return first


def natural_attack_names(fields: list[str]) -> list[str]:
    """The row's named natural attacks -- an independent re-read of the same two
    token shapes, recorded as a corpus FACT per entry and used by `--report`'s
    census. It is never the source of an expected value."""
    names: list[str] = []
    for f in fields:
        if f.startswith("NATURALATTACKS:"):
            for entry in f[len("NATURALATTACKS:") :].split("|"):
                parts = [p.strip() for p in entry.split(",")]
                if parts and parts[0] and parts[0] not in names:
                    names.append(parts[0])
    for f in fields:
        if f.startswith("ABILITY:Internal|AUTOMATIC|"):
            for name in f.split("|")[2:]:
                name = name.strip()
                if not name or name.startswith("PRE") or "=" in name or " ~ " in name:
                    continue
                if name not in names:
                    names.append(name)
    return names


def damage_tokens(fields: list[str]) -> list[tuple[str, str]]:
    out = []
    for f in fields:
        m = TOKEN_RE.match(f.strip())
        if m:
            out.append((m.group("attack").strip(), m.group("formula").strip()))
    return out


def selected_units() -> list[dict]:
    """The `kind=companion, wiring_class=derived, status=grounded` population,
    from `docs/work-inventory.json`. Identity and selection only."""
    doc = json.loads(INVENTORY_PATH.read_text())
    return [
        u
        for u in doc["units"]
        if u["kind"] == "companion"
        and u["wiring_class"] == "derived"
        and u["status"] == "grounded"
        and u["book"] != "beginner_box"
    ]


def resolve_upstream(data_root: Path, basename: str) -> Path:
    hits = sorted(data_root.glob(f"pathfinder/**/{basename}"))
    if len(hits) != 1:
        raise SystemExit(
            f"{basename}: expected exactly one file under {data_root}/pathfinder, found {len(hits)}"
        )
    return hits[0]


def derive(data_root: Path):
    units = selected_units()
    by_file: dict[str, list[dict]] = collections.defaultdict(list)
    for u in units:
        by_file[u["source_file"]].append(u)

    entries = []
    skipped: list[str] = []
    census = collections.Counter()

    for basename, group in sorted(by_file.items()):
        # CREATURE rows only. `companion_chassis::NaturalAttackDamageBonus` is a
        # field of `CompanionRecord`, and the bar check resolves an entry through
        # `CompanionBook::companion_resolve`, which searches creatures. Two rows
        # of the selected population live in an `*_abilities_*.lst`
        # (`ultimate_wilderness:companion:giant_caterpillar_bristles`'s file and
        # `bestiary:companion:tyrannosaurus_powerful_bite`, the latter already
        # refused on its `max(0,STR)` shape) -- a real, named follow-on for the
        # ability half of the kind, not silently swept in here where they would
        # read as unresolvable failures.
        if "_races_" not in basename:
            skipped.append(
                f"{basename}: an *_abilities_* file -- this seam covers companion CREATURE rows "
                f"({len(group)} unit(s) in this file deferred to the ability-row follow-on)"
            )
            continue
        path = resolve_upstream(data_root, basename)
        rel = str(path.relative_to(data_root))
        sha = sha256_file(path)
        rows = read_rows(path)
        index: dict[str, tuple[int, list[str]]] = {}
        for i, fields in enumerate(rows, start=1):
            key = row_identity(fields)
            if key and key not in index:
                index[key] = (i, fields)

        for u in sorted(group, key=lambda x: x["id"]):
            ckey = u["corpus_key"]
            hit = index.get(ckey)
            if hit is None:
                skipped.append(f"{u['id']}: no row identified {ckey!r} in {basename}")
                continue
            line_no, fields = hit
            tokens = damage_tokens(fields)
            attacks = natural_attack_names(fields)
            half = [t for t in tokens if classify_shape(t[1]) == "half_strength_never_negative"]
            census[(len(attacks), len(half))] += 1
            if len(tokens) != 1:
                skipped.append(
                    f"{u['id']}: row carries {len(tokens)} BONUS:WEAPONPROF=…|DAMAGE| tokens, "
                    "this seam pins rows that carry exactly one"
                )
                continue
            attack, formula = tokens[0]
            shape = classify_shape(formula)
            if shape is None:
                skipped.append(
                    f"{u['id']}: formula {formula!r} is a shape this seam refuses rather than "
                    "guesses at (see the module doc)"
                )
                continue
            entries.append(
                {
                    "unit_id": u["id"],
                    "book": u["book"],
                    "record_key": ckey,
                    "attack": attack,
                    "upstream_lst": rel,
                    "upstream_lst_sha256": sha,
                    "upstream_line": line_no,
                    "corpus_field": f"BONUS:WEAPONPROF={attack}|DAMAGE|{formula}",
                    "natural_attack_names": attacks,
                    "expected": {
                        "shape": shape,
                        "damage_bonus_at_strength_modifier": [
                            {
                                "strength_modifier": m,
                                "damage_bonus": expected_damage_bonus(shape, formula, m),
                            }
                            for m in STRENGTH_MODIFIER_LADDER
                        ],
                    },
                }
            )

    entries.sort(key=lambda e: e["unit_id"])
    return entries, skipped, census


TOKEN_FAMILY = (
    "BONUS:WEAPONPROF=<attack>|DAMAGE (PF1 CRB p.182 single-natural-attack extra "
    "half-Strength damage: max(0, floor(STR_modifier / 2)))"
)
DERIVATION = (
    "PCGen `BONUS:WEAPONPROF=<attack>|DAMAGE|<formula>` on a companion CREATURE row. "
    "expected.shape names the formula's rules meaning and "
    "expected.damage_bonus_at_strength_modifier pins the evaluated damage bonus at nine "
    "Strength modifiers, each computed from PF1 CRB p.9's halve-and-round-down convention "
    "(math.floor) plus the token's own max(0,...) clamp -- NOT read back from this repo's "
    "evaluator, and NOT inferred from the creature's natural-attack count, which upstream "
    "PCGen does not state uniformly (129 single-attack rows carry no such token; 3 "
    "two-attack rows carry one). natural_attack_names is recorded as a corpus fact only."
)
INDEPENDENCE = (
    "scripts/derive_companion_strength_damage_fixtures.py re-reads the pinned upstream .lst "
    "bytes directly, extracts the token with its own regex, classifies the shape with its own "
    "from-scratch classifier (classify_shape), and computes every expected value with "
    "math.floor -- structurally independent of "
    "src/rules_core/derived_evaluator_fixture_check.rs's parse_companion_strength_damage / "
    "evaluate_companion_strength_damage. It opens no file under data/corpus/, reads no Rust "
    "table, and imports no engine module. docs/work-inventory.json is read for identity and "
    "selection only."
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="derive and print, write nothing")
    ap.add_argument("--report", action="store_true",
                    help="print the natural-attack-count vs half-Strength-token census and exit")
    args = ap.parse_args()

    data_root = pcgen_data_root()
    entries, skipped, census = derive(data_root)

    if args.report:
        print("(natural attacks, half-STR tokens) -> selected derived+grounded companion units")
        for k in sorted(census):
            print(f"    {k} {census[k]}")
        print(f"\n{len(entries)} derivable, {len(skipped)} skipped")
        for s in skipped:
            print(f"    SKIPPED: {s}")
        return

    for s in skipped:
        print(f"SKIPPED: {s}", file=sys.stderr)

    if args.check:
        print(json.dumps(entries, indent=2))
        print(f"\n{len(entries)} derived, {len(skipped)} skipped", file=sys.stderr)
        return

    doc = json.loads(FIXTURE_PATH.read_text())
    doc["companion_token_family"] = TOKEN_FAMILY
    doc["companion_derivation"] = DERIVATION
    doc["companion_independence"] = INDEPENDENCE
    doc["companion_entries"] = entries
    FIXTURE_PATH.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {len(entries)} companion_entries ({len(skipped)} skipped) to {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
