#!/usr/bin/env python3
"""Derive `companion_save_dc_entries` for `derived-evaluator-fixtures.json`
FROM THE PINNED PCGEN ORACLE -- never from `data/corpus/`, never from this
repo's Rust tables, and never by importing or running any part of its
evaluator.

WHY (the same constraint every sibling `derive_companion_*_fixtures.py`
states for its own family): a fixture generated by the thing it tests proves
nothing. This script reads the UPSTREAM `.lst` bytes directly, splits each
`DESC:` field with its own tab/pipe logic, classifies the trailing formula
argument with its own tiny from-scratch classifier (`classify_shape`, below
-- a different implementation in a different language from
`src/rules_core/derived_evaluator_fixture_check.rs`'s
`parse_companion_save_dc_formula`), and computes every expected save DC with
plain Python integer arithmetic, so the two sides cannot silently agree on a
shared bug.

`docs/work-inventory.json` is read for IDENTITY AND SELECTION ONLY -- which
`unit_id` a `(book, corpus_key)` pair carries, and which units are the
`kind=companion, wiring_class=derived` population this seam exists to move.
No magnitude and no engine-computed value is ever taken from it.

THE SHAPE, AND WHY IT NEEDS ITS OWN SEAM
-----------------------------------------
Unlike `kind=monster_ability`'s formula-shape sub-seam (whose ability row
states no independent constant -- the base comes from the OWNING monster's
Universal Monster Rule Hit Dice, a two-record cross-check), a `kind=companion`
ability row states its save DC ENTIRELY on its own `DESC:` token, with no
separate `BONUS:` field at all: `DESC:Bite-injury; save Fort DC %1; ...|10+HD/2+CON`
(`b4_abilities_companion.lst:19`, `Companion (Dinosaur (Dimorphodon)) ~
Poison`). The formula argument states its OWN base constant (10, 11 or 12
corpus-wide -- NOT always 10, so this seam does not assume the Universal
Monster Rule's fixed base), an OPTIONAL `<HD or TL>/2` term, and one of the
six PF1 ability-modifier abbreviations. `render_pcgen_desc`
(`decisions.md §24`, no formula interpreter) drops the `%1` placeholder
entirely when this text reaches a player, which is exactly why this is a real
gap and not merely an unrendered convenience -- the DC number is silently
missing from the description a player reads today.

Re-derived corpus-wide 2026-08-19 (regex over every `description_variables`/
`description_variants[].variables` array `transcribe_companion_tables.py`
already compiled onto `CompanionAbilityRecord`, cross-checked by hand against
the raw upstream `.lst` bytes for every hit): the shape
`^\\d+(\\+(HD|TL)/2)?\\+(STR|DEX|CON|INT|WIS|CHA)$` occurs 30 times across two
books (Ultimate Wilderness, Bestiary 4), naming 25 distinct ability records
(some state the same formula twice, once per `PREVARLT`/`PREVARGTEQ`
companion-advancement-tier variant -- see Assassin Bug (Giant) ~ Poison).

WHAT IS DELIBERATELY NOT COVERED
---------------------------------
- A bare variable NAME with no formula on the row at all (the
  `monster_ability` named-variable shape -- `ClingDC`) needs a chassis field
  this seam does not add and does not occur in `kind=companion` upstream
  today.
- `1+HD/2` (Ultimate Wilderness `uw_abilities_companion.lst:4994`, Whiptail
  Centipede's OTHER ability, not `~ Poison`): no ability-modifier term at all
  -- a duration or a Hit-Dice-scaled quantity, not a save DC, and this seam's
  regex correctly does not match it.
- A record whose DESC-embedded arguments disagree with each other (more than
  one DISTINCT parseable formula on one record): none exists in the pinned
  oracle today; the derivation asserts this rather than assuming it.
- `dire_rat_disease` / `puffball_poison` (2 units): this exact rule, but
  stated as a `BONUS:VAR|<Name>|<formula>` token instead of a `DESC:`
  argument -- a real follow-on for a later cycle, structurally different
  extraction and not attempted here.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "rules_core" / "derived-evaluator-fixtures.json"
INVENTORY_PATH = REPO_ROOT / "docs" / "work-inventory.json"

ABILITY_ABBREVIATIONS = {"STR", "DEX", "CON", "INT", "WIS", "CHA"}

# (hit_dice, ability_modifier) pairs each entry pins. Chosen for MUTATION
# SENSITIVITY: an evaluator that dropped the "+1/2 HD" term entirely fails on
# every pair below whose hd is not 0 or 1 (floor(hd/2) != 0); one that used
# ceiling instead of floor fails on every ODD hd (1, 5); one that ignored the
# ability modifier fails on every pair with a non-zero modifier; one that
# applied the half-HD term even when the formula has none (a shape-confusion
# bug between the two forms) is caught because BOTH shapes are exercised at
# an hd whose floor(hd/2) is non-zero (5) against expected values that only
# differ if the term is wrongly applied.
HD_AND_MODIFIER_PAIRS = (
    (0, 0),
    (1, 3),
    (2, -2),
    (5, 4),
    (10, -1),
    (20, 2),
)

SHAPE_RE = re.compile(
    r"^(?P<base>\d+)\+(?:(?P<divisor>HD|TL)/2\+)?(?P<ability>STR|DEX|CON|INT|WIS|CHA)$"
)


def pcgen_data_root() -> Path:
    root = os.environ.get("PCGEN_CORPUS_ROOT")
    if root:
        return Path(root)
    home = os.environ.get("HOME")
    if not home:
        sys.exit("HOME must be set (or PCGEN_CORPUS_ROOT given) to locate the PCGen corpus")
    return Path(home) / "workspace" / "repos" / "pcgen" / "data"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def classify_shape(formula: str) -> tuple[int, bool, str] | None:
    """Independent re-implementation of the Rust seam's
    `parse_companion_save_dc_formula`. Returns `(base, includes_half_hd,
    ability)` or `None` for a shape this seam refuses."""
    f = "".join(formula.split())
    m = SHAPE_RE.match(f)
    if not m:
        return None
    base = int(m.group("base"))
    includes_half_hd = m.group("divisor") is not None
    ability = m.group("ability")
    if ability not in ABILITY_ABBREVIATIONS:
        return None
    return (base, includes_half_hd, ability)


def expected_save_dc(base: int, includes_half_hd: bool, hit_dice: int, ability_modifier: int) -> int:
    """Plain integer arithmetic -- PF1's "1/2 HD" rounds DOWN, and Hit Dice is
    never negative in this corpus, so `//` (Python floor division) is exact,
    unlike `evaluate_companion_strength_damage`'s sibling problem with
    negative Strength modifiers."""
    half_hd = (hit_dice // 2) if includes_half_hd else 0
    return base + half_hd + ability_modifier


def read_rows(path: Path) -> list[list[str]]:
    text = path.read_bytes().decode("utf-8")
    return [line.rstrip("\r\n").split("\t") for line in text.split("\n")]


def row_identity(fields: list[str]) -> str | None:
    for f in fields:
        if f.startswith("KEY:"):
            return f[len("KEY:") :].strip() or None
    first = fields[0].strip() if fields else ""
    if not first or first.startswith("#") or first.startswith("SOURCE"):
        return None
    return first


def desc_formula_candidates(fields: list[str]) -> list[str]:
    """Every `DESC:` field's trailing pipe-separated argument that is NOT a
    `PRE…`/`!PRE…` gate -- the same prose/args/conditions split
    `transcribe_companion_tables.parse_desc` makes, re-derived here from
    scratch rather than imported (independence -- see the module doc)."""
    out = []
    for field in fields:
        if not field.startswith("DESC:"):
            continue
        parts = field[len("DESC:") :].split("|")
        for arg in parts[1:]:
            arg = arg.strip()
            if not arg or arg.startswith("PRE") or arg.startswith("!PRE"):
                continue
            out.append(arg)
    return out


# BOTH statuses, and the second one is what makes this generator IDEMPOTENT
# -- the same near-miss `derive_companion_strength_damage_fixtures.py` and
# `derive_companion_skill_bonus_fixtures.py` both document on this constant:
# `apply_done_rung_stamps()` rewrites a covered unit's status from `grounded`
# to `fixture-verified`, so selecting `grounded` alone would pick the target
# population on the FIRST run and the empty set on every run after -- and
# this script REPLACES `companion_save_dc_entries` rather than merging, so a
# second run would silently erase every committed row.
TARGET_STATUSES = {"grounded", "fixture-verified"}


def selected_units() -> list[dict]:
    """The `kind=companion, wiring_class=derived` population at a status the
    `derived` done rung can act on, from `docs/work-inventory.json`. Identity
    and selection only."""
    doc = json.loads(INVENTORY_PATH.read_text())
    return [
        u
        for u in doc["units"]
        if u["kind"] == "companion"
        and u["wiring_class"] == "derived"
        and u["status"] in TARGET_STATUSES
        and u["book"] != "beginner_box"
    ]


def resolve_upstream(data_root: Path, basename: str) -> Path:
    hits = sorted(data_root.glob(f"pathfinder/**/{basename}"))
    if len(hits) != 1:
        raise SystemExit(
            f"{basename}: expected exactly one file under {data_root}/pathfinder, found {len(hits)}"
        )
    return hits[0]


def derive(data_root: Path):
    units = selected_units()
    by_file: dict[str, list[dict]] = collections.defaultdict(list)
    for u in units:
        by_file[u["source_file"]].append(u)

    entries = []
    skipped: list[str] = []

    for basename, group in sorted(by_file.items()):
        # ABILITY rows only -- this shape lives on `CompanionAbilityRecord`
        # (`_abilities_` files), the sibling of the Strength-damage/Skill-diff
        # seams' own CREATURE-row restriction but the opposite file half.
        if "_abilities_" not in basename:
            skipped.append(
                f"{basename}: a *_races_* file -- this seam covers companion ABILITY rows "
                f"({len(group)} unit(s) in this file are out of scope for it)"
            )
            continue
        path = resolve_upstream(data_root, basename)
        rel = str(path.relative_to(data_root))
        sha = sha256_file(path)
        rows = read_rows(path)
        index: dict[str, tuple[int, list[str]]] = {}
        for i, fields in enumerate(rows, start=1):
            key = row_identity(fields)
            if key and key not in index:
                index[key] = (i, fields)

        for u in sorted(group, key=lambda x: x["id"]):
            ckey = u["corpus_key"]
            hit = index.get(ckey)
            if hit is None:
                skipped.append(f"{u['id']}: no row identified {ckey!r} in {basename}")
                continue
            line_no, fields = hit
            candidates = desc_formula_candidates(fields)
            parsed = {c: classify_shape(c) for c in candidates}
            matched = {c: p for c, p in parsed.items() if p is not None}
            distinct_shapes = set(matched.values())
            if not matched:
                skipped.append(
                    f"{u['id']}: row carries no DESC: argument matching the save-DC shape "
                    f"(candidates seen: {candidates!r})"
                )
                continue
            if len(distinct_shapes) != 1:
                skipped.append(
                    f"{u['id']}: row carries {len(distinct_shapes)} DISTINCT save-DC shapes "
                    f"{sorted(distinct_shapes)!r} -- ambiguous, refused rather than guessed"
                )
                continue
            formula_text = sorted(matched)[0]
            base, includes_half_hd, ability = matched[formula_text]
            entries.append(
                {
                    "unit_id": u["id"],
                    "book": u["book"],
                    "record_key": ckey,
                    "upstream_lst": rel,
                    "upstream_lst_sha256": sha,
                    "upstream_line": line_no,
                    "corpus_field": f"DESC:...|{formula_text}",
                    "expected": {
                        "base": base,
                        "includes_half_hd": includes_half_hd,
                        "ability": ability,
                        "save_dc_at": [
                            {
                                "hit_dice": hd,
                                "ability_modifier": am,
                                "save_dc": expected_save_dc(base, includes_half_hd, hd, am),
                            }
                            for hd, am in HD_AND_MODIFIER_PAIRS
                        ],
                    },
                }
            )

    entries.sort(key=lambda e: e["unit_id"])
    return entries, skipped


TOKEN_FAMILY = (
    "DESC:<prose>%1<prose>|<base>[+<HD|TL>/2]+<ability> -- a companion ability's save DC, "
    "stated entirely in the DESC: token's own trailing formula argument (no separate BONUS: "
    "field), e.g. `10+HD/2+CON` or `11+CHA`."
)
DERIVATION = (
    "Every DESC: field on the ability's own row (there may be several, one per "
    "PREVARLT/PREVARGTEQ companion-advancement-tier variant), split on `|`, dropping the "
    "leading prose and any PRE…/!PRE… gate argument. The remaining argument(s) must all parse "
    "to the SAME (base, includes_half_hd, ability) triple via this seam's own from-scratch "
    "classifier (independent of both the Python-side skill/strength seams and the Rust "
    "evaluator). expected.save_dc_at pins the evaluated DC at six (hit_dice, ability_modifier) "
    "pairs chosen for mutation sensitivity -- plain integer arithmetic computed here in "
    "Python, NOT read back from this repo's evaluator."
)
INDEPENDENCE = (
    "scripts/derive_companion_save_dc_fixtures.py re-reads the pinned upstream .lst bytes "
    "directly, splits each DESC: field's tab/pipe structure with its own logic, classifies the "
    "shape with its own from-scratch regex (classify_shape) and computes every expected save DC "
    "with plain Python arithmetic -- structurally independent of "
    "src/rules_core/derived_evaluator_fixture_check.rs's parse_companion_save_dc_formula / "
    "evaluate_companion_save_dc_formula. It opens no file under data/corpus/, reads no Rust "
    "table, and imports no engine module. docs/work-inventory.json is read for identity and "
    "selection only."
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="derive and print, write nothing")
    ap.add_argument("--report", action="store_true", help="print the skip census to stderr and exit")
    args = ap.parse_args()

    data_root = pcgen_data_root()
    entries, skipped = derive(data_root)

    if args.report:
        for s in skipped:
            print(f"SKIPPED: {s}", file=sys.stderr)
        print(f"\n{len(entries)} derived, {len(skipped)} skipped", file=sys.stderr)
        return

    for s in skipped:
        print(f"SKIPPED: {s}", file=sys.stderr)

    if args.check:
        print(json.dumps(entries, indent=2))
        print(f"\n{len(entries)} derived, {len(skipped)} skipped", file=sys.stderr)
        return

    doc = json.loads(FIXTURE_PATH.read_text())
    doc["companion_save_dc_token_family"] = TOKEN_FAMILY
    doc["companion_save_dc_derivation"] = DERIVATION
    doc["companion_save_dc_independence"] = INDEPENDENCE
    doc["companion_save_dc_entries"] = entries
    FIXTURE_PATH.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {len(entries)} companion_save_dc_entries ({len(skipped)} skipped) to {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
