#!/usr/bin/env python3
"""Derive `class_feature_entries` for `derived-evaluator-fixtures.json` FROM
THE PINNED PCGEN ORACLE -- never from `data/corpus/`, and never by importing
or running any part of this repo's own Rust evaluator.

WHY (see also `derive_derived_evaluator_fixtures.py`'s module doc, which
states the same constraint for the equipment family this file is a sibling
of): a fixture generated by the thing it tests proves nothing. This script
reads the UPSTREAM `.lst` bytes directly and parses each formula with its own
tiny, independent parser (`parse_level_scaling`, below) -- structurally
different code from `src/rules_core/derived_evaluator_fixture_check.rs`'s
`parse_class_feature_level_scaling`, so the two cannot silently agree on a
shared bug. `docs/work-inventory.json` is read for IDENTITY ONLY (which
`unit_id` a `(book, record_key)` pair carries) -- no magnitude, no
engine-computed value, is ever taken from it.

TOKEN FAMILY
------------
PCGen `BONUS:VAR|<name>|<formula>` where `<formula>` is a per-level scaling
expression of the shape this file's own `parse_level_scaling` states:
`floor((LEVELVAR + offset_pre) / divisor) + offset_post`. Re-derived
corpus-wide 2026-08-17: `data/corpus/*/class_feature/**/*.json`'s `BONUS:VAR`
tokens carry exactly 23 records matching this shape
(`SD31-E6-F11-003`'s own cycle receipt has the full census). This script
covers a hand-picked, hand-verified batch of 9 of those 23 -- the ones this
cycle could fully verify against the pinned oracle byte-for-byte in the time
available, spanning every one of the four algebraic spellings the corpus
carries (see `parse_level_scaling`'s doc comment) plus the one cross-record
level-variable alias (`RagePowersLVL`, defined on a SIBLING pool-header
record, not the power's own row) named by wave 12's own finding
(`decisions.md`, "Wave 12 wired a real pool... and it still could not reach
done"). The other 14 corpus-wide records (`max(...)`/`min(...)`-wrapped
formulas, ability-score-mixed terms, multi-hop level-variable aliases) are a
real, named follow-on -- not attempted here, not fabricated.

TARGET SELECTION
-----------------
`TARGETS` below is transcribed BY HAND from this cycle's own corpus survey
(`docs/work-inventory.json`, `kind=class_feature AND wiring_class=derived AND
status=grounded` -- 45 units, `--report` mode below reproduces the same
survey fresh). Each entry names the upstream `.lst` file to search, the
`KEY:` value that identifies the record's line, the `BONUS:VAR` name whose
formula is the headline magnitude, and the level-variable alias's own
`BONUS:VAR` name to search the SAME upstream file for (which may sit on a
DIFFERENT `KEY:` row -- the pool-header case).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "rules_core" / "derived-evaluator-fixtures.json"

# (unit_id, book, upstream_lst (relative to $PCGEN_CORPUS_ROOT), key, bonus_var_name)
TARGETS = [
    (
        "core_rulebook:class_feature:rage_power_superstition",
        "core_rulebook",
        "pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_class.lst",
        "Rage Power ~ Superstition",
        "SuperstitionSaveBonus",
    ),
    (
        "core_rulebook:class_feature:rogue_trap_sense",
        "core_rulebook",
        "pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_class.lst",
        "Rogue ~ Trap Sense",
        "TrapSenseBonus",
    ),
    # `core_rulebook:class_feature:ranger_favored_terrain` (FavoredTerrainPool,
    # (RangerFavoredTerrainLVL+2)/5) WITHDRAWN as of SD31-W13-INTEGRATE-001:
    # the corpus formula is the NUMBER OF FAVORED TERRAINS granted; the
    # engine's only matching grounding id, `class_feature.ranger.favored_
    # terrain` (pilot_compute/mod.rs), computes the flat +2/+4/+6/+8 SKILL
    # bonus instead -- a quantity this record never states (it lives on the
    # `Common/Basic Favored Terrain` sub-abilities). The unit was reaching
    # `done` on two disjoint facts: a real `grounded` evidence id for a
    # DIFFERENT magnitude than the one this fixture verified. Re-add only
    # once a real `(RangerFavoredTerrainLVL+2)/5` pool-count consumer
    # exists, with the fixtured token and the grounding id proven to be the
    # same quantity.
    (
        "core_rulebook:class_feature:paladin_channel_positive_energy",
        "core_rulebook",
        "pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_class.lst",
        "Paladin ~ Channel Positive Energy",
        "PaladinChannelDice",
    ),
    (
        "advanced_class_guide:class_feature:slayer_trapfinding",
        "advanced_class_guide",
        "pathfinder/paizo/roleplaying_game/advanced_class_guide/acg_abilities_class.lst",
        "Slayer ~ Trapfinding",
        "SlayerTrapfindingBonus",
    ),
    (
        "advanced_class_guide:class_feature:slayer_sneak_attack",
        "advanced_class_guide",
        "pathfinder/paizo/roleplaying_game/advanced_class_guide/acg_abilities_class.lst",
        "Slayer ~ Sneak Attack",
        "SneakAttackDice",
    ),
    (
        "advanced_class_guide:class_feature:slayer_stalker",
        "advanced_class_guide",
        "pathfinder/paizo/roleplaying_game/advanced_class_guide/acg_abilities_class.lst",
        "Slayer ~ Stalker",
        "SlayerStalkerBonus",
    ),
    (
        "advanced_class_guide:class_feature:bloodrager_damage_reduction",
        "advanced_class_guide",
        "pathfinder/paizo/roleplaying_game/advanced_class_guide/acg_abilities_class.lst",
        "Bloodrager ~ Damage Reduction",
        "BloodragerDR",
    ),
    (
        "ultimate_combat:class_feature:ninja_no_trace",
        "ultimate_combat",
        "pathfinder/paizo/roleplaying_game/ultimate_combat/uc_abilities_class.lst",
        "Ninja ~ No Trace",
        "NoTraceBonus",
    ),
    # --- added SD31-W15 ---------------------------------------------------
    # Four more of the 33 `derived`+held `class_feature` units, each one
    # checked against the THREE conditions this family's own wave-13
    # withdrawal established (see the `ranger_favored_terrain` note above):
    #   (a) the headline BONUS:VAR formula parses in the seam's committed
    #       shape -- no parser widening, no `max(`/`min(`/ability-score term;
    #   (b) the level variable's alias resolves inside the SAME book's
    #       `data/corpus/<book>/class_feature/` cache, which is all
    #       `find_level_var_alias` can see;
    #   (c) a REAL production consumer computes THIS token's quantity, not a
    #       different magnitude on the same record. Each is named below with
    #       the explanation id and the function behind it, and
    #       `tests/derived_evaluator_fixture_check_class_feature_consumer_quantity.rs`
    #       drives the real engine to prove the two agree at concrete levels
    #       rather than leaving it to this comment.
    (
        # `class_chassis.paladin.lay_on_hands_heal_amount`, `paladin_level / 2`
        # (pilot_compute/mod.rs). The record's OTHER magnitude
        # (`LayOnHandsTimes|(LayOnHandsLVL/2)+CHA`) mixes an ability score and
        # is not the fixtured token.
        "core_rulebook:class_feature:paladin_lay_on_hands",
        "core_rulebook",
        "pathfinder/paizo/roleplaying_game/core_rulebook/cr_abilities_class.lst",
        "Paladin ~ Lay on Hands",
        "LayOnHandsDice",
    ),
    (
        # `class_feature.acg.slayer.studied_target_bonus`,
        # `slayer_studied_target_bonus(level) = level / 5 + 1`
        # (pilot_compute/class_slayer.rs).
        "advanced_class_guide:class_feature:slayer_studied_target",
        "advanced_class_guide",
        "pathfinder/paizo/roleplaying_game/advanced_class_guide/acg_abilities_class.lst",
        "Slayer ~ Studied Target",
        "SlayerStudiedTargetBonus",
    ),
    (
        # `class_feature.uc.ninja.sneak_attack`,
        # `ninja_sneak_attack_dice(level) = (level + 1) / 2`
        # (pilot_compute/class_ultimate_combat.rs).
        "ultimate_combat:class_feature:ninja_sneak_attack",
        "ultimate_combat",
        "pathfinder/paizo/roleplaying_game/ultimate_combat/uc_abilities_class.lst",
        "Ninja ~ Sneak Attack",
        "SneakAttackDice",
    ),
    (
        # `class_feature.uc.samurai.resolve_uses`,
        # `samurai_resolve_uses_per_day(level) = (level + 1) / 2`
        # (pilot_compute/class_ultimate_combat.rs).
        "ultimate_combat:class_feature:samurai_resolve",
        "ultimate_combat",
        "pathfinder/paizo/roleplaying_game/ultimate_combat/uc_abilities_class.lst",
        "Samurai ~ Resolve",
        "SamuraiResolveTimes",
    ),
]


def pcgen_data_root() -> Path:
    root = os.environ.get("PCGEN_CORPUS_ROOT")
    if root:
        return Path(root)
    home = os.environ.get("HOME")
    if not home:
        sys.exit("HOME must be set (or PCGEN_CORPUS_ROOT given) to locate the PCGen corpus")
    return Path(home) / "workspace" / "repos" / "pcgen" / "data"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def parse_level_scaling(formula: str):
    """Independent re-implementation of the Rust seam's
    `parse_class_feature_level_scaling`, in a different language with no
    shared code, over the same four corpus-observed shapes:

        N+VAR/D        -> offset_pre=0,  divisor=D, offset_post=N
        VAR/D          -> offset_pre=0,  divisor=D, offset_post=0
        VAR/D+N        -> offset_pre=0,  divisor=D, offset_post=N
        (VAR+N)/D      -> offset_pre=N,  divisor=D, offset_post=0
        (VAR-N)/D      -> offset_pre=-N, divisor=D, offset_post=0

    Returns (level_var, offset_pre, divisor, offset_post) or None.
    """
    f = formula.strip()

    m = re.fullmatch(r"\(([A-Za-z0-9_]+)([+-]\d+)\)/(\d+)", f)
    if m:
        var, offset, divisor = m.group(1), int(m.group(2)), int(m.group(3))
        if divisor == 0:
            return None
        return var, offset, divisor, 0

    m = re.fullmatch(r"(\d+)\+([A-Za-z0-9_]+)/(\d+)", f)
    if m:
        n, var, divisor = int(m.group(1)), m.group(2), int(m.group(3))
        if divisor == 0:
            return None
        return var, 0, divisor, n

    m = re.fullmatch(r"([A-Za-z0-9_]+)/(\d+)\+(\d+)", f)
    if m:
        var, divisor, n = m.group(1), int(m.group(2)), int(m.group(3))
        if divisor == 0:
            return None
        return var, 0, divisor, n

    m = re.fullmatch(r"([A-Za-z0-9_]+)/(\d+)", f)
    if m:
        var, divisor = m.group(1), int(m.group(2))
        if divisor == 0:
            return None
        return var, 0, divisor, 0

    return None


def find_key_line(lines, key):
    """The 1-indexed line whose tab-separated fields contain `KEY:<key>`
    verbatim -- PCGen's own record-identity token, matching how
    `record_key_of` in the sibling equipment script reads it."""
    needle = f"KEY:{key}\t"
    needle_eol = f"KEY:{key}\n"
    for i, line in enumerate(lines, start=1):
        if needle in line or line.rstrip("\n").endswith(f"KEY:{key}"):
            return i
    return None


def find_bonus_var_token(line, var_name):
    """Every `BONUS:VAR|<var_name>|<formula>` token's formula half, verbatim,
    on the given raw line text -- `None` if the row carries no such token."""
    pattern = re.compile(re.escape(f"BONUS:VAR|{var_name}|") + r"([^\t]*)")
    m = pattern.search(line)
    if not m:
        return None
    return m.group(1)


def find_alias_anywhere(lines, level_var):
    """Searches EVERY line of the upstream file for a
    `BONUS:VAR|<level_var>|<alias>` token (the level variable's own
    definition may sit on a different `KEY:` row -- the pool-header case,
    e.g. `RagePowersLVL` on `Barbarian ~ Rage Powers`, consumed by the
    sibling `Rage Power ~ Superstition` row). Returns
    (line_number, alias_text) for the FIRST match, or `None`."""
    pattern = re.compile(re.escape(f"BONUS:VAR|{level_var}|") + r"([^\t]*)")
    for i, line in enumerate(lines, start=1):
        m = pattern.search(line)
        if m:
            return i, m.group(1)
    return None


def derive_one(data_root: Path, unit_id, book, upstream_lst, key, bonus_var_name):
    path = data_root / upstream_lst
    raw = path.read_bytes()
    sha = hashlib.sha256(raw).hexdigest()
    lines = raw.decode("utf-8").split("\n")

    line_no = find_key_line(lines, key)
    if line_no is None:
        return None, f"{unit_id}: no KEY:{key!r} row found in {upstream_lst}"
    line_text = lines[line_no - 1]

    formula = find_bonus_var_token(line_text, bonus_var_name)
    if formula is None:
        return None, f"{unit_id}: line {line_no} carries no BONUS:VAR|{bonus_var_name}| token"

    parsed = parse_level_scaling(formula)
    if parsed is None:
        return None, f"{unit_id}: formula {formula!r} does not match a known level-scaling shape"
    level_var, offset_pre, divisor, offset_post = parsed

    alias_hit = find_alias_anywhere(lines, level_var)
    if alias_hit is None:
        return None, f"{unit_id}: no BONUS:VAR|{level_var}| alias found anywhere in {upstream_lst}"
    alias_line, alias_value = alias_hit

    entry = {
        "unit_id": unit_id,
        "book": book,
        "record_key": key,
        "bonus_var_name": bonus_var_name,
        "upstream_lst": upstream_lst,
        "upstream_lst_sha256": sha,
        "upstream_line": line_no,
        "corpus_field": f"BONUS:VAR|{bonus_var_name}|{formula}",
        "alias_upstream_line": alias_line,
        "alias_corpus_field": f"BONUS:VAR|{level_var}|{alias_value}",
        "expected": {
            "offset_pre": offset_pre,
            "divisor": divisor,
            "offset_post": offset_post,
            "level_var": level_var,
            "class_level_alias": alias_value,
        },
    }
    return entry, None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                     help="derive and print, write nothing (used to verify without touching the fixture)")
    args = ap.parse_args()

    data_root = pcgen_data_root()
    entries = []
    errors = []
    for unit_id, book, upstream_lst, key, bonus_var_name in TARGETS:
        entry, err = derive_one(data_root, unit_id, book, upstream_lst, key, bonus_var_name)
        if err:
            errors.append(err)
            continue
        entries.append(entry)

    for e in errors:
        print(f"SKIPPED: {e}", file=sys.stderr)

    if args.check:
        print(json.dumps(entries, indent=2))
        print(f"\n{len(entries)} derived, {len(errors)} skipped", file=sys.stderr)
        return

    doc = json.loads(FIXTURE_PATH.read_text())
    doc["class_feature_token_family"] = (
        "BONUS:VAR (per-level scaling: floor((LEVELVAR + offset_pre) / divisor) + offset_post)"
    )
    doc["class_feature_derivation"] = (
        "PCGen `BONUS:VAR|<name>|<formula>` where <formula> is a class-feature per-level "
        "scaling expression. Unlike a resolved magnitude, the LEVELVAR is never resolved to a "
        "live number (it is the character's level in a base class, not a corpus-stated fact) -- "
        "expected.offset_pre/divisor/offset_post/level_var restate the FORMULA's own structure "
        "verbatim, matching the DURATION/RANGE seams' posture. expected.class_level_alias is the "
        "level variable's own declared alias, read from the corpus (possibly a SIBLING record, "
        "e.g. a pool-header ability), asserted one hop only -- never resolved further."
    )
    doc["class_feature_independence"] = (
        "scripts/derive_class_feature_level_scaling_fixtures.py re-reads the pinned upstream "
        ".lst bytes directly and parses each formula with its own from-scratch parser "
        "(parse_level_scaling), structurally independent of "
        "src/rules_core/derived_evaluator_fixture_check.rs's "
        "parse_class_feature_level_scaling. It opens no file under data/corpus/ and imports no "
        "engine module."
    )
    doc["class_feature_entries"] = entries
    FIXTURE_PATH.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {len(entries)} class_feature_entries ({len(errors)} skipped) to {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
