#!/usr/bin/env python3
"""Derive `companion_skill_entries` for `derived-evaluator-fixtures.json` FROM
THE PINNED PCGEN ORACLE -- never from `data/corpus/`, never from this repo's
Rust tables, and never by importing or running any part of its evaluator.

WHY (the same constraint `derive_companion_strength_damage_fixtures.py`
states for its own family): a fixture generated by the thing it tests proves
nothing. This script reads the UPSTREAM `.lst` bytes directly, extracts the
`BONUS:SKILL|<skills>|<formula>` token with its own regex, classifies its
formula half with its own tiny from-scratch classifier (`classify_shape`,
below -- a different implementation in a different language from
`src/rules_core/derived_evaluator_fixture_check.rs`'s
`parse_companion_skill_ability_diff`), and computes every expected skill
bonus with a plain Python subtraction, so the two sides cannot silently
agree on a shared bug.

`docs/work-inventory.json` is read for IDENTITY AND SELECTION ONLY -- which
`unit_id` a `(book, corpus_key)` pair carries, and which units are the
`wiring_class=derived, status=grounded` population this seam exists to move.
No magnitude and no engine-computed value is ever taken from it.

THE TOKEN, AND WHY IT NEEDS ITS OWN SEAM
-----------------------------------------
`BONUS:SKILL|Climb,Swim|DEX-STR` -- companion and familiar creatures whose
Dexterity typically exceeds their Strength get their Climb and Swim checks
computed from the DIFFERENCE between the two modifiers rather than from
Strength alone (what Climb and Swim otherwise key off in PF1). Re-derived
corpus-wide 2026-08-19 (`grep BONUS:SKILL` over every registered book's
`*_races_*companion*.lst`/`*_races_*familiar*.lst`): this ARITHMETIC shape
occurs 136 times, always as exactly `DEX-STR` paired with exactly the skill
list `Climb,Swim` -- zero variance. A row's OTHER `BONUS:SKILL` tokens state
a flat `TYPE=Racial` number (`BONUS:SKILL|Perception|4|TYPE=Racial`), a
different, already-static quantity this seam does not model; the token
regex below requires a `-` in the formula half specifically to exclude them.

WHAT IS DELIBERATELY NOT COVERED
---------------------------------
A formula whose two operands are not both one of the six PF1 ability
abbreviations, or that names the same ability twice, refuses rather than
guesses -- no such row exists in the pinned oracle today, and the parser
(`parse_companion_skill_ability_diff`) is written to refuse a future
corpus spelling it has never seen rather than mis-evaluate it.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "rules_core" / "derived-evaluator-fixtures.json"
INVENTORY_PATH = REPO_ROOT / "docs" / "work-inventory.json"

# `(plus_modifier, minus_modifier)` pairs each entry pins. Chosen for MUTATION
# SENSITIVITY: an evaluator that swapped the operands fails on the asymmetric
# pairs (3,1) vs (1,3) — the two are NOT symmetric so swapping changes the
# expected value; one that negated the result, added instead of subtracted,
# or returned only one operand fails on every non-(0,0) pair.
MODIFIER_PAIRS = (
    (0, 0),
    (3, 1),
    (1, 3),
    (5, -3),
    (-3, 5),
    (-4, -1),
    (-1, -4),
    (2, -2),
    (-2, 2),
)

ABILITY_ABBREVIATIONS = {"STR", "DEX", "CON", "INT", "WIS", "CHA"}

TOKEN_RE = re.compile(r"^BONUS:SKILL\|(?P<skills>[^|]+)\|(?P<formula>.+)$")


def pcgen_data_root() -> Path:
    root = os.environ.get("PCGEN_CORPUS_ROOT")
    if root:
        return Path(root)
    home = os.environ.get("HOME")
    if not home:
        sys.exit("HOME must be set (or PCGEN_CORPUS_ROOT given) to locate the PCGen corpus")
    return Path(home) / "workspace" / "repos" / "pcgen" / "data"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def classify_shape(formula: str) -> tuple[str, str] | None:
    """Independent re-implementation of the Rust seam's
    `parse_companion_skill_ability_diff`. Returns `(plus, minus)` or `None`
    for a shape this seam refuses."""
    f = "".join(formula.split())
    if "-" not in f:
        return None
    plus, _, minus = f.partition("-")
    if plus == minus:
        return None
    if plus not in ABILITY_ABBREVIATIONS or minus not in ABILITY_ABBREVIATIONS:
        return None
    return (plus, minus)


def expected_skill_bonus(plus_modifier: int, minus_modifier: int) -> int:
    """A plain integer subtraction -- no rounding question arises, unlike the
    Strength-damage seam's halving."""
    return plus_modifier - minus_modifier


def read_rows(path: Path) -> list[list[str]]:
    text = path.read_bytes().decode("utf-8")
    return [line.rstrip("\r\n").split("\t") for line in text.split("\n")]


def row_identity(fields: list[str]) -> str | None:
    for f in fields:
        if f.startswith("KEY:"):
            return f[len("KEY:") :].strip() or None
    first = fields[0].strip() if fields else ""
    if not first or first.startswith("#") or first.startswith("SOURCE"):
        return None
    return first


def skill_tokens(fields: list[str]) -> list[tuple[list[str], str]]:
    """Every `BONUS:SKILL|<skills>|<formula>` token whose formula half
    contains a `-` (the arithmetic, ability-difference shape). A row's OTHER
    `BONUS:SKILL` tokens state a flat `TYPE=Racial` number and are excluded
    at collection time -- mirroring `transcribe_companion_tables.py`'s
    `parse_skill_ability_diff_bonuses`, which applies the identical filter.
    Collecting the flat ones here too would inflate a row's arithmetic-token
    count and cause a correct single-formula row to be skipped as
    "carries N tokens" -- found by running this script against the corpus
    before this filter existed (familiar_sloth, tarsier and 14 further rows
    each carry exactly one arithmetic SKILL token alongside one or more flat
    racial ones)."""
    out = []
    for f in fields:
        m = TOKEN_RE.match(f.strip())
        if not m:
            continue
        formula = m.group("formula").strip()
        if "-" not in formula:
            continue
        skills = [s.strip() for s in m.group("skills").split(",") if s.strip()]
        out.append((skills, formula))
    return out


# BOTH statuses, and the second one is what makes this generator IDEMPOTENT --
# see `derive_companion_strength_damage_fixtures.py`'s own comment on the same
# constant for the near-miss this repeats the fix for (SD31-W15-INTEGRATE-001
# finding (b)): `apply_done_rung_stamps()` rewrites a covered unit's status
# from `grounded` to `fixture-verified`, so selecting `grounded` alone would
# pick the target population on the FIRST run and the empty set on every run
# after -- and this script REPLACES `companion_skill_entries` rather than
# merging, so a second run would silently erase every committed row.
TARGET_STATUSES = {"grounded", "fixture-verified"}


def selected_units() -> list[dict]:
    """The `kind=companion, wiring_class=derived` population at a status the
    `derived` done rung can act on, from `docs/work-inventory.json`. Identity
    and selection only."""
    doc = json.loads(INVENTORY_PATH.read_text())
    return [
        u
        for u in doc["units"]
        if u["kind"] == "companion"
        and u["wiring_class"] == "derived"
        and u["status"] in TARGET_STATUSES
        and u["book"] != "beginner_box"
    ]


def resolve_upstream(data_root: Path, basename: str) -> Path:
    hits = sorted(data_root.glob(f"pathfinder/**/{basename}"))
    if len(hits) != 1:
        raise SystemExit(
            f"{basename}: expected exactly one file under {data_root}/pathfinder, found {len(hits)}"
        )
    return hits[0]


def derive(data_root: Path):
    units = selected_units()
    by_file: dict[str, list[dict]] = collections.defaultdict(list)
    for u in units:
        by_file[u["source_file"]].append(u)

    entries = []
    skipped: list[str] = []

    for basename, group in sorted(by_file.items()):
        # CREATURE rows only -- `companion_chassis::SkillAbilityDiffBonus` is
        # a field of `CompanionRecord`, and the bar check resolves an entry
        # through `CompanionBook::companion_resolve`, which searches
        # creatures, exactly as the sibling Strength-damage seam does.
        if "_races_" not in basename:
            skipped.append(
                f"{basename}: an *_abilities_* file -- this seam covers companion CREATURE rows "
                f"({len(group)} unit(s) in this file are out of scope for it)"
            )
            continue
        path = resolve_upstream(data_root, basename)
        rel = str(path.relative_to(data_root))
        sha = sha256_file(path)
        rows = read_rows(path)
        index: dict[str, tuple[int, list[str]]] = {}
        for i, fields in enumerate(rows, start=1):
            key = row_identity(fields)
            if key and key not in index:
                index[key] = (i, fields)

        for u in sorted(group, key=lambda x: x["id"]):
            ckey = u["corpus_key"]
            hit = index.get(ckey)
            if hit is None:
                skipped.append(f"{u['id']}: no row identified {ckey!r} in {basename}")
                continue
            line_no, fields = hit
            tokens = skill_tokens(fields)
            if not tokens:
                skipped.append(
                    f"{u['id']}: row carries no BONUS:SKILL|…|… token with an arithmetic "
                    "(ability-difference) formula half"
                )
                continue
            if len(tokens) != 1:
                skipped.append(
                    f"{u['id']}: row carries {len(tokens)} arithmetic BONUS:SKILL tokens, this "
                    "seam pins rows that carry exactly one"
                )
                continue
            skills, formula = tokens[0]
            shape = classify_shape(formula)
            if shape is None:
                skipped.append(
                    f"{u['id']}: formula {formula!r} is a shape this seam refuses rather than "
                    "guesses at (see the module doc)"
                )
                continue
            plus, minus = shape
            entries.append(
                {
                    "unit_id": u["id"],
                    "book": u["book"],
                    "record_key": ckey,
                    "skills": skills,
                    "upstream_lst": rel,
                    "upstream_lst_sha256": sha,
                    "upstream_line": line_no,
                    "corpus_field": f"BONUS:SKILL|{','.join(skills)}|{formula}",
                    "expected": {
                        "plus_ability": plus,
                        "minus_ability": minus,
                        "skill_bonus_at_modifiers": [
                            {
                                "plus_modifier": pm,
                                "minus_modifier": mm,
                                "skill_bonus": expected_skill_bonus(pm, mm),
                            }
                            for pm, mm in MODIFIER_PAIRS
                        ],
                    },
                }
            )

    entries.sort(key=lambda e: e["unit_id"])
    return entries, skipped


TOKEN_FAMILY = (
    "BONUS:SKILL|<skills>|<A>-<B> (a PF1 skill-check bonus computed as the difference "
    "between two ability modifiers, e.g. Climb/Swim keyed off DEX-STR instead of STR alone)"
)
DERIVATION = (
    "PCGen `BONUS:SKILL|<skills>|<formula>` on a companion CREATURE row, where <formula> "
    "contains a `-` (the arithmetic shape; a flat TYPE=Racial number is a different, "
    "already-static quantity this seam does not model). expected.plus_ability/minus_ability "
    "name which modifier is added and which is subtracted, and "
    "expected.skill_bonus_at_modifiers pins the evaluated bonus at nine (plus, minus) "
    "modifier pairs chosen for mutation sensitivity -- a plain integer subtraction computed "
    "here in Python, NOT read back from this repo's evaluator."
)
INDEPENDENCE = (
    "scripts/derive_companion_skill_bonus_fixtures.py re-reads the pinned upstream .lst bytes "
    "directly, extracts the token with its own regex, classifies the shape with its own "
    "from-scratch classifier (classify_shape), and computes every expected value with a plain "
    "Python subtraction -- structurally independent of "
    "src/rules_core/derived_evaluator_fixture_check.rs's parse_companion_skill_ability_diff / "
    "evaluate_companion_skill_ability_diff. It opens no file under data/corpus/, reads no Rust "
    "table, and imports no engine module. docs/work-inventory.json is read for identity and "
    "selection only."
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="derive and print, write nothing")
    args = ap.parse_args()

    data_root = pcgen_data_root()
    entries, skipped = derive(data_root)

    for s in skipped:
        print(f"SKIPPED: {s}", file=sys.stderr)

    if args.check:
        print(json.dumps(entries, indent=2))
        print(f"\n{len(entries)} derived, {len(skipped)} skipped", file=sys.stderr)
        return

    doc = json.loads(FIXTURE_PATH.read_text())
    doc["companion_skill_token_family"] = TOKEN_FAMILY
    doc["companion_skill_derivation"] = DERIVATION
    doc["companion_skill_independence"] = INDEPENDENCE
    doc["companion_skill_entries"] = entries
    FIXTURE_PATH.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {len(entries)} companion_skill_entries ({len(skipped)} skipped) to {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
