//! bestiary_5 companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py bestiary_5`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `b5_races_companion.lst` -- 33 companion creature rows
//!   * `b5_races_companion_oa.lst` -- 2 companion creature rows
//!   * `b5_abilities_companion.lst` -- 22 companion ability rows

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, NaturalAttackDamageBonus, SkillAbilityDiffBonus, Speed, StatAdjustment};

/// Every bestiary_5 companion creature (35 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Familiar (Brain Mole)",
        name: "Familiar (Brain Mole)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Burrow", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:2"),
        type_segments: &["Companion", "Familiar", "Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -6 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }],
        natural_armor: None,
        source_page: Some("p.46"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion_oa.lst",
        source_line: 5,
    },
    CompanionRecord {
        key: "Companion (Cameroceras)",
        name: "Companion (Cameroceras)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Swim", feet: 20 }, Speed { mode: "Jet", feet: 90 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Tentacle", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(1),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Cameroceras"],
        external_ability_refs: &["Cameroceras ~ Pressure Adaptation", "Grab"],
        source_file: "b5_races_companion.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Familiar (Chuspiki)",
        name: "Familiar (Chuspiki)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Magical Beast"),
        race_subtype: Some("Air"),
        monster_class: Some("Magical Beast:3"),
        type_segments: &["Companion", "Familiar", "Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Tail Fan", damage_dice: Some("1d4") }, NaturalAttack { name: "Air Blast", damage_dice: Some("0") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "WIS", amount: -2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.56"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion_oa.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Companion (Ceratosaurus)",
        name: "Companion (Ceratosaurus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }],
        natural_armor: Some(4),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Ceratosaurus"],
        external_ability_refs: &["Scent", "Trip"],
        source_file: "b5_races_companion.lst",
        source_line: 7,
    },
    CompanionRecord {
        key: "Companion (Chalicotherium)",
        name: "Companion (Chalicotherium)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(4),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Chalicotherium"],
        external_ability_refs: &["Scent"],
        source_file: "b5_races_companion.lst",
        source_line: 8,
    },
    CompanionRecord {
        key: "Companion (Digmaul)",
        name: "Companion (Digmaul)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Tail", damage_dice: Some("1d2") }, NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 10 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Digmaul"],
        external_ability_refs: &["Digmaul ~ Ball Tail", "Scent"],
        source_file: "b5_races_companion.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Companion (Frog Father)",
        name: "Companion (Frog Father)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: -2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Frog Father"],
        external_ability_refs: &["Scent", "Pull", "Giant Frog ~ Tongue"],
        source_file: "b5_races_companion.lst",
        source_line: 10,
    },
    CompanionRecord {
        key: "Companion (Frog (Goliath))",
        name: "Companion (Frog (Goliath))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: -2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Frog (Goliath)"],
        external_ability_refs: &["Scent", "Pull", "Giant Frog ~ Tongue"],
        source_file: "b5_races_companion.lst",
        source_line: 11,
    },
    CompanionRecord {
        key: "Companion (Kaprosuchus)",
        name: "Companion (Kaprosuchus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(3),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Kaprosuchus"],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 12,
    },
    CompanionRecord {
        key: "Companion (Megaprimatus)",
        name: "Companion (Megaprimatus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionPrimate"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Megaprimatus"],
        external_ability_refs: &["Scent"],
        source_file: "b5_races_companion.lst",
        source_line: 13,
    },
    CompanionRecord {
        key: "Companion (Moa)",
        name: "Companion (Moa)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Talons", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(1),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Moa"],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Companion (Narwhal)",
        name: "Companion (Narwhal)",
        size: Some("M"),
        speeds: &[Speed { mode: "Swim", feet: 80 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Narwhal"],
        external_ability_refs: &["Narwhal ~ Hold Breath"],
        source_file: "b5_races_companion.lst",
        source_line: 15,
    },
    CompanionRecord {
        key: "Companion (Plesiosaurus)",
        name: "Companion (Plesiosaurus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 5 }, Speed { mode: "Swim", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(1),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Plesiosaurus"],
        external_ability_refs: &["Keen Scent", "Scent"],
        source_file: "b5_races_companion.lst",
        source_line: 16,
    },
    CompanionRecord {
        key: "Companion (Polar Bear)",
        name: "Companion (Polar Bear)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(2),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Polar Bear"],
        external_ability_refs: &["Scent"],
        source_file: "b5_races_companion.lst",
        source_line: 17,
    },
    CompanionRecord {
        key: "Companion (Polar Bear (Dire))",
        name: "Companion (Polar Bear (Dire))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(2),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Polar Bear (Dire)"],
        external_ability_refs: &["Scent"],
        source_file: "b5_races_companion.lst",
        source_line: 18,
    },
    CompanionRecord {
        key: "Companion (Therizinosaurus)",
        name: "Companion (Therizinosaurus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }],
        natural_armor: Some(4),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Therizinosaurus"],
        external_ability_refs: &["Scent", "Therizinosaurus ~ Sprint"],
        source_file: "b5_races_companion.lst",
        source_line: 19,
    },
    CompanionRecord {
        key: "Companion (Troodon)",
        name: "Companion (Troodon)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Troodon"],
        external_ability_refs: &["Scent", "Troodon ~ Easily Trained"],
        source_file: "b5_races_companion.lst",
        source_line: 20,
    },
    CompanionRecord {
        key: "Companion (Whale (Blue))",
        name: "Companion (Whale (Blue))",
        size: Some("M"),
        speeds: &[Speed { mode: "Swim", feet: 80 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Tail Slap", formula: "max(0,(STR))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.312"),
        ability_keys: &["Companion Advancement ~ Whale (Blue)"],
        external_ability_refs: &["Blue Whale ~ Hold Breath"],
        source_file: "b5_races_companion.lst",
        source_line: 21,
    },
    CompanionRecord {
        key: "Companion (Uintatherium)",
        name: "Companion (Uintatherium)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(4),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Uintatherium"],
        external_ability_refs: &["Scent"],
        source_file: "b5_races_companion.lst",
        source_line: 22,
    },
    CompanionRecord {
        key: "Companion (Wolliped)",
        name: "Companion (Wolliped)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Gore", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.313"),
        ability_keys: &["Companion Advancement ~ Wolliped"],
        external_ability_refs: &["Scent"],
        source_file: "b5_races_companion.lst",
        source_line: 23,
    },
    CompanionRecord {
        key: "Familiar (Chicken)",
        name: "Familiar (Chicken)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.112"),
        ability_keys: &["Chicken ~ Drift"],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 26,
    },
    CompanionRecord {
        key: "Familiar (Flying Fox)",
        name: "Familiar (Flying Fox)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.112"),
        ability_keys: &["Flying Fox ~ Disease Resistant"],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 27,
    },
    CompanionRecord {
        key: "Familiar (Penguin)",
        name: "Familiar (Penguin)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Swim", feet: 40 }, Speed { mode: "Tobaggan", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.112"),
        ability_keys: &["Penguin ~ Toboggan"],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 28,
    },
    CompanionRecord {
        key: "Familiar (Red Panda)",
        name: "Familiar (Red Panda)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Climb", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.112"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 29,
    },
    CompanionRecord {
        key: "Familiar (Seal)",
        name: "Familiar (Seal)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Swim", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Animal"),
        race_subtype: Some("Familiar|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Animal:1"),
        type_segments: &["Companion", "Familiar", "Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.113"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 30,
    },
    CompanionRecord {
        key: "Familiar (Trilobite)",
        name: "Familiar (Trilobite)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Vermin"),
        race_subtype: Some("Familiar|Aquatic|Augmented Magical Beast|FamiliarBase"),
        monster_class: Some("Vermin:1"),
        type_segments: &["Companion", "Familiar", "Vermin"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(1),
        source_page: Some("p.113"),
        ability_keys: &["Trilobite ~ Curl"],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 31,
    },
    CompanionRecord {
        key: "Familiar (Clockwork Familiar)",
        name: "Familiar (Clockwork Familiar)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Construct"),
        race_subtype: Some("Clockwork"),
        monster_class: Some("Construct:3"),
        type_segments: &["Companion", "Familiar", "Construct"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 0 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: 0 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 0 }],
        natural_armor: Some(2),
        source_page: Some("p.47"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 34,
    },
    CompanionRecord {
        key: "Familiar (Liminal Sprite)",
        name: "Familiar (Liminal Sprite)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Fey"),
        race_subtype: None,
        monster_class: Some("Fey:3"),
        type_segments: &["Companion", "Familiar", "Fey"],
        natural_attacks: &[],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: Some(1),
        source_page: Some("p.158"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 35,
    },
    CompanionRecord {
        key: "Familiar (Esipil)",
        name: "Familiar (Esipil)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Evil|Extraplanar|Sahkil"),
        monster_class: Some("Outsider (Fort/Will):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.213"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 36,
    },
    CompanionRecord {
        key: "Familiar (Aether Wysp)",
        name: "Familiar (Aether Wysp)",
        size: Some("T"),
        speeds: &[Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Aether|Elemental"),
        monster_class: Some("Outsider (Fort/Ref):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Tendrils", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.282"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 37,
    },
    CompanionRecord {
        key: "Familiar (Air Wysp)",
        name: "Familiar (Air Wysp)",
        size: Some("T"),
        speeds: &[Speed { mode: "Fly", feet: 100 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Air|Elemental"),
        monster_class: Some("Outsider (Fort/Ref):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Tendrils", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.282"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 38,
    },
    CompanionRecord {
        key: "Familiar (Earth Wysp)",
        name: "Familiar (Earth Wysp)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Burrow", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Earth|Elemental"),
        monster_class: Some("Outsider (Fort/Ref):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Tendrils", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.282"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 39,
    },
    CompanionRecord {
        key: "Familiar (Fire Wysp)",
        name: "Familiar (Fire Wysp)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 60 }, Speed { mode: "Fly", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Fire|Elemental"),
        monster_class: Some("Outsider (Fort/Ref):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Tendrils", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.283"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 40,
    },
    CompanionRecord {
        key: "Familiar (Water Wysp)",
        name: "Familiar (Water Wysp)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 90 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Water|Elemental"),
        monster_class: Some("Outsider (Fort/Ref):3"),
        type_segments: &["Companion", "Familiar", "Outsider"],
        natural_attacks: &[NaturalAttack { name: "Tendrils", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.283"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 41,
    },
    CompanionRecord {
        key: "Familiar (Xiao)",
        name: "Familiar (Xiao)",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Fly", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:3"),
        type_segments: &["Companion", "Familiar", "Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Slam", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[SkillAbilityDiffBonus { skills: &["Climb", "Swim"], formula: "DEX-STR" }],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -6 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: None,
        source_page: Some("p.284"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b5_races_companion.lst",
        source_line: 42,
    },
];

/// Every bestiary_5 companion ability record (22 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Cameroceras",
        name: "Companion Advancement (Cameroceras)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "CON", amount: -2 }],
        source_page: None,
        owners: &["Companion (Cameroceras)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 6,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Ceratosaurus",
        name: "Companion Advancement (Ceratosaurus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Ceratosaurus)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 7,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Chalicotherium",
        name: "Companion Advancement (Chalicotherium)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Chalicotherium)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 8,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Digmaul",
        name: "Companion Advancement (Digmaul)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Digmaul)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 9,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Frog Father",
        name: "Companion Advancement (Frog Father)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }],
        source_page: None,
        owners: &["Companion (Frog Father)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 10,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Frog (Goliath)",
        name: "Companion Advancement (Frog (Goliath))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }],
        source_page: None,
        owners: &["Companion (Frog (Goliath))"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 11,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Kaprosuchus",
        name: "Companion Advancement (Kaprosuchus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }],
        source_page: None,
        owners: &["Companion (Kaprosuchus)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 12,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Megaprimatus",
        name: "Companion Advancement (Megaprimatus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Megaprimatus)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 13,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Moa",
        name: "Companion Advancement (Moa)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: -2 }],
        source_page: None,
        owners: &["Companion (Moa)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 14,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Narwhal",
        name: "Companion Advancement (Narwhal)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Narwhal)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 15,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Plesiosaurus",
        name: "Companion Advancement (Plesiosaurus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Plesiosaurus)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 16,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Polar Bear",
        name: "Companion Advancement (Polar Bear)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Polar Bear)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 17,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Polar Bear (Dire)",
        name: "Companion Advancement (Polar Bear (Dire))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Polar Bear (Dire))"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 18,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Therizinosaurus",
        name: "Companion Advancement (Therizinosaurus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Therizinosaurus)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 19,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Troodon",
        name: "Companion Advancement (Troodon)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }],
        source_page: None,
        owners: &["Companion (Troodon)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 20,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Whale (Blue)",
        name: "Companion Advancement (Whale (Blue))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Whale (Blue))"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 21,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Uintatherium",
        name: "Companion Advancement (Uintatherium)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Uintatherium)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 22,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Wolliped",
        name: "Companion Advancement (Wolliped)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }],
        source_page: None,
        owners: &["Companion (Wolliped)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 23,
    },
    CompanionAbilityRecord {
        key: "Chicken ~ Drift",
        name: "Drift",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary", "ChickenRacialTrait"],
        description: Some("A chicken flies in short bursts, and can't use its fly speed to hover. When it flies, it must end its move action by landing or perching on a solid surface."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.112"),
        owners: &["Familiar (Chicken)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 43,
    },
    CompanionAbilityRecord {
        key: "Flying Fox ~ Disease Resistant",
        name: "Disease Resistant",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary", "FlyingFoxRacialTrait"],
        description: Some("Flying foxes are resistant to disease. They receive a +4 racial bonus on saving throws against disease."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.112"),
        owners: &["Familiar (Flying Fox)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 46,
    },
    CompanionAbilityRecord {
        key: "Penguin ~ Toboggan",
        name: "Toboggan",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary", "PenguinRacialTrait"],
        description: Some("On snow- or ice-covered terrain, a penguin can move at a rate of 30 feet by sliding on its belly rather than walking."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.112"),
        owners: &["Familiar (Penguin)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 49,
    },
    CompanionAbilityRecord {
        key: "Trilobite ~ Curl",
        name: "Curl",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary", "TrilobiteRacialTrait"],
        description: Some("As a standard action, a trilobite can curl into a ball, increasing its natural armor bonus by 2 but preventing it from taking any move actions. Uncurling is a standard action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.113"),
        owners: &["Familiar (Trilobite)"],
        cross_book_owners: &[],
        source_file: "b5_abilities_companion.lst",
        source_line: 52,
    },
];
