//! Package-backed mirror of the compiled `rules_tables` module `bonus_bestiary` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use super::monster_chassis::{
    MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterStatBlock,
    NaturalAttack, Speed,
};
pub(crate) mod monster_data;
pub fn monsters_static() -> &'static [MonsterStatBlock] {
    &*monster_data::MONSTERS
}
pub fn monster_abilities_static() -> &'static [MonsterAbilityRecord] {
    &*monster_data::MONSTER_ABILITIES
}
pub fn monsters() -> &'static [MonsterStatBlock] {
    monsters_static()
}
pub fn monster_abilities() -> &'static [MonsterAbilityRecord] {
    monster_abilities_static()
}
pub fn monster_resolve(key: &str) -> Option<&'static MonsterStatBlock> {
    monsters().iter().find(|m| m.key == key)
}
pub fn monster_ability_resolve(key: &str) -> Option<&'static MonsterAbilityRecord> {
    monster_abilities().iter().find(|a| a.key == key)
}
pub fn abilities_of(monster: &MonsterStatBlock) -> Vec<&'static MonsterAbilityRecord> {
    monster
        .ability_keys
        .iter()
        .filter_map(|key| monster_ability_resolve(key))
        .collect()
}
