//! bestiary_3 companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py bestiary_3`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `b3_races_companion.lst` -- 16 companion creature rows
//!   * `b3_races_familiar.lst` -- 15 companion creature rows
//!   * `b3_abilities_companion.lst` -- 24 companion ability rows
//!   * `b3_abilities_familiar.lst` -- 30 companion ability rows

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, NaturalAttackDamageBonus, Speed, StatAdjustment};

/// Every bestiary_3 companion creature (31 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Familiar (Flying Squirrel)",
        name: "Flying Squirrel",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.111"),
        ability_keys: &["Flying Squirrel ~ Glide"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "b3_races_familiar.lst",
        source_line: 5,
    },
    CompanionRecord {
        key: "Companion (Antelope)",
        name: "Companion (Antelope)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Antelope"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Familiar (Fox)",
        name: "Fox",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: Some("p.111"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b3_races_familiar.lst",
        source_line: 6,
    },
    CompanionRecord {
        key: "Companion (Archelon)",
        name: "Companion (Archelon)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 15 }, Speed { mode: "Swim", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 0 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(10),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Archelon"],
        external_ability_refs: &["Hold Breath", "Scent"],
        source_file: "b3_races_companion.lst",
        source_line: 7,
    },
    CompanionRecord {
        key: "Familiar (Goat)",
        name: "Goat",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: None,
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.111"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b3_races_familiar.lst",
        source_line: 7,
    },
    CompanionRecord {
        key: "Companion (Axe Beak)",
        name: "Companion (Axe Beak)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 0 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: 0 }],
        natural_armor: None,
        source_page: None,
        ability_keys: &["Companion Advancement ~ Axe Beak", "Axe Beak ~ Sudden Charge"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 8,
    },
    CompanionRecord {
        key: "Familiar (Otter)",
        name: "Otter",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.112"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b3_races_familiar.lst",
        source_line: 8,
    },
    CompanionRecord {
        key: "Companion (Baluchitherium)",
        name: "Companion (Baluchitherium)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Hoof", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(4),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Baluchitherium"],
        external_ability_refs: &["Scent"],
        source_file: "b3_races_companion.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Familiar (Pig)",
        name: "Pig",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: None,
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 0 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.112"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b3_races_familiar.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Companion (Basilosaurus)",
        name: "Companion (Basilosaurus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Swim", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 0 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Basilosaurus"],
        external_ability_refs: &["Hold Breath"],
        source_file: "b3_races_companion.lst",
        source_line: 10,
    },
    CompanionRecord {
        key: "Familiar (Raccoon)",
        name: "Raccoon",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Climb", feet: 20 }],
        reach_feet: Some(0),
        race_type: Some("Animal"),
        race_subtype: None,
        monster_class: Some("Animal:1"),
        type_segments: &["Animal"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 6 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.112"),
        ability_keys: &[],
        external_ability_refs: &[],
        source_file: "b3_races_familiar.lst",
        source_line: 10,
    },
    CompanionRecord {
        key: "Companion (Dimetrodon)",
        name: "Companion (Dimetrodon)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(2),
        source_page: None,
        ability_keys: &["Dimetrodon ~ Tearing Bite", "Companion Advancement ~ Dimetrodon"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 11,
    },
    CompanionRecord {
        key: "Companion (Elk)",
        name: "Companion (Elk)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }, NaturalAttack { name: "Hoof", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Elk"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 12,
    },
    CompanionRecord {
        key: "Companion (Giant Chameleon)",
        name: "Companion (Giant Chameleon)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: None,
        ability_keys: &["Companion Advancement ~ Giant Chameleon", "Giant Chameleon ~ Tongue"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 13,
    },
    CompanionRecord {
        key: "Archon (Harbinger)",
        name: "Archon, Harbinger",
        size: Some("T"),
        speeds: &[Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Archon|Extraplanar|Good|Lawful"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[NaturalAttack { name: "Blades", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: 0 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        natural_armor: Some(1),
        source_page: Some("p.18"),
        ability_keys: &["Harbinger Archon ~ Blades", "Harbinger Archon ~ Disassemble", "Harbinger Archon ~ Minor Archon", "Harbinger Archon ~ Wrath", "Harbinger Archon ~ Spell-Like Abilities"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "b3_races_familiar.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Companion (Giant Gecko)",
        name: "Companion (Giant Gecko)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 0 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: None,
        ability_keys: &["Giant Gecko ~ Expert Climber", "Companion Advancement ~ Giant Gecko"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Carbuncle",
        name: "Carbuncle",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }],
        reach_feet: None,
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:2"),
        type_segments: &["Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -6 }, StatAdjustment { ability: "DEX", amount: -4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 0 }],
        natural_armor: Some(2),
        source_page: Some("p.43"),
        ability_keys: &["Carbuncle ~ Empath", "Carbuncle ~ Fatal Faker", "Carbuncle ~ Specious Suggestion", "Carbuncle ~ Vulnerability to Suggestion", "Carbuncle ~ Spell-Like Abilities"],
        external_ability_refs: &[],
        source_file: "b3_races_familiar.lst",
        source_line: 15,
    },
    CompanionRecord {
        key: "Companion (Giant Vulture)",
        name: "Companion (Giant Vulture)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(2),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Giant Vulture"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 15,
    },
    CompanionRecord {
        key: "Companion (Iguanodon)",
        name: "Companion (Iguanodon)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(3),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Iguanodon", "Iguanodon ~ Thumb Spikes"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 16,
    },
    CompanionRecord {
        key: "Div (Doru)",
        name: "Div, Doru",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 40 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Div|Evil|Extraplanar"),
        monster_class: Some("Outsider (Fort/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: 0 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: Some(3),
        source_page: Some("p.86"),
        ability_keys: &["Doru ~ Poison", "Doru ~ Spell-Like Abilities"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "b3_races_familiar.lst",
        source_line: 16,
    },
    CompanionRecord {
        key: "Companion (Kangaroo)",
        name: "Companion (Kangaroo)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Kick", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: None,
        ability_keys: &["Companion Advancement ~ Kangaroo"],
        external_ability_refs: &["Scent"],
        source_file: "b3_races_companion.lst",
        source_line: 17,
    },
    CompanionRecord {
        key: "Dragon (Faerie)",
        name: "Dragon, Faerie",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 60 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(0),
        race_type: Some("Dragon"),
        race_subtype: None,
        monster_class: Some("Dragon:3"),
        type_segments: &["Dragon"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: 6 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: 6 }],
        natural_armor: Some(2),
        source_page: Some("p.91"),
        ability_keys: &["Faerie Dragon ~ Breath Weapon", "Faerie Dragon ~ Spells", "Faerie Dragon ~ Spell-Like Abilities"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "b3_races_familiar.lst",
        source_line: 17,
    },
    CompanionRecord {
        key: "Companion (Megalania)",
        name: "Companion (Megalania)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d6") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Megalania", "Megalania ~ Poison"],
        external_ability_refs: &["Scent"],
        source_file: "b3_races_companion.lst",
        source_line: 18,
    },
    CompanionRecord {
        key: "Kyton (Augur)",
        name: "Kyton, Augur",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Fly", feet: 50 }],
        reach_feet: Some(0),
        race_type: Some("Outsider"),
        race_subtype: Some("Evil|Extraplanar|Kyton|Lawful"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(2),
        source_page: Some("p.170"),
        ability_keys: &["Augur ~ Unnerving Gaze", "Augur ~ Spell-Like Abilities"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "b3_races_familiar.lst",
        source_line: 18,
    },
    CompanionRecord {
        key: "Companion (Pachycephalosaurus)",
        name: "Companion (Pachycephalosaurus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(3),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Pachycephalosaurus", "Pachycephalosaurus ~ Clobbering Charge"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 19,
    },
    CompanionRecord {
        key: "Oni (Spirit)",
        name: "Oni, Spirit",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 30 }],
        reach_feet: None,
        race_type: Some("Outsider"),
        race_subtype: Some("Native|Oni"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d4") }, NaturalAttack { name: "Gore", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: Some(1),
        source_page: Some("p.208"),
        ability_keys: &["Spirit Oni ~ Mask Symbiosis", "Spirit Oni ~ Poison", "Spirit Oni ~ Spell-Like Abilities"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "b3_races_familiar.lst",
        source_line: 19,
    },
    CompanionRecord {
        key: "Companion (Spinosaurus)",
        name: "Companion (Spinosaurus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 8 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(3),
        source_page: None,
        ability_keys: &["Companion Advancement ~ Spinosaurus"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 20,
    },
    CompanionRecord {
        key: "Rakshasa (Raktavarna)",
        name: "Rakshasa, Raktavarna",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: None,
        race_type: Some("Outsider"),
        race_subtype: Some("Native|Rakshasa|Shapechanger"),
        monster_class: Some("Outsider (Ref/Will):3"),
        type_segments: &["Outsider"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d4") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: Some(2),
        source_page: Some("p.228"),
        ability_keys: &["Raktavarna ~ Change Shape", "Raktavarna ~ Master's Eyes", "Raktavarna ~ Poison", "Raktavarna ~ Spell-Like Abilities"],
        external_ability_refs: &[],
        source_file: "b3_races_familiar.lst",
        source_line: 20,
    },
    CompanionRecord {
        key: "Companion (Thylacine)",
        name: "Companion (Thylacine)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &[],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: None,
        source_page: None,
        ability_keys: &["Thylacine ~ Powerful Jaws", "Companion Advancement ~ Thylacine"],
        external_ability_refs: &[],
        source_file: "b3_races_companion.lst",
        source_line: 21,
    },
    CompanionRecord {
        key: "Sprite",
        name: "Sprite",
        size: Some("D"),
        speeds: &[Speed { mode: "Walk", feet: 15 }, Speed { mode: "Fly", feet: 60 }],
        reach_feet: Some(0),
        race_type: Some("Fey"),
        race_subtype: None,
        monster_class: Some("Fey:1"),
        type_segments: &["Fey"],
        natural_attacks: &[],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -8 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: -4 }, StatAdjustment { ability: "WIS", amount: 0 }, StatAdjustment { ability: "CHA", amount: 0 }],
        natural_armor: None,
        source_page: Some("p.255"),
        ability_keys: &["Sprite ~ Luminous", "Sprite ~ Spell-Like Abilities"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "b3_races_familiar.lst",
        source_line: 21,
    },
    CompanionRecord {
        key: "Zoog",
        name: "Zoog",
        size: Some("T"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        reach_feet: None,
        race_type: Some("Magical Beast"),
        race_subtype: None,
        monster_class: Some("Magical Beast:2"),
        type_segments: &["Magical Beast"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("1d3") }, NaturalAttack { name: "Claw", damage_dice: Some("1d2") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 0 }, StatAdjustment { ability: "INT", amount: -6 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.287"),
        ability_keys: &["Zoog ~ Otherworldly Touch", "Zoog ~ Spell Sight", "Zoog ~ Spell-Like Abilities"],
        external_ability_refs: &[],
        source_file: "b3_races_familiar.lst",
        source_line: 22,
    },
];

/// Every bestiary_3 companion ability record (54 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Antelope",
        name: "4th-Level Advancement ~ Companion (Antelope)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: Some("Ability Scores Str +2, Dex +2, Con +2."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Antelope)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 8,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Archelon",
        name: "7th-Level Advancement ~ Companion (Archelon)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: Some("bite (1d8), Ability Scores Str +8, Dex -2, Con +4. +2 Natural Armor. Size Large."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Archelon)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 9,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Axe Beak",
        name: "4th Level Advancement ~ Companion (Axe Beak)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Axe Beak)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 10,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Baluchitherium",
        name: "7th-Level Advancement ~ Companion (Baluchitherium)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Baluchitherium)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 11,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Basilosaurus",
        name: "7th-Level Advancement ~ Companion (Basilosaurus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Basilosaurus)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 12,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dimetrodon",
        name: "7th-Level Advancement ~ Companion (Dimetrodon)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dimetrodon)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 13,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Elk",
        name: "7th-Level Advancement ~ Companion (Elk)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Elk)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 14,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Giant Chameleon",
        name: "4th-Level Advancement ~ Companion (Giant Chameleon)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Giant Chameleon)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 15,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Giant Gecko",
        name: "4th-Level Advancement ~ Companion (Giant Gecko)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Giant Gecko)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 16,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Giant Vulture",
        name: "7th-Level Advancement ~ Companion (Giant Vulture)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Giant Vulture)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 17,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Iguanodon",
        name: "7th-Level Advancement ~ Companion (Iguanodon)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Iguanodon)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 18,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Kangaroo",
        name: "4th-Level Advancement ~ Companion (Kangaroo)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Kangaroo)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 19,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Megalania",
        name: "7th-Level Advancement ~ Companion (Megalania)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Megalania)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 20,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Pachycephalosaurus",
        name: "7th-Level Advancement ~ Companion (Pachycephalosaurus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Pachycephalosaurus)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 21,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Spinosaurus",
        name: "7th-Level Advancement ~ Companion (Spinosaurus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Spinosaurus)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 22,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Thylacine",
        name: "4th-Level Advancement ~ Companion (Thylacine)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Thylacine)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 23,
    },
    CompanionAbilityRecord {
        key: "Axe Beak ~ Sudden Charge",
        name: "Sudden Charge",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["AxeBeakRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("When making a charge attack, an axe beak makes a single bite attack. If successful, it may also attempt to trip its opponent as a free action without provoking an attack of opportunity. If the attempt fails, the axe beak cannot be tripped in return."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.29"),
        owners: &["Companion (Axe Beak)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 29,
    },
    CompanionAbilityRecord {
        key: "Dimetrodon ~ Tearing Bite",
        name: "Tearing Bite",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["DimetrodonRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("A dimetrodon's jaws are filled with razor-sharp teeth of two different sizes. This gives the creature a threat range of 19-20 with its bite attack."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.78"),
        owners: &["Companion (Dimetrodon)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 32,
    },
    CompanionAbilityRecord {
        key: "Iguanodon ~ Thumb Spikes",
        name: "Thumb Spikes",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["IguanodonRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("An iguanodon's thumb spikes can inflict grievous wounds-they deal triple damage on a successful critical hit."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.78"),
        owners: &["Companion (Iguanodon)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 35,
    },
    CompanionAbilityRecord {
        key: "Flying Squirrel ~ Glide",
        name: "Glide",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["FlyingSquirrelRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("A flying squirrel cannot use its fly speed to hover. When flying, a flying squirrel must end its movement at least 5 feet lower in elevation than where it started."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.112"),
        owners: &["Familiar (Flying Squirrel)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 38,
    },
    CompanionAbilityRecord {
        key: "Pachycephalosaurus ~ Clobbering Charge",
        name: "Clobbering Charge",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["RacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("When a pachycephalosaurus hits a target with its slam attack at the end of a charge, it can initiate a bull rush as a free action to move the struck target back in the same direction as the dinosaur's charge. The pachycephalosaurus cannot move with the target of the bull rush. If a pachycephalosaurus scores a critical hit against a creature with its slam attack at the end of a charge, it also staggers the target for 1 round. If the victim succeeds at a DC 18 Fortitude save, the stagger effect is negated, but the victim still suffers the effects of the dinosaur's bull rush attempt. The save DC is Strength-based."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.79"),
        owners: &["Companion (Pachycephalosaurus)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 38,
    },
    CompanionAbilityRecord {
        key: "Giant Gecko ~ Expert Climber",
        name: "Expert Climber",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["GiantGeckoRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("A gecko's feet allow it to climb virtually any surface, no matter how slick or sheer. In effect, geckos are treated as constantly being under a natural version of the spell spider climb."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.186"),
        owners: &["Companion (Giant Gecko)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 41,
    },
    CompanionAbilityRecord {
        key: "Harbinger Archon ~ Blades",
        name: "Blades",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("A harbinger can extend blades from its body to strike with as primary natural attacks. These blades possess a +1 enhancement bonus on attack and damage rolls, and are treated as both magic and good-aligned for the purposes of penetrating damage reduction."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.18"),
        owners: &["Archon (Harbinger)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 41,
    },
    CompanionAbilityRecord {
        key: "Harbinger Archon ~ Disassemble",
        name: "Disassemble",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialQuality", "Supernatural"],
        description: Some("As a move-equivalent action, a harbinger can break apart into its components. This is treated as gaseous form, except the archon retains its full flight speed and DR, and cannot fit through gaps smaller than 1 inch in diameter. Reforming into an orrery is a standard action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.18"),
        owners: &["Archon (Harbinger)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 42,
    },
    CompanionAbilityRecord {
        key: "Harbinger Archon ~ Minor Archon",
        name: "Minor Archon",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary"],
        description: Some("Harbinger archons lack the aura of menace and teleport abilities of more powerful archons."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.18"),
        owners: &["Archon (Harbinger)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 43,
    },
    CompanionAbilityRecord {
        key: "Giant Chameleon ~ Tongue",
        name: "Tongue",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["GiantChameleonRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("A giant chameleon can grab a foe with its tongue and draw the victim to its mouth. This tongue attack has a reach of 15 feet. The attack does no damage, but allows the creature to grab. A giant chameleon does not gain the grappled condition while using its tongue in this manner."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.186"),
        owners: &["Companion (Giant Chameleon)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 44,
    },
    CompanionAbilityRecord {
        key: "Harbinger Archon ~ Wrath",
        name: "Wrath",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialQuality", "Supernatural"],
        description: Some("Once per minute, a harbinger archon can emit a blast of energy that deals 2d6 points of force damage to adjacent creatures. A DC 12 Reflex save halves this damage. The harbinger can choose to omit any target from this blast that it desires, damaging only those foes it chooses. The save DC is Charisma-based."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.18"),
        owners: &["Archon (Harbinger)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 44,
    },
    CompanionAbilityRecord {
        key: "Harbinger Archon ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["SpecialQuality", "SpellLike"],
        description: Some("(CL 6th; concentration +7) Constant-detect evil At will-dancing lights (duration lasts until dismissed) 3/day-cure light wounds, protection from evil 1/week-commune (CL 12th, 6 questions)"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Archon (Harbinger)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 45,
    },
    CompanionAbilityRecord {
        key: "Thylacine ~ Powerful Jaws",
        name: "Powerful Jaws",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["ThylacineRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("A thylacine's muscular jaws threaten a critical hit on a natural roll of 19 or 20."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.191"),
        owners: &["Companion (Thylacine)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 47,
    },
    CompanionAbilityRecord {
        key: "Carbuncle ~ Empath",
        name: "Empath",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["CarbuncleRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("Carbuncles possess a crude form of telepathy, allowing them to transmit mild impressions and remembered sensations to other creatures. This form of telepathy cannot convey language or hinder a target in any way (such as by transmitting pain). Thus, a carbuncle can relate a feeling of fear or the faint smell of leaves, but cannot directly warn an ally of a monster or tell of a treasure under a dirt mound."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.44"),
        owners: &["Carbuncle"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 48,
    },
    CompanionAbilityRecord {
        key: "Carbuncle ~ Fatal Faker",
        name: "Fatal Faker",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["CarbuncleRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("As a standard action three times per day, a carbuncle can teleport as per the spell dimension door, but only within a range of 30 feet. Upon teleporting, the carbuncle leaves behind a perfect replica of itself amid a colored flash and the sound of a reptilian choke. This replica duplicates the carbuncle in all ways, though it is obviously dead and the colorless stone in its head is reduced to worthless dust."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.44"),
        owners: &["Carbuncle"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 49,
    },
    CompanionAbilityRecord {
        key: "Carbuncle ~ Specious Suggestion",
        name: "Specious Suggestion",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["CarbuncleRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("As a standard action three times per day, a carbuncle can concentrate intently on one creature within its line of sight and attempt to impose its will upon the target. A DC 11 Will save is enough to resist this compulsion. If the target fails to resist, roll 1d6. On a result of 1-2, the target gains a flash of insight and a +2 insight bonus to its Armor Class for 1 minute. On a result of 3-4, the victim is affected as if by suggestion for 1 minute, and must follow a single (usually embarrassing, always harmless) suggestion from the carbuncle. On a result of 5-6, the victim's thoughts are garbled with those of the carbuncle, imposing a -2 penalty to the victim's Will saving throws for 1 minute. This is a mind-affecting effect. The save DC is Charisma-based."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.44"),
        owners: &["Carbuncle"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 50,
    },
    CompanionAbilityRecord {
        key: "Megalania ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["MegalaniaRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("Bite; save Fort DC 19; frequency 1/round for 6 rounds; effect 1d4 Dex damage; cure 2 consecutive saves."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.193"),
        owners: &["Companion (Megalania)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_companion.lst",
        source_line: 50,
    },
    CompanionAbilityRecord {
        key: "Carbuncle ~ Vulnerability to Suggestion",
        name: "Vulnerability to Suggestion",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["CarbuncleRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("Any mind-affecting spell can affect a carbuncle regardless of creature type limitations. A spell like charm person, for example, which typically only affects humanoid creatures, can also affect carbuncles."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.44"),
        owners: &["Carbuncle"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 51,
    },
    CompanionAbilityRecord {
        key: "Carbuncle ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["CarbuncleRacialAbility", "SpecialQuality", "SpellLike"],
        description: Some("(CL 3rd; concentration +3) 3/day-daze (DC 10), jump, levitate (self only, up to 10 feet)"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Carbuncle"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 52,
    },
    CompanionAbilityRecord {
        key: "Doru ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["DoruRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("Bite-injury; save Fort DC 13; frequency 1/round for 6 rounds; effect 1d2 Wis; cure 2 consecutive saves."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.86"),
        owners: &["Div (Doru)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 55,
    },
    CompanionAbilityRecord {
        key: "Doru ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["DoruRacialAbility", "SpecialQuality", "SpellLike"],
        description: Some("(CL 6th; concentration +8) Constant-detect good, detect magic At will-invisibility (self only) 3/day-charm person (DC 13), minor image (DC 13) 1/day-suggestion (DC 14) 1/week-commune (CL 12th, 6 questions)"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Div (Doru)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 56,
    },
    CompanionAbilityRecord {
        key: "Faerie Dragon ~ Breath Weapon",
        name: "Breath Weapon",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["FaerieDragonRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("5-foot cone, euphoria for 1d6 rounds, DC 12 Fortitude negates. Creatures affected by euphoria are staggered, sickened, and immune to fear effects for the duration. A faerie dragon can use this breath weapon once every 1d4 rounds. The save DC is Constitution-based."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.91"),
        owners: &["Dragon (Faerie)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 59,
    },
    CompanionAbilityRecord {
        key: "Faerie Dragon ~ Spells",
        name: "Spells",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: None,
        type_segments: &["FaerieDragonRacialAbility", "SpecialQuality"],
        description: Some("A faerie dragon casts spells as a 3rd-level sorcerer."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.91"),
        owners: &["Dragon (Faerie)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 60,
    },
    CompanionAbilityRecord {
        key: "Faerie Dragon ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["FaerieDragonRacialAbility", "SpecialQuality", "SpellLike"],
        description: Some("(CL 3rd; concentration +6) 3/day-greater invisibility (self only)"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Dragon (Faerie)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 61,
    },
    CompanionAbilityRecord {
        key: "Augur ~ Unnerving Gaze",
        name: "Unnerving Gaze",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["AugurRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("A creature that succumbs to an augur's unnerving gaze becomes shaken for 1 round."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.171"),
        owners: &["Kyton (Augur)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 64,
    },
    CompanionAbilityRecord {
        key: "Augur ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["AugurRacialAbility", "SpecialQuality", "SpellLike"],
        description: Some("(CL 6th; concentration +4) Constant-deathwatch At will-bleed (DC 8), mage hand, open/close 3/day-inflict light wounds (DC 10) 1/week-commune (CL 12th, 6 questions)"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Kyton (Augur)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 65,
    },
    CompanionAbilityRecord {
        key: "Spirit Oni ~ Mask Symbiosis",
        name: "Mask Symbiosis",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpiritOniRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("A spirit oni can be worn as a mask by a willing Small or Medium creature. While worn in this way, the wearer can see through the oni's eyes and speak through its mouth, although the wearer retains its own senses and voice. The spirit oni remains a separate creature, and must detach from its host's face (as a move action) if it wishes to take any action of its own (including attacking or using a spell-like ability). While a spirit oni is worn as a mask, it grants a +2 insight bonus on its host's Perception checks."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.209"),
        owners: &["Oni (Spirit)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 68,
    },
    CompanionAbilityRecord {
        key: "Spirit Oni ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpiritOniRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("Gore-injury; save Fort DC 12; frequency 1/round for 6 rounds; effect 1d2 Cha; cure 2 consecutive saves."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.209"),
        owners: &["Oni (Spirit)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 69,
    },
    CompanionAbilityRecord {
        key: "Spirit Oni ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["SpiritOniRacialAbility", "SpecialQuality", "SpellLike"],
        description: Some("(CL 6th; concentration +8) Constant-detect magic At will-invisibility (self only), mage hand 1/day-command (DC 13), sleep (DC 13) 1/week-commune (CL 12th, 6 questions)"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Oni (Spirit)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 70,
    },
    CompanionAbilityRecord {
        key: "Raktavarna ~ Change Shape",
        name: "Change Shape",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["RaktavarnaRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("As a full-round action, a raktavarna can take the shape of a handheld object, most often an ornamental light, a one-handed weapon, or a piece of treasure. If the rakshasa remains stationary in such a form, it can attempt Stealth checks even while being observed. It can remain motionless in object form indefinitely, but reverts to its true form as soon as it takes any action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.229"),
        owners: &["Rakshasa (Raktavarna)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 73,
    },
    CompanionAbilityRecord {
        key: "Raktavarna ~ Master's Eyes",
        name: "Master's Eyes",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["RaktavarnaRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("A raktavarna can designate a single creature as its master as a standard action. If the raktavarna is a spellcaster's familiar, its master is automatically that spellcaster, and the raktavarna cannot change this. As a full-round action, a raktavarna's master can observe the world as if looking through the raktavarna's eyes. The master must concentrate to maintain this link each round. The master's visual senses are suppressed for this time, and he uses the raktavarna's darkvision, detect magic, and regular eyesight to observe the world. This ability has no limit on range, and functions even across planar boundaries. If the raktavarna is slain while its master is using this ability, the master is stunned for 1d4 rounds (no save)."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.229"),
        owners: &["Rakshasa (Raktavarna)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 74,
    },
    CompanionAbilityRecord {
        key: "Raktavarna ~ Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["RaktavarnaRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("Bite-injury; save Fort DC 13; frequency 1/round for 6 rounds; effect 1d2 Wis plus modify memory; cure 1 save. Each time a victim takes Wisdom damage from this poison, a modify memory effect causes the victim to forget the previous minute's interactions with the raktavarna, as long as the raktavarna is no longer visible or is in object form. The save DC is Constitution-based."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.229"),
        owners: &["Rakshasa (Raktavarna)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 75,
    },
    CompanionAbilityRecord {
        key: "Raktavarna ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["RaktavarnaRacialAbility", "SpecialQuality", "SpellLike"],
        description: Some("(CL 6th; concentration +8) Constant-comprehend languages 1/day-charm person (DC 13), suggestion (DC 15) 1/week-commune (CL 12th, 6 questions)"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Rakshasa (Raktavarna)"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 76,
    },
    CompanionAbilityRecord {
        key: "Sprite ~ Luminous",
        name: "Luminous",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpriteRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("A sprite naturally sheds light equal to that provided by a torch. A sprite can control the color and intensity of the light as a swift action, reducing it to the dimness of a candle or even extinguishing its luminosity entirely if it wishes."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.256"),
        owners: &["Sprite"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 79,
    },
    CompanionAbilityRecord {
        key: "Sprite ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["SpriteRacialAbility", "SpecialQuality", "SpellLike"],
        description: Some("(CL 5th; concentration +5) Constant-detect evil, detect good At will-dancing lights, daze (DC 10) 1/day-color spray (DC 11)"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Sprite"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 80,
    },
    CompanionAbilityRecord {
        key: "Zoog ~ Otherworldly Touch",
        name: "Otherworldly Touch",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["ZoogRacialAbility", "SpecialQuality", "Extraordinary"],
        description: Some("A zoog's natural attacks can strike incorporeal creatures as if they were ghost touch weapons."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.288"),
        owners: &["Zoog"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 83,
    },
    CompanionAbilityRecord {
        key: "Zoog ~ Spell Sight",
        name: "Spell Sight",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["ZoogRacialAbility", "SpecialQuality", "Supernatural"],
        description: Some("A zoog's eyes radiate normal light in a 15-foot cone and increase the light level by one step for an additional 15 feet beyond that area. Any magic effect in this area glows faintly. This glow does not reveal the magic effect's school or strength. A zoog can quell or renew this light as a swift action."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.288"),
        owners: &["Zoog"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 84,
    },
    CompanionAbilityRecord {
        key: "Zoog ~ Spell-Like Abilities",
        name: "Spell-Like Abilities",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::SpellLike),
        type_segments: &["ZoogRacialAbility", "SpecialQuality", "SpellLike"],
        description: Some("(CL 1st; concentration -2) Constant-detect magic, speak with animals"),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Zoog"],
        cross_book_owners: &[],
        source_file: "b3_abilities_familiar.lst",
        source_line: 85,
    },
];
