//! Package-backed mirror of the compiled `rules_tables` module `inner_sea_magic::spell_list` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]

/// The full 9-school PF1 spell-school enum, mirroring every other book's
/// own copy exactly.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, serde::Serialize, serde::Deserialize)]
#[cfg_attr(test, derive(schemars::JsonSchema))]
#[cfg_attr(test, schemars(rename = "inner_sea_magic__spell_list__Pf1SchoolId"))]
pub enum Pf1SchoolId {
    Abjuration,
    Conjuration,
    Divination,
    Enchantment,
    Evocation,
    Illusion,
    Necromancy,
    Transmutation,
    Universal,
}
impl Pf1SchoolId {
    pub fn from_corpus_str(raw: &str) -> Option<Self> {
        match raw {
            "Abjuration" => Some(Pf1SchoolId::Abjuration),
            "Conjuration" => Some(Pf1SchoolId::Conjuration),
            "Divination" => Some(Pf1SchoolId::Divination),
            "Enchantment" => Some(Pf1SchoolId::Enchantment),
            "Evocation" => Some(Pf1SchoolId::Evocation),
            "Illusion" => Some(Pf1SchoolId::Illusion),
            "Necromancy" => Some(Pf1SchoolId::Necromancy),
            "Transmutation" => Some(Pf1SchoolId::Transmutation),
            "Universal" => Some(Pf1SchoolId::Universal),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[cfg_attr(test, derive(schemars::JsonSchema))]
#[cfg_attr(test, schemars(rename = "inner_sea_magic__spell_list__SpellListEntry"))]
pub struct SpellListEntry {
    pub key: &'static str,
    /// `decisions.md §24`: `Some(line)` ONLY when `key` above
    /// is a Codex-generated neutral identity (the row's real
    /// name is Product Identity) -- carries the real citation
    /// line so `cache_gen::spell_lane_dump` can resolve it
    /// without a name-based lookup. `None` for an ordinary entry.
    pub name_pi_line: Option<u32>,
    pub school: Option<Pf1SchoolId>,
    pub level: Option<u8>,
    pub description: Option<&'static str>,
}
pub static SPELL_LIST: crate::rules_core::rules_catalog::Table<SpellListEntry> =
    crate::rules_core::rules_catalog::Table::new("inner_sea_magic/spell_list/SPELL_LIST");
