//! book_of_the_damned_volume_2 monster + monster-ability tables, transcribed verbatim
//! from the book's own PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_monster_tables.py book_of_the_damned_volume_2`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst` (which counts `.MOD`/`.COPY` overlays the
//! inventory correctly excludes).
//!
//! Sources, with the line each record was read from carried per row:
//!   * `botd2_races.lst` -- 4 monster rows
//!   * `botd2_abilities_race.lst` -- 17 monster-ability rows

use crate::rules_core::rules_tables::monster_chassis::{MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterSpellLikeAbility, MonsterStatBlock, NaturalAttack, Speed, StatAdjustment};

/// Every book_of_the_damned_volume_2 monster stat block (4 rows).
pub(super) static MONSTERS: &[MonsterStatBlock] = &[
    MonsterStatBlock {
        key: "Demon (Vermlek)",
        name: "Demon (Vermlek)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Burrow", feet: 20 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Demon|Evil|Extraplanar"),
        challenge_rating: Some("3"),
        monster_class: Some("Outsider (Fort/Will):4"),
        source_page: Some("p.54"),
        natural_attacks: &[NaturalAttack { name: "Bite (Primary)", damage_dice: Some("1d6") }, NaturalAttack { name: "Bite (with weapon attack)", damage_dice: Some("1d6") }],
        ability_keys: &["Vermlek ~ Abandon Flesh", "Vermlek ~ Flesh Armor", "Vermlek ~ Inhabit Body", "Vermlek ~ Negative Energy Affinity"],
        external_ability_refs: &["Scent"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "DEX", amount: -2 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 2 }],
        has_spell_like_abilities: true,
        sla_cl_token: Some("HD*3/4"),
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Inflict Light Wounds (Mass)", save_dc_token: Some("15+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Spider Climb", save_dc_token: Some("12+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("TL"), spell: "Gentle Repose", save_dc_token: Some("13+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("TL"), spell: "Summon Monster II (Vermlek)", save_dc_token: Some("12+CHA") }],
        source_file: "botd2_races.lst",
        source_line: 7,
    },
    MonsterStatBlock {
        key: "Demon (Brimorak)",
        name: "Demon (Brimorak)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Demon|Evil|Extraplanar|Fire"),
        challenge_rating: Some("5"),
        monster_class: Some("Outsider (Fort/Ref):6"),
        source_page: Some("p.56"),
        natural_attacks: &[NaturalAttack { name: "Hoof", damage_dice: Some("1d3") }],
        ability_keys: &["Brimorak ~ Boiling Blood", "Brimorak ~ Breath Weapon", "Brimorak ~ Burning Hooves", "Brimorak ~ Flaming Weapon", "Brimorak ~ Smoke Breath"],
        external_ability_refs: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 8 }, StatAdjustment { ability: "INT", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 4 }],
        has_spell_like_abilities: true,
        sla_cl_token: Some("HD"),
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Dispel Magic", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Heat Metal", save_dc_token: Some("12+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Produce Flame", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("TL"), spell: "Air Walk", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("TL"), spell: "Fireball", save_dc_token: Some("13+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("TL"), spell: "Summon Monster III (Brimorak)", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("TL"), spell: "Teleport (Greater/self plus objects)", save_dc_token: None }],
        source_file: "botd2_races.lst",
        source_line: 8,
    },
    MonsterStatBlock {
        key: "Demon (Seraptis)",
        name: "Demon (Seraptis)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Demon|Evil|Extraplanar"),
        challenge_rating: Some("15"),
        monster_class: Some("Outsider (Fort/Will):15"),
        source_page: Some("p.58"),
        natural_attacks: &[NaturalAttack { name: "Claw (Primary)", damage_dice: Some("1d6") }, NaturalAttack { name: "Claw (with weapon attack)", damage_dice: Some("1d6") }, NaturalAttack { name: "Gore (primary)", damage_dice: Some("2d6") }, NaturalAttack { name: "Gore (with weapon attack)", damage_dice: Some("2d6") }],
        ability_keys: &["Seraptis ~ Bloodless", "Seraptis ~ Compelling Domination", "Seraptis ~ Gaze of Despair", "Seraptis ~ Grab", "Seraptis ~ Ravenous Embrace"],
        external_ability_refs: &["Deathwatch ~ Constant", "True Seeing ~ Constant", "Unholy Aura ~ Constant"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 12 }, StatAdjustment { ability: "DEX", amount: 12 }, StatAdjustment { ability: "CON", amount: 18 }, StatAdjustment { ability: "INT", amount: 6 }, StatAdjustment { ability: "WIS", amount: 8 }, StatAdjustment { ability: "CHA", amount: 10 }],
        has_spell_like_abilities: true,
        sla_cl_token: Some("HD"),
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("ATWILL"), time_unit: None, caster_level_token: Some("TL"), spell: "Crushing Despair", save_dc_token: Some("13+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("ATWILL"), time_unit: None, caster_level_token: Some("TL"), spell: "Dispel Magic", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("ATWILL"), time_unit: None, caster_level_token: Some("TL"), spell: "Telekinesis", save_dc_token: Some("15+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("ATWILL"), time_unit: None, caster_level_token: Some("TL"), spell: "Teleport (Greater/self plus objects)", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Confusion", save_dc_token: Some("14+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Demand", save_dc_token: Some("18+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Dominate Person", save_dc_token: Some("14+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Fly", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("TL"), spell: "Summon Monster V (Seraptis)", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("TL"), spell: "Symbol of Insanity", save_dc_token: Some("18+CHA") }],
        source_file: "botd2_races.lst",
        source_line: 9,
    },
    MonsterStatBlock {
        key: "Demon (Vavakia)",
        name: "Demon (Vavakia)",
        size: Some("H"),
        speeds: &[Speed { mode: "Walk", feet: 60 }, Speed { mode: "Fly", feet: 60 }],
        race_type: Some("Outsider"),
        race_subtype: Some("Chaotic|Demon|Evil|Extraplanar"),
        challenge_rating: Some("18"),
        monster_class: Some("Outsider (Fort/Will):18"),
        source_page: Some("p.60"),
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: Some("3d6") }, NaturalAttack { name: "Claw", damage_dice: Some("1d8") }, NaturalAttack { name: "Tail Slap", damage_dice: Some("2d8") }],
        ability_keys: &["Vavakia ~ Breath Weapon", "Vavakia ~ Smoking Wound", "Vavakia ~ Stun"],
        external_ability_refs: &["Frightful Presence", "Immunity to Fire", "Trample", "True Seeing ~ Constant", "Unholy Aura ~ Constant"],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 22 }, StatAdjustment { ability: "CON", amount: 22 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: 8 }, StatAdjustment { ability: "WIS", amount: 10 }, StatAdjustment { ability: "CHA", amount: 12 }],
        has_spell_like_abilities: true,
        sla_cl_token: Some("HD"),
        spell_like_abilities: &[MonsterSpellLikeAbility { label: "Innate", times: Some("ATWILL"), time_unit: None, caster_level_token: Some("TL"), spell: "Enervation", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("ATWILL"), time_unit: None, caster_level_token: Some("TL"), spell: "Telekinesis", save_dc_token: Some("15+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("ATWILL"), time_unit: None, caster_level_token: Some("TL"), spell: "Teleport (Greater/self plus objects)", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Blasphemy", save_dc_token: Some("17+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Power Word Stun", save_dc_token: Some("18+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("3"), time_unit: None, caster_level_token: Some("TL"), spell: "Quickened Enervation", save_dc_token: None }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("TL"), spell: "Earthquake", save_dc_token: Some("18+CHA") }, MonsterSpellLikeAbility { label: "Innate", times: Some("1"), time_unit: None, caster_level_token: Some("TL"), spell: "Summon Monster VI (Vavakia)", save_dc_token: None }],
        source_file: "botd2_races.lst",
        source_line: 10,
    },
];

/// Every book_of_the_damned_volume_2 monster-ability record (17 rows).
pub(super) static MONSTER_ABILITIES: &[MonsterAbilityRecord] = &[
    MonsterAbilityRecord {
        key: "Brimorak ~ Boiling Blood",
        name: "Boiling Blood",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Defensive"],
        description: Some("A brimorak's blood is boiling hot. It can cough out a hiedous amount of this scorching fluid as a breath weapon, but the blood also serves the demon as a defensive ability. Any creature that damages a brimorak with a slashing or piercing weapon is sprayed by boiling blood, and takes 1d4 points of fire damage with each successful hit with such a weapon. Creatures using reach weapons are not subject to this damage."),
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &["Demon (Brimorak)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 7,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Brimorak ~ Breath Weapon",
        name: "Breath Weapon",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("20-foot line of boiling blood, %1d6 fire damage, Reflex DC %2 half, usable every 1d4 rounds."),
        description_variables: &["BreathWeaponDice", "BreathWeaponDC"],
        source_page: Some("p.56"),
        owners: &["Demon (Brimorak)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 8,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Brimorak ~ Burning Hooves",
        name: "Burning Hooves",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A brimorak's hooves burn with fire, leaving scorched hoofprints on wood, stone, and most every other solid surface, yet this supernatural fire does not set alight surfaces the demon treads upon. It does make it easier to track a brimorak, though--Survival checks made to track a brimorak gain a +8 circumstance bonus. Brimoraks use their air walk ability to throw creatures off their trail, or to leave their prints in strange places (like atop roofs) to spread fear and terror. Against a prone foe, a brimorak can make two hoof attacks rather than just one."),
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &["Demon (Brimorak)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 9,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Brimorak ~ Flaming Weapon",
        name: "Flaming Weapon",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("As a free action, a brimorak can infuse a wielded weapon (including a two-handed weapon, but not a second weapon held in the off-hand) with its fiery nature, allowing it to inflict an additional 1d6 points of fire damage with the weapon. This fire damage stacks with any additional fire damage that the weapon might also inflict. The weapon loses this ability if it leaves the demon's grasp."),
        description_variables: &[],
        source_page: Some("p.56"),
        owners: &["Demon (Brimorak)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 10,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Brimorak ~ Smoke Breath",
        name: "Smoke Breath",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Aura"],
        description: Some("A brimorak's breath manifests as clouds of foul-smelling smoke when it exhales. This breath surrounds the brimorak out to a radius of %1 feet--while the smoke isn't thick enough to obscure vision or choke foes, it is enough to sicken breathing foes who are not immune to poison. A DC %2 Fortitude save grants immunity to a particular brimorak's breath for 24 hours. The save DC is Constitution-based."),
        description_variables: &["SmokeAuraRange", "SmokeAuraDC"],
        source_page: Some("p.56"),
        owners: &["Demon (Brimorak)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 11,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Seraptis ~ Bloodless",
        name: "Bloodless",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["Defensive"],
        description: Some("A seraptis's body is not completely bloodless, but what blood its body does contain is typically blood taken from its previous victims--the blood that flows through the demon's atrophied veins does nothing to give it life. Its wounds do not bleed, and it is immune to bleed effects and to attacks that utilize blood drain to function. Sneak attacks, critical hits, and similar hits function normally on a seraptis, although if such effects would normally cause bleed damage, those additional effects do not work."),
        description_variables: &[],
        source_page: Some("p.58"),
        owners: &["Demon (Seraptis)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 15,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Seraptis ~ Compelling Domination",
        name: "Compelling Domination",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("When a seraptis uses dominate person (as a spell or spell-like ability), its victims do not actively resist the control and do not gain a new saving throw when ordered to take actions against their nature unless those actions are obviously self-destructive, in which case the victim does get a new saving throw with a +2 bonus to escape the effects of the domination."),
        description_variables: &[],
        source_page: Some("p.58"),
        owners: &["Demon (Seraptis)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 16,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Seraptis ~ Gaze of Despair",
        name: "Gaze of Despair",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Aura"],
        description: Some("A seraptis' gaze fills the minds of those within %1 feet with overwhelming and soul-crushing despair. Anyone who fails a DC %2 Will save upon being exposed to a seraptis's gaze immediately takes 1d6 points of Charisma drain and is staggered for 1d6 rounds. If the Charisma drain would normally reduce to creature's Charisma to 0, that creature instead succumbs to overwhelming suicidal urges and attempts to end its life by the most convenient method at hand, subject to GM discretion (in most cases, this effect causes a creature to make a coup de grace attempt on itself, but if a more dramatic method of self-destruction is available, the creature takes that action). Once a creature reaches this suicidal state of despair, it remains in that state until its Charisma score is restored to its normal maximum--if methods of restoring lost Charisma are not available, the suicidal victim must be restrained at all times to prevent attempts to kill itself. This is a mind-affecting effect. The save DC is Charisma-based."),
        description_variables: &["GazeAuraRange", "GazeAuraDC"],
        source_page: Some("p.58"),
        owners: &["Demon (Seraptis)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 17,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Seraptis ~ Grab",
        name: "Grab",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A seraptis gains a cumulative +4 bonus on grapple attempts for each successive claw attack that hits in a single round, provided the claw attacks all this the same target. If she grabs a foe, she can use her ravenous embrace."),
        description_variables: &[],
        source_page: Some("p.58"),
        owners: &["Demon (Seraptis)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 18,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Seraptis ~ Ravenous Embrace",
        name: "Ravenous Embrace",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Once per round, a creature grappling or grappled by a seraptis can be attacked by the ravenous, toothed wounds that decorate a seraptis's arms. These teeth bite and chew, inflicting an automatic 4d6+12 points of damage each round--in addition, the wounds caused by the ravenous embrace cause 2d6 bleed and 1d4 point of Strength drain as the seraptis drinks away the victim's blood and other vital fluids. As long as the seraptis is within 30 feet of a foe suffering bleed damage from her ravenous embrace, the blood that flows from the victim writhes through the air into the seraptis's arm maws, healing the seraptis by an amount equal to the amount caused by that round's bleed effect."),
        description_variables: &[],
        source_page: Some("p.58"),
        owners: &["Demon (Seraptis)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 19,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Vavakia ~ Breath Weapon",
        name: "Breath Weapon",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("Once every 1d4 rounds, a vavakia can breathe out a 60-foot cone of green fire that seems to writhe and coil with the tortured shapes of a thousand screaming ghosts. This green fire is akin to vomiting up the countless souls the vavakia has consumed, and these souls consume flesh as surely as they consume sanity. A creature struck by this breath weapon takes %1d6 points of damage (DC %2 Reflex half)--this damage manifests as blackened, melted flesh and skin but is treated as raw profane power. Evil creatures take half damage from the breath weapon, but good creatures who take any damage from a vavakia's breath weapon are automatically staggered for 1 round by the hideous sensation. In addition, any living creature that takes damage from a vavakia's breath weapon must also make a DC %2 Fortitude save to avoid suffering 1d8 points of Wisdom drain as her sanity slips away into madness. Immediately after the vavakia expels this green \"soul fire\", the wailing flames flow in reverse back into the demon's gullet through its open maw. This heals the vavakia 1d8 points of damage for each creature that was damaged by its breath weapon. The Wisdom drain element of this breath weapon is a mind-affecting effect. The save DC is Constitution-based."),
        description_variables: &["BreathWeaponDice", "BreathWeaponDC"],
        source_page: Some("p.60"),
        owners: &["Demon (Vavakia)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 23,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Vavakia ~ Smoking Wound",
        name: "Smoking Wound",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("The wounds caused by a vavakia's fangs result in tremendous and eerie wounds. Rather than blood, wisps of green smoke constantly weep from a vavakia's bite wound--a grim manifestation of the demon's effect on a mortal soul. Each time a vavakia bites a creature, it bestows two negative levels--the wounds continue to smoke as long as the victim suffers those negative levels. The smoking wounds cause the victim to become sickened because of the hideous sensation and rank smell of the vapors. An effect that removes this sickened condition only temporarily causes the wounds to stop smoking--they begin smoking again in 1d6 rounds and persist as long as the victim suffers from the associated negative levels. Nonliving creatures bitten by a vavakia are immune to its energy-draining bite and do not exhibit smoking wounds. The Fortitude save to remove these negative levels is DC %1. The save DC is Charisma-based."),
        description_variables: &["VavakiaWoundDC"],
        source_page: Some("p.60"),
        owners: &["Demon (Vavakia)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 24,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Vavakia ~ Stun",
        name: "Stun",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &[],
        description: Some("A creature struck by a vavakia's tail slap must make a DC %1 Fortitude save or be stunned for 1 round. On a critical hit, the stun effect lasts for 1d4 rounds on a failed save, and 1 round on a successful save. The save DC is Constitution-based."),
        description_variables: &["VavakiaStunDC"],
        source_page: Some("p.60"),
        owners: &["Demon (Vavakia)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 25,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Vermlek ~ Abandon Flesh",
        name: "Abandon Flesh",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Defensive"],
        description: Some("As a swift action, a vermlek can abandon an inhabited body, crawling hideously out of its host and leaving behind an empty sack of skin and bits of gristle. In so doing, it absorbs much of the body's flesh to heal itself, restoring 2d6+3 hit points. A vermlek cannot later reclaim this body with its inhabit body ability."),
        description_variables: &[],
        source_page: Some("p.54"),
        owners: &["Demon (Vermlek)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 29,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Vermlek ~ Flesh Armor",
        name: "Flesh Armor",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &["Defensive"],
        description: Some("When a vermlek wears a humanoid body (see inhabit body, below), it treats the dead flesh and muscle as armor and gains a +3 armor bonus to its AC."),
        description_variables: &[],
        source_page: Some("p.54"),
        owners: &["Demon (Vermlek)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 30,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Vermlek ~ Inhabit Body",
        name: "Inhabit Body",
        facet: MonsterAbilityFacet::SpecialAttack,
        delivery: Some(MonsterAbilityDelivery::Supernatural),
        traits: &[],
        description: Some("A vermlek can crawl into the body of any dead Medium humanoid, consuming and replacing the bulk of the humanoid's skeleton and internal organs as it does so. This process takes 1d4 rounds for the vermlek to complete, during which it is considered flat-footed. Once the process is complete, the vermlek appears for all practical purposes to be a living but hideously obese version of the previous humanoid--it gains a +8 racial bonus on Disguise checks to appear as a normal humanoid while wearing a dead body in this manner, but does not gain any of the abilities that the dead creature possessed in life, including natural attacks, unusual movement types, or bonuses to natural armor. It loses its own burrow speed while inhabiting a body, but gains the ability to wield weapons or wear armor shaped for humanoids (although note that the armor bonus granted by wearing armor does not stack with the bonus granted by the vermlek's flesh armor ability)."),
        description_variables: &[],
        source_page: Some("p.54"),
        owners: &["Demon (Vermlek)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 31,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
    MonsterAbilityRecord {
        key: "Vermlek ~ Negative Energy Affinity",
        name: "Negative Energy Affinity",
        facet: MonsterAbilityFacet::SpecialQuality,
        delivery: Some(MonsterAbilityDelivery::Extraordinary),
        traits: &["Defensive"],
        description: Some("A vermlek is healed by negative energy and harmed by positive energy as if it were an undead creature."),
        description_variables: &[],
        source_page: Some("p.54"),
        owners: &["Demon (Vermlek)"],
        source_file: "botd2_abilities_race.lst",
        source_line: 32,
        codex_generated_name: false,
        rename_reason: None,
        rename_coordinate: None,
    },
];
