//! core_rulebook companion tables, transcribed verbatim from the book's own
//! PCGen `.lst` rows.
//!
//! GENERATED FILE -- do not hand-edit. Regenerate with
//! `python3 scripts/transcribe_companion_tables.py core_rulebook`, whose unit set is
//! `docs/work-inventory.json`'s own units for this book rather than a raw
//! line count over the `.lst`.
//!
//! Sources, with the file AND line each record was read from carried per row:
//!   * `cr_races_companion.lst` -- 38 companion creature rows
//!   * `cr_abilities_companion.lst` -- 46 companion ability rows
//!
//! NOT transcribed -- ability rows no creature row of this book owns, so
//! nothing could ever reach them on screen. Dropped rather than emitted
//! unreachable (`decisions.md §50`, adopted from the monster lane; §56.1).
//! These rows keep their `engine-does-not-hold` status in
//! `docs/work-inventory.json`, which is where the shortfall is counted; they
//! are NOT a `reach_gate` `OPEN_FINDINGS` entry, because that list is keyed by
//! FAMILY and this book's `companions` family does reach a player:
//!   * `+2 to Dexterity and Constitution`
//!   * `Animal Companion Feat ~ Acrobatic`
//!   * `Animal Companion Feat ~ Agile Maneuvers`
//!   * `Animal Companion Feat ~ Armor Proficiency (Heavy)`
//!   * `Animal Companion Feat ~ Armor Proficiency (Light)`
//!   * `Animal Companion Feat ~ Armor Proficiency (Medium)`
//!   * `Animal Companion Feat ~ Athletic`
//!   * `Animal Companion Feat ~ Blind-Fight`
//!   * `Animal Companion Feat ~ Combat Reflexes`
//!   * `Animal Companion Feat ~ Diehard`
//!   * `Animal Companion Feat ~ Dodge`
//!   * `Animal Companion Feat ~ Endurance`
//!   * `Animal Companion Feat ~ Feat`
//!   * `Animal Companion Feat ~ GM Feat`
//!   * `Animal Companion Feat ~ Great Fortitude`
//!   * `Animal Companion Feat ~ Improved Bull Rush`
//!   * `Animal Companion Feat ~ Improved Initiative`
//!   * `Animal Companion Feat ~ Improved Natural Armor`
//!   * `Animal Companion Feat ~ Improved Natural Attack`
//!   * `Animal Companion Feat ~ Improved Overrun`
//!   * `Animal Companion Feat ~ Intimidating Prowess`
//!   * `Animal Companion Feat ~ Iron Will`
//!   * `Animal Companion Feat ~ Lightning Reflexes`
//!   * `Animal Companion Feat ~ Mobility`
//!   * `Animal Companion Feat ~ Power Attack`
//!   * `Animal Companion Feat ~ Run`
//!   * `Animal Companion Feat ~ Skill Focus`
//!   * `Animal Companion Feat ~ Spring Attack`
//!   * `Animal Companion Feat ~ Stealthy`
//!   * `Animal Companion Feat ~ Toughness`
//!   * `Animal Companion Feat ~ Weapon Finesse`
//!   * `Animal Companion Feat ~ Weapon Focus`
//!   * `Animal Companion ~ AC Bonus`
//!   * `Animal Companion ~ Ability Score Increase`
//!   * `Animal Companion ~ Bonus Tricks`
//!   * `Animal Companion ~ Devotion`
//!   * `Animal Companion ~ Evasion`
//!   * `Animal Companion ~ Improved Evasion`
//!   * `Animal Companion ~ Link`
//!   * `Animal Companion ~ Multiattack`
//!   * `Animal Companion ~ Share Spells`
//!   * `Animal Companion ~ Spell Resistance`
//!   * `Animal Companion ~ Stat Bonus`
//!   * `Animal Training ~ Combat Training`
//!   * `Animal Training ~ Fighting`
//!   * `Animal Training ~ Guarding`
//!   * `Animal Training ~ Heavy Labor`
//!   * `Animal Training ~ Hunting`
//!   * `Animal Training ~ Performance`
//!   * `Animal Training ~ Riding`
//!   * `Animal Trick ~ Air Walk`
//!   * `Animal Trick ~ Attack`
//!   * `Animal Trick ~ Attack II`
//!   * `Animal Trick ~ Come`
//!   * `Animal Trick ~ Defend`
//!   * `Animal Trick ~ Down`
//!   * `Animal Trick ~ Fetch`
//!   * `Animal Trick ~ Guard`
//!   * `Animal Trick ~ Heel`
//!   * `Animal Trick ~ Perform`
//!   * `Animal Trick ~ Seek`
//!   * `Animal Trick ~ Stay`
//!   * `Animal Trick ~ Track`
//!   * `Animal Trick ~ Work`
//!   * `Base Companion ~ Animal Companion`
//!   * `Base Companion ~ Special Mount`
//!   * `Companion Advancement`
//!   * `Companion Skills`
//!   * `Companion Stat ~ CHA`
//!   * `Companion Stat ~ CON`
//!   * `Companion Stat ~ DEX`
//!   * `Companion Stat ~ INT`
//!   * `Companion Stat ~ STR`
//!   * `Companion Stat ~ WIS`
//!   * `Companion ~ Ability Score Increase`
//!   * `Companion ~ Bonus Tricks`
//!   * `Companion ~ Devotion`
//!   * `Companion ~ Evasion`
//!   * `Companion ~ Improved Evasion`
//!   * `Companion ~ Link`
//!   * `Companion ~ Multiattack`
//!   * `Companion ~ Share Spells`
//!   * `Companion ~ Spell Resistance (AC)`
//!   * `Companion ~ Spell Resistance (SM)`
//!   * `Familiar Alertness Choice ~ Alertness Active`
//!   * `Familiar Alertness Choice ~ Alertness Inactive`
//!   * `Familiar ~ Alertness`
//!   * `Familiar ~ Deliver Touch Spells`
//!   * `Familiar ~ Empathic Link`
//!   * `Familiar ~ Improved Evasion`
//!   * `Familiar ~ Intelligence Score`
//!   * `Familiar ~ Natural Armor Bonus`
//!   * `Familiar ~ Scry on Familiar`
//!   * `Familiar ~ Share Spells`
//!   * `Familiar ~ Speak One Language`
//!   * `Familiar ~ Speak with Animals of Its Kind`
//!   * `Familiar ~ Speak with Master`
//!   * `Familiar ~ Spell Resistance`
//!
//! NOT transcribed -- `*_classes_companion.lst` CLASS rows (`decisions.md
//! §65.1`). A PCGen monster class is the hit-dice progression a creature
//! row's `MONSTERCLASS:` token names -- it states no `SIZE:`, no `MOVE:` and
//! no natural attacks, so every field this chassis models transcribes empty.
//! Modelling it is a new record type (a level progression table), not a wider
//! predicate on this one. Left honestly `engine-does-not-hold`; the creature rows that
//! name them ship, and carry the token verbatim:
//!   * `Companion`
//!   * `Shadow Companion`

use crate::rules_core::rules_tables::companion_chassis::{CompanionAbilityDelivery, CompanionAbilityFacet, CompanionAbilityRecord, CompanionRecord, NaturalAttack, NaturalAttackDamageBonus, Speed, StatAdjustment};

/// Every core_rulebook companion creature (38 rows).
pub(super) static COMPANIONS: &[CompanionRecord] = &[
    CompanionRecord {
        key: "Companion (Ape)",
        name: "Companion (Ape)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Climb", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionPrimate"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.55"),
        ability_keys: &["Companion Advancement ~ Ape"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 9,
    },
    CompanionRecord {
        key: "Companion (Badger (Wolverine))",
        name: "Companion (Badger (Wolverine))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }, Speed { mode: "Burrow", feet: 10 }, Speed { mode: "Climb", feet: 10 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(2),
        source_page: Some("p.55"),
        ability_keys: &["Companion Advancement ~ Wolverine"],
        external_ability_refs: &["Rage", "Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 10,
    },
    CompanionRecord {
        key: "Companion (Bear)",
        name: "Companion (Bear)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(2),
        source_page: Some("p.55"),
        ability_keys: &["Companion Advancement ~ Bear"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 11,
    },
    CompanionRecord {
        key: "Companion (Bird (Eagle))",
        name: "Companion (Bird (Eagle))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 80 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion", "Raptor"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Talons", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.55"),
        ability_keys: &["Companion Advancement ~ Bird"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "cr_races_companion.lst",
        source_line: 12,
    },
    CompanionRecord {
        key: "Companion (Bird (Hawk))",
        name: "Companion (Bird (Hawk))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 80 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion", "Raptor"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Talons", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.55"),
        ability_keys: &["Companion Advancement ~ Bird"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "cr_races_companion.lst",
        source_line: 13,
    },
    CompanionRecord {
        key: "Companion (Bird (Owl))",
        name: "Companion (Bird (Owl))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 10 }, Speed { mode: "Fly", feet: 80 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion", "Raptor"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Talons", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.55"),
        ability_keys: &["Companion Advancement ~ Bird"],
        external_ability_refs: &["Flight Maneuverability"],
        source_file: "cr_races_companion.lst",
        source_line: 14,
    },
    CompanionRecord {
        key: "Companion (Boar)",
        name: "Companion (Boar)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(6),
        source_page: Some("p.55"),
        ability_keys: &["Companion Advancement ~ Boar"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 15,
    },
    CompanionRecord {
        key: "Companion (Camel)",
        name: "Companion (Camel)",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 8 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(1),
        source_page: Some("p.56"),
        ability_keys: &["Camel ~ Spit", "Companion Advancement ~ Camel"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 16,
    },
    CompanionRecord {
        key: "Companion (Cat (Small (Cheetah)))",
        name: "Companion (Cat (Small (Cheetah)))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 10 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Cheetah", "Cat ~ Sprint"],
        external_ability_refs: &["Scent", "Trip"],
        source_file: "cr_races_companion.lst",
        source_line: 17,
    },
    CompanionRecord {
        key: "Companion (Cat (Small (Leopard)))",
        name: "Companion (Cat (Small (Leopard)))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 10 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Leopard", "Cat ~ Sprint"],
        external_ability_refs: &["Scent", "Trip"],
        source_file: "cr_races_companion.lst",
        source_line: 18,
    },
    CompanionRecord {
        key: "Companion (Crocodile (Alligator))",
        name: "Companion (Crocodile (Alligator))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(4),
        source_page: Some("p.56"),
        ability_keys: &["Crocodile ~ Hold Breath", "Companion Advancement ~ Alligator", "Crocodile ~ Death Roll", "Crocodile ~ Sprint", "Crocodile ~ Tail Slap"],
        external_ability_refs: &[],
        source_file: "cr_races_companion.lst",
        source_line: 19,
    },
    CompanionRecord {
        key: "Companion (Dog)",
        name: "Companion (Dog)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(2),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Dog"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 20,
    },
    CompanionRecord {
        key: "Companion (Horse)",
        name: "Companion (Horse)",
        size: Some("L"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Hoof", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 6 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(4),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Horse"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 21,
    },
    CompanionRecord {
        key: "Companion (Pony)",
        name: "Companion (Pony)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Hoof", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(2),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Pony"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 22,
    },
    CompanionRecord {
        key: "Companion (Shark)",
        name: "Companion (Shark)",
        size: Some("S"),
        speeds: &[Speed { mode: "Swim", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("Aquatic"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(4),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Shark"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 23,
    },
    CompanionRecord {
        key: "Companion (Snake (Constrictor))",
        name: "Companion (Snake (Constrictor))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 8 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(2),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Snake (Constrictor)"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 24,
    },
    CompanionRecord {
        key: "Companion (Snake (Viper))",
        name: "Companion (Snake (Viper))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -10 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(2),
        source_page: Some("p.56"),
        ability_keys: &["Poison", "Companion Advancement ~ Snake (Viper)"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 25,
    },
    CompanionRecord {
        key: "Companion (Cat (Big (Lion)))",
        name: "Companion (Cat (Big (Lion)))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }],
        natural_armor: Some(1),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Lion"],
        external_ability_refs: &["Rake", "Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 28,
    },
    CompanionRecord {
        key: "Companion (Cat (Big (Tiger)))",
        name: "Companion (Cat (Big (Tiger)))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }],
        natural_armor: Some(1),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Tiger"],
        external_ability_refs: &["Rake", "Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 29,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Deinonychus))",
        name: "Companion (Dinosaur (Deinonychus))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Talons", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: Some(1),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Deinonychus)"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 30,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Velociraptor))",
        name: "Companion (Dinosaur (Velociraptor))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Talons", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: Some(1),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Velociraptor)"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 31,
    },
    CompanionRecord {
        key: "Companion (Wolf)",
        name: "Companion (Wolf)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(2),
        source_page: Some("p.56"),
        ability_keys: &["Companion Advancement ~ Wolf"],
        external_ability_refs: &["Scent", "Trip"],
        source_file: "cr_races_companion.lst",
        source_line: 32,
    },
    CompanionRecord {
        key: "Companion (Dire Rat)",
        name: "Companion (Dire Rat)",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Climb", feet: 20 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.232"),
        ability_keys: &["Companion Advancement ~ Dire Rat", "Dire Rat ~ Disease"],
        external_ability_refs: &["Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 36,
    },
    CompanionRecord {
        key: "Companion (Shadow)",
        name: "Companion (Shadow)",
        size: Some("M"),
        speeds: &[Speed { mode: "Fly", feet: 40 }],
        reach_feet: None,
        race_type: Some("Undead"),
        race_subtype: Some("Incorporeal|Undead"),
        monster_class: Some("Shadow Companion:3"),
        type_segments: &["Companion"],
        natural_attacks: &[NaturalAttack { name: "Incorporeal Touch", damage_dice: Some("1d6") }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: 4 }],
        natural_armor: None,
        source_page: Some("p.245"),
        ability_keys: &["Shadow Companion Resistance", "Shadow Companion Saves", "Strength Damage"],
        external_ability_refs: &["Channel Resistance", "Flight Maneuverability"],
        source_file: "cr_races_companion.lst",
        source_line: 42,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Allosaurus))",
        name: "Companion (Dinosaur (Allosaurus))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }, NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }],
        natural_armor: Some(4),
        source_page: Some("p.90"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Allosaurus)"],
        external_ability_refs: &["Animal Traits Output", "Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 53,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Parasaurolophus))",
        name: "Companion (Dinosaur (Parasaurolophus))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Tail Slap", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 8 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }],
        natural_armor: Some(2),
        source_page: Some("p.91"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Parasaurolophus)"],
        external_ability_refs: &["Animal Traits Output", "Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 54,
    },
    CompanionRecord {
        key: "Companion (Dinosaur (Tylosaurus))",
        name: "Companion (Dinosaur (Tylosaurus))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: Some("AnimalCompanionDinosaur"),
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -2 }],
        natural_armor: Some(3),
        source_page: Some("p.91"),
        ability_keys: &["Companion Advancement ~ Dinosaur (Tylosaurus)"],
        external_ability_refs: &["Animal Traits Output", "Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 55,
    },
    CompanionRecord {
        key: "Companion (Gar)",
        name: "Companion (Gar)",
        size: Some("M"),
        speeds: &[Speed { mode: "Swim", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -9 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(1),
        source_page: Some("p.128"),
        ability_keys: &["Companion Advancement ~ Gar"],
        external_ability_refs: &["Animal Traits Output", "Can't Be Tripped", "Grab ~ Bite"],
        source_file: "cr_races_companion.lst",
        source_line: 56,
    },
    CompanionRecord {
        key: "Companion (Herd Animal (Ram))",
        name: "Companion (Herd Animal (Ram))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Gore", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(1),
        source_page: Some("p.154"),
        ability_keys: &["Companion Advancement ~ Herd Animal (Ram)"],
        external_ability_refs: &["Animal Traits Output", "Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 57,
    },
    CompanionRecord {
        key: "Companion (Hippopotamus)",
        name: "Companion (Hippopotamus)",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(6),
        source_page: Some("p.157"),
        ability_keys: &["Companion Advancement ~ Hippopotamus"],
        external_ability_refs: &["Animal Traits Output", "Hippopotamus ~ Sweat", "Scent", "Hippopotamus Companion Natural Attack", "!PRETEMPLATE:1,Hippopotamus Companion Advancement"],
        source_file: "cr_races_companion.lst",
        source_line: 58,
    },
    CompanionRecord {
        key: "Companion (Megafauna (Arsinoitherium))",
        name: "Companion (Megafauna (Arsinoitherium))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Gore", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 4 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(4),
        source_page: Some("p.186"),
        ability_keys: &["Companion Advancement ~ Megafauna (Arsinoitherium)"],
        external_ability_refs: &["Animal Traits Output", "Scent", "Arsinoitherium Companion Natural Attack", "!PRETEMPLATE:1,Arsinoitherium Companion Advancement"],
        source_file: "cr_races_companion.lst",
        source_line: 59,
    },
    CompanionRecord {
        key: "Companion (Megafauna (Gylptodon))",
        name: "Companion (Megafauna (Gylptodon))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(5),
        source_page: Some("p.186"),
        ability_keys: &["Companion Advancement ~ Megafauna (Gylptodon)"],
        external_ability_refs: &["Animal Traits Output", "Scent", "Gylptodon Companion Natural Attack", "!PRETEMPLATE:1,Gylptodon Companion Advancement"],
        source_file: "cr_races_companion.lst",
        source_line: 60,
    },
    CompanionRecord {
        key: "Companion (Megafauna (Megaloceros))",
        name: "Companion (Megafauna (Megaloceros))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 50 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Gore", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Gore", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "DEX", amount: 6 }, StatAdjustment { ability: "CON", amount: 4 }, StatAdjustment { ability: "WIS", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: Some(3),
        source_page: Some("p.187"),
        ability_keys: &["Companion Advancement ~ Megafauna (Megaloceros)"],
        external_ability_refs: &["Animal Traits Output", "Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 61,
    },
    CompanionRecord {
        key: "Companion (Megafauna (Megatherium))",
        name: "Companion (Megafauna (Megatherium))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 40 }, Speed { mode: "Climb", feet: 10 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Claw", damage_dice: None }],
        natural_attack_damage_bonuses: &[],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(5),
        source_page: Some("p.187"),
        ability_keys: &["Companion Advancement ~ Megafauna (Megatherium)"],
        external_ability_refs: &["Animal Traits Output", "Scent"],
        source_file: "cr_races_companion.lst",
        source_line: 62,
    },
    CompanionRecord {
        key: "Companion (Primate (Baboon))",
        name: "Companion (Primate (Baboon))",
        size: Some("S"),
        speeds: &[Speed { mode: "Walk", feet: 30 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "INT", amount: -8 }, StatAdjustment { ability: "CHA", amount: -6 }],
        natural_armor: None,
        source_page: Some("p.212"),
        ability_keys: &["Companion Advancement ~ Primate (Baboon)"],
        external_ability_refs: &["Animal Traits Output"],
        source_file: "cr_races_companion.lst",
        source_line: 63,
    },
    CompanionRecord {
        key: "Companion (Ray (Manta))",
        name: "Companion (Ray (Manta))",
        size: Some("M"),
        speeds: &[Speed { mode: "Swim", feet: 60 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Tail Slap", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -9 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: Some(1),
        source_page: Some("p.232"),
        ability_keys: &["Companion Advancement ~ Ray (Manta)"],
        external_ability_refs: &["Animal Traits Output"],
        source_file: "cr_races_companion.lst",
        source_line: 64,
    },
    CompanionRecord {
        key: "Companion (Ray (Stingray))",
        name: "Companion (Ray (Stingray))",
        size: Some("S"),
        speeds: &[Speed { mode: "Swim", feet: 40 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Tail Slap", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Tail Slap", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -4 }, StatAdjustment { ability: "DEX", amount: 4 }, StatAdjustment { ability: "CON", amount: 2 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "INT", amount: -9 }, StatAdjustment { ability: "CHA", amount: -8 }],
        natural_armor: None,
        source_page: Some("p.232"),
        ability_keys: &["Companion Advancement ~ Ray (Stingray)"],
        external_ability_refs: &["Animal Traits Output", "Stingray ~ Poison"],
        source_file: "cr_races_companion.lst",
        source_line: 65,
    },
    CompanionRecord {
        key: "Companion (Turtle (Giant Snapping))",
        name: "Companion (Turtle (Giant Snapping))",
        size: Some("M"),
        speeds: &[Speed { mode: "Walk", feet: 20 }, Speed { mode: "Swim", feet: 20 }],
        reach_feet: Some(5),
        race_type: Some("Companion"),
        race_subtype: None,
        monster_class: Some("Companion:2"),
        type_segments: &["Companion", "AnimalCompanion"],
        natural_attacks: &[NaturalAttack { name: "Bite", damage_dice: None }],
        natural_attack_damage_bonuses: &[NaturalAttackDamageBonus { attack: "Bite", formula: "max(0,(STR/2))" }],
        skill_ability_diff_bonuses: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: -2 }, StatAdjustment { ability: "DEX", amount: 0 }, StatAdjustment { ability: "CON", amount: -2 }, StatAdjustment { ability: "INT", amount: -9 }, StatAdjustment { ability: "WIS", amount: 2 }, StatAdjustment { ability: "CHA", amount: -4 }],
        natural_armor: Some(10),
        source_page: Some("p.273"),
        ability_keys: &["Crocodile ~ Hold Breath", "Companion Advancement ~ Turtle (Giant Snapping)"],
        external_ability_refs: &["Scent", "Animal Traits Output"],
        source_file: "cr_races_companion.lst",
        source_line: 66,
    },
];

/// Every core_rulebook companion ability record (46 rows).
pub(super) static COMPANION_ABILITIES: &[CompanionAbilityRecord] = &[
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Ape",
        name: "Companion Advancement (Ape)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Ape)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 99,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Wolverine",
        name: "Companion Advancement (Badger (Wolverine))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Badger (Wolverine))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 100,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Bear",
        name: "Companion Advancement (Bear)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Bear)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 101,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Bird",
        name: "Companion Advancement (Bird)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Bird (Eagle))", "Companion (Bird (Hawk))", "Companion (Bird (Owl))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 102,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Boar",
        name: "Companion Advancement (Boar)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Boar)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 103,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Camel",
        name: "Companion Advancement (Camel)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Camel)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 104,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Cheetah",
        name: "Companion Advancement (Cat (Small (Cheetah)))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Cat (Small (Cheetah)))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 105,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Leopard",
        name: "Companion Advancement (Cat (Small (Leopard)))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Cat (Small (Leopard)))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 106,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Alligator",
        name: "Companion Advancement (Crocodile (Alligator))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Crocodile (Alligator))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 107,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dog",
        name: "Companion Advancement (Dog)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dog)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 108,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Horse",
        name: "Companion Advancement (Horse)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Horse)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 109,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Pony",
        name: "Companion Advancement (Pony)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Pony)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 110,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Shark",
        name: "Companion Advancement (Shark)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Shark)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 111,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Snake (Constrictor)",
        name: "Companion Advancement (Snake (Constrictor))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Snake (Constrictor))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 112,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Snake (Viper)",
        name: "Companion Advancement (Snake (Viper))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Snake (Viper))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 113,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dire Rat",
        name: "Companion Advancement (Dire Rat)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Dire Rat)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 114,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Lion",
        name: "Companion Advancement (Cat (Big (Lion)))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Cat (Big (Lion)))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 117,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Tiger",
        name: "Companion Advancement (Cat (Big (Tiger)))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Cat (Big (Tiger)))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 118,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Deinonychus)",
        name: "Companion Advancement (Dinosaur (Deinonychus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Deinonychus))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 119,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Velociraptor)",
        name: "Companion Advancement (Dinosaur (Velociraptor))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Velociraptor))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 120,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Wolf",
        name: "Companion Advancement (Wolf)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Wolf)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 121,
    },
    CompanionAbilityRecord {
        key: "Shadow Companion Saves",
        name: "+4 bonus on Will saves made to halve the damage from positive channeled energy",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: None,
        type_segments: &["SpecialQuality"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Shadow)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 126,
    },
    CompanionAbilityRecord {
        key: "Shadow Companion Resistance",
        name: "Cannot be turned or commanded",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: None,
        type_segments: &["SpecialQuality"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Shadow)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 127,
    },
    CompanionAbilityRecord {
        key: "Strength Damage",
        name: "Strength Damage",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Supernatural),
        type_segments: &["SpecialAttack", "Supernatural"],
        description: Some("A shadow's touch deals 1d6 points of Strength damage to a living creature. This is a negative energy effect. A creature dies if this Strength damage equals or exceeds its actual Strength score."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Shadow)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 128,
    },
    CompanionAbilityRecord {
        key: "Poison",
        name: "Poison",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: None,
        type_segments: &["SpecialAttack"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Snake (Viper))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 179,
    },
    CompanionAbilityRecord {
        key: "Camel ~ Spit",
        name: "Spit",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: None,
        type_segments: &["SpecialAttack"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Camel)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 180,
    },
    CompanionAbilityRecord {
        key: "Dire Rat ~ Disease",
        name: "Disease",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Extraordinary"],
        description: Some("Filth Fever: Bite injury; Save Fort DC %1; Onset 1d3 days; Frequency 1/day; Effect 1d3 Dex damage and 1d3 Con damage; Cure 2 consecutive saves."),
        description_variables: &["DiseaseDC"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.232"),
        owners: &["Companion (Dire Rat)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 184,
    },
    CompanionAbilityRecord {
        key: "Crocodile ~ Death Roll",
        name: "Death Roll",
        facet: Some(CompanionAbilityFacet::SpecialAttack),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialAttack", "Special Attack", "Special Ability", "Extraordinary"],
        description: Some("When grappling a foe of its size or smaller, a crocodile can perform a death roll upon making a successful grapple check. As it clings to its foe, it tucks in its legs and rolls rapidly, twisting and wrenching its victim. The crocodile inflicts its bite damage and knocks the creature prone. If successful, the crocodile maintains its grapple."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.51"),
        owners: &["Companion (Crocodile (Alligator))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 188,
    },
    CompanionAbilityRecord {
        key: "Crocodile ~ Hold Breath",
        name: "Hold Breath",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Special Quality", "Special Ability", "Extraordinary"],
        description: Some("A crocodile can hold its breath for %1 rounds before it risks drowning."),
        description_variables: &["HoldBreathRounds"],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.51"),
        owners: &["Companion (Crocodile (Alligator))", "Companion (Turtle (Giant Snapping))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 189,
    },
    CompanionAbilityRecord {
        key: "Crocodile ~ Sprint",
        name: "Sprint",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Special Ability", "Extraordinary", "ModifyMovement"],
        description: Some("Once per minute a crocodile may sprint, increasing its land speed to 40 feet for 1 round."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.51"),
        owners: &["Companion (Crocodile (Alligator))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 190,
    },
    CompanionAbilityRecord {
        key: "Crocodile ~ Tail Slap",
        name: "Tail Slap",
        facet: None,
        delivery: None,
        type_segments: &["NaturalAttack", "NaturalAttackSecondary", "Secondary"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.301"),
        owners: &["Companion (Crocodile (Alligator))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 191,
    },
    CompanionAbilityRecord {
        key: "Cat ~ Sprint",
        name: "Sprint",
        facet: Some(CompanionAbilityFacet::SpecialQuality),
        delivery: Some(CompanionAbilityDelivery::Extraordinary),
        type_segments: &["SpecialQuality", "Extraordinary", "ModifyMovement"],
        description: Some("Once per hour, a Small Cat companion can move at 10 times its normal speed (500 feet) when it makes a charge."),
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: Some("p.40"),
        owners: &["Companion (Cat (Small (Cheetah)))", "Companion (Cat (Small (Leopard)))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 194,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Allosaurus)",
        name: "Companion Advancement (Dinosaur (Allosaurus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Allosaurus))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 203,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Parasaurolophus)",
        name: "Companion Advancement (Dinosaur (Parasaurolophus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Parasaurolophus))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 204,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Dinosaur (Tylosaurus)",
        name: "Companion Advancement (Dinosaur (Tylosaurus))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Dinosaur (Tylosaurus))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 205,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Gar",
        name: "Companion Advancement (Gar)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Gar)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 206,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Herd Animal (Ram)",
        name: "Companion Advancement (Herd Animal (Ram))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Herd Animal (Ram))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 207,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Hippopotamus",
        name: "Companion Advancement (Hippopotamus)",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Hippopotamus)"],
        source_file: "cr_abilities_companion.lst",
        source_line: 208,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Megafauna (Arsinoitherium)",
        name: "Companion Advancement (Megafauna (Arsinoitherium))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Megafauna (Arsinoitherium))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 209,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Megafauna (Gylptodon)",
        name: "Companion Advancement (Megafauna (Gylptodon))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Megafauna (Gylptodon))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 210,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Megafauna (Megaloceros)",
        name: "Companion Advancement (Megafauna (Megaloceros))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Megafauna (Megaloceros))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 211,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Megafauna (Megatherium)",
        name: "Companion Advancement (Megafauna (Megatherium))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Megafauna (Megatherium))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 212,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Primate (Baboon)",
        name: "Companion Advancement (Primate (Baboon))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[StatAdjustment { ability: "STR", amount: 2 }, StatAdjustment { ability: "CON", amount: 2 }],
        source_page: None,
        owners: &["Companion (Primate (Baboon))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 213,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Ray (Manta)",
        name: "Companion Advancement (Ray (Manta))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Ray (Manta))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 214,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Ray (Stingray)",
        name: "Companion Advancement (Ray (Stingray))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Ray (Stingray))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 215,
    },
    CompanionAbilityRecord {
        key: "Companion Advancement ~ Turtle (Giant Snapping)",
        name: "Companion Advancement (Turtle (Giant Snapping))",
        facet: Some(CompanionAbilityFacet::CompanionAdvancement),
        delivery: None,
        type_segments: &["CompanionAdvancement"],
        description: None,
        description_variables: &[],
        description_variants: &[],
        stat_adjustments: &[],
        source_page: None,
        owners: &["Companion (Turtle (Giant Snapping))"],
        source_file: "cr_abilities_companion.lst",
        source_line: 216,
    },
];
