//! PF1 CRB Sorcerer spell list — per-class spell-level overrides.
//!
//! Mirrors `ranger_spell_list.rs`/`paladin_spell_list.rs`'s own doc comment
//! exactly, substituting Sorcerer: `crb::spell_list::SPELL_LIST`'s `level`
//! field is the MINIMUM spell level across every class named in the
//! corpus's `CLASSES:` tag for that record, not necessarily the
//! Sorcerer-specific level. This table re-parses the same corpus record's
//! raw `CLASSES:` tag directly (`core_rulebook/cr_spells.lst`), isolating
//! only the Sorcerer-specific level for each of the 394 real records that
//! name Sorcerer at all: 20 cantrips (0th level), 42 first-level, 51
//! second-level, 46 third-level, 41 fourth-level, 47 fifth-level, 46
//! sixth-level, 40 seventh-level, 37 eighth-level, 24 ninth-level --
//! matching the real PF1 Sorcerer/Wizard shared arcane list, the largest
//! spell list in the corpus (verified via a direct parse of the raw
//! `CLASSES:` token). Every `key` here is spot-checked against a real,
//! exact `crb::spell_list::SPELL_LIST` key -- this is a strict subset of
//! the 652 CRB spell records, never an invented name.
//!
//! Unlike Ranger/Paladin (partial casters, prepared, no 0th-level spells),
//! Sorcerer is a full 9th-level caster with 0th-level cantrips included:
//! spell level 0 entries are real (cantrips are "spells known" only, per
//! PF1 rules, outside the spells-per-day ladder but still capped by the
//! Sorcerer Spells Known table's own 0th-level column).
//!
//! Regenerate by re-parsing `cr_spells.lst`'s `CLASSES:` tag for any
//! `|`-separated group whose name list contains "Sorcerer", taking that
//! group's own level (not the record's collapsed minimum), if the corpus
//! changes.

/// (spell key, Sorcerer-specific spell level 0-9). A real CRB Sorcerer may
/// only know a spell that appears in this table, subject to the
/// character's own spell-level access ceiling (for 1st+ level spells) and
/// the Sorcerer Spells Known table's per-level cap -- see
/// `sorcerer_spell_level` for the lookup helper.
pub const SORCERER_SPELL_LIST: &[(&str, u8)] = &[
    ("Acid Arrow", 2),
    ("Acid Fog", 6),
    ("Acid Splash", 0),
    ("Alarm", 1),
    ("Alter Self", 2),
    ("Analyze Dweomer", 6),
    ("Animal Growth", 5),
    ("Animate Dead", 4),
    ("Animate Rope", 1),
    ("Antimagic Field", 6),
    ("Antipathy", 8),
    ("Arcane Eye", 4),
    ("Arcane Lock", 2),
    ("Arcane Mark", 0),
    ("Arcane Sight", 3),
    ("Arcane Sight (Greater)", 7),
    ("Astral Projection", 9),
    ("Baleful Polymorph", 5),
    ("Banishment", 7),
    ("Bear's Endurance", 2),
    ("Bear's Endurance (Mass)", 6),
    ("Beast Shape I", 3),
    ("Beast Shape II", 4),
    ("Beast Shape III", 5),
    ("Beast Shape IV", 6),
    ("Bestow Curse", 4),
    ("Binding", 8),
    ("Black Tentacles", 4),
    ("Bleed", 0),
    ("Blight", 5),
    ("Blindness/Deafness", 2),
    ("Blink", 3),
    ("Blur", 2),
    ("Break Enchantment", 5),
    ("Bull's Strength", 2),
    ("Bull's Strength (Mass)", 6),
    ("Burning Hands", 1),
    ("Cat's Grace", 2),
    ("Cat's Grace (Mass)", 6),
    ("Cause Fear", 1),
    ("Chain Lightning", 6),
    ("Charm Monster", 4),
    ("Charm Monster (Mass)", 8),
    ("Charm Person", 1),
    ("Chill Touch", 1),
    ("Circle of Death", 6),
    ("Clairaudience/Clairvoyance", 3),
    ("Clenched Fist", 8),
    ("Clone", 8),
    ("Cloudkill", 5),
    ("Color Spray", 1),
    ("Command Undead", 2),
    ("Comprehend Languages", 1),
    ("Cone of Cold", 5),
    ("Confusion", 4),
    ("Contact Other Plane", 5),
    ("Contagion", 4),
    ("Contingency", 6),
    ("Continual Flame", 2),
    ("Control Undead", 7),
    ("Control Water", 6),
    ("Control Weather", 7),
    ("Create Greater Undead", 8),
    ("Create Undead", 6),
    ("Crushing Despair", 4),
    ("Crushing Hand", 9),
    ("Dancing Lights", 0),
    ("Darkness", 2),
    ("Darkvision", 2),
    ("Daylight", 3),
    ("Daze", 0),
    ("Daze Monster", 2),
    ("Deep Slumber", 3),
    ("Delayed Blast Fireball", 7),
    ("Demand", 8),
    ("Detect Magic", 0),
    ("Detect Poison", 0),
    ("Detect Scrying", 4),
    ("Detect Secret Doors", 1),
    ("Detect Thoughts", 2),
    ("Detect Undead", 1),
    ("Dimension Door", 4),
    ("Dimensional Anchor", 4),
    ("Dimensional Lock", 8),
    ("Discern Location", 8),
    ("Disguise Self", 1),
    ("Disintegrate", 6),
    ("Dismissal", 5),
    ("Dispel Magic", 3),
    ("Dispel Magic (Greater)", 6),
    ("Displacement", 3),
    ("Disrupt Undead", 0),
    ("Dominate Monster", 9),
    ("Dominate Person", 5),
    ("Dream", 5),
    ("Eagle's Splendor", 2),
    ("Eagle's Splendor (Mass)", 6),
    ("Elemental Body I", 4),
    ("Elemental Body II", 5),
    ("Elemental Body III", 6),
    ("Elemental Body IV", 7),
    ("Endure Elements", 1),
    ("Energy Drain", 9),
    ("Enervation", 4),
    ("Enlarge Person", 1),
    ("Enlarge Person (Mass)", 4),
    ("Erase", 1),
    ("Ethereal Jaunt", 7),
    ("Etherealness", 9),
    ("Expeditious Retreat", 1),
    ("Explosive Runes", 3),
    ("Eyebite", 6),
    ("Fabricate", 5),
    ("False Life", 2),
    ("False Vision", 5),
    ("Fear", 4),
    ("Feather Fall", 1),
    ("Feeblemind", 5),
    ("Finger of Death", 7),
    ("Fire Shield", 4),
    ("Fire Trap", 4),
    ("Fireball", 3),
    ("Flame Arrow", 3),
    ("Flaming Sphere", 2),
    ("Flare", 0),
    ("Flesh to Stone", 6),
    ("Floating Disk", 1),
    ("Fly", 3),
    ("Fog Cloud", 2),
    ("Forcecage", 7),
    ("Forceful Hand", 6),
    ("Foresight", 9),
    ("Form of the Dragon I", 6),
    ("Form of the Dragon II", 7),
    ("Form of the Dragon III", 8),
    ("Fox's Cunning", 2),
    ("Fox's Cunning (Mass)", 6),
    ("Freedom", 9),
    ("Freezing Sphere", 6),
    ("Gaseous Form", 3),
    ("Gate", 9),
    ("Geas (Lesser)", 4),
    ("Geas/Quest", 6),
    ("Gentle Repose", 3),
    ("Ghost Sound", 0),
    ("Ghoul Touch", 2),
    ("Giant Form I", 7),
    ("Giant Form II", 8),
    ("Glitterdust", 2),
    ("Globe of Invulnerability", 6),
    ("Globe of Invulnerability (Lesser)", 4),
    ("Grasping Hand", 7),
    ("Grease", 1),
    ("Guards and Wards", 6),
    ("Gust of Wind", 2),
    ("Hallucinatory Terrain", 4),
    ("Halt Undead", 3),
    ("Haste", 3),
    ("Heroism", 3),
    ("Heroism (Greater)", 6),
    ("Hideous Laughter", 2),
    ("Hold Monster", 5),
    ("Hold Monster (Mass)", 9),
    ("Hold Person", 3),
    ("Hold Person (Mass)", 7),
    ("Hold Portal", 1),
    ("Horrid Wilting", 8),
    ("Hypnotic Pattern", 2),
    ("Hypnotism", 1),
    ("Ice Storm", 4),
    ("Identify", 1),
    ("Illusory Script", 3),
    ("Illusory Wall", 4),
    ("Imprisonment", 9),
    ("Incendiary Cloud", 8),
    ("Insanity", 7),
    ("Instant Summons", 7),
    ("Interposing Hand", 5),
    ("Invisibility", 2),
    ("Invisibility (Greater)", 4),
    ("Invisibility (Mass)", 7),
    ("Invisibility Sphere", 3),
    ("Iron Body", 8),
    ("Irresistible Dance", 8),
    ("Jump", 1),
    ("Keen Edge", 3),
    ("Knock", 2),
    ("Legend Lore", 6),
    ("Levitate", 2),
    ("Light", 0),
    ("Lightning Bolt", 3),
    ("Limited Wish", 7),
    ("Locate Creature", 4),
    ("Locate Object", 2),
    ("Mage Armor", 1),
    ("Mage Hand", 0),
    ("Mage's Disjunction", 9),
    ("Mage's Faithful Hound", 5),
    ("Mage's Magnificent Mansion", 7),
    ("Mage's Private Sanctum", 5),
    ("Mage's Sword", 7),
    ("Magic Aura", 1),
    ("Magic Circle against Chaos", 3),
    ("Magic Circle against Evil", 3),
    ("Magic Circle against Good", 3),
    ("Magic Circle against Law", 3),
    ("Magic Jar", 5),
    ("Magic Missile", 1),
    ("Magic Mouth", 2),
    ("Magic Weapon", 1),
    ("Magic Weapon (Greater)", 3),
    ("Major Creation", 5),
    ("Major Image", 3),
    ("Make Whole", 2),
    ("Maze", 8),
    ("Mending", 0),
    ("Message", 0),
    ("Meteor Swarm", 9),
    ("Mind Blank", 8),
    ("Mind Fog", 5),
    ("Minor Creation", 4),
    ("Minor Image", 2),
    ("Mirage Arcana", 5),
    ("Mirror Image", 2),
    ("Misdirection", 2),
    ("Mislead", 6),
    ("Moment of Prescience", 8),
    ("Mount", 1),
    ("Move Earth", 6),
    ("Nightmare", 5),
    ("Nondetection", 3),
    ("Obscure Object", 2),
    ("Obscuring Mist", 1),
    ("Open/Close", 0),
    ("Overland Flight", 5),
    ("Owl's Wisdom", 2),
    ("Owl's Wisdom (Mass)", 6),
    ("Passwall", 5),
    ("Permanency", 5),
    ("Permanent Image", 6),
    ("Persistent Image", 5),
    ("Phantasmal Killer", 4),
    ("Phantom Steed", 3),
    ("Phantom Trap", 2),
    ("Phase Door", 7),
    ("Planar Binding", 6),
    ("Planar Binding (Greater)", 8),
    ("Planar Binding (Lesser)", 5),
    ("Plane Shift", 7),
    ("Plant Shape I", 5),
    ("Plant Shape II", 6),
    ("Plant Shape III", 7),
    ("Polar Ray", 8),
    ("Polymorph", 5),
    ("Polymorph (Greater)", 7),
    ("Polymorph Any Object", 8),
    ("Power Word Blind", 7),
    ("Power Word Kill", 9),
    ("Power Word Stun", 8),
    ("Prestidigitation", 0),
    ("Prismatic Sphere", 9),
    ("Prismatic Spray", 7),
    ("Prismatic Wall", 8),
    ("Programmed Image", 6),
    ("Project Image", 7),
    ("Protection from Arrows", 2),
    ("Protection from Chaos", 1),
    ("Protection from Energy", 3),
    ("Protection from Evil", 1),
    ("Protection from Good", 1),
    ("Protection from Law", 1),
    ("Protection from Spells", 8),
    ("Prying Eyes", 5),
    ("Prying Eyes (Greater)", 8),
    ("Pyrotechnics", 2),
    ("Rage", 3),
    ("Rainbow Pattern", 4),
    ("Ray of Enfeeblement", 1),
    ("Ray of Exhaustion", 3),
    ("Ray of Frost", 0),
    ("Read Magic", 0),
    ("Reduce Person", 1),
    ("Reduce Person (Mass)", 4),
    ("Refuge", 9),
    ("Remove Curse", 4),
    ("Repulsion", 6),
    ("Resilient Sphere", 4),
    ("Resist Energy", 2),
    ("Resistance", 0),
    ("Reverse Gravity", 7),
    ("Rope Trick", 2),
    ("Scare", 2),
    ("Scintillating Pattern", 8),
    ("Scorching Ray", 2),
    ("Screen", 8),
    ("Scrying", 4),
    ("Scrying (Greater)", 7),
    ("Secret Chest", 5),
    ("Secret Page", 3),
    ("Secure Shelter", 4),
    ("See Invisibility", 2),
    ("Seeming", 5),
    ("Sending", 5),
    ("Sepia Snake Sigil", 3),
    ("Sequester", 7),
    ("Shades", 9),
    ("Shadow Conjuration", 4),
    ("Shadow Conjuration (Greater)", 7),
    ("Shadow Evocation", 5),
    ("Shadow Evocation (Greater)", 8),
    ("Shadow Walk", 6),
    ("Shapechange", 9),
    ("Shatter", 2),
    ("Shield", 1),
    ("Shocking Grasp", 1),
    ("Shout", 4),
    ("Shout (Greater)", 8),
    ("Shrink Item", 3),
    ("Silent Image", 1),
    ("Simulacrum", 7),
    ("Sleep", 1),
    ("Sleet Storm", 3),
    ("Slow", 3),
    ("Solid Fog", 4),
    ("Soul Bind", 9),
    ("Spectral Hand", 2),
    ("Spell Turning", 7),
    ("Spider Climb", 2),
    ("Statue", 7),
    ("Stinking Cloud", 3),
    ("Stone Shape", 4),
    ("Stone to Flesh", 6),
    ("Stoneskin", 4),
    ("Suggestion", 3),
    ("Suggestion (Mass)", 6),
    ("Summon Monster I", 1),
    ("Summon Monster II", 2),
    ("Summon Monster III", 3),
    ("Summon Monster IV", 4),
    ("Summon Monster IX", 9),
    ("Summon Monster V", 5),
    ("Summon Monster VI", 6),
    ("Summon Monster VII", 7),
    ("Summon Monster VIII", 8),
    ("Summon Swarm", 2),
    ("Sunburst", 8),
    ("Symbol of Death", 8),
    ("Symbol of Fear", 6),
    ("Symbol of Insanity", 8),
    ("Symbol of Pain", 5),
    ("Symbol of Persuasion", 6),
    ("Symbol of Sleep", 5),
    ("Symbol of Stunning", 7),
    ("Symbol of Weakness", 7),
    ("Sympathy", 8),
    ("Telekinesis", 5),
    ("Telekinetic Sphere", 8),
    ("Telepathic Bond", 5),
    ("Teleport", 5),
    ("Teleport (Greater)", 7),
    ("Teleport Object", 7),
    ("Teleportation Circle", 9),
    ("Temporal Stasis", 8),
    ("Time Stop", 9),
    ("Tiny Hut", 3),
    ("Tongues", 3),
    ("Touch of Fatigue", 0),
    ("Touch of Idiocy", 2),
    ("Transformation", 6),
    ("Transmute Mud to Rock", 5),
    ("Transmute Rock to Mud", 5),
    ("Trap the Soul", 8),
    ("True Seeing", 6),
    ("True Strike", 1),
    ("Undeath to Death", 6),
    ("Unseen Servant", 1),
    ("Vampiric Touch", 3),
    ("Veil", 6),
    ("Ventriloquism", 1),
    ("Vision", 7),
    ("Wail of the Banshee", 9),
    ("Wall of Fire", 4),
    ("Wall of Force", 5),
    ("Wall of Ice", 4),
    ("Wall of Iron", 6),
    ("Wall of Stone", 5),
    ("Water Breathing", 3),
    ("Waves of Exhaustion", 7),
    ("Waves of Fatigue", 5),
    ("Web", 2),
    ("Weird", 9),
    ("Whispering Wind", 2),
    ("Wind Wall", 3),
    ("Wish", 9),
];

/// Looks up a spell's Sorcerer-specific spell level (0-9). `None` means the
/// named spell is not on the real CRB Sorcerer spell list at all -- either
/// it's not a real spell, or it's a real spell no Sorcerer can ever know.
pub fn sorcerer_spell_level(spell_key: &str) -> Option<u8> {
    SORCERER_SPELL_LIST
        .iter()
        .find(|(key, _)| *key == spell_key)
        .map(|(_, level)| *level)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules_core::rules_tables::crb::spell_list::SPELL_LIST;

    #[test]
    fn sorcerer_spell_list_has_the_real_corpus_verified_count() {
        assert_eq!(SORCERER_SPELL_LIST.len(), 394);
    }

    #[test]
    fn every_sorcerer_spell_level_is_within_the_real_sorcerer_ceiling() {
        for (key, level) in SORCERER_SPELL_LIST {
            assert!(
                (0..=9).contains(level),
                "{key} has out-of-range Sorcerer spell level {level}"
            );
        }
    }

    #[test]
    fn every_sorcerer_spell_key_is_a_real_spell_list_entry() {
        for (key, _) in SORCERER_SPELL_LIST {
            assert!(
                SPELL_LIST.iter().any(|entry| entry.key == *key),
                "{key} is not a real SPELL_LIST key"
            );
        }
    }

    #[test]
    fn sorcerer_spell_level_looks_up_known_values() {
        assert_eq!(sorcerer_spell_level("Acid Splash"), Some(0));
        assert_eq!(sorcerer_spell_level("Wish"), Some(9));
        assert_eq!(sorcerer_spell_level("Magic Missile"), Some(1));
        assert_eq!(sorcerer_spell_level("Nonexistent Spell"), None);
    }

    #[test]
    fn level_distribution_matches_the_real_corpus_parse() {
        let count_at =
            |level: u8| SORCERER_SPELL_LIST.iter().filter(|(_, l)| *l == level).count();
        assert_eq!(count_at(0), 20);
        assert_eq!(count_at(1), 42);
        assert_eq!(count_at(2), 51);
        assert_eq!(count_at(3), 46);
        assert_eq!(count_at(4), 41);
        assert_eq!(count_at(5), 47);
        assert_eq!(count_at(6), 46);
        assert_eq!(count_at(7), 40);
        assert_eq!(count_at(8), 37);
        assert_eq!(count_at(9), 24);
    }
}
