//! Generated from the real PCGen corpus file `cr_equip_arms_armor.lst`.
//! 310 records, one per distinct item after the SD-17 KEY:-based merge fix
//! (see `src/pcgen_import/lst_parser/equipment.rs`'s `open_record`).
//! Not hand-authored -- do not hand-edit; regenerate if the corpus changes.

use crate::rules_core::rules_tables::crb::equipment_tables::{EquipmentCategory, EquipmentTableEntry};

pub const ARMS_ARMOR_TABLE: &[EquipmentTableEntry] = &[
    EquipmentTableEntry { key: "Arrow (Base)", category: EquipmentCategory::ArmsArmor, name: "Arrow", cost_gp: Some(0.05_f64) },
    EquipmentTableEntry { key: "Bolt (Base)", category: EquipmentCategory::ArmsArmor, name: "Bolt", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Repeating Bolt (Base)", category: EquipmentCategory::ArmsArmor, name: "Repeating Bolt", cost_gp: Some(0.2_f64) },
    EquipmentTableEntry { key: "Sling Bullet (Base)", category: EquipmentCategory::ArmsArmor, name: "Bullet", cost_gp: Some(0.01_f64) },
    EquipmentTableEntry { key: "Blowgun Dart (Base)", category: EquipmentCategory::ArmsArmor, name: "Blowgun Dart", cost_gp: Some(0.05_f64) },
    EquipmentTableEntry { key: "Arrow", category: EquipmentCategory::ArmsArmor, name: "Arrow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Bolt (Crossbow)", category: EquipmentCategory::ArmsArmor, name: "Bolt (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Bolt (Crossbow/Repeating)", category: EquipmentCategory::ArmsArmor, name: "Repeating Bolt (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Bullet (Sling)", category: EquipmentCategory::ArmsArmor, name: "Sling Bullet (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dart (Blowgun)", category: EquipmentCategory::ArmsArmor, name: "Blowgun Dart (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Arrows (20)", category: EquipmentCategory::ArmsArmor, name: "Arrow (Base)", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Bolts (Crossbow/10)", category: EquipmentCategory::ArmsArmor, name: "Bolt (Base)", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Bolts (Crossbow/Repeating/5)", category: EquipmentCategory::ArmsArmor, name: "Repeating Bolt (Base)", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Bullets (Sling/10)", category: EquipmentCategory::ArmsArmor, name: "Sling Bullet (Base)", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Darts (Blowgun/10)", category: EquipmentCategory::ArmsArmor, name: "Blowgun Dart (Base)", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Bolt (Screaming)", category: EquipmentCategory::ArmsArmor, name: "Bolt (Base)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Arrow (Slaying)", category: EquipmentCategory::ArmsArmor, name: "Arrow (Base)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Arrow (Slaying/Greater)", category: EquipmentCategory::ArmsArmor, name: "Arrow (Base)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Arrow (Sleep)", category: EquipmentCategory::ArmsArmor, name: "Arrow (Base)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Padded Armor (Base)", category: EquipmentCategory::ArmsArmor, name: "Padded Armor", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Leather Armor (Base)", category: EquipmentCategory::ArmsArmor, name: "Leather Armor", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Studded Leather (Base)", category: EquipmentCategory::ArmsArmor, name: "Studded Leather Armor", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Chain Shirt (Base)", category: EquipmentCategory::ArmsArmor, name: "Chain Shirt", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Hide Armor (Base)", category: EquipmentCategory::ArmsArmor, name: "Hide Armor", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Scale Mail (Base)", category: EquipmentCategory::ArmsArmor, name: "Scale Mail", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Chainmail (Base)", category: EquipmentCategory::ArmsArmor, name: "Chainmail", cost_gp: Some(150_f64) },
    EquipmentTableEntry { key: "Breastplate (Base)", category: EquipmentCategory::ArmsArmor, name: "Breastplate", cost_gp: Some(200_f64) },
    EquipmentTableEntry { key: "Splint Mail (Base)", category: EquipmentCategory::ArmsArmor, name: "Splint Mail", cost_gp: Some(200_f64) },
    EquipmentTableEntry { key: "Banded Mail (Base)", category: EquipmentCategory::ArmsArmor, name: "Banded Mail", cost_gp: Some(250_f64) },
    EquipmentTableEntry { key: "Half-Plate (Base)", category: EquipmentCategory::ArmsArmor, name: "Half-Plate", cost_gp: Some(600_f64) },
    EquipmentTableEntry { key: "Full Plate (Base)", category: EquipmentCategory::ArmsArmor, name: "Full Plate", cost_gp: Some(1500_f64) },
    EquipmentTableEntry { key: "Padded", category: EquipmentCategory::ArmsArmor, name: "Padded Armor (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Leather", category: EquipmentCategory::ArmsArmor, name: "Leather Armor (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Studded Leather", category: EquipmentCategory::ArmsArmor, name: "Studded Leather (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Chain Shirt", category: EquipmentCategory::ArmsArmor, name: "Chain Shirt (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Hide", category: EquipmentCategory::ArmsArmor, name: "Hide Armor (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Scale Mail", category: EquipmentCategory::ArmsArmor, name: "Scale Mail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Chainmail", category: EquipmentCategory::ArmsArmor, name: "Chainmail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Breastplate", category: EquipmentCategory::ArmsArmor, name: "Breastplate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Splint Mail", category: EquipmentCategory::ArmsArmor, name: "Splint Mail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Banded Mail", category: EquipmentCategory::ArmsArmor, name: "Banded Mail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Half-Plate", category: EquipmentCategory::ArmsArmor, name: "Half-Plate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Full Plate", category: EquipmentCategory::ArmsArmor, name: "Full Plate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Adamantine Breastplate", category: EquipmentCategory::ArmsArmor, name: "Breastplate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Banded Mail of Luck", category: EquipmentCategory::ArmsArmor, name: "Banded Mail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Breastplate of Command", category: EquipmentCategory::ArmsArmor, name: "Breastplate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Celestial Armor", category: EquipmentCategory::ArmsArmor, name: "Chainmail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Demon Armor", category: EquipmentCategory::ArmsArmor, name: "Full Plate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dwarven Plate", category: EquipmentCategory::ArmsArmor, name: "Full Plate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dragonhide Plate", category: EquipmentCategory::ArmsArmor, name: "Full Plate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Elven Chain", category: EquipmentCategory::ArmsArmor, name: "Chainmail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Mithral Full Plate of Speed", category: EquipmentCategory::ArmsArmor, name: "Full Plate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Mithral Shirt", category: EquipmentCategory::ArmsArmor, name: "Chain Shirt (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Plate Armor of the Deep", category: EquipmentCategory::ArmsArmor, name: "Full Plate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Rhino Hide", category: EquipmentCategory::ArmsArmor, name: "Hide Armor (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Padded Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Padded Armor (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Leather Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Leather Armor (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Studded Leather Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Studded Leather (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Chain Shirt Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Chain Shirt (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Hide Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Hide Armor (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Scale Mail Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Scale Mail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Chainmail Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Chainmail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Breastplate Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Breastplate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Splint Mail Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Splint Mail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Banded Mail Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Banded Mail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Half-Plate Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Half-Plate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Full Plate Barding (Base)", category: EquipmentCategory::ArmsArmor, name: "Full Plate (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Padded)", category: EquipmentCategory::ArmsArmor, name: "Padded Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Leather)", category: EquipmentCategory::ArmsArmor, name: "Leather Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Studded Leather)", category: EquipmentCategory::ArmsArmor, name: "Studded Leather Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Chain Shirt)", category: EquipmentCategory::ArmsArmor, name: "Chain Shirt Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Hide)", category: EquipmentCategory::ArmsArmor, name: "Hide Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Scale Mail)", category: EquipmentCategory::ArmsArmor, name: "Scale Mail Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Chainmail)", category: EquipmentCategory::ArmsArmor, name: "Chainmail Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Breastplate)", category: EquipmentCategory::ArmsArmor, name: "Breastplate Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Splint Mail)", category: EquipmentCategory::ArmsArmor, name: "Splint Mail Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Banded Mail)", category: EquipmentCategory::ArmsArmor, name: "Banded Mail Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Half-Plate)", category: EquipmentCategory::ArmsArmor, name: "Half-Plate Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Barding (Full Plate)", category: EquipmentCategory::ArmsArmor, name: "Full Plate Barding (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Buckler (Base)", category: EquipmentCategory::ArmsArmor, name: "Buckler", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Light Wooden Shield (Base)", category: EquipmentCategory::ArmsArmor, name: "Light Wooden Shield", cost_gp: Some(3_f64) },
    EquipmentTableEntry { key: "Light Steel Shield (Base)", category: EquipmentCategory::ArmsArmor, name: "Light Steel Shield", cost_gp: Some(9_f64) },
    EquipmentTableEntry { key: "Heavy Wooden Shield (Base)", category: EquipmentCategory::ArmsArmor, name: "Heavy Wooden Shield", cost_gp: Some(7_f64) },
    EquipmentTableEntry { key: "Heavy Steel Shield (Base)", category: EquipmentCategory::ArmsArmor, name: "Heavy Steel Shield", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Tower Shield (Base)", category: EquipmentCategory::ArmsArmor, name: "Tower Shield", cost_gp: Some(30_f64) },
    EquipmentTableEntry { key: "Buckler", category: EquipmentCategory::ArmsArmor, name: "Buckler (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shield (Light/Wooden)", category: EquipmentCategory::ArmsArmor, name: "Light Wooden Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shield (Light/Steel)", category: EquipmentCategory::ArmsArmor, name: "Light Steel Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shield (Heavy/Wooden)", category: EquipmentCategory::ArmsArmor, name: "Heavy Wooden Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shield (Heavy/Steel)", category: EquipmentCategory::ArmsArmor, name: "Heavy Steel Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shield (Tower)", category: EquipmentCategory::ArmsArmor, name: "Tower Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Absorbing Shield", category: EquipmentCategory::ArmsArmor, name: "Heavy Steel Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Caster's Shield", category: EquipmentCategory::ArmsArmor, name: "Light Wooden Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Darkwood Buckler", category: EquipmentCategory::ArmsArmor, name: "Light Wooden Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Darkwood Shield", category: EquipmentCategory::ArmsArmor, name: "Heavy Wooden Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Lion's Shield", category: EquipmentCategory::ArmsArmor, name: "Heavy Steel Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Mithral Heavy Shield", category: EquipmentCategory::ArmsArmor, name: "Heavy Wooden Shield (Base)", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Spined Shield", category: EquipmentCategory::ArmsArmor, name: "Heavy Steel Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Winged Shield", category: EquipmentCategory::ArmsArmor, name: "Heavy Wooden Shield (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Demon Armor Claw Attack", category: EquipmentCategory::ArmsArmor, name: "Demon Armor Claw Attack", cost_gp: Some(-2300_f64) },
    EquipmentTableEntry { key: "Armor Spikes", category: EquipmentCategory::ArmsArmor, name: "Armor Spikes", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Gauntlet (Base)", category: EquipmentCategory::ArmsArmor, name: "Gauntlet", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Dagger (Base)", category: EquipmentCategory::ArmsArmor, name: "Dagger", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Punching Dagger (Base)", category: EquipmentCategory::ArmsArmor, name: "Punching Dagger", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Spiked Gauntlet (Base)", category: EquipmentCategory::ArmsArmor, name: "Spiked Gauntlet", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Light Mace (Base)", category: EquipmentCategory::ArmsArmor, name: "Light Mace", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Sickle (Base)", category: EquipmentCategory::ArmsArmor, name: "Sickle", cost_gp: Some(6_f64) },
    EquipmentTableEntry { key: "Club (Base)", category: EquipmentCategory::ArmsArmor, name: "Club", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Heavy Mace (Base)", category: EquipmentCategory::ArmsArmor, name: "Heavy Mace", cost_gp: Some(12_f64) },
    EquipmentTableEntry { key: "Morningstar (Base)", category: EquipmentCategory::ArmsArmor, name: "Morningstar", cost_gp: Some(8_f64) },
    EquipmentTableEntry { key: "Shortspear (Base)", category: EquipmentCategory::ArmsArmor, name: "Shortspear", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Longspear (Base)", category: EquipmentCategory::ArmsArmor, name: "Longspear", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Quarterstaff (Base)", category: EquipmentCategory::ArmsArmor, name: "Quarterstaff", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Spear (Base)", category: EquipmentCategory::ArmsArmor, name: "Spear", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Throwing Axe (Base)", category: EquipmentCategory::ArmsArmor, name: "Throwing Axe", cost_gp: Some(8_f64) },
    EquipmentTableEntry { key: "Light Hammer (Base)", category: EquipmentCategory::ArmsArmor, name: "Light Hammer", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Handaxe (Base)", category: EquipmentCategory::ArmsArmor, name: "Handaxe", cost_gp: Some(6_f64) },
    EquipmentTableEntry { key: "Kukri (Base)", category: EquipmentCategory::ArmsArmor, name: "Kukri", cost_gp: Some(8_f64) },
    EquipmentTableEntry { key: "Light Pick (Base)", category: EquipmentCategory::ArmsArmor, name: "Light Pick", cost_gp: Some(4_f64) },
    EquipmentTableEntry { key: "Sap (Base)", category: EquipmentCategory::ArmsArmor, name: "Sap", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Spiked Armor (Base)", category: EquipmentCategory::ArmsArmor, name: "Spiked Armor", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Starknife (Base)", category: EquipmentCategory::ArmsArmor, name: "Starknife", cost_gp: Some(24_f64) },
    EquipmentTableEntry { key: "Short Sword (Base)", category: EquipmentCategory::ArmsArmor, name: "Short Sword", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Battleaxe (Base)", category: EquipmentCategory::ArmsArmor, name: "Battleaxe", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Light Flail (Base)", category: EquipmentCategory::ArmsArmor, name: "Light Flail", cost_gp: Some(8_f64) },
    EquipmentTableEntry { key: "Longsword (Base)", category: EquipmentCategory::ArmsArmor, name: "Longsword", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Heavy Pick (Base)", category: EquipmentCategory::ArmsArmor, name: "Heavy Pick", cost_gp: Some(8_f64) },
    EquipmentTableEntry { key: "Rapier (Base)", category: EquipmentCategory::ArmsArmor, name: "Rapier", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Scimitar (Base)", category: EquipmentCategory::ArmsArmor, name: "Scimitar", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Trident (Base)", category: EquipmentCategory::ArmsArmor, name: "Trident", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Warhammer (Base)", category: EquipmentCategory::ArmsArmor, name: "Warhammer", cost_gp: Some(12_f64) },
    EquipmentTableEntry { key: "Falchion (Base)", category: EquipmentCategory::ArmsArmor, name: "Falchion", cost_gp: Some(75_f64) },
    EquipmentTableEntry { key: "Glaive (Base)", category: EquipmentCategory::ArmsArmor, name: "Glaive", cost_gp: Some(8_f64) },
    EquipmentTableEntry { key: "Greataxe (Base)", category: EquipmentCategory::ArmsArmor, name: "Greataxe", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Greatclub (Base)", category: EquipmentCategory::ArmsArmor, name: "Greatclub", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Heavy Flail (Base)", category: EquipmentCategory::ArmsArmor, name: "Heavy Flail", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Greatsword (Base)", category: EquipmentCategory::ArmsArmor, name: "Greatsword", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Guisarme (Base)", category: EquipmentCategory::ArmsArmor, name: "Guisarme", cost_gp: Some(9_f64) },
    EquipmentTableEntry { key: "Halberd (Base)", category: EquipmentCategory::ArmsArmor, name: "Halberd", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Lance (Base)", category: EquipmentCategory::ArmsArmor, name: "Lance", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Ranseur (Base)", category: EquipmentCategory::ArmsArmor, name: "Ranseur", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Scythe (Base)", category: EquipmentCategory::ArmsArmor, name: "Scythe", cost_gp: Some(18_f64) },
    EquipmentTableEntry { key: "Kama (Base)", category: EquipmentCategory::ArmsArmor, name: "Kama", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Nunchaku (Base)", category: EquipmentCategory::ArmsArmor, name: "Nunchaku", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Sai (Base)", category: EquipmentCategory::ArmsArmor, name: "Sai", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Siangham (Base)", category: EquipmentCategory::ArmsArmor, name: "Siangham", cost_gp: Some(3_f64) },
    EquipmentTableEntry { key: "Bastard Sword (Base)", category: EquipmentCategory::ArmsArmor, name: "Bastard Sword", cost_gp: Some(35_f64) },
    EquipmentTableEntry { key: "Dwarven Waraxe (Base)", category: EquipmentCategory::ArmsArmor, name: "Dwarven Waraxe", cost_gp: Some(30_f64) },
    EquipmentTableEntry { key: "Whip (Base)", category: EquipmentCategory::ArmsArmor, name: "Whip", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Orc Double Axe (Base)", category: EquipmentCategory::ArmsArmor, name: "Orc Double Axe", cost_gp: Some(60_f64) },
    EquipmentTableEntry { key: "Spiked Chain (Base)", category: EquipmentCategory::ArmsArmor, name: "Spiked Chain", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Elven Curve Blade (Base)", category: EquipmentCategory::ArmsArmor, name: "Elven Curve Blade", cost_gp: Some(80_f64) },
    EquipmentTableEntry { key: "Dire Flail (Base)", category: EquipmentCategory::ArmsArmor, name: "Dire Flail", cost_gp: Some(90_f64) },
    EquipmentTableEntry { key: "Gnome Hooked Hammer (Base)", category: EquipmentCategory::ArmsArmor, name: "Gnome Hooked Hammer", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Two-Bladed Sword (Base)", category: EquipmentCategory::ArmsArmor, name: "Two-Bladed Sword", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Dwarven Urgrosh (Base)", category: EquipmentCategory::ArmsArmor, name: "Dwarven Urgrosh", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Gauntlet (Part of Armor Suit)", category: EquipmentCategory::ArmsArmor, name: "Gauntlet (Base)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Gauntlet", category: EquipmentCategory::ArmsArmor, name: "Gauntlet (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dagger", category: EquipmentCategory::ArmsArmor, name: "Dagger (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dagger (Punching)", category: EquipmentCategory::ArmsArmor, name: "Punching Dagger (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Gauntlet (Spiked)", category: EquipmentCategory::ArmsArmor, name: "Spiked Gauntlet (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Mace (Light)", category: EquipmentCategory::ArmsArmor, name: "Light Mace (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sickle", category: EquipmentCategory::ArmsArmor, name: "Sickle (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Club", category: EquipmentCategory::ArmsArmor, name: "Club (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Mace (Heavy)", category: EquipmentCategory::ArmsArmor, name: "Heavy Mace (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Morningstar", category: EquipmentCategory::ArmsArmor, name: "Morningstar (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shortspear", category: EquipmentCategory::ArmsArmor, name: "Shortspear (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Longspear", category: EquipmentCategory::ArmsArmor, name: "Longspear (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Quarterstaff", category: EquipmentCategory::ArmsArmor, name: "Quarterstaff (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Spear", category: EquipmentCategory::ArmsArmor, name: "Spear (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Axe (Throwing)", category: EquipmentCategory::ArmsArmor, name: "Throwing Axe (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Hammer (Light)", category: EquipmentCategory::ArmsArmor, name: "Light Hammer (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Handaxe", category: EquipmentCategory::ArmsArmor, name: "Handaxe (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Kukri", category: EquipmentCategory::ArmsArmor, name: "Kukri (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Pick (Light)", category: EquipmentCategory::ArmsArmor, name: "Light Pick (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sap", category: EquipmentCategory::ArmsArmor, name: "Sap (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Spiked Armor", category: EquipmentCategory::ArmsArmor, name: "Spiked Armor (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Starknife", category: EquipmentCategory::ArmsArmor, name: "Starknife (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sword (Short)", category: EquipmentCategory::ArmsArmor, name: "Short Sword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Battleaxe", category: EquipmentCategory::ArmsArmor, name: "Battleaxe (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Flail", category: EquipmentCategory::ArmsArmor, name: "Light Flail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Longsword", category: EquipmentCategory::ArmsArmor, name: "Longsword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Pick (Heavy)", category: EquipmentCategory::ArmsArmor, name: "Heavy Pick (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Rapier", category: EquipmentCategory::ArmsArmor, name: "Rapier (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Scimitar", category: EquipmentCategory::ArmsArmor, name: "Scimitar (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Trident", category: EquipmentCategory::ArmsArmor, name: "Trident (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Warhammer", category: EquipmentCategory::ArmsArmor, name: "Warhammer (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Falchion", category: EquipmentCategory::ArmsArmor, name: "Falchion (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Glaive", category: EquipmentCategory::ArmsArmor, name: "Glaive (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Greataxe", category: EquipmentCategory::ArmsArmor, name: "Greataxe (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Greatclub", category: EquipmentCategory::ArmsArmor, name: "Greatclub (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Flail (Heavy)", category: EquipmentCategory::ArmsArmor, name: "Heavy Flail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Greatsword", category: EquipmentCategory::ArmsArmor, name: "Greatsword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Guisarme", category: EquipmentCategory::ArmsArmor, name: "Guisarme (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Halberd", category: EquipmentCategory::ArmsArmor, name: "Halberd (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Lance", category: EquipmentCategory::ArmsArmor, name: "Lance (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Ranseur", category: EquipmentCategory::ArmsArmor, name: "Ranseur (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Scythe", category: EquipmentCategory::ArmsArmor, name: "Scythe (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Kama", category: EquipmentCategory::ArmsArmor, name: "Kama (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Nunchaku", category: EquipmentCategory::ArmsArmor, name: "Nunchaku (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Nunchaku (Metal)", category: EquipmentCategory::ArmsArmor, name: "Nunchaku (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sai", category: EquipmentCategory::ArmsArmor, name: "Sai (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Siangham", category: EquipmentCategory::ArmsArmor, name: "Siangham (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sword (Bastard)", category: EquipmentCategory::ArmsArmor, name: "Bastard Sword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Waraxe (Dwarven)", category: EquipmentCategory::ArmsArmor, name: "Dwarven Waraxe (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Whip", category: EquipmentCategory::ArmsArmor, name: "Whip (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Axe (Orc Double)", category: EquipmentCategory::ArmsArmor, name: "Orc Double Axe (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Chain (Spiked)", category: EquipmentCategory::ArmsArmor, name: "Spiked Chain (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Curve Blade (Elven)", category: EquipmentCategory::ArmsArmor, name: "Elven Curve Blade (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Flail (Dire)", category: EquipmentCategory::ArmsArmor, name: "Dire Flail (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Hammer (Gnome Hooked)", category: EquipmentCategory::ArmsArmor, name: "Gnome Hooked Hammer (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sword (Two-Bladed)", category: EquipmentCategory::ArmsArmor, name: "Two-Bladed Sword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Urgrosh (Dwarven)", category: EquipmentCategory::ArmsArmor, name: "Dwarven Urgrosh (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Battleaxe (Adamantine)", category: EquipmentCategory::ArmsArmor, name: "Battleaxe (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dagger (Adamantine)", category: EquipmentCategory::ArmsArmor, name: "Dagger (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dagger (Assassin's)", category: EquipmentCategory::ArmsArmor, name: "Dagger (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dagger of Venom", category: EquipmentCategory::ArmsArmor, name: "Dagger (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dwarven Thrower", category: EquipmentCategory::ArmsArmor, name: "Warhammer (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Flame Tongue", category: EquipmentCategory::ArmsArmor, name: "Longsword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Frost Brand", category: EquipmentCategory::ArmsArmor, name: "Greatsword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Holy Avenger", category: EquipmentCategory::ArmsArmor, name: "Longsword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Life-Drinker", category: EquipmentCategory::ArmsArmor, name: "Greataxe (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Longsword (Cold Iron/Masterwork)", category: EquipmentCategory::ArmsArmor, name: "Longsword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Luck Blade (0 wishes)", category: EquipmentCategory::ArmsArmor, name: "Short Sword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Luck Blade (1 wish)", category: EquipmentCategory::ArmsArmor, name: "Short Sword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Luck Blade (2 wishes)", category: EquipmentCategory::ArmsArmor, name: "Short Sword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Luck Blade (3 wishes)", category: EquipmentCategory::ArmsArmor, name: "Short Sword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Mace of Smiting", category: EquipmentCategory::ArmsArmor, name: "Heavy Mace (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Mace of Terror", category: EquipmentCategory::ArmsArmor, name: "Heavy Mace (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Nine Lives Stealer", category: EquipmentCategory::ArmsArmor, name: "Longsword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Rapier of Puncturing", category: EquipmentCategory::ArmsArmor, name: "Rapier (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shatterspike", category: EquipmentCategory::ArmsArmor, name: "Longsword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shifter's Sorrow", category: EquipmentCategory::ArmsArmor, name: "Two-Bladed Sword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dagger (Silver/Masterwork)", category: EquipmentCategory::ArmsArmor, name: "Dagger (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sun Blade (Bastard)", category: EquipmentCategory::ArmsArmor, name: "Bastard Sword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sun Blade (Short)", category: EquipmentCategory::ArmsArmor, name: "Sun Blade (Bastard)", cost_gp: None },
    EquipmentTableEntry { key: "Sword of Life Stealing", category: EquipmentCategory::ArmsArmor, name: "Longsword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sword of the Planes", category: EquipmentCategory::ArmsArmor, name: "Longsword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sword of Subtlety", category: EquipmentCategory::ArmsArmor, name: "Short Sword (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sylvan Scimitar", category: EquipmentCategory::ArmsArmor, name: "Scimitar (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Trident of Fish Command", category: EquipmentCategory::ArmsArmor, name: "Trident (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Trident of Warning", category: EquipmentCategory::ArmsArmor, name: "Trident (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Mattock of the Titans", category: EquipmentCategory::ArmsArmor, name: "Mattock of the Titans", cost_gp: Some(23348_f64) },
    EquipmentTableEntry { key: "Maul of the Titans", category: EquipmentCategory::ArmsArmor, name: "Maul of the Titans", cost_gp: Some(25305_f64) },
    EquipmentTableEntry { key: "Axe of the Dwarvish Lords", category: EquipmentCategory::ArmsArmor, name: "Dwarven Waraxe (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Flurry of Blows", category: EquipmentCategory::ArmsArmor, name: "Flurry of Blows", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Shieldbash (Light)", category: EquipmentCategory::ArmsArmor, name: "Shieldbash (Light Shield)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Shieldbash (Heavy)", category: EquipmentCategory::ArmsArmor, name: "Shieldbash (Heavy Shield)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Touch Attack (Ray)", category: EquipmentCategory::ArmsArmor, name: "Touch Attack (Ray Spell)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Unarmed Strike", category: EquipmentCategory::ArmsArmor, name: "Unarmed Strike", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Blowgun (Base)", category: EquipmentCategory::ArmsArmor, name: "Blowgun", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Heavy Crossbow (Base)", category: EquipmentCategory::ArmsArmor, name: "Heavy Crossbow", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Light Crossbow (Base)", category: EquipmentCategory::ArmsArmor, name: "Light Crossbow", cost_gp: Some(35_f64) },
    EquipmentTableEntry { key: "Dart (Base)", category: EquipmentCategory::ArmsArmor, name: "Dart", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Javelin (Base)", category: EquipmentCategory::ArmsArmor, name: "Javelin", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Sling (Base)", category: EquipmentCategory::ArmsArmor, name: "Sling", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Longbow (Base)", category: EquipmentCategory::ArmsArmor, name: "Longbow", cost_gp: Some(75_f64) },
    EquipmentTableEntry { key: "Composite Longbow (Base)", category: EquipmentCategory::ArmsArmor, name: "Composite Longbow", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Shortbow (Base)", category: EquipmentCategory::ArmsArmor, name: "Shortbow", cost_gp: Some(30_f64) },
    EquipmentTableEntry { key: "Composite Shortbow (Base)", category: EquipmentCategory::ArmsArmor, name: "Composite Shortbow", cost_gp: Some(75_f64) },
    EquipmentTableEntry { key: "Bolas (Base)", category: EquipmentCategory::ArmsArmor, name: "Bolas", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Hand Crossbow (Base)", category: EquipmentCategory::ArmsArmor, name: "Hand Crossbow", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Repeating Heavy Crossbow (Base)", category: EquipmentCategory::ArmsArmor, name: "Repeating Heavy Crossbow", cost_gp: Some(400_f64) },
    EquipmentTableEntry { key: "Repeating Light Crossbow (Base)", category: EquipmentCategory::ArmsArmor, name: "Repeating Light Crossbow", cost_gp: Some(250_f64) },
    EquipmentTableEntry { key: "Net (Base)", category: EquipmentCategory::ArmsArmor, name: "Net", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Shuriken (Base)", category: EquipmentCategory::ArmsArmor, name: "Shuriken", cost_gp: Some(0.2_f64) },
    EquipmentTableEntry { key: "Halfling Sling Staff (Base)", category: EquipmentCategory::ArmsArmor, name: "Halfling Sling Staff", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Blowgun", category: EquipmentCategory::ArmsArmor, name: "Blowgun (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Crossbow (Heavy)", category: EquipmentCategory::ArmsArmor, name: "Heavy Crossbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Crossbow (Light)", category: EquipmentCategory::ArmsArmor, name: "Light Crossbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Dart", category: EquipmentCategory::ArmsArmor, name: "Dart (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Javelin", category: EquipmentCategory::ArmsArmor, name: "Javelin (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sling", category: EquipmentCategory::ArmsArmor, name: "Sling (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Longbow", category: EquipmentCategory::ArmsArmor, name: "Longbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Longbow (Composite)", category: EquipmentCategory::ArmsArmor, name: "Composite Longbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Longbow (Composite +0)", category: EquipmentCategory::ArmsArmor, name: "Composite Longbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shortbow", category: EquipmentCategory::ArmsArmor, name: "Shortbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shortbow (Composite)", category: EquipmentCategory::ArmsArmor, name: "Composite Shortbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shortbow (Composite +0)", category: EquipmentCategory::ArmsArmor, name: "Composite Shortbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Bolas", category: EquipmentCategory::ArmsArmor, name: "Bolas (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Crossbow (Hand)", category: EquipmentCategory::ArmsArmor, name: "Hand Crossbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Crossbow (Repeating Heavy)", category: EquipmentCategory::ArmsArmor, name: "Repeating Heavy Crossbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Crossbow (Repeating Light)", category: EquipmentCategory::ArmsArmor, name: "Repeating Light Crossbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Net", category: EquipmentCategory::ArmsArmor, name: "Net (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Shuriken", category: EquipmentCategory::ArmsArmor, name: "Shuriken (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Sling Staff (Halfling)", category: EquipmentCategory::ArmsArmor, name: "Halfling Sling Staff (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Javelin of Lightning", category: EquipmentCategory::ArmsArmor, name: "Javelin (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Oathbow", category: EquipmentCategory::ArmsArmor, name: "Composite Longbow (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Improvised Weapon (1d2)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (1d2)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (1d3)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (1d3)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (1d4)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (1d4)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (1d6)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (1d6)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (1d8)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (1d8)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (1d10)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (1d10)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (1d12)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (1d12)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (2d4)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (2d4)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (2d6)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (2d6)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (2d8)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (2d8)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (2d10)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (2d10)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (1d2)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (1d2)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (1d3)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (1d3)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (1d4)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (1d4)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (1d6)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (1d6)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (1d8)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (1d8)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (1d10)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (1d10)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (1d12)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (1d12)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (2d4)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (2d4)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (2d6)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (2d6)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (2d8)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (2d8)", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Improvised Weapon (Thrown) (2d10)", category: EquipmentCategory::ArmsArmor, name: "Improvised Weapon (Thrown) (2d10)", cost_gp: Some(0_f64) },
];
