//! Generated from the real PCGen corpus file `cr_equip_general.lst`.
//! 453 records, one per distinct item after the SD-17 KEY:-based merge fix
//! (see `src/pcgen_import/lst_parser/equipment.rs`'s `open_record`).
//! Not hand-authored -- do not hand-edit; regenerate if the corpus changes.

use crate::rules_core::rules_tables::crb::equipment_tables::{EquipmentCategory, EquipmentTableEntry};

pub const GENERAL_TABLE: &[EquipmentTableEntry] = &[
    EquipmentTableEntry { key: "Belt", category: EquipmentCategory::General, name: "Belt", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Girdle", category: EquipmentCategory::General, name: "Girdle", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Robe", category: EquipmentCategory::General, name: "Robe", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Vestment", category: EquipmentCategory::General, name: "Vestment", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Mantle", category: EquipmentCategory::General, name: "Mantle", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Shirt", category: EquipmentCategory::General, name: "Shirt", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Vest", category: EquipmentCategory::General, name: "Vest", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Eye Lenses", category: EquipmentCategory::General, name: "Eye Lenses", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Goggles", category: EquipmentCategory::General, name: "Goggles", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Boots", category: EquipmentCategory::General, name: "Boots", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Shoes", category: EquipmentCategory::General, name: "Shoes", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Slippers", category: EquipmentCategory::General, name: "Slippers", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Gauntlets", category: EquipmentCategory::General, name: "Gauntlets", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Gloves", category: EquipmentCategory::General, name: "Gloves", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Circlet", category: EquipmentCategory::General, name: "Circlet", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Crown", category: EquipmentCategory::General, name: "Crown", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Hat", category: EquipmentCategory::General, name: "Hat", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Helmet", category: EquipmentCategory::General, name: "Helmet", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Mask", category: EquipmentCategory::General, name: "Mask", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Headband", category: EquipmentCategory::General, name: "Headband", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Phylactery", category: EquipmentCategory::General, name: "Phylactery", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Amulet", category: EquipmentCategory::General, name: "Amulet", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Brooch", category: EquipmentCategory::General, name: "Brooch", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Medallion", category: EquipmentCategory::General, name: "Medallion", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Necklace", category: EquipmentCategory::General, name: "Necklace", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Periapt", category: EquipmentCategory::General, name: "Periapt", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Scarab", category: EquipmentCategory::General, name: "Scarab", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Ring", category: EquipmentCategory::General, name: "Ring", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Cape", category: EquipmentCategory::General, name: "Cape", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Cloak", category: EquipmentCategory::General, name: "Cloak", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Bracelets", category: EquipmentCategory::General, name: "Bracelets", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Bracers", category: EquipmentCategory::General, name: "Bracers", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Potion", category: EquipmentCategory::General, name: "Potion", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Rod", category: EquipmentCategory::General, name: "Rod", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Scroll", category: EquipmentCategory::General, name: "Scroll", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Staff", category: EquipmentCategory::General, name: "Staff", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Wand", category: EquipmentCategory::General, name: "Wand", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Spell Component", category: EquipmentCategory::General, name: "Spell Component", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Spell Focus", category: EquipmentCategory::General, name: "Spell Focus", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Art", category: EquipmentCategory::General, name: "Art", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Gem", category: EquipmentCategory::General, name: "Gem", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Tattoo Head", category: EquipmentCategory::General, name: "Head Tattoo", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Tattoo Shoulders", category: EquipmentCategory::General, name: "Shoulder Tattoo", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Tattoo Neck", category: EquipmentCategory::General, name: "Neck Tattoo", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Tattoo Chest", category: EquipmentCategory::General, name: "Chest Tattoo", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Tattoo Body", category: EquipmentCategory::General, name: "Body Tattoo", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Tattoo Belt", category: EquipmentCategory::General, name: "Belt Tattoo", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Tattoo Wrist", category: EquipmentCategory::General, name: "Wrist Tattoo", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Tattoo Hands", category: EquipmentCategory::General, name: "Hand Tattoo", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Tattoo Ring", category: EquipmentCategory::General, name: "Ring Tattoo", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Tattoo Feet", category: EquipmentCategory::General, name: "Feet Tattoo", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Wheat (per lb)", category: EquipmentCategory::General, name: "Pound of Wheat", cost_gp: Some(0.01_f64) },
    EquipmentTableEntry { key: "Flour (per lb)", category: EquipmentCategory::General, name: "Pound of Flour", cost_gp: Some(0.02_f64) },
    EquipmentTableEntry { key: "Chicken", category: EquipmentCategory::General, name: "Chicken", cost_gp: Some(0.02_f64) },
    EquipmentTableEntry { key: "Iron (per lb)", category: EquipmentCategory::General, name: "Pound of Iron", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Tobacco (per lb)", category: EquipmentCategory::General, name: "Pound of Tobacco", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Copper (per lb)", category: EquipmentCategory::General, name: "Pound of Copper", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Cinnamon (per lb)", category: EquipmentCategory::General, name: "Pound of Cinnamon", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Goat", category: EquipmentCategory::General, name: "Goat", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Ginger (per lb)", category: EquipmentCategory::General, name: "Pound of Ginger", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Pepper (per lb)", category: EquipmentCategory::General, name: "Pound of Pepper", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Sheep", category: EquipmentCategory::General, name: "Sheep", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Pig", category: EquipmentCategory::General, name: "Pig", cost_gp: Some(3_f64) },
    EquipmentTableEntry { key: "Linen (sq yd)", category: EquipmentCategory::General, name: "Square Yard of Linen", cost_gp: Some(4_f64) },
    EquipmentTableEntry { key: "Salt (per lb)", category: EquipmentCategory::General, name: "Pound of Salt", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Silver (per lb)", category: EquipmentCategory::General, name: "Pound of Silver", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Silk (sq yd)", category: EquipmentCategory::General, name: "Square Yard of Silk", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Cow", category: EquipmentCategory::General, name: "Cow", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Saffron (per lb)", category: EquipmentCategory::General, name: "Pound of Saffron", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Cloves (per lb)", category: EquipmentCategory::General, name: "Pound of Cloves", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Ox", category: EquipmentCategory::General, name: "Ox", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Gold (per lb)", category: EquipmentCategory::General, name: "Pound of Gold", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Platinum (per lb)", category: EquipmentCategory::General, name: "Pound of Platinum", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Backpack", category: EquipmentCategory::General, name: "Backpack", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Barrel", category: EquipmentCategory::General, name: "Barrel", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Basket", category: EquipmentCategory::General, name: "Basket", cost_gp: Some(0.4_f64) },
    EquipmentTableEntry { key: "Bedroll", category: EquipmentCategory::General, name: "Bedroll", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Bell", category: EquipmentCategory::General, name: "Bell", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Blanket (Winter)", category: EquipmentCategory::General, name: "Blanket, Winter", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Block and Tackle", category: EquipmentCategory::General, name: "Block and Tackle", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Bottle (Glass)", category: EquipmentCategory::General, name: "Bottle", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Bucket", category: EquipmentCategory::General, name: "Bucket", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Caltrops", category: EquipmentCategory::General, name: "Caltrops", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Candle", category: EquipmentCategory::General, name: "Candle", cost_gp: Some(0.01_f64) },
    EquipmentTableEntry { key: "Canvas (sq yd)", category: EquipmentCategory::General, name: "Canvas (sq. yd.)", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Scroll Case", category: EquipmentCategory::General, name: "Case, Scroll", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Map Case", category: EquipmentCategory::General, name: "Scroll Case", cost_gp: None },
    EquipmentTableEntry { key: "Chain (10 ft)", category: EquipmentCategory::General, name: "Chain (10 ft.)", cost_gp: Some(30_f64) },
    EquipmentTableEntry { key: "Chalk (1 Piece)", category: EquipmentCategory::General, name: "Chalk", cost_gp: Some(0.01_f64) },
    EquipmentTableEntry { key: "Chest", category: EquipmentCategory::General, name: "Chest", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Crowbar", category: EquipmentCategory::General, name: "Crowbar", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Firewood (Per Day)", category: EquipmentCategory::General, name: "Firewood, Per Day", cost_gp: Some(0.01_f64) },
    EquipmentTableEntry { key: "Fishhook", category: EquipmentCategory::General, name: "Fishhook", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Fishing Net (25 sq ft)", category: EquipmentCategory::General, name: "Fishing Net", cost_gp: Some(4_f64) },
    EquipmentTableEntry { key: "Flask", category: EquipmentCategory::General, name: "Flask", cost_gp: Some(0.03_f64) },
    EquipmentTableEntry { key: "Flint and Steel", category: EquipmentCategory::General, name: "Flint and Steel", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Grappling Hook", category: EquipmentCategory::General, name: "Grappling Hook", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Hammer", category: EquipmentCategory::General, name: "Hammer", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Hourglass", category: EquipmentCategory::General, name: "Hourglass", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Ink (1 oz Vial)", category: EquipmentCategory::General, name: "Ink, 1 oz. Vial", cost_gp: Some(8_f64) },
    EquipmentTableEntry { key: "Ink (Color/1 oz Vial)", category: EquipmentCategory::General, name: "Ink, Colored, 1 oz. Vial", cost_gp: Some(16_f64) },
    EquipmentTableEntry { key: "Inkpen", category: EquipmentCategory::General, name: "Inkpen", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Jug (Clay)", category: EquipmentCategory::General, name: "Jug, Clay", cost_gp: Some(0.03_f64) },
    EquipmentTableEntry { key: "Ladder (10 ft)", category: EquipmentCategory::General, name: "Ladder (10 ft.)", cost_gp: Some(0.2_f64) },
    EquipmentTableEntry { key: "Lamp (Common)", category: EquipmentCategory::General, name: "Lamp", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Lantern (Bullseye)", category: EquipmentCategory::General, name: "Lantern, Bullseye", cost_gp: Some(12_f64) },
    EquipmentTableEntry { key: "Lantern (Hooded)", category: EquipmentCategory::General, name: "Lantern, Hooded", cost_gp: Some(7_f64) },
    EquipmentTableEntry { key: "Lock (Simple)", category: EquipmentCategory::General, name: "Lock, Simple", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Lock (Average)", category: EquipmentCategory::General, name: "Lock, Average", cost_gp: Some(40_f64) },
    EquipmentTableEntry { key: "Lock (Good)", category: EquipmentCategory::General, name: "Lock, Good", cost_gp: Some(80_f64) },
    EquipmentTableEntry { key: "Lock (Superior)", category: EquipmentCategory::General, name: "Lock, Superior", cost_gp: Some(150_f64) },
    EquipmentTableEntry { key: "Manacles (Small)", category: EquipmentCategory::General, name: "Manacles, Small", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Manacles (Medium)", category: EquipmentCategory::General, name: "Manacles, Medium", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Manacles (Large)", category: EquipmentCategory::General, name: "Manacles, Large", cost_gp: Some(150_f64) },
    EquipmentTableEntry { key: "Manacles (Huge)", category: EquipmentCategory::General, name: "Manacles, Huge", cost_gp: Some(1500_f64) },
    EquipmentTableEntry { key: "Manacles (Masterwork/Small)", category: EquipmentCategory::General, name: "Manacles, Small Masterwork", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Manacles (Masterwork/Medium)", category: EquipmentCategory::General, name: "Manacles, Medium Masterwork", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Manacles (Masterwork/Large)", category: EquipmentCategory::General, name: "Manacles, Large Masterwork", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Manacles (Masterwork/Huge)", category: EquipmentCategory::General, name: "Manacles, Huge Masterwork", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Mirror (Small/Steel)", category: EquipmentCategory::General, name: "Mirror", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Mug (Clay)", category: EquipmentCategory::General, name: "Mug, Clay", cost_gp: Some(0.02_f64) },
    EquipmentTableEntry { key: "Tankard", category: EquipmentCategory::General, name: "Mug (Clay)", cost_gp: None },
    EquipmentTableEntry { key: "Oil (1 Pint Flask)", category: EquipmentCategory::General, name: "Oil, 1 Pint Flask", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Paper (Sheet)", category: EquipmentCategory::General, name: "Paper (Sheet)", cost_gp: Some(0.4_f64) },
    EquipmentTableEntry { key: "Parchment (Sheet)", category: EquipmentCategory::General, name: "Parchment (Sheet)", cost_gp: Some(0.2_f64) },
    EquipmentTableEntry { key: "Pick (Miner's)", category: EquipmentCategory::General, name: "Pick, Miner's", cost_gp: Some(3_f64) },
    EquipmentTableEntry { key: "Pitcher (Clay)", category: EquipmentCategory::General, name: "Pitcher, Clay", cost_gp: Some(0.02_f64) },
    EquipmentTableEntry { key: "Piton", category: EquipmentCategory::General, name: "Piton", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Pole (10 ft)", category: EquipmentCategory::General, name: "Pole (10 ft.)", cost_gp: Some(0.05_f64) },
    EquipmentTableEntry { key: "Pot (Iron)", category: EquipmentCategory::General, name: "Pot, Iron", cost_gp: Some(0.8_f64) },
    EquipmentTableEntry { key: "Pouch (Belt)", category: EquipmentCategory::General, name: "Pouch, Belt", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Ram (Portable)", category: EquipmentCategory::General, name: "Ram, Portable", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Rations (Trail/Per Day)", category: EquipmentCategory::General, name: "Rations, Trail", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Rope (Hemp/50 ft)", category: EquipmentCategory::General, name: "Rope (50 ft.)", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Rope (Silk/50 ft)", category: EquipmentCategory::General, name: "Rope, Silk (50 ft.)", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Sack", category: EquipmentCategory::General, name: "Sack", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Sealing Wax", category: EquipmentCategory::General, name: "Sealing Wax", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Sewing Needle", category: EquipmentCategory::General, name: "Sewing Needle", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Shovel", category: EquipmentCategory::General, name: "Shovel", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Spade", category: EquipmentCategory::General, name: "Shovel", cost_gp: None },
    EquipmentTableEntry { key: "Signal Whistle", category: EquipmentCategory::General, name: "Signal Whistle", cost_gp: Some(0.8_f64) },
    EquipmentTableEntry { key: "Signet Ring", category: EquipmentCategory::General, name: "Signet Ring", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Sledge", category: EquipmentCategory::General, name: "Sledge", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Soap", category: EquipmentCategory::General, name: "Soap", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Spyglass", category: EquipmentCategory::General, name: "Spyglass", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Tent (Small)", category: EquipmentCategory::General, name: "Tent", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Torch", category: EquipmentCategory::General, name: "Torch", cost_gp: Some(0.01_f64) },
    EquipmentTableEntry { key: "Vial", category: EquipmentCategory::General, name: "Vial", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Water Clock", category: EquipmentCategory::General, name: "Water Clock", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Waterskin", category: EquipmentCategory::General, name: "Waterskin", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Waterskin (Filled)", category: EquipmentCategory::General, name: "Waterskin, Filled", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Whetstone", category: EquipmentCategory::General, name: "Whetstone", cost_gp: Some(0.02_f64) },
    EquipmentTableEntry { key: "Acid (Flask)", category: EquipmentCategory::General, name: "Acid", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Alchemist's Fire (Flask)", category: EquipmentCategory::General, name: "Alchemist's Fire", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Antitoxin (Vial)", category: EquipmentCategory::General, name: "Antitoxin", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Everburning Torch", category: EquipmentCategory::General, name: "Everburning Torch", cost_gp: Some(110_f64) },
    EquipmentTableEntry { key: "Holy Water (Flask)", category: EquipmentCategory::General, name: "Holy Water", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Smokestick", category: EquipmentCategory::General, name: "Smokestick", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Sunrod", category: EquipmentCategory::General, name: "Sunrod", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Tanglefoot Bag", category: EquipmentCategory::General, name: "Tanglefoot Bag", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Thunderstone", category: EquipmentCategory::General, name: "Thunderstone", cost_gp: Some(30_f64) },
    EquipmentTableEntry { key: "Tindertwig", category: EquipmentCategory::General, name: "Tindertwig", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Alchemist's Lab", category: EquipmentCategory::General, name: "Alchemist's Lab", cost_gp: Some(200_f64) },
    EquipmentTableEntry { key: "Artisan's Tools", category: EquipmentCategory::General, name: "Artisan's Tools", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Climber's Kit", category: EquipmentCategory::General, name: "Climber's Kit", cost_gp: Some(80_f64) },
    EquipmentTableEntry { key: "Disguise Kit", category: EquipmentCategory::General, name: "Disguise Kit", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Healer's Kit", category: EquipmentCategory::General, name: "Healer's Kit", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Holly and Mistletoe", category: EquipmentCategory::General, name: "Holly and Mistletoe", cost_gp: None },
    EquipmentTableEntry { key: "Holy Symbol", category: EquipmentCategory::General, name: "Holy Symbol", cost_gp: None },
    EquipmentTableEntry { key: "Holy Symbol (Wooden)", category: EquipmentCategory::General, name: "Holy Symbol", cost_gp: None },
    EquipmentTableEntry { key: "Holy Symbol (Silver)", category: EquipmentCategory::General, name: "Holy Symbol", cost_gp: None },
    EquipmentTableEntry { key: "Magnifying Glass", category: EquipmentCategory::General, name: "Magnifying Glass", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Musical Instrument (Harpsichord)", category: EquipmentCategory::General, name: "Harpsichord (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Piano)", category: EquipmentCategory::General, name: "Piano (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Pipe Organ)", category: EquipmentCategory::General, name: "Pipe Organ (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Bells)", category: EquipmentCategory::General, name: "Bells (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Chimes)", category: EquipmentCategory::General, name: "Chimes (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Drums)", category: EquipmentCategory::General, name: "Drums (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Gong)", category: EquipmentCategory::General, name: "Gong (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Fiddle)", category: EquipmentCategory::General, name: "Fiddle (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Harp)", category: EquipmentCategory::General, name: "Harp (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Lute)", category: EquipmentCategory::General, name: "Lute (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Mandolin)", category: EquipmentCategory::General, name: "Mandolin (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Flute)", category: EquipmentCategory::General, name: "Flute (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Pan Pipes)", category: EquipmentCategory::General, name: "Pan Pipes (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Recorder)", category: EquipmentCategory::General, name: "Recorder (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Musical Instrument (Trumpet)", category: EquipmentCategory::General, name: "Trumpet (Base)", cost_gp: None },
    EquipmentTableEntry { key: "Scale (Merchant's)", category: EquipmentCategory::General, name: "Scale, Merchant's", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Spell Component Pouch", category: EquipmentCategory::General, name: "Spell Component Pouch", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Spellbook", category: EquipmentCategory::General, name: "Spellbook", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Thieves' Tools", category: EquipmentCategory::General, name: "Thieves' Tools", cost_gp: Some(30_f64) },
    EquipmentTableEntry { key: "Unholy Symbol", category: EquipmentCategory::General, name: "Unholy Symbol", cost_gp: None },
    EquipmentTableEntry { key: "Harpsichord (Base)", category: EquipmentCategory::General, name: "Harpsichord", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Piano (Base)", category: EquipmentCategory::General, name: "Piano", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Pipe Organ (Base)", category: EquipmentCategory::General, name: "Pipe Organ", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Bells (Base)", category: EquipmentCategory::General, name: "Bells", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Chimes (Base)", category: EquipmentCategory::General, name: "Chimes", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Drums (Base)", category: EquipmentCategory::General, name: "Drums", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Gong (Base)", category: EquipmentCategory::General, name: "Gong", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Fiddle (Base)", category: EquipmentCategory::General, name: "Fiddle", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Harp (Base)", category: EquipmentCategory::General, name: "Harp", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Lute (Base)", category: EquipmentCategory::General, name: "Lute", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Mandolin (Base)", category: EquipmentCategory::General, name: "Mandolin", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Flute (Base)", category: EquipmentCategory::General, name: "Flute", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Pan Pipes (Base)", category: EquipmentCategory::General, name: "Pan Pipes", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Recorder (Base)", category: EquipmentCategory::General, name: "Recorder", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Trumpet (Base)", category: EquipmentCategory::General, name: "Trumpet", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Outfit (Artisan's)", category: EquipmentCategory::General, name: "Artisan's Outfit", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Vestments (Cleric's)", category: EquipmentCategory::General, name: "Cleric's Vestments", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Outfit (Cold-Weather)", category: EquipmentCategory::General, name: "Cold-Weather Outfit", cost_gp: Some(8_f64) },
    EquipmentTableEntry { key: "Outfit (Courtier's)", category: EquipmentCategory::General, name: "Courtier's Outfit", cost_gp: Some(30_f64) },
    EquipmentTableEntry { key: "Outfit (Entertainer's)", category: EquipmentCategory::General, name: "Entertainer's Outfit", cost_gp: Some(3_f64) },
    EquipmentTableEntry { key: "Outfit (Explorer's)", category: EquipmentCategory::General, name: "Explorer's Outfit", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Outfit (Monk's)", category: EquipmentCategory::General, name: "Monk's Outfit", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Outfit (Noble's)", category: EquipmentCategory::General, name: "Noble's Outfit", cost_gp: Some(75_f64) },
    EquipmentTableEntry { key: "Outfit (Peasant's)", category: EquipmentCategory::General, name: "Peasant's Outfit", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Outfit (Royal)", category: EquipmentCategory::General, name: "Royal Outfit", cost_gp: Some(200_f64) },
    EquipmentTableEntry { key: "Outfit (Scholar's)", category: EquipmentCategory::General, name: "Scholar's Outfit", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Outfit (Traveler's)", category: EquipmentCategory::General, name: "Traveler's Outfit", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Ale (Gallon)", category: EquipmentCategory::General, name: "Gallon of Ale", cost_gp: Some(0.2_f64) },
    EquipmentTableEntry { key: "Ale (Mug)", category: EquipmentCategory::General, name: "Mug of Ale", cost_gp: Some(0.04_f64) },
    EquipmentTableEntry { key: "Banquet (Per Person)", category: EquipmentCategory::General, name: "Banquet, Per Person", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Bread (Loaf)", category: EquipmentCategory::General, name: "Loaf of Bread", cost_gp: Some(0.02_f64) },
    EquipmentTableEntry { key: "Cheese (Hunk)", category: EquipmentCategory::General, name: "Hunk of Cheese", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Inn (Good/Per Day)", category: EquipmentCategory::General, name: "Inn Stay, Per Day (Good)", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Inn (Common/Per Day)", category: EquipmentCategory::General, name: "Inn Stay, Per Day (Common)", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Inn (Poor/Per Day)", category: EquipmentCategory::General, name: "Inn Stay, Per Day (Poor)", cost_gp: Some(0.2_f64) },
    EquipmentTableEntry { key: "Meals (Good/Per Day)", category: EquipmentCategory::General, name: "Meal, Per Day (Good)", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Meals (Common/Per Day)", category: EquipmentCategory::General, name: "Meal, Per Day (Common)", cost_gp: Some(0.3_f64) },
    EquipmentTableEntry { key: "Meals (Poor/Per Day)", category: EquipmentCategory::General, name: "Meal, Per Day (Poor)", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Meat (Chunk)", category: EquipmentCategory::General, name: "Chunk of Meat", cost_gp: Some(0.3_f64) },
    EquipmentTableEntry { key: "Wine (Common/Pitcher)", category: EquipmentCategory::General, name: "Pitcher of Wine", cost_gp: Some(0.2_f64) },
    EquipmentTableEntry { key: "Wine (Fine/Bottle)", category: EquipmentCategory::General, name: "Bottle of Fine Wine", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Bit and Bridle", category: EquipmentCategory::General, name: "Bit and Bridle", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Dog (Guard)", category: EquipmentCategory::General, name: "Dog, Guard", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Dog (Riding)", category: EquipmentCategory::General, name: "Dog, Riding", cost_gp: Some(150_f64) },
    EquipmentTableEntry { key: "Donkey", category: EquipmentCategory::General, name: "Donkey", cost_gp: Some(8_f64) },
    EquipmentTableEntry { key: "Mule", category: EquipmentCategory::General, name: "Donkey", cost_gp: None },
    EquipmentTableEntry { key: "Feed (Per Day)", category: EquipmentCategory::General, name: "Feed", cost_gp: Some(0.05_f64) },
    EquipmentTableEntry { key: "Horse (Heavy)", category: EquipmentCategory::General, name: "Heavy Horse", cost_gp: Some(200_f64) },
    EquipmentTableEntry { key: "Horse (Heavy/Combat Trained)", category: EquipmentCategory::General, name: "Heavy Horse (Combat Trained)", cost_gp: Some(300_f64) },
    EquipmentTableEntry { key: "Horse (Light)", category: EquipmentCategory::General, name: "Light Horse", cost_gp: Some(75_f64) },
    EquipmentTableEntry { key: "Horse (Light/Combat Trained)", category: EquipmentCategory::General, name: "Light Horse (Combat Trained)", cost_gp: Some(110_f64) },
    EquipmentTableEntry { key: "Pony", category: EquipmentCategory::General, name: "Pony", cost_gp: Some(30_f64) },
    EquipmentTableEntry { key: "Pony (Combat Trained)", category: EquipmentCategory::General, name: "Pony (Combat Trained)", cost_gp: Some(45_f64) },
    EquipmentTableEntry { key: "Saddle (Military)", category: EquipmentCategory::General, name: "Saddle, Military", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Saddle (Pack)", category: EquipmentCategory::General, name: "Saddle, Pack", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Saddle (Riding)", category: EquipmentCategory::General, name: "Saddle, Riding", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Saddle (Exotic/Military)", category: EquipmentCategory::General, name: "Saddle, Exotic Military", cost_gp: Some(60_f64) },
    EquipmentTableEntry { key: "Saddle (Exotic/Pack)", category: EquipmentCategory::General, name: "Saddle, Exotic Pack", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Saddle (Exotic/Riding)", category: EquipmentCategory::General, name: "Saddle, Exotic Riding", cost_gp: Some(30_f64) },
    EquipmentTableEntry { key: "Saddlebags", category: EquipmentCategory::General, name: "Saddlebags", cost_gp: Some(4_f64) },
    EquipmentTableEntry { key: "Stabling (Per Day)", category: EquipmentCategory::General, name: "Stabling, Per Day", cost_gp: Some(0.5_f64) },
    EquipmentTableEntry { key: "Carriage", category: EquipmentCategory::General, name: "Carriage", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Cart", category: EquipmentCategory::General, name: "Cart", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Galley", category: EquipmentCategory::General, name: "Galley", cost_gp: Some(30000_f64) },
    EquipmentTableEntry { key: "Keelboat", category: EquipmentCategory::General, name: "Keelboat", cost_gp: Some(3000_f64) },
    EquipmentTableEntry { key: "Longship", category: EquipmentCategory::General, name: "Longship", cost_gp: Some(10000_f64) },
    EquipmentTableEntry { key: "Rowboat", category: EquipmentCategory::General, name: "Rowboat", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Oar", category: EquipmentCategory::General, name: "Oar", cost_gp: Some(2_f64) },
    EquipmentTableEntry { key: "Sailing Ship", category: EquipmentCategory::General, name: "Sailing Ship", cost_gp: Some(10000_f64) },
    EquipmentTableEntry { key: "Sled", category: EquipmentCategory::General, name: "Sled", cost_gp: Some(20_f64) },
    EquipmentTableEntry { key: "Wagon", category: EquipmentCategory::General, name: "Wagon", cost_gp: Some(35_f64) },
    EquipmentTableEntry { key: "Warship", category: EquipmentCategory::General, name: "Warship", cost_gp: Some(25000_f64) },
    EquipmentTableEntry { key: "Coach Cab (Per Mile)", category: EquipmentCategory::General, name: "Coach Cab, Per Mile", cost_gp: Some(0.03_f64) },
    EquipmentTableEntry { key: "Hireling (Trained)", category: EquipmentCategory::General, name: "Trained Hireling, Per Day", cost_gp: Some(0.3_f64) },
    EquipmentTableEntry { key: "Hireling (Untrained)", category: EquipmentCategory::General, name: "Untrained Hireling, Per Day", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Messenger (Per Mile)", category: EquipmentCategory::General, name: "Messenger, Per Mile", cost_gp: Some(0.02_f64) },
    EquipmentTableEntry { key: "Road or Gate Toll", category: EquipmentCategory::General, name: "Road or Gate Toll", cost_gp: Some(0.01_f64) },
    EquipmentTableEntry { key: "Ship's Passage (Per Mile)", category: EquipmentCategory::General, name: "Ship's Passage, Per Mile", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Coin (Copper Piece)", category: EquipmentCategory::General, name: "Copper Piece", cost_gp: Some(0.01_f64) },
    EquipmentTableEntry { key: "Coin (Silver Piece)", category: EquipmentCategory::General, name: "Silver Piece", cost_gp: Some(0.1_f64) },
    EquipmentTableEntry { key: "Coin (Gold Piece)", category: EquipmentCategory::General, name: "Gold Piece", cost_gp: Some(1_f64) },
    EquipmentTableEntry { key: "Coin (Platinum Piece)", category: EquipmentCategory::General, name: "Platinum Piece", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Agate", category: EquipmentCategory::General, name: "Agate", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Azurite", category: EquipmentCategory::General, name: "Azurite", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Quartz (Blue)", category: EquipmentCategory::General, name: "Quartz, Blue", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Hematite", category: EquipmentCategory::General, name: "Hematite", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Lapis Lazuli", category: EquipmentCategory::General, name: "Lapis Lazuli", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Malachite", category: EquipmentCategory::General, name: "Malachite", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Obsidian", category: EquipmentCategory::General, name: "Obsidian", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Rhodochrosite", category: EquipmentCategory::General, name: "Rhodochrosite", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Tigereye", category: EquipmentCategory::General, name: "Tigereye", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Turquoise", category: EquipmentCategory::General, name: "Turquoise", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Pearl (Freshwater/Irregular)", category: EquipmentCategory::General, name: "Irregular Freshwater Pearl", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Bloodstone", category: EquipmentCategory::General, name: "Bloodstone", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Carnelian", category: EquipmentCategory::General, name: "Carnelian", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Chalcedony", category: EquipmentCategory::General, name: "Chalcedony", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Chrysoprase", category: EquipmentCategory::General, name: "Chrysoprase", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Citrine", category: EquipmentCategory::General, name: "Citrine", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Jasper", category: EquipmentCategory::General, name: "Jasper", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Moonstone", category: EquipmentCategory::General, name: "Moonstone", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Onyx", category: EquipmentCategory::General, name: "Onyx", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Peridot", category: EquipmentCategory::General, name: "Peridot", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Rock Crystal (Clear Quartz)", category: EquipmentCategory::General, name: "Rock Crystal (Clear Quartz)", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Sard", category: EquipmentCategory::General, name: "Sard", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Sardonyx", category: EquipmentCategory::General, name: "Sardonyx", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Quartz (Rose)", category: EquipmentCategory::General, name: "Rose Quartz", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Quartz (Smoky)", category: EquipmentCategory::General, name: "Smoky Quartz", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Quartz (Star Rose)", category: EquipmentCategory::General, name: "Star Rose Quartz", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Zircon", category: EquipmentCategory::General, name: "Zircon", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Amber", category: EquipmentCategory::General, name: "Amber", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Amethyst", category: EquipmentCategory::General, name: "Amethyst", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Chrysoberyl", category: EquipmentCategory::General, name: "Chrysoberyl", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Coral", category: EquipmentCategory::General, name: "Coral", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Garnet (Red)", category: EquipmentCategory::General, name: "Red Garnet", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Garnet (Brown-Green)", category: EquipmentCategory::General, name: "Brown-Green Garnet", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Jade", category: EquipmentCategory::General, name: "Jade", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Jet", category: EquipmentCategory::General, name: "Jet", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Pearl (White)", category: EquipmentCategory::General, name: "White Pearl", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Pearl (Golden)", category: EquipmentCategory::General, name: "Golden Pearl", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Pearl (Pink)", category: EquipmentCategory::General, name: "Pink Pearl", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Pearl (Silver)", category: EquipmentCategory::General, name: "Silver Pearl", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Spinel (Red)", category: EquipmentCategory::General, name: "Red Spinel", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Spinel (Red-Brown)", category: EquipmentCategory::General, name: "Red-Brown Spinel", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Spinel (Deep Green)", category: EquipmentCategory::General, name: "Deep Green Spinel", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Tourmaline", category: EquipmentCategory::General, name: "Tourmaline", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Alexandrite", category: EquipmentCategory::General, name: "Alexandrite", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Aquamarine", category: EquipmentCategory::General, name: "Aquamarine", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Garnet (Violet)", category: EquipmentCategory::General, name: "Violet Garnet", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Pearl (Black)", category: EquipmentCategory::General, name: "Black Pearl", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Spinel (Deep Blue)", category: EquipmentCategory::General, name: "Deep Blue Spinel", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Topaz (Golden Yellow)", category: EquipmentCategory::General, name: "Golden Yellow Topaz", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Emerald", category: EquipmentCategory::General, name: "Emerald", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Opal (White)", category: EquipmentCategory::General, name: "White Opal", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Opal (Black)", category: EquipmentCategory::General, name: "Black Opal", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Opal (Fire)", category: EquipmentCategory::General, name: "Fire Opal", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Sapphire (Blue)", category: EquipmentCategory::General, name: "Blue Sapphire", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Corundum (Fiery Yellow)", category: EquipmentCategory::General, name: "Fiery Yellow Corundum", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Corundum (Rich Purple)", category: EquipmentCategory::General, name: "Rich Purple Corundum", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Star Sapphire (Blue)", category: EquipmentCategory::General, name: "Blue Star Sapphire", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Star Sapphire (Black)", category: EquipmentCategory::General, name: "Black Star Sapphire", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Emerald (Clearest Bright Green)", category: EquipmentCategory::General, name: "Clearest Bright Green Emerald", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Diamond", category: EquipmentCategory::General, name: "Diamond", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Jacinth", category: EquipmentCategory::General, name: "Jacinth", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Ruby", category: EquipmentCategory::General, name: "Ruby", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Amber Dust (1000 gp)", category: EquipmentCategory::General, name: "Amber Dust (worth 1,000 gp)", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Crushed Black Pearl (500 gp)", category: EquipmentCategory::General, name: "Crushed Black Pearl (worth 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Crushed Jade (250 gp)", category: EquipmentCategory::General, name: "Crushed Jade (worth 250 gp)", cost_gp: Some(250_f64) },
    EquipmentTableEntry { key: "Crushed Pearls (1500 gp)", category: EquipmentCategory::General, name: "Crushed Pearls (worth 1,500 gp)", cost_gp: Some(1500_f64) },
    EquipmentTableEntry { key: "Diamond (1000 gp)", category: EquipmentCategory::General, name: "Diamond (worth 1,000 gp)", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Diamond (10000 gp)", category: EquipmentCategory::General, name: "Diamond (worth 10,000 gp)", cost_gp: Some(10000_f64) },
    EquipmentTableEntry { key: "Diamond (1500 gp)", category: EquipmentCategory::General, name: "Diamond (worth 1,500 gp)", cost_gp: Some(1500_f64) },
    EquipmentTableEntry { key: "Diamond (25000 gp)", category: EquipmentCategory::General, name: "Diamond (worth 25,000 gp)", cost_gp: Some(25000_f64) },
    EquipmentTableEntry { key: "Diamond (500 gp)", category: EquipmentCategory::General, name: "Diamond (worth 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Diamond (5000 gp)", category: EquipmentCategory::General, name: "Diamond (worth 5,000 gp)", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Diamond Dust (100 gp)", category: EquipmentCategory::General, name: "Diamond Dust (worth 100 gp)", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Diamond Dust (1000 gp)", category: EquipmentCategory::General, name: "Diamond Dust (worth 1,000 gp)", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Diamond Dust (200 gp)", category: EquipmentCategory::General, name: "Diamond Dust (worth 200 gp)", cost_gp: Some(200_f64) },
    EquipmentTableEntry { key: "Diamond Dust (250 gp)", category: EquipmentCategory::General, name: "Diamond Dust (worth 250 gp)", cost_gp: Some(250_f64) },
    EquipmentTableEntry { key: "Diamond Dust (25000 gp)", category: EquipmentCategory::General, name: "Diamond Dust (worth 25,000 gp)", cost_gp: Some(25000_f64) },
    EquipmentTableEntry { key: "Diamond Dust (50 gp)", category: EquipmentCategory::General, name: "Diamond Dust (worth 50 gp)", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Diamond Dust (500 gp)", category: EquipmentCategory::General, name: "Diamond Dust (worth 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Diamond Dust (5000 gp)", category: EquipmentCategory::General, name: "Diamond Dust (worth 5,000 gp)", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod", category: EquipmentCategory::General, name: "Forked Metal Rod", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Abyss)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Abyss", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Astral Plane)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Astral Plane", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Elysium)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to Elysium", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Ethereal Plane)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Ethereal Plane", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Heaven)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to Heaven", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Hell)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to Hell", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Material Plane)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Material Plane", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Negative Energy Plane)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Negative Energy Plane", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Plane of Air)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Plane of Air", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Plane of Earth)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Plane of Earth", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Plane of Fire)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Plane of Fire", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Plane of Water)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Plane of Water", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Positive Energy Plane)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Positive Energy Plane", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Forked Metal Rod (Shadow Plane)", category: EquipmentCategory::General, name: "Forked Metal Rod, attuned to the Shadow Plane", cost_gp: Some(0_f64) },
    EquipmentTableEntry { key: "Gem Dust (5000 gp)", category: EquipmentCategory::General, name: "Powdered Diamond, Emerald, Ruby, and Sapphire Dust (worth 5,000 gp)", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Gold Dust (25 gp)", category: EquipmentCategory::General, name: "Gold Dust (worth 25 gp)", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Gold Dust (50 gp)", category: EquipmentCategory::General, name: "Gold Dust (worth 50 gp)", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Herbs and Oils (2000 gp)", category: EquipmentCategory::General, name: "Herbs and Oils (worth 2,000 gp)", cost_gp: Some(2000_f64) },
    EquipmentTableEntry { key: "Herbs Oils and Incense (1000 gp)", category: EquipmentCategory::General, name: "Herbs, Oils, and Incense (worth 1,000 gp)", cost_gp: Some(2000_f64) },
    EquipmentTableEntry { key: "Incense (1500 gp)", category: EquipmentCategory::General, name: "Incense (worth 1,500 gp)", cost_gp: Some(1500_f64) },
    EquipmentTableEntry { key: "Incense (25 gp)", category: EquipmentCategory::General, name: "Incense (worth 25 gp)", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Incense (250 gp)", category: EquipmentCategory::General, name: "Incense (worth 250 gp)", cost_gp: Some(250_f64) },
    EquipmentTableEntry { key: "Incense (500 gp)", category: EquipmentCategory::General, name: "Incense (worth 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Ivory Plaque (50 gp)", category: EquipmentCategory::General, name: "Ivory Plaque (worth 50 gp)", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Ivory Statuette of Self (1500 gp)", category: EquipmentCategory::General, name: "Ivory Statuette of Self (worth 1,500 gp)", cost_gp: Some(1500_f64) },
    EquipmentTableEntry { key: "Jacinth (1000 gp)", category: EquipmentCategory::General, name: "Jacinth (worth 1,000 gp)", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Jade Circlet (1500 gp)", category: EquipmentCategory::General, name: "Jade Circlet (worth 1,500 gp)", cost_gp: Some(1500_f64) },
    EquipmentTableEntry { key: "Jade Dust (10 gp)", category: EquipmentCategory::General, name: "Jade Dust (worth 10 gp)", cost_gp: Some(10_f64) },
    EquipmentTableEntry { key: "Jade Dust (25 gp)", category: EquipmentCategory::General, name: "Jade Dust (worth 25 gp)", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Laboratory Equipment (500 gp)", category: EquipmentCategory::General, name: "Laboratory Equipment (costing 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Laboratory Supplies (1000 gp)", category: EquipmentCategory::General, name: "Laboratory Supplies (worth 1,000 gp)", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Lead-Based Ink (50 gp)", category: EquipmentCategory::General, name: "Lead-Based Ink (worth 50 gp)", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Miniature Ivory Door (5 gp)", category: EquipmentCategory::General, name: "Miniature Ivory Door (worth 5 gp)", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Miniature Platinum Sword (250 gp)", category: EquipmentCategory::General, name: "Miniature Platinum Sword (worth 250 gp)", cost_gp: Some(250_f64) },
    EquipmentTableEntry { key: "Oils (1000 gp)", category: EquipmentCategory::General, name: "Oils (worth 1,000 gp)", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Ointment (250 gp)", category: EquipmentCategory::General, name: "Ointment (worth 250 gp)", cost_gp: Some(250_f64) },
    EquipmentTableEntry { key: "Onyx (25 gp)", category: EquipmentCategory::General, name: "Onyx Gem (worth 25 gp)", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Onyx (50 gp)", category: EquipmentCategory::General, name: "Onyx Gem (worth 50 gp)", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Opal (500 gp)", category: EquipmentCategory::General, name: "Opal (worth 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Pair of Canine Statuettes (50 gp)", category: EquipmentCategory::General, name: "Pair of Canine Statuettes (worth 50 gp)", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Platinum Ring (50 gp)", category: EquipmentCategory::General, name: "Platinum Ring (worth 50 gp)", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Polished Marble (5 gp)", category: EquipmentCategory::General, name: "Polished Marble (worth 5 gp)", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Powdered Amber (500 gp)", category: EquipmentCategory::General, name: "Powdered Amber (worth 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Powdered Diamond (200 gp)", category: EquipmentCategory::General, name: "Powdered Diamond (worth 200 gp)", cost_gp: Some(200_f64) },
    EquipmentTableEntry { key: "Powdered Diamond (400 gp)", category: EquipmentCategory::General, name: "Powdered Diamond (worth 400 gp)", cost_gp: Some(400_f64) },
    EquipmentTableEntry { key: "Powdered Diamond (5000 gp)", category: EquipmentCategory::General, name: "Powdered Diamond (worth 5,000 gp)", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Powdered Diamond and Opal (1000 gp)", category: EquipmentCategory::General, name: "Powdered Diamond and Opal (worth 1,000 gp)", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Powdered Diamond and Opal (5000 gp)", category: EquipmentCategory::General, name: "Powdered Diamond and Opal (worth 5,000 gp)", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Powdered Opal (5000 gp)", category: EquipmentCategory::General, name: "Powdered Opal (worth 5,000 gp)", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Powdered Ruby (500 gp)", category: EquipmentCategory::General, name: "Powdered Ruby (worth 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Powdered Silver (25 gp)", category: EquipmentCategory::General, name: "Powdered Silver (worth 25 gp)", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Ruby Dust (50 gp)", category: EquipmentCategory::General, name: "Ruby Dust (worth 50 gp)", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Ruby Dust (500 gp)", category: EquipmentCategory::General, name: "Ruby Dust (worth 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Sapphire (1000 gp)", category: EquipmentCategory::General, name: "Sapphire (worth 1,000 gp)", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Set of 4 Pieces of Ivory (200 gp)", category: EquipmentCategory::General, name: "Set of 4 Pieces of Ivory (worth 50 gp each)", cost_gp: Some(200_f64) },
    EquipmentTableEntry { key: "Set of Marked Bones (25 gp)", category: EquipmentCategory::General, name: "Set of Marked Bones (worth 25 gp)", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Set of Minature Items (15 gp)", category: EquipmentCategory::General, name: "Set of Minature Items (worth 15 gp)", cost_gp: Some(15_f64) },
    EquipmentTableEntry { key: "Set of Prayer Beads (500 gp)", category: EquipmentCategory::General, name: "Set of Prayer Beads (worth 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Silver Dust (25 gp)", category: EquipmentCategory::General, name: "Silver Dust (worth 25 gp)", cost_gp: Some(25_f64) },
    EquipmentTableEntry { key: "Silver Mirror (1000 gp)", category: EquipmentCategory::General, name: "Silver Mirror (worth 1,000 gp)", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Silver Spoon (5 gp)", category: EquipmentCategory::General, name: "Silver Spoon (worth 5 gp)", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Small Replica of Self (5 gp)", category: EquipmentCategory::General, name: "Small Replica of Self (worth 5 gp)", cost_gp: Some(5_f64) },
    EquipmentTableEntry { key: "Special Dust (50 gp)", category: EquipmentCategory::General, name: "Special Dust (worth 50 gp)", cost_gp: Some(50_f64) },
    EquipmentTableEntry { key: "Tiny Reliquary (500 gp)", category: EquipmentCategory::General, name: "Tiny Reliquary (worth 500 gp)", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Poison (Arsenic)", category: EquipmentCategory::General, name: "Poison, Arsenic", cost_gp: Some(120_f64) },
    EquipmentTableEntry { key: "Poison (Belladonna)", category: EquipmentCategory::General, name: "Poison, Belladonna", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Poison (Black Adder Venom)", category: EquipmentCategory::General, name: "Poison, Black Adder Venom", cost_gp: Some(120_f64) },
    EquipmentTableEntry { key: "Poison (Black Lotus Extract)", category: EquipmentCategory::General, name: "Poison, Black Lotus Extract", cost_gp: Some(4500_f64) },
    EquipmentTableEntry { key: "Poison (Bloodroot)", category: EquipmentCategory::General, name: "Poison, Bloodroot", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Poison (Blue Whinnis)", category: EquipmentCategory::General, name: "Poison, Blue Whinnis", cost_gp: Some(120_f64) },
    EquipmentTableEntry { key: "Poison (Burnt Othur Fumes)", category: EquipmentCategory::General, name: "Poison, Burnt Othur Fumes", cost_gp: Some(2100_f64) },
    EquipmentTableEntry { key: "Poison (Dark Reaver Powder)", category: EquipmentCategory::General, name: "Poison, Dark Reaver Powder", cost_gp: Some(800_f64) },
    EquipmentTableEntry { key: "Poison (Deathblade)", category: EquipmentCategory::General, name: "Poison, Deathblade", cost_gp: Some(1800_f64) },
    EquipmentTableEntry { key: "Poison (Dragon Bile)", category: EquipmentCategory::General, name: "Poison, Dragon Bile", cost_gp: Some(1500_f64) },
    EquipmentTableEntry { key: "Poison (Drow Poison)", category: EquipmentCategory::General, name: "Poison, Drow Poison", cost_gp: Some(75_f64) },
    EquipmentTableEntry { key: "Poison (Giant Wasp Poison)", category: EquipmentCategory::General, name: "Poison, Giant Wasp Poison", cost_gp: Some(210_f64) },
    EquipmentTableEntry { key: "Poison (Greenblood Oil)", category: EquipmentCategory::General, name: "Poison, Greenblood Oil", cost_gp: Some(100_f64) },
    EquipmentTableEntry { key: "Poison (Hemlock)", category: EquipmentCategory::General, name: "Poison, Hemlock", cost_gp: Some(2500_f64) },
    EquipmentTableEntry { key: "Poison (Id Moss)", category: EquipmentCategory::General, name: "Poison, Id Moss", cost_gp: Some(125_f64) },
    EquipmentTableEntry { key: "Poison (Insanity Mist)", category: EquipmentCategory::General, name: "Poison, Insanity Mist", cost_gp: Some(1500_f64) },
    EquipmentTableEntry { key: "Poison (King's Sleep)", category: EquipmentCategory::General, name: "Poison, King's Sleep", cost_gp: Some(5000_f64) },
    EquipmentTableEntry { key: "Poison (Large Scorpion Venom)", category: EquipmentCategory::General, name: "Poison, Large Scorpion Venom", cost_gp: Some(200_f64) },
    EquipmentTableEntry { key: "Poison (Lich Dust)", category: EquipmentCategory::General, name: "Poison, Lich Dust", cost_gp: Some(400_f64) },
    EquipmentTableEntry { key: "Poison (Malyass Root Paste)", category: EquipmentCategory::General, name: "Poison, Malyass Root Paste", cost_gp: Some(250_f64) },
    EquipmentTableEntry { key: "Poison (Medium Spider Venom)", category: EquipmentCategory::General, name: "Poison, Medium Spider Venom", cost_gp: Some(150_f64) },
    EquipmentTableEntry { key: "Poison (Nightmare Vapor)", category: EquipmentCategory::General, name: "Poison, Nightmare Vapor", cost_gp: Some(1800_f64) },
    EquipmentTableEntry { key: "Poison (Nitharit)", category: EquipmentCategory::General, name: "Poison, Nitharit", cost_gp: Some(650_f64) },
    EquipmentTableEntry { key: "Poison (Oil of Taggit)", category: EquipmentCategory::General, name: "Poison, Oil of Taggit", cost_gp: Some(90_f64) },
    EquipmentTableEntry { key: "Poison (Purple Worm Poison)", category: EquipmentCategory::General, name: "Poison, Purple Worm Poison", cost_gp: Some(700_f64) },
    EquipmentTableEntry { key: "Poison (Sassone Leaf Residue)", category: EquipmentCategory::General, name: "Poison, Sassone Leaf Residue", cost_gp: Some(300_f64) },
    EquipmentTableEntry { key: "Poison (Shadow Essence)", category: EquipmentCategory::General, name: "Poison, Shadow Essence", cost_gp: Some(250_f64) },
    EquipmentTableEntry { key: "Poison (Small Centipede Poison)", category: EquipmentCategory::General, name: "Poison, Small Centipede Poison", cost_gp: Some(90_f64) },
    EquipmentTableEntry { key: "Poison (Striped Toadstool)", category: EquipmentCategory::General, name: "Poison, Striped Toadstool", cost_gp: Some(180_f64) },
    EquipmentTableEntry { key: "Poison (Tears of Death)", category: EquipmentCategory::General, name: "Poison, Tears of Death", cost_gp: Some(6500_f64) },
    EquipmentTableEntry { key: "Poison (Terinav Root)", category: EquipmentCategory::General, name: "Poison, Terinav Root", cost_gp: Some(400_f64) },
    EquipmentTableEntry { key: "Poison (Ungol Dust)", category: EquipmentCategory::General, name: "Poison, Ungol Dust", cost_gp: Some(1000_f64) },
    EquipmentTableEntry { key: "Poison (Wolfsbane)", category: EquipmentCategory::General, name: "Poison, Wolfsbane", cost_gp: Some(500_f64) },
    EquipmentTableEntry { key: "Poison (Wyvern Poison)", category: EquipmentCategory::General, name: "Poison, Wyvern Poison", cost_gp: Some(3000_f64) },
];
