//! Package-backed mirror of the compiled `rules_tables` module `occult_adventures::kineticist_features` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::occult_adventures::kineticist_features::burn_max_points;
pub use rt::occult_adventures::kineticist_features::elemental_focus_level_base;
pub use rt::occult_adventures::kineticist_features::expanded_element_pool;
pub use rt::occult_adventures::kineticist_features::infusion_pool;
pub use rt::occult_adventures::kineticist_features::kinetic_blast_range_feet;
pub use rt::occult_adventures::kineticist_features::wild_talents_dc;
