//! Package-backed mirror of the compiled `rules_tables` module `occult_adventures::medium_features` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use rt::occult_adventures::medium_features::ask_the_spirits_dc;
pub use rt::occult_adventures::medium_features::astral_journey_dc;
pub use rt::occult_adventures::medium_features::haunt_channeler_dc;
pub use rt::occult_adventures::medium_features::haunt_channeler_dice;
pub use rt::occult_adventures::medium_features::location_channel_dc;
pub use rt::occult_adventures::medium_features::location_channel_duration_rounds;
pub use rt::occult_adventures::medium_features::spirit_bonus;
pub use rt::occult_adventures::medium_features::spirit_surge_dice;
pub use rt::occult_adventures::medium_features::trance_of_three_duration_rounds;
