//! Package-backed mirror of the compiled `rules_tables` module `occult_adventures` (SD-37 E4a.2; generated by `artifacts/epic_4a/E4a.2_gen_catalog/gen_catalog.py`).
#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    clippy::explicit_auto_deref,
    clippy::needless_borrow,
    clippy::type_complexity
)]
use crate::rules_core::rules_tables as rt;

pub use super::monster_chassis::{
    MonsterAbilityDelivery, MonsterAbilityFacet, MonsterAbilityRecord, MonsterStatBlock,
};
pub mod kineticist_features;
pub mod medium_features;
pub mod mesmerist_features;
pub(crate) mod monster_data;
pub mod occultist_features;
pub mod psychic_features;
pub mod spell_list;
pub mod spiritualist_features;
pub fn monsters_static() -> &'static [MonsterStatBlock] {
    &*monster_data::MONSTERS
}
pub fn monster_abilities_static() -> &'static [MonsterAbilityRecord] {
    &*monster_data::MONSTER_ABILITIES
}
